### ISSUE TITLE
can you add OpenDingux

### ISSUE THREAD

**Issue by Cibomatto2002** [libretro/mame2003-plus-libretro#1016]
can you add OpenDingux? i would love to have this emulator on my pocket go 2v2 it's a RG 350 clone.  I know it would be slow on most games but it would be ok for games like pac-man and so on.

**Comment by mahoneyt944** [comment]
I will look into it.

**Comment by Cibomatto2002** [comment]
Thank you !!

**Comment by mahoneyt944** [comment]
@Cibomatto2002 good news I was able to get OpenDingux to build. It will show up in the nightly builds before too long. Let me know what your experience is with this core. I'll also be adding mame2003 support for dingux as well soon.

**Comment by Cibomatto2002** [comment]
I will report back. Thanks again.

**Comment by mahoneyt944** [comment]
also, if you don't want to wait for the nightly builds page to catch up, you can download this new binary directly from here https://git.libretro.com/libretro/mame2003-plus-libretro/-/pipelines/19486

**Comment by Cibomatto2002** [comment]
It works but when the game loads it will look like retroarch is froze but it just takes time to load pac- man plays fine frogger plays fine bubble bobble is a little slow neo Geo games are alittle slow but not to bad do you know a setting that could speed it up? Anyway I'm enjoying this emulator on my pocket go 2 v2 thanks again.

**Comment by Cibomatto2002** [comment]
Is mame2003 faster than mame2003 plus?

**Comment by mahoneyt944** [comment]
They are very comparible in performance. Mame is just a demanding core. @arcadez2003 what do you think about trying cyclone with this core?

**Comment by Cibomatto2002** [comment]
I will try it. Will it work with my mame2003 plus ROMs or will I have to download new ones and if so what set do I need?

**Comment by mahoneyt944** [comment]
Mame2003 and mame2003-plus share a lot of roms and many will work in both but there are some that are different. These "romsets" are available if your search for them. I can't link you any sources for roms however.

**Comment by mahoneyt944** [comment]
Building romsets with clrmamepro is the best way to get a working set for any core. Plenty of tutorials out there for that.

**Comment by Cibomatto2002** [comment]
Thanks for telling me about clrmamepro I have lots of ROMs for both mame2003 and mame 2003 plus Im enjoying mame 2003 plus on my pocket go 2 v2.

**Comment by arcadez2003** [comment]
> 
> 
> They are very comparible in performance. Mame is just a demanding core. @arcadez2003 what do you think about trying cyclone with this core?
> 
> .

Dont we have it as an option that users can turn on or off.?? i mean i wouldn't like cyclone versions of the M68k and or 
the Z80 to be on as default in this core for a couple of reasons really, the first being that most devices using MAME2003
will not need the performance boost anyway and secondly the cyclone cores have been known to be buggy and cause 
more problems than they're worth.

The cyclone should only really be used if you have no option otherwise

**Comment by mahoneyt944** [comment]
There's not a core option, just a flag for it in the make file. Maybe it should be a core option so users don't have to compile custom builds to use it or at least try it.

**Comment by arcadez2003** [comment]
Sure a core option would be fine but i would suggest we turn it off by default, and add info to the documentation so users
would know they have the option of using the cyclone should they require it

**Comment by mahoneyt944** [comment]
Yeah, I agree. I'll have to look into it.

**Comment by Cibomatto2002** [comment]
what does the cyclone do? There needs to be a way for people with slower handhelds to know there game is loading and not crashing RetroArch like add a progress of the game loading maybe something like 10% 20% and so on.

**Comment by mahoneyt944** [comment]
A progress bar maybe possible but most users wouldn't want that. If a developer would want to work on this, it would have to be implemented in a optional way. I'll keep it in mind though for a rainy day project. Closing this now as the primary issue was resolved.
