### ISSUE TITLE
Support the Korean version of Tant-R and Ichidant-R?

### ISSUE THREAD

**Issue by litaniast** [libretro/mame2003-plus-libretro#1033]
Of course mame2003-plus has original Japanese version of them, but they dumped after the release of MAME 0.78 so current mame2003-plus doesn't support them.

So many Koreans use either Japanese version of these games, or installing lr-mame2010 on their pi4 for playing them.

Is it difficult for support that clones on mame2003-plus?

**Comment by arcadez2003** [comment]
They will likely just drop in i'll look into adding them later

**Comment by arcadez2003** [comment]
@litaniast Here ya go test em and lemmie know if everything is good..........

https://github.com/libretro/mame2003-plus-libretro/commit/d23434c38efb8d44f232c60c7a823d2440aa0042

**Comment by mahoneyt944** [comment]
Tested all 8 romsets, all are working.

**Comment by arcadez2003** [comment]
That was nice of ya :)

**Comment by litaniast** [comment]
Updated and both of them work well. Thanks a lot!
