### ISSUE TITLE
What does warnings flagged during rom loading mean?

### ISSUE THREAD

**Issue by Cibomatto2002** [libretro/mame2003-plus-libretro#1041]
What does warnings flagged during rom loading mean?  so far I to games say it in my list Metal Slug 4 and the king of fighters 2001.

Windows 10 

![1](https://user-images.githubusercontent.com/21169038/116764253-28fa5a00-a9e6-11eb-8ff3-14d9bf2e0347.jpg)

**Comment by mahoneyt944** [comment]
This means there were issues when loading the rom. You could be using the wrong romset. Verify your rom's checksums. You could be missing a bios file too.

**Comment by Cibomatto2002** [comment]
ok thanks I will go look for another set thanks alot. :)  after that screen goes away the game will play.

**Comment by mahoneyt944** [comment]
I'll check more into it too. There's been updates to neogeo not too long ago.

**Comment by Cibomatto2002** [comment]
ok thanks

**Comment by mahoneyt944** [comment]
Looks like 263-m1.bin has a new checksum.

**Comment by mahoneyt944** [comment]
Here's the new checksum you'll need
```
NEO_BIOS_AUDIO_ENCRYPTED_128K( "263-m1.bin", CRC(46ac8228) SHA1(5aeea221050c98e4bb0f16489ce772bf1c80f787) )
```

**Comment by Cibomatto2002** [comment]
Thanks alot :) that was fast

**Comment by Cibomatto2002** [comment]
finding files like this is hard lol anyways thanks for your help.
