### ISSUE TITLE
Porky sound

### ISSUE THREAD

**Issue by mahoneyt944** [libretro/mame2003-plus-libretro#1042]
I started a branch for it but hit a wall in DRIVER_INIT( porky ). I'm not sure how to back port the bank configuration? Might be a easy fix but unsure.

**Comment by arcadez2003** [comment]
You do pick the code mere mortals like me keep well away from :) 

As per the big sound and memory rewrite circa MAME93 or so none of these calls will be compatible in MAME78
without totally reworking the handling, your best chance is to search the MAME112 src for the following see what
drivers turn up and then check the same ones in our core to see how they handled these calls in MAME78 and
that way you might spot what you need to change to roll back the porky banking code to work in this core.

memory_set_bank = no such call MAME78
memory_set_bankptr = cpu_setbank but code post MAME93 will likely not work in 78
memory_configure_bank = no such call MAME78

Best of luck this could well be a big ole rabbit hole ;)
