### ISSUE TITLE
Generating a DAT creates very weird results

### ISSUE THREAD

**Issue by ZappaUtopia** [libretro/mame2003-plus-libretro#105]
When creating a DAT in the MAME menu on the latest build the DAT is not created correctly ? It's asking to rename -

1943,1943j,1943kai,1943mii > exedexes
2020bb > 2020bbn
4in1 > batman2
8ball > cvs 

etc.

**Comment by grant2258** [comment]
@markwkidd 
Configuring 'lr-mame2003-plus' : Arcade emu - updated MAME 0.78 port for libretro with added game support
= = = = = = = = = = = = = = = = = = = = =

cp: cannot stat ‘/opt/retropie/libretrocores/lr-mame2003-plus/metadata/*.nv’: No such file or directory
chown: cannot access ‘arcade/mame2003-plus//*.*’: No such file or directory
cp: cannot stat ‘/opt/retropie/libretrocores/lr-mame2003-plus/metadata/*.nv’: No such file or directory
chown: cannot access ‘mame-libretro/mame2003-plus//*.*’: No such file or directory

**Comment by grant2258** [comment]
i am on the latest setup script mark its probably realated to the above is why i posted here

**Comment by Wilstorm** [comment]
I was going to rebuild from source today. Should we hold off for a bit?

**Comment by markwkidd** [comment]
@grant2258 can you try to build mame2003-libretro from source vie RetroPie-Setup and see if you get the same error.

lord I hope I don't have to submit another PR to RetroPie-Setup... it's been five or six now already. Embarrassing how often I break that script.

**Comment by grant2258** [comment]
i did build from the souce the build is fine its the configure thats going wrong its pasting bad here though

**Comment by Wilstorm** [comment]
I updated RetroPie and built from source about a half hour ago.

```
= = = = = = = = = = = = = = = = = = = = =
Configuring 'lr-mame2003-plus' : Arcade emu - updated MAME 0.78 port for libretro with added game support
= = = = = = = = = = = = = = = = = = = = =

Copying new default configuration to /opt/retropie/configs/arcade/retroarch.cfg.rp-dist
cp: cannot stat ‘/opt/retropie/libretrocores/lr-mame2003-plus/metadata/*.nv’: No such file or directory
chown: cannot access ‘arcade/mame2003-plus//*.*’: No such file or directory
cp: cannot stat ‘/opt/retropie/libretrocores/lr-mame2003-plus/metadata/*.nv’: No such file or directory
chown: cannot access ‘mame-libretro/mame2003-plus//*.*’: No such file or directory
/home/pi

Log ended at: Wed Apr 18 11:54:39 CDT 2018
Total running time: 0 hours, 20 mins, 1 secs
```

**Comment by grant2258** [comment]
why doesnt mine paste like that! them cocktail dip switch do seem to be missing Wilstorm i just checked

**Comment by Wilstorm** [comment]
Put 3 back quote marks (above TAB) before the block and 3 after (on their own line).

**Comment by Wilstorm** [comment]
@markwkidd - Normally game.nv files were creating to ```/home/pi/RetroPie/roms/mame-liberetro/mame2003-plus/nvram```

root is the owner of ```/opt/retropie/liberetrocores/lr-mame2003/metadata``` so that's an issue for sure. 

I am not sure what does the double forward slash means ```arcade/mame2003-plus//*.*```?

**Comment by markwkidd** [comment]
@ZappaUtopia if you update again, that particular error in the DAT file should be gone. it was essentially a copy paste error on my part.

I didn't notice any more like that, but I made dozens and dozens of similar copy/paste/cleanup operations in that file so your feedback would be useful. I don't have more than a handful of roms with me right now for testing, so it's not practical for me to process them in clrmamepro myself at the moment.

**Comment by markwkidd** [comment]
@grant2258 if you can spot the error with the retropie configure function that would be very fine with me

**Comment by markwkidd** [comment]
do you have a retropie setup at hand? it would be particularly good if someone was creating these PRs who could test the scripts. I have to work blind in that code... not a good practice really

**Comment by grant2258** [comment]
naw ill just look at it and fix it should be simple enough

**Comment by Wilstorm** [comment]
How is this not an issue due to root is the owner of ```/opt/retropie/liberetrocores/lr-mame2003/metadata/nvram``` and root owns the *.nv files. Should pi be the owner as user rights out files?

Also is that the new location instead of the roms directory?

**Comment by Wilstorm** [comment]
Normally nvram files go here ```/home/pi/RetroPie/roms/mame-liberetro/mame2003-plus/nvram``` (same location as lr-mame2003 for folders arcade or mame-libretro) and pi is the owner. That way when playing a game pi writes the new nvram, cfg, hi, etc.

**Comment by markwkidd** [comment]
That should be the `nvram` folder, a subfolder inside mame2003 (or
mame2003-plus when it loads this core).

If you follow the link you will see that when the script is working
correctly, the user takes ownership of the copied files. Among whatever
else is happening with the misisng `nvram` folder path it probably is
causing permissions problems.

**Comment by Wilstorm** [comment]
@grant2258 - Ok, I will wait for the fix and update from source when completed for testing.

**Comment by markwkidd** [comment]
Exactly -- somehow I bungled the script and it's not pointing to the right pair of folders any more.

RetroPie Setup is intended to download all nvram patches from inside this repository's `metadata/nvram` folder, copy them to the corresponding locations in RetroPie, and take ownership of them as the user. That way when those games are loaded, the nvram patches are in the right place to allow the user to skip past places where they might get stalled.

**Comment by markwkidd** [comment]
folks with an actual retropie setup :small_airplane: could make the edit to their local copy of `lr-mame2003.sh` and make sure that the change works before submitting to the RetroPie team

**Comment by Wilstorm** [comment]
@markwkidd - Damn dude we need to get you a Pi, you have a donation page or no interest in the platform right now?

**Comment by grant2258** [comment]
gawd i hate pico lol

**Comment by Wilstorm** [comment]
Pico?

**Comment by markwkidd** [comment]
I'm a big fan user and fan of Lakka, which is admittedly pretty different
but does give a nice interface for playing the same emulators as retropie
on a whole variety of low power devices and vintage devices.

Something about having to buy or build a case for the board might be
holding me back. If some folks wanted to buy a pi setup for me, I would
want to think about it for a bit but I would probably agree to install
RetroPie to be better able to support folks.

But then again that might obligate me to stick around the forums and help
with support, which I like doing already, but I have my freedom!
Volunteering has its perks.

**Comment by grant2258** [comment]
= = = = = = = = = = = = = = = = = = = =
Configuring 'lr-mame2003' : Arcade emu - MAME 0.78 port for libretro
= = = = = = = = = = = = = = = = = = = = =

cp /opt/retropie/libretrocores/lr-mame2003/metadata/*.nv arcade/mame2003/
chown pi:pi arcade/mame2003//*.*
cp /opt/retropie/libretrocores/lr-mame2003/metadata/*.nv mame-libretro/mame2003/
chown pi:pi mame-libretro/mame2003//*.*
mkUserDir /home/pi/RetroPie/BIOS/mame2003
mkUserDir /home/pi/RetroPie/BIOS/mame2003/samples
cp /opt/retropie/libretrocores/lr-mame2003/metadata/hiscore.dat /opt/retropie/libretrocores/lr-mame2003/metadata/cheat.dat /home/pi/RetroPie/BIOS/mame2003/
chown pi:pi /home/pi/RetroPie/BIOS/mame2003/hiscore.dat /home/pi/RetroPie/BIOS/mame2003/cheat.dat
/home/pi/RetroPie-Setup

**Comment by markwkidd** [comment]
Ok thanks that was helpful. I've found my dumb error, give me a sec

**Comment by markwkidd** [comment]
Can someone try replacing the configure function in `lr-mame2003.sh` with what's below?

```

function configure_lr-mame2003() {
    local name="$(_get_name_lr-mame2003)"

    local mame_dir
    local mame_sub_dir

    # create subfolders to prepopulate - mame2003 generates the other folders when run
    for mame_dir in arcade mame-libretro; do
        mkRomDir "$mame_dir"
        mkRomDir "$mame_dir/$name"
        ensureSystemretroconfig "$mame_dir"
        
        # currently nvram is the only folder to repopulate
        for mame_sub_dir in nvram; do
            mkRomDir "$mame_dir/$name/$mame_sub_dir"
        done
        
        # prepopulate nvram patches
        cp "$md_inst/metadata/nvram/*.nv" "$mame_dir/$name/$nvram"
        chown $user:$user "$mame_dir/$name/$nvram/*.*"
    done

    mkUserDir "$biosdir/$name"
    mkUserDir "$biosdir/$name/samples"

    # prepopulate hiscore.dat and cheat.dat
    cp "$md_inst/metadata/"{hiscore.dat,cheat.dat} "$biosdir/$name/"
    chown $user:$user "$biosdir/$name/"{hiscore.dat,cheat.dat}

    # Set core options
    setRetroArchCoreOption "${name}-skip_disclaimer" "enabled"
    setRetroArchCoreOption "${name}-dcs-speedhack" "enabled"
    setRetroArchCoreOption "${name}-samples" "enabled"

    addEmulator 0 "$md_id" "arcade" "$md_inst/${name}_libretro.so"
    addEmulator 1 "$md_id" "mame-libretro" "$md_inst/${name}_libretro.so"
    addSystem "arcade"
    addSystem "mame-libretro"
}
```

**Comment by markwkidd** [comment]
If this works, what do I have to bribe one of you with in order to submit the PR to RetroPie Setup? I don't know if I can face them again about this script

**Comment by grant2258** [comment]
cp: cannot stat ‘/opt/retropie/libretrocores/lr-mame2003/metadata/nvram/*.nv’: No such file or directory
chown: cannot access ‘arcade/mame2003//*.*’: No such file or directory
cp: cannot stat ‘/opt/retropie/libretrocores/lr-mame2003/metadata/nvram/*.nv’: No such file or directory
chown: cannot access ‘mame-libretro/mame2003//*.*’: No such file or directory
/home/pi/RetroPie-Setup

**Comment by Wilstorm** [comment]
I have no issue pitching in for that cause and to be quite frank you, Grant and Arcadez have put in plenty of time as far as I am concerned so any obligation you may feel has already been met/exceeded by my expectations but on the other hand it can be a bit like socialism as in a whole community is looking to the small core group of guys for a majority of their game additions/updates. It seems like I see 5 or 6 of the same names mainly over and over. Aaron Giles is always in my thoughts when I think of MAME. The "politics" but I am pretty much a straight shooter out of the Midwest. The people in this area are fairly honest and hard working folks. Anyway give it some thought at least.

To be honest I have never ventured outside of RetroPie but should poke my head up once in a while just to see what's out there.

**Comment by markwkidd** [comment]
Agreed @grant2258 I think that's what my script update will do. It somehow
got messed up to not have `nvram` in the source directory that's going to
`cp`

**Comment by grant2258** [comment]
Could not successfully install Arcade emu - MAME 0.78 port for libretro (/home/pi/RetroPie-Setup/tmp/build/lr-mame2003/CHANGELOG.md not found).

**Comment by grant2258** [comment]
maybe add one to mame2003

**Comment by grant2258** [comment]
even an empty file

**Comment by grant2258** [comment]
ok fixed it

we need to add that file to the repo though

= = = = = = = = = = = = = = = = = = = = =
Installing 'lr-mame2003' : Arcade emu - MAME 0.78 port for libretro
= = = = = = = = = = = = = = = = = = = = =

‘/home/pi/RetroPie-Setup/tmp/build/lr-mame2003/mame2003_libretro.so’ -> ‘/opt/retropie/libretrocores/lr-mame2003/mame2003_libretro.so’
‘/home/pi/RetroPie-Setup/tmp/build/lr-mame2003/README.md’ -> ‘/opt/retropie/libretrocores/lr-mame2003/README.md’
‘/home/pi/RetroPie-Setup/tmp/build/lr-mame2003/CHANGELOG.md’ -> ‘/opt/retropie/libretrocores/lr-mame2003/CHANGELOG.md’
‘/home/pi/RetroPie-Setup/tmp/build/lr-mame2003/metadata’ -> ‘/opt/retropie/libretrocores/lr-mame2003/metadata’
‘/home/pi/RetroPie-Setup/tmp/build/lr-mame2003/metadata/MAME 0.78 XML.dat’ -> ‘/opt/retropie/libretrocores/lr-mame2003/metadata/MAME 0.78 XML.dat’
‘/home/pi/RetroPie-Setup/tmp/build/lr-mame2003/metadata/catver.ini’ -> ‘/opt/retropie/libretrocores/lr-mame2003/metadata/catver.ini’
‘/home/pi/RetroPie-Setup/tmp/build/lr-mame2003/metadata/cheat.dat’ -> ‘/opt/retropie/libretrocores/lr-mame2003/metadata/cheat.dat’
‘/home/pi/RetroPie-Setup/tmp/build/lr-mame2003/metadata/hiscore.dat’ -> ‘/opt/retropie/libretrocores/lr-mame2003/metadata/hiscore.dat’
‘/home/pi/RetroPie-Setup/tmp/build/lr-mame2003/metadata/nvram’ -> ‘/opt/retropie/libretrocores/lr-mame2003/metadata/nvram’
‘/home/pi/RetroPie-Setup/tmp/build/lr-mame2003/metadata/nvram/rungun.nv’ -> ‘/opt/retropie/libretrocores/lr-mame2003/metadata/nvram/rungun.nv’
‘/home/pi/RetroPie-Setup/tmp/build/lr-mame2003/metadata/nvram’ -> ‘/opt/retropie/libretrocores/lr-mame2003/nvram’
‘/home/pi/RetroPie-Setup/tmp/build/lr-mame2003/metadata/nvram/rungun.nv’ -> ‘/opt/retropie/libretrocores/lr-mame2003/nvram/rungun.nv’
/home/pi/RetroPie-Setup

**Comment by grant2258** [comment]
cp: cannot stat ‘/opt/retropie/libretrocores/lr-mame2003/metadata/nvram/*.nv’: No such file or directory
chown: cannot access ‘arcade/mame2003//*.*’: No such file or directory
cp: cannot stat ‘/opt/retropie/libretrocores/lr-mame2003/metadata/nvram/*.nv’: No such file or directory
chown: cannot access ‘mame-libretro/mame2003//*.*’: No such file or directory

**Comment by markwkidd** [comment]
@wilstrom give lakka a shot sometime. Lakka is carefully tested to always
run well rpi and has a live mode --  you might be able to just run it off
of a usb drive. definitely you could pop in another sdcard to your rpi with
lakka on it and give it a test run that way, assuming you have a spare sd
card laying around.

I've worked on the docs for Lakka as well (although they won't turn me
loose on their docs as much as the RetroPie folks do!) Glad to hear what
you think.

As a self-employed consulting artist and writer, and media professional, I
would love to earn some money for the work I do on emulation docs, support,
bugfixes, and raising bounties. If I could just dedicate 10-20 hours per
month on the clock for this -- and/or have that money to hire out for
specific fixes, like I do with projects I manage in my professional life --
a lot could happen.

But that's true for a lot of open source volunteers. We would all probably
get more done if we had budgets for ourselves and to sub out smaller
projects.

**Comment by grant2258** [comment]
@markwkidd the install takes care of the copy no need to worry about that

**Comment by markwkidd** [comment]
The nvram files are getting copied out of the temp folder, but they are not getting copied from `‘/opt/retropie/libretrocores/lr-mame2003/nvram’` to `/opt/retropie/libretrocores/lr-mame2003/metadata/nvram/` and the retropie arcade folder equivalent.

**Comment by grant2258** [comment]
it it just teh nvram you want to copy ok no problems it be /home/pi/Retropie

**Comment by Wilstorm** [comment]
I definitely spy an entrepreneur and you definitely have the skill set. You just need a solid business model and run with it! ;) I remember reading a book years and years ago when PC gaming was in the beginning. The writer said something to the effect of *"There's about 50,000,000,000 [more like infinite] possibilities for games and you should never run out of ideas. Oh, and watch Real Genius about 100 times."* A classic Val Kilmer movie that has some really crazy ideas to promote creativity. Out of the whole book that was one of the few motivational/philosophical paragraph pieces I remember to this day. 

I will give Lakka a try. I do have a few extra SD cards of varying sizes.

**Comment by markwkidd** [comment]
Well I do enjoy Real Genius as a guilty pleasure, and have my own copy. I
suggest coding while listening to New Wave music to get in the vibe.

**Comment by grant2258** [comment]
@markwkidd last one to fix is this the right dir

test3 cp /opt/retropie/libretrocores/lr-mame2003/metadata/hiscore.dat /opt/retropie/libretrocores/lr-mame2003/metadata/cheat.dat /home/pi/RetroPie/BIOS/mame2003/
test4 chown pi:pi /home/pi/RetroPie/BIOS/mame2003/hiscore.dat /home/pi/RetroPie/BIOS/mame2003/cheat.dat

guess that would be system on retroach

**Comment by markwkidd** [comment]
Yes the `hiscore.dat` and `cheats` are supposed to go directly in to the retoarch system directory, so that part looks like it's working right

**Comment by grant2258** [comment]
ok let me delete the nvram from both folders and make sure it goes in arcade and lrmame

**Comment by grant2258** [comment]
Could not successfully install Arcade emu - MAME 0.78 port for libretro (/home/pi/RetroPie-Setup/tmp/build/lr-mame2003/CHANGELOG.md not found).

this CHANGELOG.md will have tro be added to Mame2003 else the install will fail mark

**Comment by markwkidd** [comment]
That's the thing -- there is a CHANGELOG.md in mame2003: https://github.com/libretro/mame2003-libretro/blob/master/CHANGELOG.md

**Comment by grant2258** [comment]
/home/pi/RetroPie-Setup/tmp/build/lr-mame2003/CHANGELOG.md 

hold on i probably need to do a pull or the file isint tracked

**Comment by grant2258** [comment]
Saved working directory and index state WIP on master: 566a7ae Merge pull request #357 from grant2258/master
HEAD is now at 566a7ae Merge pull request #357 from grant2258/master
pi@retropie:~/RetroPie-Setup/tmp/build/lr-mame2003 $ git pull
Updating 566a7ae..b53550d
error: The following untracked working tree files would be overwritten by merge:
	CHANGELOG.md
Please move or remove them before you can merge.

**Comment by grant2258** [comment]
look good to go mark

**Comment by grant2258** [comment]
it cause i didnt update my repo sorry

**Comment by grant2258** [comment]
ok my good man um going to get some sleep

**Comment by markwkidd** [comment]
Did you have to alter the config function any from the edit in my post
above?

**Comment by grant2258** [comment]
yes quite a bit

**Comment by grant2258** [comment]
just diff it when add it to the repo the copy statements need changed and some paths fixed up

**Comment by markwkidd** [comment]
So your updated version of the script is in your repo? someone should
submit to retropie and I will do it but I want to ,make sure I'm giving
themthe copy that worked for you

**Comment by grant2258** [comment]
yes it does work for me tried it thats only for mame 2003 though wait liet me add a chmod to it for the bios dir

**Comment by grant2258** [comment]
ok all done mark

**Comment by grant2258** [comment]
pi@retropie:~/RetroPie-Setup $ sudo  ./retropie_packages.sh lr-mame2003 configure
/opt/retropie/libretrocores/lr-mame2003 /home/pi/RetroPie-Setup

= = = = = = = = = = = = = = = = = = = = =
Configuring 'lr-mame2003' : Arcade emu - MAME 0.78 port for libretro
= = = = = = = = = = = = = = = = = = = = =

/home/pi/RetroPie-Setup

**Comment by markwkidd** [comment]
I am not sure you are saving these changes anywhere I have access to. Are
they maybe only in a local repository ? I don't know where to find your
work! Sorry, and no rush

**Comment by grant2258** [comment]
https://github.com/grant2258/mame2003-plus-libretro

**Comment by grant2258** [comment]
posted a link above

**Comment by grant2258** [comment]
no problems at all mark least i can do with the amount of work you put in. I thought it might be wise to put it in the repo incase people need to copy over

**Comment by Wilstorm** [comment]
Nice, same here Real Genius is definitely a guilty pleasure that I've always enjoyed through the years. I wear my nerd badge proudly. ;) Well the older I get the less I care what others think. I hope not to be the cynical old guy someday though. Anything but cynical. I like all genres but do appreciate a good sci-fi flick. 

I originally started as a programmer on the likes of a IBM System/38. I originally went to school for Programming. I learned BASIC, COBOL, Fortran, RPG, etc. Did some work for the public schools in COBOL and RPG. COBOL so wordy and RPG loved indicator columns. Then later did some work for UPS in C to setup customers with UPS shipping systems. I would get their shipping database in a comma, semicolon, or whatever delimited format so I could distinguish the fields. Then I would read it into a structure with subscripts, flip fields around to fit the UPS format then write it back out for importing. Simple C stuff.

That's been 20+ years ago though. Now I work for the state and I mainly do firewalls currently a Fortigate but we almost went with a Palo Alto, Lot's of VPN & IPSEC tunnels between city/state and other organizations for for law enforcement vehicles. We have the jail, juvenile detention center, 911, and on and on, 23 departments total, public defender, states attorney, treasurer, auditors, etc. When I first started we used Checkpoint on a Nokia box, 16/4 token ring and Novell servers with NDS which is like Windows AD. That's a tough go. I do switching and all the fiber communication structure, a lot of VMWare and mass storage shelves like NetApp. Mainly a Windows shop so Windows, SQL, AD, Group Policy, LDAP all that fun stuff. Wireless and that security like certificates generated from a certificate authority (CA), 

I even get virus scan but we use enterprise class tools to manage like 700 or so PC's at a go. We aren't a big enough organization to have dedicated positions so I have to switch hats often. The firewall was a forklift upgrade so I built it from the ground up and it took a several months before the final cut-over as I had to get a lot of redundant failover connections to the core and other stacks beforehand. Now I am doing a lot of switch replacements in a ring. Which requires 50ms or less fail over for IP telelphony (oh ShoreTel phones). QoS to shape and throttle traffic, etc.

I like programming but I feel better suited to a Network Engineer. I can follow the code but when it comes to figuring what values are being passed to what variables/functions/structs I get lost when looking at the code or something. It seems it would take time to become proficient in what you guys do because you really need to understand the whole thing from beginning to end to a certain extent it seems. Possibly someone to mentor you through it a little.

I have a lot going on with family in the evenings with swim lessons, dance lessons, family gatherings, etc. now with summer on the horizon and I spend most of that time with them or I would try nerding out more but I still get to to do it a little as I pass it off as my hobby. ;) I have one little one left at home and she's the last and I have to say I enjoy her a ton knowing that. My oldest is 27 and recently married so I could be grandpa anytime really but I stay pretty active and in shape for an older guy so I can keep up with her when she gets older and do some traveling together. Well for her age she is well traveled and has been out of the country several times already but we keep her humble and kind and to *always* use good manners no matter what. ;)

**Comment by markwkidd** [comment]
@Wilstorm I think you represent the perfect audience for this core. There's an irony in that it represents the first libretro core that many arcade emulator users encounter when they get interested in coding, but as a libretro core it's been kind of a mess. Also mame2003 was ported to libretro before there were some conveniences like the libretro-common libraries to use and keep the core code clean & crossplatform.

Anyway code should be self-documenting & in fact the MAME emulator code in general is pretty legible. Also the libretro code is pretty legible in general. The parts in the middle have been a little soupy here and there that's getting better too. Also lots of code that is never used is gone now. Hopefully the net effect is mame2003/mame2003-plus is getting slightly more accessible for people to (re)learn coding.

**Comment by markwkidd** [comment]
@ZappaUtopia is it ok to close this issue now?

**Comment by ZappaUtopia** [comment]
Yes it's fixed.
