### ISSUE TITLE
Add ssf2tnl and sf2mix

### ISSUE THREAD

**Issue by palmerj** [libretro/mame2003-plus-libretro#1050]
Would it be possible to add these really good Street Fighter 2 hacks? 

Super Street Fighter 2 Turbo - New Legacy - https://newlegacy.fr/
Street Fighter 2 Mix: - https://sf2mix.github.io/

Thank you. 

If you are willing to accept these games, I'm happy to prepare a PR for the changes.

**Comment by mahoneyt944** [comment]
Surely. Add the hacked roms in, test both games and submit a working PR.

**Comment by mahoneyt944** [comment]
I'm going to close this. We welcome these game additions if you decide to submit them. If you need any help or have questions feel free to open a PR or new issue. 👍

**Comment by grant2258** [comment]
never seen this as it was closed is added now a but late since you made the request years ago.
