### ISSUE TITLE
msvc toolchains always pass

### ISSUE THREAD

**Issue by markwkidd** [libretro/mame2003-plus-libretro#1056]
I have noticed that the msvc tasks in gitlab always show up as successful, even if there is a compiler error that stops every other platform from building. However I don't really know anything about how that is set up -- magic, probably. Is it a problem?

**Comment by mahoneyt944** [comment]
I'm not sure exactly, though since it's built from templates outside of our core specifically, I think this issue would be global if it was a real issue? I'm assuming msvc is just more tolerant maybe?

@m4xw would probably know the specifics.

**Comment by mahoneyt944** [comment]
Maybe ask him on discord of he doesn't reply here.

**Comment by mahoneyt944** [comment]
Spoke with @m4xw about this. Seems to be a issue up stream but we'll have to see for sure.

![Screenshot_20210608-000456](https://user-images.githubusercontent.com/49591133/121121236-31b42c00-c7ed-11eb-9e68-bda4e27b633b.png)

**Comment by markwkidd** [comment]
Because msvc isn't building due to some c89 strict compliance issues, I'm peeking at the logs we do get to see if I can at least fix the existing compiler errors.

m4xw is kind of reiterating now that the CI scripts aren't really our problem to fix, but I will see if there is anything in our build files that could lead to a make sure failed build getting a 0 (passing) return code.

**Comment by markwkidd** [comment]
The news is that the MSVC builds are working as of now, although they still always say that whether they fail or not. :)

**Comment by mahoneyt944** [comment]
Hopefully solves this properly
