### ISSUE TITLE
To do: Fix pad layout information

### ISSUE THREAD

**Issue by mahoneyt944** [libretro/mame2003-plus-libretro#1066]
Update our notes to our current layout names.
- PAD_CLASSIC
- PAD_FIGHTSTICK
- PAD_8BUTTON
- PAD_6BUTTON

https://github.com/libretro/mame2003-plus-libretro/blob/1dd72914542ae2b5d18f9cbdc2728b0d3a5d585f/src/mame2003/mame2003.c#L1578-L1653

**Comment by grant2258** [comment]
feel free to remove the 8 button as I dont use this core and it was my personal layout for 8 button arcade sticks that mapped itn a sane way to use other cores. rename the 6 to snes if you want it works for that and 6 buttons. Fightstick is misleading its basically mapping modern gamepad to work for sf2 pretty much useless for anything else

**Comment by mahoneyt944** [comment]
These just add complexity because even when you use an alternate layout you still might have to remap in the mame menu anyhow. Seems to me it's easier to just setup mame under input general, and then override under input this game as needed. Not to mention I see users trying to use retroarch configs like they do in other cores which gets things even more messy. Then there's also the legacy core option which adds more to the pile. Lol.

Right now I think it would be good to update the notes with the current naming we have so it at least matches.

**Comment by grant2258** [comment]
dont know what to tell you i just use the tab menus myself. I never took anything to do with the libretro implementation as far as i can see its still a wip

**Comment by mahoneyt944** [comment]
I'm not looking to change the alternate mappings. I don't use them anyhow and would rather not disturb those who do. My goal here is just to structure the diagrams more clearly.

- For example one of them is labeled "PAD_GAMEPAD" which is not a current layout name. I think this is the 8 button layout though?
- PAD_FIGHTSTICK former "PAD_MODERN" is not listed either.

**Comment by grant2258** [comment]
PAD_GAMEPAD is fightstick aka modern they are the same layout.

**Comment by mahoneyt944** [comment]
Oh ok. So the 8 button layout is just missing here then.

**Comment by grant2258** [comment]
yea that was a core wide map so the panel can be used for other cores beyond this one a more global friendly one for my personal use if i wanted to use other cores

**Comment by mahoneyt944** [comment]
Interesting read lol. I'll leave the decision to remove it to you I guess. It certainly doesn't bother me either way. My reservation is if any users are using it, I wouldn't want to remove it then but I have no way of knowing that for sure.

If you think it might be useful for some user and might be worth keeping, I see no issue in it. If not I can remove it too.

**Comment by grant2258** [comment]
Yea well all in all it doesnt matter to me at all as I dont use this core ive long since installed a mini pc in my barcade and use mame current. If that breaks i can install my little port I done for myself on the pie. 

The direction the core was taking wasnt good for my own personal use. Mark will probably pick up before his health  back tracked him. Im not a part of the project anymore anyway time for new people to do there thing. My only partial interest is in drivers and emulation bugs nothing more.
