### ISSUE TITLE
Can't remap buttons even legacy input turns off

### ISSUE THREAD

**Issue by litaniast** [libretro/mame2003-plus-libretro#1069]
I want to remap the button on some games (like Gunsmoke, Bank Panic)

but when I try to remap, it's just ---. Can't remap the buttons.

I remember changed the mapping long time ago, but maybe it's some regression.

**Comment by mahoneyt944** [comment]
Are you mapping in the mame menu or retroarch menu?

**Comment by mahoneyt944** [comment]
Mame menu mapping.

Enter retroarch main menu-> quick menu-> options-> display mame menu-> on

Then close retroarch menu. The mame menu will be open now.

Under "input this game" map things the way you want for that game.

**Comment by litaniast** [comment]
Retroarch menu. In old version of Mame2003-Plus, If I turn off legacy input and can remappable on retroarch menu.

But It seems to broken now. No way to remap unless I use legacy mapping.

**Comment by markwkidd** [comment]
Can you provide the name of one specific game, and a specific control from that game that you can't remap via RetroArch?

**Comment by litaniast** [comment]
I tested Bank Panic and Gunsmoke because these use 3 button that represents left, center and right firing direction.
But both of them can't remap buttons in retroarch menu on non-legacy mapping.

**Comment by grant2258** [comment]
delete the contents in your <savedir>mame2003-plus/cfg/ looks like the input offets have been shifted in input.h clearing this should help bring things back to new defaults

**Comment by litaniast** [comment]
> delete the contents in your retroarchsavedir/mame2003-plus/cfg/ looks like the input offsets have been shifted in input.h clearing this should help bring things back to new defaults

Tried, but not solved

**Comment by grant2258** [comment]
I'll check this at the weekend would need to compile it. I personally never use none legacy mode. What was the full path name to the cfg files you deleted?

**Comment by litaniast** [comment]
\\192.168.1.202\roms\mame-libretro\mame2003-plus\cfg\ra_gunsmoke.cfg
\\192.168.1.202\roms\mame-libretro\mame2003-plus\cfg\ra_default.cfg
\\192.168.1.202\roms\mame-libretro\mame2003-plus\cfg\ra_rodland.cfg
\\192.168.1.202\roms\mame-libretro\mame2003-plus\cfg\ra_bankp.cfg

**Comment by grant2258** [comment]
can confirm with 0f11bc7439878710f00f58a540f20f83fd71d33c that the input descriptors dont seem to be working in the quick menu controls

**Comment by mahoneyt944** [comment]
0f11bc7 was just pushed today. So it's likely before this is the issue.

**Comment by mahoneyt944** [comment]
Maybe one of the descriptor changes in mame2003.c at some point?

**Comment by grant2258** [comment]
I havent really been looking at the changes to be honest. From memory the macro set the input descriptors as well.

**Comment by mahoneyt944** [comment]
Yeah. I think mark added some logging to it that's commented out if I recall. He'd probably know more about what it's doing now

**Comment by mahoneyt944** [comment]
Knowing the last working commit would be a big helper there too lol.

**Comment by grant2258** [comment]
had a quick look and it looks like its changed but it is calling it on controller port changes and some other options just the descriptions are not setting to anything when its called will need fixed at some point

**Comment by litaniast** [comment]
2ea66bf commit (with retroarch 1.9.1) working.

**Comment by grant2258** [comment]
are other cores working fine for you with 1.9.4?

**Comment by litaniast** [comment]
yes. other cores have no issue on 1.9.4. and even the mame2003-plus 829e8b7 commit on retroarch 1.9.4, it also works.

**Comment by markwkidd** [comment]
This seems likely to be due to some of my refactoring. Thanks for your
patience, I haven't focused on tracing it down but I plan to.

**Comment by grant2258** [comment]
a quick look seems like a stray continue is here https://github.com/libretro/mame2003-plus-libretro/blob/0f11bc7439878710f00f58a540f20f83fd71d33c/src/mame2003/mame2003.c#L1660

**Comment by grant2258** [comment]
https://github.com/grant2258/blaster-barcade/commit/2a25fda6f76aa021f4c97d8a4a9e9b5b13d0caea will fix it up mark probably needs white space fixing.

**Comment by litaniast** [comment]
Some buttons can now remapped but not fully solved. 
For example: in bankp, can't reassign "up" "coin" and "start".

**Comment by mahoneyt944** [comment]
@litaniast which commit are you using

**Comment by grant2258** [comment]
yea i checked this you missed some logic check sf2 my second commit in my pull req fixed this

**Comment by mahoneyt944** [comment]
@grant2258 
Just these lines right? get_device_parent(device_code) can't return lightgun. So I used if-else for that instead
```
const char *control_name  = 0;
if(string_is_empty(control_name) && retro_code !=INT_MAX) control_name = game_driver-&gt;ctrl_dat-&gt;get_name(ctrl_ipt_code);
```

**Comment by grant2258** [comment]
yea and the braces need fixed for the else as well

**Comment by mahoneyt944** [comment]
I'm not seeing the brace fix you mentioned. might be looking right past it though. lol

**Comment by litaniast** [comment]
> Some buttons can now remapped but not fully solved.
> For example: in bankp, can't reassign "up" "coin" and "start".

that still presents on d25791a commit.

**Comment by grant2258** [comment]
ill fix it give me a a few minutes going to grab a coffee

**Comment by mahoneyt944** [comment]
the else statement shouldn't point to:
```
 if (get_device_parent(device_code) == RETRO_DEVICE_JOYPAD)
```

 because it can never be called. all devices in get_device_parent(device_code) return as RETRO_DEVICE_JOYPAD

**Comment by mahoneyt944** [comment]
at one point the lightgun was added as a device but now its not. probably where this issue started.

**Comment by grant2258** [comment]
You focusing on the wrong part https://github.com/libretro/mame2003-plus-libretro/blob/d25791a17e214fb7db9a6003523b2aebe1c2ce97/src/mame2003/mame2003.c#L1630

will put lightgun descriptors in the retropad

**Comment by mahoneyt944** [comment]
so can't we just remove the lightgun stuff then?

**Comment by mahoneyt944** [comment]
also retro_code is reinitialized if INT_MAX is returned in the above if

https://github.com/libretro/mame2003-plus-libretro/blob/d25791a17e214fb7db9a6003523b2aebe1c2ce97/src/mame2003/mame2003.c#L1648

**Comment by grant2258** [comment]
I know how the code is working both commits i posted work. retrogun should never be called in a a retropad device context and thats exactly what your doing here

**Comment by mahoneyt944** [comment]
I just removed the lightgun all together. I agree it shouldn't be there now.

**Comment by grant2258** [comment]
i left it open so mark could add the device type seems like this went south making workarounds for broken android input. It worked fine on udev that worked the way the api should. I think youll have a bit of tidying up to do when android gets fixed.

**Comment by mahoneyt944** [comment]
yeah the android issue definitely threw a wrench in things. I think marks plan was to make the lightgun work with the retropad instead of having it as its own dedicated device, eventually having all devices working at once. Even with the android port issue fixed, touch screens will still need an option to disable the lightgun, mouse, and pointer because the screen is already in use as a touchscreen retropad and the touches register and trigger and clicks. That's why we added it as another xy device for now. It allows the user to select which xy device they want to use if any at all.

**Comment by mahoneyt944** [comment]
anywho, @litaniast hopefully the latest commit solved this issue for you.

**Comment by litaniast** [comment]
solved on last commit. thx

**Comment by mahoneyt944** [comment]
That's Great.  And @grant2258 thanks for finding the solution here. appreciate it.
