### ISSUE TITLE
Feature Request: Easier Access to Diagnostic/Test Menu

### ISSUE THREAD

**Issue by KMFDManic** [libretro/mame2003-plus-libretro#1079]
**Update: Looking further, I see it is in most FBA/NEO Cores, in addition to Test Switch On/Off Core Option**

I tested this with FBA, and it works quite nicely.  Nothing can get more irritating than having to remap a needed button on your controller to be Test Menu.  It can lead to some pesky conflicts.  But, if you have it set to a delayed "hold" on Start Button, it works very well!  So, I would suggest the diagnostic be shortcut to a "hold" start button.  I just need to better analyze how this is implemented, to see about this going in Xtreme.  But, it would be super nice in Plus/Standard, as well!  It was particularly nice being able to change settings in Mars Matrix to have higher difficulty, with absolute ease, with this quick shortcut.

Core Option in FBA 2012, for example, is:

line 145:

https://github.com/libretro/fbalpha2012/blob/master/svn-current/trunk/src/burner/libretro/libretro.cpp

static const struct retro_variable var_fba_diagnostic_input = { CORE_OPTION_NAME "_diagnostic_input", "Diagnostic Input; None|Hold Start|Start + A + B|Hold Start + A + B|Start + L + R|Hold Start + L + R|Hold Select|Select + A + B|Hold Select + A + B|Select + L + R|Hold Select + L + R" };

**Comment by KMFDManic** [comment]
@dinkc64 Can you shed some light on the best way to handle incorporating this function into MAME 2003?  And, you've been doing truly awesome on the MESS Additions for FBNEO, of late:)  The Coleco stuff will never get old to play!

**Comment by dinkc64** [comment]
Hi KMFDManic, nice to run into you again thanks for the kind words :)
Though unfortunately I don't know much about libretro or its ui/interface integration code.  Sorry, I can't help with this one.

best regards,
- dink

**Comment by mahoneyt944** [comment]
@KMFDManic currently you can remap the service button combo to whatever you want, though hold is not an option. Map the service buttons under input general in the mame menu so it's globally applied to the entire core. When you map it just hold the combo you want.
![baluba-210622-010836](https://user-images.githubusercontent.com/49591133/122866895-b7100400-d2f6-11eb-88eb-717e0e98a3af.png)
![baluba-210622-010900](https://user-images.githubusercontent.com/49591133/122866901-ba0af480-d2f6-11eb-8af1-23ac8b2af06c.png)

**Comment by KMFDManic** [comment]
@mahoneyt944 I am familiar with the MAME Menu mapping method.  Problem is, I am trying to avoid End Users mapping it to a function they might want to use for another MAME game.  It isn't super easy to "unmap" those functions, once remapped.  The Hold Start, I will look into.  I just gotta pinpoint the structure of how it is added.  It would be a welcome addition, if I implemented.  I already have L1+R1 dedicated to rotary games.  And, on the MegaDrive, SNES, NES Classics, the default controllers would have a hell of a time using the Test Menu, without having to remap more than once.  I personally use a PS2 style controller, so am covered mostly.  But, not everyone does!  I will bump this issue if I can get it working with 2003 Xtreme!:)

@dinkc64 And, yeah, Covid sort of made it a little more difficult to keep up on some communication online.  I have been working roughly 60+ hours a week since that fun stuff hit the world.  But, I try to catch up as much as I can in my free time.  You have done an absolutely awesome job continually adding more games into FBNEO.  I actually was thinking of opening an issue as far as a potential feature request there, too.  I might as well just throw the idea your way here, to see what you think.  What do you think about Atari Jaguar being added to the MESS structure?  It would for sure run way better than it does on normal MESS!  Testing, there is a good 45 percent differential in performance on lower spec with FBNEO MESS versus real MESS Core!  Games like Rayman should run fairly well, in fact.

**Comment by grant2258** [comment]
There really isint an easy way to do this it is possible but the service menu has more than one button on mame. You have service mode and some service buttons most are f2 service mode and 9 service 1

**Comment by mahoneyt944** [comment]
Personally I set the service buttons to "none" so there's not accidental presses ever. Most in-game service menus are accessable from a service mode dip switch which seems easier to me for how rarely I enter those menus.

I imagine these dip switches could use a common core option instead but that would have to be integrated into every driver to use the appropriate values when toggled
