### ISSUE TITLE
testing: final fight, mortal kombat, nba jam with sega cd soundtracks

### ISSUE THREAD

**Issue by markwkidd** [libretro/mame2003-plus-libretro#108]
https://www.youtube.com/watch?v=VW_ompmEsEE

**Comment by twinaphex** [comment]
I have merged these commits now.

**Comment by markwkidd** [comment]
Note for the docs per twinaphex: This method may actually allow the games to perform better on lower-power systems because sample playback is often less intensive than emulating music ROMs.
