### ISSUE TITLE
Tryout memory map

### ISSUE THREAD

**Issue by mahoneyt944** [libretro/mame2003-plus-libretro#1088]
Trying to get tryout going, see the tryout branch too. Having some issues converting the memory map though. @grant2258 @arcadez2003 maybe one of you see where I'm goofing up on this? Should be close. Not sure about this line either "AM_ROM AM_REGION(REGION_CPU1, 0xbff0) "

Here's the map to convert
```
static ADDRESS_MAP_START( main_cpu, ADDRESS_SPACE_PROGRAM, 8 )
	AM_RANGE(0x0000, 0x07ff) AM_RAM
	AM_RANGE(0x1000, 0x17ff) AM_WRITE(tryout_videoram_w) AM_BASE(&videoram)
	AM_RANGE(0x2000, 0x3fff) AM_ROMBANK(1)
	AM_RANGE(0x4000, 0xbfff) AM_ROM
	AM_RANGE(0xc800, 0xc87f) AM_RAM AM_BASE(&spriteram)
	AM_RANGE(0xcc00, 0xcc7f) AM_RAM AM_BASE(&spriteram_2)
	AM_RANGE(0xd000, 0xd7ff) AM_READWRITE(tryout_vram_r, tryout_vram_w)
	AM_RANGE(0xe000, 0xe000) AM_READ(input_port_0_r)
	AM_RANGE(0xe001, 0xe001) AM_READ(input_port_1_r)
	AM_RANGE(0xe002, 0xe002) AM_READ(input_port_2_r)
	AM_RANGE(0xe003, 0xe003) AM_READ(input_port_3_r)
	AM_RANGE(0xe301, 0xe301) AM_WRITE(tryout_flipscreen_w)
	AM_RANGE(0xe302, 0xe302) AM_WRITE(tryout_bankswitch_w)
	AM_RANGE(0xe401, 0xe401) AM_WRITE(tryout_vram_bankswitch_w)
	AM_RANGE(0xe402, 0xe404) AM_WRITE(MWA8_RAM) AM_BASE(&tryout_gfx_control)
	AM_RANGE(0xe414, 0xe414) AM_WRITE(tryout_sound_w)
	AM_RANGE(0xe417, 0xe417) AM_WRITE(tryout_nmi_ack_w)
	AM_RANGE(0xfff0, 0xffff) AM_ROM AM_REGION(REGION_CPU1, 0xbff0) /* resect vectors */
ADDRESS_MAP_END

static ADDRESS_MAP_START( sound_cpu, ADDRESS_SPACE_PROGRAM, 8 )
	AM_RANGE(0x0000, 0x07ff) AM_RAM
	AM_RANGE(0x4000, 0x4000) AM_READWRITE(YM2203_status_port_0_r, YM2203_control_port_0_w)
	AM_RANGE(0x4001, 0x4001) AM_WRITE(YM2203_write_port_0_w)
	AM_RANGE(0xa000, 0xa000) AM_READ(soundlatch_r)
	AM_RANGE(0xd000, 0xd000) AM_WRITE(tryout_sound_irq_ack_w)
	AM_RANGE(0xc000, 0xffff) AM_ROM
ADDRESS_MAP_END
```

And my WIP map so far
```
static MEMORY_READ_START( readmem )
	{ 0x0000, 0x07ff, MRA_RAM },
	{ 0x2000, 0x3fff, MRA_BANK1 },
	{ 0x4000, 0xbfff, MRA_ROM },
	{ 0xc800, 0xc87f, MRA_RAM },
	{ 0xcc00, 0xcc7f, MRA_RAM },
	{ 0xd000, 0xd7ff, tryout_vram_r },
	{ 0xe000, 0xe000, input_port_0_r },
	{ 0xe001, 0xe001, input_port_1_r },
	{ 0xe002, 0xe002, input_port_2_r },
	{ 0xe003, 0xe003, input_port_3_r },
	{ 0xfff0, 0xffff, MRA_ROM },
MEMORY_END

static MEMORY_WRITE_START( writemem )
	{ 0x0000, 0x07ff, MWA_RAM },
	{ 0x1000, 0x17ff, tryout_videoram_w , &videoram },
	{ 0x2000, 0x3fff, MWA_BANK1 },
	{ 0x4000, 0xbfff, MWA_ROM },
	{ 0xc800, 0xc87f, MWA_RAM, &spriteram },
	{ 0xcc00, 0xcc7f, MWA_RAM, &spriteram_2 },
	{ 0xd000, 0xd7ff, tryout_vram_w },
	{ 0xe301, 0xe301, tryout_flipscreen_w },
	{ 0xe302, 0xe302, tryout_bankswitch_w },
	{ 0xe401, 0xe401, tryout_vram_bankswitch_w },
	{ 0xe402, 0xe404, MWA_RAM, &tryout_gfx_control },
	{ 0xe414, 0xe414, tryout_sound_w },
	{ 0xe417, 0xe417, tryout_nmi_ack_w },
	{ 0xfff0, 0xffff, MWA_ROM },
MEMORY_END

static MEMORY_READ_START( sound_readmem )
	{ 0x0000, 0x07ff, MRA_RAM },
	{ 0x4000, 0x4000, YM2203_status_port_0_r },
	{ 0xa000, 0xa000, soundlatch_r },
	{ 0xc000, 0xffff, MRA_ROM },
MEMORY_END

static MEMORY_WRITE_START( sound_writemem )
	{ 0x0000, 0x07ff, MWA_RAM },
	{ 0x4000, 0x4000, YM2203_control_port_0_w },
	{ 0x4001, 0x4001, YM2203_write_port_0_w },
	{ 0xd000, 0xd000, tryout_sound_irq_ack_w },
	{ 0xc000, 0xffff, MWA_ROM },
MEMORY_END
```

**Comment by arcadez2003** [comment]
@mahoneyt944 your gonna need a trampoline something like.........

Rough example ripped from our cave.c

static data8_t *tryout_rom;

	{ 0xfff0, 0xffff, MRA_ROM },
MEMORY_END

	{ 0xfff0, 0xffff, MWA_ROM, &tryout_rom              }, 	/* extra data ROM space */
MEMORY_END


DRIVER_INIT( tryout )
{
	/* set up data ROMs */
	memcpy(tryout_rom, memory_region(REGION_CPU1, 0xbff0), memory_region_length(REGION_CPU1, 0xbff0));
	
}

(REGION_CPU1, 0xbff0)

Not sure if this is the correct way to hookin the address value though you'll need to search this core for memcpy
to see more examples

**Comment by grant2258** [comment]
AM_RANGE(0xfff0, 0xffff) AM_ROM AM_REGION(REGION_CPU1, 0xbff0) /* resect vectors */

@arcadez2003 is that a specific mirror for an address on another cpu thats the way im reading it without checking the memory code.

**Comment by arcadez2003** [comment]
@grant2258 It might be bigman i've only came up against this twice before once when adding Power Instinct Legends
and again when updating the PGM driver so im not 100% on how the code needs to be set for this core.

The only driver we can compare against this core would be namcos10.c

**Comment by mahoneyt944** [comment]
I'll have to experiment with that one line. Does anything else look out of place or wrong though? So I'm not chasing my tail so to speak.

**Comment by grant2258** [comment]
Since its rom it won't change its safe to copy like arcadez posted will look at it a bit more

**Comment by mahoneyt944** [comment]
@grant2258  I got it with this but the length was just a pure guess it needs set accurately
```
memcpy(tryout_rom, &memory_region(REGION_CPU1)[0xbff0], 0x2000);
```

**Comment by grant2258** [comment]
{ 0xfff0, 0xffff, MWA_ROM, &tryout_rom   0-15 (16 bytes) is what you need. You would also need to read from tryout as well currently your only writing to it and reading the original rom

**Comment by mahoneyt944** [comment]
I added the read, what hex value is 16 bytes so I can fix the memcpy

**Comment by grant2258** [comment]
0xffff - 0xfff0 = 0xf (0 -15) = 

16 decimal is 0x10 you can use either

**Comment by mahoneyt944** [comment]
Thanks. I seem to be missing some gfx probably due to this: 

gfx_element_set_source(machine->gfx[2], tryout_vram_gfx);

**Comment by mahoneyt944** [comment]
Got it going now, thanks guys.
