### ISSUE TITLE
TODO: implement CPU underclock and overclock adjustments as core option

### ISSUE THREAD

**Issue by markwkidd** [libretro/mame2003-plus-libretro#109]
Edit: As of May 12, Brightness and Gamma Correction are implemented but not yet CPU Overclock

The RetroArch way is to do brightness and gamma is with shaders. Not always cool. So cores often keep their native functions for simple image quality manipulation like these.

Also there is some kind of variable CPU overclock option in MAME. To be explored

Should be easy to hook up some time. It would be interesting to know if they operate independently from the Backdrops, or whether these settings would affect the artwork too.

**Comment by markwkidd** [comment]
I have just pushed a commit to implement the brightness option, this time with 100% less crashing I think.

**Comment by markwkidd** [comment]
@arcadez have you ever worked with the CPU overclock code? I don't remember running across mentions of it so I don't know what it would even be tested with

**Comment by arcadez** [comment]
No i haven't i tended to make clock changes at driver level

**Comment by markwkidd** [comment]
@arcadez It is an OSD function intended to allow users to enable CPU overclocking on the fly. no change needed to the drivers

**Comment by markwkidd** [comment]
I assume with MAME 0.78 you could just press a button and the clock would change.... with some drivers... maybe?

**Comment by markwkidd** [comment]
Update: With the latest commit I have enabled gamma correction as a core option

**Comment by markwkidd** [comment]
Here is the old CPU OSD code. I have to admit I'm not as motivated to implement this until I know what it's good for.

```
  double overclock;
  int cpu, doallcpus = 0, oc;

  if (code_pressed(KEYCODE_LSHIFT) || code_pressed(KEYCODE_RSHIFT))
    doallcpus = 1;
  if (!code_pressed(KEYCODE_LCONTROL) && !code_pressed(KEYCODE_RCONTROL))
    increment *= 5;
  if( increment )
  {
    overclock = timer_get_overclock(arg);
    overclock += 0.01 * increment;
    if (overclock < 0.01) overclock = 0.01;
    if (overclock > 2.0) overclock = 2.0;
    if( doallcpus )
      for( cpu = 0; cpu < cpu_gettotalcpu(); cpu++ )
        timer_set_overclock(cpu, overclock);
    else
      timer_set_overclock(arg, overclock);
  }

  oc = 100 * timer_get_overclock(arg) + 0.5;

  if( doallcpus )
    sprintf(buf,"%s %s %3d%%", ui_getstring (UI_allcpus), ui_getstring (UI_overclock), oc);
  else
    sprintf(buf,"%s %s%d %3d%%", ui_getstring (UI_overclock), ui_getstring (UI_cpu), arg, oc);
```

**Comment by markwkidd** [comment]
I think this CPU clock option might be useful.

Historically it seems like one of the main uses was to overclock Double Dragon -- it turns out that there was some kind of protection code that wasn't fully cracked until 2013 that slowed it down more than the original hardware. (This didn't affect the bootleg versions of the game)

_Tangent: There were major debates from 2000-2013 about whether Double Dragon was playing at the right speed since it would slow down so bad. MAMEdev kept saying for more than ten years when people complained that "it's accurate that way" but then it turned out it wasn't accurate. lol._

At any rate, there may be some times when the overclock is needed -- NeoGeo people use it too -- but I am mainly intrigued at the possibilities for using this for underclocking to tweak performance on low power systems like @KMFDManic does for SNES Classic. If you start looking back at threads from the early 2000s on the BYOAC forums that is what some people were doing with the clock adjustment.

However, the one thing about it is that the system for adjusting the clock speeds doesn't fit neatly into the RetroArch UI paradigm with core options. Each driver can have between 1 and 6+ CPUs (I need to check to make sure what the actual maximum number is, 6 is the most I have observed).

The overclock option needs to be able to be applied selectively to individual CPUs, so at the moment the easiest route to implement this would be to simply make 6+ different core options so that there is one per CPU.

As with some other game-specific options like the vector adjustments, it is possible via libretro to only display core options that are relevant to the currently loaded game but it would take refactoring. That way if there are only two CPUs then only two CPU clocking options would be displayed, etc.

**Comment by arcadez** [comment]
I have a driver which according to the dev that worked on it has hacks in there to
get rid of the slowdown in both Double Dragon 1 and 2, it might be worth porting
across to this core and then users can let us know if the games perform better
or not

**Comment by markwkidd** [comment]
That sounds great.

I was reading about those hacks -- or some similar ones created sometime between 2010 and 2013 -- and I thought about asking you if you knew anything but I decided not to make it seem like I was asking you to do a project.

**Comment by arcadez** [comment]
Funny enough it wasn't hacks per say just cpu clockspeed adjustments, i've implemented
these changes for this core all the slowdown is gone in both games, however the trade
off is their both running a little faster but you dont really notice this in game.

We can always revert this should people who use this core not like it

**Comment by markwkidd** [comment]
Awesome! If there are concerns that it is too fast we can try in current MAME on desktop and compare the two, since the current version is supposed to actually be accurate / full speed now.

**Comment by arcadez** [comment]
I already checked a few vids on youtube "i dont use current mame" plus tried out the games
in FBA, i think Double Dragon is about right, however Double Dragon II seems a little fast
but it's the only way we get around the severe slowdown in that one without a major
overhall of the driver + CPU IRQ and the V-Blank commands on the video side.

**Comment by markwkidd** [comment]
Cool. That seems definitive to me

**Comment by ZappaUtopia** [comment]
Double Dragon now seems more like the speed of current Mame (except for the kidnap intro !) but now Double Dragon 2, Dragon World and Virtual Bowl have slow stuttering sound.

**Comment by markwkidd** [comment]
Ongoing research:

```#define MAX_CPU 8	/* MAX_CPU is the maximum number of CPUs which cpuintrf.c */
					/* can run at the same time. Currently, 8 is enough. */```

**Comment by RaduNastase** [comment]
So, is the overclock/underclock option available in android core of mame 2003 plus?

**Comment by markwkidd** [comment]
I have to admit that my previous work in this area didn't do us any favors. I had thought that it would be possible to implement controls for the MAME CPU as core options, but that was naive on my part.

As I recall, the trouble is that we have to enumerate every possible core option value. To implement the CPU options, the only way I could think of how to do this would be to have multiple CPU core options that each have a lot of different values specified in the declaration.

Soo... it probably means bringing back the MAME GUI/menu way of adjusting things. That's what I mean by my previous work not helping.
