### ISSUE TITLE
TODO: implement TESTDRIVER handler (or something similar) for known-broken games

### ISSUE THREAD

**Issue by markwkidd** [libretro/mame2003-plus-libretro#110]
It seems possible to add a parameter to the XML generator function like `int include_not_working`. If `include_not_working` is set, then the XML includes all games. If it is not set, then the XML omits all games flagged as not working.

There could easily be two entries on the MAME menu -- there is probably space for something like `Generate 'Working' DAT` above `Generate 'Full' DAT`

What do you think @arcadez and @grant2258 ?

**Comment by grant2258** [comment]
yea agreed mark personally my gamelist displays the working status on retropie so i know if its working or not according to the driver information

**Comment by Wilstorm** [comment]
> yea agreed mark personally my gamelist displays the working status on retropie so i know if its working or not according to the driver information

That would be handy. In your game list it shows the working status as part of the title or something?

**Comment by markwkidd** [comment]
Ohh right the gamelist script. That plus a catver.ini is good for RetroPie
and for other RetroArch users.

OK, this is less of an issue than I was thinking. I think we should
actively recommend that RetroPie users use your gamelist system

**Comment by grant2258** [comment]
@Wilstorm 

https://retropie.org.uk/forum/topic/16833/mame-2003-gamelist-xml-with-data-from-the-binary/30

this is how me and mark actually started talking

**Comment by markwkidd** [comment]
Closing in favor of standardizing on grant's script and the catver. New TODO here: https://github.com/libretro/mame2003-plus-libretro/issues/111
