### ISSUE TITLE
Frog & Spiders inputs

### ISSUE THREAD

**Issue by arcadez2003** [libretro/mame2003-plus-libretro#1106]
Being on a classic Taito trip of late i've been plodding away on this new driver over the last week
taken from MAME100 and converted for use in this core, only Jolly Jogger was supported so i then
took these commits reworked the code and spliced into the older driver so we can support 
Frog & Spiders......

https://github.com/arcadez2003/mame/commits/master?after=08b773a665063a35365a4c93fb3c7e9e7be515d3+34&branch=master&path%5B%5D=src&path%5B%5D=mame&path%5B%5D=drivers&path%5B%5D=jollyjgr.c

Everything is fine with one exception i cannot use the dip switches they created for Frog & Spider as they simply
break the game, for the moment i just copied the inputs for Jolly Jogger and spliced in the controls for Frog & Spiders
it works now but obviously since all then settings are wrong it's not ideal.

So @mahoneyt944 or @grant2258 the driver is ready to go and can be added at anytime however if one of ya's fancies
taking a crack at get Frog & Spiders to work with the proper inputs then that would be nice.

jollyjgr
[jollyjgr.zip](https://github.com/libretro/mame2003-plus-libretro/files/6868811/jollyjgr.zip)

Regards

**Comment by mahoneyt944** [comment]
I created a branch for this https://github.com/libretro/mame2003-plus-libretro/compare/Jollyjgr , the make file needs updated and games added to the driver list then we can do live tests with this branch on gitlab.

**Comment by mahoneyt944** [comment]
@arcadez2003  it looks like the dsw2 port was out of order. I switched it around and it seems to be working. Test it on your port and confirm then we can merge this here.

**Comment by arcadez2003** [comment]
@mahoneyt944 Yip all good here good job bigman and thanks for taking the time to sort this, feel free
to do the honors add the driver and mind to credit yourself in the whatsnew

Cheers!!
