### ISSUE TITLE
TODO: add mamemagic2003 to mame2003-plus

### ISSUE THREAD

**Issue by markwkidd** [libretro/mame2003-plus-libretro#111]
Grant would you add your scripts to this repo, maybe within the `/tools` folder?

I had a few ideas in mind to contribute to making it more fully integrated with mame2003 and you reminded me earlier that it is very helpful for RetroPie users who can distinguish between working games and 'testing' games.

**Comment by grant2258** [comment]
ill need to get back to python im new to it havent touched it in days. I do know the new games will probably throw an exception

**Comment by markwkidd** [comment]
Maybe it takes a week, maybe a month, maybe a year :)

**Comment by grant2258** [comment]
np will get to adding it mark

**Comment by grant2258** [comment]
just closing these issues as we know we have to the code to fix it just waiting on nayslayer to port

**Comment by arcadez2003** [comment]
I think we can close this now as grant2258 no longer contributes to this core, and either nayslayer has ported
the code already or if he was going to do it would have been done by now.
