### ISSUE TITLE
Super Bubble Bobble (Sun Mixing, Megadrive Hardware)

### ISSUE THREAD

**Issue by arcadez2003** [libretro/mame2003-plus-libretro#1111]
An arcade version of the ole genesis ripoff Bubble Bobble game surfaced recently and since i always
had a soft spot for it i thought i'd try and get it to work with our ancient code, it runs on 
bootleg MD hardware as do a handfull of others.........

http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=sbubsm&arcade_only=0&autosearch=1

The current driver they use is megadriv_acbl.cpp, this driver was once split into three seperate ones
all using the same genesis hookup, so since Super Bubble Bobble is the exact same type of pcb
as Top Shooter i took that driver from MAME103 spliced in some code for this game then dropped
everything into our segac2 driver expecting it to blowup in million ways but then the game actually 
booted and is fully playable except for one small issue....

The main sound is working but i cannot seem to get the SN76496 samples to work these handle jump
and bubble sounds mostly thankfully the YM2612 handles everything else so the game does at least
have plenty of music and sfx but still it would be nice to get the missing sounds to work.

i've marked the game as imperfect sound and can live with it but @mahoneyt944 or @grant2258 
do you mind taking a look at the code if get some spare time to see if you can trackdown the
cause.

Thoughts 

In latest MAME the game is using two SN76496 sound chips and looking at our ole Segac2 driver
only one chip is supported in the code except for the Megaplay games which use two but the
second chip can only be accessed via the MP bios which wont be compatible with Super Bubble Bobble.

i was hoping the game could be forced to use a single chip and output the sounds in mono but no dice
then again i cant rule out that the SN67496 hookup in the mem maps that all the games in our ole segac2
use might not have the correct address values this game expects. but with no address mapping in the
latest driver for the sound chips im kinda in the dark here as if ours are right or not.

So it might still work in mono with a tweaked address value it might not, the only other way i suppose is to 
actually add support for a second sound chip, looking at the code in latest mame megadriv.c it's so chalk
to our cheese im finding it hard to pindown where in our genesis code to hook it up i've tried a couple
of times but no joy as of yet.

So i thought it time to call in the big guns but hey dont knock yourselves out here a game working with 80%
of the sound where it didn't before can only be considered a result plus this could well be another of those
big ole rabbit holes :)

Here is my latest WIP there is also another new bootleg in there a beat em up with ripped off street fighter
characters called Juezhan Tianhuang it just hung off puckman pockimon with some minor mods so was easy 
enough to add both of the games are indeed playable and can be supported here anytime

[new segac2.zip](https://github.com/libretro/mame2003-plus-libretro/files/6927243/new.segac2.zip)

Regards.

**Comment by mahoneyt944** [comment]
Looks cool. I started a branch for it. https://github.com/libretro/mame2003-plus-libretro/compare/Segac2

**Comment by arcadez2003** [comment]
Thanks man i've not just dumped this onto you right enough, as im still working on this myself but i feel 
more heads are better than one :)

**Comment by mahoneyt944** [comment]
Not entirely related but how do you win level 4-1? This is the 2nd option when you coin up. I can't seem to get to the top? Can't seem to jump off of my own bubble. 
![sbubsm-210804-060516](https://user-images.githubusercontent.com/49591133/128210672-7b39f0de-016d-4bd5-995b-74c7a8f6fe73.png)

**Comment by arcadez2003** [comment]
Hold down the bubble fire button he keeps the bubble in then gets fat and floats :)

**Comment by mahoneyt944** [comment]
I think we should try to live log the sound through the "usrintf_showmessage" to see what's happening here. Seems like a hookup situation.

**Comment by arnoldsecret** [comment]
that driver `megadriv_acbl.cpp` has some rather interesting MD-to-arcade bootlegs, though I can't say for sure if it's worth supporting those.

**Comment by grant2258** [comment]
I'll have a peek when I'm off work

**Comment by arcadez2003** [comment]
> 
> 
> that driver `megadriv_acbl.cpp` has some rather interesting MD-to-arcade bootlegs, though I can't say for sure if it's worth supporting those.

Your right although most of them are using some input hookup which is in no way compatible here, however it might
be possible to backport one or two down the road, but obviously fixing the sound for this game is more important
just now as even if we did support other games in that driver we'll only bump into the same issue eg missing sounds.

**Comment by mahoneyt944** [comment]
@arcadez2003 with you latest memory map changes super bubble bobble is broken. Nothing loading to the level
![sbubsm-210805-184202](https://user-images.githubusercontent.com/49591133/128430631-c2a464c6-6df9-45f8-a077-b7d6beeb1162.png)

**Comment by arcadez2003** [comment]
Hmm it works fine in my build ok i'll revert the changes tomorrow unless you beat me to it :)

**Comment by arcadez2003** [comment]
With thanks to dink the problem is solved it turns out we were missing a write on the Z80 side in our ole driver

**Comment by arcadez2003** [comment]
@mahoneyt944 @grant2258 everything should be good now with this game lemmie know if there
are still any outstanding issues but all's good on my end.

@arnoldsecret i had at look at the other games in this driver apart from Top Shooter which i wont personally 
be adding here as it's just a lame redemption gambler. all the rest are bootlegs of the original megadrive games 
and as such would require special inputs connected to gamepad buttons the code for which we dont have and it 
would require too much graft to hookup it up for this core.

We lucked out with Super Bubble Bobble as it runs on cloned megadrive hardware the code for which we already
had more or less and since it had it's own arcade inputs it just dropped into the driver without too much hastle
barring the sound issues which are now sorted.

Which would not be the case with the others so i'll quit here while im still ahead :) but it's pity we cant have 
Bare Knuckle III etc etc as i would have liked to support that one right enough but ya win some ya lose some
that is always the way of it.

**Comment by arcadez2003** [comment]
Edit never mind i've got Bare Knuckle III up and running just had to port some new input handling 
for it across from the MESS genesis driver

**Comment by mahoneyt944** [comment]
Great work

**Comment by arcadez2003** [comment]
> 
> 
> Great work

Thanks man it wasn't as much hastle as i thought it was going to be, anyway take a peek at the inputs will ya.??
as i know there have been alotta changes in that dept for this core so i just need someone familiar with those to
run a quick eye over the code to make sure the buttons are setup correctly for here

Cheers
[segac2.zip](https://github.com/libretro/mame2003-plus-libretro/files/6950012/segac2.zip)

**Comment by mahoneyt944** [comment]
Sure thing. I'm heading out right now but I can check it out later tonight or tomorrow.

**Comment by arcadez2003** [comment]
> 
> 
> Sure thing. I'm heading out right now but I can check it out later tonight or tomorrow.

Nae bother bigman thanks again

**Comment by grant2258** [comment]
Nice work m8. I'm just up. I guess I have feck all to now haha! Touching anything Sega is a rabbit hole. If the inputs are good on your core it should be fine m8.

**Comment by arcadez2003** [comment]
> 
> 
> Nice work m8. I'm just up. I guess I have feck all to now haha! Touching anything Sega is a rabbit hole. If the inputs are good on your core it should be fine m8.

Well at least you now have more time to do other lazy Sunday type stuff like cut the grass or tinker on the car :)
