### ISSUE TITLE
Core option categories

### ISSUE THREAD

**Issue by mahoneyt944** [libretro/mame2003-plus-libretro#1113]
With this latest PR we are able to support categories or sub menus within the core options menu. See the PR for more details. We can now categorize options, such as vector and artwork options, for better organization.

https://github.com/libretro/RetroArch/pull/12749

**Comment by markwkidd** [comment]
This would also be a good occasion to add the core option "sublabel" descriptions that got added to the API a year or two: https://github.com/libretro/RetroArch/blob/master/libretro-common/include/libretro.h#L1123-L1133

**Comment by mahoneyt944** [comment]
I'd like to sculpt this into our code as seamless as possible. From my understanding, we'll need to default to v1 when frontends don't support v2.

**Comment by mahoneyt944** [comment]
Started a branch for this. Only copied over the header file so far.
https://github.com/libretro/mame2003-plus-libretro/compare/Categories

**Comment by mahoneyt944** [comment]
I started looking at this some and our structure is quite different from the example pr. I think we have to add a new field to init_default for the category, and each core option will get a NULL placeholder if it's not using a category? Does this seem right?

**Comment by mahoneyt944** [comment]
Ok merged first wave #1115. Next is to structure with `retro_core_options_v2_definition` instead of `retro_variable`. This will require a heavy overhaul of `init_core_options()` and `init_defaults()` etc.

**Comment by mahoneyt944** [comment]
Updated: merged #1122 which integrates the new API. Also added a few sub-labels. Still need to add the categories themselves but the structure is ready to go.

**Comment by mahoneyt944** [comment]
Categories are officially added, preliminary organization is mostly complete. So far I have made the following categories:
- System
- Input
- Audio
- Video
- Artwork
- Vector

Some options left uncategorized for the time being....bios options, cyclone mode, CPU clock scale.

**Comment by KMFDManic** [comment]
@mahoneyt944 @grant2258 @arcadez2003 So far, things looking tip top shape:)  And, off the record, a demo of the cpu clock in action, with Cruis'n World!  This had way less chance of running well before we added these changes!  Well, not "user friendly" wise, obviously!  I have some additional changes, bash script, environment wise, which help the Minis chug along a bit better!  

Start the video at 3:45, unless you are curious as to how we "Roll Out" the Cores for the Minis:)

https://www.youtube.com/watch?v=JoB1XI9-Gcw&lc=Ugz6Qx-sAxVOux1v1ed4AaABAg

**Comment by mahoneyt944** [comment]
I guess we can stack this in the complete bin. Any thoughts or concerns can go in a new issue 🙂. Hope everyone enjoys this feature!

**Comment by markwkidd** [comment]
Awesome!
