### ISSUE TITLE
Gitlab servers and pushing commits

### ISSUE THREAD

**Issue by mahoneyt944** [libretro/mame2003-plus-libretro#1114]
@arcadez2003 @markwkidd 

As you guys know, the commits we push here are triggering a full rebuild through the pipeline each time. Unfortunately, having too many commits in less than an hour ties up the servers resources for the other cores. I was asked that we try to consolidate these commits to reduce server resources being tied up the best we can.

This doesn't change much, but we should follow some guidelines when pushing commits:

- limit merges to once an hour. An exception would be if your commit caused a core meltdown 🙃 and in that case we wouldn't want to leave the core in a broken state.
- try to make changes locally and push your changes as a single commit to the master branch. This is best done through creating a single PR with you changes.
- when merging a PR containing multiple commits, it's best to use the "squash and merge" option instead of just "merge". This consolidates commits into one and also looks much cleaner in the commit history down the road.

Other than that keep up the great work. Development here has been awesome 😎

**Comment by markwkidd** [comment]
Got it, thanks!

**Comment by arcadez2003** [comment]
Oki doki
