### ISSUE TITLE
Arkanoid

### ISSUE THREAD

**Issue by arcadez2003** [libretro/mame2003-plus-libretro#1116]
I've noticed something i never knew about before the japan set we support similar to the USA Romstar versions 
of Bubble Bobble has a level select, so the question is should we rename it as per later MAME to reflect this.??

I know alotta users dont bother with the clones but they might like to know that this version has a handy option over 
and above the other sets.

Something like.....

GAME( 1986, arknoidj, arkanoid, arkanoid, arknoidj, 0,       ROT90, "Taito Corporation", "Arkanoid, with level select (Japan)" )

Whatya's think.??

**Comment by mahoneyt944** [comment]
Was it just the description updated in later mame? Or roms too? Probably fine either way.

**Comment by markwkidd** [comment]
FWIW I think updating with the current mame romset name is a good idea.

**Comment by arcadez2003** [comment]
GAME( 1986, arkanoidja,   arkanoid, arkanoid, arkanoidj, arkanoid_state, empty_init,     ROT90, "Taito Corporation",                           "Arkanoid (Japan, newer w/level select)",      MACHINE_SUPPORTS_SAVE )

**Comment by arcadez2003** [comment]
> 
> 
> Was it just the description updated in later mame? Or roms too? Probably fine either way.

Just the description really the romsets are the same, all im suggesting is we stick with the original romset
here but simply add in the extra info to let people know it has the level select mode.

This how it's named in latest MAME......

Arkanoid (Japan, newer w/level select)

**Comment by mahoneyt944** [comment]
That's probably fine I would think

**Comment by arcadez2003** [comment]
https://github.com/libretro/mame2003-plus-libretro/commit/7a5c29c19de6996c9fc7168a3e36fbe39547018e
