### ISSUE TITLE
Bare Knuckle III Dip Switches

### ISSUE THREAD

**Issue by arcadez2003** [libretro/mame2003-plus-libretro#1117]
@mahoneyt944 I've noticed a problem with the dip switches in Bare Knuckle III in my MAME84 core which was not
present in my MAME72 test core, since the our driver is more or less on a par with my mine as i updated it to
support the Megaplay games a while back.

i was wondering if the same issues might be present here and if you could quickly check if the dip switch settings are 
working correctly as the game will be insanely hard more or less unplayable really

They'll be broken if this happens.......

4 coins to register one credit instead of one coin one credit
3 lives instead of one
Very_Difficult instead of Normal difficulty eg more enemies on screen and more dangerous than usual
Unable to change any of the settings

If you get the above then here is a fix which worked for me in MAME84 and should do here, simply replace 
the previous handler for the dips in the barek3 DRIVER_INIT with this...

install_mem_read16_handler(0, 0x380078, 0x380079, input_port_3_word_r );

Thanks

Edit never mind im gonna just add the fix as i've clearly made a bo bo when porting the original code
that's what happens when i dont wear my reading glasses :)

**Comment by mahoneyt944** [comment]
Found and solved fast ha. Nice!
