### ISSUE TITLE
Samurai Shodown V Perfect

### ISSUE THREAD

**Issue by arcadez2003** [libretro/mame2003-plus-libretro#1119]
Is it time to support this.?? or since it's still being sold as part of that special set should we leave it well alone 
for now seeing as we might get a cease and desist or worse, i dont think much of this personally but it has
a fairly big fanclub right enough :) 

i have the code to support it here and a patched rom which will be required but that might not always be the case
but i suppose someone else can always add it from scratch down the road sometime but some new Bios handling
would be required to force the game into AES mode otherwise you dont get the extra feature additions.

Thoughts.??

**Comment by mahoneyt944** [comment]
I'm not really sure.....I'd reach higher up the libretro ladder if you're concerned with legality. As long as your not distributing the rom or any other proprietary property, I can't see how it would be an issue.

**Comment by arnoldsecret** [comment]
I believe the FBN romset has it, maybe use that rom instead?

**Comment by arcadez2003** [comment]
Decided to not add this
