### ISSUE TITLE
MS Pacman Twin MAME84

### ISSUE THREAD

**Issue by arcadez2003** [libretro/mame2003-plus-libretro#1121]
Hi @grant2258 im having some problems with mspactwin in MAME84 i just ported the code across 
and i get the following fatal error on boot...

memory_set_bankptr called with invalid bank1

I know you wrote the decryption for this core but off the top of your head any ideas why it's going wrong
in MAME84, i know the memory handling is totally different MAME79 onwards but certainly i dont see the 
above call which can also be cpu_setbank anywhere in the code.

**Comment by arcadez2003** [comment]
I think it's something to do with the memory_set_opcode_base call, as the code that handles this is totally different 
in this core vs MAME84 i'll have to look at the other drivers using it to see if i can pindown the problem but hey
i could be totally wrong on this.

**Comment by grant2258** [comment]
I've ported mame084 to libretro can you drop the files I'll have a look m8

**Comment by arcadez2003** [comment]
> 
> 
> I've ported mame084 to libretro can you drop the files I'll have a look m8

Here ya go it should just drop in 

[grant2258.zip](https://github.com/libretro/mame2003-plus-libretro/files/6967745/grant2258.zip)

**Comment by grant2258** [comment]
I had a quick look its either the cpu or memory handling it might take a minute for me to see what's going on. The mame memory map has changed as well will have a better look at the weekend hopefully get it sorted. It seems one the first decrypt causing the issue though

**Comment by arcadez2003** [comment]
@grant2258 good luck man i've been tinkering still with this over the last few days, setup the code as per how i think
MAME84 expects it everything looks correct but no still it wont boot which is fucking annoying :)

**Comment by mahoneyt944** [comment]
Current mame added a note about the maps being conflicted, though our maps seem to function ok. Who knows how the original creators hacked this one together. These hacks are limited on resources and most sacrifice some area of game play to incorporate their hacks. Such as parts of sounds, or the fruit bonus, or even flashing the ghosts like the Atari home console did.

**Comment by grant2258** [comment]
@mahoneyt944 these older cores dont directly support encryped cpus well not sure about mame084 as in not familiar with memory  changes atm. The problem is the op codes and operands need to be in different places when fetched as both are decrypted differently.

**Comment by grant2258** [comment]
@arcadez2003 

Change 
```
	AM_RANGE(0x8000, 0xbfff) AM_WRITE(MWA8_ROM)	/* Ms. Pac-Man / Ponpoko only */
```
to
```
	AM_RANGE(0x8000, 0xbfff) AM_WRITE(MWA8_BANK1)	/* Ms. Pac-Man / Ponpoko only */
```
line 910

**Comment by mahoneyt944** [comment]
Haven't been able to look. I'm at an arcade in Hershey park with lots of games right now 😎
![IMG_20210814_122849061](https://user-images.githubusercontent.com/49591133/129454904-db573e10-f0ba-450e-8812-2510e1c71570.jpg)
![IMG_20210814_130020469](https://user-images.githubusercontent.com/49591133/129454906-2ae2cb56-5948-4629-8d29-cff7ac255a16.jpg)
![IMG_20210814_130152240](https://user-images.githubusercontent.com/49591133/129454908-f38ff6b0-c1da-42be-8841-b72c51975af3.jpg)
![IMG_20210814_122924824](https://user-images.githubusercontent.com/49591133/129454911-9039a6f1-d27c-4393-9ef4-730117c5a8fb.jpg)
![IMG_20210814_130032656](https://user-images.githubusercontent.com/49591133/129454913-882f7051-6cdd-495b-a1d2-61ae335336d8.jpg)
![IMG_20210814_122944335](https://user-images.githubusercontent.com/49591133/129454914-e599c755-5421-449c-920a-df026c259adf.jpg)
![IMG_20210814_122949863](https://user-images.githubusercontent.com/49591133/129454916-02ec9ee5-cff6-4b4c-81ef-77742086b7e2.jpg)
![IMG_20210814_130059377](https://user-images.githubusercontent.com/49591133/129454917-d16f2b0f-db72-4546-a970-b0f256e11a1f.jpg)
![IMG_20210814_122956647](https://user-images.githubusercontent.com/49591133/129454919-680454a9-4aca-40ff-9a0a-6c07f123f86b.jpg)
![IMG_20210814_130106109](https://user-images.githubusercontent.com/49591133/129454920-d4b40479-6d5a-4a46-879a-85c09454cb85.jpg)
![IMG_20210814_123001581](https://user-images.githubusercontent.com/49591133/129454922-d6c89e60-7cd0-4bf8-b16b-aac2de7bd8f8.jpg)
![IMG_20210814_130110309](https://user-images.githubusercontent.com/49591133/129454924-ddb38979-572d-463b-8d01-f31f0da1ef14.jpg)
![IMG_20210814_123756315](https://user-images.githubusercontent.com/49591133/129454925-11f21157-4db1-495f-9589-59db37bcd40f.jpg)
![IMG_20210814_130114311](https://user-images.githubusercontent.com/49591133/129454927-36551641-b60f-4418-9de3-9cedfaa78fe7.jpg)
![IMG_20210814_123801593](https://user-images.githubusercontent.com/49591133/129454928-0c1050ea-6472-461f-9275-76eb53d5e6c7.jpg)
![IMG_20210814_130118048](https://user-images.githubusercontent.com/49591133/129454929-322b6d64-a5c3-4d10-8d8e-ae9f2c8fe954.jpg)
![IMG_20210814_125948189](https://user-images.githubusercontent.com/49591133/129454930-2645fe5d-5b8a-4213-9671-a7680099dddb.jpg)
![IMG_20210814_130131179](https://user-images.githubusercontent.com/49591133/129454932-ab065ea0-7d82-4ccf-a64d-d890fe34b5ac.jpg)
![IMG_20210814_125957468](https://user-images.githubusercontent.com/49591133/129454934-65652c45-0667-4e28-899f-de03cec4e396.jpg)
![IMG_20210814_130137010](https://user-images.githubusercontent.com/49591133/129454936-8e480c1c-3586-4924-8a73-af584510c61f.jpg)
![IMG_20210814_130001846](https://user-images.githubusercontent.com/49591133/129454938-b8720282-b0ac-4532-9834-379b281c730b.jpg)
![IMG_20210814_130142189](https://user-images.githubusercontent.com/49591133/129454939-1ac220b6-03a3-4b92-b0b3-17d036c4dd9e.jpg)
![IMG_20210814_130043976](https://user-images.githubusercontent.com/49591133/129454940-ba167503-9b9e-41c5-9c53-e9e6a975f582.jpg)

**Comment by grant2258** [comment]
Hope there set to freeplay or you'll be spending all your cash

**Comment by arcadez2003** [comment]
@grant2258 Aye that's it sorted thanks for taking the time to look at this, cant believe i didn't look at the mem map
being so focused on the decryption side, i guess that's what they mean by cant see the woods for the trees :)

**Comment by arcadez2003** [comment]
@mahoneyt944 some nice games there you'll have square eyes after playing all those.

**Comment by grant2258** [comment]
@arcadez2003  nae bother m8 feel free to ask it not a bother m8. Like you I'm only interested in the emulation side of things

**Comment by mahoneyt944** [comment]
I can't believe how many classics they have, usually modern arcades are caked with ticket games. Not to mention the pricing is still original, pretty much all set to a quarter. Spent about an hour in there and it was fun. I think I had the most fun playing road blaster, never experienced that one before. 

Anyhow, glad you guys got things working 👍. 

Ps: have either of you seen the new core option setup implemented here? I tried to organize it in a thoughtful way but it's definitely challenging configuring a decent appearance for v0, v1 and now v2 versions across all the menu driver skins. It seems ok but probably needs some cosmetics improvement or even a shuffle if it seems wrong in anyway. I'm totally open to ideas on this. Just trying to make sure things seem easy and flows well. 1.9.8 shows the new category fields. Older uses the layout from before but some items are moved around now. Flowing the category organization.

**Comment by grant2258** [comment]
To be honest I don't use the core or ra per say. It's not really good for my setup I'm using in my barcade. I sure the menus will be fine someone will complain if the don't like the you can be sure of that.

**Comment by arcadez2003** [comment]
@mahoneyt944 Like grant i dont use this core but if i ever do i'll let ya know how the new cats are looking but it'll
likely be too late by then :)

**Comment by mahoneyt944** [comment]
I also find that I do more work on the core than actually gaming but it's a fun hobby and I feel people enjoy what we do here regardless. Even the general up keep helps smooth out things for future devs.

**Comment by grant2258** [comment]
I did see the screenshot they looked fine to be honest. The list was too long fwiw

**Comment by mahoneyt944** [comment]
Which screenshot?

**Comment by grant2258** [comment]
Cant remember the github thread might be when the option was added to ra. As far as I read it can't be multi nested might have changed since then don't really keep up with ra changes unless something about it comes up in this core.

**Comment by mahoneyt944** [comment]
Yeah they are 1 level deep subdirectories. I believe the code technically supports going deeper but it was capped at one to keep things simple. That may change at some point.
I created some basic ones for here.
![Screenshot_20210814-232928](https://user-images.githubusercontent.com/49591133/129467716-335ec009-3ab1-47dc-9bd6-64068a352acf.png)
