### ISSUE TITLE
Trying to understand the ffight audio CD fix

### ISSUE THREAD

**Issue by Wilstorm** [libretro/mame2003-plus-libretro#113]
Could you clarify one more thing for me. I might be wrong because something still doesn't make sense for me. Are parent/clone relationship formed within the same driver or can they cross drivers? It seems **ffight** is using the **cps1** driver and **ffight** is using the **ffight_hack** driver. Is that the "logical" boundary for parent/clone relationships when creating a DAT? ffight_hack is like a derivative of cps1. They are related but my thought is to break them due the same ROM is using two different drivers.

I guess looking below it seems the same ROM is using 2 different drivers which doesn't completely make sense to me. The **ffight** ROM is using both the **cps1** and **ffight_hack** driver so how does it know when to use the ROM audio or the CD sample audio for the same ROM set named **ffight**?

```
+GAME( 1989, ffight,   0,        ffight_hack,     ffight,   cps1,     ROT0,   "Capcom", "Final Fight (World)" )
+GAME( 1989, ffightu,  ffight,   ffight_hack,     ffight,   cps1,     ROT0,   "Capcom", "Final Fight (US 900112)" )
+GAME( 1989, ffightj,  ffight,   ffight_hack,     ffight,   cps1,     ROT0,   "Capcom", "Final Fight (Japan set 1)" )
+GAME( 1989, ffightj1, ffight,   ffight_hack,     ffight,   cps1,     ROT0,   "Capcom", "Final Fight (Japan set 2)" )
+
+/*
 GAME( 1989, ffight,   0,        cps1,     ffight,   cps1,     ROT0,   "Capcom", "Final Fight (World)" )
 GAME( 1989, ffightu,  ffight,   cps1,     ffight,   cps1,     ROT0,   "Capcom", "Final Fight (US 900112)" )
 GAME( 1989, ffightj,  ffight,   cps1,     ffight,   cps1,     ROT0,   "Capcom", "Final Fight (Japan set 1)" )
 GAME( 1989, ffightj1, ffight,   cps1,     ffight,   cps1,     ROT0,   "Capcom", "Final Fight (Japan set 2)
```

**Comment by markwkidd** [comment]
The second set of declarations you have there is wrapped in `/*` and `*/` meaning they are commented out. I would imagine that was the existing set of driver declarations from before the hack was added, and were left for reference.

That would be the kind of thing to add in a source comment so it's clearer what's going on in 5 years when we're gone.

**Comment by markwkidd** [comment]
As in something like `/* Existing driver declarations from before Sega CD sample hack are left here for reference. */`

That would be a better coding practice but it's not the end of the world.

**Comment by Wilstorm** [comment]
Ah ok, so they are no longer using the cps1 driver for that ROM? How does it know whether to play the ROM audio or the CD samples audio or are you always forced to use the CD samples audio since there's only one ROM.

**Comment by Wilstorm** [comment]
Ok I think I have the above comment edited enough to explain my thought/confusion clearly as I understand it. :)

**Comment by grant2258** [comment]
@Wilstorm 

here is how it knows to use the samples when its using the hacked version

// For Final Fight.
static MACHINE_DRIVER_START( ffight_hack )
	ff_playing_final_fight = true;
	
	/* basic machine hardware */
	MDRV_IMPORT_FROM(cps1)

+	// Lets add our Final Fight music sample packs.
+	MDRV_SOUND_ATTRIBUTES(SOUND_SUPPORTS_STEREO)
+	MDRV_SOUND_ADD(SAMPLES, ff_samples)
+	//MDRV_SOUND_ADD(SAMPLES, ff_samplesR)
+MACHINE_DRIVER_END
+

it sets ff_playing_final_fight = true;

that sets things in motion at

 static WRITE16_HANDLER( cps1_sound_command_w )
 {
if(ff_playing_final_fight == true) {
( do the samples)
}
else {
		if(ACCESSING_LSB)
			soundlatch_w(0,data & 0xff);
 (use the original)

**Comment by ZappaUtopia** [comment]
I just built the latest source using @grant2258 's setup script and can confirm that the samples work ! I created a new DAT file with the MAME menu but it reports that there are NO new roms. Like I said in the other thread, if you have the samples in the samples folder (eg. for ffight) then you get the CD music. The only way to play with the original Arcade music is to delete the samples. There doesn't seem to be a separate version.

**Comment by ZappaUtopia** [comment]
OK sussed it out now.

Mortal Kombat needs the `mkla1` Game Rom version for the new Samples soundtrack to work. This means you can also use the parent `mk` Game Rom to play with the original Arcade music.

NBA Jam Samples need either `nbajam` or the clone `nbajamr2` for the samples to work. So I use the parent `nbajam` for the original music and use the clone `nbajamr2` for the new soundtrack (you must rename the samples to `nbajamr2` as well).

Final Fight I use the parent `ffight` for the original music and the clone `ffightu` for the new soundtrack (you must rename the samples to `ffightu` as well).

**Comment by Wilstorm** [comment]
Thanks for the info Zappa, that answered it. Are you building from DAT for the ROMs or duplicating the parent and renaming them?

**Comment by ZappaUtopia** [comment]
I used the ones from the DAT, parent and clone.

**Comment by Wilstorm** [comment]
Ok, thanks for testing this. I will build out a new set this weekend. One last question so you can rename the samples to either mk or mk1a1 (matching the ROM) and it will work with either or remove it for ROM based audio. Also the same for nbajam and nbajamr2 and lastly ffight or ffightu. Basically the samples may work with either from each game?

**Comment by ZappaUtopia** [comment]
According to the commit, only mk1a1 works with the samples https://github.com/libretro/mame2003-plus-libretro/commit/1f7b43c69c234ef5bd02fcc7bb97f95723f8a950 and only nbajam or nbajamr2 https://github.com/libretro/mame2003-plus-libretro/commit/06a3b2246f289c0177a129db61a77995a74df0a1

So the `mk1a1` samples will only work with the `mk1a1` rom, this means that if you also have the parent `mk` it will play the original arcade music.

**Comment by ZappaUtopia** [comment]
These new samples only seem to work for the rom thats named the same. For instance, I now have `mk` and `mkla1` in my collection but the new samples will only be heard when playing `mkla1`. If I run the parent `mk` then I hear the original arcade music. This is good because we can have both in the collection !

**Comment by Wilstorm** [comment]
What I would be curious about is if you name it to mk.zip will the CD based audio work then?

Like this example of nbajam in the comments it looks like the samples will work with either set or remove them for ROM based audio so you have the choice of both depending if the samples exists and matches the ROM name is how I interpret the information below.

Sega-CD OST Support for:
Rev3: nbajam.zip
Rev2: nbajamr2.zip

nbajam.zip samples needs to be named to whichever rom set is used

**Comment by grant2258** [comment]
simple fix symlink if you want sample audio in them all

**Comment by ZappaUtopia** [comment]
Yes correct. So in my collection I have `nbajam` which will play the original audio and the clone `nbajamr2` which will play the new audio because I renamed the samples to `nbajamr2`.

**Comment by Wilstorm** [comment]
Thanks Grant, that's a good idea! Can you tell from the code all the ROMs that used the 3 different samples that would need a symlink? I am not completely sure as some are used by several.

**Comment by Wilstorm** [comment]
@grant2258 - I am not sure if the PR has been submitted but your workaround script seemed to work great for installing from source.

**Comment by ZappaUtopia** [comment]
@Wilstorm It tells you in the commit comments that I linked what versions are compatible. mkla1 , nbajam ,  nbajamr2 , ffight and probably all clones.

Please don't make the symlinks permanent as I and probably others don't want the SegaCd sound on all versions !

**Comment by Wilstorm** [comment]
@ZappaUtopia - No nothing permanent. Ok so based off the code these are the ROMs that may use the alternate CD based audio. Unfortunately I wish could figure out definitely what samples a ROM uses. Anyway they need to be renamed to match the ROM.

ffight - Final Fight (World)
ffightu - Final Fight (US 900112)
ffightj - Final Fight (Japan set 1)
ffightj1 - Final Fight (Japan set 2)

mk4 - Mortal Kombat (rev 5.0 T-Unit 03/19/93)
mkr4 - Mortal Kombat (rev 4.0 T-Unit 02/11/93)

nbajam - NBA Jam (rev 3.01 04/07/93)
nbajamr2 - NBA Jam (rev 2.00 02/10/93)

**Comment by Wilstorm** [comment]
Well ok so more to add but not exactly sure which:

**For Mortal Kombat music hack. For Midway T-Unit versions.**
**For Mortal Kombat music hack. For Midway Y-Unit versions.**

**Comment by Wilstorm** [comment]
Ok, I think this is the complete list but if there's any mistakes maybe someone can chime in. Samples need to be renamed to match the ROMs.

@grant2258 - Will these samples be part of the DAT or are folks on their own when compiling these CD audio samples? I think these would be first ROMs or samples that wouldn't be part of the DAT. Hence you would just have to know there is alternative samples that will work.

ffight - Final Fight (World)
ffightu - Final Fight (US 900112)
ffightj - Final Fight (Japan set 1)
ffightj1 - Final Fight (Japan set 2)

mk4 - Mortal Kombat (rev 5.0 T-Unit 03/19/93)
mkr4 - Mortal Kombat (rev 4.0 T-Unit 02/11/93)
mk1a4 - Mortal Kombat (rev 4.0 09/28/92)
mk1a3 - Mortal Kombat (rev 3.0 08/31/92)
mk1a2 - Mortal Kombat (rev 2.0 08/18/92)
mkla1 - Mortal Kombat (rev 1.0 08/08/92)

nbajam - NBA Jam (rev 3.01 04/07/93)
nbajamr2 - NBA Jam (rev 2.00 02/10/93)

**Comment by ZappaUtopia** [comment]
I dont know if the samples work for all the Mortal Kombat versions because the commit said it was optimised for `mkla1` (Y-Unit).

**Comment by Wilstorm** [comment]
Hmmm...this is posted directly in the driver:

```
For Mortal Kombat music hack. For Midway T-Unit versions.
For Mortal Kombat music hack. For Midway Y-Unit versions.
```
Also the T-Unit versions are the ones using the new driver vs the original one.

```
GAME( 1992, mk,       0,       mk, mk,      mk,       ROT0, "Midway",   "Mortal Kombat (rev 5.0 T-Unit 03/19/93)" )
+GAME( 1992, mkr4,     mk,      mk, mk,      mkr4,     ROT0, "Midway",   "Mortal Kombat (rev 4.0 T-Unit 02/11/93)" )
```

**Comment by markwkidd** [comment]
@KMFDMFan, do you have any thoughts on the naming of these files?

**Comment by Wilstorm** [comment]
It would be helpful to have a list of all the ROMs and clones that the new CD based audio works with. I usually rely on the DAT for sample building but that's not possible. Honestly this feels a bit like a craps shoot guessing which games support the new CD audio.

**Comment by Wilstorm** [comment]
>I think these are not in the DAT because they are considered as an optional bonus, they are not needed to emulate the arcade machine, whereas the other samples are needed.

I agree. If we get a definitive list I will probably create an optional DAT for the sets/clones they support.

**Comment by markwkidd** [comment]
Testers: do any of these sample/hack filenames need to change?

**Comment by ZappaUtopia** [comment]
Not really, this thread can probably be closed. You can just rename the samples for the game you wan't them to work with.

**Comment by Wilstorm** [comment]
I did go through each txt file and pulled this list together. I only have 2 questionable entries. In the code it looks like all the ffight clones use the hacked driver. Also in the Mortal Kombat text file it doesn't list mkr4 but it also uses the hacked driver.

It's pretty creative splitting the left/channels stereo channels, and hooking them to allow 1 channel to play back mono on both speakers. It essentially cuts space usage in half and allows some systems that otherwise couldn't utilize these beefy samples due to system limitations.

Anyway the only change to the list is the Mortal Kombat prototype machine.
```
fight - Final Fight (World)
ffightu - Final Fight (US 900112)
ffightj - Final Fight (Japan set 1)
ffightj1 - Final Fight (Japan set 2)

mk4 - Mortal Kombat (rev 5.0 T-Unit 03/19/93)
mkr4 - Mortal Kombat (rev 4.0 T-Unit 02/11/93)
mk1a4 - Mortal Kombat (rev 4.0 09/28/92)
mk1a3 - Mortal Kombat (rev 3.0 08/31/92)
mk1a2 - Mortal Kombat (rev 2.0 08/18/92)
mkla1 - Mortal Kombat (rev 1.0 08/08/92)
mkprot9 - Mortal Kombat (rev 4.0 T-Unit 02/11/93)

nbajam - NBA Jam (rev 3.01 04/07/93)
nbajamr2 - NBA Jam (rev 2.00 02/10/93)
```

**Comment by grant2258** [comment]
@Wilstorm 

#define GAME(YEAR,NAME,PARENT,MACHINE,INPUT,INIT,MONITOR,COMPANY,FULLNAME)

**Comment by Wilstorm** [comment]
@grant2258 - Sorry I don't quite understand what you're pointing out.

**Comment by grant2258** [comment]
yous saying it using a hacked driver its just changing the machine init to use the samples for ff not sure what you mean by hacked driver here

**Comment by Wilstorm** [comment]
Sorry that was grammatically incorrect of me. I should say the questionable ROMs that are not listed in the text files are using an alternate driver vs the original so I a made the assumption they also use the CD audio based samples.

The other neat thing is any sample you don't want to use or if you need to cut down on space you can literally delete it from the sample pack and it will fall back to the ROM based driver. Some platforms have a "resource" limitation and a workaround is required to either split out the stereo or cut down the sample pack to get it up and running. Very creative.

**Comment by grant2258** [comment]
sorry i got my wires crossed the way i read that
