### ISSUE TITLE
Neo Bomberman (Full Non-Merged) default language(Spanish?) can't be changed

### ISSUE THREAD

**Issue by SapphireTactician** [libretro/mame2003-plus-libretro#114]
### Description:

Neo Bomberman, rom name `neobombe`, has its mode select menu language default to Spanish(?) when using the version provided by the MAME 2003 Full Non-Merged Reference Set v3.

I checked the dip switch settings, both hard dip and soft dip for both cabinet and Neo Bomberman, but couldn't find nor access any region or language settings. A quick Google search reveals that certain NeoGeo roms use the language / region setting as defined through the bios... which is inaccessible when using a Full Non-Merged rom set due to being embedded within the rom.

Tagging @markwkidd at his request. Sorry I'm late, things happened.

*****

### Specs:

**OS:** Android 7.0 Nougat (_32-bit_)
**RetroArch Version:** 1.7.2 (*Git 6e46d1d*)
**MAME 2003 Core Commit:** b53550d
**Device:** Motorola Moto G5 Plus (_32GB Model_)
**CPU:** Qualcomm® Snapdragon™ 625 (_64-bit, 2 GHz Octo-core_)
**CPU Architecture:** ARMv7
**GPU:** Adreno 506 (_650 MHz_)
**RAM:** 2 GB

*****

### Expected Behavior:

I should be able to access the bios and change the bios language / region (*when applicable*) if it is not available in the dip switches.

*****

### Actual Behavior:

Game is stuck in a non-english language / region. This makes reading anything beyond the title screen impossible for people who can only speak / read English.

*****

### Steps to Reproduce:

* Launch RetroArch
* Load Core
     * Arcade (MAME 2003)
* Load Content
    * Select `neobombe`
    * Make sure it is from the MAME 2003 Full Non-Merged Reference Set
* Insert Coin
* Press Start
* Observe language issue after tutorial demo completes

*****

### Example:

![screenshot_20180418-235717](https://user-images.githubusercontent.com/24427487/39027103-5d94ce02-441e-11e8-8ff6-2509eeca8b1a.png)

**Comment by grant2258** [comment]
neogeo has a bios select like diehard you can choose a bios i wold need to check it out might be another way

**Comment by grant2258** [comment]
The language displayed depends on the Neo-Geo BIOS. A Japanese BIOS will display Japanese text, a US BIOS will display English text, and a European BIOS will display Spanish text. MAME will use the European BIOS by default.  (for this game)

**Comment by SapphireTactician** [comment]
The latest MAME 2003 Plus commit I'm able to get via RA's Online Updater is 5ff8cb8 . I guess that means I'm stuck waiting on the buildbot before I'll be able to test it.

**Comment by ZappaUtopia** [comment]
I just built the latest source using @grant2258 's setup script and can confirm that Neo Bomberman is now defaulted to English.

**Comment by arcadez** [comment]
Well we may just have upset a few Spanish speakers today :) the language can be set
via the Neogeo service mode as i remember doin that for Ironclad a while back but no matter.

**Comment by arcadez** [comment]
I was only joking bigman!! but the Neogeo service mode is something users should take
the time to learn about as there are many cool settings to be found, like for example how
to turn on the blood and gore for say the Metal Slug games.

**Comment by grant2258** [comment]
Thats just naughty the spanish get it rough enough with trump!!!!!!!! lol. I do agree with what your saying but most users dont really understand how some of that stuff works!

**Comment by arcadez** [comment]
Anyway im not against this per say as i actually took the time to add English versions
of certain games supported in later MAME builds when only the japan region 
had been dumped in the older MAME cores

**Comment by grant2258** [comment]
what happen in fight club stays in fight club!

**Comment by markwkidd** [comment]
I think I have a concept for setting bios region via a core option. Working on it.

**Comment by markwkidd** [comment]
Just merged a BIOS region core option, although Neo Bomberman should still default to English it is now possible to select the Europe BIOS via an option.

**Comment by SapphireTactician** [comment]
@markwkidd Will that option get pushed to the regular MAME 2003 core as well? Still stuck waiting on buildbot cause I have no idea how to install the core on my own...

**Comment by markwkidd** [comment]
@SapphireTactician the buildbot can be monitored in the Discord #buildbot channel... usually it will build a round of mame2003 cores within 10 or 12 hours of a commit being merged. Sometimes there can be a buildbot backlog and things take longer but 10-12 seems typical.

After that, there is a mysterious period between when they are built and when they are copied to the web server. So 12-24 hours total is the best estimate I know to give.

Speaking of which, I just merged one more commit related to Neo Bomberman.

I cannot set that game to use the US BIOS by default, but as of the latest commit, I am pretty sure the BIOS region core option is working consistently so it's no problem to try out either of the 2 US BIOSes for that or any other Neo Geo game.

So give it 12-24 hours and see if you can download an updated copy of the core with this new core option set up. Thank you very much for bringing this topic to our attention. It's good to have even preliminary support for BIOS regions for the first time!

**Comment by SapphireTactician** [comment]
@markwkidd Seems like I was right in suspecting Buildbot was having issues. Looks like Twinaphex fixed it. Was able to test out the new setting, works great. I noticed some regions on the menu have a `-a` such as `us` and `us-a` next to them, I'm curious what the difference is.

@markwkidd Are you able to add this to the regular MAME 2003 core as well, please? Then I can close this.

**Comment by markwkidd** [comment]
`us-a` is an alternate united states BIOS ROM. More than that I cannot say -- you need to talk to one of the  Neo Geo experts out there.

I do hope to add this to mame2003 as part of the next batch of backports from mame2003-plus. I'm not sure when I'll get to that, but should be within a week or two if.

**Comment by SapphireTactician** [comment]
Hopefully it can get backported soon, I don't see a way to add the 2003 Plus core to Lakka, so my ARM boxes are boned.

**Comment by markwkidd** [comment]
you might try to copy two things to your Lakka `Cores` folder via Samba:

1. the `.info` file for mame2003-plus from libretro-super or the RetroArch
in-GUI content downloader
2. ARM version of the latest buildbot build from here:
https://buildbot.libretro.com/nightly/linux/armhf/

That might just work

**Comment by SapphireTactician** [comment]
I'm pretty sure the cores in Lakka go in Lakka's system partition (*unless I remap the cores folder and open the gates of Hell*) which is inaccessible via Samba, but I get the idea, I'll just have to use a card reader and add it manually. The fact that Lakka can't just download / update cores is a royal pain.

**Comment by markwkidd** [comment]
You don't need to remap the cores folder.

Any core and .info file combo you add to the Lakka Cores Samba share will join the ones that are preinstalled. That's the purpose of the Cores Samba share, and it does work.

I have used this method to install later builds of mame2003 onto earlier builds of Lakka several times.

**Comment by SapphireTactician** [comment]
Oh cool, did not know that. Thanks again! :smiley:

**Comment by SapphireTactician** [comment]
@markwkidd  Should I leave this open until it is backported to MAME 2003?

**Comment by grant2258** [comment]
mame2003 is another core can open an issue there if you like im sure mark will add it though.

**Comment by SapphireTactician** [comment]
Ok, will open there and close this here.
