### ISSUE TITLE
The core does not load in Opendingux Beta

### ISSUE THREAD

**Issue by ToniBC** [libretro/mame2003-plus-libretro#1148]
Hello, it turns out that if we put the core of version 1.9.9 Stable that has the `d599f5e` version and we load the core in Opendingux Beta, it loads without problems, but if we put the versions of the latest nightly, that is, the updated retroarch core crashes and you can't load the kernel from the menu.

I have tried putting Retroarch Stable and the updated core and the same thing happens, it does not load it. It is the only core that does not load.

Therefore, something changed since that version that prevents it from loading.

Thanks.

**Comment by mahoneyt944** [comment]
You will have to post a log to help diagnosis this issue. If there is an issue, it seems to be isolated to your platform for whatever reason.

**Comment by ToniBC** [comment]
I tried general the LOG but it is not generated, only the Retroarch startup information is created, but nothing else, since when putting “Load Core” and selecting the core, Retroarch crashes and the log does not register anything in debug mode.

It's not when loading a game or anything, it's just trying to load the core with “Load Core”. All cores load without problems, including MAME 2003 Plus Stable version `d599f5e`, but the latest revisions do not, Retroarch closes when trying to load it.

It is as if from 1.9.9 to the current one, the core did not compile well and is incorrect for Openbigux Beta. As if it were a wrong core.

Like I said, with "Load core", it crashes and closes, but if I put the stable core there is no problem. That is why I say that it is surely compiling wrong.

But more info I can not show, sorry.

**Comment by mahoneyt944** [comment]
RetroArch 1.9.10 stable was just release moments ago. Please test it with the latest nightly mame2003-plus core

**Comment by ToniBC** [comment]
At the moment it seems that this version does load, the 1.9.10 Stable version. So for now we close the topic.

Thank you.
