### ISSUE TITLE
Journey sample bug

### ISSUE THREAD

**Issue by mahoneyt944** [libretro/mame2003-plus-libretro#1177]
Found a bug. Restarting through the RA menu causes the sample to not work.

Tested by starting the game with service menu dip switch activated to load into the service menu,  use the cassette test. Note the sample works, enter RA, hit restart. The game should restart back into the service menu, now the sample will not play. 

I think this has to do with the sample loading on restart, this sample being large maybe part of it too. May need to free loaded samples and reload?

**Comment by grant2258** [comment]
@mahoneyt944 its the resources freeing happening.  Samples are handled different from other sound devices they are freed and not reloaded I know our runloop has changed need to find where we should handle the samples properly.

https://github.com/libretro/mame2003-plus-libretro/blob/1fd30e32ec948da4227b5eb7af327fddd6c7115b/src/cpuexec.c#L342  removing this stops the auto_mallocs freeing and everything is fine. Ill need to check the original mame source and see if a inhereted bug or something that changed this end. I have to drop the subframe of car and see if i need a new steering rack so might not be able to do this if i get the time i will

**Comment by mahoneyt944** [comment]
I've been rebuilding my tron machine. The thing was starting to become a fire hazard. It has 4 uv lights that bake the wire harnesses 24/7 and the crt is basically a big magnet for dust. Lots of fun ha

**Comment by grant2258** [comment]
yea I know the feeling of fixing things fixed my mums tv wasnt coming on popped some caps in the psu after testing for bas ones and it turned on fine didnt think much else of it gave her it back. Get a call its making a screeching sound if you leave it off a while and turn it on yea you guessed two more bad caps on the main board. First time ive came across this in a main board on a tv though didnt have any surface mount caps so just put some radials in it jobs done. Honestly its must have been so damn time consuming diagnosing bad caps without a scope or esr meter back in the day.

**Comment by grant2258** [comment]
you know what i need some sleep i converted the to kilobytes megs of megs its just below 10 megs as it is set now:)

**Comment by mahoneyt944** [comment]
How many individual samples are that large? I know journey is due to it being a whole song. Probably the most Samples too.

**Comment by grant2258** [comment]
not sure to be honest but here is a fix for now till one of gets the time to look into it more. The sample support will need updated and the mixer as well to support this in any meaningful way and we defo need to loose the auto_mallocs for dynamic allocating de-allocating.

here is the fix for now the mixer only sets up one time it can be updated on the fly. For example load journey into service mode dont play the sample then reset it. Then play the sample it will work.  Now reset again and youll see its gone, 

Ive put a fix here temp fix here until someone has the time to implement it. 

https://github.com/grant2258/blaster-barcade/commit/e95f63a1aa6fcbd3114249f1157139ea5a0ff072

With this fix youll see whats going on play the sample reset and do it again and it will start where it left off where you where so that paused sample needs dealt with on reset at the very least. I will sort it have a few spare moments but best fixing it for now it never worked properly anyway I fixed ost as teh bigger samples in sf2 always caused me issues i fixed it in my branch though.

**Comment by grant2258** [comment]
This will fix the issue im not willing to track everywhere this pointer is used any free with a reference to it will cause issues its up to you if you want to add a de allocate the mixer

**Comment by mahoneyt944** [comment]
Where it's paused at should start there after a soft reset since in the real machine, the eight track player wouldn't have rewound itself either. So that sounds right to me. As far as freeing things, I haven't looked into any of that and admittedly doesn't sound like a fun task.

I think it would be best to heavily test a new and complete implementation here before commiting anything to be sure we aren't introducing new issues.

**Comment by grant2258** [comment]
Not sure exactly where your coming from we aren't emulating a tape cassette. This core also never had pause support or unloading of samples. Either way you'll need to re write the code to keep samples loaded and stop samples on reset that's will work with current code all you need to do is stop all sample to current code added easy enough  Or you'll have to do some real work on the mixer and samples and support states on reset. Is up to you if you want to do this

**Comment by mahoneyt944** [comment]
Journey's sample that we use here, was originally played via a 8-track player inside the arcade machine. when the bonus level ends it just hit pause on the 8-track player and would play again when the next bonus level was encountered.. if the song reached the end it would rewind the tape and rinse and repeat the process.

So our sample support is effectively recreating this functionality.

**Comment by mahoneyt944** [comment]
Here's a video showing the setup at 3:30
https://m.youtube.com/watch?v=lNikyy11q5U&t=571s

**Comment by grant2258** [comment]
I know that but when you close mame you'll need a save state to remember as well. If you willing to put the time in to do that fair  enough.. personally I think it's not worth the effort  but if your up for it. I'd say go for it.

**Comment by mahoneyt944** [comment]
On a fresh boot starting at the beginning of the song is ideal I think. I don't see any reason to save that data between sessions. On a soft reset though we shouldn't free the sample and such as you described. Seems most logical to me. So I think we agree on this. These changes just need tested with a variety of samples and situations before we push it. I'm willing to help test but I'd have to study this area of the code more to actually do anything with it. It's not an area I've messed with much. I'll look at it over the next few days when I get a chance.
