### ISSUE TITLE
LED interface code in mame2003.c causes IOS build error

### ISSUE THREAD

**Issue by markwkidd** [libretro/mame2003-plus-libretro#118]
There is some LED interface code in `mame2003.c` that causes a compiler warning in mysys2 but is enough to stop the IOS 9 build process: http://p.0bl.net/401

This LED code is mysterious to me. @twinaphex do you know how that LED code is supposed to work? I don't know if I have ever seen any docs on it or read any discussion about its function

**Comment by grant2258** [comment]
i take thats for keyboard leds?

**Comment by markwkidd** [comment]
It must be but I have not investigated since it turned out to be a C89 issue

**Comment by grant2258** [comment]
was just curious is all
