### ISSUE TITLE
The Eve Of The Typhoon

### ISSUE THREAD

**Issue by arcadez2003** [libretro/mame2003-plus-libretro#1183]
Might this be worth looking into supporting here.?? certainly a src would help however it might be possible to
just rip out the roms and build a rom loading table from em for use in our ole NG driver......

https://ozzyouzo.itch.io/teot

**Comment by mahoneyt944** [comment]
Looks pretty interesting. I'd say it's worth a try.

**Comment by arcadez2003** [comment]
Hmm i looked into this a little more today the current version is only a WIP release really.....

https://ozzyouzo.itch.io/teot/devlog/254127/alpha-version

Maybe better to wait for a stable final version further down the road i'll close this for now
