### ISSUE TITLE
[Request] Add an option to swap mouse X/Y axis

### ISSUE THREAD

**Issue by wn2000** [libretro/mame2003-plus-libretro#1184]
As the title suggests. This will come handy in case:

- A mouse hardware (trackball/spinner) is incorrectly wired so its X/Y axes are swapped, and you do not want to or cannot easily rewire it.
- You simply want to use the mouse Y axis as the dial control. The option `dialsharexy` enables player 2 to use player 1's mouse Y, but it's only for player 2. Sometimes you may want to use mouse Y for player 1 (due to physical placement of spinners for example).

**Comment by mahoneyt944** [comment]
Many of the common mouse, trackball, and spinners support this already in software. Are you experiencing this with a particular brand?

**Comment by wn2000** [comment]
I'm using the [Legends Ultimate cabinet](https://www.atgames.net/arcades/legends-ultimate), which has a trackball and two spinners (as X/Y axis of another mouse). Their front-end does not offer this feature. And even if it does, this needs to be enabled on a per-game basis, as you may not want to swap X/Y for every game. So it'll be great if the core has such an option.

**Comment by mahoneyt944** [comment]
This should solve your issue, please test the new core option and let me know thanks!
https://github.com/libretro/mame2003-plus-libretro/commit/4f05703a46d6667b7df6125e5baa8d5b512d7c16

**Comment by wn2000** [comment]
Awesome. Will test shortly.

**Comment by wn2000** [comment]
This works as expected. Thanks for the quick add!
