### ISSUE TITLE
Defender and Stargate cheat input port bug

### ISSUE THREAD

**Issue by mahoneyt944** [libretro/mame2003-plus-libretro#1186]
When using the cheat input ports, if you press left and thrust the ship will reverse. Expected behavior would be to continue facing left unless right is pressed. Appears that combining cheat keys with standard keys may be causing false presses.

https://github.com/libretro/mame2003-plus-libretro/blob/755e64ed8c7f1fdc5d69e65084a3355c51107937/src/machine/williams_machine.c#L695-L717

https://github.com/libretro/mame2003-plus-libretro/blob/755e64ed8c7f1fdc5d69e65084a3355c51107937/src/drivers/williams.c#L700-L728

**Comment by arcadez2003** [comment]
Yeah i was never one to use cheats myself as quite often i found they'd make the games behave
strangely or crash, likely a code anomally tucked away somewhere finding it will be the fun part
if only there was a cheat for things like that eh :)

**Comment by mahoneyt944** [comment]
I believe it's just one of the bitwise operators, I think it just needs another condition or something. Probably an easy fix but bitwise stuff can be tricky to follow.

**Comment by mahoneyt944** [comment]
Fixed with #1187
