### ISSUE TITLE
Kyukyoku Tiger 2 Players Version

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/mame2003-plus-libretro#1189]
Saw this commit on https://github.com/finalburnneo/FBNeo/commit/b41f792c03a48230d2050a2cb2f7638a70e5b2fd and thought it'll be a worthwhile add, information from https://neo-source.com/index.php?topic=3890.0 states that the only difference is that b30_02.8j and b30_04.8h are different, wiring in 2p on this thing is another beast depending on how complicated our driver is.

**Comment by arcadez2003** [comment]
Well it looks simple enough i'd take the romset from the original japanese set swap in the two different roms you mention
above then simply hook it up to use the USA version inputs

**Comment by arcadez2003** [comment]
@mahoneyt944 @arnoldsecret i've setup ktiger2p in our tcobra.c driver i've hung it off the older ktiger romset
so the clone should work here and plugged it into the twincobrau inputs, the only problem is i cant mind how 
you glean the SHA1 info for the romset how is that done again.??

**Comment by grant2258** [comment]
https://github.com/tristanheaven/gtkhash/releases/tag/v1.4

**Comment by mahoneyt944** [comment]
My desktop has a "right click" menu option to get the sha1

**Comment by grant2258** [comment]
I think you need 7zip installed to get that menu

**Comment by arcadez2003** [comment]
Thx guys as always

**Comment by arcadez2003** [comment]
https://github.com/libretro/mame2003-plus-libretro/commit/ca06b8fe1d979e9aa2f6df3f6bab4417a5d799f0

Not tested right enough but i think everything should be fine

**Comment by mahoneyt944** [comment]
I'll test these games later tonight. Just got my tron machine rebuilt and playable again. Still need the new molding and decals put on. But happy to see it alive again.
![IMG_20211114_153216470](https://user-images.githubusercontent.com/49591133/141698539-0ac51ed4-3742-4d6b-9eb1-6ad747719be6.jpg)

**Comment by mahoneyt944** [comment]
Seems ok. Boots and plays. Not too familiar with the game though.

**Comment by cinnamonmatexfce** [comment]
> Saw this commit on https://github.com/finalburnneo/FBNeo/commit/b41f792c03a48230d2050a2cb2f7638a70e5b2fd and thought it'll be a worthwhile add, information from https://neo-source.com/index.php?topic=3890.0 states that the only difference is that b30_02.8j and b30_04.8h are different, wiring in 2p on this thing is another beast depending on how complicated our driver is.



Sorry guys, can you please help my understanding why I got wrong (SHA1)hashes?
I used https://bbbradsmith.github.io/ipstool/

Comparing the patched roms against your https://github.com/libretro/mame2003-plus-libretro/blob/master/metadata/mame2003-plus.xml I got wrong SHA1 values (but the CRC32 is correct...)
```
CRC32    SHA1                                              Size  Name
-------- ---------------------------------------- -------------  ------------
321E2BE6 03B2C530326D1859B66829B49555D862BE235643         32768  b30_02 (patched).8j    <<< good CRC32, but SHA1 is wrong
1D63E9C4 BDF013487A6FE8F8CBB03FDA5F4FAE881064831C         32768  b30_02.8j              <<< original ROM
203E36B1 56C97523D243927C09F02979D2A208A281EED4B5         23162  b30_02_8j.ips          <<< wrong CRC32, but SHA1 is good
C3F960FF CBEBF576D677CC02F4D0F22DCC226E898D4832C6         32768  b30_04 (patched).8h    <<< good CRC32, but SHA1 is wrong
03957A30 D809881A16B05595B6F184E44A36E592F46BA04A         32768  b30_04.8h              <<< original ROM
593E7F2C F93D0B72BEDEE65268E3AA4B20FA59DA82E29CCF         25125  b30_04_8h.ips          <<< wrong CRC32, but SHA1 is good
-------- ---------------------------------------- -------------  ------------
```

I am really new (and n00b) about IPS patching... Am I doing something wrong?


Thanks in advance

**Comment by arcadez2003** [comment]
I know nothing about ips patching simply because i've never bumped into any roms i wanted which required it
all i did was take the ktiger2p romset from this site and then created the SHA1's for each individual rom......

https://neo-source.com/index.php?topic=3890.0

**Comment by cinnamonmatexfce** [comment]
How did you manage to get the correct set? The downloadable [ktiger2p.7z](https://neo-source.com/index.php?PHPSESSID=acaj2fb1mp81m1fa2433p7gla7&action=dlattach;topic=3890.0;attach=24067) only contains `*.ips` patches... I suppose original roms (`b30_02_2p.8j` and `b30_04_2p.8h`) should be patched (`b30_02_8j.ips` and `b30_04_8h.ips` respectively), but I cannot get the correct hashes.

**Comment by mahoneyt944** [comment]
What are the hashes before you patch?

**Comment by cinnamonmatexfce** [comment]
> What are the hashes before you patch?

```

CRC32 SHA1 Size Name -------- ---------------------------------------- ------------- ------------ 321E2BE6 03B2C530326D1859B66829B49555D862BE235643 32768 b30_02 (patched).8j <<< good CRC32, but SHA1 is wrong 1D63E9C4 BDF013487A6FE8F8CBB03FDA5F4FAE881064831C 32768 b30_02.8j <<< original ROM 203E36B1 56C97523D243927C09F02979D2A208A281EED4B5 23162 b30_02_8j.ips <<< wrong CRC32, but SHA1 is good C3F960FF CBEBF576D677CC02F4D0F22DCC226E898D4832C6 32768 b30_04 (patched).8h <<< good CRC32, but SHA1 is wrong 03957A30 D809881A16B05595B6F184E44A36E592F46BA04A 32768 b30_04.8h <<< original ROM 593E7F2C F93D0B72BEDEE65268E3AA4B20FA59DA82E29CCF 25125 b30_04_8h.ips <<< wrong CRC32, but SHA1 is good -------- ---------------------------------------- ------------- ------------
```

**Comment by mahoneyt944** [comment]
Google "ktiger2p wowroms" that seemed to work for me. Loads like it should.

**Comment by cinnamonmatexfce** [comment]
> Google "ktiger2p wowroms" that seemed to work for me. Loads like it should. No need to patch.

Gotcha, thanks!! 💪

**Comment by mahoneyt944** [comment]
@cinnamonmatexfce my apologies, the sha1 values listed in the generated dat file were not correct for b30_02_2p.8j and b30_04_2p.8h

I pushed a commit to fix this which should solve your initial issue here.
