### ISSUE TITLE
Bypass audio skew core option default

### ISSUE THREAD

**Issue by mahoneyt944** [libretro/mame2003-plus-libretro#1193]
mame2003 and 2003+ have opposite defaults for this setting. Never really paid much attention to it but recently noticed that tempest crackles when this setting is enabled (2003+ default). I'd like to add a proper description to this core option to make it clearer to the user when and why this setting is used. It seems like 2003+ default should be disabled as well and perhaps this was a simple typo of sorts at some point?

I was hoping someone might elaborate on this option some so I can add a proper description.

**Comment by grant2258** [comment]
just compiled the latest ra and plus no crackling here for linux unless im missing it here can you post a sample of it? Audio skew should be covered in the ra docs its basically speeds certain games up and changes the audio speed and the game speed. I dont use the core if android is doing it check linux and windows changing the default isint a big deal if you dont mind dealing with people say game .... is running the wrong speed. I cant test on windows as i dont have it installed.

**Comment by mahoneyt944** [comment]
It wasn't android, this issue was on a rpi3b+ using RetroPie. I've had tempest in my one cabinet using mame2003 and using it's default setting of disabled. When I switched it into my other cab that uses 2003+ I noticed the Audio sounding off. It would lightly crackle here and there as you play. 2003+ default is enabled. So I changed the setting to disabled and the audio sounded right again.

It looks like the option changes how the timing is adjusted when it's not in sync. enabled tries to match the timing where disabled tries to adjust it by a hard coded value? Not sure which is best and some games properly prefer one way or another to get the clearest sound. Maybe there's a better was to manage this?

**Comment by mahoneyt944** [comment]
As long as there's no frames_per_second drop, both options will use the set sample rate. Its when there is a drop that it differs how the sample rate is corrected. "enabled" tries to match the rate where as "disabled" just drops the rate to 22050.

Neither of these seem like the full solution up front. With matching in a frame drop this gets the sync to be accurate but if we are in a drop it could prolong the drop. Essentially pushing accuracy over performance.

With dropping to 22050, this would relieve the drop but it's not accounting for all the sample rates? What if we had the rate set to 8000? We would be raising the rate in a frame drop.

I think a temporary drop is the better of the two options but this needs to account for all the sample rates. Some nested if statements could solve this.

https://github.com/libretro/mame2003-plus-libretro/blob/841e44dff953a346127f15be53cb34778e20ce1c/src/mame2003/mame2003.c#L535-L552

**Comment by mahoneyt944** [comment]
So I ended up creating a branch with these changes to test out. Basically, "enabled" matches the timing. "disabled" lower the timing one notch below the drop.
https://github.com/libretro/mame2003-plus-libretro/compare/Timing

**Comment by grant2258** [comment]
Do you understand what this code is actually doing?

**Comment by grant2258** [comment]
Tapper and starwars are games with odd framerates that did cause the issue for have to drop the sample rate and the buffer over flow issues. 

For the audio skew issue see any 57fps game roboco ect your can see teh speed difference with it on. Tempest shouldnt be triggering any of these as far as i remember it runs 60fps could be wrong though. I know some vector games run odd framerates

**Comment by mahoneyt944** [comment]
Well Im certainly not an expert on this but as a musician I feel comfortable with audio stuff to some degree. The change I made, the "disabled side", pretty much works the same way as it always did. The difference is it lowers the sample rate with industry standard rates (also the rates we use in the sample rate selection) based on the users choice. This has the highest compatibility with things like single and dual channel amps. Most tvs "HDMI" based devices have internal leveling software that by proxy will level non standard rates so it not very noticeable.

2003 has used "disabled" on this setting as far back as I can see in the commit history.

I've also switched my one cabinet with about 150 games to mame2003+ and hand tested every single one. The audio has either improved or is the same.

**Comment by grant2258** [comment]
Haven't checked to be honest as long as the rate is equal or below the fps it should be fine if your sample frame doesnt take longer to play the fps will go up. I've never heard any reports on Audio breaking up on this is new to me.

I don't like the music playing too fast for the audio screw with a higher pitch with the audio screw and the game playing too fast. Again  it's personal preference if you want things as they should be or running too fast by default.  That all the bypass does the sample rate drop is something seperate

**Comment by mahoneyt944** [comment]
I'm seeing very good results with the setting "disabled" on a rpi3b+ now.

I will have to experiment with the "enabled" setting with these isolated games that have issues. Most notable in tempest and in mspacman when the fruit is moving around the screen. Oddly this doesn't happen on Android. I'm wondering if this is a platform issue or perhaps the sample rate timing is sensitive to certain amps. There's also HDMI vs the aux jack on the rpi3b+. I'll try different combinations to see if I can single out it being software or hardware.

**Comment by grant2258** [comment]
raspberry pi is using an older retroarch could be that not sure again its not big deal at the end of the day its only a default.

**Comment by mahoneyt944** [comment]
You're right haha. Though admittedly it has my curiosity. I've been using the enabled setting for a long time and just noticed this while I've been building my new cab. I never considered the RA version. Very good point.

**Comment by grant2258** [comment]
you can change the audio skew setting in ra not to do this anyway its just a pain for new users so things just work

**Comment by grant2258** [comment]
Try rampage and see if you have and audio issues this will only happen if your using the audio jack if it's a problem fix is here. This is a very old issue though don't know if it still is one.
https://retropie.org.uk/forum/topic/17828/rampage-sound-issue-retropie-4-4

**Comment by mahoneyt944** [comment]
Yeah I've seen that before. And have used the fix.

Do you have a rpi3? If so what's your average fps in tempest during game play? I'm testing on a spare unit, older build but it's averaging in the 40s didn't expect that.

**Comment by grant2258** [comment]
dont know to be honest will check when i get time. Need toput a bush in the subframe and finish painting my bits. Its normal for some vector gamre to run odd fps like starwars ect. I dont think all of them do though.

**Comment by mahoneyt944** [comment]
That sounds like a pain. I was able to get the fps up by lowering the output resolution in the rasp-config. I was using the default setting too. Seems like tempest is sensitive to it even umk3 was playing an normal fps

**Comment by grant2258** [comment]
I dont know why your lowering the out on raspi the vector resolutions are in the video options. It does seem 1024x768 is too much for the pi 640x480 ran ok still a but slow. Theres not much i can  audio will break when games run slow there is frameskip option to try though.

**Comment by mahoneyt944** [comment]
seems to run fine with the lower vector res set. Maybe we could use platform defined default for pi?

**Comment by grant2258** [comment]
its not that big of deal just test the 57 fps games with and without this on your can also change the audio skew setting to fix this and document it and remove the timing option all together to be honest.
