### ISSUE TITLE
[WiiU] Rotating Game Rotates Ozone UI

### ISSUE THREAD

**Issue by Ploggy** [libretro/mame2003-plus-libretro#1196]
The Games Rotation is messed and so is the Ozone UI.
For example with the Game 19XX the screen is upside-down and the Ozone UI is rotated to the right, any attempt to adjust the rotation in the settings not only adjusts the Game but the UI too.

EDIT: This seems to happen on both the Arcade Cores (Mame/FB)

**Comment by grant2258** [comment]
what is Settings - Video - Output - Screen Orientation set too not sure about the wiiu port but it should be on normal.

**Comment by Ploggy** [comment]
yes set to normal

**Comment by grant2258** [comment]
Ah the wii u must not support rotation out port lets Ra deal with rotations it can do else mame does it if its unsupported one the frontend cant handle. Unfortunately RA needs to tell us it cant rotate then we can do it.

**Comment by grant2258** [comment]
listen this isit an ideal solution turn tate mode on in the options then rotate the game in Settings - Video - Output  you should be able to go from there

**Comment by Ploggy** [comment]
Using these tips I can rotate the Game Screen so it's correct but the Ozone UI/Mame Menu are still is all over the place, the XMB UI doesn't have this issue and doesn't rotate with the Game Screen. 

I guess I should make a RA issue instead of a Core issue?
Thank You for your advice :)

**Comment by grant2258** [comment]
Sorry I cant help with the ozone issue but at least you can play the games hopefully I know its a pain

**Comment by Ploggy** [comment]
No probs, thank you for your help :)

**Comment by grant2258** [comment]
ive put a pull request in here it should fix your issue hopefully. https://github.com/libretro/mame2003-plus-libretro/pull/1197 please see details you need a specific version of RA

**Comment by Ploggy** [comment]
Ok after abit of trial and error I got this to compile (took ages) lol and so far so good :)
I tested 19XX again and now the Games screen is the correct way AND the Ozone UI is correct!

I did get a this WiiU Crash Error when I tried to load another Game but that maybe unrelated?
![20211121_214029](https://user-images.githubusercontent.com/1160255/142780041-a9c01069-670f-40ba-8f53-2536955c0b01.jpg)

**Comment by grant2258** [comment]
What game is it will tell you if it crashes my end

**Comment by Ploggy** [comment]
It happens if I load one game, then another.. in this case it was 19XX then Twin Cobra , but it has happened loading a Mame2003 Plus game then a Snes game :/

It happens if I load a Mame2003 Plus game then any other game from any core.

**Comment by grant2258** [comment]
Try the nightly builds see if it happens there or if it's new. The only thing I would suggest is settings->core disable rotate and start the core again. It's only  the core you need with pull request added.

**Comment by Ploggy** [comment]
Thank You, I already have rotate disabled in Settings>Core :) as you said in your PR.. I'll grab the latest nightly and see if it still crashes there ;)

**Comment by grant2258** [comment]
I not getting any crashes here with the same games for what its worth. another good shooter is fshark btw. I did say to get 13.2 but the later you can get the better was to save you compiling is all not sure if the wii u is static or not.

**Comment by Ploggy** [comment]
OK, hang on. it looks like just disabling rotation in Settings>Core fixes the Screen/UI issue, makes sense..
Your fix does fix the Screen (with rotation still enabled) but the UI is still rotated.. I know that's not part of the fix though ;)
I quite like Blazing Star :D 
I assumed 13.2 was the latest.. lol
WiiU is Static .. I think.

The current nightly version doesn't crash when loading a Mame game and another. So it seems it is introduced with your fix :/

The takeaway is that just disabling rotation in the Core Settings seems to fix the issue but it still should work with rotation enabled?

**Comment by grant2258** [comment]
try testing the same nightly ra commit and mame2003-plus as the one you compiled to rule RA out.  It could be some fixes that sorted the issue. So the easiest way to do that is compile the plus core again without my patch and see if it crashes. That will let us know if its causing it or not/

The ui rotates fine here in testing.  Will let @mahoneyt944  get some people to test and will get some  feedback. If the platform is static you would need to compile it all at once.

**Comment by Ploggy** [comment]
I can do that, but it'll have to be tomorrow, it's getting late here. Thank You for looking into this ;)

**Comment by grant2258** [comment]
Well i only usually do weekends when i have some time isint a rush so just compile the normal core and ra that failed if you get the time that will lets us know if this is causing you issues and we can deal with it another way

**Comment by Ploggy** [comment]
Huh? ok I built the Core without your fix as suggested and it STILL crashes when I load 2 games.. So a ME problem. Nothing to do with your fix :P..

**Comment by grant2258** [comment]
Well thats new it wasnt me that broke it haha! In all seriousness it might be best asking the libretro folk about compiling this it might be something simply over looked or something that was fixed in ra. since it worked on the nightly try compile that exact commit the nightly had if you still have issues ask the libretro folk about the compiling issues. Try it all without the patch.

for testing with my patch settings/video/output should be nornal and disable core rotation in the core settings.

**Comment by Ploggy** [comment]
Its more than likely a setup issue on my side, I'm not very good at this kind of stuff.. would it be possible to have your PR merged then I can test the official buildbot version.. Then if there is an issue with the fix (likely not) it can just be reverted?

**Comment by grant2258** [comment]
Well to be honest you im not part of libretro and im not sure about the wii u cfw stuff at all as i dont have one. you would need to ask @mahoneyt944  if he could do this for you. He is approachable all he can say is no I guess

**Comment by mahoneyt944** [comment]
Had to revert, many games were loading incorrectly rotated. Need to sort that out and we can try again.

**Comment by mahoneyt944** [comment]
Tested 1941, the log never executes inside the if statement, though the if statement itself probably changes the rotating in itself.

**Comment by Ploggy** [comment]
More test results (All tested with Allow Rotation = ON

Mame2000:
Ozone UI Bug = NO
Game Rotation Bug = NO

Mame2003 Plus:
Ozone Bug = YES
Game Rotation Bug = YES

FBA2012:
Ozone Bug = YES
Game Rotation Bug = YES

FBNEO:
Ozone Bug = NO
Game Rotation Bug = YES

**Comment by grant2258** [comment]
@mahoneyt944 what settings are you using when testing on android? @Ploggy  Allow Rotation = ON should be off ad RA rotation doesnt work on your port to enable this fix it should be off to let mame do it.

**Comment by mahoneyt944** [comment]
everything is set to default settings, outside of the core options.

**Comment by grant2258** [comment]
what other platforms? he is only testing wii u and the rotation doesnt work there and always done this. I posted in this pull request you need at least 1.9.13.2 more specifically this commit. https://github.com/libretro/RetroArch/commit/211e7d4094bdf16af5e86db74590627c05b3835a without this commit issues will happen

**Comment by grant2258** [comment]
ill pick this up again after the latest stable because I dont know what commit is being tested and what version or ra or plus is in use since this was reverted we will need to know what commit he has on plus and ra

**Comment by grant2258** [comment]
There is far too much confusion in this issue. Teh simple fact is the wording of the option makes you assume core allow rotation should be on that should actually read let ra do the rotation and this should be off for wii u since the rotation doesnt work properly.

**Comment by mahoneyt944** [comment]
I tested the PR (that's now been reverted) and games such as 1941, 1943, food fight, etc will display at the wrong rotation when "allow rotation" in settings-> core is enabled. This being tested on 1.9.13

I know you mentioned 1.9.13.2 has to be used but we can't push a commit that breaks all other frontends that don't have the return false fix in place. So we'd need to figure out a compatible fix to support both cases. Or perhaps we need to focus on wiiu specifically and fix that platforms rotation issue.

**Comment by mahoneyt944** [comment]
@Ploggy @grant2258 the latest commit compiled here https://git.libretro.com/libretro/mame2003-plus-libretro/-/jobs/1162896 or you can wait for the nightly build to catch up usually within 24 hours.

**Comment by grant2258** [comment]
@mahoneyt944  fixed the code should be fine for android but left it define in for wii u as thats the targeted for

**Comment by mahoneyt944** [comment]
Merged again. Tested fine on Android. With 1.9.13

**Comment by Ploggy** [comment]
Thank you :) I'll have to wait until it hits the buildbot, I wont be around much Today.. I'm sorry if I contributed to the confusion :P
I'll report back once I test it :)

**Comment by Ploggy** [comment]
Ok, got a chance to try out the build.. Rotation is now correct with the fix :) thank you @grant2258 @mahoneyt944

**Comment by grant2258** [comment]
glad its sorted for you this core is really for the lower end hardware!

**Comment by Ploggy** [comment]
Yea, for the most part the WiiU handles Mame 2003 Plus pretty well, the CHD's dont run great but that's understandable. 
Thank you for your help and the fix :)
