### ISSUE TITLE
mame directory setup

### ISSUE THREAD

**Issue by grant2258** [libretro/mame2003-plus-libretro#120]
@markwkidd 

I get the feeling retropie is setting the savefile path to the content path this will cause issues if your roms arent directly in the the arcade or mame-libretro folder its a none issue for retroarch though.

example if you have your directory setup like this

arcade/fba
arcade/mame2003
arcade/mame2003+

your savedir will be saved to 

arcade/fba/mame2003-plus
arcade/mame2003/mame2003-plus
arcade/mame2003+/arcade/mame2003+

this will a none issue if your roms are directly in the directory but if you have them in subdirs its an issue the nvram fixes will be in arcade/mame2003-plus-nvram

wouldnt it be more logical to save this data in the system folder as technically it is mame system data thoughts?

**Comment by grant2258** [comment]
@markwkidd  the thing is say i have two dirs on retropie neogeo and mame078(full none meged) both have neogeo games. make2003 and mame2003 plus will be reading the data for the same emulator in two different places on (retropie) not retroach though. This problem would include highscores and inp

**Comment by markwkidd** [comment]
I don't think I personally want to try to suggest that RetroPie  change their save directory approach :\

**Comment by grant2258** [comment]
neither do i so we just put the data in the system folder it is for the mame system anayway

**Comment by grant2258** [comment]
the nvram can still be done the way you want to do it but this path issue on retropie and retroarch will come back to bite if we dont do something to make the data be where it should be on both.

**Comment by grant2258** [comment]
mark the savedir is set to "default" would this be content dir ?

**Comment by markwkidd** [comment]
for libretro, there is no guarantee that there will be a system path or a
save path at all. in those cases mame2003 has traditionally used the
content directory as its fallback.

For the official retroarch distributions, savedir is set to its own path
but RetroPie has decided to make savedir = contendir

They probably have their reasons but it would be easier if RetroPie set a
savedir

**Comment by grant2258** [comment]
Well again it is a retro pie issue i posted a link to this issue maybe jools can give some input if they want it fixed

**Comment by markwkidd** [comment]
Yeah I have looked at the libretro API again -- libretro doesn't want you to put something like nvram into the system folder: https://github.com/libretro/RetroArch/blob/4d64a94cb21a9df820cebcc9a5cc5b227379751f/libretro-common/include/libretro.h#L539-L542

**Comment by grant2258** [comment]
feel free to reopen i feel like this issue is solved

**Comment by markwkidd** [comment]
Yeah I'm not sure what to for now. Agree on closing the issue.
