### ISSUE TITLE
Cursor offset in lightgun devices for some games

### ISSUE THREAD

**Issue by StormedBubbles** [libretro/mame2003-plus-libretro#1203]
Hello,

On Raspberry Pi 4 with a lightgun device such as a Sinden Lightgun, some games work perfectly (area51, maxforce), while others (lethalen, cryptklr) have the gun cursors offset by what appears to be a constant amount. The guns track nicely and consistently otherwise. It's just that the emulator thinks you're aiming at a different spot on the screen than you actually are for the problem games. This would be a non-issue if the games had their own calibration menus in service mode, but the two problem games mentioned above do not have that feature.

If fixing this would require some fundamental change that could negatively affect other games, perhaps introducing a core option for manual cursor offset could mitigate the issue and allow game-by-game adjustments.

**Comment by mahoneyt944** [comment]
https://github.com/libretro/mame2003-plus-libretro/commit/dc5e822d560e488fe43db524393961e1eebf98f6

This commit should fix lethalen

**Comment by mahoneyt944** [comment]
I didn't notice the guns being off in cryptklr, but I updated the lightgun reads to newer mame. With this commit https://github.com/libretro/mame2003-plus-libretro/commit/d2480d16d7f7ce94db782ca17f9601ff705bd9c8 seems to track normally too. Let me know if you see any improvements with these two commits.

**Comment by StormedBubbles** [comment]
Thank you so much!

The first commit did fix lehtalen, and that was maintained in the second commit. The aim was still off for me in cryptklr in the first commit, but I didn't activate the crosshairs until I installed the second commit. In the second commit, I found that the crosshairs for cryptklr were locked to the y-axis. I could only move guns 1 and 2 vertically on a straight line through the center of the screen.

area51 and maxforce maintained their proper aim throughout.

**Comment by mahoneyt944** [comment]
Sorry try this commit for cryptklr
https://github.com/libretro/mame2003-plus-libretro/commit/3aaf473203f2d4ae22a06d0b88202d24c42d1380

**Comment by StormedBubbles** [comment]
Thank you again! cryptklr is working properly for me now. 

Were these fixes specific to these games? Would you prefer that I (or others) comment here if other, similar issues arise for other games?

**Comment by mahoneyt944** [comment]
Yes they are specific to those games. It's better to just open a new issue in such event.

**Comment by StormedBubbles** [comment]
@mahoneyt944 Okay, I will open a new issue if I find anything else. @grant2258 The xy device is set to lightgun. I am on RetroPie, but I am unsure of exactly how the Sinden gun reports coordinates. The most recent commit resolved the particular issues I was having.
