### ISSUE TITLE
crash at rom loading on Retroid pocket 2 

### ISSUE THREAD

**Issue by Speedvicio** [libretro/mame2003-plus-libretro#1207]
Every time you run a rom with this core, also on mame2003 standard core RA crash.

Running last RA android version by LineageOS 8.1

**Comment by grant2258** [comment]
any other cores doing this ?

**Comment by Speedvicio** [comment]
> any other cores doing this ?

All mame core except mame 2000, puae and flycast in the last month, previous version working fine

**Comment by mahoneyt944** [comment]
See if you can get a log

**Comment by Speedvicio** [comment]
where is placed the log?

**Comment by mahoneyt944** [comment]
Retroarch has options under settings->logging.

Enable - logging verbosity
Enable - log to file

Then run a rom in the core. RetroArch will save this in it's main directory. Retorarch->logs->retroarch.log

Based on your platform and configs this location may vary.

**Comment by Speedvicio** [comment]
> Retroarch has options under settings->logging.
> 
> Enable - logging verbosity Enable - log to file
> 
> Then run a rom in the core. RetroArch will save this in it's main directory.
> 
> Retorarch->logs->retroarch.log
> 
> Based on your platform and configs this location may vary.
[retroarch.log](https://github.com/libretro/mame2003-plus-libretro/files/7632049/retroarch.log)

**Comment by mahoneyt944** [comment]
Your log is saying, repeatedly lol, that the system directory can not be made at this location "/storage/6564-3531/system/mame2003-plus".

You may not have access to write to this location. Or there is an issue with this location for some reason with your platform creating directories

**Comment by mahoneyt944** [comment]
@jdgleaver has there been any libretro-common commits to the recursive directory creation? Had this issue before with wiiu not being able to create a new file path when the path ended in a slash.

**Comment by Speedvicio** [comment]
i have moved the system folder to internal storage and the problem is dissapeared, the strange is that in the past release there was not problems relative to access onto external storage.
I doubt that the problem is not related to the emulation core but to RA itself

**Comment by mahoneyt944** [comment]
Issue moved to RA issue tracking.
