### ISSUE TITLE
Backport request: Lethal Enforcers II

### ISSUE THREAD

**Issue by StormedBubbles** [libretro/mame2003-plus-libretro#1212]
Hello,

Would le2 be possible to backport? Even though not officially supported, some versions of the ROM currently play decently in lr-mame2003-plus. There are some graphical glitches (some graphical elements are blacked out occasionally) and a cursor offset similar to #1203, but the sound and speed seem fine as-is at a glance.

**Comment by mahoneyt944** [comment]
le2 is supported. What version are you referring to?

**Comment by StormedBubbles** [comment]
Sorry for my ignorance. It was a misunderstanding on my part. I see now that le2 and le2u are supported and that the recent commit fixed the aim. Thank you for that! The aim works well on my end with a Sinden gun for each player.

Would it be difficult to fix the graphical issues? The game is certainly playable aside from one issue (see below). Just curious.

I do notice that off-screen reload is unreliable with this game for me. In Lethal Enforcers (lethalen), I have no issues and can reload quite easily on any side of the screen by pointing the gun outside of the screen. In le2 and le2u, the off-screen reload only seems to work a small percentage of the time.

**Comment by arcadez2003** [comment]
KonamiGx hardware http://adb.arcadeitalia.net/lista_mame.php?game_sourcefile=konamigx.cpp&arcade_only=0&current_version=0

Alotta fixes for those games over the years but due to the workload required i never looked into it really, but there
are a couple of commits which sort the gun reloading i dunno how much work would be needed to backport those
changes.........

0.131: Derrick Renaud fixed P2 gun reload in Lethal Enforcers II.
0.127u8: R. Belmont fixed gun reload in Lethal Enforcers II.

**Comment by mahoneyt944** [comment]
@arcadez2003 thanks. @StormedBubbles fixed gun reload in le2 with latest commit for top and bottom of screen

**Comment by mahoneyt944** [comment]
@StormedBubbles just committed a color fix for le2. Should be much better now. https://github.com/libretro/mame2003-plus-libretro/commit/b52ed08aadce3104db80369cb4de56b3f85662e1

**Comment by StormedBubbles** [comment]
Wow! It's so much better now for both le2 and le2u! Thank you!

The graphical glitches I experienced before are gone. 

Reload appears to be flawless for player 2 (all four sides of the screen work well). 

The top, bottom, and right work really well for player 1, but I notice that when I go off the left side of the screen with player 1, I have to pull the trigger twice to get reload to work. A bullet gets fired first, and then, without moving the cursor, it will recognize the off-screen reload when I pull the trigger a second time.

**Comment by mahoneyt944** [comment]
I believe the original game was meant to aim up or down for off screen shot. So I'd recommend that if it working well.

**Comment by mahoneyt944** [comment]
That's what this shows anyhow lol
![le2-211201-002042](https://user-images.githubusercontent.com/49591133/144176637-2d01f1c7-6b93-4682-9e2f-48430020ab6a.png)

**Comment by StormedBubbles** [comment]
Yeah, the cabinets for lethalen and le2 both have a sign printed under the screen that says "shoot here to reload." I just figured it was a suggestion to avoid interference from lights on the ceiling/marquee or potentially hitting the other player or other people next to you with the gun. Maybe the programming actually is picky about it.

Many of those lightgun games allowed you to cover the muzzle with your hand and fire to reload instead of pointing off screen. It's a trick to avoid having to point away from the screen. I wonder if that would work on this game's cabinet. I haven't been able to get that trick to work with the Sinden guns. They know you haven't moved away from the screen.

**Comment by mahoneyt944** [comment]
I pushed a commit to fix the left side reload. Test both players and let me know

**Comment by StormedBubbles** [comment]
le2 works great now! I tried each player individually as well as both players off the same side of the screen and different sides simultaneously, and everything went smoothly.

**Comment by mahoneyt944** [comment]
Great!
