### ISSUE TITLE
Can't rebuild set ktiger2p

### ISSUE THREAD

**Issue by unit3uk** [libretro/mame2003-plus-libretro#1215]
I generated a datfile with the latest mame2003-plus core and can’t rebuild set ktiger2p using clrmamepro. The CRC’s match the datfile, but not the sha1 hashes.

This is what I get for hashes:

b30_02_2p.8j [CRC32:321e2be6] [SHA1: 03b2c530326d1859b66829b49555d862be235643]

b30_04_2p.8h [CRC32:c3f960ff] [SHA1: cbebf576d677cc02f4d0f22dcc226e898d4832c6]

**Comment by mahoneyt944** [comment]
I'll have to review the checksums but in the mean time you can

Google "ktiger2p wowroms" that seemed to work for me. Loads like it should.

**Comment by mahoneyt944** [comment]
Your sha1 values are correct. I updated the the values to now be correct.

**Comment by mahoneyt944** [comment]
@arcadez2003 The values are correctly labeled above for these 2 files. If you had crashing issues in your core this may be why. Just a heads up. I built this rom by hand and verified it / tested in 2003+. Looks good now.

**Comment by arcadez2003** [comment]
@mahoneyt944 i never tested the game as i lost my dev environment when my PC crashed as i explained to @grant2258 
in another thread, so going forward all my commits will be untested and very minimal when it comes to code changes
as per In Your Face the other day and a fix to stop Thunder Hoop from crashing on level 4 which i'll be uploading later.
