### ISSUE TITLE
Hide inactive crosshair timing

### ISSUE THREAD

**Issue by mahoneyt944** [libretro/mame2003-plus-libretro#1225]
With commit https://github.com/libretro/mame2003-plus-libretro/commit/2379981191f129c520c85ac9e03116e4743e03be I added some tracking to the crosshairs when they are drawn to allow player specific configurations and it's working very well with all my tests so far.

In regards to hiding inactive players, I'm currently using a generic counter to determine how long the crosshair have been inactive. While this works as is, there's no guarantee how often draw_crosshair will be called based on where in the code it's calling from. This results in the inconsistent timing. Average is about 20 seconds, luckywld is about 10. Though I'm guessing it's updating the video twice in the driver hookups?

I'd like to modify this to use actual timing so it's consistent just not sure the best approach to this.

@grant2258 @markwkidd  thoughts on this?
https://github.com/libretro/mame2003-plus-libretro/blob/2379981191f129c520c85ac9e03116e4743e03be/src/drawgfx.c#L3535-L3547

I'm thinking we should save a time stamp when the player is active in `inactive_xy[player_number-1][2]` then our check would simply see if so many seconds have passed from that time stamp. Though when entering/ returning from the RA menu the crosshairs would go inactive since we would be comparing actual time stamps.

**Comment by grant2258** [comment]
I dont see anywhere your tracking the actual player number

**Comment by mahoneyt944** [comment]
@grant2258 it's not tracking the player number directly since the code doesn't support this afaik. What I'm doing is using a content flag to determine how many lightguns a game uses and assuming that crosshairs will be drawn for each player. So I can use my player_number variable to track calls to draw_crosshair.

It's preying on the execution of draw_crosshair to track different players. Which means we can assign colors to different players if desired.

The only draw back is that we can't garantee the actual player order if a driver happened to draw player 2 then player 1 for example. But typically they are drawn in order. I'll have to locate drivers like this and fix the order if any.

**Comment by grant2258** [comment]
just add player number to draw_crosshair there not that many games that support lightgun

**Comment by mahoneyt944** [comment]
> just add player number to draw_crosshair there's not that many games that support lightgun

Yeah that's true. I could probably add that in instead when I get a chance.

**Comment by mahoneyt944** [comment]
Ok updated the player_number. I wonder if the timing is just the driver.

**Comment by grant2258** [comment]
How are you defining Inactive

**Comment by mahoneyt944** [comment]
inactive_xy is an array that saves x, y, and a inactive counter for each player. If the player has not moved the crosshair since last call it adds 1 to the counter for that player. If the counter reaches "1000" then the player is deemed inactive and that crosshair will not be drawn. If at anytime the play moves the crosshair the counter is reset to 0.  This basically just hides crosshairs for players that aren't playing so they aren't in the way.

**Comment by mahoneyt944** [comment]
@grant2258 
> This isn't ideal for all games if your shooting thing going past at the same position. You just timing the trigger you'll also need to check any player buttons for activity in this as well to not cause unexpected side effects.

Replying here instead. I was going off of newer mames which deactivates the crosshairs after about 5 seconds( try bbusters in mame2010 for reference). It's set to 20 seconds here which is pretty hard to hit if you're actually playing a game for real. But this timer can be set to any amount of time to be more convenient.

**Comment by mahoneyt944** [comment]
Heres 2010 reference too
https://github.com/libretro/mame2010-libretro/blob/932e6f2c4f13b67b29ab33428a4037dee9a236a8/src/emu/crsshair.c#L367-L377

**Comment by mahoneyt944** [comment]
I can't quite figure out how to setup the other colors. I've got some but not what I expected. Here's a commit that shows how more were added but i can't get it working properly.
https://github.com/mamedev/historic-mame/blob/2eef32cb3e2f48649cba9bfaa159d5d24e5a073a/src/emu/video.c#L1845-L1914

**Comment by grant2258** [comment]
I think around mame107 mame added the crosshairs as artwork. Our video code and palette code is very different you might have to allocate more pens and defaults and the extra initialization code  to the game palette as its using pens for the pixel plot

**Comment by mahoneyt944** [comment]
Yeah think we will need to create a new isolated palette or something. Though I did make a strobe effect that's commented out for now in the code. Just something I was messing with.

**Comment by mahoneyt944** [comment]
Tagging https://github.com/libretro/mame2003-plus-libretro/issues/256 here instead since this is essentially the same thing. While not the gun sight from 2010 we have added an enhanced crosshair core option and now include inactive players to disappear after a period of time.
