### ISSUE TITLE
CarnEvil (carnevil) post-0.78 changes for performance improvements?

### ISSUE THREAD

**Issue by StormedBubbles** [libretro/mame2003-plus-libretro#1226]
Some friends and I have been trying carnevil on Pi 4 with RetroPie and find that the gameplay goes reasonably smoothly (45-50 FPS) once some CPU, audio, and dip-switch settings are adjusted. The gun calibration is spot on! Scene transitions and especially the jester on the loading screen are what hit the performance the hardest.

I saw some 2003-plus commits related to bootstraps and configs for carnevil for the purpose of getting it running. Looking at the commit history for standalone Windows MAME, I noticed a handful of commits after MAME 0.78 that are related to sound/speed issues for carnevil. Are those implemented in 2003plus? 

This game seems to be rather intense, so I wouldn't expect full speed on a Pi 4, but if those post-0.78 changes aren't currently implemented and were added, would there be a noticeable improvement?

**Comment by mahoneyt944** [comment]
Carnevil is one of the most demanding games we support in this core. Your results are probably normal. This games really need a stronger platform.

**Comment by StormedBubbles** [comment]
I have a question about this one because I think I am misinterpreting FPS measurements. 

I find that this game reaches its best (and likely peak, based on the previous comment) performance on my overclocked Pi when I set the CPU clock core option to 25% in the RetroArch menu. The RetroArch FPS counter shows

- Low/mid-50s for the opening cinematic. This goes very smoothly.
- Teens/twenties for the loading screen where the jester taunts you. This seems about right.
- 45-50 during gameplay, which is a humongous jump over how the game performs on default settings. The gameplay still feels very choppy, which is strange because...

I notice that playing, for example, the Naomi version of The House of the Dead 2 in lr-flycast goes very smoothly despite the FPS counter varying pretty wildly from the 30s-50s. Most of the time, the counter stays around the same 45-50 range that CarnEvil does, but the gameplay is much smoother.

**Does that CPU setting affect how the FPS measurement is calculated?**

**Comment by mahoneyt944** [comment]
You're essentially slowing the emulated cpu to 25% which as you can imagine, emulating a cpu at a quarter speed is less taxing than emulating it at full speed so this will raise the fps in most cases. The unfortunate side effect is that this can negatively effect game timings.

The default setting will run the game as it's intended to run, assuming the platform has enough power to handle it. Dropping the percentage may improve performance on your platform at the cost of game timings.

Game timings can have very unpredictable results. Some game don't seem to mind while others are very sensitive to them. Some games may randomly lock up and/or fail to run all together.

Most games have a "sweet spot" where you can drop the percentage to gain a performance boost while also not low enough to notice unusual game timings.

You may think of it as a slowed down pi executing full emulated speed versus a fast pi executing a quarter emulated speed. On one hand, if the pi can't keep up you'll see slow downs. On the other hand if the pi is keeping up but the game is only executing at a quarter speed  you will actually be running slow.
