### ISSUE TITLE
Hmm seems like you didn't get the job :)

### ISSUE THREAD

**Issue by arcadez2003** [libretro/mame2003-plus-libretro#1228]
A little snapshot from the bannister MAME chat boards, yes i go there now and again to read
up on the latest dev WIP but i do find it amusing that certain people bitch moan and 
generally cry about our core on a constant basis

It tends to go in one ear and out the other however i thought it prudent in this case
to point out to whomever this may concern that your privacy has clearly been breached and
you may want to consider a response........

Haze: lol, one of the mame2003 plus people applied for a job at a place where I know the staff.

Haze: advertising their work on 2003 plus as the most important and widely used version of MAME, that offers real performance and has been shipped on millions of devices (with a list of chinese consoles)

Haze: "most popular core in modern Retroarch distributions"

Haze: needless to say, they weren't considered for the job.

Your details that's to say name age address employment roll numbers etc etc may well not be secure

Regards.

**Comment by grant2258** [comment]
Wonder who it was

**Comment by twinaphex** [comment]
This is undeed very unprofessional and uncalled for behavior. Shame that this happened and that people have not matured yet in this scene and underhanded dirty shenanigans like this still goes on. Hope the person's privacy details are safe.

**Comment by arcadez2003** [comment]
Hmm this reminds me i got a strange email the other day along the lines of a dev has "invited" me to join
codersrank i assumed it was some sort of co-promotion with github obviously but im starting to think
that's not the case any of you guys ever heard of that company or got a similar email.??

i didn't click on the invite as i have no intrest in a job of that type as i worked in the building industry 
when i was younger and i have a trade i can always fall back on apart from that i've only ever done driving 
jobs so blue collar stuff more or less.

They got my email address from somewhere right enough which is making me wonder if this was some
sort of fishing exercise to obtain the idents of those who work on this core via a possible profile created
via that invite or maybe im reading too much into it 

Im not one for conspiracies but then again that is the whole point of this thread is to mention that someones 
details who works on this core were passed on to a certain MAME dev unless he's totally bullshitting around.

**Comment by twinaphex** [comment]
Never heard of it.

**Comment by mahoneyt944** [comment]
Sounds like a bogus story to me. Haze is from the UK so that not even the same continent. It's actually sad that people attack this core since we all share a common ground. Seems people just get jealous when it's not their core in use.

In all honesty, as a dev here, I recommend using the core or standalone that works best for you and your needs. The make and model means nothing to me.

**Comment by arcadez2003** [comment]
Alright i'll close this down false alarm more than likely
