### ISSUE TITLE
Golly! Ghost! (gollygho) lightguns not mapped to gun axes during gameplay

### ISSUE THREAD

**Issue by StormedBubbles** [libretro/mame2003-plus-libretro#1237]
I finally have a request related to a game already in this ROM set and with what seems to be a minor issue. 😆

In gollygho, both guns seem to show that they are tracking in the test menu, but during gameplay, both of the in-game crosshairs are stuck in the upper-left portion of the screen. The coin, start, and trigger buttons all appear to function correctly for both players. I ran the game with verbose logging and didn't receive any warnings, and the game list indicates that all should be good with this one as a lightgun game.

**Comment by mahoneyt944** [comment]
I have a fix for this game and steel gunner which will be released soon.

**Comment by mahoneyt944** [comment]
Pushed a commit to fix gollygho and sgunner

**Comment by StormedBubbles** [comment]
Thanks! sgunner is good. gollygho tracks now, but the cursors are a offset a bit. P1's in-game cursor is to the right of the mouse cursor, and P2's is to the left. Both also seem a little too low. I cycled through the service menu and didn't find a way to calibrate in game. 

Was this update supposed to affect sgunner2 also? That has coin, start, trigger, and secondary-weapon buttons but is missing mouse tracking.

**Comment by mahoneyt944** [comment]
Sgunner2 still needs to be fixed. Did you delete the .cfg and .nv files before testing?

I may be able to get gollygho a bit tighter but I'll have to work on it.

**Comment by StormedBubbles** [comment]
Yes, deleted both of those. Thanks a lot!

**Comment by mahoneyt944** [comment]
Do me a favor, delete your gollygho.nv and place this one that I'm linking here in the directory instead, you'll have to unzip it first. Is this calibration better or worse?
[golly.zip](https://github.com/libretro/mame2003-plus-libretro/files/7704756/golly.zip)

**Comment by StormedBubbles** [comment]
Sorry, I should give better feedback. Here is the tracking for player 1 after the update you posted. It seems that the game loses vertical alignment the further up the screen you go. The yellow mark represents where I am aiming. The 2003plus cursor and the in-game cursor do line up exactly. It's just that they are offset from where the mouse cursor typically should be.

![golly1-edited](https://user-images.githubusercontent.com/80055191/145865110-c117e701-f833-4013-9c15-e3b096e33363.jpg)
![golly2-edited](https://user-images.githubusercontent.com/80055191/145865114-14f8bd3c-fe60-4fcd-8076-33c0bc6f42a7.jpg)

And this is with the nvram file you sent me:

![golly3-edited](https://user-images.githubusercontent.com/80055191/145865807-3d8e679d-dd4c-4842-a8fd-f66ecef8e02b.jpg)
![golly4-edited](https://user-images.githubusercontent.com/80055191/145865815-e0f17d1c-d528-4ed5-9dfd-3e0233c127f0.jpg)

It's a similar problem, except now the 2003plus cursor is also misaligned with the in-game cursor.

**Comment by mahoneyt944** [comment]
Well I think I found the issue with gollygho. At first i couldn't get the tracking to be off like you were experiencing then realized you were using the artwork and I wasn't. Once i added the artwork the tracking was indeed off. It seems the artwork scaling the image effects the calibration in some way. I'll.have to see if this can be worked around.

**Comment by mahoneyt944** [comment]
This maybe related to this open PR as the viewpoint is scaled to fit the artwork. https://github.com/libretro/RetroArch/pull/13258

**Comment by mahoneyt944** [comment]
Pushed a commit that fixes sgunner2 and sgunnr2j (japan version). Delete the cfg and nv file.

**Comment by StormedBubbles** [comment]
Both of those are good now. Thanks! 😃

Luckily, gollygho has an in-game set of crosshairs to use until that RetroArch issue gets closed.

**Comment by mahoneyt944** [comment]
@grant2258 I'm getting a random reset crash with gollygho, if I reset usually with the 2nd or 3rd reset it crashes RA . Does this happen for you?

**Comment by mahoneyt944** [comment]
Just tested resetting with artwork turned off and there's no crash. So artwork related on reset.

**Comment by grant2258** [comment]
I'll have a look at the weekend did you debug the crash?

**Comment by mahoneyt944** [comment]
No just the above test. I also tried blueshrk with artwork loaded and it does not crash either. Seems specific to this game or artwork for it.

**Comment by grant2258** [comment]
had a quick look was a simple fix

**Comment by grant2258** [comment]
i tried deleting the cfg this game just doesnt work properly with a abs touchpad even with artwork disabled something is amiss with the code its well off

**Comment by mahoneyt944** [comment]
With the new bootstrap and artwork off, the pointer(touch screen) works properly for me. When artwork is on though, the touchscreen responds to the entire screen and not just the game viewpoint which causes the touched point to be misaligned .

**Comment by grant2258** [comment]
seems fine with the touchpad i deleted my retroarch.cfg file and it was using x instead of udev that udev fix wont make a difference if its not working on android though is the artwork putting the cursor off there as well?

**Comment by mahoneyt944** [comment]
When the artwork is enabled, if I touch the top left area of the artwork(scoreboard area), it puts the in-game crosshair to the top left corner of the top left room. Which means touching inside the rooms(actual game play area) is always offset by that amount.

**Comment by mahoneyt944** [comment]
The pi uses udev right? If so should fix the ops issue.

**Comment by grant2258** [comment]
Dont see how it will fix the issue if its not working on android you said that worked fine in different scaling  modes

**Comment by mahoneyt944** [comment]
I'm not overly worried about it working on Android for myself at this point though that would be nice, I can test things on here though since I can workaround the issue by turning the artwork off.

And oh yeah, I forgot RetroPie is behind. Can you confirm if it is working in udev now though? You'd have to delete the current gollygho.nv and gollygho.cfg, grab the lastest commit of 2003+ in the latest nightly RA where the udev fix was committed lol. A lot to chew i know ha.

**Comment by grant2258** [comment]
Let me charge my AA batterys ill check it out with my wii mote there not very accurate though would really need a gunsight haha

**Comment by grant2258** [comment]
Ok batterys werent too bad its fine on a wii mote without the scaling fix to be honest.

**Comment by mahoneyt944** [comment]
The bootstrap should calibrate the mame crosshairs to be very tight to the in game ones except for the very outmost edge since mame has more range than the internal crosshairs. So if it tracks in the ballpark it's probably right. Without artwork its very accurate for me, hopefully that fix makes the artwork irrelevant to it's tracking.

**Comment by grant2258** [comment]
Well im having no issues on a wii mote at 4:3 core provide aspect ratio without the fix even with artwork on. Only time there is an issues is when i change the aspect ratio to 3:4 then its off. This is without the scaling fix btw so no issues with the wii mote even with artwork on.

**Comment by grant2258** [comment]
just compiled the latest mame game seems to not work properly with artwork disabled for me very strange

**Comment by grant2258** [comment]
@mahoneyt944  if you have the artwork and disable artwork game does not function properly even before the heapsize fixes need to see if this driver or core in general issue

**Comment by StormedBubbles** [comment]
Ah, thank you for pointing out that calibration menu! I completely missed that. With the artwork on and calibration via that menu, both guns work perfectly for me.

**Comment by mahoneyt944** [comment]
Great
