### ISSUE TITLE
SF2 difficulty dips

### ISSUE THREAD

**Issue by Riddler1** [libretro/mame2003-plus-libretro#1240]
Is it known that the difficulty setting for any Street fighter 2 game does not match the service menu?

Dip setting 4 (normal) actually sets the game to difficulty 3

Difficulty level 8 is not possible in this case.

Example:
 https://youtu.be/TMTAc-EUb6s

**Comment by mahoneyt944** [comment]
Just pushed a commit to fix this thanks
