### ISSUE TITLE
[SUGGESTION] Allow XML cfg files

### ISSUE THREAD

**Issue by capitaineflam25** [libretro/mame2003-plus-libretro#1243]
Using binary cfg files allow less tweaks than XML files used in later Mame libretro core version.

Would it be possible to allow XML files for Mame and games configuration ?
If not, is it possible to decrypt those files manually ?

**Comment by mahoneyt944** [comment]
This would be a major overhaul. I imagine to do this we'd have to support reading in our current cfg format, if found, and convert them on load to the new format to not break everyone's cfgs. It's also worth investing if there would be any performance hits from alternative format handling.

**Comment by mahoneyt944** [comment]
This seems to be out of the scope for this core so I'm going to close this. Too much of an overhaul, plus ideally we'd like to move away from legacy cfgs and more towards libretro structuring where possible.
