### ISSUE TITLE
Xbox port

### ISSUE THREAD

**Issue by mahoneyt944** [libretro/mame2003-plus-libretro#1246]
@arcadez2003 I was wondering what the build issues are with this core for og Xbox. If we iron these out it could be a typical nightly build like everything else relieving the need to compile on your own.

I don't know much about compiling for the Xbox but I'm sure others would enjoy such a binary being created if possible.

**Comment by grant2258** [comment]
Its not a libretro port at all would libretro allow this to be built ?

**Comment by mahoneyt944** [comment]
I'm sure they would allow it if it's properly added like all the other ports. Then it would just build like everything else.

**Comment by grant2258** [comment]
well ive done mame084 already if you want to port all the stuff arcadez has done and he is ok with it go for it..

**Comment by arcadez2003** [comment]
Too much work big chaps better you focus your time on something worthwhile :) anyway i've got my dev setup
back up and running so at least i can test once again before pushing any commits here, but damn it was hard
to trackdown obsolete programs which are nearly 20 years old namely VS-2003 and the Xbox SDK.

Half the sites looked dodgy as fuck although i lucked out and found a couple of decent ones tucked out the way.

**Comment by grant2258** [comment]
@arcadez2003 just keep in mind if your porting something to 084 and are having issue I have a build here I can test on. Im not too fussed about porting it all to be honest but it could save you doing 078 and 084 in the long run.

**Comment by arcadez2003** [comment]
Although i moan im only really backporting code from 84 to 72 testing it works then porting across to here 72 to 78
99% of the code created for 72 is fine for this core i just paste it in more or less, so you'd only be removing one small
step in the dev cycle which is not really worth the time.

Back when the workload was high the constant churn of port test re-port repeat sometimes got to me but nowadays the
workload is far lighter so im not really all that fussed, but hey thanks for the offer guys.
