### ISSUE TITLE
Neo-Geo Support for Cabal Neo-Geo Port

### ISSUE THREAD

**Issue by KMFDManic** [libretro/mame2003-plus-libretro#1247]
Included FBNeo Implementation, as a reference point:

Cabal Neo-Geo Port:

https://github.com/libretro/FBNeo/commit/1728611436983890196a27a266394b0e064fdca2

Personal thanks, @iq132

I wanna take a stab at this for 2003 Xtreme, as well.  I have the needed test files.  Opinion, @mahoneyt944 @arcadez2003 @grant2258 ?

**Comment by mahoneyt944** [comment]
Arcadez just added xeno crisis

**Comment by KMFDManic** [comment]
@mahoneyt944 Haha, that is what I get for not refreshing the latest commits before opening this issue:)  Forgive my ignorance:)

**Comment by arcadez2003** [comment]
What does the Cabal hack offer over and above the multiple versions of that game we already support.??

**Comment by KMFDManic** [comment]
@arcadez2003 The individual who brought it to my attention that Cabal was on Neo Geo, I asked the same thing.  He said it was a "remake".  But, in checking further, it really does come across as just a porting.  So, this is not as high a priority.

https://www.arcade-projects.com/threads/cabal-mvs-port-by-iq_132.18893/

Always on the lookout for newer stuff to be added:)  Tested Xeno Crisis earlier, and it played great!
