### ISSUE TITLE
Ost support isolation

### ISSUE THREAD

**Issue by mahoneyt944** [libretro/mame2003-plus-libretro#1249]
Wip

Edit PR #1251

**Comment by mahoneyt944** [comment]
@grant2258  merged #1252

Also could probably remove all these individual "game_playing" flags and use the ost content flag. in these checks.

https://github.com/libretro/mame2003-plus-libretro/blob/47ccff642a723fd212ac711b80fa7a58b5a3f819/src/sndhrdw/williams_sndhrdw.c#L604

To 
```
(options.content_flags[CONTENT_ALT_SOUND] && options.use_samples)
```

**Comment by grant2258** [comment]
just make sure your changes work when samples are enabled and missing as well. Not really been following this cores changes we used to keep samples and ost seperate so you could disable ost or normal samples.

**Comment by mahoneyt944** [comment]
Yes this is still how they are handled. the samples are not loaded if the user disabled the option which will user default sound. If the user has the option turned on but no samples it falls back to default sound.

**Comment by mahoneyt944** [comment]
We should be able to easily pull any fixes right into the main switch(data) with minimal changes. My focus was to trim the fat and structure ost_samples.c to be very linear. The structure uses this format.

ost_samples.c (assuming ost core option is on)
- define sample packs
- define interfaces
- define ost functions for repetitive tasks
- define generate_ost_sound_*() to play ost samples and return a flag when the driver needs to play an original sound. This way the driver does it's own laundry.

generate_ost_sound_*() structure
- each should initialize with a default config and override with any game specific configs
- switch(data) should determine what to do. This includes flags to start, stop, schedule a default sound, toggle variables,  do nothing, etc.
- we then close up our function by processing some things and returning a flag to the driver which determines when it needs to play a default sound or not

When the ost option is disabled the driver will execute it's normal routing, bypassing ost entirely. This ensures our hook up does not interfere with any other games using it or when the user has disabled it.

**Comment by grant2258** [comment]
> Yes this is still how they are handled. the samples are not loaded if the user disabled the option which will use default sound. If the user has the option turned on but no samples it falls back to default sound.

This is in the context of ost.that always what it should do. I know I had to fix up nba jam up on my port because that didnt work when you never had the samples and disabled it. 

Im talking about normal samples in games that arent ost. There is no option to disable the samples unless the user deletes them. It something that was change at the point i ported off will need to fix that on my port as well.

**Comment by mahoneyt944** [comment]
I believe sample loading uses the CONTENT_ALT_SOUND as a control to prevent regular samples from being disabled.

Though.... unlike ost samples which replace working game sounds, normal samples are providing sounds that aren't emulated. I can't see a reason to ever disable them and still have all the sample packs as overhead on your device? If the device can't handle the sample packs then it probably shouldn't store them?

**Comment by grant2258** [comment]
I think it was zaxon the samples where too loud to be honest. I dont really see a lot of reason to disable normal samples myself but people could have there reasons. Its also an option that came with standard mame as well. For example it would be handy to fix the journey reset bug but thats a niche edge case. Regardless of views some people want different things its just for the sake of completeness not a personal preference.

**Comment by mahoneyt944** [comment]
I can see that point too. We also wouldn't want to confuse users with seemingly similar core options. I see a lot of users get confused about what samples even are and where they go, let alone different types of samples.

It would be easy to add another core option... one to disable all samples and one to disable ost samples but I think this may confuse some users. It would need to be very simple so that someone without prior understanding could easily use it without any confusion. That's where it can be tricky because people like us having used this core and RA long enough can confidently change options where others get nervous even opening the options menu.

I also like to structure things and get into the "fine print" if I'm making significant changes. Admittedly, I stayed away from ost stuff for awhile because I didn't have a design in mind for how it should be structured... being it's an audio hack in it's own. The new layout doesn't really make monumental changes by any means but it should be very predictable in it's flow and overall be easier to work with. There's probably a part 3 I'll be doing to structure exiting functions and maybe even swap the switch(data) for something's that's not so god awful long to look at. Also should probably be passing a reference to data in these functions instead of creating a new instance but that doesn't seem to be problematic either way.

**Comment by grant2258** [comment]
Dont see any problems separating optional ost from internal mame samples from a users perspective in two different options they have nothing in common with each other apart from the both use wavs of flac and that doesnt really matter to the user well shouldnt anyway

**Comment by mahoneyt944** [comment]
It would be easy to hook up that way certainly. Just need a new option for ost samples since "use_samples" should be for all samples. Then use_samples can just return.

**Comment by mahoneyt944** [comment]
Merged part 3, starting to shape up now. Need to investigate all these flags.

**Comment by mahoneyt944** [comment]
Currently the drivers initiate game specific ost flags. Such as these:
https://github.com/libretro/mame2003-plus-libretro/blob/69d329f2a9c65263856bcc18603344e91435b3b3/src/drivers/outrun.c#L1154-L1160

This makes sense for starting a new game, though I'm not sure what happens when you reset a game.. will these be reinitialized? Not that samples work on reset now anyways but this is also an area that we should structure. I'd like to move the ini

**Comment by mahoneyt944** [comment]
@grant2258 this should isolate ost like we discussed above. #1256 feel free to create a PR if I've missed anything. I was going to add the options.use_samples check to the ost hookup but this should catch this when the samples load anyhow.

**Comment by grant2258** [comment]
take some time off you shouldnt be coding this time of year! Will test a liitle if you want me too.

**Comment by mahoneyt944** [comment]
Testing would be a big help. Merry Christmas / holidays to you as well. I've removed all the sa_* flags and converted ost_samples.c to use "one liner" function calls instead. This really cleans up the implementation.

I found some oddities in the switch statements "default" sections that had to be addressed, mainly in NBA jam. This could never happen since "case 0x0" is found at the top of the switch statement. So I move this into that case.

https://github.com/libretro/mame2003-plus-libretro/blob/06775dc470ad3eaeb9c800fe37123dc5d6132de1/src/ost_samples.c#L1852-L1859

The "use samples" option was a basic plug in to isolate it from ost samples. Though they do share a relationship since samples need to be enabled to load ost samples. I'm reviewing options to dynamically hide the ost samples option when "use samples" is disabled. So it interacts with the users selection in real time.

**Comment by mahoneyt944** [comment]
I've also found a slight bug with outrun. When a game ends and the progress map is displayed, the map sample starts playing. However, if you also do well enough to enter your name right after, there is a default sound that plays as well on top of the map sample. We need to log what data value this is and decide what do in this instance. Either continue playing the map sample and ignore the default sound or stop the map sample and start the default sound.

**Comment by mahoneyt944** [comment]
I think technically this sample is hooked up wrong. It's hooked on data "147" which fires at game over and the best runners screen right after.  Hence the outrun_lastwave flag to prevent it from restarting. "165" fires when you get to enter a highscore, which is when last wave is actually played.

The original sound plays through the game over and only plays last wave if you get to enter highscore.

Do we want the sample to play at game over or only when the player gets a highscore?

**Comment by grant2258** [comment]
Just goto the diagnostics should be able to issue sound tests thats how i worked on fixing sf2 issues on my port

**Comment by mahoneyt944** [comment]
I just wasn't sure what the intended trigger point is because the commenting doesn't match what's happening. Either we want the sample to play when lastwave plays as the commenting implies, or where it's hooked to now (at game over). 

The original game continues the game music through the game over and if the player gets a highscore then it plays lastwave.

The sample is called "map" so that implies it should be played at game over (when the coarse map is shown). So it's probably correctly hooked up, just the commenting needs corrected.

Is there a version of the game that actually used the map sample that I could reference perhaps to verify?

**Comment by grant2258** [comment]
I know it was a later mame the binary and source where available at the time. I would reference current mame for this could be this ole port is missing some code as far as the sound goes.

**Comment by mahoneyt944** [comment]
I'd be happy to cross compare later versions if someone can link me to it.

**Comment by grant2258** [comment]
you might want to ask KMFDManic I dont have any of the sources. One thing you need to keep in mind not all command given are to play sounds some fade and change pitch and other functions. You could look up cannon ball source code as well might save you some time.

**Comment by mahoneyt944** [comment]
Yeah I've been combing through each structure and the sample support can basically be broken down into a few conditions:

- return a default sound
- return no sound (aka do nothing)
- play samples
- stop samples
- adjust volume / fade volume (only used in moonwalker)
- game specific flags to monitor where the game is
- and combination of the above

That also being that I have not looked at sf2 at all since it's not currently active in this core. I plan to integrate that at some point again just haven't looked into it as of yet.

Ive been considering options to change the game specific flags init process. Currently we initiate these from the driver but this means we have to farm out these to all the drivers as extern variables. I think it might be cleaner to have a function to init these from within ost_samples.c and we can just call that from the driver. We'd also be able to call this if needed from our generate_ost_sound_* functions, like in the case of a game reset or new game starting etc.

**Comment by mahoneyt944** [comment]
@grant2258 just commited sf2 ost support #1270

Any chance you'd want to help test this new version? 🙃 So far seems pretty good, check the commit comments too.

**Comment by grant2258** [comment]
Well i fixed it up myself on my port didnt see anything really wrong with it apart from the fading code which didnt really fade at end of levels it should fade not instantly drop volume. If your using big samples if the unloading samples can be an issue you can end up with no music playing. Some of the ending where problematic I know blanka lead to no sound sometimes during level play due to sample unloading which was disabled on my port all together because the sample support in this core doesnt include the sample number playing just if a channel is playing.

I took a bit of time to get the timing to work properly for the fading on my port all i see you us subtracing a number instead of doing a fade unless i missed some code somewhere. I also changed how the sample volumes worked on my port as well as it didint translate well on thus port max vol for samples is 256 not 100 by default so i changed mine to 100 on my port a few games like zaxon needed fixed up doing this change. If your happy with it as is just go with it people will say if they come across issues anyway.

**Comment by mahoneyt944** [comment]
I changed how the fade works to remove the float to int conversion. Basically the the float method would always start at 1.0f and subtract 0.0048f each time. So this mean it will adjust approx 208 times before reaching zero. We also had to convert this to an int so you'd end up with this

Sample started at 1.0f converted.    = 100 volume
(1.000f - 0.0048 ) * 100 = (int)99.52 = 99 volume
(0.9952 - 0.0048) * 100 = (int)99.04 = 99 volume
(0.9904 - 0.0048) * 100 = (int)98.56 = 98 volume
(0.9856 - 0.0048) * 100 = (int)99.08 = 98 volume
etc etc

To avoid all the float conversations we just subtract one every other call by using a simple toggle `allow_fade`. This means we will reduce the volume approx 200 times before reaching zero. So you get this

Sample started at 100 volume
100 volume
99 volume
99 volume
98 volume
98 volume
etc etc

So it's essentially the same it terms of how long it takes to fade to zero. There's a usrintf_showmessage in ost_fade_volume() you can enable to watch the fading level in real time too.

**Comment by grant2258** [comment]
The floats where originally from from a later mame that uses that as long as the it times properly should be fine. Ill try test when I get time. About the volume this core by default is not setting 1 to 100 it will be 2.56 * your volume level.

https://github.com/libretro/mame2003-plus-libretro/blob/2bc0992710034afbdbf626f0402338f46121e6e4/src/sound/samples.c#L81-L105

**Comment by grant2258** [comment]
its also worth noting the float to int will drop the decimal point completely so  youll be counting down quicker as just using integers. If it times right at the end of level its all good though

**Comment by grant2258** [comment]
Havent been about git rear ended on friday so just been chilling going to catch some zzzs for work nice work on this btw ill try get some testing in the ost during the week or at the weekend at the latest

**Comment by mahoneyt944** [comment]
Thanks and sorry to hear.

uncomment this usrintf_showmessage to monitor the fade in real time. 
https://github.com/libretro/mame2003-plus-libretro/blob/2bc0992710034afbdbf626f0402338f46121e6e4/src/ost_samples.c#L453-L468

The fade use to be hooked on 0xf9. But this value gets called in some other undesirable places causing some bugs with endings and the title screen. So I re-hooked this and it's now very predictable. The new hook just so happens to call on top of where 0xf9 is at the end of a round so this was a win win.
