### ISSUE TITLE
Zero Point 2 (zeropnt2): reload issue

### ISSUE THREAD

**Issue by StormedBubbles** [libretro/mame2003-plus-libretro#1253]
Hi again,

The two games mentioned in the title work very well in this emulator aside from reload issues. I get shots registered on the edges of the screen when trying to reload in both of these games for the vast majority of reload attempts. It will work occasionally, but I can't pinpoint the conditions.

It doesn't appear that newer MAME versions introduced any fixes for this particular issue for these two games, so hopefully this doesn't require any back-porting to fix 😊

**Comment by mahoneyt944** [comment]
Lethalj returns the value here
https://github.com/libretro/mame2003-plus-libretro/blob/379c0e94268937fc498c01b0204b3bc873d77818/src/vidhrdw/lethalj_vidhrdw.c#L48-L74

Would have to determine what value forces a reload. And check against a threshold.

**Comment by StormedBubbles** [comment]
I should also mention that Zero Point 2 has a dipswitch to disable the need for reloading. If getting reload to work for that game is too much of a hassle, disabling reload is a good option. That makes the game play like the first Zero Point anyway.

**Comment by StormedBubbles** [comment]
https://github.com/libretro/mame2003-plus-libretro/commit/863389ff7e420e6c5991846ec669266ba2a531db resolved the issues with `lethalj`. Thanks! `zeropnt2` still has some erratic behavior when reloading is attempted. Some offscreen shots register as on screen, and some on-screen shots register as off screen. [A similar issue with this game was recently fixed in FBNeo](https://github.com/finalburnneo/FBNeo/commit/86e79b3e3b085d9041a5e58f4f523c3d7d205b05).

**Comment by mahoneyt944** [comment]
Appears to be game specific, thanks for linking a a good resource.

**Comment by mahoneyt944** [comment]
Fixed https://github.com/libretro/mame2003-plus-libretro/commit/664e176cb0cbf329663035ff9e55b6692700428a
