### ISSUE TITLE
Xeno Crisis XML code

### ISSUE THREAD

**Issue by Riddler1** [libretro/mame2003-plus-libretro#1254]
After purchasing a rom only copy of the game, The Bitmap Bureau advised that to run this game in mame, the following XML code needs to be added to a mame root subfolder called "hash".

..."Create a folder or zip file called xenocrisis with the supplied MAME ROM files and then copy the text from the provided neogeo.xml into the neogeo.xml file found
in the hash folder inside MAME's root."

Will this XML be needed in this core if trying to run the game via emulation station?

(neogeo.xml) attached
[neogeo.zip](https://github.com/libretro/mame2003-plus-libretro/files/7770335/neogeo.zip)

**Comment by Riddler1** [comment]
<software name="xenocrisis">

<description>Xeno Crisis</description>

<year>2021</year>

<publisher>Bitmap Bureau</publisher>

<info name="serial" value="NGM-BB01 (MVS), NGH-BB01 (AES)"/>

<info name="release" value="20211011 (MVS), 20211011 (AES)"/>

<sharedfeat name="release" value="MVS,AES"/>

<sharedfeat name="compatibility" value="MVS,AES"/>

<part name="cart" interface="neo_cart">

<dataarea name="maincpu" width="16" endianness="big" size="0x200000">

<rom loadflag="load16_word_swap" name="BB01-p1.p1" offset="0x000000" size="0x100000" crc="637605a6" sha1="179ebcdeaac3e561fd7acb72022eda8c3c74cb8a"/>

<rom loadflag="load16_word_swap" name="BB01-p2.p2" offset="0x100000" size="0x100000" crc="84838145" sha1="c1f48d333dfc85b9371f811dd449a42d8cdecf3f"/>

</dataarea>

<dataarea name="fixed" size="0x040000">

<rom offset="0x000000" size="0x020000" name="BB01-s1.s1" crc="7537ea79" sha1="b7242a6dd7b2ad8ccf7a223c08d626abf013f366"/>

</dataarea>

<dataarea name="audiocpu" size="0x010000">

<rom offset="0x000000" size="0x010000" name="BB01-m1.m1" crc="28c13ed9" sha1="a3c8cf36906293a24f1ed49376c9d561560d2730"/>

</dataarea>

<dataarea name="ymsnd:adpcma" size="0x1000000">

<rom name="BB01-v1.v1" offset="0x000000" size="0x1000000" crc="60d57867" sha1="e1f3f759b4af4404f19dd5b75135e6968b6be3c5"/>

</dataarea>

<dataarea name="sprites" size="0x400000">

<rom loadflag="load16_byte" name="BB01-c1.c1" offset="0x000000" size="0x200000" crc="ae51ef89" sha1="da82214263a99520364a2b7ab8140bdc68940f6d"/>

<rom loadflag="load16_byte" name="BB01-c2.c2" offset="0x000001" size="0x200000" crc="a8610100" sha1="aded6eaa17a518a8f4af9c3779c41ef8dd32a316"/>

</dataarea>

</part>

</software>

**Comment by mahoneyt944** [comment]
@KMFDManic just tested this game and might be able to guide you to get this game working.

**Comment by KMFDManic** [comment]
@Riddler1 @mahoneyt944 somehow I didnt get a ping to my email on this one.  Anyways, I didnt have to do anything special with XML at all.  It was merely a matter of having neogeo.zip bios in same directory as the rom, or in system.  That's it:)

**Comment by Riddler1** [comment]
yep great ok. No need for this then. with the neogeo bios in the roms folder, the game loads all ok. 👍
