### ISSUE TITLE
Master's Fury

### ISSUE THREAD

**Issue by arcadez2003** [libretro/mame2003-plus-libretro#1259]
@grant2258 @mahoneyt944 i've updated the Dragon Master driver and video code adding support for
Master's Fury, however due to those games requiring more than 64mg to load i've been unable to 
test em in MAME72.

As my MAME84 core has a VMM programe i was able to try both games and they seem fine considering
i had to heavily mod the code for use in this core, can one of ya's please test these in MAME2003+ to make
sure they'll work here.

We're only talking about a few lines of code being different in the mem map so im confident they'll be
fine here but as we've seen before you wouldn't wanna bet your house on it :)

Here is the code it should drop in but you'll need to dec the new romset in driver.c
[mastfury.zip](https://github.com/libretro/mame2003-plus-libretro/files/7782076/mastfury.zip)

Regards.

**Comment by grant2258** [comment]
Ill test it out later tonight m8 and let you know.

**Comment by arcadez2003** [comment]
Thanks man it seems i missed a small gfx commit im testing those changes now all being well i'll likely
push the commit later.

**Comment by grant2258** [comment]
Ill test it anyway mate sorry about the delay cars mot was up today and had to get it sorted its all good now. No advisories but am getting a slight knocking the drivers side the mot people cant find where its coming from either. Will need to sort it and get it sold dont need two cars but cant sell it our bumpy ole roads.

**Comment by mahoneyt944** [comment]
I was just working on my mine as well. I was getting a thud when the brakes were pressed. Turned out to be a torn control arm bushing popping around.

**Comment by grant2258** [comment]
changes the usual suspects control arms lower(uppers look good), steering rack, subrame, shocks strut mount and spings, inner and outter tie rods, drop links. It has upper control arms as well can get it off the knuckle though need a biger puller and can hit it as its alloy.

**Comment by grant2258** [comment]
@arcadez2003 good job as usual appears to be working fine! Now you two dont go mental at me for saying this the way these characters move bring back memories Yie Ar Kung-Fu accept on steroids.

**Comment by mahoneyt944** [comment]
Lol

**Comment by arcadez2003** [comment]
Yie Ar Kung-Fu now there's a blast from the past :)

**Comment by grant2258** [comment]
Rubbery keys and a heatsink radator at the for the cold winters very thoughtful design from Mr sinclair. I actually had this in the local arcade computers where so bad then haha

**Comment by arcadez2003** [comment]
Right i think we can close this down, on to the next one then
