### ISSUE TITLE
Games with a FPS below 47

### ISSUE THREAD

**Issue by arcadez** [libretro/mame2003-plus-libretro#126]
For testing purposes i'll make a list of all the games that have a frame rate below
47fps and that way we will know just how many grant actually fixed via the
core timing changes.

**Comment by arcadez** [comment]
Here's the list some wee gems in here :)

Armour Attack
Aztarac
Bally /  Midway MCR games (already been documented)
Barrier
Battle Zone
Big Run (11th rally version)
Boxing Bugs
Bradley Trainer
Cosmic Chasm
Demon
Eliminator
Gravitar
Green Beret / Rush' n Attack
Iron Horse
Juno First
Luner Battle 
Luner Lander
Omega Race
Red Baron
Rip Off
Scud Hammer
Shanghi
Shanghi 2
Space Duel
Space Fury
Space Wars
Solar Quest
Speed Freak
Star Castle
Star Hawk
Star Trek
Sundance
Tac Scan
Tail Gunner
The Empire Strikes Back
Tutankham
War Of The Worlds
Warrior
Zektor

Star Wars

**Comment by markwkidd** [comment]
@KMFDManic

**Comment by KMFDManic** [comment]
@arcadez Absolutely awesome!  Really happy to see a preliminary list of awesomeness there:)  I will check into each and every one:)

@markwkidd Thanks for the ping:)  You rock!

@grant2258 I would absolutely love to see a complete list!

And, to all of you, you can see me embarrass myself, enjoying one commit, I believe gamez-fan did awhile back, that got the absolutely incredible game, Rogha going!  I do tech videos, as well as silly videos.  Check out the first minute or so to see me embarrass myself, haha:)

https://www.youtube.com/watch?v=-L2ZyvChaVE

**Comment by markwkidd** [comment]
LOL Love the videos, keep them coming

**Comment by grant2258** [comment]
lol nice vid!!!!!

here is the list its from the mame078 ill update with mame2003+dat incase there is any more

archriv2 Arch Rivals (rev 2.0) 30.000000
archrivl Arch Rivals (rev 4.0) 30.000000
armora Armor Attack 38.000000
armorap Armor Attack (prototype) 38.000000
armorar Armor Attack (Rock-ola) 38.000000
aztarac Aztarac 40.000000
barrier Barrier 38.000000
bigrun Big Run (11th Rallye version) 30.000000
blasted Blasted 30.000000
boxingb Boxing Bugs 38.000000
bradley Bradley Trainer 40.000000
bzone Battle Zone (set 1) 40.000000
bzone2 Battle Zone (set 2) 40.000000
bzonec Battle Zone (cocktail) 40.000000
cchasm Cosmic Chasm (set 1) 40.000000
cchasm1 Cosmic Chasm (set 2) 40.000000
cischeat Cisco Heat 30.000000
crater Crater Raider 30.000000
dairesya Dai Ressya Goutou (Japan) 30.000000
deltrace Delta Race 40.000000
demoderb Demolition Derby 30.000000
demoderm Demolition Derby (2-Player Mono Board Version) 30.000000
demon Demon 38.000000
domino Domino Man 30.000000
dotron Discs of Tron (Upright) 30.000000
dotrona Discs of Tron (Upright alternate) 30.000000
dotrone Discs of Tron (Environmental) 30.000000
elim2 Eliminator (2 Players, set 1) 40.000000
elim2a Eliminator (2 Players, set 2) 40.000000
elim4 Eliminator (4 Players) 40.000000
esb The Empire Strikes Back 30.000000
f1gpstar Grand Prix Star 30.000000
f1gpstr2 F-1 Grand Prix Star II 30.000000
farwest Far West 30.000000
gberet Green Beret 30.000000
ironhors Iron Horse 30.000000
journey Journey 30.000000
junofrst Juno First 30.000000
junofstg Juno First (Gottlieb) 30.000000
kick Kick (upright) 30.000000
kicka Kick (cocktail) 30.000000
kroozr Kozmik Kroozr 30.000000
llander Lunar Lander (rev 2) 40.000000
llander1 Lunar Lander (rev 1) 40.000000
lunarba1 Lunar Battle (prototype, earlier) 45.000000
maxrpm Max RPM 30.000000
omegrace Omega Race 40.000000
pigskin Pigskin 621AD 30.000000
powerdrv Power Drive 30.000000
rampage Rampage (revision 3) 30.000000
rampage2 Rampage (revision 2) 30.000000
rbtapper Tapper (Root Beer) 30.000000
redbaron Red Baron 45.000000
ripoff Rip Off 38.000000
rushatck Rush'n Attack 30.000000
sarge Sarge 30.000000
scudhamm Scud Hammer 30.000000
shangha2 Shanghai II (Japan) 30.000000
shanghai Shanghai (Japan) 30.000000
shollow Satan's Hollow (set 1) 30.000000
shollow2 Satan's Hollow (set 2) 30.000000
solarfox Solar Fox 30.000000
solarq Solar Quest 38.000000
spacduel Space Duel 45.000000
spacewar Space Wars 38.000000
spacfura Space Fury (revision A) 40.000000
spacfury Space Fury (revision C) 40.000000
speedfrk Speed Freak 38.000000
spyhnt2a Spy Hunter 2 (rev 1) 30.000000
spyhunt Spy Hunter 30.000000
spyhunt2 Spy Hunter 2 (rev 2) 30.000000
starcas Star Castle (version 3) 38.000000
starcas1 Star Castle (older) 38.000000
starcase Star Castle (Mottoeis) 38.000000
starcasp Star Castle (prototype) 38.000000
stargrds Star Guards 30.000000
starhawk Star Hawk 38.000000
startrek Star Trek 40.000000
starwar1 Star Wars (rev 1) 30.000000
starwars Star Wars (rev 2) 30.000000
stellcas Stellar Castle (Elettronolo) 38.000000
sundance Sundance 38.000000
sutapper Tapper (Suntory) 30.000000
tacscan Tac/Scan 40.000000
tailg Tailgunner 38.000000
tapper Tapper (Budweiser) 30.000000
tappera Tapper (alternate) 30.000000
timber Timber 30.000000
trisport Tri-Sports 30.000000
tron Tron (set 1) 30.000000
tron2 Tron (set 2) 30.000000
turbotag Turbo Tag (prototype) 30.000000
tutankhm Tutankham 30.000000
tutankst Tutankham (Stern) 30.000000
twotiger Two Tigers 30.000000
twotigra Two Tigers (dedicated) 30.000000
wacko Wacko 30.000000
warrior Warrior 38.000000
wotw War of the Worlds 38.000000
xenophob Xenophobe 30.000000
zektor Zektor (revision B) 40.000000
zwackery Zwackery 30.000000

**Comment by KMFDManic** [comment]
@grant2258 Thanks so much for the list!  @markwkidd Glad you both are enjoying the Videos:)  Like I said, I do a combination of Tech Videos, as well as silly stuff.  I did one video where I played Adventures of Bayou Billy for NES, arguably, one of the more difficult games...and, ripped apart its silly AI.  I make the game a cakewalk with my tactics, haha:)

https://www.youtube.com/watch?v=AQbnIkEDSIQ&t=2s

**Comment by markwkidd** [comment]
Bayou Billy was my Everest when I was young. I never did reach the summit...

**Comment by KMFDManic** [comment]
Thanks again for the lists @arcadez and @grant2258 Absolutely tremendous compatibility Update, wise:)  

@markwkidd Don't be so modest, you do some truly kickass work!

**Comment by KMFDManic** [comment]
Most I have tested, work great. I need to check again.  But, Lunar Lander controls may still be broken.  Seems possibly off in my quick test.

But, thanks again for the list, all of you!

Star Wars, once wave 4 is defeated, the Death Star run never triggers.  You simply fly, endlessly, haha.

Rush N Attack and Iron Horse and Juno First all run great.

And, of course, the obvious flipped screen/controls on a few:)

And, while I have your attention, @arcadez, what is your opinion of backporting tcaveman?  

Thanks!

**Comment by grant2258** [comment]
@KMFDManic thanks for teh update the flipped controls are a pain it because we need to un mirror the screen the core doesnt handle this at the moment.

Star Wars, once wave 4 is defeated, the Death Star run never triggers. You simply fly, endlessly, haha.

ive never played this game will give it a bash

**Comment by arcadez** [comment]
@KMFDManic thanks for giving em those a whirl i guess that's more classics we can add to
the now fixed and playable list thanks to @grant2258 :)

@KMFDManic with regards to tommy caveman i pointed out to you a while back we are limited
around what we can backport to this ole core for a few reasons, without rabbiting on basically 
the major memory handling update in MAME79 the huge input port changes in the MAME84-88
dev cycle and finally the latest mame code generally being incompatable with this core

For the above reasons it's not possible to support that game is this core.

**Comment by KMFDManic** [comment]
@arcadez Understood:)  There has been one individual who has been really wanting it to work.  And, sadly, a lot of obstacles running it:)  MAME 2014 is the last MAME we can properly run.  MAME has issues, and MESS has a few issues.  But, over time, may be able to sort things out.  But, thanks for reminding me on Tcaveman!  It is already incredibly awesome that some of the Data East games such as Rohga, Boogie Wings, etc. were able to be fixed!  Thanks for the response!

**Comment by ZappaUtopia** [comment]
I can confirm the Star Wars bug.

If you start on 'Easy' and get to Wave 3, after shooting all the Tie Fighters you are just left on your own with the Death Star in the distance, it should be the towers stage.

If you start on 'Medium' (which is Wave 3), it works fine.

@markwkidd @grant2258 Should I open this as an issue ?

**Comment by markwkidd** [comment]
Unless someone knows an immediate fix I think it's worth a new Issue.

I see some potential starting points for investigation in the history of the driver: http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=starwars&lang=en
```
0.80u2: Reverted some Star Wars code back to older working version (machine\starwars.c), this fixes bad trench vectors in Star Wars.
0.79: Aaron Giles fixed a problem with Star Wars.
0.71u3: Frank Palazzolo removed "bad trench vectors hack" from Star Wars which he created in 1997. Appears not to be necessary any more.
```
