### ISSUE TITLE
XML year field issue

### ISSUE THREAD

**Issue by leov30** [libretro/mame2003-plus-libretro#1264]
the script making the XML datafile is ignoring years with '?' characters
like this game from gundealr.c

GAME( 19??, gundeala, gundealr, gundealr, gundealr, gundealr, ROT270, "Dooyong", "Gun Dealer (set 2)" )

the year dosen't shows up in the XML

	<game name="gundeala" sourcefile="gundealr.c" cloneof="gundealr" romof="gundealr">
		<description>Gun Dealer (set 2)</description>
		<manufacturer>Dooyong</manufacturer>

**Comment by markwkidd** [comment]
The best thing would be if someone had time to update that information with
the correct year, since in many cases that information is now available.

Is there any chance you are interested in helping update this data?

**Comment by leov30** [comment]
most of those games years still have the '?" character in the current MAME release
best thing its to fix the code that's generating the XML

**Comment by grant2258** [comment]
This is a simple fix dont see much point in adding invalid data myself again in not very bothered about this to be honest.

https://github.com/libretro/mame2003-plus-libretro/blob/0332a2003fb1ae40e5f03b27392e14027ea148dd/src/info.c#L727-L729

just remove the if condition if you want all the data to print. Its really a maintainers call on it.

**Comment by mahoneyt944** [comment]
Couldn't we just add the "?" Character to the string? So it supports 0-9 and "?" For these few cases.

**Comment by leov30** [comment]
not really an issue, since 'year' its not a required field, its just missing information not being passed into the datafile.
however, I found 87 games with missing 'year' by parsing the XML into a spreadsheet.

**Comment by mahoneyt944** [comment]
I'm running a test branch to see. Though I'm not sure why we would want to fill the year in with an "idk" year. Seems counter productive besides completing a format

**Comment by mahoneyt944** [comment]
Here's the comparison if we should choose to integrate this.
https://github.com/libretro/mame2003-plus-libretro/compare/Year

**Comment by grant2258** [comment]
youll need to add + as well one has that at least didnt check them all seems stupid doing a number check when there are non numerical values just check if the strings not null would make more sense,

```
dealer 19??
tst_galx 19??
pisces 19??
piscesb 19??
exodus 19??
smooncrs 1980?
scorpnmc 19??
mimonscr 198?
mimonkey 198?
mimonsco 198?
rpatrolb 1982?
silvland 1982?
drakton 198?
nss_smw 199?
nss_fzer 199?
nss_sten 199?
sinvzen 19??
superinv 19??
sinvemag 19??
invrvnge 19??
invrvnga 19??
alieninv 19??
tst_invd 19??
grudge 198?
ipminvad 1979?
cubybop 199?
4in1boot 199?
moremorp 199?
legend 1986?
alphaho 19??
fantzn2 198?
aceattac 19??
afighter 19??
cltchitr 19??
cotton 19??
cottona 19??
ddcrew 19??
dunkshot 19??
exctleag 19??
lghost 19??
loffire 19??
mvp 19??
ryukyu 19??
suprleag 19??
thndrbld 19??
thndrbdj 19??
sspirits ????
sgmast ????
qsww ????
gground ????
crkdown ????
shougi 198?
shougi2 198?
dommy 198?
pkunwar 1985?
pkunwarj 1985?
arkarea 1988?
vgoalsoc 199?
vgoalsca 199?
worldc94 199?
gundeala 19??
ladykill 1993?
moegonta 1993?
spcforc2 19??
paradise 1994+
magicbub 19??
inca 199?
cabaret 19??
mblkjack 197?
yumefuda 199?
jogakuen 1992?
mjikaga 1991?
hexa 1986?
mugsmash 1990?
fitfight 199?
histryma 199?
bbprot 199?
beaminv 19??
oneshot 199?
truco 198?
rotaryf 19??
vamphalf 19??
hidnctch 19??
landbrk 19??
racoon 19??
xfiles 19??
malzak 19??
```

**Comment by mahoneyt944** [comment]
> youll need to add + as well one has that at least didnt check them all seems stupid doing a number check when there are non numerical values just check if the strings not null would make more sense,

Good catch, doesn't really matter to me. I agree a null check would be better if we want these misfits to show.

**Comment by grant2258** [comment]
Again its one of them meh who cares moments the cleanest solution imho is output N\A in and else condition or print it all.

**Comment by leov30** [comment]
the '+' symbol in the year seems to be left overs from older MAME, I don't think its used anymore.
well, I am closing, since you already got notified about the issue, and I think you got it sorted out.
