### ISSUE TITLE
XML datafile not showing 'imperfect' overall status

### ISSUE THREAD

**Issue by leov30** [libretro/mame2003-plus-libretro#1268]
The overall status for a game with any IMPERFECT flags in the drivers should be imperfect
like this game "Jack Rabbit (set 1)" from the datafile:

driver status="good" color="good" sound="imperfect" graphic="good" palettesize="512"

The header of the XML also doesn't shows the "imperfect" status, however there's one that its not used "test". 
!ATTLIST driver status (good|preliminary|test) #REQUIRED

**Comment by mahoneyt944** [comment]
This isn't the overall status, each field represents specific flags. You can see how it's broken down here. Each game is broken into several "drivers" so the main loading driver can be good while a graphics driver is wrong.

https://github.com/libretro/mame2003-plus-libretro/blob/1d483a22943c7e31c7438b054b4b413cc9996120/src/info.c#L658-L693

**Comment by leov30** [comment]
so "status" its just for emulation? its confusing since they change it in later MAME

the status field was improved in MAME 0.139 to show more information,
```<driver status="imperfect" emulation="good" color="imperfect" sound="good" graphic="good" savestate="supported" palettesize="32"/>```

so, as feature request I propose to implement the newer "status" field in the XML

MAME 0.139, info.c
```
void info_xml_creator::output_driver()
{
	fprintf(m_output, "\t\t<driver");

	/* The status entry is an hint for frontend authors */
	/* to select working and not working games without */
	/* the need to know all the other status entries. */
	/* Games marked as status=good are perfectly emulated, games */
	/* marked as status=imperfect are emulated with only */
	/* some minor issues, games marked as status=preliminary */
	/* don't work or have major emulation problems. */

	if (m_drivlist.driver().flags & (MACHINE_NOT_WORKING | MACHINE_UNEMULATED_PROTECTION | MACHINE_NO_SOUND | MACHINE_WRONG_COLORS | MACHINE_MECHANICAL))
		fprintf(m_output, " status=\"preliminary\"");
	else if (m_drivlist.driver().flags & (MACHINE_IMPERFECT_COLORS | MACHINE_IMPERFECT_SOUND | MACHINE_IMPERFECT_GRAPHICS))
		fprintf(m_output, " status=\"imperfect\"");
	else
		fprintf(m_output, " status=\"good\"");

	if (m_drivlist.driver().flags & MACHINE_NOT_WORKING)
		fprintf(m_output, " emulation=\"preliminary\"");
	else
		fprintf(m_output, " emulation=\"good\"");

	if (m_drivlist.driver().flags & MACHINE_WRONG_COLORS)
		fprintf(m_output, " color=\"preliminary\"");
	else if (m_drivlist.driver().flags & MACHINE_IMPERFECT_COLORS)
		fprintf(m_output, " color=\"imperfect\"");
	else
		fprintf(m_output, " color=\"good\"");

	if (m_drivlist.driver().flags & MACHINE_NO_SOUND)
		fprintf(m_output, " sound=\"preliminary\"");
	else if (m_drivlist.driver().flags & MACHINE_IMPERFECT_SOUND)
		fprintf(m_output, " sound=\"imperfect\"");
	else
		fprintf(m_output, " sound=\"good\"");

	if (m_drivlist.driver().flags & MACHINE_IMPERFECT_GRAPHICS)
		fprintf(m_output, " graphic=\"imperfect\"");
	else
		fprintf(m_output, " graphic=\"good\"");

	if (m_drivlist.driver().flags & MACHINE_NO_COCKTAIL)
		fprintf(m_output, " cocktail=\"preliminary\"");

	if (m_drivlist.driver().flags & MACHINE_UNEMULATED_PROTECTION)
		fprintf(m_output, " protection=\"preliminary\"");

	if (m_drivlist.driver().flags & MACHINE_SUPPORTS_SAVE)
		fprintf(m_output, " savestate=\"supported\"");
	else
		fprintf(m_output, " savestate=\"unsupported\"");

	fprintf(m_output, "/>\n");
}
```

**Comment by mahoneyt944** [comment]
Yeah. newer mame uses "status" as a "dummy light" and "emulation" is the new place holder for the old status. Seems like overkill to me personally, obviously if any field has anything but "good" the overall status would reflect that.

This wouldn't be hard to implement if we wanted this change, but I'd have to verify that datmagic (the tool that builds the compatibility table) is also aware of this change.

**Comment by leov30** [comment]
alright, i'll close since its not an issue.
thanks for clarifying what I assume was a problem
