### ISSUE TITLE
catver.ini corrections 

### ISSUE THREAD

**Issue by leov30** [libretro/mame2003-plus-libretro#1269]
I made corrections to the catver.ini, now every game from the datafile has a entry, even BIOS
its align to MAME 0.239 catver.ini
I included the original catver_old.ini for comparison, you can use winmerge to see the changes I made
I also included an alternative version catver_alt.ini with the "Unplayable" category for games that have the NOT_WORKING flag
there's another file catver.txt, that's all the categories listed and how many times they appear.  
 
[leov30_catver.zip](https://github.com/libretro/mame2003-plus-libretro/files/7826293/leov30_catver.zip)

**Comment by mahoneyt944** [comment]
Thanks for working on this I know how tedious it can be. Unfortunately there are entries that need looked into further in catver.ini

Games which I noticed but maybe more..... wpksoc, solarwar, kopunch, silkshot, sliksh17, omega, or anything with "Electromechanical / Misc."

Make sure that any fields which are updated make sense, for example if the game was noted as pinball before and now is labeled "scrolling shooter" or something, these need hand checked to be sure.

**Comment by mahoneyt944** [comment]
Ok pushed your new carver.ini with a few light changes thank you
