### ISSUE TITLE
Possible implementation of Donggul Donggul Haerong (Wonder Boy Style Game)

### ISSUE THREAD

**Issue by KMFDManic** [libretro/mame2003-plus-libretro#1272]
I was going through some of the other games on higher MAME revisions.  And, I came across this unique game, which is a Wonder Boy style one.

https://www.youtube.com/watch?v=5DbKKREt1e4

Not even sure we can add this to 2003 Plus.  But, figured, why not at least poke at its implementation and see if its plausible @arcadez2003 ?

https://www.mamedev.org/releases/whatsnew_0168.txt

 (I changed the number in the url to reflect each MAME version, to very quickly see what was new on each.)

And, I see a whole slew of other later games were already added by you.  Just not sure if you had looked into THIS particular one.  Top Landing also looks kind of interesting, as it is a Flight Sim game.  You did great with Ken Go, and a few other recent additions.  Just trying to find more gems that we may have missed!

**Comment by arcadez2003** [comment]
Donggul Donggul Haerong is Crystal System we have none of the code for this, as for Top Landing looks like alotta graft
for one working game http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=topland&search_id=

I think i'll leave these ones upto someone else :)
