### ISSUE TITLE
Cheat file question

### ISSUE THREAD

**Issue by mahoneyt944** [libretro/mame2003-plus-libretro#1276]
The cheat engine reads in cheat.dat but it appears like it can read cheat files of a different name? Anyone know if this is the case? Logging the buffer from loadcheatdatabase, I can only ever get cheat.dat passed to loadcheatfile? Is there another excepted format name?

https://github.com/libretro/mame2003-plus-libretro/blob/38fe93119e2606b478a16789ec22d4addef230ae/src/cheat.c#L399

https://github.com/libretro/mame2003-plus-libretro/blob/38fe93119e2606b478a16789ec22d4addef230ae/src/cheat.c#L856

https://github.com/libretro/mame2003-plus-libretro/blob/38fe93119e2606b478a16789ec22d4addef230ae/src/cheat.c#L8382-L8432

**Comment by grant2258** [comment]
yea you could set the cheatfile name from the command line on the original mame078 and you could set it i the ini file as well if you had a different named cheatfile

**Comment by mahoneyt944** [comment]
Is any of that still functional to us?

**Comment by grant2258** [comment]
Cant see any reason for it on a libretro port. Thing is if you want to keep it portable to other platforms as well you might not want to remove this stuff if your interested in cutting out extra code just remove it. Depends on your views of the project. Right now it would be a lot of work porting it back to windows anyway because a lot of code was ripped out already anyway.

**Comment by mahoneyt944** [comment]
I'm working on loading the cheatfile faster through compression and other optimizations so I'm just reviewing the cheat code that's there now.

It seems like we could simplify loadcheatdatabase() significantly if not remove it entirely for this core and use loadcheatfile() with just cheat.dat as the filename.

**Comment by mahoneyt944** [comment]
Especially if the ini support isn't hooked up. I can't see any references to it but maybe I'm missing them?

**Comment by markwkidd** [comment]
ini support is definitely not hooked up, if I'm understanding the question.

**Comment by mahoneyt944** [comment]
Ok so im going to just use cheat.dat and remove the excess stuff. It also looks like we read in the entire cheat file and if edited, save the entire cheat file. This seems rather inefficient, typically we are only using a handful of lines for each game. The issue here is that in order to save to new cheat.dat we need it loaded. However, we could scan cheat.dat on load for what we need and simply save edits/new cheats to its own file in the system directory. This could reduce a huge part of the slow down. Then by utilizing rzip in the libretro library we could make reading the the cheat file much faster. Cheat.dat compressed about 7:1
