### ISSUE TITLE
Crashes on startup Nintendo Switch

### ISSUE THREAD

**Issue by Sludgebuster** [libretro/mame2003-plus-libretro#1282]
Running Name 2003 plus from the Homebrew menu. It crashes immediately with error 2498-8191

**Comment by mahoneyt944** [comment]
Need some details on the version of 2003+ your using and if you can get any logging at all that would be great

**Comment by arcadez2003** [comment]
Alotta build errors just now also, upstream libretro issues most likely

**Comment by Sludgebuster** [comment]
It says very early beta last updated 2018. I guess that reason why. I'm running latest Atmosphere and Firmware. It's actually error code 2001-000. Alot of homebrew apps are crashing.

**Comment by mahoneyt944** [comment]
I would recommend using the latest versions of everything. You should be able to download the latest versions of RetroArch and mame2003-plis from here. https://buildbot.libretro.com/nightly/nintendo/switch/libnx/

**Comment by mahoneyt944** [comment]
I now have 2 confirmations that the switch build is working as expected for other users. Have you made any progress with this crash issue?
