### ISSUE TITLE
Recalbox 8.0.2 - issue with lightgun games 

### ISSUE THREAD

**Issue by Ltort79** [libretro/mame2003-plus-libretro#1285]
Good morning,
I have not been able to find solutions on the failure of some roms on recalbox 8.0.2 installed on raspberry p4 for weeks.
in practice, after having ensured the compliance and adequacy of the roms (with clearmame pro, romulus and mame set rebuilder) I cannot make them work with any core mame (except advancemame which however does not support the lightgun). the singularity of the problem is that they are all lightgun games and many of a single manufacturer exidy. all the other roms of the various sets work (including some roms for lightgun). what can I do?
sincere thanks for the help you will give me

**Comment by mahoneyt944** [comment]
Hello, have you verified that the roms you are trying to load are working games in this core? You can check against this compatibility table:
https://buildbot.libretro.com/compatibility_lists/cores/mame2003-plus/mame2003-plus.html

**Comment by Ltort79** [comment]
Hello, yes. They have good status (chiller, Cheyenne, crossbow, lethal Justice, nycaptor, whodunit, police trainer) . They worked in recent past but now, I don't know why, stopped to work. I could  not understand what is the problem if a scraping or else. Anyway I made scrap again and checked name and correspondence with dat xml file and gamelist, all is aligned. It's like the core read an error launching roms. Thanks 


Inviato da Yahoo Mail su Android 
 
  Il mer, 2 feb, 2022 alle 10:49, ***@***.***> ha scritto:   


Hello, have you verified that the roms you are trying to load are working games in this core? You can check against this compatibility table:
https://buildbot.libretro.com/compatibility_lists/cores/mame2003-plus/mame2003-plus.html

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mahoneyt944** [comment]
With a quick test of nycaptor it seems to load just fine. Can you post a log when trying to load this game?
![nycaptor-220202-050955](https://user-images.githubusercontent.com/49591133/152134106-ee189327-bcd8-4c33-b8f6-8c0a41b6bb05.png)

**Comment by Ltort79** [comment]
How I can generate a log? Thanks so much

Inviato da Yahoo Mail su Android 
 
  Il mer, 2 feb, 2022 alle 11:11, ***@***.***> ha scritto:   


With a quick test of nycaptor it seems to load just fine. Can you post a log when trying to load this game?


—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mahoneyt944** [comment]
Do you have access to the retroarch menu?
- settings-> logging-> logging verbosity-> toggle on
- settings-> logging-> log to file-> toggle on

Then launch the rom.

**Comment by Ltort79** [comment]
Yes I think I could access by launching other rom on recalbox then activer menu and go in the settings that you have indicated me. I'm at office now. I'll try after 6 p.m. And I make as you suggested. Where I can find log result in share fder of recalbox? many thanks for your help

Inviato da Yahoo Mail su Android 
 
  Il mer, 2 feb, 2022 alle 11:26, ***@***.***> ha scritto:   


Do you have access to the retroarch menu?
   
   - settings-> logging-> logging verbosity-> toggle on
   - settings-> logging-> log to file-> toggle on

Then launch the rom.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mahoneyt944** [comment]
I'm not familiar with recalbox but retroarch will save it as retroarch.log found in:
Retroarch directory-> logs->retroarch.log

This maybe setup differently for recalbox

**Comment by Ltort79** [comment]
i have tried a lot of times and in the end setting level 3 error for log generation seems to have worked. I am attaching you log. they do not report the names of the roms. but to see the time are all the times that I tried to launch the roms not working. I hope now you can continue to guide me towards a solution
thanks again for your invaluable help

    Il mercoledì 2 febbraio 2022, 11:49:22 CET, mahoneyt944 ***@***.***> ha scritto:  
 
 


I'm not familiar with recalbox but retroarch will save it as retroarch.log found in:
Retroarch directory-> logs->retroarch.log

This maybe setup differently for recalbox

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Ltort79** [comment]
sorry but I am very bad in English, do you mean that you do not find a link between the failure of the roms and the attached logs or that you do not see the attachments?
I'll copy the contents of one below. thank you


WARN] --libretro argument "/usr/lib/libretro/mame_libretro.so" is neither a file nor directory. Ignoring.
[INFO] === Build =======================================
[INFO] Funzionalità:  NEON VFPv3 VFPv4
[INFO] Built: Jan 30 2022
[INFO] Version: 1.9.8
[INFO] =================================================
[INFO] [Input]: Found input driver: "udev".
[ERROR] [Core]: Frontend is built for dynamic libretro cores, but path is not set. Cannot continue.
[ERROR] Errore irreversibile ricevuto in: "init_libretro_symbols()"
[INFO] [Core]: Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[INFO] [Core]: Unloading core symbols..
[INFO] [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.
Inviato da Yahoo Mail su Android 
 
  Il mer, 2 feb, 2022 alle 23:05, ***@***.***> ha scritto:   


Sure, i don't see it linked though.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mahoneyt944** [comment]
This does not seem like a log from this core, are you sure you have mame2003-plus selected to run this rom?

**Comment by Ltort79** [comment]
Sure! In recalbox mame2003plus is settled as standard for opening mame roms. What other check/report I could do to help you to find where is the problem? Thanks

Inviato da Yahoo Mail su Android 
 
  Il gio, 3 feb, 2022 alle 9:36, ***@***.***> ha scritto:   


This does not seem like a log from this core, are you sure you have mame2003-plus selected to run this rom?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mahoneyt944** [comment]
`"/usr/lib/libretro/mame_libretro.so"` this is not the correct emulator name.

**Comment by Ltort79** [comment]
How I can proceed? Or fix? By w

Inviato da Yahoo Mail su Android 
 
  Il gio, 3 feb, 2022 alle 12:58, ***@***.***> ha scritto:   


"/usr/lib/libretro/mame_libretro.so" this is not the correct emulator name.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Ltort79** [comment]
I also found this error with ko roms 
libretro ERROR] [MAME 2003+] error: palette_set_color() called with color 1024, but only 1024 allocated
Inviato da Yahoo Mail su Android 
 
  Il gio, 3 feb, 2022 alle 12:58, ***@***.***> ha scritto:   


"/usr/lib/libretro/mame_libretro.so" this is not the correct emulator name.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mahoneyt944** [comment]
That looks like the proper log for ko. Whatever is going on with exidy, it doesn't seem proper. I'm not sure what to advise.

**Comment by Ltort79** [comment]
So you suggest me to surrender? 

Inviato da Yahoo Mail su Android 
 
  Il gio, 3 feb, 2022 alle 13:57, ***@***.***> ha scritto:   


That looks like the proper log for ko. Whatever is going on with exidy, it doesn't seem proper. I'm not sure what to advise.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mahoneyt944** [comment]
Are you able to reinstall mame2003-plus? Maybe you can get a fresh image?

**Comment by mahoneyt944** [comment]
Just found this, looks like the maybe as to assist you here https://forum.recalbox.com/topic/26079/mame-appears-to-be-broken-in-recalbox-8

Seems to be a recalbox issue not core related

**Comment by Ltort79** [comment]
Thank you

Inviato da Yahoo Mail su Android 
 
  Il sab, 5 feb, 2022 alle 21:05, ***@***.***> ha scritto:   


Just found this, looks like the maybe as to assist you here https://forum.recalbox.com/topic/26079/mame-appears-to-be-broken-in-recalbox-8

Seems to be a recalbox issue not core related

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
