### ISSUE TITLE
Need support for Cinematronics games

### ISSUE THREAD

**Issue by wolfgangrumpf** [libretro/mame2003-plus-libretro#1291]
Some of my favorite games are the old Cinematronics vector graphics games like Tail Gunner - if you could add support for that, I would be very happy!

**Comment by mahoneyt944** [comment]
This game does work but without sound.

**Comment by arcadez2003** [comment]
0.79u2: Support for Tailgunner samples recorded by Zonn Moore. Added Samples sound (bounce, hypersp, sexplode, shield, slaser and thrust1.wav).

**Comment by mahoneyt944** [comment]
I didn't look too much into it yet, I did peek at mame2010 which has an isolated audio driver with a few games in there. All sample based. If it was supported earlier maybe it would be even easier.

**Comment by mahoneyt944** [comment]
Did a quick plug in, still need the driver side though. See tail branch for reference

**Comment by mahoneyt944** [comment]
Am I nuts or are samples only supported on two channels? Why does this driver and many others use more channels?

**Comment by mahoneyt944** [comment]
#1293 samples added, seems like analog control does not work though, only digital...haven't looked into it yet.
