### ISSUE TITLE
Final Fight double impact samples not sound always

### ISSUE THREAD

**Issue by Ipxildor** [libretro/mame2003-plus-libretro#1294]
Hello good. I have put the soundtrack of the double impact version in the specified path of retroarch/system/mame2003plus/samples. It turns out that if you start the game, the warning appears that some clues cannot be found, the thing is that you start playing and they start to fail in some sections of the final part of the game and the penultimate phase. If you use the savestate and go through those places there are occasions that it reproduces them and others not. Is it my problem or is it the core of the emulator. If so, could you explain to me how to fix it (some tutorial) because I've been stuck and I can't find the solution. I have tested the ones from the sega mega CD version and it reads them without any problem. All the best.
PS: if you explain it to me as if it were a fool I would appreciate it since English is not my language. Thanks.
My sample soundtrack
![Sin título](https://user-images.githubusercontent.com/97182047/155441788-feae83d8-7f49-4f72-8f4b-6797fb4a03ef.jpg)

**Comment by mahoneyt944** [comment]
It seems like you are missing samples. These are the sample files that are expected to be loaded

https://github.com/libretro/mame2003-plus-libretro/blob/91547c9892090250493ade59b1d76f0b2bb48cda/src/ost_samples.c#L94-L143

**Comment by mahoneyt944** [comment]
https://drive.google.com/drive/folders/13Lzqdx2kH-G3t4aStfkznu5uQK7ThMwi

**Comment by Ipxildor** [comment]
this is the samples who i am using:
https://drive.google.com/file/d/1bFCH5FJzX8eiaj1sUIZlBOm11qWoQaOm/view

**Comment by Ipxildor** [comment]
i will fix the problem and runs perfect.  i write a guide for dummies like me. ty to all ^^
