### ISSUE TITLE
starblad mouse/lightgun controls

### ISSUE THREAD

**Issue by StormedBubbles** [libretro/mame2003-plus-libretro#1299]
Hi all,

I suppose this request could relate to several games with a similar control scheme, but I will concentrate on Starblade since it plays far better in 2003-plus than in any other (libretro) emulator on a Raspberry Pi 4B.

Starblade was one of those yoke/stick games that seems to translate well to mouse/lightgun controls in more recent MAME versions. Could there be an option to use mouse/lightgun controls for it in 2003-plus? 

As it currently stands, the movement is all over the place when trying to use a mouse device. Later MAME versions allow the user to use either a stick or a mouse/lightgun for controlling this game. It would be awesome to be able to do the same in 2003-plus 😃

**Comment by mahoneyt944** [comment]
A mouse should be fine with this game. You may have to disable "center joystick axis for digital controls" under input options.

**Comment by StormedBubbles** [comment]
That did the trick. Thanks! It works fine with a Sinden gun too, as long as you reduce the analog sensitivity.
