### ISSUE TITLE
Deco Cassette Driver GPL2

### ISSUE THREAD

**Issue by arcadez2003** [libretro/mame2003-plus-libretro#1316]
So i just fixed Zeroize in decocass.c nice wee game reminds me of Namco's motos, anyway the driver is now GPL2 in current
MAME but this fix takes code from well before it was re-licenced so we're ok to use it here and other code i added
with regards to my other recent additions in our version of the driver namely Angler Dangler / Fishing as again the code
for those games comes pre the re-licence.

The fact decocass is now GPL2 is a real pity right enough as there are some cracking games exclusive to this system which 
were either dumped then supported or fixed up graphically and or made playable after the driver was switched to GPL2, 
we cannot touch that code for obvious reasons.

However there are two games one of which is Manhattan one of the best on this system the other a Sumo Wrestling game
and there are not many of those kicking around, we could add those no problem Manhattan would need some of the video
updated right enough, but @mahoneyt944 just want your opinion around if you think it's worth it.??

Personally im not sure as the problem is to support these we'd need to update the decocass bios as they use a type to boot
the main cpu which we dont support here, that would break every game in the driver for users who dont suss out that some new updated bios would then be required so i dunno we should do this for two games just or leave it well alone.

Decisions decisions :)

**Comment by mahoneyt944** [comment]
Nice addition. 

Hmm, might be more hassle than it's worth for two games. Surely would need lots of testing also.

**Comment by arcadez2003** [comment]
Aye your right let's forget it.
