### ISSUE TITLE
A recent fix for R-type Leo

### ISSUE THREAD

**Issue by arcadez2003** [libretro/mame2003-plus-libretro#1318]
@mahoneyt944 There was a recent commit which sorted a long standing bug with R-Type Leo, here are the commits for it
one rather long winded for MAME and a simplier deal in FBN......

https://github.com/mamedev/mame/commit/ba7824cd437a366139e76c6632c1fcde51468575
https://github.com/finalburnneo/FBNeo/commit/95e7070b539705a24cc66a660eeb04951acfdb11

So without rabbitin on as we have a similar kludge setup in our M92 driver i've went with the FBN style

Basically after the ready message at the begining of a level and everytime after you die the ship should change
colour flicker or blink slightly "depending on how you describe that "for short time so when playing you know 
your invincible for a few secs which comes in handy as you can use it to your advantage.

I've ran into a little issue in the sense that in my MAME core when in NTSC mode the blink effect doesn't really
show up as well than if i switch to PAL mode, however it's fine in both modes when i use my FBN xbox port.
it's likely an issue with any combination of emu + TV + xbox video settings.

There is the outside chance it might be related to our m92 driver settings for the vblank period and screen
refresh rate but since ours are the same as in current MAME more or less it's as i said likely the setup on my
end.

Could you test out a small change im gonna make in m92 video to basically force R-type Leo to disable the
pallette bank just to make sure we're getting the desired effects thanks.

EDIT::  Actually as per this video that's how it looks on my TV so likely it's dependent on whatever set up
you happen to have as to how much the ship will blink/flicker rather than a core or code issue.....

https://www.youtube.com/watch?v=LMC8YW0KBfQ

**Comment by mahoneyt944** [comment]
I'll just merge and test. Easy to revert if need be.

**Comment by mahoneyt944** [comment]
Seems to work ok in both versions. Unrelated, I notice playing the J version that when I die, it does more of a level reset. You hear "3, 2, 1 let's go" again. In the regular version it just respawns where you died. Is this a bug? Or a setting or something?

**Comment by arcadez2003** [comment]
Likely just how the game is setup.?? Japan versions of these type games tend to favour checkpoints where as
the world or USA versions tend to just restart where you died.

**Comment by arcadez2003** [comment]
Unrelated matter but there is this commit.........

0.99u3: Pierpaolo Prazzoli removed a speedup kludge in the M92 video driver. This fixes R-Type Leo video.

It came after a huge video rewrite so maybe we're unaffected with the older code.?? anyhow i should do a full
playtest sometime to see if there are graphical problems caused by the speedup and ifso how bad they are
but ideally we'd like to keep it active for performance reasons.........

/* This is a kludgey speedup that I consider to be pretty ugly..  But -
it gets a massive speed increase (~40fps -> ~65fps).  It works by avoiding
the need to dirty the top playfield twice a frame */

Not being a huge fan of side scrolling shmups believe it or not i've never played any of the R-Type games from
start to finish i guess this gives me an excuse to finish one of them at least.

**Comment by KMFDManic** [comment]
R-Type games have always been some of my favorites to play.  Thanks for this fix up:)  SHMUPS are a pretty niche genre, much like horror.  Just need the right game or movie to get someone into them.  Just don't play Silver Surfer for NES as your shmup example, haha:) Sturmwind for Dreamcast or Last Hope: Pink Bullets, for Neo Geo on 2003, are both fun ones.

**Comment by arcadez2003** [comment]
Actually there is more going on here there is a colour cycling effect red and blue basically which mix together so that
certain enemy attacks are one or the other but mostly combined to give as i said blue/red hue to bullets lasers etc etc
this is also noticeable for example the laser grid on level one or those two satellite looking devices which try and trap
you on level two and again those enemies that explode into loads of wee circles to try and block your path on level 5
and many other sections all through the game.

These effects are broken due to the speedhack!!

@mahoneyt944 by disabling that gfx speedhack we fix all the above plus the invincibility flashing seems to work better
and i noticed no real performance drops certainly on my xbox which can be prone to that right enough by doin so

so you wanna disable that speedhack for this core.?? certainly we could always add it back in with an option to toggle
it on or off and explain the pro's and con's of doin so should many users report a significant performance drop in
the proccess although i dont really expect they'll notice.

**Comment by mahoneyt944** [comment]
We can disable it, should be easy enough to revert if need be.

**Comment by arcadez2003** [comment]
Alright done might as well close this down once again
