### ISSUE TITLE
Support Neo-Geo "Hypernoid" Homebrew

### ISSUE THREAD

**Issue by KMFDManic** [libretro/mame2003-plus-libretro#1330]
@arcadez2003 @mahoneyt944 

A friend brought this to my attention a few days ago.  This one completely escaped me.  But, I gave it a try and it is a "6+ year developed" homebrew "break-out/arkanoid" style game, with some nice gameplay, and a rocking soundtrack!

It was added to FBNeo here:

https://github.com/libretro/FBNeo/commit/2e8466b3add12f22e5bc679e682bacb87f3d1d45

Here is a video demonstration trailer:

https://www.youtube.com/watch?v=vU1d43Gg_KI

Temp Link to the test file.  

https://drive.google.com/drive/folders/14z1PPRhoC36oQGaoBQrSzKdY0kesKrC7

P.S.:  I will revise some Cheats and do another Pull Request, likely tomorrow:)  But, give this game a shot, and let me know what you two think!  I feel it is a worthy addition!

**Comment by mahoneyt944** [comment]
We could probably support that without too much trouble.

**Comment by arcadez2003** [comment]
Im only focused on the super rare just now...

I have this one up and running some input niggles i need to look at though but it's 99% there

https://www.youtube.com/watch?v=aDSbLEIIUlE

And well there is the small matter of this one.....

https://www.youtube.com/watch?v=OapUeEAWrho

**Comment by KMFDManic** [comment]
@arcadez2003 Both look great.  Marble Madness has always been one of my absolute favorite games.  I would always keep going back to it to try to do "just" a little better.  Seems like 2 is a worthy one worth delving into.  Gotta wonder how many other prototypes are out there that we are unaware of.  Many of them "very briefly" showed up in magazines over the years.  But, then just disappeared til they resurfaced decades later!

**Comment by markwkidd** [comment]
Marble Madness is one of the games, like Moonwalker, that stuck in my
imagination as a youngster I think because of the soundtrack. MM has better
gameplay, and I have to admit I'm looking forward to trying it soon.

**Comment by mikehyrus** [comment]
There are other super rare titles that exist like Sigma’s Akuzukin which is not yet dumped.

**Comment by KMFDManic** [comment]
@markwkidd Like the Moonwalker with MAME 2003, and CD Soundtrack "Real Songs", you can now also do the same thing with Sega Genesis/MegaDrive version, having the "Real Songs"...

https://www.youtube.com/watch?v=4FxKOJPRgXQ&t=311s

If you wanna try this one out, or need ANY help running it, just let me know:)

**Comment by arcadez2003** [comment]
@mahoneyt944 @markwkidd @KMFDManic Any of ya's fancy taking a wee stab at fixing the inputs for Megumi Rescue
it hooks up via the inputs for the Riddle Of Pythagaros but for some reason it's only playable in single player mode.

I've tweaked the analog hookup a little to get player 2 inputs working somewhat via player 1 but that's obviously not
correct as you'd still have to press start on the player 2 side, TBH analog inputs are not my strong point and i dont wanna
bug FBN dev with this as they're busy with other things so i thought it worth sharing my WIP on here and hopefully
one of ya's can nail it.

BTW i had to add a rather untidy hack to fix the video as the game did not like our segae video update call, not ideal
but since we changed that when supporting the Mega Play games i thought it best to leave it be and have a seperate
video call for this game i plan to put this right down the road after i've had time to test the Mega Play games with
this gfx diff.

[stuff.zip](https://github.com/libretro/mame2003-plus-libretro/files/8766441/stuff.zip)

**Comment by KMFDManic** [comment]
@arcadez2003 I assume you've already seen this commit?

https://github.com/finalburnneo/FBNeo/commit/35462728e15c9f0329f5c3de6a495649d316d7f7

**Comment by arcadez2003** [comment]
Aye but if you compare our driver with that one you'll see it's chalk n cheese :)

**Comment by KMFDManic** [comment]
Haha, duly noted:)

**Comment by arcadez2003** [comment]
Back on topic it'll be easier to take it from here.......

https://github.com/Robbbert/hbmame/commit/eb8ea1fb87fea4dffac6b38b56035bf5d562e9a0

I'll take a run at it later on if someone else doesn't beat me to it

**Comment by arcadez2003** [comment]
Hmm this should be good i think

// 447 : Hypernoid by M.Priewe.
ROM_START( hypernoid )
	ROM_REGION( 0x100000, REGION_CPU1, 0 )
	ROM_LOAD16_WORD_SWAP( "447.p1", 0x000000, 0x100000, CRC(e024fa76) SHA1(6ef393ad80ec80e30929f07c95305d97fca3ad22) )

	NEO_SFIX_128K( "447.s1", CRC(bb82ab71) SHA1(307f420446c2d411a65b59543b61c21d0360536b) )

	NEO_BIOS_SOUND_512K( "447.m1", CRC(6c8eaacc) SHA1(6bc065be18db6830a4c94b424f9380d38da6f8b7) )

	ROM_REGION( 0x1000000, REGION_SOUND1, ROMREGION_SOUNDONLY )
	ROM_LOAD( "447.v1", 0x000000, 0x400000, CRC(dafa1bdd) SHA1(743a5ad24a3dba04ce8f3e2d95ebd5ca83fd9f98) )
	ROM_LOAD( "447.v2", 0x400000, 0x400000, CRC(85ad8283) SHA1(8abcf48a353dcd4777608b13471608f7290d89a5) )
	ROM_LOAD( "447.v3", 0x800000, 0x400000, CRC(86c27f0c) SHA1(85b740e0224d5ea09b600683dec6fe532a723355) )
	ROM_LOAD( "447.v4", 0xc00000, 0x400000, CRC(a3982244) SHA1(7191909d7264df3dc417dc76cee53291986d84e9) )

	NO_DELTAT_REGION

	ROM_REGION( 0x400000, REGION_GFX3, 0 )
	ROM_LOAD16_BYTE( "447.c1", 0x000000, 0x200000, CRC(41d6140a) SHA1(862b95ca1fe2b75d7ead0de8ac50c1b8a049c774) )
	ROM_LOAD16_BYTE( "447.c2", 0x000001, 0x200000, CRC(36f35df2) SHA1(22715561d5383263e41563fcb060f83a0c544531) )
ROM_END

And

GAMEB( 2021, hypernoid, neogeo,  neogeo, neogeo, neogeo,  neogeo,   ROT0, "M.Priewe", "Hypernoid (2021-11-28)", &neogeo_ctrl, NULL )

**Comment by KMFDManic** [comment]
@arcadez2003 Awesome:)  Hopefully, we can be all good on Marble Madness 2, soon, as well!  I did a change to fix just detecting the rom set you specified for Turbo OutRun on my Repo.  The only oddity, it seems .dat files can be a little finicky in being read in commits, as you can clearly see lines 130763-13769 do not show in the commit, yet exist in the .dat file.  I tested this perimeter by adjusting the .dat file a few more times, and it seems to be equally goofy in how it detects the changes.  Maybe an odd bug?  Viewing the actual .dat file, however, everything is fine!  If my commit is fine for you, I can pull it to Plus to at least account for THAT rom set.  For some reason my toutrun3.zip may not be the proper one, even with the "decrypted" roms, as it fails to load for me.  So, I can't verify, for sure, the "SAME" codes work.  

https://github.com/KMFDManic/mame2003-xtreme/commit/6912494563573bc1bc49a07923ed11eeff76bccd

Double Dragon II cheat wise, I tested them all.  Unfortunately, they are best left not added, for now.  The character select ones cause "last battle" exploding bodies like glitches.  Level select black screens (I read the warnings in the cheats, but still have issues there).  The "no flickering" just slows the game down to a crawl.  Game, by default, actually seems to run alright with 2003 Plus/Xtreme, currently!  I didn't notice any annoying issues, at least in the playtime I gave to it!

Thanks for Hypernoid, and let me know what you think of the odd way the "cheat.dat" commit on my Repo didn't display those lines?

In any case, I will keep playing around with more additions, as some Cheats do definitively help improve performance and speed, via hacks, like the Killer Instinct ones!  Bound to be quite a few more to get introduced!

**Comment by mahoneyt944** [comment]
@arcadez2003
I added hypernoid with the rom loading you provided. The game boots and plays, only played it for a second though.

@KMFDManic 
Feel free to PR any cheat.dat fixes, just be sure to test any cheats you want to submit or fix so we aren't adding non-working cheats. GitHub sometimes displays oddly for large files like this so don't be overly concerned.

I actually wrote a code for umk3p to auto enter the UKK data for you to unlock chameleon, super subzero, and triborg. I wasn't planning on releasing it but the creator of the hack released a video showing you the combinations for each character anyhow. So I may add it in, though I wanted to read though the cheat engine a bit more and utilize some of the delay pokes so the code is easier to use.

**Comment by mahoneyt944** [comment]
@KMFDManic i would assume hypernoid is meant to be played with a dial, but it seems we have it tied to a joystick?

**Comment by mahoneyt944** [comment]
@arcadez2003 
It looks like you missed the e2 port, which is throwing off the ports which follow (the dials). 

```
	PORT_START("e1")    /* Read from Port 0xe1 */
	//PORT_BIT( 0x01, IP_ACTIVE_LOW,  IPT_UNUSED )
	//PORT_BIT( 0x02, IP_ACTIVE_LOW,  IPT_UNUSED )
	//PORT_BIT( 0x04, IP_ACTIVE_LOW,  IPT_UNUSED )
	//PORT_BIT( 0x08, IP_ACTIVE_LOW,  IPT_UNUSED )
	//PORT_BIT( 0x10, IP_ACTIVE_LOW,  IPT_UNUSED )
	//PORT_BIT( 0x20, IP_ACTIVE_LOW,  IPT_UNUSED )
	//PORT_BIT( 0x40, IP_ACTIVE_LOW,  IPT_UNUSED )
	//PORT_BIT( 0x80, IP_ACTIVE_LOW,  IPT_UNUSED )

	PORT_START("e2")    /* Read from Port 0xe2 */
	//PORT_BIT( 0x01, IP_ACTIVE_LOW,  IPT_UNUSED )
	//PORT_BIT( 0x02, IP_ACTIVE_LOW,  IPT_UNUSED )
	//PORT_BIT( 0x04, IP_ACTIVE_LOW,  IPT_UNUSED )
	//PORT_BIT( 0x08, IP_ACTIVE_LOW,  IPT_UNUSED )
	//PORT_BIT( 0x10, IP_ACTIVE_LOW,  IPT_UNUSED )
	//PORT_BIT( 0x20, IP_ACTIVE_LOW,  IPT_UNUSED )
	//PORT_BIT( 0x40, IP_ACTIVE_LOW,  IPT_UNUSED )
	//PORT_BIT( 0x80, IP_ACTIVE_LOW,  IPT_UNUSED )
```

**Comment by MistyDreams** [comment]
works fine here

```
src/drivers/neogeo.c: In function ‘mv0_bankswitch_r’:
src/drivers/neogeo.c:7504:53: warning: array subscript 2 is above array bounds of ‘UINT16[2]’ {aka ‘short unsigned int[2]’} [-Warray-bounds]
 7504 |                         return mv0_bankswitch_offset[ offset ];
      |                                ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
src/drivers/neogeo.c:7452:15: note: while referencing ‘mv0_bankswitch_offset’
 7452 | static UINT16 mv0_bankswitch_offset[ 2 ];
      |               ^~~~~~~~~~~~~~~~~~~~~
src/drivers/neogeo.c:7494:53: warning: array subscript 2 is above array bounds of ‘UINT16[2]’ {aka ‘short unsigned int[2]’} [-Warray-bounds]
 7494 |                         return mv0_bankswitch_offset[ offset ];
      |                                ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
src/drivers/neogeo.c:7452:15: note: while referencing ‘mv0_bankswitch_offset’
 7452 | static UINT16 mv0_bankswitch_offset[ 2 ];
```

change ``` 7452 | static UINT16 mv0_bankswitch_offset[ 2 ];  ``` too 
 ```static UINT16 mv0_bankswitch_offset[ 3 ];``` thats probably your issue on your system

**Comment by arcadez2003** [comment]
Right silly me i think the controls are fine as the game defaults to upright so you share the same stick more or less
but in cocktail mode that would switch to a different stick for player two, i think the some of the dips are wrong as
the lives dont change when you alternate  from say 2 to 4 so maybe cocktail mode is broken also hence the
problems.

I just copied Riddle Of Pytharos inputs and pasted in the changes so i'll need to look at this again what a bummer.

**Comment by arcadez2003** [comment]
> @arcadez2003 kickass:) I also noticed the marble madness 2 was done on hbmame, which might enlighten us a little more for that game, as well. As always, 2003 Plus staying exciting:)

HB uses the same codebase more or less little in that driver is of use to us due to differences not only to how that is coded
but also the wider Atari code it hooks up with, our only chance that i can see is to try and hookup mm2 to our older batman
driver it wont be easy but we'll give it a try at least :)

**Comment by KMFDManic** [comment]
@arcadez2003 yeah, I did look at the coding and after a minute, I was like..."wait, what", better run this by arcadez2003:) 2003 Plus For Life, even if we have to duct tape it to Batman, hehe.  I will get some more cheats fixed up, now that we are on the same page with the weird display issue for larger files:)

**Comment by KMFDManic** [comment]
Thanks @arcadez2003 @mahoneyt944 and @MistyDreams :)  Feel free to close this issue anytime, now!  We can open another one or respond to this one, if Hypernoid needs any adjustments!  Thanks, as always!  Hopefully, we can sort Marble Madness 2, as well!  But, these 2 latest additions are more than enough for now!!!
