### ISSUE TITLE
Wrestle war sprite bug. / System16 improvements 

### ISSUE THREAD

**Issue by mahoneyt944** [libretro/mame2003-plus-libretro#1360]
- If you watch the attract screen or play through some rounds, you'll see the sprites slide out and bounce back. Like a clipping issue. This seems happen when the ring viewpoint should rotate, but instead glitches for a moment.
- "welcome to wrestle war" banner at start of round is blacked out. Glitched sprite.

**Comment by mahoneyt944** [comment]
Also has bad ram test.
![wrestwar-220603-103520](https://user-images.githubusercontent.com/49591133/171875778-e049ba1d-6033-4cde-bf82-bdb8f6ee2b77.png)

**Comment by arcadez2003** [comment]
It might be worth trying out Tough turf with the new sprite code also as it has some issues with the character and enemy
sprites movements which if we're lucky will be sorted fingers crossed.

**Comment by arcadez2003** [comment]
> * If you watch the attract screen or play through some rounds, you'll see the sprites slide out and bounce back. Like a clipping issue.
> 
>     * There's also an issue with the ring view, it should twist while playing
> 
>     * "welcome to wrestle war" banner at start of round is blacked out. Glitched sprite.

These were all fixed as per the big Sega update, i think it's to do with some sort of flipping or rotate effect SDI has it as do some other baseball games which are not playable in our ole driver.

**Comment by mahoneyt944** [comment]
No luck with tturf. Just tried.

**Comment by mahoneyt944** [comment]
That rotation though is definitely what's missing, any idea when that was added to mame?

**Comment by arcadez2003** [comment]
> That rotation though is definitely what's missing, any idea when that was added to mame?

the sega rewrite started MAME version  88.u6 so anytime around then or after.

**Comment by arcadez2003** [comment]
0.167: David Haywood Make screen flipping actually work in the System16 driver (it hasn't since the driver was rewritten). This makes 'SDI - Strategic Defense Initiative' playable again (level 2 onwards had no sprites and completely broken backgrounds) .

It seems from reading the above that this likely is related to the conversion from system16.c to segas16a.c and segas16b.c
the flip or rotation support will be present in our driver but maybe there are some mistakes in either the code or how 
it's hooked to Wrestle War.

It might be worth checking the SDI video handling to see if anything setup for that game will help with Wrestle War.

**Comment by mahoneyt944** [comment]
wrestwar has some similarities with fantzn2x and hwchamp. But that's just guess work based on some of the code we have now. After all, that's why I picked wrestwar for fantzn2x in the first place. Now that we got that game working about as good as it can be. I wonder if some of those differences in the hookup would work on the latter too.

**Comment by MistyDreams** [comment]
you done need extraram if your using the tilemap_w depends how your setting bank0 and 1

**Comment by mahoneyt944** [comment]
It seems like using extraram[0] and extraram[1] for bank0 and bank1 means less specific code in the init function, at least for wrestwar. This would be ideal to trim the fat from each game and gear towards more common structures shared between most games in the driver. This was part of the reason why I removed about 400 lines of duplicate code while adding in the fantzn2x fix. Trying to achieve as much common ground as possible and remove clutter.

**Comment by MistyDreams** [comment]
working on generic inputs at wanting to test some system16b games that are decrypted see how we get on started with cotton having strange issues but its early days only done the memory map need to sort the inputs out and figure out why the video aint firing at first read

**Comment by mahoneyt944** [comment]
Do we have the same issue in sdi as noted here?
https://github.com/mamedev/mame/commit/1e61bf70fbedcc20e57504d85f2381ce251df323

**Comment by MistyDreams** [comment]
never played that game use spr offset if its bad I think

**Comment by mahoneyt944** [comment]
It says level 2 has no sprites, testing our core we have sprites. So seems ok. If this is linked to wrestwar in anyway we should be ok if it's hooked right.

**Comment by MistyDreams** [comment]
whats the issue with wrestwar ?

**Comment by mahoneyt944** [comment]
Updated the original post with these details. Also found this, https://github.com/mamedev/mame/commit/2782c92d8e7e575e89e4ebc0a6de4ed810bfb90d

**Comment by MistyDreams** [comment]
> Updated the original post with these details. Also found this, [mamedev/mame@2782c92](https://github.com/mamedev/mame/commit/2782c92d8e7e575e89e4ebc0a6de4ed810bfb90d)

I didnt think any encrypted sets where being used ?

**Comment by mahoneyt944** [comment]
The old sim code might be usable if we don't already have something.

**Comment by MistyDreams** [comment]
all sets are decrypted anyways cottons not booting though. Checked wrestwar against the latest mame the sprites are loaded completely different. Will be a rabbit hole changing things.

**Comment by mahoneyt944** [comment]
Looking at other mem maps that replace extra ram with sys16_tilebank_w, they all seem to drop the read here. Must be write only.

**Comment by arcadez2003** [comment]
> all sets are decrypted anyways cottons not booting though. Checked wrestwar against the latest mame the sprites are loaded completely different. Will be a rabbit hole changing things.

I have cotton up and running the tiles are fine some issues with certain sprites and no sound currently i can send my current
WIP if you want.??

The only game it's remotely close to is Aurail im using the gfx hookup for that game currently and rejiged the GFX2 sprite rom boot order to match Aurail's

**Comment by mahoneyt944** [comment]
Think I'm onto this issue with wrestwar. Using Libretro-mame2000, this game rotates properly. shortly after this time it was broken, as part of the overhaul.

If you look at mame2000, wrestwar was using an extraram2 hook up in the mem maps and the inits are slightly different. wrestwar_update_proc  sets the tilebank with extraram[2] and the inits sets its own bank.

We should be able to configure ours to work here again with some luck.

**Comment by arcadez2003** [comment]
> Think I'm onto this issue with wrestwar. Using Libretro-mame2000, this game rotates properly. shortly after this time it was broken, as part of the overhaul.
> 
> Being that we also have glitchy sprites probably the tilebanks.
> 
> We should be able to configure ours to work here again with some luck.

Good spot i guess the rewrite he mentioned happened far sooner

**Comment by mahoneyt944** [comment]
Seems like it's been ongoing since the 2000s. Crazy, but it just might help us here.

**Comment by arcadez2003** [comment]
Ok fixed the sound in Cotton well got it to function at any rate as per work i did on my xbox core the UPD7759 sound
will need to be updated to totally fix the sound but that will be a breeze, to keep this on topic i'll start another issue
for Cotton.

It's close now if someone can fix the issue with some of the sprites being distorted then this will be more or less playable

**Comment by MistyDreams** [comment]
> I have cotton up and running the tiles are fine some issues with certain sprites and no sound currently i can send my current
> WIP if you want.??

sure id like to see where its going wrong. I dont thing the wrong gfx would crash it but could be wrong . I know my gfx loading is completely wrong for this core

**Comment by mahoneyt944** [comment]
Logerror is supposed to be phased out for libretro logging. There's still plenty of it lurking around the code though.

**Comment by MistyDreams** [comment]
just the wrapper needs fixing is going through libretro logging see mame2003/log.h not a big deal just in case your debugging and come across issues

**Comment by arcadez2003** [comment]
> > I have cotton up and running the tiles are fine some issues with certain sprites and no sound currently i can send my current
> > WIP if you want.??
> 
> @arcadez2003 sure id like to see where its going wrong. I dont thing the wrong gfx would crash it but could be wrong . I know my gfx loading is completely wrong for this core. Im p[retty sure its interrupt related. Im looking for a way to map unmapped memory in this core is it possible in real time ?
> 
> @mahoneyt944 there is an issue with logerror(it doesnt print numbers correctly wasted a bit of time yesterday before using libretro log functions %d %u and %02x ect

Here ya go https://github.com/libretro/mame2003-plus-libretro/issues/1362
