### ISSUE TITLE
Tturf, tturfu, tturfbl sprite issue.

### ISSUE THREAD

**Issue by mahoneyt944** [libretro/mame2003-plus-libretro#1366]
Sprite issue while moving, works in mame2000

https://github.com/libretro/mame2003-plus-libretro/blob/5eeba98b34311645e24a56feb628467f25491b59/src/drivers/system16.c#L28
![tturf-220606-203250](https://user-images.githubusercontent.com/49591133/172275861-c4b60960-0a25-46da-b66c-d5e84423a493.png)

**Comment by MistyDreams** [comment]
seems like this could be related to the gub in fantzn2x when you start any luck with adding the gfx viewer in this core its not mapped in the general inputs and if you do map it strange voodoo happens when you use it.

**Comment by mahoneyt944** [comment]
Well it does start to load, but I'm guessing there's some snippets disabled in the code or an overflow somewhere.
Mame2003-plus
![Screenshot_20220606-235051_1](https://user-images.githubusercontent.com/49591133/172292642-0ac392f8-4f38-4720-9b6e-e410af666c4f.png)

Mame2000
![tturf-220606-235333](https://user-images.githubusercontent.com/49591133/172292685-b49836be-ed50-4e92-991e-3c1c518a54a1.png)

**Comment by mahoneyt944** [comment]
Mame2000 disables osd sound before it loads the map, worth testing.
https://github.com/libretro/mame2003-plus-libretro/compare/Showgfx

**Comment by MistyDreams** [comment]
ill compile the original mame if i have too, it will be less work in the long run dont worry if you cant fix it. Not something I want to waste time on

**Comment by mahoneyt944** [comment]
It's likely something in `static void showcharset` I'll see if I can find it.

**Comment by mahoneyt944** [comment]
Also added the sound dump in for tturf. Getting most of the sounds now but still have some issues.....cross comparing to tturfu where the sound is much better. Maybe a write handler issue or activecpu_get_pc value?

**Comment by arcadez2003** [comment]
Im gonna look at this later i noticed the GFX2 roms are loaded in the same boot order as Torymon so im on spec gonna
hook it off that game to see what happens :)

**Comment by arcadez2003** [comment]
The boot order for the sprite roms is this.......

	ROM_REGION( 0x80000, REGION_GFX2, 0 ) /* sprites */
	ROM_LOAD16_BYTE( "12279.1b", 0x00001, 0x10000, CRC(7a169fb1) SHA1(1ec6da0d2cfcf727e61f61c847fd8b975b64f944) )
	ROM_LOAD16_BYTE( "12283.5b", 0x00000, 0x10000, CRC(ae0fa085) SHA1(ae9af92d4dd0c8a0f064d24e647522b588fbd7f7) )
	ROM_LOAD16_BYTE( "12278.2b", 0x20001, 0x10000, CRC(961d06b7) SHA1(b1a9dea63785bfa2c0e7b931387b91dfcd27d79b) )
	ROM_LOAD16_BYTE( "12282.6b", 0x20000, 0x10000, CRC(e8671ee1) SHA1(a3732938c370f1936d867aae9c3d1e9bbfb57ede) )
	ROM_LOAD16_BYTE( "12277.3b", 0x40001, 0x10000, CRC(f16b6ba2) SHA1(00cc04c7b5aad82d51d2d252e1e57bcdc5e2c9e3) )
	ROM_LOAD16_BYTE( "12281.7b", 0x40000, 0x10000, CRC(1ef1077f) SHA1(8ce6fd7d32a20b93b3f91aaa43fe22720da7236f) )
	ROM_LOAD16_BYTE( "12276.4b", 0x60001, 0x10000, CRC(838bd71f) SHA1(82d9d127438f5e1906b1cf40bf3b4727f2ee5685) )
	ROM_LOAD16_BYTE( "12280.8b", 0x60000, 0x10000, CRC(639a57cb) SHA1(84fd8b96758d38f9e1ba1a3c2cf8099ec0452784) )


After the big Sega core update with the new gfx handling the roms boot in this order........

	ROM_REGION16_BE( 0x100000, REGION_GFX2, 0 ) /* sprites */
	ROM_LOAD16_BYTE( "12279.1b", 0x00001, 0x10000, CRC(7a169fb1) SHA1(1ec6da0d2cfcf727e61f61c847fd8b975b64f944) )
	ROM_LOAD16_BYTE( "12283.5b", 0x00000, 0x10000, CRC(ae0fa085) SHA1(ae9af92d4dd0c8a0f064d24e647522b588fbd7f7) )
	ROM_LOAD16_BYTE( "12278.2b", 0x40001, 0x10000, CRC(961d06b7) SHA1(b1a9dea63785bfa2c0e7b931387b91dfcd27d79b) )
	ROM_LOAD16_BYTE( "12282.6b", 0x40000, 0x10000, CRC(e8671ee1) SHA1(a3732938c370f1936d867aae9c3d1e9bbfb57ede) )
	ROM_LOAD16_BYTE( "12277.3b", 0x80001, 0x10000, CRC(f16b6ba2) SHA1(00cc04c7b5aad82d51d2d252e1e57bcdc5e2c9e3) )
	ROM_LOAD16_BYTE( "12281.7b", 0x80000, 0x10000, CRC(1ef1077f) SHA1(8ce6fd7d32a20b93b3f91aaa43fe22720da7236f) )
	ROM_LOAD16_BYTE( "12276.4b", 0xc0001, 0x10000, CRC(838bd71f) SHA1(82d9d127438f5e1906b1cf40bf3b4727f2ee5685) )
	ROM_LOAD16_BYTE( "12280.8b", 0xc0000, 0x10000, CRC(639a57cb) SHA1(84fd8b96758d38f9e1ba1a3c2cf8099ec0452784) )

I suppose if as @mahoneyt944 suggests the game is fine in MAME2000 it might be worth looking at how the GFX2 roms
and the graphics are hooked up but the Sega games have had many gfx updates over the years so likely what was good
in 2000 wont be the same for 2003.

**Comment by mahoneyt944** [comment]
Fixed the sound for tturf. Tturfu uses different loading though not sure why.

**Comment by arcadez2003** [comment]
Yeah i seen that good spot

**Comment by mahoneyt944** [comment]
The new sound loading doesn't seem to work for tturfu. Probably something to do with the write handler or sound write

**Comment by arcadez2003** [comment]
Well same deal as before you can either fix the character sprites but that breaks the enemy sprites and vice versa
i've had a few goes at this now and have to admit defeat, there is obviously a setting in the wider video and sprite
code which this game does not like.

Alotta video changes over the years before 2003 any one of them could have broken this game while at the same time
fixing a far more popular one it's the way it goes.

**Comment by mahoneyt944** [comment]
> i've had a few goes at this now over the years and have to admit defeat

Maybe sound needs a turn lol 😄. I think tturf sound is correct now. Everything works. However.... on tturfu it mostly works, some of the sounds pops or cuts out, I believe this to be in the difference in rom loading using 0x50000 for the region and such as newer mame does but can't get this to work properly for tturfu which is odd because it works for tturf. Maybe there's something else needed to change for this loading to work.?

**Comment by arcadez2003** [comment]
Well if you notice that fix was just for tturf i assume if it had worked for tturfu then they would used it for that game also.??
i suppose being it's the parent version you've fixed at least outta the two that's the verion most players will use shame
about the sprites though but hey you could try this at least............

	ROM_REGION( 0x30000, REGION_CPU2, 0 ) /* sound CPU */
	ROM_LOAD( "epr12271.bin", 0x00000,  0x8000, CRC(99671e52) SHA1(ab21b7e7a449c8081b5db1fdb579071e31b6852c) )
	ROM_LOAD( "epr12272.bin", 0x10000, 0x8000, CRC(7cf7e69f) SHA1(62c9f75db8e2b4ece517167ba5c0712bac5f1d95) )
	ROM_LOAD( "epr12273.bin", 0x18000, 0x8000, CRC(28f0bb8b) SHA1(d99aff57d213b10ac10c37ceff2f125875816488) )
	ROM_LOAD( "epr12274.bin", 0x20000, 0x8000, CRC(8207f0c4) SHA1(169914861a52fa731a305e1ee2d230aa0d0d97fe) )
        // note: it needs this hole otherwise voice samples won't playback
	ROM_LOAD( "epr12275.bin", 0x30000, 0x8000, CRC(182f3c3d) SHA1(1482fe08a05a721e315b1a3aa5bef4dddc72e26e) )

**Comment by arcadez2003** [comment]
Anyway if i had to guess it's the lack of the MCU and a simulation of some of it's sound commands is maybe why tturf
sound has always been broken, at least now we have full working sound and fixed speech in the Japan version

**Comment by MistyDreams** [comment]
interesting oddity in the video code banking code doesnt shift when you change it, Will have a better look at the weekend. I think fantzone could  be fixed up with banking adjustments will need to have a look.

**Comment by MistyDreams** [comment]
Done mean to come across as dismissive. Im working on the gfx side of things .  Youll need to check what sets your working with in  recent mame so you know what sound cpu roms your using

**Comment by mahoneyt944** [comment]
That's fine, arcadez and I took a swing at the gfx already with no luck. So I moved on to sound. Tturf is fixed now, but tturfu has a secret to unfold...it's close but no cigar as they say.

**Comment by mahoneyt944** [comment]
Though the newer sound loading fixes some sounds like speech and the pipe dropping on the ground but messes up others. Probably a way to configure it right. But idk.

**Comment by MistyDreams** [comment]
@mahoneyt944 youll get there in the end

@arcadez2003 here is the romloads for cotton with the wwe fix not perfect but better. I want to look at that sprite drawing code at the weekend

```
ROM_START( cottond )
	ROM_REGION( 0x100000, REGION_CPU1, 0 ) // 68000 code
	ROM_LOAD16_BYTE( "bootleg_epr-13921a.a7", 0x000000, 0x20000, CRC(92947867) SHA1(6d5f1be45690bacac7093b442ed99c4de56d73a4) )
	ROM_LOAD16_BYTE( "bootleg_epr-13919a.a5", 0x000001, 0x20000, CRC(30f131fb) SHA1(5b35b4691d2436e82be3079634d8f7f259e46450) )
	ROM_LOAD16_BYTE( "bootleg_epr-13922a.a8", 0x080000, 0x20000, CRC(f0f75329) SHA1(e223b3b6e15ead11f93e353ddce5227f8b362d2e) )
	ROM_LOAD16_BYTE( "bootleg_epr-13920a.a6", 0x080001, 0x20000, CRC(a3721aab) SHA1(bfcd8e564f06520e51c61418246ef06e4a0036d7) )

	ROM_REGION( 0xc0000, REGION_GFX1, 0 ) // tiles
	ROM_LOAD( "opr-13862.a14", 0x00000, 0x20000, CRC(a47354b6) SHA1(ce52813b245f1d491a134d4bd5ab074e71d20129) )
	ROM_LOAD( "opr-13877.b14", 0x20000, 0x20000, CRC(d38424b5) SHA1(884ca190936aee2d2cac86491d4d0cdf4a45efe5) )
	ROM_LOAD( "opr-13863.a15", 0x40000, 0x20000, CRC(8c990026) SHA1(07b4510936376c171f3b31d87ac6154361eb0cbc) )
	ROM_LOAD( "opr-13878.b15", 0x60000, 0x20000, CRC(21c15b8a) SHA1(690d92420ec5465885e0f4870419992961420e33) )
	ROM_LOAD( "opr-13864.a16", 0x80000, 0x20000, CRC(d2b175bf) SHA1(897b7c794d0e7229ea5e9a682f64266a947a818f) )
	ROM_LOAD( "opr-13879.b16", 0xa0000, 0x20000, CRC(b9d62531) SHA1(e8c5e7b93339c00f75a3b66ce18f7838255577be) )

	ROM_REGION( 0x400000, REGION_GFX2, 0 ) // sprites
	ROM_LOAD16_BYTE( "opr-13869.b5", 0x000000, 0x10000, CRC(ab4b3468) SHA1(3071654a295152d609d2c2c1d4153b5ba3f174d5) )
	ROM_CONTINUE( 0x040000, 0x10000 )
	ROM_RELOAD  ( 0x020000, 0x10000 )
	ROM_CONTINUE( 0x060000, 0x10000 )
	ROM_LOAD16_BYTE( "opr-13865.b1", 0x000001, 0x10000, CRC(7024f404) SHA1(4b2f9cdfdd97218797a3e386106e53f713b8650d) )
	ROM_CONTINUE( 0x040001, 0x10000 )
	ROM_RELOAD  ( 0x020001, 0x10000 )
	ROM_CONTINUE( 0x060001, 0x10000 )
	
	ROM_LOAD16_BYTE( "opr-13870.b6", 0x080000, 0x10000, CRC(69b41ac3) SHA1(4c5a85e5a5ca9f8260557d4e97eb091dd857d63a) )
	ROM_CONTINUE( 0x0c0000, 0x10000 )
	ROM_RELOAD  ( 0x0a0000, 0x10000 )
	ROM_CONTINUE( 0x0e0000, 0x10000 )
	ROM_LOAD16_BYTE( "opr-13866.b2", 0x080001, 0x10000, CRC(6169bba4) SHA1(a24a418ee7cd0c1109870a2e7a91e430671897ed) )
    ROM_CONTINUE( 0x0c0001, 0x10000 )
	ROM_RELOAD  ( 0x0a0001, 0x10000 )
	ROM_CONTINUE( 0x0e0001, 0x10000 )

	ROM_LOAD16_BYTE( "opr-13871.b7", 0x100000, 0x10000, CRC(0801cf02) SHA1(3007bbbce2f327f4700e78e2b8672f4482189cd7) )
	ROM_CONTINUE( 0x140000, 0x10000 )
	ROM_RELOAD  ( 0x120000, 0x10000 )
	ROM_CONTINUE( 0x160000, 0x10000 )
	ROM_LOAD16_BYTE( "opr-13867.b3", 0x100001, 0x10000, CRC(b014f02d) SHA1(46f5ed0b44cee03a6aec9ec57b506bb15bf35e47) )
    ROM_CONTINUE( 0x140001, 0x10001 )
	ROM_RELOAD  ( 0x120001, 0x10001 )
	ROM_CONTINUE( 0x160001, 0x10001 )
	
	ROM_LOAD16_BYTE( "opr-13872.b8", 0x180000, 0x10000, CRC(f066f315) SHA1(bbeb24daaded994240d0cdb5cec2e662b677cb75) )
	ROM_CONTINUE( 0x1c0000, 0x10000 )
	ROM_RELOAD  ( 0x1a0000, 0x10000 )
	ROM_CONTINUE( 0x1e0000, 0x10000 )
	ROM_LOAD16_BYTE( "opr-13868.b4", 0x180001, 0x10000, CRC(e62a7cd6) SHA1(1e6d06345f7b6cef2e887d9b9cd45e0155140c5e) )
    ROM_CONTINUE( 0x1c0001, 0x10000 )
	ROM_RELOAD  ( 0x1a0001, 0x10000 )
	ROM_CONTINUE( 0x1e0001, 0x10000 )
	
	ROM_LOAD16_BYTE( "opr-13873.b10",0x200000, 0x10000, CRC(1bd145f3) SHA1(4744ffe9fbda453785345b46eb61b56730048f42) )
	ROM_CONTINUE( 0x240000, 0x10000 )
	ROM_RELOAD  ( 0x220000, 0x10000 )
	ROM_CONTINUE( 0x260000, 0x10000 )
	ROM_LOAD16_BYTE( "opr-13852.a1", 0x200001, 0x10000, CRC(943aba8b) SHA1(d0dd1665a8d9495a92ae4e35d6b15b966e8d43cd) )
    ROM_CONTINUE( 0x240001, 0x10000 )
	ROM_RELOAD  ( 0x220001, 0x10000 )
	ROM_CONTINUE( 0x260001, 0x10000 )

	ROM_LOAD16_BYTE( "opr-13874.b11",0x280000, 0x10000, CRC(4fd59bff) SHA1(2b4630e49b60593d668fe34d8faf712ac6928c14) )
	ROM_CONTINUE( 0x2c0000, 0x10000 )
	ROM_RELOAD  ( 0x2a0000, 0x10000 )
	ROM_CONTINUE( 0x2e0000, 0x10000 )

	ROM_LOAD16_BYTE( "opr-13853.a2", 0x280001, 0x10000, CRC(7ea93200) SHA1(8e2d8cd48a12306772653f25bddc99ad0597a698) )
	ROM_CONTINUE( 0x2c0000, 0x10000 )
	ROM_RELOAD  ( 0x2a0000, 0x10000 )
	ROM_CONTINUE( 0x2e0000, 0x10000 )

	ROM_LOAD16_BYTE( "opr-13894.b12",0x300000, 0x10000, CRC(e3d0bee2) SHA1(503a78123ca9d6f3405972bca281dcdaba929c99) )
	ROM_CONTINUE( 0x340000, 0x10000 )
	ROM_RELOAD  ( 0x320000, 0x10000 )
	ROM_CONTINUE( 0x360000, 0x10000 )
	ROM_LOAD16_BYTE( "opr-13891.a3", 0x300001, 0x10000, CRC(c6b3c414) SHA1(0f0d936e77eb483be8865e8d968d78260e88ca99) )
	ROM_CONTINUE( 0x340001, 0x10000 )
	ROM_RELOAD  ( 0x320001, 0x10000 )
	ROM_CONTINUE( 0x360001, 0x10000 )

	ROM_LOAD16_BYTE( "opr-13876.b13",0x380000, 0x10000, CRC(1c5ffad8) SHA1(13e5886ceece564cc71ba7f43a26d2b1782ccfc8) )
	ROM_CONTINUE( 0x3c0000, 0x10000 )
	ROM_RELOAD  ( 0x3a0000, 0x10000 )
	ROM_CONTINUE( 0x3e0000, 0x10000 )
	ROM_LOAD16_BYTE( "opr-13855.a4", 0x380001, 0x10000, CRC(856f3ee2) SHA1(72346d887ff9738ebe93acb2e3f8cd80d494621e) )
    ROM_CONTINUE( 0x3c0001, 0x10000 )
	ROM_RELOAD  ( 0x3a0001, 0x10000 )
	ROM_CONTINUE( 0x3e0001, 0x10000 )
	
	ROM_REGION( 0x50000, REGION_CPU2, 0 ) // sound CPU
	ROM_LOAD( "epr-13892.a10", 0x00000, 0x08000, CRC(fdfbe6ad) SHA1(9ebb94889c0e96e6af9cdced084804ca98612d61) )
	ROM_LOAD( "opr-13893.a11", 0x10000, 0x20000, CRC(384233df) SHA1(dfdf94697587a5ee45e97700f3741be54b90742b) )

//	ROM_REGION( 0x0100, "plds", 0 )
//	ROM_LOAD( "315-5298.b9",  0x0000, 0x00eb, CRC(39b47212) SHA1(432b47aee5ecbf08a8a6dc2f8379c816feb86328) ) // PLS153

ROM_END
```

**Comment by arcadez2003** [comment]
> Though the newer sound loading fixes some sounds like speech and the pipe dropping on the ground for tturfu but messes up others. Probably a way to configure it right. But idk.

Have you tried looking at hooking up the MCU for tturfu.?? as from what i understand that controls some aspects of the 
sound command structure 

> @mahoneyt944 youll get there in the end
> 
> @arcadez2003 here is the romloads for cotton with the wwe fix not perfect but better. I want to look at that sprite drawing code at the weekend
> 
> ```
> ROM_START( cottond )
> 	ROM_REGION( 0x100000, REGION_CPU1, 0 ) // 68000 code
> 	ROM_LOAD16_BYTE( "bootleg_epr-13921a.a7", 0x000000, 0x20000, CRC(92947867) SHA1(6d5f1be45690bacac7093b442ed99c4de56d73a4) )
> 	ROM_LOAD16_BYTE( "bootleg_epr-13919a.a5", 0x000001, 0x20000, CRC(30f131fb) SHA1(5b35b4691d2436e82be3079634d8f7f259e46450) )
> 	ROM_LOAD16_BYTE( "bootleg_epr-13922a.a8", 0x080000, 0x20000, CRC(f0f75329) SHA1(e223b3b6e15ead11f93e353ddce5227f8b362d2e) )
> 	ROM_LOAD16_BYTE( "bootleg_epr-13920a.a6", 0x080001, 0x20000, CRC(a3721aab) SHA1(bfcd8e564f06520e51c61418246ef06e4a0036d7) )
> 
> 	ROM_REGION( 0xc0000, REGION_GFX1, 0 ) // tiles
> 	ROM_LOAD( "opr-13862.a14", 0x00000, 0x20000, CRC(a47354b6) SHA1(ce52813b245f1d491a134d4bd5ab074e71d20129) )
> 	ROM_LOAD( "opr-13877.b14", 0x20000, 0x20000, CRC(d38424b5) SHA1(884ca190936aee2d2cac86491d4d0cdf4a45efe5) )
> 	ROM_LOAD( "opr-13863.a15", 0x40000, 0x20000, CRC(8c990026) SHA1(07b4510936376c171f3b31d87ac6154361eb0cbc) )
> 	ROM_LOAD( "opr-13878.b15", 0x60000, 0x20000, CRC(21c15b8a) SHA1(690d92420ec5465885e0f4870419992961420e33) )
> 	ROM_LOAD( "opr-13864.a16", 0x80000, 0x20000, CRC(d2b175bf) SHA1(897b7c794d0e7229ea5e9a682f64266a947a818f) )
> 	ROM_LOAD( "opr-13879.b16", 0xa0000, 0x20000, CRC(b9d62531) SHA1(e8c5e7b93339c00f75a3b66ce18f7838255577be) )
> 
> 	ROM_REGION( 0x400000, REGION_GFX2, 0 ) // sprites
> 	ROM_LOAD16_BYTE( "opr-13869.b5", 0x000000, 0x10000, CRC(ab4b3468) SHA1(3071654a295152d609d2c2c1d4153b5ba3f174d5) )
> 	ROM_CONTINUE( 0x040000, 0x10000 )
> 	ROM_RELOAD  ( 0x020000, 0x10000 )
> 	ROM_CONTINUE( 0x060000, 0x10000 )
> 	ROM_LOAD16_BYTE( "opr-13865.b1", 0x000001, 0x10000, CRC(7024f404) SHA1(4b2f9cdfdd97218797a3e386106e53f713b8650d) )
> 	ROM_CONTINUE( 0x040001, 0x10000 )
> 	ROM_RELOAD  ( 0x020001, 0x10000 )
> 	ROM_CONTINUE( 0x060001, 0x10000 )
> 	
> 	ROM_LOAD16_BYTE( "opr-13870.b6", 0x080000, 0x10000, CRC(69b41ac3) SHA1(4c5a85e5a5ca9f8260557d4e97eb091dd857d63a) )
> 	ROM_CONTINUE( 0x0c0000, 0x10000 )
> 	ROM_RELOAD  ( 0x0a0000, 0x10000 )
> 	ROM_CONTINUE( 0x0e0000, 0x10000 )
> 	ROM_LOAD16_BYTE( "opr-13866.b2", 0x080001, 0x10000, CRC(6169bba4) SHA1(a24a418ee7cd0c1109870a2e7a91e430671897ed) )
>     ROM_CONTINUE( 0x0c0001, 0x10000 )
> 	ROM_RELOAD  ( 0x0a0001, 0x10000 )
> 	ROM_CONTINUE( 0x0e0001, 0x10000 )
> 
> 	ROM_LOAD16_BYTE( "opr-13871.b7", 0x100000, 0x10000, CRC(0801cf02) SHA1(3007bbbce2f327f4700e78e2b8672f4482189cd7) )
> 	ROM_CONTINUE( 0x140000, 0x10000 )
> 	ROM_RELOAD  ( 0x120000, 0x10000 )
> 	ROM_CONTINUE( 0x160000, 0x10000 )
> 	ROM_LOAD16_BYTE( "opr-13867.b3", 0x100001, 0x10000, CRC(b014f02d) SHA1(46f5ed0b44cee03a6aec9ec57b506bb15bf35e47) )
>     ROM_CONTINUE( 0x140001, 0x10001 )
> 	ROM_RELOAD  ( 0x120001, 0x10001 )
> 	ROM_CONTINUE( 0x160001, 0x10001 )
> 	
> 	ROM_LOAD16_BYTE( "opr-13872.b8", 0x180000, 0x10000, CRC(f066f315) SHA1(bbeb24daaded994240d0cdb5cec2e662b677cb75) )
> 	ROM_CONTINUE( 0x1c0000, 0x10000 )
> 	ROM_RELOAD  ( 0x1a0000, 0x10000 )
> 	ROM_CONTINUE( 0x1e0000, 0x10000 )
> 	ROM_LOAD16_BYTE( "opr-13868.b4", 0x180001, 0x10000, CRC(e62a7cd6) SHA1(1e6d06345f7b6cef2e887d9b9cd45e0155140c5e) )
>     ROM_CONTINUE( 0x1c0001, 0x10000 )
> 	ROM_RELOAD  ( 0x1a0001, 0x10000 )
> 	ROM_CONTINUE( 0x1e0001, 0x10000 )
> 	
> 	ROM_LOAD16_BYTE( "opr-13873.b10",0x200000, 0x10000, CRC(1bd145f3) SHA1(4744ffe9fbda453785345b46eb61b56730048f42) )
> 	ROM_CONTINUE( 0x240000, 0x10000 )
> 	ROM_RELOAD  ( 0x220000, 0x10000 )
> 	ROM_CONTINUE( 0x260000, 0x10000 )
> 	ROM_LOAD16_BYTE( "opr-13852.a1", 0x200001, 0x10000, CRC(943aba8b) SHA1(d0dd1665a8d9495a92ae4e35d6b15b966e8d43cd) )
>     ROM_CONTINUE( 0x240001, 0x10000 )
> 	ROM_RELOAD  ( 0x220001, 0x10000 )
> 	ROM_CONTINUE( 0x260001, 0x10000 )
> 
> 	ROM_LOAD16_BYTE( "opr-13874.b11",0x280000, 0x10000, CRC(4fd59bff) SHA1(2b4630e49b60593d668fe34d8faf712ac6928c14) )
> 	ROM_CONTINUE( 0x2c0000, 0x10000 )
> 	ROM_RELOAD  ( 0x2a0000, 0x10000 )
> 	ROM_CONTINUE( 0x2e0000, 0x10000 )
> 
> 	ROM_LOAD16_BYTE( "opr-13853.a2", 0x280001, 0x10000, CRC(7ea93200) SHA1(8e2d8cd48a12306772653f25bddc99ad0597a698) )
> 	ROM_CONTINUE( 0x2c0000, 0x10000 )
> 	ROM_RELOAD  ( 0x2a0000, 0x10000 )
> 	ROM_CONTINUE( 0x2e0000, 0x10000 )
> 
> 	ROM_LOAD16_BYTE( "opr-13894.b12",0x300000, 0x10000, CRC(e3d0bee2) SHA1(503a78123ca9d6f3405972bca281dcdaba929c99) )
> 	ROM_CONTINUE( 0x340000, 0x10000 )
> 	ROM_RELOAD  ( 0x320000, 0x10000 )
> 	ROM_CONTINUE( 0x360000, 0x10000 )
> 	ROM_LOAD16_BYTE( "opr-13891.a3", 0x300001, 0x10000, CRC(c6b3c414) SHA1(0f0d936e77eb483be8865e8d968d78260e88ca99) )
> 	ROM_CONTINUE( 0x340001, 0x10000 )
> 	ROM_RELOAD  ( 0x320001, 0x10000 )
> 	ROM_CONTINUE( 0x360001, 0x10000 )
> 
> 	ROM_LOAD16_BYTE( "opr-13876.b13",0x380000, 0x10000, CRC(1c5ffad8) SHA1(13e5886ceece564cc71ba7f43a26d2b1782ccfc8) )
> 	ROM_CONTINUE( 0x3c0000, 0x10000 )
> 	ROM_RELOAD  ( 0x3a0000, 0x10000 )
> 	ROM_CONTINUE( 0x3e0000, 0x10000 )
> 	ROM_LOAD16_BYTE( "opr-13855.a4", 0x380001, 0x10000, CRC(856f3ee2) SHA1(72346d887ff9738ebe93acb2e3f8cd80d494621e) )
>     ROM_CONTINUE( 0x3c0001, 0x10000 )
> 	ROM_RELOAD  ( 0x3a0001, 0x10000 )
> 	ROM_CONTINUE( 0x3e0001, 0x10000 )
> 	
> 	ROM_REGION( 0x50000, REGION_CPU2, 0 ) // sound CPU
> 	ROM_LOAD( "epr-13892.a10", 0x00000, 0x08000, CRC(fdfbe6ad) SHA1(9ebb94889c0e96e6af9cdced084804ca98612d61) )
> 	ROM_LOAD( "opr-13893.a11", 0x10000, 0x20000, CRC(384233df) SHA1(dfdf94697587a5ee45e97700f3741be54b90742b) )
> 
> //	ROM_REGION( 0x0100, "plds", 0 )
> //	ROM_LOAD( "315-5298.b9",  0x0000, 0x00eb, CRC(39b47212) SHA1(432b47aee5ecbf08a8a6dc2f8379c816feb86328) ) // PLS153
> 
> ROM_END
> ```
> 
> I think the tileram is the other graphical issues will need to confirm though and there isint a gfx viewer on this mame. Yea tested all good (mostly) with tileram added

Good work man it's looking ALOT better now although im using MAME72 so my sprite and gfx loading is somewhat different
both in the code and mem map loading depts, so it could look even better in this core.?? anyway likely confined to my
end but some sprites are sticking with shinobi hookup which doesn't happen with the fantzn2x sprites.

Just thought i'd mention that listen my setup is not ideal for this so i was thinking i'll leave you guys to it with regards
to these Sega games unless you specfically want me to do something for ya's should Cotton become fully playable i'll
be happy to update the soundcore and all affected drivers so we have full music and sfx in the game.

**Comment by mahoneyt944** [comment]
@arcadez2003 no I didn't. Though it seems like the sound loading needs deliberately empty pockets for the speech to work right.

**Comment by arcadez2003** [comment]
> @arcadez2003 no I didn't. Though it seems like the sound loading needs deliberately empty pockets for the speech to work right.

I spent a fair few hours yesterday looking into why tturfu sound is bad and trying to fix that bad sprite i never got anywhere 
so not too keen to revisit it today, but maybe adding a proper dump of the MCU if we can support it here might be a path worth traveling as fixed sound might be at the end of it.

**Comment by mahoneyt944** [comment]
Would probably have to add all the mcu dumps if going that route, for consistency purposes.

**Comment by MistyDreams** [comment]
> Good work man it's looking ALOT better now

Ive added a test ROMREGION16_BE  draw it should take care of the gfx glitches the drawing needs worked around not the rom loading. Ill test it when I get in. Just grabbed the appropriate code and reworked it for out core. Will test when I get in. Will take a screenshot. It should fix the missing /corrupt gfx our current code drawing stalling on needing the romload hacks

**Comment by MistyDreams** [comment]
Well testing the new system cotton sprites are good, bullet as well, fantzn2x is good as well afightere however is a bit sketchy might be using system16a drawing who know.

@mahoneyt944 i also tested tturf and it fixes that sprite issue as well.

**Comment by mahoneyt944** [comment]
Nice

**Comment by arcadez2003** [comment]
I've updated the UPD7759 sound core and all related drivers and files it may sort the problems with tturfu it may not
still a bit to do however as unlike with my xbox core we dont have the segas16b driver to drop the changes directly 
into so i've been splicing in code i think is needed from the newer driver.

As things stand i've only tested Cotton music and sfx now works if you coin and start a game right away but if you
let the attract mode cycle or do an ingame reset when you start a game there is no sound as for the speech there
is none currently so some work still do here.

i'll send the code changes tomorrow i may need some advice as to how to proceed here

**Comment by arcadez2003** [comment]
> Well testing the new system using ROMREGION16_BE loads cotton sprites are good, bullet as well, fantzn2x is good as well afightere however is a bit sketchy might be using system16a drawing who knows. I an get one set working then the other doesnt will look into that one a little more.
> 
> @mahoneyt944 i also tested tturf and it fixes that sprite issue as well.

Well there ya go one bird many stones :)

**Comment by MistyDreams** [comment]
well sprites where the issue ill have more time at the weekend to get afighter looked at looks like a banking issues it swaps one or the other

**Comment by mahoneyt944** [comment]
@MistyDreams. PR the new video code once you deem it "ready". Also, you may want to initialize `sys16_sprite_draw = 0;` in `MACHINE_INIT( sys16_onetime )`, if you haven't already that is.

https://github.com/libretro/mame2003-plus-libretro/blob/755e64ed8c7f1fdc5d69e65084a3355c51107937/src/machine/system16_machine.c#L56-L74

**Comment by MistyDreams** [comment]
Well its good practice but c will initialize it to 0. I just need to clam the banks its doing something funky at the moment to make it good with our code, The problem is if you change the romloads and find an issue its a lot of undoing without testing. Again things can be fixed in time tha tget broke but I only have a certain amount of free time.

**Comment by mahoneyt944** [comment]
@MistyDreams we also should probably allow sprite x offset shifts in the new code as well, needed for some games like tturfbl

VIDEO_START( system16 ) should use this in common default:
```
		if (!sys16_sprxoffset)
			sys16_sprxoffset = -0xb8;
```

Then use this in draw_one_sprite_new
```
int xpos    = (data[1] & 0x1ff) + sys16_sprxoffset;
```

**Comment by mahoneyt944** [comment]
Sprites fixed now closing. Probably need a general discussion area for system16

**Comment by arcadez2003** [comment]
Lovely work there honestly i cannot state that enough i didnt think it possible to support some of these in the old system16.c 
hence why i created a seperate Sega core for my xbox project and i load all these games via segas16a segas16b segas18 
segaxbrd and segaybrd.

If only you were around all those years ago eh it would have saved me a ton of work :)

For Cotton some work will be required to get the sound to work i've mentioned that in the other thread.
