### ISSUE TITLE
Aliensyn titlescreen graphics issue

### ISSUE THREAD

**Issue by mahoneyt944** [libretro/mame2003-plus-libretro#1372]
Probably a BE issue, but noting it for testing. Titlescreen flashes improper colors before going to gameplay demo.
![aliensyn-220610-014113](https://user-images.githubusercontent.com/49591133/172998320-c4010306-726e-4e9e-953b-37789404f83d.png)

**Comment by MistyDreams** [comment]
thank for the heads up ill look into it. First on the agenda is to sort this need for driver init and and machine init only one is needed!

**Comment by mahoneyt944** [comment]
There's a pecking order for driver init vs machine init vs video_start(common defaults). That's probably a big can of worms moving everything, but I agree it's messy.

**Comment by mahoneyt944** [comment]
It only flashes for a quick second like that. Tried priority 2 didn't seem to help.
