### ISSUE TITLE
Fantzn2x scroll issue.

### ISSUE THREAD

**Issue by mahoneyt944** [libretro/mame2003-plus-libretro#1384]
There's now an issue with y scroll with fantzn2x on this screen below. Left side image not scrolling while the right side is scrolling but with a glitched image. 
![fantzn2x-220619-220019](https://user-images.githubusercontent.com/49591133/174512663-f5c9c415-d65e-4bf2-b7b4-82bff6999c33.png)

**Comment by MistyDreams** [comment]
not really a glitch the part just scrolls can update the video code but will not go to far on it because its aimed at lower end hardware
