### ISSUE TITLE
Action Fighter in ole system16.c

### ISSUE THREAD

**Issue by arcadez2003** [libretro/mame2003-plus-libretro#1390]
Here is Action Fighter hooked up in the ole system16.c everything seems fine with it feel free to use it or not.

[AF.zip](https://github.com/libretro/mame2003-plus-libretro/files/8967187/AF.zip)

Regards

**Comment by MistyDreams** [comment]
i do have action fightere working apart from the inputs on the old driver will obviously working in the new segas16b as well apart from the inputs. I think i would probably be best to let mahoney do teh segas16a update for this unless you guys want to mess about with the old system

**Comment by MistyDreams** [comment]
i did recheck the afightere e i done doesnt have there issues. the game looks fine apart from some minor tile issues to be honest. I would change the  romname to afightera thats what it is in current mame and leave afighter as it is so its one less set to fix when sorting all this mess eventally.

**Comment by arcadez2003** [comment]
Aye i noticed the tilemaps had a different address was gonna try it later, but hey it looks like you have this in the bag
so maybe i'll just drop it and move on to something else

**Comment by MistyDreams** [comment]
need to hook the segas16.c in properly. still need to sort the sound and scrolls ect the 8255 stuff can wait  should get it done at the weekend. I did try on the old system didnt help unless you wanna mess with the offsets

**Comment by arcadez2003** [comment]
Well it looks just about there now i simply needed  sys16_tilebank_switch=0x2000; in the MACHINE_INIT it looks 100% now
the sound is 100% the inputs are 100% but i suppose you guys wanna hook it up via the segas16a so it's no bother
i'll just dump the code then only two hours of my life wasted with this :)

**Comment by MistyDreams** [comment]
great job saves me doing the segas16a.c stuff haha good job!

**Comment by arcadez2003** [comment]
Well @mahoneyt944 can still do the segas16a port if he wants but it's up and running via this commit......

https://github.com/libretro/mame2003-plus-libretro/pull/1391

**Comment by mahoneyt944** [comment]
I don't have plans to do segas16a any time soon, while closing / moving into the new house. So this is probably best for now, unless someone else wants to plug it into the new driver. But that can also be done later too.

**Comment by arcadez2003** [comment]
Yeah 100% playable could be considered best for now until well someone else makes it 101% playable in another driver 
sometime down the road or not LOL 

Anyway time to close this down and good luck with the shift which will likely = bigtime stress

**Comment by MistyDreams** [comment]
can see any issues moving the stuff problem is romsets are misnamed that leads to missing games like shinobi system16a thats really using system16b more organizing . Cotton,fantzn2 have known glitches with the system16 video maybe others too if the do have glitches move em so they dont

**Comment by mahoneyt944** [comment]
We can adjust naming to better identify things now that it works. Shouldn't be an issue. PR whatever.

**Comment by MistyDreams** [comment]
nah isint an issue with this pr per say just the driver in general

**Comment by arcadez2003** [comment]
I agree with ya but it's time and motivation really isn't it.?? most people im sure have a baseline as to whether a game 
is playable or not most of the big name classic Sega games that i like at anyrate pass the criteria that i've set for myself
everyone is different some will have lower or higher expectations that is to be well expected :)

Sure there are some niggles with the ole code with certain games while others seem fine it's handy to have options now
something to consider is if you wanna shift more games across is some of them perform worse with the newer Sega code
and worse again with each rewrite "there were several upto around MAME92"

You'll be ok with the Sega System 16 A and B games but if you were to expand this to the following drivers then you'd
have to expect some drops in performance hence why i only use the newer code for games that did not work or had
serious gfx problems in the ole core........

segaxboard
segaorun
segahang
system18
segayboard

**Comment by MistyDreams** [comment]
Well anything that runs in the old xbox should run fine on the pie no problems. Again its all in the eye of the beholder certainly the system16a and b can be improved with extra set added and the protection ones removed and a general driver tidy up. Since all games are covered that was the main goal the rest of the improvements are optional if a particular game has bugs. Personally id like to see eswat supported and passing shot  think only the bootlegs work for them ones

**Comment by arcadez2003** [comment]
I can do ESWAT and Dynamite Dux no problem if you want

**Comment by MistyDreams** [comment]
nah that would be lazy on my part i could add them easily enough. No point in making bigger messes it is what it is

**Comment by arcadez2003** [comment]
Aye nae worries i decided to look at Dunkshot seeing as for some reason i like basketball games but it's one of
the very few sets there are no decrypted versions available, im sure there was one for that game on that jamma site
that kept all those FD decrypted sets back in the day.

But they long since removed all the roms due to scammers using them on pcb's and selling as the official versions
which is a pity and a prime example of how the few mess everything up for the majority, now if only they'd release
those system 24 decrypted sets then we could have Crackdown Gain Ground and Rough Racer.

**Comment by MistyDreams** [comment]
just to be clear dont give a toss about what sets we do and dont use just the same set name that matches current mame so we know what sets we are working with to see if we can use better ones or add sets.

**Comment by arcadez2003** [comment]
Well most of the decrypted sets are clones so for user ease of use we should actually add the parent set so everything flows
as it should, but that will only give us more non working parent sets which can be an issue in this core due to warning
screens being disabled.

**Comment by MistyDreams** [comment]
the parent sets dont even work anyway should be tossed

**Comment by arcadez2003** [comment]
The warning screens are disabled as you likely know due to users not likeing them which i never understood as every arcade 
game more or less boots to a warning screen of some sort anyhow, MAME is an arcade preservation project hence they tend
to add all versions they have of a dumped game regardless of whether it works or not.

I think we should stick with that format users can easily filter out non working games from their romlists your other point
i agreed with last time you made it that a little warning popup that a game is playable or not and if there is a working clone
or not should be something to consider implementing for this core.

As i often see this or that game is not working posts across the forums where the users dont know that there is a working
set they can fall back on.

**Comment by MistyDreams** [comment]
big picture i agree with you should be an info screen. I cant think of a sane reason to remove this without placing something else in its place to show the user this info and react to it.  GAME_UNEMULATED_PROTECTION  tells me a game probably doesnt work.

**Comment by arcadez2003** [comment]
Yeah most of the time your right i guess it depends on what the protection is how it's used how complex it is etc etc 
and whether the simulation workarounds can handle all the routines to a decent enough standard which reminds me
i'll need to look into this sometime.....

GAMEX(1991, tmnt2,    0,        tmnt2,    ssridr4p, gfx,      ROT0,  "Konami", "Teenage Mutant Ninja Turtles - Turtles in Time (US 4 Players ver. UAA)", GAME_UNEMULATED_PROTECTION )		// ver. UAA
GAMEX(1991, tmnt22p,  tmnt2,    tmnt2,    ssriders, gfx,      ROT0,  "Konami", "Teenage Mutant Ninja Turtles - Turtles in Time (US 2 Players ver. UDA)", GAME_UNEMULATED_PROTECTION )		// ver. UDA
GAMEX(1991, tmnt2a,   tmnt2,    tmnt2,    ssrid4ps, gfx,      ROT0,  "Konami", "Teenage Mutant Ninja Turtles - Turtles in Time (Asia 4 Players ver. ADA)", GAME_UNEMULATED_PROTECTION )	// ver. ADA

**Comment by MistyDreams** [comment]
maybe add a not running flag for clarity as well as the other flags if needed is all I can think of to be honest
