### ISSUE TITLE
System16 WIP

### ISSUE THREAD

**Issue by mahoneyt944** [libretro/mame2003-plus-libretro#1396]
Starting unified issue for these games as requested.

**Comment by mahoneyt944** [comment]
@MistyDreams @arcadez2003

**Comment by mahoneyt944** [comment]
@MistyDreams @arcadez2003 
I got passht4b gfx working, still needs the sound fixed though. Not sure if this is a simple mem map issue or a chip issue.

**Comment by MistyDreams** [comment]
later mames have the sound hooked up for this bootle, info will be there  if you want to fix it. A lot of the bootlegs have gfx issues in later mame guess they figured the decrypted bootlegs sets where better quality or they just never go round to fixing the bootleg gfx issues.

**Comment by mahoneyt944** [comment]
I don't think many mame versions work with this 4 player version, gfx wise, so I wanted to get it working here. It's still not perfect but pretty great all things considered.

Haven't looked into the sound but that would be great if it's not too difficult to get going.

**Comment by MistyDreams** [comment]
yea wont do any harm if someone decided to add sound to the bootleg have to agree.

**Comment by mahoneyt944** [comment]
Also just added snapper which piggybacks atomicp. Both have no sound.  It's basically "snake" back before phones became "smart".  Lol

**Comment by arcadez2003** [comment]
0.123u1: Changed YM2413 clock speed to 5MHz.
0.89u3: Aaron Giles hooked up sound in Atomic Point (tempo is just a guess right now).

Dunno about Snapper though but i may well use the same hookup

**Comment by mahoneyt944** [comment]
Snapper looks to be the same sound except i see something about a divisor variable being used.

Also, with the video, this game seems to just use tiles, I think. I saw something about disabling vblank /refresh or something, can't remember now lol. The game plays a little choppy but I think that might be the way it is unless we need to disable the vblank or refresh still.

**Comment by mahoneyt944** [comment]
I didn't think this game would be that great but it's growing on me ha https://m.youtube.com/watch?v=DNSbbFBiOtM&t=117s

**Comment by MistyDreams** [comment]
if you disable the vblank it wont run

**Comment by MistyDreams** [comment]
well thats just stops the system16 video refresh disable kicking in

**Comment by MistyDreams** [comment]
if it was an issue you would be getting black screen frames

**Comment by mahoneyt944** [comment]
Seems ok to me.

**Comment by mahoneyt944** [comment]
Just merged a priority fix for action fighter. Looks good so far but needs some critical eyes to help find any issues. Need to compare it to other examples.

**Comment by mahoneyt944** [comment]
@arcadez2003 latest commit should solve all the priority issues in action fighter. It's firing on all cylinders now 👍.

**Comment by MistyDreams** [comment]
something must be really wrong with the system16a tile/sprite priority decoding to need these priority changes

**Comment by arcadez2003** [comment]
> something must be really wrong with the system16a tile/sprite priority decoding to need these priority changes

There was no set system type drawing back then just a whole chunk of code all the games used in one way or another
all hacks and mods basically and not 100% for everyone one.

**Comment by arcadez2003** [comment]
> @arcadez2003 latest commit should solve all the priority issues in action fighter. It's firing on all cylinders now 👍.

Good stuff

**Comment by MistyDreams** [comment]
> There was no set system type drawing back then just a whole chunk of code all the games used in one way or another
> all hacks and mods basically and not 100% for everyone one.

right enough not sure what set aliensyn really is could be systen16b would need to check that to be fair could be code wide

**Comment by MistyDreams** [comment]
shinobibl seems to be leaving spirtes on the screen

**Comment by mahoneyt944** [comment]
When? Pic?

**Comment by MistyDreams** [comment]
even without that sray bullets ect

**Comment by mahoneyt944** [comment]
Hmm need to verify type1 textram, in mame2003 it was this but it differed for certain games, (set_bg_page vs set_bg_page1) 

Either that, the new quartet2 spritesystem or maybe the banking is wrong. Idk that it was actually working before.

```
static void shinobl_update_proc( void ){
	set_bg_page( sys16_textram[0x74e] );
	set_fg_page( sys16_textram[0x74f] );
	sys16_fg_scrolly = sys16_textram[0x792] & 0x00ff;
	sys16_bg_scrolly = sys16_textram[0x793] & 0x01ff;
	sys16_fg_scrollx = sys16_textram[0x7fc] & 0x01ff;
	sys16_bg_scrollx = sys16_textram[0x7fd] & 0x01ff;
}
```

**Comment by MistyDreams** [comment]
yea them functions are identical someone put the set_bg_page and set_fg_page  in a ifdef unless the source was already like that

**Comment by mahoneyt944** [comment]
Found the issue it's the quartet2 spritesystem change, see T2 branch, fixes the issue. Need to see if we can get both working since this change was needed for bodyslam

**Comment by MistyDreams** [comment]
yea that priority value is off for a start in the spritesystem

**Comment by mahoneyt944** [comment]
Not sure why shinobl has an issue with the top and bottom adding 1. Simple hack to fix it but probably another reason this is happening. The other games need the plus 1 for alignment.

**Comment by mahoneyt944** [comment]
Merged #1407, not sure if there's a better way but this seems to work. Let me know if it solves the issues you saw.

**Comment by mahoneyt944** [comment]
We should probably log top and bottom and see what's going on, I bet it's clipping and returning before it sets the priority. By removing the 1 from top and bottom it must just avoid clipping.

**Comment by MistyDreams** [comment]
I bust doing other updates cant merge atm else ill have to fix re-bases ect. Do you have sound in alexkidd Seems im not getting any sound. Ill need to rebuild my roms to check master.

**Comment by mahoneyt944** [comment]
Yes alexkidd and alexkida are both working with the sound.

**Comment by MistyDreams** [comment]
hm ones protected both are working for you ?

**Comment by mahoneyt944** [comment]
It's not working but sound still plays if you let it run

**Comment by MistyDreams** [comment]
i know what i did stupid mistake on my part!

**Comment by arcadez2003** [comment]
> @MistyDreams @arcadez2003 I got passht4b gfx working, still needs the sound fixed though. Not sure if this is a simple mem map issue or a chip issue, maybe a totally different hookup.

https://github.com/libretro/mame2003-plus-libretro/commit/bc7bdb6bdf56a88fd5a91e5e27efca6ac1687177

The YM2203 is done the msm5205 still needs hooking up though although it looks tricky

**Comment by mahoneyt944** [comment]
Nice work. That really brings the game to life.

**Comment by arcadez2003** [comment]
Ah it's likely this then.........

	MDRV_CPU_ADD_TAG("sound", Z80, 4096000)

As the driver i grabbed the YM2203 code from had switched back to 4000000 for the Z80 all i can do is match up the
YM2003 with our Z80 clock and hope ofr the best :)

**Comment by mahoneyt944** [comment]
I'll test it

**Comment by arcadez2003** [comment]
This is the original commit incase you spot an error i might have made, the YM2203 MEM address values are handled differently in core so i had to seriously mod em but if those were incorrect we'd have no sound rather than it being
to fast.

https://github.com/mamedev/mame/commit/437b4a615b42cdb961a960ff6f573674a9c64e8d

**Comment by MistyDreams** [comment]
nah not different just system16b was added for the u7759 the original system16 is there as it was

**Comment by mahoneyt944** [comment]
Think I got it solved. MDRV_CPU_PERIODIC_INT controls the tempo, I slowed it down by ear. Not sure if there's a exact way to match the timing but it sounds close. https://github.com/libretro/mame2003-plus-libretro/commit/5fb09fdc55e6cee90b9c48bcee87b0f17ebeb444

**Comment by mahoneyt944** [comment]
Should these be mono or stereo? If you serve the ball and continue rapidly swinging the racket, the swing sounds like nails on a chalk board lol. Guessing this isn't right but it's close since the sound trigger is right.

**Comment by MistyDreams** [comment]
knew these changes would mess up what i was doing. This is the last time im spending 30 minutes and im still re basing still not.  if it happens again not going to all the hassle to keep it based with master.

**Comment by arcadez2003** [comment]
I thought those sounds are sample based and are triggered by the MSM5205 hence they're broken without it hooked up

0.181: Sound improvements for clone Passing Shot (4 Players) (bootleg). Hook up MSM5205 and 74LS157, game now have some imperfect samples playback [AJR].

**Comment by mahoneyt944** [comment]
> knew these changes would mess up what i was doing. This is the last time im spending 30 minutes and im still re basing still not. if it happens again not going to all the hassle to keep it based with master.

This is just the nature of working in a public project. But as a fore warning, I was under the impression we were not removing the protected sets just for the sake of? Unless I've misunderstood? or are you working on something else entirely? Just trying to reach an understanding here to avoid miscommunication and issues later. Hopefully you can elaborate on what you're doing or proposing to do so we are all on the same page.


>I thought those sounds are sample based and are triggered by the MSM5205 hence they're broken without it hooked up

I think the 5205 is likely used for the announcer voices. I didn't hear them when testing, but this is only my guess.

**Comment by arcadez2003** [comment]
> > I thought those sounds are sample based and are triggered by the MSM5205 hence they're broken without it hooked up
> 
> I think the 5205 is likely used for the announcer voices. I didn't hear them when testing, but this is only my guess.

Yeah your likely correct i haven't played this game all that much so not 100% on the sounds although currently we
have music at least but the sfx ball sounds etc etc are kinda messed up. it's tagged as imperfect sound right enough

0.175: Osso added preliminary sound to clone Passing Shot (4 Players) (bootleg).

On a seperate note i've got the sound working for Atomic Punk however im getting a strange address error / crash
when your game ends rather than hitting the game over and continue screen i'll need to investigate further, i assume
since Snapper uses the same hookup it would potentially have sound now also not tested it as yet i might add it
tonight to see if it crashes or not.

**Comment by arcadez2003** [comment]
Well Snapper seems fine with the sound hooked up played upto level 4 with no issues, however Atomic Punk
does not wanna play ball for some reason still outta the two Snapper is the better game so at least it has full
music and sfx now.

If anyone wants to see why Atomic Punk is playing hard to get sometime then simply use the hookup for Snapper
the clock tempo is different however.......

    timer_pulse(TIME_IN_HZ(10000), 0, snapper_sound_irq);

and mind to reem this out

//MDRV_CPU_VBLANK_INT(ap_interrupt,2)

**Comment by arcadez2003** [comment]
It's addictive this Snapper game upto level 7 now, just sussed out you can actually fire and kill the baddies :)

**Comment by MistyDreams** [comment]
remember this game on the bbc was called magic eel

**Comment by arcadez2003** [comment]
> remember this game on the bbc was called magic eel

Ah the BBC micro every school had em back in the day i think i've only ever played a couple of games on that Frak!
and Way Of The Exploding Fist, they let folks bring in games last day of school before the summer or Xmas.

No one i was pals with had a BBC right enough we all had the speccy and had to endure all manor of people with a C64 or whatever telling us the gfx and or the sound was far worse etc etc those were the days :)

**Comment by MistyDreams** [comment]
haha ten minutes to load a game!

**Comment by arcadez2003** [comment]
Dont you start now i loved my wee speccy :)

**Comment by mahoneyt944** [comment]
@arcadez2003 I cant compile anything because my phone screen is toast.... looking at mame2010 though, it uses atomicp_sound_divisor to skip over the irq, snapper would be every 4  but atomicp looks like it hits every time since it uses "++" to increment as a prefix (before the comparison is made)

try 
static int atomicp_sound_divisor = 0

initialize atomicp_sound_divisor for each mach init
(atomicp) atomicp_sound_divisor = 1;
(snapper) atomicp_sound_divisor = 4;

```
static void snapper_sound_irq(int param)
{
	static int atomicp_sound_count = 0;

	if (++atomicp_sound_count >= atomicp_sound_divisor) {
		cpu_set_irq_line(0, 2, HOLD_LINE);
		atomicp_sound_count = 0;
	}
}
```

```
MAME2010

static DRIVER_INIT( atomicp )
{
	segas1x_state *state = (segas1x_state *)machine->driver_data;

	system16b_generic_init(machine, ROM_BOARD_ATOMICP);
	state->disable_screen_blanking = 1;
	state->atomicp_sound_divisor = 1;

	segaic16_display_enable = 1;
}


static DRIVER_INIT( snapper )
{
	segas1x_state *state = (segas1x_state *)machine->driver_data;

	system16b_generic_init(machine, ROM_BOARD_ATOMICP);
	state->disable_screen_blanking = 1;
	state->atomicp_sound_divisor = 4;

	segaic16_display_enable = 1;
}

static TIMER_DEVICE_CALLBACK( atomicp_sound_irq )
{
	segas1x_state *state = (segas1x_state *)timer.machine->driver_data;

	if (++state->atomicp_sound_count >= state->atomicp_sound_divisor)
	{
		cpu_set_input_line(state->maincpu, 2, HOLD_LINE);
		state->atomicp_sound_count = 0;
	}
}
```

**Comment by MistyDreams** [comment]
to be fair @mahoneyt944  I think arcadez needs the crash looked at rather that how to implement it. Hope you get you phone fixed as well. I didnt know you  compile on a android pone/iphone phone never mind  an dev on then. I suppose it would be doable with a keyboard attached for editing.

**Comment by mahoneyt944** [comment]
Took some time to get use to but its actually really convenient, portability wise lol.

**Comment by mahoneyt944** [comment]
Took a stab at atomicp. From my testing, the sound does seem to work right when plugged in. The "crash" situation seems to be a divide by zero error which is being caught by the game code. At least the core isn't locked up when this occurs. Curious to as why snapper doesn't have this same issue, maybe this condition doesn't occur or the game code doesn't catch this. Either way I think we'd have to skip the line hold when this case happens for atomicp. Haven't nailed down when it occurs exactly but seems to be when the player loses. So maybe a game over or continue sound triggers it?
![atomicp-220712-160927](https://user-images.githubusercontent.com/49591133/178652992-30b97bb2-bf52-419d-864a-103548e45d69.png)

**Comment by arcadez2003** [comment]
Yeah i was thinking that also, that Atomic Punk somehow trips something to do with the sound timer or IRQ's which Snapper luckily doesn't, i seen no commits after the code was added which mention a fix for this issue so maybe it's confined to
our ole system16.c.?? the code was written for segas16b afterall.

**Comment by mahoneyt944** [comment]
It's definitely related to the irq. You can comment that out and it won't crash although it also has no sound then so not a useful workaround lol. Seems like a minor bug just can't pin down why.

**Comment by arcadez2003** [comment]
You've likely tried this already but if not you might wanna toggle the IRQ to see if that helps, currently it's holding the line
maybe try one of the other options eg ASSERT, CLEAR or PULSE.

**Comment by MistyDreams** [comment]
@mahoneyt944 im assuming you used the code from mame2010 with the comments above. It would probably be a good idea to check the memory maps against it for atomicp.

**Comment by mahoneyt944** [comment]
I'm looking into shangon, the sprites bug out every now and then and this did not happen in mame2000. So there may be an easy fix to this issue.
