### ISSUE TITLE
Option to use lightgun for AD_STICK games?

### ISSUE THREAD

**Issue by StormedBubbles** [libretro/mame2003-plus-libretro#1399]
Hello,

I haven't delved too deeply into the code, but lr-mame2003-plus appears to use the control type defined in the MAME drivers to determine which physical controllers are allowed to be used. Though not lightgun games in the traditional sense, some `AD_STICK` games do perform well when changed to `LIGHTGUN` (`esb`, `starblad`, and `starwars` are some examples). 

I don't think forcing lightgun controls on these games by explicitly changing them from `AD_STICK` to `LIGHTGUN` is a reasonable request, but is it possible to allow lightgun devices to be used with those games in addition to their default analog-stick control schemes? Or, if that would cause other issues, perhaps a toggle between stick and lightgun in the core options?

**Comment by mahoneyt944** [comment]
I was under the impression that ad stick controls could be controlled by a lightgun through the override system already in place, but maybe it's the other way around. May just be a limitation of our current code. At some point we need to rewrite areas of the input code to allow more functionality.

**Comment by MistyDreams** [comment]
code works like that originally your lightgun always overides other analog inputs this should be remapped in ra the way you implemented the code.

**Comment by StormedBubbles** [comment]
Thank you both for your responses.

I updated from source just a few minutes ago and deleted the .cfg files for the games I tested just to make sure everything is up to date. Here is my experience:

Games labeled as `LIGHTGUN` in the input driver are affected as follows by the XY Device core option:
- lightgun = absolute coordinates gun (what I want)
- mouse = relative gun coordinates (improper alignment with gun sight)
- none = absolute coordinates for analog stick on controller

On the other hand, games labeled as `AD_STICK` in the input driver are affected as follows:
- lightgun = relative gun coordinates (improper alignment with gun sight)
- mouse = same as lightgun
- none = absolute coordinates for analog stick on controller

For `starblad` in particular, I changed its input type to `LIGHTGUN` in its input driver on my own fork of this emulator and have absolute gun coordinates when using the lightgun. Perhaps the issue comes from 

`/src/inptport.c`

```
		case IPT_AD_STICK_X:
			axis = X_AXIS; is_stick = 1; is_gun=0; check_bounds = 1; break;
		case IPT_AD_STICK_Y:
			axis = Y_AXIS; is_stick = 1; is_gun=0; check_bounds = 1; break;
		case IPT_AD_STICK_Z:
			axis = Z_AXIS; is_stick = 1; is_gun=0; check_bounds = 1; break;
		case IPT_LIGHTGUN_X:
			axis = X_AXIS; is_stick = 1; is_gun=1; check_bounds = 1; break;
		case IPT_LIGHTGUN_Y:
			axis = Y_AXIS; is_stick = 1; is_gun=1; check_bounds = 1; break;
```

Note how the `AD_STICK` controls do not have gun enabled. I only noticed this just now and haven't tested.

@MistyDreams That does allow me to move the gun to move the cursor, but it's a hamstrung experience due to the relative coordinates. When using absolute coordinates, the alignment isn't lost when interacting with the screen edges. I suppose there are other considerations too, like how the cursor leaps to the corner of the screen to aid with offscreen reloading. That probably shouldn't be enabled for the stick-as-gun games.

**Comment by MistyDreams** [comment]
there is also another flaw it wont read for abs unless xy set to lightgun for abs the way its setup so that will have to stay on for a start

**Comment by MistyDreams** [comment]
@StormedBubbles I only have a laptop with  a abs touchpad cant test on that right now. But reading the code if you press the touchpad button in and move left and right it will work but you have to press the button.

**Comment by Widge-5** [comment]
> For `starblad` in particular, I changed its input type to `LIGHTGUN` in its input driver on my own fork of this emulator and have absolute gun coordinates when using the lightgun. Perhaps the issue comes from
> 
> `/src/inptport.c`
> 
> ```
> 		case IPT_AD_STICK_X:
> 			axis = X_AXIS; is_stick = 1; is_gun=0; check_bounds = 1; break;
> 		case IPT_AD_STICK_Y:
> 			axis = Y_AXIS; is_stick = 1; is_gun=0; check_bounds = 1; break;
> 		case IPT_AD_STICK_Z:
> 			axis = Z_AXIS; is_stick = 1; is_gun=0; check_bounds = 1; break;
> 		case IPT_LIGHTGUN_X:
> 			axis = X_AXIS; is_stick = 1; is_gun=1; check_bounds = 1; break;
> 		case IPT_LIGHTGUN_Y:
> 			axis = Y_AXIS; is_stick = 1; is_gun=1; check_bounds = 1; break;
> ```
> 
> Note how the `AD_STICK` controls do not have gun enabled. I only noticed this just now and haven't tested.
> 

Out of curiosity I tried changing `is_gun=0` to `is_gun=1` for AD_STICK in my own fork to see what the behaviour would be.  I tested it out in starblade and I found that the crosshair tracked perfectly with my aim as I would expect from an original lightgun game.

I use a Sinden Lightgun with a Raspberry Pi.

**Comment by MistyDreams** [comment]
not an ideal fix but can hack it like that for your fork

**Comment by Widge-5** [comment]
Apologies,  I've just realised that when I tested that hack I had an irregular offset/ratio calibration set for my lightgun calibration.  I'll test it again a little later.

**Comment by StormedBubbles** [comment]
I tested it out too and found that the lightgun does indeed use absolute coordinates when `is_gun=0` is changed to `is_gun=1` for `AD_STICK` **and with no additional code changes made**. @Widge-5's irregular calibration must have been affecting the perception of the tracking, though, because it is not perfect on my end. However, it is way more usable than the standard mouse mode because the offsets are consistent regardless of hitting the screen edge.

@MistyDreams I am curious what a proper solution would be. My interpretation of the above change is that it is simply adding `GUNCODE` axes as an additional choice to the `AD_STICK`-specific default controls. It's similar to allowing an analog stick to control a lightgun game's aim. Currently, selecting lightgun for `AD_STICK` games doesn't work as intended. Many of these games would probably require specific fixes for alignment to the absolute mouse cursor, and I agree that those are more along the lines of hacks.

**Comment by mahoneyt944** [comment]
If changing is_gun to 1 fixes your issue, then that would be easy to add a core option to....defaulting the current value of 0. Idk if this is the best solution available but surely one that would work.

**Comment by MistyDreams** [comment]
@StormedBubbles would be better off as core hack option will cause other issues. It dont really matter the lightgun/pointer/mouse is a mess already switching between abs and rel tested on the touchpad. Doesnt matter in reallity adding another hack on mess of hack in there already i suppose good luck debugging issues when some type of drift comes in

**Comment by StormedBubbles** [comment]
@MistyDreams Sorry if I am not explaining this very clearly, but I am indeed using device type lightgun from the core-option perspective. I have the emulator configured to use a lightgun device such as Widge's Sinden Lightgun as an absolute device. I am able to get that functionality properly in this emulator for all games identified within the MAME driver code as `LIGHTGUN`. The issue is that games identified as `AD_STICK` do not allow the use of a lightgun device with absolute coordinates, even though `AD_STICK` is also an absolute-input category. Changing that `is_gun` option appears to enable that without affecting other functionality.

I am not proposing changing anything at all in the game's input driver. I was just proposing to enable absolute coordinates for lightgun as an option for `AD_STICK` games. I would just add the gun axes to the game's specific cfg file myself, but this port of MAME does not allow me to edit those manually.

@mahoneyt944 Thanks. I don't want to cause the floor to cave in with something that appears to be a tiny change. 😅 Is the issue that I am describing clear? The current behavior is:

MAME says it's a `LIGHTGUN` game:
Core option for lightgun gives absolute coordinates

MAME says it's an `AD_STICK` game:
`is_gun=0`: Core option for lightgun gives relative coordinates
`is_gun=1`: Core option for lightgun gives absolute coordinates

Elimination of offsets and scaling issues is a whole different beast that I can just try to deal with myself.

**Comment by MistyDreams** [comment]
@StormedBubbles  the is_gun will knock sensitivity settings out in the driver if the gun is moved and you go back to yo analog stick its will be messed up why its not set as a gun, 

https://github.com/libretro/mame2003-plus-libretro/blob/d780e6c72437f8f89c84028cb80ffdbe756b5854/src/inptport.c#L870
https://github.com/libretro/mame2003-plus-libretro/blob/d780e6c72437f8f89c84028cb80ffdbe756b5854/src/inptport.c#L937-L938

it should be fairly obvious the issues this will cause

**Comment by MistyDreams** [comment]
it might be enough to add 
 sensitivity = IP_GET_SENSITIVITY(in); 
input_analog_scale[port]=1;

in is stick but the issue remains with relative and abs device xy switching thats unrelated to this though

**Comment by StormedBubbles** [comment]
Thank you for clarifying. I missed that part in the code. I am an amateur with interpreting code, so the side effects of what I tried probably would have gone unnoticed by me. That is why I brought it up as an issue instead of proposing a change in a pull request 😜

**Comment by mahoneyt944** [comment]
I'm indifferent about how we fix this, I did however plug in a core option quickly in a test branch but we can scrap it if a better solution is made.  https://github.com/libretro/mame2003-plus-libretro/compare/Adstick

**Comment by MistyDreams** [comment]
@StormedBubbles easiest change is the drivers and tweak them to the lightgun as a lightgun axis the analog joystick will work to your tailored changes required anyway. Sorry i wasnt clearer about this before. Still think its the least resistance path for what you want to do.

**Comment by mahoneyt944** [comment]
The only difference in the ad stick flags and lightgun flags is `is_gun` so by using the core option, it would apply this fix to all games anyway for the few people wanting to do this. I don't think we'd want to change all the drivers since these aren't actually lightgun games.

**Comment by MistyDreams** [comment]
do as you will is more issues beyond that but hey youll find out in time.

**Comment by mahoneyt944** [comment]
I'm just discussing possible solutions. Not at the implementation stage. Do share if you propose something better

**Comment by MistyDreams** [comment]
ra should be mapping the joystick x/y to the lightgun instead of the mouse

**Comment by mahoneyt944** [comment]
You mean on the driver side or core side

**Comment by MistyDreams** [comment]
like you do other retroarch remapping mapping press f1 and goto controls

**Comment by mahoneyt944** [comment]
Oh you mean here
![Screenshot_20220626-190220](https://user-images.githubusercontent.com/49591133/175837048-52f27406-75d5-479f-94b3-9a3a06c70af6.png)

**Comment by MistyDreams** [comment]
yea mame should be showing them controls when a lightgun context controls when its is used can be set in else where though. There seems no way to set x and y axis. There should be an option to use the  lightgun x/y axis remap on the controller axis its a legit device.

**Comment by MistyDreams** [comment]
@StormedBubbles  can the lightgun your using work as a analog axis as well mapped as a controller that would work pretty sure it supports that mode

**Comment by mahoneyt944** [comment]
That might be from the way we have the lightgun hooked up, technically we only have retropad as a device type which is what populates the port 1 controls then we read the mouse/ lightgun/ pointer inputs directly (like an extension to our retropad)

Unfortunately, I'm not sure there's a proper way in RA to have two different device types active at the same time for a single player and having the user manually change them for every game wouldn't be friendly either. Probably would have to integrate something upstream I think.

**Comment by MistyDreams** [comment]
I think there is a solution on the device itself.

like the dophin bar


Switch to four different modes, Keyboard and Mouse Mode (LED1), Keyboard and Mouse Game Mode (LED2), Game Controller Mode (LED3) and WiiRemote Controller Emulator Mode (LED4) by pressing the MODE button on the DolphinBar.

mode 2 is rel mouse and keyboard
mode 2 is abs mouse and keyboard
mode3 is gamecontroller liek an analog joystick

**Comment by mahoneyt944** [comment]
That I couldn't comment on, I don't own any to test.

**Comment by MistyDreams** [comment]
Well if the siden supports controller mode which is should just a hid change it will work as an analog joystick when mapped in RA

**Comment by mahoneyt944** [comment]
Well that seems fair, @StormedBubbles see if your device has alternate modes and or if it can be remapped in RA. If not we can add the core option for this specific case as a last resort. Then maybe we can work with upstream to integrate this in a more proper way.

**Comment by StormedBubbles** [comment]
Sinden Lightguns are only absolute mice. There is no joystick mode. I haven't come across any emulator that allows the lightgun, mouse, or pointer axes to be mapped by the user via the RA GUI. I did search around for that recently, but I don't think it is implemented in RetroArch. That would be a useful feature, though.

As far as I know, having the device types being swapped via the core options or the RA GUI's controls menu is just a semantics thing. 6 of one; half a dozen of another. They more or less serve the same purpose as selection tools, and the lightgun axes must be mapped behind the scenes anyway (which they already are here). Switching from one menu to the other wouldn't change that and would make it a tad more inconvenient due to the difficulty in dealing with per-game overrides vs. per-game core options.

@MistyDreams I don't quite understand what the issue with having that core-option toggle is. Those not using lightgun devices should have it off, and those using lightgun devices wouldn't be using joystick devices. It's a niche thing for sure, but I figure those simultaneously using lightguns and joysticks would be an even smaller minority.

**Comment by MistyDreams** [comment]
the dolphinbar is a mouse device as well and can be put in controller mode as well though just goes through a different hid interface its all build into the device and diff hid modes are available. 

Im surprised sinden doesn't support this for older software thats the only reason dolphinbar has this mode. If it did support this there would be no need for a hack is all. if your sure is only show as a mouse youll need to speak to mahony.

**Comment by mahoneyt944** [comment]
I can PR the core option if that's the case. No problem.

**Comment by StormedBubbles** [comment]
> I can PR the core option if that's the case. No problem.

Thanks! I really appreciate it.

**Comment by MistyDreams** [comment]
sensitivity wont work in the analog menu due to what i showed you before  @StormedBubbles  just so your aware changing them will mess the original analog setting up if you use a controller again

**Comment by mahoneyt944** [comment]
I added restart will be required to the description for this reason.

**Comment by mahoneyt944** [comment]
Merged a core option. Remember to restart the core if and when you want to toggle this. Let me know if this solve the issue.

**Comment by StormedBubbles** [comment]
Yes, that new option works 😃. Thank you again!

**Comment by mahoneyt944** [comment]
👍
