### ISSUE TITLE
add support for 7049-5035=2014 new games

### ISSUE THREAD

**Issue by AngelofMe** [libretro/mame2003-plus-libretro#1410]
[ClrMame Pro XML, Arcade.txt](https://github.com/libretro/mame2003-plus-libretro/files/9034716/ClrMame.Pro.XML.Arcade.txt)
rename txt -> xml

**Comment by MistyDreams** [comment]
???????

**Comment by mahoneyt944** [comment]
I'm sorry but this issue does not make logical sense. You cannot just add thousands of games, they need drivers to operate not just names of romsets.
