### ISSUE TITLE
neo geo button name

### ISSUE THREAD

**Issue by AngelofMe** [libretro/mame2003-plus-libretro#1411]
They're A B C D
I don't like call them 1 2 3 4

**Comment by mahoneyt944** [comment]
Mame emulates thousands of arcade titles so a generic system of buttons is required to create structure for many games.

**Comment by mahoneyt944** [comment]
BTW neogeo is already set to this within RA. just not in the mame menu.
https://github.com/libretro/mame2003-plus-libretro/blob/bd536204b5b544ab1c62b4a3c00aaab48a6ae195/src/controls.c#L10978-L10989
