### ISSUE TITLE
Hard Times and World Beach Volley sound

### ISSUE THREAD

**Issue by arcadez2003** [libretro/mame2003-plus-libretro#1417]
I thought it looked simple enough famous last words i guess......

Hard Times 
https://github.com/mamedev/mame/pull/10043

World Beach Volley
https://github.com/mamedev/mame/commit/694eabe89d05d3b880b945d60e6b47231773e72c

But after adding in the above CPU dumps and the relevent code changes World Beach Volley stalls on boot
Hard Times however get's in game but alas i cannot get the music and sfx to work the best i could achieve is
to get it to make a buzzing sound akin to a big ole wasp :)

Thoughts

I've never worked with PIC CPU's before so not sure if that handles the music and the OKI does the sfx, certainly Haze mentions
only the music is working in World Beach Volley due to the OKI banking being wrong, i stuck with the ole banking style present in the driver it might be wrong it might be ok i dunno yet.

But that doesn't explain the lack of music which im guessing as per the above comes via the 2nd cpu maybe our ancient PIC
needs updated also.?? anyway feel free to take run at this sometime if ya's want to try and get the sound to work as i've run
outta ideas basically i've let some notes in the driver this could well be another of those rabbit holes so keep that in mind :)

Here are the PIC CPU and Hex dumps for Hard Times as they're not publically available yet, currently as per latest MAME
i have the games setup to use the proper CPU2 dump but the hex can also be used as per bigtwin cpu2 rom loading and
DRIVER_INIT

As for World Beach Volley the latest romset should have the PIC dump included in it however i could not trackdown a hex
for this game, as things stand regardless of which dump is used the result is still the same
[hard_times_pic16c57.zip](https://github.com/libretro/mame2003-plus-libretro/files/9106705/hard_times_pic16c57.zip)

**Comment by kounabi22** [comment]
Is the hard times now working in mame2003plus?

**Comment by arcadez2003** [comment]
It works but doesn't have sound or music currently.

**Comment by MistyDreams** [comment]
I did look at this. I dont know it the download posted was bad but the crc was wrong and had some memory access issues on the pic not sure if it was the dump or the pic itself. When a good dump with the crc comes ill test it a little more. Probably will be in the next mame release

**Comment by arcadez2003** [comment]
Yeah i noticed that as well and like yourself i decided to wait for a 100% bona-fida official release of the PIC dump
which should be available now via a site i grab em from, i assumed the banking might be incorrect but i'll try it
with the latest romset and see how it goes.

**Comment by MistyDreams** [comment]
world beach volley caused issues as well I think the pic might need to tlc for this core. Ill check out the possibility if it being a 64 bit issues.Will let you know if i find anything so im not digging into the work you've done already.

**Comment by arcadez2003** [comment]
Yip your likely on the right track i tested the latest dump no src warnings this time but the results are the same might be a
fools errand to look into this further as our PIC CPU might need updating and even then we're guessing on the sound banks
anyhow as we cant support the new banking code added at the same time as the new sound rom.

**Comment by MistyDreams** [comment]
It does seem like a lot of work for two games. Feel free to close issue doesnt need to be open to look at it when the rom comes out in the public. Main thing is the games do work.

**Comment by arcadez2003** [comment]
Ok took some time to look at this again tonight some progress but still there are issues.......
https://github.com/libretro/mame2003-plus-libretro/commit/dc90a6ad071a8a28edfc0154f42c0d7f8c129e00

Game starts fine the music kicks in on the title screen but as soon the character fires his tommygun which creates
the Hard Times logo the game slows to an absolute crawl, if however you coin it up before the attract mode cycles
to the title screen and start a game the sound works at first then drops out although the game speed wise is fine.

When the character fires the gun is the exact moment the SFX should kick in which makes me wonder if it's a banking 
issue although i'd expect the sound to simply drop out or not work in that instance rather than it affecting the game
speed.

It could an issue with the timing or interrupts with regards to our PIC CPU core but with no working games that actually
use a bona-fida PIC rom dump in our core it's hard to find anything to go by, they weren't able to dump PIC's until 
relatively recently.

Im not really experienced with the PIC CPU's TBH having never dealt with them before from what i can tell before
they could dump em properly they seemed to have HEX dumps then code to hack around protected reads and writes
to and from the CPU two games use this method in our core Dragon Master and Big Twin so obviously not alot to
go on here.

Any ideas as to the most likely cause.??
