### ISSUE TITLE
buildbot: hold on merges again

### ISSUE THREAD

**Issue by markwkidd** [libretro/mame2003-plus-libretro#142]
libretro is trying to put out RA 1.7.2 stable today, we're asked to not merge anything till the release is ready

**Comment by grant2258** [comment]
no probs already done the pull req for cps1 and 2 just waiting for @arcadez input

**Comment by markwkidd** [comment]
retroarch stable is now released! closing

**Comment by grant2258** [comment]
sweet ill update mine! only updated it a few days ago as well does this mean we have our new keyboard functions to play with?

**Comment by grant2258** [comment]
just in time :)
