### ISSUE TITLE
I don't know if it's a core issue - Xbox PAD can't assign "HOME BUTTON".....

### ISSUE THREAD

**Issue by DjDiabolik** [libretro/mame2003-plus-libretro#1421]
I see i can use a button combination to open the MAME interal DIP SWITCH menù......... 

To my Pi4 i have a XBOX 360 Wired Controller that have the central HOME BUTTON........ this central button it's work and i can use to recall the retroarch hotkey like HOTKEY + START to close retroarch or HOTKEY + SELECT (in my case) to open the retroarch GUI.

In my case i have try to SET a combination like HOME BUTTONS + X or Y for open the MAME DIP SWITCH menù but apparently there's an issue. the core does not seem to recognize this button and i can't bind it to anythigs.....

How it's possible........

**Comment by mahoneyt944** [comment]
The core doesn't support this button, I've asked Libretro about this before. No support for it

**Comment by DjDiabolik** [comment]
Ah ok........ it's a know """ issue """... look the three consecutive " because it's not a really issue at this point :)

**Comment by MistyDreams** [comment]
Its an retroarch issue unfortunately the retropad is based on a snes pad that did not have this button. You would be better off posting an issue on retroarch github to gain some traction as its not something core can fix.

**Comment by DjDiabolik** [comment]
@MistyDreams mmmmmmmmm ok i can try but it's strange because this button can be assigned for hotkey combination....

Oh... i my case i have a Retropie installed on a Rasp Pi4 and whit default hotkey HOME BUTTON + X open the retroarch GUI... HOME BUTTON + START exit from games/retroarch  :)

**Comment by DjDiabolik** [comment]
I thinks it's corrent place............. see some news in next days.

**Comment by DjDiabolik** [comment]
@mahoneyt944 and @MistyDreams 

about 10 minutes ago i have made some test whit my ARCADE JOYSTICK DIY KIT (build myself whit 0delay usb and sanwa whit 10 buttons).
I have 8 playable buttons one for start and one for select.......... using RETROPIE whit this joystick on emulationstation i have bind the SELECT and the HOTKEY button to same button.

Apparently whit this when i press SELECT i obtain +1 coin and if i press SELECT+ START i can exit from retroarch thanks to hotkey.
Apparently whit this arcade joystick i can also open the Retroarch GUI using SELECT + Y button (the button chosen as X in retroarch). Whit SELECT + X i obtain a RESET of emulation.

But it's so curios...... whit this joystick arcade i can bind all button to made how combination i want to open the internal MAME dipswitch menù and all button it's be recognized.

It's so made this strange....... because it's not works for Xbox wired controller ? It's the home button it's not a "real" button ?

**Comment by mahoneyt944** [comment]
Hotkeys are used by RetroArch which includes the home button in some instances. Within mame2003-plus (the core) the home button is not supported because this button is not passed to the core for RetroArch

**Comment by MistyDreams** [comment]
```
https://github.com/libretro/RetroArch/blob/078f712b34e4f845a064022ca2e00cfdff5e5956/libretro-common/include/libretro.h#L188-L212 
```
these are the only buttonss cores have access to its a frontend/backend issue

**Comment by DjDiabolik** [comment]
@MistyDreams so interesting...... does this mean that anyway we have a software limit of 10 buttons that can be used on retroarch? 

So, If i add an addictional buttons to my DIY arcade joystick (since in the 0delay usb converter the installable and usable buttons are in theory 12) could there be the risk of not being able to use this eleventh button?

Sorry for my BAD English......

**Comment by MistyDreams** [comment]
Pretty much again its a design choice you would need to  discuss this with RA devs.

**Comment by DjDiabolik** [comment]
@MistyDreams yeah i know...... every direction we can assimilate it to a button :)

look this is very similar to those I have used for my arcade stick diy:
https://www.vic-20.it/wp-content/uploads/2022/04/interfaccia-usb-arcade-zero-delay-1-player.jpg

It's 12 buttons plus the 4 for direction........ also here 16 buttons/function :)

so i think using my arcade stick i can use all combination i want......


Returning IT about HOME Button of Xbox PAD:
I'm just curious....... if i attach my Xbox 360 pad on a windows pc i'm not sure if the "HOME" buttons is recognized as a normal buttons like other in the pad ?

**Comment by MistyDreams** [comment]
I sont use windows try bind it and check

**Comment by DjDiabolik** [comment]
@MistyDreams 

i have attach my current Xbox GamePAD to my windows 10.......... this is its configuration panel:

![immagine](https://user-images.githubusercontent.com/9040397/184408639-b989182d-6ad4-454e-b1dd-bae5f67602ab.png)

I can confirm also on windows........ if i press HOME Button on Controller i can't see any button feedback on screen........

So also on windows i thinks the HOME button it's can not be BINDED to anythings.......

**Comment by mahoneyt944** [comment]
Yes it would be. The core documents are a little outdated though. The meat of everything is there but it needs scanned through / updated. I know things like the core options and i believe lightgun support from what I remember are a bit behind. Though, now that our core options include descriptions idk if we really need to spell them out elsewhere too, but doesn't hurt I guess.

**Comment by mahoneyt944** [comment]
@DjDiabolik I'm going to close this since we can't really do anything about this at the core level, though you may want to reach out to the RetroArch repository directly and they may be able to give you a more detailed response about the API.

**Comment by DjDiabolik** [comment]
@mahoneyt944 my issue open on retroarch it's stalled whitout any answer........ you told me they had ignored similar discussions in the past :)
Ok i'm agree about closing this "issue" :)

**Comment by DjDiabolik** [comment]
Thanks for every info i now learn right here :)
