### ISSUE TITLE
mutiple definitions errors

### ISSUE THREAD

**Issue by kurrono** [libretro/mame2003-plus-libretro#1436]
Is there a way to fix that?
like when compiling u can use  game_playing = true;    bool game_playing = false;
and 2 more of these: game_playing = true
so acutally 4 timess... i need it for rastan and narc to make them play custom osts... is there a way i can fix that on the makefile or that is on msys?

**Comment by mahoneyt944** [comment]
This core uses a different system for ost which eliminates all the "game playing" variables. You would need to add these as unique variables for each game.
