### ISSUE TITLE
Ddragon clock speed

### ISSUE THREAD

**Issue by mahoneyt944** [libretro/mame2003-plus-libretro#1448]
@arcadez2003 @MistyDreams 
Noticed the high score table is glitched in attract mode and the game crashes when you beat the final boss. Seems this was something we looked into before just wondering if either of you recall if there's a viable fix here?
https://github.com/libretro/mame2003-plus-libretro/commit/4a79423f0b55d52c3e8627a143fce9700c712516

![ddragon-220913-061253](https://user-images.githubusercontent.com/49591133/189875610-c35193d5-d6e3-45cd-9e45-6e6bff04ab49.png)
![ddragon-220913-051841](https://user-images.githubusercontent.com/49591133/189875612-1ce25e19-351f-426e-acff-4e893ba383af.png)

**Comment by arcadez2003** [comment]
These are the changes we require in order to fix the issues with Double Dragon

https://github.com/arcadez2003/mame/commit/b58b2b3fa4538478ade7b97b26eec3222aa77a17

However as you can see it's not a two min job and i have zero time to work on anything at the moment.

**Comment by arcadez2003** [comment]
However as @MistyDreams suggested we can roll the driver back to a previous version but the game will still have the
same ole issues.

**Comment by mahoneyt944** [comment]
Maybe there's a compromise in what we have. I'll try some things out.

**Comment by mahoneyt944** [comment]
9a6c6da tried this already, fixes the crash but causes lots of game glitches

**Comment by mahoneyt944** [comment]
Did you try using that with `activecpu_get_pc() == 0x6261`?

**Comment by mahoneyt944** [comment]
So activecpu_get_pc() == 0x6261 works with the Japan version. Is this to say with the correct value the parent would also work?

**Comment by mahoneyt944** [comment]
Sorry my comment was confusing, I meant should we use `!dd_sub_cpu_busy` with `activecpu_get_pc() == 0x6261` also since `activecpu_get_pc() == 0x6261` does fix the glitches as you noted with the girl at the end. Possibly combining them we can get the best of both worlds? I'd be curious to test that combination

**Comment by mahoneyt944** [comment]
Just tested and it seems all good now, no crash after two tries. There is some oddity with the game timing though unrelated to the latest commits. I notice speed ups and slow downs. Not sure if this is how the game is or something else needed. It's most noticable with the players movement. Seems like with more enemies it gets slower in some parts. One on one fights seem faster.

**Comment by arcadez2003** [comment]
Many debates around this over the years regarding the slowdowns in Double Dragon i wont go over those other than to say 
i did push a commit several years back which tweaked the cpu clocks to get rid of the slowdown which tends to happen
when anymore than two enemies are on the screen at any given time.

**Comment by mahoneyt944** [comment]
It looks like ddragon clock got reverted here, https://github.com/libretro/mame2003-plus-libretro/commit/4a79423f0b55d52c3e8627a143fce9700c712516

**Comment by mahoneyt944** [comment]
4bab1ffc431493bbd39f7ab236a1b7105048b338 added back in to test

**Comment by mahoneyt944** [comment]
That definitely removes the slow down but it's too fast in parts. Like the intro, they run off screen etc. I found this https://github.com/libretro/mame2015-libretro/commit/5baa045d9d0ae7cb5f65674231556c4763bdb590 

need to look into it further but I'm getting some rest now.

**Comment by arcadez2003** [comment]
Yip Double Dragon II was the same as i recall at the end of the day i think the games were too advanced for the hardware.
anyhow if solution cannot be found which does not negatively impact the games in other ways then we'll just have to
leave as is.

**Comment by mahoneyt944** [comment]
Reverted the change. PR whatever you think will work best.

**Comment by mahoneyt944** [comment]
a3aec9be5069f8888e8ae24d545ca1704138ee78 pushed the change.

I notice the slow down when you get to the 2nd boss fight (where the conveyor is running). You end up with lots of enemies at this point 3 or 4 I think.

I wonder if there's a modifier we can use that would be more dynamic to the enemies currently on screen. That way when we get more enemies we can adjust accordingly then return to normal after knocking down some foes.

**Comment by mahoneyt944** [comment]
Yeah but it's kind of counter active. If you speed it up to get the bad slow downs right, the rest of the game plays too fast. Might just be how this one is.

Ddragon2 might need the same update though based on the commits arcadez previous did.

**Comment by mahoneyt944** [comment]
Just those added or the full range?

**Comment by mahoneyt944** [comment]
>going through the history arcadez reverted the ddragon2. Overclocking can cause issues

I was wondering if it was just the audio that was an issue with the overclock. Maybe the main cpu would be ok.

**Comment by KMFDManic** [comment]
@MistyDreams @mahoneyt944 @arcadez2003 Hope all has been well:)  Been a few chaotic months for me in reality:)  But, getting back in business, emulation wise.  I decided to dabble a bit in Double Dragon 1 and 2 fairly recently.  I noticed a bit of an anomaly, which of course we already know is existent in the original hardware/s.  In any case, it seems like this was cleaned up effectively on the FBNEO side, within the history of commits, particularly the OC ones.  I tested overclocking with 2003 codeset, and it always "still" slows down.  

https://github.com/libretro/FBNeo/commits/master/src/burn/drv/pre90s/d_ddragon.cpp

I am curious if any of the fixes added to FBNEO would be useful in the driver from 2003.  I did a test video showing ddragon2 with no slowdown, (requires overclock to be set to 200) even with several enemies on screen.  I could not replicate this on 2003, thus far.  But, I think we'd all love to have no slowdown double dragon ii, with overclock set to 200 on 2003 for non purists!:)

https://www.youtube.com/watch?v=yqXuJkWvBi4

**Comment by mahoneyt944** [comment]
@KMFDManic 
I find that the game speed runs fairly well in 2003+ except for when enemies are at a high count. I always suspected there maybe a way to effectively monitor the slowdowns and throttle at appropriate times as locking the over clock high all the time speeds up other parts of the game in a negative way. I assume the fbneo code was more or less a port from current mame or hybrid of, though their team would have to comment on those specifics.
