### ISSUE TITLE
Double dragon 3 - The Rosetta Stone (US) - ddragon3

### ISSUE THREAD

**Issue by Cibomatto2002** [libretro/mame2003-plus-libretro#1463]
Theses a graphics bug on one of the levels I forgot what level it is but it got fixed some time ago could this be fixed in MAME 2003plus? if not that's ok. I think the MAME it got fixed in is in the MAME info.

**** :MAMEINFO: ****

0.36b10 [Carlos A. Lozano, Richard Bush, Bryan McPhail]

Artwork available

Bugs:

- ddragon3, ddragon3j: Game over and ending music are missing. Augusto (ID 08417)

WIP:

- 22nd November 2020: Mr. Do - PapaShine took some time out and cleaned up the bezel and marquee for Double Dragon 3, both courtesy of BYOAC/CAG.

- 0.190: Soundlatch modernization. Use explicit buffering trigger in clone Double Dragon 3 - The Rosetta Stone (bootleg) [AJR].

- 0.151: hap fixed video frequency regression in DoubleDragon3 driver. Changed VSync to 57.444853 Hz.

- 0.150: Fixed gfx1 rom loading and VSync to 49.238445 Hz.

- 0.146: hap fixed mistakes with MCFG_SOUND_ROUTE in MCFG_SOUND_MODIFY, causing double routing (louder volume + soundchip showing up twice in the sliders menu).

- 0.135u2: Fabio Priuli added driver data structs to the Double Dragon 3 driver.

- 0.133u1: Renamed (ddrago3p) to (ddragon3p), (ddrago3j) to (ddragon3j) and (ddrago3b) to (ddragon3b).

- 0.131u1: MooglyGuy merged memory maps in the Double Dragon 3 driver.

- 0.129: Creamymami fixed clone 'Double Dragon 3 - The Rosetta Stone (prototype)' gfx ROM loading. Mamesick fixed debug assertion in Double Dragon 3 driver.

- 0.128u7: Guru added clone Double Dragon 3 - The Rosetta Stone (prototype). Improvements to DoubleDragon3 driver [Mamesick]: Converted driver to be fully scanlines based using timers. Updated driver to new video screen raw parameters. Hooked up interrupts. Changed 68000 CPU1 clock speed to 10MHz, OKI6295 to 1056000 Hz and VSync to 57.444853 Hz.

- 28th October 2008: Guru - A supposedly rare prototype Double Dragon 3 PCB arrived over the past few weeks. Thanks to Smitdogg.

-  9th July 2008: Mr. Do - Double Dragon 3 bezel, scanned by Anoid.

- 0.125u6: Sonikos added dips location in all sets of Double Dragon 3. Added the missing dips (now are 8x2) on clone 'Double Dragon 3 - The Rosetta Stone (bootleg)'. Adjusted the frame rate from 60 to around 57Hz as reported on MAMEtester ID 00417. Adjusted OKI frequency to 1MHz (according to recording on MAMEtester ID 00181). Adjusted the volume (according to recording on MAMEtester ID 00181 and 01441). Added 4x 'Unused' dipswitch.

- 0.123u5: RansAckeR fixed Double Dragon 3 locks up immediately on Technos logo.

- 0.123u2: Kevin Eshbach fixed some incorrect rom dumps for Double Dragon 3 (some of the dumps were based of the bootleg and not the original) and updated the name and location to actually match that of a real board.

- 0.109u1: Corrado Tomaselli added clone Double Dragon 3 - The Rosetta Stone (Japan). Changed visible area to 320x240.

- 0.100u4: Mamesick merged MACHINE_DRIVER (ctribe) with (ddragon3).

- 0.97u4: Mamesick adjusted volume balance in Double Dragon 3.

- 0.97u1: Pierpaolo Prazzoli fixed tilemaps and sprites in Double Dragon 3.

- 0.77u2: Fixed dipswitches. Removed coin slots 3 and 4.

- 16th November 2003: Curt Coder fixed input ports in the Double Dragon 3 driver.

- 0.71: Added 6x 'Unknown' dipswitches. Changed description to 'Double Dragon 3 - The Rosetta Stone (US)'.

- 0.60: Added prom ($0).

- 27th May 2001: David Haywood fixed Double Dragon 3 from skipping through the cut scenes.

- 20th November 1999: Phil Stroffolino fixed the input ports in Double Dragon 3 and Combatribes.

- 14th November 1999: Bryan McPhail fixed Double Dragon 3.

- 0.36b10: Carlos A. Lozano, Richard Bush and Bryan McPhail added 'Double Dragon 3 - The Rosetta Stone' (Technos 1990) and clone (bootleg). Known issues: Double Dragon 3 bootleg has some misplaced graphics, but this is how the real thing would look. Double Dragon 3 original cut scenes seem to fade a bit fast?

- 20th November 1999: Phil Stroffolino fixed the input ports in Double Dragon 3.

- 13th November 1999: Phil Stroffolino sent in WIP driver for Double Dragon 3, but working.

**Comment by arcadez2003** [comment]
This one and then another to sort the Combat Tribes might be the best bet........

0.97u2: Pierpaolo Prazzoli added priorities and fixed 3rd level in The Combatribes.
0.97u1: Pierpaolo Prazzoli fixed tilemaps and sprites in Double Dragon 3.

**Comment by Cibomatto2002** [comment]
I will make a video sorry about that.

**Comment by arcadez2003** [comment]
> I will make a video sorry about that.

Well why not just update to the latest build and see if some small changes im about to make sort the problems.

**Comment by Cibomatto2002** [comment]
i will try to update later tonight i'm not at home right now. thanks for your time on this. 

here is the video
https://www.youtube.com/watch?v=WFeKJ30nhQo

**Comment by Cibomatto2002** [comment]
that fixed it thanks.

**Comment by arcadez2003** [comment]
Nae worries im glad it's sorted however i'll likely need to give The Combat Tribes a whirl to make sure noting broke
in that games as tey share the same video code, but outta the two games that is the one i'd prefer to be playing..

PS have you tried the Japan version of Double Dragon 3 it has many gameplay changes over the USA set.

**Comment by Cibomatto2002** [comment]
No I have never tried the Japan set I will try it.

**Comment by arcadez2003** [comment]
Here are the diffs in the Japan version.......

The Japanese version discards the weapon shops completely from the game. Instead, the game asks the player to select from the 4 character types available when they begin (Lee, Chin, Urquidez or Oyama). The one-armed stand head-butt and the hurricane kick are available as part of the default moveset, but the hurricane kick is made hard to execute. While controlling one of the Lee brothers, a nunchaku or a sword can be found on the floor in certain stages. The first stage is slightly re-arranged, with the starting point moved in front of the Power Records store and the conveyor belt inside the warehouse removed.
