### ISSUE TITLE
Quartet (Rev A, 8751 315 -5194)

### ISSUE THREAD

**Issue by Cibomatto2002** [libretro/mame2003-plus-libretro#1476]
Just wondering if this game could get fixed if not it's ok

0.227: David Haywood fixed incomplete protection hookup in Quartet, fixes the moving floors that appear after the 15th stage are not displayed.

**Comment by arcadez2003** [comment]
Your not the first to ask about this unfortunately the fix cannot be applied here as we dont have the I8051 CPU core 
that is the CPU these games use via their protection MCU and that's what fixes the bug you mentioned 

Without it we're dead in the water, but it's not bad news there is one unprotected set which plays fine in this core...

GAME( 1986, quartt2j,  quartet,  quartet2, quartet2, 0,        ROT0,   "Sega",    "Quartet 2 (unprotected)" )

**Comment by Cibomatto2002** [comment]
Ok thank you for your time.
