### ISSUE TITLE
Auto Frameskip options are not working well

### ISSUE THREAD

**Issue by schmurtzm** [libretro/mame2003-plus-libretro#1482]
Hi, The Frameskip feature is great, it seems to work fine with fixed values and really improve the playability of demanding game on low CPU (I mainly use Mame 2003 Plus on Miyoo Mini, a little Linux handheld).

On last dev versions (b2b642c) the auto frameskip options are able to freeze the screen. 
It happens on the Miyoo Mini as soon as I use one of three "auto" frameskip options.
I can also reproduce on PC (Windows) when I use `auto agressive` or `auto max` (on PC it works with "auto" but slower than without frameskip).

The auto frameskip options was already malfunctioning on old release (8f1498fff) but it wasn't freezing.

**Environnement :** 
Windows or Linux
core build : last current (b2b642c)
Retroarch 1.10.3 or later

**Steps to reproduce :** 
- Any game (I'm making tests with "ninja baseball bat man" as it require frameskip on the Miyoo Mini but same behaviour with "1943".
- Run game and compare "auto" frameskip options to fixed value frameskip options.  (fixed values are a lot more efficient, auto value is able to slow down games)
- "Auto max" frameskip should systematically freeze
‎
‎
Any plan to improve the auto frameskip options ?  May be the "auto" options should be disabled for now ?

**Comment by mahoneyt944** [comment]
I'm wondering if the device you're using is so low that auto options are just skipping none stop, skipping every frame or enough to appear frozen?

**Comment by mahoneyt944** [comment]
@schmurtzm did using the alsa driver solve your issue ?

**Comment by saulfabregwiivc** [comment]
It also happens on Wii builds.
"Auto" frameskip options on some cores (including test MAME2003+ builds) aren't working such well.

**Comment by mahoneyt944** [comment]
Please try again with the latest commits and resubmit an issue if it's still not working.
