### ISSUE TITLE
maxforce: issue with absolute coordinates?

### ISSUE THREAD

**Issue by StormedBubbles** [libretro/mame2003-plus-libretro#1483]
Hey,

I took a closer look at `area51` and `maxforce` recently and noticed some issues I didn't see before. The emulator cursor, which seems to line up with the shots without any service-menu tinkering, doesn't line up with an absolute mouse's position on the screen. These games do have calibration menus, but calibration doesn't solve the issue. After calibrating, a similar issue with misalignment between shots and line of sight still occurs.

The driver code in current MAME for these games appears to make an attempt at aligning the cursor to the shots without accounting for an absolute mouse's position. I am not fully familiar with the syntax in this older version of MAME and can't tell if the same is happening here. Would it be possible to scale the gun coordinates for these games so that better alignment with absolute mice (e.g., Sinden Lightguns) is possible?

**Comment by StormedBubbles** [comment]
I am so sorry. There was something external to the emulator causing an issue with my setup. I jumped the gun with posting this, as I am wont to do. Mea culpa. There are no issues 😅

**Comment by Widge-5** [comment]
Hey, I can corroborate this.  In maxforce there appears to be an issue with the lightgun alignment on the x-axis.  With crosshair activated in the core options, the lightgun appears to be well-aligned on the left side of the screen but on the right side the crosshair deviates away from aim, appearing more to the right than it should.  in-game calibration doesn't resolve this.
Area51 seems fine however.
I'm using a Sinden Lightgun on a Raspberry Pi.

**Comment by StormedBubbles** [comment]
Thanks! I need to keep better notes. What Widge described is exactly what I experience with `maxforce` with the same hardware. The calibration screen does not resolve the alignment issues.

`area51` can be properly aligned after careful calibration in the service menu.

**Comment by mahoneyt944** [comment]
5dd4a30500edc0b00c712750093aa287c9bb4ce2 should fix maxforce

**Comment by StormedBubbles** [comment]
Thanks so much! Maximum Force is indeed fixed. I deleted the nv file before testing again and found the new default calibration to be correct. Perhaps I should wait until @Widge-5 chimes in before closing the issue again 😆

**Comment by Widge-5** [comment]
Thank you @mahoneyt944 . I can confirm that maxforce is now well aligned with default nvram for me too.
