### ISSUE TITLE
The King of Fighters '99 crash on Android

### ISSUE THREAD

**Issue by Cibomatto2002** [libretro/mame2003-plus-libretro#1484]
Trying to get The King of Fighters '99 to run on the Retroid Pocket 3 and for some reason it will freeze then boot out of RetroArch  the game works on windows just fine here is a log.

Using old --libretro behavior. Setting libretro_directory to "/data/user/0/com.retroarch/cores/" instead.
RetroArch 1.12.0 (Git a50f9ba)
=== Build =======================================
Capabilities:  ASIMD
[INFO] Built: Nov 17 2022
[INFO] Version: 1.12.0
[INFO] Git: a50f9ba
[INFO] =================================================
[Input]: Found input driver: "android".
[Environ]: SET_PIXEL_FORMAT: RGB565.
[Core]: Version of libretro API: 1, Compiled against API: 1
[Audio]: Set audio input rate to: 48000.00 Hz.
[Video]: Set video size to: 1281x720.
Android EGL: GLES version = 2.
[EGL] Falling back to eglGetDisplay
[EGL]: EGL version: 1.4
[GL]: Found GL context: "egl_android".
[GL]: Detecting screen resolution: 0x0.
[EGL]: Current context: 0x7c4cca1ea0.
[GL]: Vendor: Imagination Technologies, Renderer: PowerVR Rogue GE8300.
[GL]: Version: OpenGL ES 3.2 build 1.13@5776728.
[GL]: Using resolution 1336x752.
[GL]: Default shader backend found: glsl.
[Shader driver]: Using GLSL shader backend.
[GL]: Stock GLSL shaders will be used.
[GLSL]: Found GLSL vertex shader.
Shader log: Success.

[GLSL]: Found GLSL fragment shader.
Shader log: Success.

[GLSL]: Linking GLSL program.
[GLSL]: Found GLSL vertex shader.
Shader log: Success.

[GLSL]: Found GLSL fragment shader.
Shader log: Success.

[GLSL]: Linking GLSL program.
[GLSL]: Found GLSL vertex shader.
Shader log: Success.

[GLSL]: Found GLSL fragment shader.
Shader log: Success.
WARNING: 0:13: Calls to any function that may require a gradient calculation inside a conditional block may return undefined results
1 compilation warnings.

[GLSL]: Linking GLSL program.
[GL]: Using 4 textures.
[GL]: Loaded 1 program(s).
[Joypad]: Found joypad driver: "android".
[Video]: Found display server: "android".
[OpenSL]: Requested audio latency: 128 ms.
[OpenSL]: Setting audio latency: Block size = 3840, Blocks = 6, Total = 23040 ...
[Display]: Found display driver: "gl".
[SRAM]: SRAM will not be saved.
[Playlist]: Loading history file: "/storage/emulated/0/Android/data/com.retroarch/files/content_history.lpl".
[Playlist]: Loading history file: "/storage/emulated/0/Android/data/com.retroarch/files/content_music_history.lpl".
[Playlist]: Loading history file: "/storage/emulated/0/Android/data/com.retroarch/files/content_image_history.lpl".
[Playlist]: Loading favorites file: "/storage/emulated/0/Android/data/com.retroarch/files/content_favorites.lpl".

[retroarch.log](https://github.com/libretro/mame2003-plus-libretro/files/10049805/retroarch.log)

**Comment by mahoneyt944** [comment]
Can you share the full log? Preferably in debug mode?

**Comment by Cibomatto2002** [comment]
[retroarch.log](https://github.com/libretro/mame2003-plus-libretro/files/10057655/retroarch.log)

**Comment by mahoneyt944** [comment]
Ok, I confirmed the crash on my android device as well. Looks like we are crashing before we reach Preparing emulated CPUs for execution.

**Comment by mahoneyt944** [comment]
I couldn't see anything abnormal at a glance.

**Comment by arcadez2003** [comment]
Might the problem be endian related.?? maybe with the protection decryption.??

**Comment by mahoneyt944** [comment]
Probably the decryption. Is it in the init or something? Just like mspactwin back when.

**Comment by arcadez2003** [comment]
Oh there is a huge whack of code sitting in machine neogeo.c / neocrypt.c all written with windows in mind back in the days
when an Android was usually the baddie in a sci-fi movie, but im only guessing here and this does look alot like a potential
rabbithole :)

Sometimes the type of neogeo bios used can also throw off a game maybe it's worth @Cibomatto2002 trying out a few
different types to see if kof99 will then bootup.

**Comment by Cibomatto2002** [comment]
I tried three different BIOS US, Europe and Japan. same thing.

**Comment by mahoneyt944** [comment]
I haven't had any issue with playing neogeo on my android device, so I wouldn't think it's an endian issue. @Cibomatto2002 tried multiple bios files so likely not that either. Hmm. Need more testing.

**Comment by mahoneyt944** [comment]
Kof99 works in mame2003, so we probably broke something in the updates sometime ago.

**Comment by mahoneyt944** [comment]
Didn't think of that. Should we edit the cheat list to shorten the description vs expand the size limit?

**Comment by mahoneyt944** [comment]
Also would be nice if we added some error logging to catch this. We could probably check the length before setting it. And log the overflow.

**Comment by mahoneyt944** [comment]
#1487 should prevent over flow, and fix this issue, however looking at how description is used later, maybe this DESC_MAX_LENGTH should be 255 instead? If I'm reading that right.
https://github.com/libretro/mame2003-plus-libretro/blob/15d060afeb5f4a0cd6c8d6fdfd09de34c43b1921/src/cheat.c#L9567

**Comment by mahoneyt944** [comment]
`DESC_MAX_LENGTH` is defined as 256. Which I'm using to declare `description[DESC_MAX_LENGTH]`. Then I'm also using `DESC_MAX_LENGTH` to restrict how many characters we read in when sscanf fills description. This means it can't overflow if the cheat file has a description that's larger, it just stops reading characters at 256. This in itself is enough to prevent a crash, but the size might not play nice when it's entered into entry->comment and used later.

**Comment by mahoneyt944** [comment]
Oh is it treating it as `%D` instead of `%DESC_MAX_LENGTH`?

**Comment by mahoneyt944** [comment]
This should do it. https://github.com/libretro/mame2003-plus-libretro/commit/d9c151c4d6fd07056445eebb5ca019617444d80a

**Comment by mahoneyt944** [comment]
What's the issue with hotgmck?

Also should we use a similar constraint with `name`? This also caps at 255, though I wouldn't think any would actually be that long but it would be a safer practice.

**Comment by mahoneyt944** [comment]
Oh dang I'll have to look at that

**Comment by mahoneyt944** [comment]
Yeah that's pretty ugly, is it a special character in the cheat?

**Comment by Cibomatto2002** [comment]
Thanks for getting kof 99 working why was this the only kof game that would not work? Could there be more neogeo games that will not boot?

**Comment by Cibomatto2002** [comment]
Thanks for telling me.
