### ISSUE TITLE
Space War (Leijac Corporation) and SPACE LASER there are no 2player butttons

### ISSUE THREAD

**Issue by kounabi22** [libretro/mame2003-plus-libretro#1499]
In Space War (Leijac Corporation) spcewarl.zip and Space laser spclaser.zip there are no 2player buttons and you cant add them.

**Comment by arcadez2003** [comment]
Seems some silly bugger removed em 

0.90u4: Steve Ellenoff added missing Player 2 controls to clone Space War (Leijac). Added 'Coinage' dipswitch.
0.70u2: Removed 2nd Player.

I'll see about adding em back in later

**Comment by arcadez2003** [comment]
Here ya go all you need to do is update to the latest core and you'll likely need to delete your previous save file
for this game so the new inputs will register correctly

https://github.com/libretro/mame2003-plus-libretro/commit/8f689fd8c9d926ae2146ffd1856675d7ce2165fd
