### ISSUE TITLE
Twin Bee Yahhoo! (tbyahhoo) bad rom check at start

### ISSUE THREAD

**Issue by kounabi22** [libretro/mame2003-plus-libretro#1503]
Twin Bee Yahhoo! gives a bad error at start of boot check rom of game.

**Comment by mahoneyt944** [comment]
I can't replicate this error, are you sure you're using the correct romset for mame2003-plus? If so, please post a log to review.

**Comment by arcadez2003** [comment]
@mahoneyt944 this sounds like one of those eeprom errors you get with some Konami games, the solution is to 
turn on the service mode let the game boot into it then save and exit i think @markwkidd added a bootstrap for
several of these games Run And Gun for example

**Comment by kounabi22** [comment]
yes deleete cfg and nv worked..

thanks.

**Comment by mahoneyt944** [comment]
I was able to boot into it just fine though when I tried. Bootstraps are easy enough to implement if need be, but didn't seem like the issue.

**Comment by mahoneyt944** [comment]
Ahh I see clearing your cfg and nv fixed the issue, maybe you had a corrupt one or something.
