### ISSUE TITLE
Mr. Do's Castle not respecting Lives dipswitch

### ISSUE THREAD

**Issue by SapphireDrew** [libretro/mame2003-plus-libretro#1508]
Mr. Do's Castle, `docastle` and `docastl2` (*only ones I've tested*), do not respect the Lives dipswitch (*Difficulty is also suspect as I don't notice any difference between Easy and Hardest*), defaulting to 2 lives no matter what. A quick google search shows that Mr. Do's Castle is "VERY timing sensitive, and dipswitch reading will fail if timing is not completely accurate."

**Steps to Reproduce:**

* Load `docastle` or `docastl2` with the MAME 2003-Plus core
* Access MAME Menu and select Dipswitches
* Adjust lives
* Play game

**RetroArch Version:** 1.10.3 64-bit (Windows 10)
**MAME 2003-Plus Core Version / Build:** 918f94a

**Comment by arcadez2003** [comment]
We likely just need these fixes from later MAME......

0.92: Workaround for dipswitch problem in Mr Do's Castle [Nicola Salmoria].
0.79u1: Fixed dipswitches.

**Comment by arcadez2003** [comment]
Alright the hard way to do this eg update all the mem maps add in the missing IO Port map then update all the inputs
or the easier way ie just splice in the code we need, as it happens i've taken the easy road but the inputs and dips
for Mr Do's Castle now function correctly.

I think Do! Run Run might have the same issue as the fix from MAME92 mentions that game also, anyway i'll need to
go over the code again tomorrow to make sure it's all good before porting across to here i may as well fix the sound
for Indoor Soccer while im at it.

@SapphireDrew thanks for the bug report all being well i should have a fix for you shortly.

Regards.

**Comment by SapphireDrew** [comment]
No problem. And yeah, can confirm Do! Run Run is having the same issue.
![Untitled](https://user-images.githubusercontent.com/65051071/209889465-9efbb52c-38fb-44bf-bc95-bc24cd653623.png)

**Comment by arcadez2003** [comment]
Everything should be fine now.......
https://github.com/libretro/mame2003-plus-libretro/commit/eba3d6144eab70b1fd772504cea06bfa2004bf70

**Comment by SapphireDrew** [comment]
@arcadez2003 We got a problem. Something about the fix for this broke compatibility with Mr. Do's Wild Ride - `dowild`. Since you said you were borrowing code from a later MAME, I take it that means we need one from a newer reference set now? RetroArch kicks me back to the menu complaining about missing or corrupted files. Game ran perfectly fine in the previous build.
