### ISSUE TITLE
Problems with tma1-c-6k_e.6k file for Mario Bros. (US, Revision E)

### ISSUE THREAD

**Issue by ZOMBIE39** [libretro/mame2003-plus-libretro#1515]
Based on the results after scanning the latest mame2003-plus.xml.
It should be impossible to have a different size and still have the same CRC, so I would like to ask if the size is not marked correctly or the CRC is not marked correctly.
![QQ截图20230103210638](https://user-images.githubusercontent.com/37724369/210363270-7c9fe7cd-f33e-4433-b9f9-bcddd7805139.png)

**Comment by arcadez2003** [comment]
Aye easy to do i've done it myself looks like we need it like this for our ole core.......


	ROM_REGION( 0x1000, REGION_CPU2, 0 )	/* sound */
	ROM_LOAD( "tma1-c-6k_e.6k",   0x0000, 0x1000, CRC(06b9ff85) SHA1(111a29bcb9cda0d935675fa26eca6b099a88427f) )
