### ISSUE TITLE
Any change little robin and yoyo spell to be supported?

### ISSUE THREAD

**Issue by kounabi22** [libretro/mame2003-plus-libretro#1517]
Any change little robin (littlerb) and yoyo spell (yoyospel) to be supported?

**Comment by arcadez2003** [comment]
Same games more or less but Little Robin is the complete final version, the workload required would be high as
99% of the code would have to be refactored i personally dont have the time nowadays to take on a mammoth task
such as this.

**Comment by kounabi22** [comment]
i see thanks for the info.
