### ISSUE TITLE
Updating the Catver/Catlist ?

### ISSUE THREAD

**Issue by 4shpool** [libretro/mame2003-plus-libretro#1519]
Have asked this (before) in the retropie Forum: https://retropie.org.uk/forum/post/285247 and was redirected here by arcadez2003 advice -> As the catver.ini data wasn't updated in a while and I have just brought it up 2 date for my personal use (unless I missed something, its 53 roms added and 2 renamed (20230105)), would it be Ok if I fork the repo and commit a PR? And if so, should I be aware of some styleguide in regards of the catver.ini? The old one here isn't strict alphanumerical (may it be clones under parents, or whatsoever) whereas current datfiles (from mamedev webside, not generated by mame) seem to be sorted alphanumerical ? Of course, as my contribution would just be short-termed for this and maybe a few follow-ups, I can understand and accept a "please don't open a fork&PR".

**Comment by mahoneyt944** [comment]
Keep in mind that our romset is custom, you can't just update it to the latest mame version. Many naming conflicts exist. A while back I made a small program for scanning, comparing and building a mostly accurate list and I still had to hand edit some odd ball ones.
