### ISSUE TITLE
Metal Hawk (WORLD)

### ISSUE THREAD

**Issue by Cibomatto2002** [libretro/mame2003-plus-libretro#1521]
This game needs to buttons mapped to the controller from the keyboard the R and F key those keys let's you go up and down. This is not a mame2003plus bug I thought I would post here anyways because I don't want to use a keyboard.  I'm going to post this over at MAME to.

**Comment by Cibomatto2002** [comment]
Here is what mane said 

https://github.com/mamedev/mame/issues/10817

**Comment by mahoneyt944** [comment]
I assume the original cabinet had a lever for altitude (up and down position). I would think this lever would hold it's position when you're not physically holding it? But I'm unsure. If so, any analog stick which returns to center would be difficult to play with. 

For actual retropad use. I'd probably map L and R to this which leaves your right hand free to fire.
![metlhawk-230109-120036](https://user-images.githubusercontent.com/49591133/211366760-6dd21c86-d703-4142-936d-173734c3ef3d.png)

**Comment by Cibomatto2002** [comment]
Thanks for your help I will try it later tonight when I get home from work

**Comment by Cibomatto2002** [comment]
That fixed it.
