### ISSUE TITLE
battle ranger and bloody wolf no music

### ISSUE THREAD

**Issue by kounabi22** [libretro/mame2003-plus-libretro#1528]
battle ranger and bloody wolf  have no music only sound effects

**Comment by mahoneyt944** [comment]
Both these games have imperfect sound and imperfect graphics in this core. I'm not sure if a fix is available or not.

**Comment by mahoneyt944** [comment]
@kounabi22 though please verify that you have stereo sound working (left and right speakers). I tested battlera and I have music, so likely your only getting half the sound through one speaker.

**Comment by kounabi22** [comment]
i have try some other emulators lr-mame , fbneo they have musc but its terrible..
i test sound its ok.

**Comment by mahoneyt944** [comment]
So the sound is working now?

**Comment by kounabi22** [comment]
only on fbneo and lr-mame still no music on mame2003plus

**Comment by arcadez2003** [comment]
Just tested Bloody Wolf using both my 78 and 84 MAME cores and can confirm the game has full sound and music
so it's not a code issue our end.

**Comment by kounabi22** [comment]
still nothing.....the only sound i can hear is the effects of the died sprites.

**Comment by mahoneyt944** [comment]
I wonder if fbneo is doing something different with the sound. I'm fairly sure our core has effect sounds on one speaker and music on the other. So i I would suggest auditing your audio output. It the past I have suggested Pi users to try running the sound through auxiliary jack instead of HDMI to verify with a good set of headphones

**Comment by kounabi22** [comment]
retropie on raspberry pi4

**Comment by kounabi22** [comment]
i use hdmi output..

**Comment by mahoneyt944** [comment]
@kounabi22 have you tried using the headphone jack with a trusted pair of headphones? Sounds like a speaker or HDMI wire issue.

**Comment by kounabi22** [comment]
test a second hdmi cable ,problem exist, i will try headphone.

**Comment by mahoneyt944** [comment]
@kounabi22 any update on this?

**Comment by kounabi22** [comment]
still same problem with 3,5 jack

**Comment by mahoneyt944** [comment]
Not sure what to advise you. Seems to be something with your setup specifically.

**Comment by Riddler1** [comment]
Not sure if this helps but here is a video example....https://youtu.be/vlNm1naofFk

raspberry Pi4
Headphone jack audio out
Battlera rom
mame2003plus latest build (commit f992c9a)
