### ISSUE TITLE
Enabling / Disabling Shifter Toggle (without XML .cfg files)

### ISSUE THREAD

**Issue by neildavis** [libretro/mame2003-plus-libretro#1529]
Looking for help with racing games which use two-way toggle switch gear shifters (e.g. 'Turbo'.) By default the shifter is mapped to a single input button with 'low/high toggle' behavior. 

If you want to change this to make it e.g. 'active high' (high gear only when pressed, otherwise low gear) or 'active low' (the opposite) the only way I'm aware of to do this was to edit the `.cfg` file for the ROM, since the functionality is not exposed through the inputs menu UI. This is explained in the [MAMEdev documentation](https://docs.mamedev.org/advanced/shiftertoggle.html)

However, since mame2003-plus-libretro uses a binary format instead of the later XML format, this is not possible either? I noted #1243 was closed as 'out of scope' so is there an alternative way to achieve this? 

For now my workaround is to rebuild the core with a modified input port definition to remove the `IPF_TOGGLE` flag, but a config option would be preferable.

Any help would be greatly appreciated, and many thanks for maintaining this core!

**Comment by mahoneyt944** [comment]
So essentially you want constant low gear except if high gear is active. I'm not sure if we have that functionality present but could probably make an easy mod. @MistyDreams any thoughts on this?

**Comment by mahoneyt944** [comment]
Here's a test branch I made real quick. This defeats the toggle, could make this condition a core option?
https://github.com/libretro/mame2003-plus-libretro/compare/Test

**Comment by mahoneyt944** [comment]
The default core option would enable the toggle as is now.

**Comment by mahoneyt944** [comment]
Yeah I'd like the icon option as well. It annoys me playing pole position. Especially when that toggle seems to misbehave sometimes.

I'm not sure how else to globally allow this option without diving into every driver.

**Comment by mahoneyt944** [comment]
I didn't consider the service menu, that would also defeat that. I feel like most users would never switch this option to become an issue. But it could be present for those who do.

**Comment by mahoneyt944** [comment]
Maybe we could add a cfg setting to enable/ disable this per input?

**Comment by neildavis** [comment]
Wow guys, thanks for the super quick responses - I really wasn't expecting that! Seems like I've opened the proverbial can of worms here

I'm no expert on this code base, but I think a 'per input' solution sounds like the way to go. This is the approach taken by the MAMEDev guys with their [XML `.cfg` edit](https://docs.mamedev.org/advanced/shiftertoggle.html) solution. 

Globally changing every toggle sounds like it could backfire. Are there any games with more than one toggle input where you might want a mix of behaviors? I also feel that the people who would make use of this option are also likely to be making use of the service menu - i.e. those putting it into custom cabs and/or using custom controller hardware etc? 

But like I say, no expert, just my 2c :)

**Comment by mahoneyt944** [comment]
Maybe add a cheat input port for each input using ipf_toggle? That way you could disable the toggle for the specific input you want and it would save in the cfg?

**Comment by mahoneyt944** [comment]
Fair enough, easy to revert if there's any issues.

**Comment by mahoneyt944** [comment]
@neildavis try this out, I recommend only disabling the new core option when needed though. https://github.com/libretro/mame2003-plus-libretro/commit/a3c987880c4342a0ca3b9a03340ed97defa4d387

**Comment by mahoneyt944** [comment]
@MistyDreams we could also check for `IPT_SERVICE`, that would likely handle most of those conditions I'd think.

**Comment by mahoneyt944** [comment]
Sounds good.

**Comment by neildavis** [comment]
@mahoneyt944 [`a3c9878`](https://github.com/libretro/mame2003-plus-libretro/commit/a3c987880c4342a0ca3b9a03340ed97defa4d387) works well, at least in 'Turbo' which is all I tested and where I'm focused right now.

Of course it only works one way (gear H unless pressed rather than gear L unless pressed) but that's going to be just fine in the vast majority of cases since anyone setting up custom shifter hardware can just choose which 'end' is the button and/or choose to use a NO/NC switch appropriately etc.

Great work and huge thanks for such a quick turnaround.

**Comment by mahoneyt944** [comment]
@neildavis great. If you find any issues with using it be sure to open another issue. I'll mark this as complete for now.
