### ISSUE TITLE
Lockload wip

### ISSUE THREAD

**Issue by mahoneyt944** [libretro/mame2003-plus-libretro#1532]
Started some work on lockload. Seems like I have all the inputs working, in the service menu at least, and I added crosshairs which may not be entirely accurate at this point but it's getting there... got improvements in the sound as well. There's an odd gun calibration required for this game, but I can seem to get anywhere with it. There manual says when the calibration is off you should hear the gun fire but not register on the screen. All I seem to get is a flash on the screen but no gun fire sound. I can't tell if the trigger is working properly or if it needs to go through calibration first.

I need to look into the trigger input, may not even be hooked up properly and figure out this calibration. Most of the changes were committed awhile ago and this branch adds the crosshairs.

https://github.com/libretro/mame2003-plus-libretro/compare/Patch

Anyone willing to take a look? If we figure out the calibration, I'll bootstrap it.

**Comment by mahoneyt944** [comment]
Looks like we might be missing some graphics. The targets for calibration are missing.

**Comment by arcadez2003** [comment]
From memory on the MAME chat some years back Kale thought there was an undumped device maybe a dongle which
Lock and Loaded had connected to the PCB in order to handle the calibration hence it cant be setup correctly.

**Comment by mahoneyt944** [comment]
Merged #1543 for now. Seems there's still work to be done though. From notes in newer mame, we need to get the trigger registering, I believe this is due to vblank timings. Also there seems to be a very restricted range for the lightgun, even the documentation writes this off as odd. And lastly in calibration mode we seem to me missing the target graphics to calibrate with, likely an easy fix.

**Comment by Widge-5** [comment]
Just want to add something of my experience with lockload.  In current mame at least, it's impossible to calibrate Player 2.  When you shoot, a grid flashes on screen which is normal, but if P2 shoots too close to the bottom of the screen the grid appears then won't disappear and it crashes the game.  One of the calibration points is in this affected area, so you can't calibrate player 2 unless you deliberately aim higher than that point, defeating the purpose of the calibration.
I'm using a Raspberry Pi and Retroarch if it's relevant.  I don't know if this is an issue in 2K3+ but I understood it to be an issue for this game across all mames at present so thought it would be worth mentioning.
