### ISSUE TITLE
Enable `share_xy` and `swap_xy` for `IPT_PADDLE` games

### ISSUE THREAD

**Issue by wn2000** [libretro/mame2003-plus-libretro#1550]
I know that the real "paddle" and "dial" hardware are different, maybe in the sense of ABS_X vs REL_X.

But in the emulator both paddle games and dial games are controlled by some mouse-like controllers.

The `dial_share_xy` option is particularly useful for playing 2P games, when two spinners are wired as a single mouse device and act as its X/Y axis.

But currently the options `dial_share_xy` and `dial_swap_xy` only show up in the UI and take effect for DIAL games and not PADDLE games.
An example is the game Warlords. It's technically a Paddle game, but can be naturally controlled by spinners. But those DIAL options do not show up in settings.

**Comment by mahoneyt944** [comment]
This will allow these options to show for paddle now as well. https://github.com/libretro/mame2003-plus-libretro/commit/d757c21d0f1305865c8a48657ccb0c7ff119d52b

**Comment by markwkidd** [comment]
Nice!

**Comment by wn2000** [comment]
Thanks for the quick fix!
I guess [this line](https://github.com/libretro/mame2003-plus-libretro/blob/0db1cbe704239089f4ab583cab0c0a957dad3e5b/src/inptport.c#L901) also needs to be changed?

**Comment by mahoneyt944** [comment]
This should do it.
https://github.com/libretro/mame2003-plus-libretro/commit/2bd4ba1be083e9a4a79cb8550444470fd6512fc1

**Comment by wn2000** [comment]
Thanks again!
