### ISSUE TITLE
The output image of spcfrcii is upside down

### ISSUE THREAD

**Issue by royfokk** [libretro/mame2003-plus-libretro#1552]
commit version cc2ddd54589b1e597cfd47a6f28f0751f7f64498

**Comment by arcadez2003** [comment]
The game is loading the correct way up screen wise for me, maybe it's a problem with your setup
anyway Special Forces II is a clone of Special Forces there are no gameplay diffs so if that set is
working correctly then your better sticking with it.

**Comment by arcadez2003** [comment]
Right so change to ROT270 and everything will be sorted i'll do it later

**Comment by arcadez2003** [comment]
https://github.com/libretro/mame2003-plus-libretro/commit/b0f3b7bd1009db0e21b7d63e8e01aab8ae5fcad6

**Comment by arcadez2003** [comment]
> cheers would have done it myself but dont have the repo anymore and one liners are are easier to do without a pull request. Reminds me I need to fix shootgal will need to fix some issue in the video driver for that though.

Nae worries i added Shooting Gallery it was fine on my core but as you changed the video code for
all games in dkong.c as you say some extra work might be required.

**Comment by mahoneyt944** [comment]
>pointer device or light-gun selected will stop all other controls working keyboard and joystick (due to the way its implemented)

Is this all games or this one on particular? Seems to work on Android but I'm using an on screen overlay for a controller. So it may differ

**Comment by royfokk** [comment]
spcfrcii is ok now. 
Should I close this issue?

**Comment by royfokk** [comment]
Thank you very much.

**Comment by royfokk** [comment]
Thank you very much.
