### ISSUE TITLE
Phoenix fixes backport

### ISSUE THREAD

**Issue by wn2000** [libretro/mame2003-plus-libretro#1557]
I see the `phoenix` driver still has the 0.78 original source.

There has been multiple fixes since then according to the [adb site](http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=phoenix), some notable ones (mostly audio, but having save state is super nice):

- 0.128u2: More Discrete module optimizations [Derrick Renaud]. This module optimizations speed up Phoenix 13%.
- 0.122u7: Changed 8085A CPU1 clock speed to 5.5MHz.
- 0.122u6: Phoenix and clones [Couriersud]: Video timing from schematics. Palette from schematics (resnet.h). No more colortable. Added save state. Changed visible area to 208x256 and VSync to 61.035156 Hz.
- 0.104: Derrick Renaud changed R22 to 470 ohm per real board in Phoenix discrete sounds. This should fix the remaining complaints with the discrete sound. The shot & explosion noise sounds still need discrete emulation.
- 0.103u5: Derrick Renaud tweaked Phoenix effect 2 sound to be more accurate matching oscilliscope data. Changed the Phoenix discrete clock rate to a fixed rate of 120000 allowing the simulation to be more accurate with less alaising noise at the cost of speed.
- 0.103u2: Hans Andersson fixed discrete sound effect 2 in Phoenix.
- 0.95u3: Derrick Renaud updated tone sounds in Phoenix to use discrete system. Added Discrete sound.

Is it possible to backport these from e.g. the mame2010 source?

**Comment by arcadez2003** [comment]
Well they hooked the game up to use MAME's discrete sound code rather than using samples as was
the case for many ole games over the years, sometimes this nets sound improvements for the games
while other times it's not really all that noticeable.. 

Certainly many people decided to just stick with the original samples for many of these games 
preferring how they sound vs using discrete sound as there will be noticeable differences.

Anyway our discrete sound is MAME80 or so from memory as another dev updated it some time ago
i know for a fact the discrete code in MAME has changed alot between then and the first commit you
pasted above circa MAME95 or so.

So we'd need to firstly update the discrete sound and then every game driver or sound core using it 
and then we'd need to test all the games connected to this to make sure there is no breakage in other
words a hell of alotta work for maybe minimal improvements in the sound dept for Pheonix and then
as i said some users will likely not thank us for doin so.

**Comment by wn2000** [comment]
Thanks for the info about the discrete sound code. Totally understandable.

Reading the logs on the adb site, it seems samples are no longer used for Phoenix. So is it already using the discrete sound, just the older version of it?

- 20th March 2000: Juergen Buchmueller fixed some SN76477 and Phoenix sound bugs.
- 0.36RC2: Rewritten sound emulation in Phoenix, samples are no longer used [Juergen Buchmueller]. Added TMS36XX sound.
- 12th March 2000: Juergen Buchmueller sent in a sound core for TMS36xx sound chips emulation and modified Phoenix, Pleiads, Naughty Boy, Pop Flamer and Monster Bash to use it. Phoenix samples are no longer used.
- 9th March 2000: Juergen Buchmueller sent a preliminary Phoenix analog sound driver.
- 0.36b7: Added Custom sound.
- 0.35b11: Richard Davies fixed tune in Phoenix.
- 0.30: Brad Oliver support music in Phoenix, via samples.
- 0.26: Andrew Scott provided a better sound support for Phoenix. Melody is still missing, because Shaun's board doesn't have it.
- 0.19: Shaun Stephenson provided me original Phoenix sound samples [Mirko Buffoni], so I adjusted sound driver to achieve correct sound modulation and frequency, and substituted noise generator for shots and explosions with a couple of samples. Noise generator can be still used (just don't put the samples in the directory) with Phoenix and it's used in Pleiads. I changed white noise waveshape and adjusted frequency, so now it sounds better.
- 0.14: Richard Davies updated the audio routines in Phoenix, sound is now closer to the original and noise is emulated.

**Comment by arcadez2003** [comment]
> Thanks for the info about the discrete sound code. Totally understandable.
> 
> Reading the logs on the adb site, it seems samples are no longer used for Phoenix. So is it already using the discrete sound, just the older version of it?

Sure i get what your saying im kinda familiar with the discrete code i studied it once or twice with a 
view to adding sound FX and music for Spiders but was scared off by the amount of changes required
up until around MAME99 or so.

Derrick Renaud did alotta work in that dept he made alotta changes spanning many MAME builds years of graft and testing basically im sure we'd net many improvements by backporting some of those changes.

As i said it's just the workload and many users will likely not care to much for the results this is only my
two cents right enough maybe some other dev's who work on this core from time to time might be more interested than me about this.

**Comment by mahoneyt944** [comment]
I have to agree with @arcadez2003. It's not always what can be updated, but the amount of work required and how much gain we'd get out of it.

More reasonably, is there a particular difference while playing this game that you'd like to see in this core vs another?

**Comment by wn2000** [comment]
> More reasonably, is there a particular difference while playing this game that you'd like to see in this core vs another?

This actually came up from someone in our Legends Ultimate community ([original post](https://www.reddit.com/r/LegendsUltimate/comments/12lxihu/phoenix_emulation_on_my_legends_ultimate_11/)).
I never played this game as a child. So to me, all I can say is that the game sounds "differently" in mame2003+ vs mame2010 and later. But to someone who grew up with this game, the sound is basically "wrong".

BTW the Legends Ultimate uses a rockchip 3328 SoC which is not that powerful. We use mame2003+ as the main emu as it's the most performant one among all options.

**Comment by essigline** [comment]
I'd like to weigh in here for a moment. I played the very popular game "Phoenix" excessively in Belgian and German arcades in the early 80s and wanted to fulfill an adult dream with Legends Ultimate V1.1. The emulation of the PHOENIX-Rom with the MAME 2003 Core, which is in itself flawlessly dumped, is flawed sound-wise. The sounds of all the attackers are wrong and terrible in my rating. The sounds in this game in particular are exceptional and make up a large part of the game. So it would be great if someone would take care of the 100% implementation in the MAME 2003+ core.

**Comment by arcadez2003** [comment]
> I have to agree with @arcadez2003. It's not always what can be updated, but the amount of work required and how much gain we'd get out of it.
> 
> More reasonably, is there a particular difference while playing this game that you'd like to see in this core vs another?

Well @mahoneyt944 there are a few things which make me not wanna look at this further firstly
and most importantly it's the workload take phoenix for example, it has to be connected up to the discrete sound core which requires a fair amount of graft for starters.

Then the discrete sound core needs to be updated and the differences will mean that the sound code
for a few other games will need to be affected, also this is assuming of course that the changes from
MAME95.u3 will just drop in without further groundwork being laid for the discrete code beforehand.

There further fixes will likely be a rinse and repeat of the above and i dont have the time for this nowadays.

But ya know talk in that thread of "WE" need to be made aware of how important "THIS IS" coming from people who have bought the Legends Arcade platform which clearly rips off our work profits from it
without giving anything back to the community kinda grates with me.

Part of me thinks instead of coming here with totally unreasonable requests for fixes to the Phoenix
sound considering the work which would be required maybe they should just take it up Legends Arcade directly get them to fix it ya know.

**Comment by mahoneyt944** [comment]
@arcadez2003 yeah I never liked when people try to sell this stuff, though I understand the other expenses they must have to build the cabinets and what not which is likely their argument....but never the less, it breaks licensing. Unfortunately so many people just want a product click and shipped without too much trouble, half of which probably don't even know what emulation is and don't care to research.

As far as Phoenix, we could also try to isolate the update, as in add it but only hook to the the one game, or to games as needed. Think we did this with another sound core recently? Can't remember though. Was it the Sega code maybe?

**Comment by wn2000** [comment]
> But ya know talk in that thread of "WE" need to be made aware of how important "THIS IS" coming from people who have bought the Legends Arcade platform which clearly rips off our work profits from it
without giving anything back to the community kinda grates with me.

I understand. I am a developer myself, and I know how much time and effort goes into creating free software. It is often a thankless job, but developers do it because they love what they do.

The Legends Ultimate cab is a popular choice for people who want to add their own games and cores. It is essentially open hardware at this point, so users have a lot of freedom to customize it. And we are all just regular users who want to get the most out of this thing.

Thank you for considering this request and for explaining the work involved. I appreciate your time and effort.

**Comment by arcadez2003** [comment]
> > But ya know talk in that thread of "WE" need to be made aware of how important "THIS IS" coming from people who have bought the Legends Arcade platform which clearly rips off our work profits from it
> > without giving anything back to the community kinda grates with me.
> 
> I understand. I am a developer myself, and I know how much time and effort goes into creating free software. It is often a thankless job, but developers do it because they love what they do.
> 
> The Legends Ultimate cab is a popular choice for people who want to add their own games and cores. It is essentially open hardware at this point, so users have a lot of freedom to customize it. And we are all just regular users who want to get the most out of this thing.
> 
> Thank you for considering this request and for explaining the work involved. I appreciate your time and effort.

Ok i decided to look into this with a view to backporting the fixes you asked for, not having the time nowadays 
as i did in the past i planned to plod away on the code over a longer timespan. however there is a problem which
im afraid is gonna be the dealbreaker.

I'll quickly explain it here.......

MAME93 was the build they totally rewrote every sound core from scratch long story short this meant all the code to handle
the sound for every game supported in MAME then changed, alot of the time we can simply rewrite said code for use in MAME78 we usually do this in the drivers.

However when rewriting the sound code they added an option to clock game sound speeds directly for cores like DISCRETE
which did not have this option previously, unfortunately this means we'd have to update some parts of our soundcore
handling to MAME93 to support this then update everything using the DISCRETE sound at the same time, obviously you understand this would be a mammoth undertaking and i cant see any of the dev team here being all that interested in 
taking this on.

0.103u5: Derrick Renaud tweaked Phoenix effect 2 sound to be more accurate matching oscilliscope data. Changed the Phoenix discrete clock rate to a fixed rate of 120000 allowing the simulation to be more accurate with less alaising noise at the cost of speed.

The above fix requires us to set a clock speed directly for the DISCRETE sound core which as i explained above
we dont have that option and without it the sound in Phoenix will still be broken might be better or worse than
what we have just now but unless we can do all the fixes and get it to 100% then there is no point on working on this.

MDRV_SOUND_ADD_TAG("discrete", DISCRETE, 120000) <- clock speed
	MDRV_SOUND_CONFIG(phoenix_discrete_interface)
	MDRV_SOUND_ROUTE(ALL_OUTPUTS, "mono", 0.6)

**Comment by wn2000** [comment]
Ahhh ok. Thanks again for looking into this. I hope someday I could be poking the drivers as you guys do, but all those macros just throw me off lol. Well I guess this one can be closed. Really appreciate your time!
