### ISSUE TITLE
Mortal Kombat 2 demo text

### ISSUE THREAD

**Issue by Riddler1** [libretro/mame2003-plus-libretro#1560]
Hi guys i noticed this....
rom= mk2
-commit f2018df
-raspberry pi 4

![20230421_192605](https://user-images.githubusercontent.com/43607359/233716619-ef05aaf8-370e-45a6-89f4-88e2de4dfc4d.jpg)

![20230421_193541](https://user-images.githubusercontent.com/43607359/233716561-0b95817d-e58c-4897-91d8-aac8594839ea.jpg)

tested same rom on fbneo and test is all ok
![20230421_193114](https://user-images.githubusercontent.com/43607359/233718406-a8364af3-d27a-4448-b2ad-b02b23a96e6f.jpg)

**Comment by mahoneyt944** [comment]
I confirm this issue

**Comment by mahoneyt944** [comment]
Fixed
