### ISSUE TITLE
usgames.c - Sometimes emulation freeze whitout any apparently error....

### ISSUE THREAD

**Issue by DjDiabolik** [libretro/mame2003-plus-libretro#1565]
On current collection of mame2003-plus i have some of this games...... if i remember  i have:
- Games 25.4x
- Games 18.5
- Games 18.7C

The games generally it's work good....... but sometime i see the emulation goes completely in freeze and it's not accept input or other button pressed.
Expecially apparently some games can't playable at all like "Red Dog Poker" or some Trivia it's be goes in freeze after you put credit... put your name and chose your bet.

I have apparently tryed this same games on my windows pc whit mame 0.253 and here this same games it's never goes in freeze.

It's a fixable little trouble ? For example updating some internal core bios or similar ?

Little OT....... same exact issue it's present if i try to use the current "FinalBurn Neo".
This uses a different .zip files apparently but some title as supported and also here it's still goes in freeze randomly (thinks it's an idea to open an issue also on this core issue tracker ?) .

**Comment by mahoneyt944** [comment]
Are you mapping the buttons to the inputs you're using?
![usg185-230426-082300](https://user-images.githubusercontent.com/49591133/234573533-ba24f5a7-74af-4844-bca5-3b2d892dc721.png)

**Comment by DjDiabolik** [comment]
> Are you mapping the buttons to the inputs you're using? Also using the correct romsets? ![usg185-230426-082300](https://user-images.githubusercontent.com/49591133/234573533-ba24f5a7-74af-4844-bca5-3b2d892dc721.png)

On FinalBurn Neo it's not need to reconfigure the button.... 
On mame2003plus yes i have need to set all button manually otherwise you just can't do anything :)

Anyway it's only specific games apparently freeze the emulation....... on 25.4 it's append when you try to play at "Red Dog Poker" or "Sex Trivia".

If i have correct romset ? I have checked all my roms collection whit clrmamepro and apparently it's not report error.
@mahoneyt944 you can play correctly this two built-in games whitout freezing issue ?

**Comment by DjDiabolik** [comment]
if i want to be more specific:
Add credit....... select games and select number of player. i can select correctly my "player" name (or i can choose to keep the default one) but when the games start emulation goes in freeze.

Try to play expecially a built-in games....... on usgames 25.4 "Red Dog Poker" :)

**Comment by mahoneyt944** [comment]
I looked into these games a little, this commit should add support for the missing inputs. You will still need to open the mame menu and map them how you want.

https://github.com/libretro/mame2003-plus-libretro/commit/10e5792459df44e0f78b98ab7b169c6c17e78e92

**Comment by DjDiabolik** [comment]
Ops at today i have also changed my setup... now i'm using "ecosystem" retropie on a Mini PC whit Ubuntu 22.04 and i need to check the same games whit same core/emulator. I'll try this commit as soon as I can.

**Comment by DjDiabolik** [comment]
Reported a similar issue also using FBNeo here:
https://github.com/finalburnneo/FBNeo/issues/1848

Only as purpose feedback :) Know it's totally different project.... i hope also FBNeo can fix this issue.

**Comment by grant2258** [comment]
Yes any help towards that project is welcome, they mostly a bunch all round good guys that have been doing this for years :)
