### ISSUE TITLE
le2: inputs sent in wrong order?

### ISSUE THREAD

**Issue by StormedBubbles** [libretro/mame2003-plus-libretro#1592]
Anecdotally, something seemed a touch off with Lethal Enforcers II (`le2`) to me when using a lightgun-like device (Sinden Lightgun, in my case). Using the RetroArch pause feature finally allowed me to see what the issue was. I used a trackball to test this to ensure I wasn't accidentally moving the gun crosshairs.

By enabling the crosshairs, pausing the emulation with hotkey+P, moving the trackball a bit, letting go of the trackball, and then holding the trigger button and advancing the emulation frame by frame using hotkey+K, I found that the white flash occurs before the cursor moves. This results in the shot not being aligned with the cursor position even though the cursor was moved first. The shots normally line up exactly with the center of the cursor (i.e., when the cursor is stationary).

In contrast, I tested Area 51 and Crypt Killer and found that the cursor moves before the flash occurs, and the resulting shot lines up correctly.

I hope I have articulated this well enough. I can provide more information if need be. The anecdotal experience was difficulty hitting targets on opposite sides of the screen in rapid succession. The second shot always seemed closer to the center of the screen than it should have been.

**Comment by mahoneyt944** [comment]
If I'm understanding what you're saying, the cursor is drawn in the new location but the shot is a frame behind at the old location?

**Comment by mahoneyt944** [comment]
I captured a pic of this by holding the dpad and firing then pausing mid movement. I can't see why this happens, but the shot seems to lag behind the crosshairs.
![le2-230527-102808](https://github.com/libretro/mame2003-plus-libretro/assets/49591133/1b688003-81ae-4c7a-a013-ce927cdbcce4)

**Comment by StormedBubbles** [comment]
Thanks for the screen shot. Yes, to the naked eye, it does appear that the shot location lags behind the crosshair's location. However, I think in terms of what the emulator sees, it's the other way around: the trigger input is activated too early. 

The crosshair moved with the same amount of input lag for me in all three of the games I mentioned. If I'm looking at it right, there's 1 frame of input lag for the cursor for me in all three games.

Only in `le2` did the trigger input get activated even earlier than that. In Area 51 and Crypt Killer, the cursor was allowed to take the 2 frames to get from point A to point B before the trigger was registered, so the shot appeared at point B. In `le2`, the trigger input was registered while the cursor was in the midst of moving from point A to point B, so the shot appeared at point C in between them.

**Comment by mahoneyt944** [comment]
The way our crosshairs work in this core, we draw the game screen then draw the crosshair on top of it each frame. I think what's happening is the games "bullet splatter" animation is taking longer to draw than how fast we draw the crosshairs. Mind you natively the game doesn't draw crosshairs, so you probably wouldn't notice on a real machine.

I'm curious to see if the shot actually lands at the splatter point or where are crosshairs are.

**Comment by mahoneyt944** [comment]
If you use the service buttons to enter the gun check service menu, it seems like this is the case as my crosshair.passes a grid line, the bullet point is dead on, but the flash or splatter lags the shot
![le2-230527-113758](https://github.com/libretro/mame2003-plus-libretro/assets/49591133/a3eaae0d-74c6-4c44-af65-0544606a44a3)
![le2-230527-113839](https://github.com/libretro/mame2003-plus-libretro/assets/49591133/420343b2-ba63-48f9-89d7-78024ac53115)

**Comment by StormedBubbles** [comment]
Oh wow interesting. I hadn't thought of that. I will take a look at the service menu later today with my setup and see if the frame-by-frame test produces a different result from what I got in game.

**Comment by mahoneyt944** [comment]
> > The way our crosshairs work in this core, we draw the game screen then draw the crosshair on top of it each frame. I think what's happening is the games "bullet splatter" animation is taking longer to draw than how fast we draw the crosshairs.
> 
> thats not quite true the crosshair drawn in an if condition in the video update code instead of unconditionally in this case.

Yes but the if condition is always true for le2.
https://github.com/libretro/mame2003-plus-libretro/blob/c2053dd23b70b178f7f835dc5007ecf129133d8f/src/vidhrdw/konamigx_vidhrdw.c#L288

**Comment by mahoneyt944** [comment]
Yeah definitely odd naming, not sure why it's that way. Probably should update it to something more simple but it's functional non the less.

Btw not sure if you've been looking at #1587, but maybe you'd be willing to look into why radr starts up to a network check screen? It requires you to hit a service button to skip it to actually get to the game. Likely a dip switch, or read/write handler but haven't found it.

**Comment by mahoneyt944** [comment]
I noticed they are slightly different from the reads to the crosshair draw, I think there's some minor scaling going on when we draw the crosshairs to make it where the game thinks it is. It's really accurate in the test menu, always within a pixel.

**Comment by mahoneyt944** [comment]
Can they actually be different? These are read once a frame and we only poll inputs once a frame. So I'd assume they would be the same inside the same frame?

**Comment by mahoneyt944** [comment]
Isn't video update apart of the mame loop? What you're saying doesn't make sense to me, if we are in a certain frame, the game should readinputport, and then video update will readinputport later in the same frame. Mame_frame has to finish before the next loop occurs where the inputs are polled again and the process repeats again and again.

What I think you are saying is readinputport can return different values within the same frame, which I don't believe it can? Though I've never specifically tested such things, so I could be wrong.

**Comment by mahoneyt944** [comment]
For reference: we poll then run mame_frame last. So I can't see how it could return differently in the same frame.
https://github.com/libretro/mame2003-plus-libretro/blob/c2053dd23b70b178f7f835dc5007ecf129133d8f/src/mame2003/mame2003.c#L367-L391

**Comment by mahoneyt944** [comment]
I'm not arguing with you I stated I could be wrong, just a discussion. I happen to run my own test and agree with your notion. If you want PR a change I'll push it later. Headed out right now.
```
[MAME 2003+] le2_gun_H_r( frame455 ) readinputport(9)126  readinputport(10)171
[MAME 2003+] le2_gun_H_r( frame455 ) readinputport(9)126  readinputport(10)171
[MAME 2003+] video_update( frame455 ) readinputport(9)126  readinputport(10)170
[MAME 2003+] le2_gun_H_r( frame456 ) readinputport(9)118  readinputport(10)139
[MAME 2003+] le2_gun_H_r( frame456 ) readinputport(9)118  readinputport(10)139
[MAME 2003+] video_update( frame456 ) readinputport(9)118  readinputport(10)138
[MAME 2003+] le2_gun_H_r( frame457 ) readinputport(9)108  readinputport(10)129
[MAME 2003+] le2_gun_H_r( frame457 ) readinputport(9)108  readinputport(10)129
[MAME 2003+] video_update( frame457 ) readinputport(9)108  readinputport(10)129
[MAME 2003+] le2_gun_H_r( frame458 ) readinputport(9)76  readinputport(10)96
[MAME 2003+] le2_gun_H_r( frame458 ) readinputport(9)76  readinputport(10)96
[MAME 2003+] video_update( frame458 ) readinputport(9)75  readinputport(10)95
[MAME 2003+] le2_gun_H_r( frame459 ) readinputport(9)63  readinputport(10)4
[MAME 2003+] le2_gun_H_r( frame459 ) readinputport(9)63  readinputport(10)4
[MAME 2003+] video_update( frame459 ) readinputport(9)63  readinputport(10)0
[MAME 2003+] le2_gun_H_r( frame460 ) readinputport(9)63  readinputport(10)0
[MAME 2003+] le2_gun_H_r( frame460 ) readinputport(9)63  readinputport(10)0
[MAME 2003+] video_update( frame460 ) readinputport(9)63  readinputport(10)0
[MAME 2003+] le2_gun_H_r( frame461 ) readinputport(9)60  readinputport(10)0
[MAME 2003+] le2_gun_H_r( frame461 ) readinputport(9)60  readinputport(10)0
[MAME 2003+] video_update( frame461 ) readinputport(9)59  readinputport(10)0
[MAME 2003+] le2_gun_H_r( frame462 ) readinputport(9)54  readinputport(10)0
[MAME 2003+] le2_gun_H_r( frame462 ) readinputport(9)54  readinputport(10)0
[MAME 2003+] video_update( frame462 ) readinputport(9)53  readinputport(10)0
[MAME 2003+] le2_gun_H_r( frame463 ) readinputport(9)51  readinputport(10)0
[MAME 2003+] le2_gun_H_r( frame463 ) readinputport(9)51  readinputport(10)0
[MAME 2003+] video_update( frame463 ) readinputport(9)51  readinputport(10)0
[MAME 2003+] le2_gun_H_r( frame464 ) readinputport(9)51  readinputport(10)0
[MAME 2003+] le2_gun_H_r( frame464 ) readinputport(9)51  readinputport(10)0
[MAME 2003+] video_update( frame464 ) readinputport(9)51  readinputport(10)0
[MAME 2003+] le2_gun_H_r( frame465 ) readinputport(9)51  readinputport(10)0
[MAME 2003+] le2_gun_H_r( frame465 ) readinputport(9)51  readinputport(10)0
[MAME 2003+] video_update( frame465 ) readinputport(9)51  readinputport(10)0
[MAME 2003+] le2_gun_H_r( frame466 ) readinputport(9)7  readinputport(10)0
[MAME 2003+] le2_gun_H_r( frame466 ) readinputport(9)7  readinputport(10)0
[MAME 2003+] video_update( frame466 ) readinputport(9)6  readinputport(10)0
[MAME 2003+] le2_gun_H_r( frame467 ) readinputport(9)6  readinputport(10)0
[MAME 2003+] le2_gun_H_r( frame467 ) readinputport(9)6  readinputport(10)0
[MAME 2003+] video_update( frame467 ) readinputport(9)6  readinputport(10)0
[MAME 2003+] le2_gun_H_r( frame468 ) readinputport(9)0  readinputport(10)113
[MAME 2003+] le2_gun_H_r( frame468 ) readinputport(9)0  readinputport(10)113
[MAME 2003+] video_update( frame468 ) readinputport(9)0  readinputport(10)117
[MAME 2003+] le2_gun_H_r( frame469 ) readinputport(9)10  readinputport(10)127
[MAME 2003+] le2_gun_H_r( frame469 ) readinputport(9)10  readinputport(10)127
[MAME 2003+] video_update( frame469 ) readinputport(9)11  readinputport(10)128
[MAME 2003+] le2_gun_H_r( frame470 ) readinputport(9)11  readinputport(10)128
[MAME 2003+] le2_gun_H_r( frame470 ) readinputport(9)11  readinputport(10)128
[MAME 2003+] video_update( frame470 ) readinputport(9)11  readinputport(10)128
[MAME 2003+] le2_gun_H_r( frame471 ) readinputport(9)33  readinputport(10)129
[MAME 2003+] le2_gun_H_r( frame471 ) readinputport(9)33  readinputport(10)129
[MAME 2003+] video_update( frame471 ) readinputport(9)34  readinputport(10)129
[MAME 2003+] le2_gun_H_r( frame472 ) readinputport(9)62  readinputport(10)142
[MAME 2003+] le2_gun_H_r( frame472 ) readinputport(9)62  readinputport(10)142
[MAME 2003+] video_update( frame472 ) readinputport(9)63  readinputport(10)143
[MAME 2003+] le2_gun_H_r( frame473 ) readinputport(9)86  readinputport(10)165
[MAME 2003+] le2_gun_H_r( frame473 ) readinputport(9)86  readinputport(10)165
[MAME 2003+] video_update( frame473 ) readinputport(9)86  readinputport(10)166
[MAME 2003+] le2_gun_H_r( frame474 ) readinputport(9)111  readinputport(10)197
[MAME 2003+] le2_gun_H_r( frame474 ) readinputport(9)111  readinputport(10)197
[MAME 2003+] video_update( frame474 ) readinputport(9)112  readinputport(10)198
[MAME 2003+] le2_gun_H_r( frame475 ) readinputport(9)121  readinputport(10)212
[MAME 2003+] le2_gun_H_r( frame475 ) readinputport(9)121  readinputport(10)212
[MAME 2003+] video_update( frame475 ) readinputport(9)121  readinputport(10)212
[MAME 2003+] le2_gun_H_r( frame476 ) readinputport(9)131  readinputport(10)204
[MAME 2003+] le2_gun_H_r( frame476 ) readinputport(9)131  readinputport(10)204
[MAME 2003+] video_update( frame476 ) readinputport(9)132  readinputport(10)204
[MAME 2003+] le2_gun_H_r( frame477 ) readinputport(9)150  readinputport(10)169
[MAME 2003+] le2_gun_H_r( frame477 ) readinputport(9)150  readinputport(10)169
[MAME 2003+] video_update( frame477 ) readinputport(9)151  readinputport(10)167
[MAME 2003+] le2_gun_H_r( frame478 ) readinputport(9)208  readinputport(10)140
[MAME 2003+] le2_gun_H_r( frame478 ) readinputport(9)208  readinputport(10)140
[MAME 2003+] video_update( frame478 ) readinputport(9)210  readinputport(10)139
[MAME 2003+] le2_gun_H_r( frame479 ) readinputport(9)210  readinputport(10)139
[MAME 2003+] le2_gun_H_r( frame479 ) readinputport(9)210  readinputport(10)139
[MAME 2003+] video_update( frame479 ) readinputport(9)210  readinputport(10)139
[MAME 2003+] le2_gun_H_r( frame480 ) readinputport(9)253  readinputport(10)131
[MAME 2003+] le2_gun_H_r( frame480 ) readinputport(9)253  readinputport(10)131
[MAME 2003+] video_update( frame480 ) readinputport(9)255  readinputport(10)131
[MAME 2003+] le2_gun_H_r( frame481 ) readinputport(9)255  readinputport(10)128
[MAME 2003+] le2_gun_H_r( frame481 ) readinputport(9)255  readinputport(10)128
[MAME 2003+] video_update( frame481 ) readinputport(9)255  readinputport(10)128
[MAME 2003+] le2_gun_H_r( frame482 ) readinputport(9)255  readinputport(10)122
[MAME 2003+] le2_gun_H_r( frame482 ) readinputport(9)255  readinputport(10)122
[MAME 2003+] video_update( frame482 ) readinputport(9)255  readinputport(10)121
[MAME 2003+] le2_gun_H_r( frame483 ) readinputport(9)255  readinputport(10)94
[MAME 2003+] le2_gun_H_r( frame483 ) readinputport(9)255  readinputport(10)94
[MAME 2003+] video_update( frame483 ) readinputport(9)255  readinputport(10)93
[MAME 2003+] le2_gun_H_r( frame484 ) readinputport(9)235  readinputport(10)38
[MAME 2003+] le2_gun_H_r( frame484 ) readinputport(9)235  readinputport(10)38
[MAME 2003+] video_update( frame484 ) readinputport(9)233  readinputport(10)36
[MAME 2003+] le2_gun_H_r( frame485 ) readinputport(9)197  readinputport(10)1
[MAME 2003+] le2_gun_H_r( frame485 ) readinputport(9)197  readinputport(10)1
[MAME 2003+] video_update( frame485 ) readinputport(9)196  readinputport(10)0
[MAME 2003+] le2_gun_H_r( frame486 ) readinputport(9)156  readinputport(10)0
[MAME 2003+] le2_gun_H_r( frame486 ) readinputport(9)156  readinputport(10)0
[MAME 2003+] video_update( frame486 ) readinputport(9)155  readinputport(10)0
[MAME 2003+] le2_gun_H_r( frame487 ) readinputport(9)129  readinputport(10)0
[MAME 2003+] le2_gun_H_r( frame487 ) readinputport(9)129  readinputport(10)0
[MAME 2003+] video_update( frame487 ) readinputport(9)128  readinputport(10)0
[MAME 2003+] le2_gun_H_r( frame488 ) readinputport(9)126  readinputport(10)0
[MAME 2003+] le2_gun_H_r( frame488 ) readinputport(9)126  readinputport(10)0
[MAME 2003+] video_update( frame488 ) readinputport(9)126  readinputport(10)0
[MAME 2003+] le2_gun_H_r( frame489 ) readinputport(9)126  readinputport(10)0
[MAME 2003+] le2_gun_H_r( frame489 ) readinputport(9)126  readinputport(10)0
[MAME 2003+] video_update( frame489 ) readinputport(9)126  readinputport(10)0
[MAME 2003+] le2_gun_H_r( frame490 ) readinputport(9)117  readinputport(10)0
[MAME 2003+] le2_gun_H_r( frame490 ) readinputport(9)117  readinputport(10)0
[MAME 2003+] video_update( frame490 ) readinputport(9)117  readinputport(10)0
[MAME 2003+] le2_gun_H_r( frame491 ) readinputport(9)96  readinputport(10)79
[MAME 2003+] le2_gun_H_r( frame491 ) readinputport(9)96  readinputport(10)79
[MAME 2003+] video_update( frame491 ) readinputport(9)95  readinputport(10)83
[MAME 2003+] le2_gun_H_r( frame492 ) readinputport(9)82  readinputport(10)113
[MAME 2003+] le2_gun_H_r( frame492 ) readinputport(9)82  readinputport(10)113
[MAME 2003+] video_update( frame492 ) readinputport(9)81  readinputport(10)114
[MAME 2003+] le2_gun_H_r( frame493 ) readinputport(9)88  readinputport(10)127
[MAME 2003+] le2_gun_H_r( frame493 ) readinputport(9)88  readinputport(10)127
[MAME 2003+] video_update( frame493 ) readinputport(9)88  readinputport(10)128
[MAME 2003+] le2_gun_H_r( frame494 ) readinputport(9)108  readinputport(10)133
[MAME 2003+] le2_gun_H_r( frame494 ) readinputport(9)108  readinputport(10)133
[MAME 2003+] video_update( frame494 ) readinputport(9)109  readinputport(10)133
[MAME 2003+] le2_gun_H_r( frame495 ) readinputport(9)119  readinputport(10)148
[MAME 2003+] le2_gun_H_r( frame495 ) readinputport(9)119  readinputport(10)148
[MAME 2003+] video_update( frame495 ) readinputport(9)120  readinputport(10)148
[MAME 2003+] le2_gun_H_r( frame496 ) readinputport(9)124  readinputport(10)159
[MAME 2003+] le2_gun_H_r( frame496 ) readinputport(9)124  readinputport(10)159
[MAME 2003+] video_update( frame496 ) readinputport(9)124  readinputport(10)160
[MAME 2003+] le2_gun_H_r( frame497 ) readinputport(9)127  readinputport(10)183
[MAME 2003+] le2_gun_H_r( frame497 ) readinputport(9)127  readinputport(10)183
[MAME 2003+] video_update( frame497 ) readinputport(9)128  readinputport(10)184
[MAME 2003+] le2_gun_H_r( frame498 ) readinputport(9)128  readinputport(10)184
[MAME 2003+] le2_gun_H_r( frame498 ) readinputport(9)128  readinputport(10)184
[MAME 2003+] video_update( frame498 ) readinputport(9)128  readinputport(10)184
[MAME 2003+] le2_gun_H_r( frame499 ) readinputport(9)132  readinputport(10)184
[MAME 2003+] le2_gun_H_r( frame499 ) readinputport(9)132  readinputport(10)184
[MAME 2003+] video_update( frame499 ) readinputport(9)133  readinputport(10)184
[MAME 2003+] le2_gun_H_r( frame500 ) readinputport(9)203  readinputport(10)153
[MAME 2003+] le2_gun_H_r( frame500 ) readinputport(9)203  readinputport(10)153
[MAME 2003+] video_update( frame500 ) readinputport(9)206  readinputport(10)152
[MAME 2003+] le2_gun_H_r( frame501 ) readinputport(9)253  readinputport(10)136
[MAME 2003+] le2_gun_H_r( frame501 ) readinputport(9)253  readinputport(10)136
[MAME 2003+] video_update( frame501 ) readinputport(9)255  readinputport(10)135
[MAME 2003+] le2_gun_H_r( frame502 ) readinputport(9)255  readinputport(10)135
[MAME 2003+] le2_gun_H_r( frame502 ) readinputport(9)255  readinputport(10)135
[MAME 2003+] video_update( frame502 ) readinputport(9)255  readinputport(10)135
[MAME 2003+] le2_gun_H_r( frame503 ) readinputport(9)255  readinputport(10)129
[MAME 2003+] le2_gun_H_r( frame503 ) readinputport(9)255  readinputport(10)129
[MAME 2003+] video_update( frame503 ) readinputport(9)255  readinputport(10)128
[MAME 2003+] le2_gun_H_r( frame504 ) readinputport(9)255  readinputport(10)128
[MAME 2003+] le2_gun_H_r( frame504 ) readinputport(9)255  readinputport(10)128
[MAME 2003+] video_update( frame504 ) readinputport(9)255  readinputport(10)128
```

**Comment by mahoneyt944** [comment]
Had a second to make a branch for this, on a quick test the game doesn't read the input during startup so it's locked out for a little. The input doesn't feel any different to me. I'll wait to see how @StormedBubbles tests go in the service menu before pushing anything.

**Comment by StormedBubbles** [comment]
Sorry for the delay, and thank you both for looking into this. My experience in the service menu is exactly the same as in game when I do the procedure I mentioned earlier. The shot lags behind where the cursor location is by an amount that appears to be the same as during normal gameplay (so the splat effect appears to be where the shot actually lands).

**Comment by StormedBubbles** [comment]
Sorry I may have misunderstood the request. I tested the main branch of lr-mame2003plus. Would you like me to take a look at that le2 branch and test?

**Comment by mahoneyt944** [comment]
Yeah I must have deleted it I can write it back up if need be, when I tested the crosshairs (input read) is locked out while the game boots up. And it felt the same to me in the menu and in game. Many drivers read the port directly in draw_crosshair, so its a common practice here for what it's worth. I think this is just how the game feels. Seems like the gun is very accurate to me, not sure what your experience is misty with tests you've done

**Comment by StormedBubbles** [comment]
The code changes posted above appear to rescale/shift the position of the emulator's cursor if I'm reading that right. I should have mentioned that I actually play with the cursor off and was just using the cursor as a means of explaining the issue I experienced. I tried said code changes with `le2` and still had the same issue. Here are some screen shots of `lethalen` and `le2` (both in this emulator) to hopefully give a better idea of what I mean. `lethalen` does NOT have the same issue. This was all done by pausing emulation and advancing frame by frame. `lethalen` feels fine to me, but `le2`'s shots seem to drag behind the cursor when moving.

`lethalen` first, to show expected behavior:

**Initial shot to show expected alignment**
![lethalen-230528-235639](https://github.com/libretro/mame2003-plus-libretro/assets/80055191/55b33dcb-e9a0-41c1-a7f2-65a3dfd5d540)

**Cursor left alone after that shot**
![lethalen-230528-235656](https://github.com/libretro/mame2003-plus-libretro/assets/80055191/75215c3c-6f71-43e9-aadc-eda70882434f)

**Move cursor with trackball, take hand off trackball, fire shot, advance 1 frame**
![lethalen-230528-235700](https://github.com/libretro/mame2003-plus-libretro/assets/80055191/f0310551-1d79-4d11-acbd-597c731ee6c8)

**Advance 1 frame. Cursor has moved, but shot has not yet appeared**
![lethalen-230528-235702](https://github.com/libretro/mame2003-plus-libretro/assets/80055191/1e01da90-443d-4cbd-986d-2360b9742b4e)

**Advance 1 frame. Shot appears in correct spot with correct alignment**
![lethalen-230528-235705](https://github.com/libretro/mame2003-plus-libretro/assets/80055191/99907a87-764a-49ac-bf1f-441b1b186b75)
 
Now for `le2`:

**Initial shot to show expected alignment**
![le2-230529-000424](https://github.com/libretro/mame2003-plus-libretro/assets/80055191/b6d3e550-cafd-426c-bd1c-80b0a82d57c2)

**Cursor left alone after that shot**
![le2-230529-000427](https://github.com/libretro/mame2003-plus-libretro/assets/80055191/e2228e7f-4d96-41f9-9231-c775d62dab88)

**Move cursor with trackball, take hand off trackball, fire shot, advance 1 frame**
![le2-230529-000440](https://github.com/libretro/mame2003-plus-libretro/assets/80055191/2e333d0c-3aba-4948-b834-4d92eb6f9ed0)

**Advance 1 frame. Cursor has moved, but shot has not yet appeared**
![le2-230529-000444](https://github.com/libretro/mame2003-plus-libretro/assets/80055191/8bbc8a14-1c05-4bab-8f09-2c169fbb09b3)

**Advance 1 frame. Cursor moves again, and shot appears at previous location**
![le2-230529-000446](https://github.com/libretro/mame2003-plus-libretro/assets/80055191/a93cdc0c-90bf-434d-98b5-4459c905cb06)

**Advance 1 frame to show completion of shot and misalignment**
![le2-230529-000449](https://github.com/libretro/mame2003-plus-libretro/assets/80055191/233f3f0a-4d47-4b4a-9e48-41b56e358251)

I ran the same test with Area 51 and Crypt Killer in this emulator as well as a few other games in other emulators, and they all behave like `lethalen` does. `le2` seems to take 2 steps to go from position A to position B while the others jump immediately from position A to position B.

**Comment by mahoneyt944** [comment]
@MistyDreams sounds like this is just how it is for this game here.

**Comment by StormedBubbles** [comment]
The best comparison I found was lr-mame2010. `le2` passes the "pause test" I have been doing and also seems to perform better in the service menu if I start at one end of the screen and do my best to move the gun to the other side at a constant speed and fire multiple times. The bullet splats there in lr-mame2010 (MAME .139) follow my line of sight more closely. The downside is that there are numerous graphical glitches in the game in that version of MAME for whatever reason. Later versions of MAME give me a poor frame rate for `le2` on my Raspberry Pi 4B.

**Comment by mahoneyt944** [comment]
Yeah I patched the colors up for le2 awhile ago in this core, otherwise it would probably have more issues too.

**Comment by StormedBubbles** [comment]
My previous comment minus the sentence with the "C" word is my experience with line of sight. The shots lag behind my sight in this core by maybe half of a service-menu square more than in 2010 when moving. It actually looks like what I show in my screen shots above.

@mahoneyt944 are you referring to the [color hack l](https://github.com/libretro/mame2003-plus-libretro/pull/1218) from November of 2021? That was originally implemented in a MAME version predating 2010's and is already in that libretro core. Also, what were the changes that you originally proposed before? I can take a look at those too. After looking at that, I can just close the issue if no one else seems to be having a similar experience.

**Comment by mahoneyt944** [comment]
The change I made here was a color palette shift, can't recall the mame version it was from. 
https://github.com/libretro/mame2003-plus-libretro/commit/b52ed08aadce3104db80369cb4de56b3f85662e1

The change I had in my branch was basically the same as what misty had, I just kept the scaling the same. But it you saw no difference with his, it won't be better with what I had

**Comment by mahoneyt944** [comment]
Does the game require so many frames of the trigger to register?

**Comment by mahoneyt944** [comment]
Seemed fine by my tests, but I don't use an actual lightgun. Idk probably nothing we can do here.
