### ISSUE TITLE
Building The Romset

### ISSUE THREAD

**Issue by arcadez** [libretro/mame2003-plus-libretro#16]
im gathering up the roms currently i have 80% fixed and correct via the dat, however of the
Neogeo games i have so far it will not be possible to trackdown a correct version of 
Metal Slug 5 as it has one rom 268-m1.bin which has since been redumped and replaced.

What i will do for this game and any others like this i'll simply update the rom in the driver
so we support the newer dumped version of the 268-m1.bin which we'll be able to trackdown.

**Comment by arcadez** [comment]
Update i now a correct and working rom for every game barring the Neogeo's which im
leaving until later as i suspect i'll have a bit of work to do on those at driver level

BTW this seems to show as a grey unknown rom it's a clone of Osman and should be supported

GAME( 1996, candance, osman, mitchell156, simpl156, candance, ROT0, "Mitchell", "Cannon Dancer (Japan)" )

**Comment by arcadez** [comment]
OK i have a working rom for everyone of the newly supported games which match up with
the dat, and by using a couple of redumped roms for Metal Slug 5 and Samurai Shodown 5
it should make it easy for folks to trackdown a compatable set.

That just leaves two games............

The King Of Fighters 2003 (Decrypted) kof2003d.zip

Im thinking of removing support for the above as i have been unable to trackdown a viable
romset across alotta different sites and i think the one we would need will be lost in the 
midst of time.

SVC Chaos : Capcom Vs SNK 

Again i cant find a working rom, i might have to update the romset to match up with MAME103
problem is the neogeo decryption changed around this time so the older style decryption we use
for this neogeo driver in this core might not work with the newer rom.

All i can do is update the rom and see what happens if it's not gonna work it can always be removed
down the road as we do support another version of this game anyway all be it a bootleg.

**Comment by grant2258** [comment]
im building the set now will let you know how i get on

**Comment by grant2258** [comment]
Hyper Street Fighter II: The Anniversary Edition (Asia 040202) [folder: hsf2a - size: 45mb]
missing rom: hs2ax.03 [size: 524288] [CRC32: 5f3d7397] [SHA1: 96f327dd998105ad5dc46bc9d3b741805a840d68]
missing rom: hs2ax.04 [size: 524288] [CRC32: 59acf108] [SHA1: e68fe233681175b29a35badab249c2b892b23af3]

The King of Fighters 2003 (Decrypted C) [system: Neo-Geo - folder: kof2003d - size: 124mb]
missing rom: 271-v1d.bin [size: 16777216] [CRC32: 2964f36e]

Snk Vs Capcom : Svc Chaos [system: Neo-Geo - folder: svcchaos - size: 114mb]
missing rom: 269-m1d.bin [size: 131072] [CRC32: fd4f0ff9] [SHA1: e97e864aaa4789d854363512986e80c0606da996]

them other roms must be in the fba set

**Comment by arcadez** [comment]
Yeah listen those missing roms for hsf2a are Xor decryption romfiles which have since been
done away with in MAME and FBA, most new roms wont have em you would need to 
trackdown an older rom but here is the correct one to save ya some time.

hsf2a
https://www.sendspace.com/file/lfnbrd

**Comment by grant2258** [comment]
cheers appreciated

**Comment by grant2258** [comment]
try this in the driver for sva chaos

sha 7466a6962de5242f71b9c52d7bd21a9832115e11 crc32 7b7bf462

**Comment by grant2258** [comment]
only information i can find is there was patches for it
