### ISSUE TITLE
Sinistar - Digital Controls cause Player to accelerate out of control, turning feels wrong [MAME 2003 & 2003 Plus]

### ISSUE THREAD

**Issue by SapphireTactician** [libretro/mame2003-plus-libretro#160]
### Description

"Sinistar" (*rom name: `sinistar`*) exhibits a problem in both MAME 2003 cores when using digital controls, in which the player accelerates uncontrollably. Turning also feels wrong and cumbersome. At the screen where you'd enter your initals, the cursors advances to the right on its own without any input from the player.

-----

### Expected behavior

Player should have full control over their ship's movement and speed.

Proper movement and behavior can be observed here on the official Ready Player One movie website: http://arcade.readyplayeronemovie.com/sinistar/

-----

### Actual behavior

When using digital controls, the Player accelerates automatically after a direction is inputted (*fully automatic after restarts*) and cannot slow down. Turning is awkward / difficult.

-----

### Steps to reproduce the bug

* Load `sinistar`
* Select the either MAME 2003 core
* Insert Coin
* Start Game
    * Move ship with digital controls
* Observe bug

-----

### Logs:

None

-----

### Bisect Results:

No bisect performed. Not even sure where to begin looking for this one.

-----

### Version/Commit Info:

- **RetroArch Version:** 1.7.2 (_Commit: 80b480e855_)
- **MAME 2003 Plus core commit version:** ed5f466

### Environment information

- **OS:** Debian 9 (*Stretch*) Stable x86_64
- **Compiler:** gcc 3.6.0 64-bit

**Comment by arcadez** [comment]
Analog inputs can sometimes be a little flaky in MAME as they dont often transfer too well
when using certain gamepads, i dunno if you can access the analog control options in this core..?? 

They should pop up as part of the MAME tab menu and by tweaking the input sensitivity or 
speed values the problems your describing with Sinister can usually be ironed out.

**Comment by SapphireTactician** [comment]
I tested the game with a keyboard to rule out the possibility of a sketchy controller. I stumbled upon the analog control options myself and suspected them as well, but even after tinkering them I couldn't resolve the issue myself.

Even when setting the sensitivity to 0 and the speed to 1, I found my ship flying out of control.

**Comment by dankcushions** [comment]
i believe these games work fine with an analog controller (eg dual shock, or spinner), but the digital controls are obviously a bit funky. care should be taken that any fixes work for all device types.

**Comment by SapphireTactician** [comment]
@dankcushions hit the nail on the head. I decided to use the 8bitdo SN30 Pro and using just the analog sticks, Sinistar played perfectly at the default analog settings. Thanks for mentioning analog being fine.

It's the digital settings that need fixing. @arcadez . I'll update the issue title and such.

**Comment by markwkidd** [comment]
agreeing with grant.

MAME has code for converting digital controls to analog, and so does libretro.

One theory is, based on @SapphireTactician setting the sensitivity down to 1% and still having problems, is that the MAME code is not being executed. The way to test to see if it's even possible for the MAME code to work correctly is to use MAME 0.78 with a keyboard and replicate the test.

The other, somewhat better approach is to try the libretro/RetroArch digital-to-analog mapping features to simulate the experience that @SapphireTactician has when using the SN30 Pro Analog sticks.

I really have never used analog controls, simulated from a digital control or true analog. For anything. :disappointed: True story.

I'm trying to wrap up the nvram work on the games in the `qix` driver in the short term, but I'll try to look at this issue more closely afterward.

**Comment by markwkidd** [comment]
@fr500 as we discussed I'm not going to tag you unless I have specific questions or issues. I have one, which I hope will lead me to writing up some instructions in the mame2003-plus docs.

For this game `sinistar` if you have analog controls as part of your retropad everything works well.

If you are using digital controls, MAME provides a way to do that mapping and calibrate the sensitivity. That isn't working, at least in this case. Rather than try to fix the MAME digital-to-analog code, I would like to write up instructions on how to use the native libretro/RetroArch remapper to accomplish the same thing.

Is it possible for you to summarize in a brief sentence or two to tell the "libretro way" of mapping a digital control (like a D-Pad or keyboard key) to an emulated analog input, and tweaking its sensitivity to fit the game?

If I have a little bit of handholding here I will take that and turn it into docs that many people will use and love!

**Comment by fr500** [comment]
Well, the calibration part wouldn't be available at all. You could expose that as core option or just use the mame value for calibration.

Digital inputs have only on or off state so you would poll the button normally

```
input_state_cb(player_index, RETRO_DEVICE_JOYPAD, 0, RETRO_DEVICE_ID_JOYPAD_L2 )
```

And then you would use the calibration to simulated that input percentage.

**Comment by markwkidd** [comment]
I would have imagined that any core/game with analog inputs that are being played with digital controls via RetroArch might need to be calibrated in this way. Is it possible I have written the question incorrectly?

Sinistar's original analog inputs rotate the ship at a varying rate of speed depending on how far they are pushed. In standalone MAME we can set the sensitivity and speed of a digital control to some happy medium compromise, so that it maybe emulates the original analog control at its halfway point.

Just making double-sure that there is no 'libretro way' before delving into a core option or some such.

**Comment by fr500** [comment]
Are you sure that's analog input? to me it looks like an 8 way switch that varies acceleration depeding on the time that the direction is held.

**Comment by fr500** [comment]
What are we talking about here?
The RetroArch mapper?

Is that being used to map analogs to dpad?

**Comment by markwkidd** [comment]
Well I guess I am not sure, although the MAME OSD code thinks Sinistar handles analog input, and when SapphireTactician switched RetroArch to use a retropad with analog the input was good.

**Comment by markwkidd** [comment]
We want to use the RetroArch mapper to map between a real d-pad or keyboard and an emulated analog input for Sinistar

**Comment by fr500** [comment]
Ah ok, that's a whole different issue. RetroArch issue not core issue.

It's hardcoded to 100% now, I plan to add modifier buttons someday, so with a button held it may be 50% and with another 25%.

**Comment by fr500** [comment]
FWIW, you can't really simulate analog inputs via digital inputs, you always have to make some concessions.

**Comment by markwkidd** [comment]
That makes sense about concessions.

It's good to know where we are on this and where to start looking for a fix for people who want to try anyway. If we want better digital controls for Sinistar for the time being this needs to be handled within mame2003, maybe with a core option.

Thank you for the consultation! I think we kept it nice and focused.

**Comment by fr500** [comment]
I don't think a core option is good in this case. the core has no idea it's being lied about input.
As far as it knows it's receiving analog input.

**Comment by markwkidd** [comment]
Isn't that the difference between RetroPad and RetroPad w/Analog? So the frontend can communicate to the core whether there is real analog input or not?

**Comment by fr500** [comment]
You're getting it wrong
The input devices come from the core, the frontend just selects which one of the core exposed devices is being used (in the core)

If you're using the retroarch mapper to simulate analog input via digital inputs, you're in fact using RETRO_DEVICE_JOYPAD_ANALOG.

The dpad is giving you ANALOG_X_+ 100% whenever it's pressed.
