### ISSUE TITLE
Need some help with Gut's N Glory

### ISSUE THREAD

**Issue by arcadez2003** [libretro/mame2003-plus-libretro#1604]
So here we have an Atari proto a mini game collection more or less the final game being still in dev before it was cancelled...
http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=guts&arcade_only=0&autosearch=1

Without rabbiting on this is a decent game which would be worth adding here, i've nearly got it but need some help 
around how to deal with a ram bank switching call in the memmap any advice would be appreciated thanks
[Guts Wip.zip](https://github.com/libretro/mame2003-plus-libretro/files/11714819/Guts.Wip.zip)

Im assuming the hack is for the slipram but with no notes in the driver im not 100% on that it's good for eprom and klax
but the address values for the slipram are different for guts, i've been working blind so to speak guessing at values and
i've got the game to boot and the sound now works after some tweaks but the game crashes on the level select screen.

Regards.

**Comment by mahoneyt944** [comment]
Nice work. I haven't had time to look at it yet but I'm sure there's something we can do with it.

**Comment by arcadez2003** [comment]
Well fancy that i guess it's one of those xbox or MAME72 issues and  we've had a fair few of those, right if everything is
good then i can just go ahead and add it to the core shortly thanks guys as always cheers.

**Comment by arcadez2003** [comment]
Ok added the game so i guess this can be shutdown now cheers lads.

**Comment by mahoneyt944** [comment]
@arcadez2003 just tried this game out and I'm having an input issue, the coins keep adding up and up for no reason by itself.

**Comment by arcadez2003** [comment]
Alright i'll reopen this @MistyDreams said the game works fine i dunno what build he was using right enough

**Comment by arcadez2003** [comment]
Ah upon further checking i missed that they added a new share here in the sound map 
AM_RANGE(0x16cc00, 0x16cc01) AM_READWRITE(sync_r, sync_w) AM_SHARE(2) AM_BASE(&sync_data)

I'll attempt to update the mem map once again to see if that sorts the problems

**Comment by mahoneyt944** [comment]
@arcadez2003 I think guts would use this, can't test right now though since the build bot is acting up. The "6" should be the jsa audio port in the inputports 
```
atarijsa_init(1, 6, 1, 0x0002);
```

**Comment by arcadez2003** [comment]
Yeah it seems like i made a mistake when originally backporting this game from MAME122 funny how it works in MAME84
but not here, ok i'll switch the driver INIT call to the correct one you've pointed out above and we'll see how it goes :)

**Comment by mahoneyt944** [comment]
Haven't looked but I'm guessing 84 made changes to how the cpus and ports are loaded. 78 seems  like it could be improved in that department.

**Comment by arcadez2003** [comment]
No functional change by switching the jsa call

**Comment by mahoneyt944** [comment]
Fixed the coin issue for me.

**Comment by mahoneyt944** [comment]
When the game loads you get these errors which the games skips but might be a clue to something
![guts-230619-082410](https://github.com/libretro/mame2003-plus-libretro/assets/49591133/18217bd4-637a-44c2-9e6a-2dcf42b3789e)

seems to work fine with the change I posted previously. The coin counts need reset though in the service menu then they track right. Seems like a bootstrap fix could be used but doesn't seem to hurt anything if it's not reset.
![guts-230619-082704](https://github.com/libretro/mame2003-plus-libretro/assets/49591133/d6d196bf-2139-4a5c-a2af-853fb0ddbb78)

**Comment by arcadez2003** [comment]
Yeah same rom errors on load in either of my cores however the screen is pink rather than yellow so is the game now
working for ya in the sense you can coin it up and play it.?? obviously on my end that is not the case it locks up on
the level select

**Comment by arcadez2003** [comment]
Oh thanks for the offer the game works for me using my MAME84 core i only added it to 72 for testing before porting it
across to here i guess we can finally close this down now that the game seems to work fine thanks again for your help

Cheers.

**Comment by mahoneyt944** [comment]
👍 I'll see if I can nail down the right PCs for the speedup too.

**Comment by arcadez2003** [comment]
Aye we'll have to put it down to it being one of those ole mysteries as to why the game was fine for one but not the other :)
