### ISSUE TITLE
Mortal Race One of Ya's Wanna Take A Run At It

### ISSUE THREAD

**Issue by arcadez2003** [libretro/mame2003-plus-libretro#1607]
@mahoneyt944 @MistyDreams 
[mortalr.zip](https://github.com/libretro/mame2003-plus-libretro/files/11941736/mortalr.zip)

Here is a driver supporting Mortal Race it boots to a crosshatch screen but you can hear the game functioning
in the background, the problem is the gfx decryption, basically im trying to use the original setup as the decrypt
code in the latest MAME driver wont work here.

I've been tweaking the tiles rom loading boot values but the best i can get is the gfx rather faint in the background with
the crosshatch still present over the top not ideal :) 

i've reset the values as per the rom loading tables if one of ya's fancies having a crack at this sometime but if ya's dont then 
no big deal as this game is another version of Top Driving which i added recently allbeit with quite a few diffs.

Regards.

**Comment by mahoneyt944** [comment]
I saw this the other day and had a feeling this would pop up here lol. Yeah I have a look.

**Comment by arcadez2003** [comment]
Ha ha yeah you must have the gift of the second sight, i've been dabbling with this for a couple of weeks and everything
i've tried has not as yet worked hence i thought it a good idea to have more eyes on it.

**Comment by arcadez2003** [comment]
This is the problem more or less.........
https://github.com/mamedev/mame/commit/34069f8823c86120534af6637f85bab3b4d734e1#diff-b7d82573b0c4f3865a32ded927cc975b9cf6fe6bced0c47755ed15551dd62a78

I assume these newer style decryption calls wont work for our ole core as if i use the code when Mortal Race was added 
which was after the above change the gfx although viewable are all messed up for both games in the driver hence i decided
likely wrongly to attempt to shoehorn the game into using the older style decryption.

This might be a rabbithole worth steering well clear of :)

**Comment by mahoneyt944** [comment]
The decode will still need expanded for gfx1 due to the stacked gfx1 chips, I'm not entirely sure the proper way to do that but I'd think it would be possible.

**Comment by arcadez2003** [comment]
For reference WIP history  https://github.com/mamedev/mame/pull/11341/commits

**Comment by mahoneyt944** [comment]
I looked over this and in my opinion, we'd have to update the video code to make this work. This game uses layers and priorities which the other games do not use, so likely if we managed to get it going in our current code, it would have a fair amount of video glitches anyhow. The changes don't seem too complex, but up to you if it's worth the effort.

**Comment by arcadez2003** [comment]
I thought a simple tweak to the rom loading and still using the original decryption might have done the job 
i was expecting some video glitches which i was hoping to sort via some video hacks they added when
Twin Brats was supported in the driver.

But as you say this is likely gonna be more complex i'll close this down as i dont wanna lumber ya's with 
a ton of work here, i might look into this again when i have more time then again i might not :)

Regards.!!

**Comment by arcadez2003** [comment]
Hey @MistyDreams thanks for taking the time to look at this it's seems you've more or less nailed it but dont bother with
Twin Brats it totally sucks, due to having zero time for code ATM do you mind if i just leave ya to it.?? im sure you'll have it
more or less 100% soon enough.

Regards

**Comment by mahoneyt944** [comment]
Surely can be added here too, just PR your work. I'm down with a cold right now but I'll merge it no problem.

**Comment by mahoneyt944** [comment]
I was working outside and it was raining on and off and I think I caught something. Pretty miserable right now.

**Comment by arcadez2003** [comment]
Both games seem fine to me some screen positioning issues on the attract but in game totally fine i suppose the sound
levels between the music and sfx could be balanced out better for Mortal Race but apart from these really minor niggles
we can sign off on this.

**Comment by arcadez2003** [comment]
Nae worries i pasted in your changes as per the PR maybe i missed something

**Comment by arcadez2003** [comment]
> just copy both files easiest way

Well i didnae just sail up the clyde in a banana boat as they used to say :) anyway the merge is in and once again let me
say good job on this.

**Comment by arcadez2003** [comment]
> Well i did clean the code up removed the extra stuff i had in for testing ect. If your having issues can look into it is fine my end what games having issues in attract mode?

Both TBH just screen being chopped off on either side really nothing major as i said inga,me there are no issues
one question though does Mighty Warriors eg mwarr share the same video code in our ole core.?? if so we'll need to check it if not then everything will be all good.

**Comment by arcadez2003** [comment]
On first glance mwarr should be fine it's using totally seperate video code as per before the merge.

**Comment by arcadez2003** [comment]
![mortalr](https://github.com/libretro/mame2003-plus-libretro/assets/51386955/ca19cb24-2dc7-4922-abac-e16d33d1d5e7)

**Comment by mahoneyt944** [comment]
May have already covered this, but I saw there are some shift differences between the games and the visible area like you mentioned. not sure if priority issues would cause that but maybe something to check again?

**Comment by mahoneyt944** [comment]
Is it like that on all screens or just the one? We could shift the tilemap if need be with `tilemap_set_scrolldx` and init it for both games to get the right position

**Comment by mahoneyt944** [comment]
Not sure which "tilemap" is off but maybe we can use something like this in the video start.
```
int shift = 0; // set per game
tilemap_set_scrolldx(tilemap, 0-shift, 0);
```

**Comment by mahoneyt944** [comment]
Hmm. Yeah that issue is weird, didn't try stlforce yet. Mortal race seems correct in game just the title screen is off. Could be a simple overscan cutoff? But I'm thinking there's something unique about the title screen not emulated yet, maybe it changes resolutions or something differing from the rest of the game? Either way it's working and looks great. Nice work.

**Comment by mahoneyt944** [comment]
Can we close this now? Not sure if any testing or anything is still needed?
