### ISSUE TITLE
TODO: trim and correct romset names in MAME history file

### ISSUE THREAD

**Issue by markwkidd** [libretro/mame2003-plus-libretro#161]
After sifting through the internet archive for quite a while, the closest `history.dat` to MAME 0.78 I was able to find was created for MAME 0.106.

This version works much better than the current MAME history.dat with mame2003/plus and this dat has mostly correct romset names. Some of the romset names are different between mame2003-plus and MAME 0.106 however.

I'm creating this Issue to have somewhere to keep track of improving `history.dat` as a potential project one day.

**Comment by dankcushions** [comment]
it would be cool to add all the info in history dat to entries in https://github.com/libretro/libretro-database, along with the checksums of the files, etc. i guess displaying it within the MAME osd isn't viable forever.

**Comment by markwkidd** [comment]
Agreed, that should be the ultimate goal.

**Comment by markwkidd** [comment]
I'd like to consolidate this issue into the more general one here: https://github.com/libretro/mame2003-plus-libretro/issues/161
