### ISSUE TITLE
is savestate_features set as intended ?

### ISSUE THREAD

**Issue by barbudreadmon** [libretro/mame2003-plus-libretro#1613]
@mahoneyt944 @arcadez2003 
I noticed some days ago that this core has `savestate_features` set to `basic` at https://github.com/libretro/libretro-super/blob/master/dist/info/mame2003_plus_libretro.info#L20.

Is this value accurately describing the level of savestate support in this core ? I believe it used to be promoted as the only MAME core with netplay/runahead support ?

With recent retroarch versions, this value controls the availability of savestate-based retroarch features : `deterministic` is required for netplay/runahead/preemptive to become available, and i believe `serialized` is the expected value to at least get rewind.

FYI, MAME current has it set to `deterministic`, even though netplay/runahead/preemptive only works on a subset of games.

**Comment by mahoneyt944** [comment]
These supports are hit or miss in this core. We usually add support for games as users bring them up. I don't actually use any of these features so I wouldn't be the best to answer this. I did try netplay awhile ago and it was glitchy at best so I can't promote that feature. savestates work for most games, I've tried anyway. Rewind should work as well.

**Comment by barbudreadmon** [comment]
>Rewind should work as well.

Then you might want to send a PR to set it to `serialized`, otherwise recent versions of retroarch will prevent rewind from being available.

**Comment by mahoneyt944** [comment]
I sent a PR for this core and mame2003. Went with deterministic, if mame current uses it probably good enough for here too id think. Thanks for the heads up.
