### ISSUE TITLE
Possible to Fix Sound in Baku Baku Animal?

### ISSUE THREAD

**Issue by Ploggy** [libretro/mame2003-plus-libretro#1617]
Currently the Game Baku Baku Animal has no sound at all on Mame 2003/Plus, I think it was fixed in later Mame versions, would it be possible to cherry pick that fix from the Newer Mame and bring it to Mame2003/Plus?
It also has slight Graphical issues too but that doesn't effect gameplay at all.

**Comment by arcadez2003** [comment]
I'll look into it sometime it all depends on if the code is backportable and how much graft is involved

**Comment by arcadez2003** [comment]
So no quick fixes i'll likely not have the time for this then, there are some big improvements for these STV games
which we're missing but the workload has always put me off

**Comment by Ploggy** [comment]
Well the game in question runs fullspeed on the WiiU, tho it could just be a particularly light game.
but if its a big undertaking its fine, the game does run, its just missing sound so I can live with that :D

**Comment by arcadez2003** [comment]
It might not be a big undertaking though it could be one line of code we need outta all those commits with 100's of
changes or it could be 10 20 or 30 lines of code, pinning it down is the problem when all the commits dont mention
a specific fix and just say MESS PORTS or whatever.

**Comment by jilou08** [comment]
Hello,

Baku baku animal is a very good game but with the sound it is more fun ...
What we can say exactly for help you ?

**Comment by arcadez2003** [comment]
Too much work closing down
