### ISSUE TITLE
Mame2003plus freezes from time to time with retroarch logs debug

### ISSUE THREAD

**Issue by Kelvfimer** [libretro/mame2003-plus-libretro#1619]
------
Description
‐-----

Hello

I noticed that the emulator freezes from time to time if you have enable logging verbosity on and frontend logging level and core level to debug.

-------
Expected behaviour
-------
Not to freeze

-------
System
-------
Odroid n2+ linux 4.9
Latest retroarch commit 1.16
Latest mame commit 2003-plus https://github.com/libretro/mame2003-plus-libretro/commit/e0f4c66ec4f11f21c1d1607a569e656d6f358137 
It occurs also with previous commits.

‐-------
Repro
--------
Open mame2003-plus with Twin Cobra game or Flying shark game.
Get into retroarch menu=>settings=>logging=>
Set up to on logging verbosity and frontend logging level and core logging level to debug.

Play a few minutes and you will notice the random halts/freezes.

------
Workaround
------
Two workaround

1 raise level to info instead of debug
2 or set up looging verbosity to off

------
Troubleshoot
------
I took retroarch logs and performance counters but i didn't see anything.

Thx

Ps:
I know debug is not recommended setting but the rest of the cores with same settings is not having this performance issue

**Comment by mahoneyt944** [comment]
This is because debug logs too much information too quickly for your platform to keep up.

**Comment by Kelvfimer** [comment]
Oki, as I expected. @mahoneyt944 thx so much. Closing issue.
