### ISSUE TITLE
Sega's Hangon

### ISSUE THREAD

**Issue by arcadez** [libretro/mame2003-plus-libretro#162]
Can someone please give this game a real quick test im mame2003-plus, im expecting it to have no background layers plus the road layer will be missing making this classic game unplayable

edited

**Comment by grant2258** [comment]
You want it tested on mame078?

**Comment by arcadez** [comment]
Sorry i should have said mame2003-plus, just boot the game as soon as you start a level
you'll know if it's broken in this core, i have the code ready to fix it just wanna know if
it's needed here before i push the commit.

**Comment by grant2258** [comment]
hiya mate im on the middle of update to the new retropie. Il try this rom when i get in from work have to leave in 3 minues will test first thing when i get in. My roms should be copied by then too

**Comment by SapphireTactician** [comment]
@arcadez As of commit ed5f466 I can confirm that the backgrounds and road are missing.

**Comment by arcadez** [comment]
Thanks for the heads up fix for this game incoming ;)

**Comment by arcadez** [comment]
Ok game is now fixed graphically and fully playable in mame2003-plus i'll close this issue now

**Comment by arcadez** [comment]
Hmmm got a little buildbot failure after the commit but i think it's all good now

**Comment by SapphireTactician** [comment]
Seems fine to me now.
