### ISSUE TITLE
PGM Puzzli 2

### ISSUE THREAD

**Issue by arcadez2003** [libretro/mame2003-plus-libretro#1621]
So i decided to look at the last couple of IGS games which have a simulation of the ARM7 protection which was
added circa MAME150, long story short i had to bend and mould the code to fit in with not only our PGM prot
handling but for use in 78 generally.

I had to change so much of it around i thought this will never work but on boot the games actually worked
and the code seems to function correctly as so far im upto stage 8 and both versions of Puzzli 2 seem fine 
logically plus gfx and soundwise.

But that was using my MAME84 test core i dont forsee any issues here but @mahoneyt944 @MistyDreams 
can you boot up these games ASP just to lemmie know they're working in this core thanks.

EDIT i did notice the build failed after i added these but checking the logs i see no errors related to the PGM driver
so i assume the build has settled down and compiles again.??

**Comment by arcadez2003** [comment]
Well thanks for taking the time to try these out it's good to know they're working here, as for the debug info it's not
intentional this is likely due to me changing the code slightly as i was not sure how to handle the following.....

#define puzzli2_printf logerror
https://github.com/arcadez2003/mame/commit/98e69b7070d3cbba753ddb5dfdcd0835a12ccc05#diff-963c69488202f769df908878ee29e9ac147a6cfb0c956dda2f3d6281238ced7b

Since we dont use logerror i rolled back on the changes above and kept the debug calls as printf but if that is causing
stuff to showup on the screen i suppose i could silence em by reeming those calls out or simply look at how to add
puzzli2_printf logerror in such as way that this core will be happy with

**Comment by mahoneyt944** [comment]
Convert them to use `log_cb`, `RETRO_LOG_DEBUG`. Lots of examples of this in the code

**Comment by arcadez2003** [comment]
> Convert them to use `log_cb`, `RETRO_LOG_DEBUG`. Lots of examples of this in the code

Sure although ut means extra work for me i've done that many times but that was part of a define like say
		logerror("%02x <- Mask value equal to number of entries (xor table location is %02x)", rawvalue, tableloc);

i wasn't sure if this core would like puzzli2_printf  `log_cb`, `RETRO_LOG_DEBUG` defined on it's own

**Comment by arcadez2003** [comment]
Right one last question boys these are instances of C++ defines in the code i backported examples below..........

			//  clear the return structure
			for (int columns=0;columns<8;columns++)
				for (int rows=0;rows<10;rows++)
					level_structure[columns][rows] = 0x0000;
				
				int num_mask_bits = count_bits(m_row_bitmask);
				int desired_mask = 0;
		        int realrow = get_position_of_bit(m_row_bitmask, currentrow);

Usually it's just a simple case of removing the int call from here and define it above like this..

                        int columns = 0; 
                        int rows = 0;
			for (columns=0;columns<8;columns++)
				for (rows=0;rows<10;rows++)

But try as i might i could not get the build to accept that which makes me worry the code might not make sense in it's
current form.?? i do however have these defines elsewhere in the driver so my question is will the core pick these up
and work correctly.??

static int columns;
static int rows;
static int num_mask_bits;
static int desired_mask;
static int realrow;

Certainly i've been testing the games and they seem correct logically where i would expect problems to pop up should
some of the above code be incorrectly interpreted emulation wise due to me having to remove the int from those defines

**Comment by arcadez2003** [comment]
> > Sure although it means extra work for me i've done that many times but that was part of a define like say logerror("%02x <- Mask value equal to number of entries (xor table location is %02x)", rawvalue, tableloc);
> > i wasn't sure if this core would like puzzli2_printf `log_cb`, `RETRO_LOG_DEBUG` defined on it's own
> 
> logerror was always there just needed a fix for parsing the arguments properly, you can use logerror regardless of this pull req anyway it just didnt pass the arguments properly. It will go to the right place automatically changing ever debug is a head ache that's not needed. Already updated the pgm driver.
> 
> ```
> [libretro DEBUG] (LOGERROR) ICS2115:  8: vctl = 03 (02ad)
> [libretro DEBUG] (LOGERROR) ICS2115:  8: ctl = 00 (02ad)
> [libretro DEBUG] (LOGERROR) ICS2115: KEYON  8 conf:00 vctl:03 a:45d48a8.000 l:00000.0 e:d5c80.0 v:d80 f:22351
> [libretro DEBUG] (LOGERROR) ICS2115:  1: fc = 0184 (12532Hz) (02b6)
> [libretro DEBUG] (LOGERROR) ICS2115:  1: fc = 0184 (12532Hz) (02b9)
> [libretro DEBUG] (LOGERROR) ICS2115:  5: fc = 0569 (44735Hz) (02b6)
> [libretro DEBUG] (LOGERROR) ICS2115:  5: fc = 0569 (44735Hz) (02b9)
> [libretro DEBUG] (LOGERROR) ICS2115:  7: fc = 0205 (16698Hz) (02b6)
> [libretro DEBUG] (LOGERROR) ICS2115:  7: fc = 0205 (16698Hz) (02b9)
> [libretro DEBUG] (LOGERROR) ICS2115:  8: fc = 02b4 (22351Hz) (02b6)
> [libretro DEBUG] (LOGERROR) ICS2115:  8: fc = 02b4 (22351Hz) (02b9)
> [libretro DEBUG] (LOGERROR) ICS2115:  8: vctl = 01 (02ad)
> [libretro DEBUG] (LOGERROR) ICS2115:  8: vstart = 01 (02ad)
> [libretro DEBUG] (LOGERROR) ICS2115:  8: vend = 01 (02ad)
> [libretro DEBUG] (LOGERROR) ICS2115:  8: ctl = 0f (02ad)
> [libretro DEBUG] (LOGERROR) ICS2115:  8: vctl = 03 (02ad)
> [libretro DEBUG] (LOGERROR) ICS2115:  8: conf = 00 (02ad)
> [libretro DEBUG] (LOGERROR) ICS2115:  8: fc = 02b4 (22351Hz) (02b6)
> [libretro DEBUG] (LOGERROR) ICS2115:  8: fc = 02b4 (22351Hz) (02b9)
> [libretro DEBUG] (LOGERROR) ICS2115:  8: saddr = 45 (02ad)
> [libretro DEBUG] (LOGERROR) ICS2115:  8: addrl = 3500 (02b6)
> [libretro DEBUG] (LOGERROR) ICS2115:  8: addrl = 8000 (02b9)
> [libretro DEBUG] (LOGERROR) ICS2115:  8: addrh = d58a (02b6)
> [libretro DEBUG] (LOGERROR) ICS2115:  8: addrh = d48a (02b9)
> [libretro DEBUG] (LOGERROR) ICS2115:  8: endl = 00 (02b9)
> [libretro DEBUG] (LOGERROR) ICS2115:  8: endh = d5c8 (02b6)
> [libretro DEBUG] (LOGERROR) ICS2115:  8: endh = d5c8 (02b9)
> [libretro DEBUG] (LOGERROR) ICS2115:  8: volacc = d800 (02b6)
> [libretro DEBUG] (LOGERROR) ICS2115:  8: volacc = d800 (02b9)
> [libretro DEBUG] (LOGERROR) ICS2115:  8: conf = 00 (02ad)
> [libretro DEBUG] (LOGERROR) ICS2115:  8: vctl = 03 (02ad)
> [libretro DEBUG] (LOGERROR) ICS2115:  8: ctl = 00 (02ad)
> [libretro DEBUG] (LOGERROR) ICS2115: KEYON  8 conf:00 vctl:03 a:45d48a8.000 l:00000.0 e:d5c80.0 v:d80 f:22351
> ```

Yeah i remember when it was changed it certainly added to my workload not that it seemed to be a concern for those
making such alterations to the codebase anyway thanks for sorting this it's saved me some graft which is always good :)

**Comment by arcadez2003** [comment]
Well i can stick em at the top of each call i suppose........

static int puzzli2_take_leveldata_value(UINT8 datvalue)
{
	int num_mask_bits;
    int desired_mask;
    int realrow;

static WRITE16_HANDLER( puzzli2_asic_w )
{
	int columns = 0;
	int rows = 0;

fatalerror calls i'll need to check how we handle those in MAME78

**Comment by arcadez2003** [comment]
> @arcadez2003 fatalerror should handled with any exit(1) at the very least (you just wont know why the exit happened) or you'll end up with a segfault if that condition is hit. Its easy enough to implement dont know if its an oversight or not.

Ok i think this commit should iron out those int calls https://github.com/libretro/mame2003-plus-libretro/commit/1d6b85fee56d87fa2f8e000615476c006cc84bac

As for fatalerror ya think it's exit(1) in MAME78 i'll look into adding that call shortly

**Comment by arcadez2003** [comment]
Alright i've went and added this one https://github.com/libretro/mame2003-plus-libretro/commit/cf23344e522948cc2c1821e2fe2c1983d4824c77 it's adult as for how adult then who knows :)

Right apart from some solitare mahjong games called Dragon World etc etc there is nothing left we can add
without having the ARM7 CPU but i hold out hope some unprotected sets turn up for Do Don Pachi II  Beestorm
Demon Front and The Gladiator Road Of The Sword, it's unlikely after all this time but ya never know what
is out there and what might turn up.
