### ISSUE TITLE
Sigterm is not well supported by MAME 2003-Plus

### ISSUE THREAD

**Issue by schmurtzm** [libretro/mame2003-plus-libretro#1623]
**Problem :** 
In many cases when running mame2003-plus, SIGTERM commands sent to Retroarch doesn't work properly : Retroarch is not exited. This is a different behavior from all the other cores which allow a proper exit.

It could be nice that mame2003-plus supports properly sigterm command too.
This is really useful to support this because on many devices as it allows to close Retroarch and to triggers an auto save state. 

For example on the Miyoo Mini (little handheld linux device), pressing the "menu" button triggers an exit of Retroarch to the OS main menu. As the sigterm doesn't work, the only way to exit Retroarch when running Mame 2003 is to exit Retroarch from the menu instead just pressing the button provided for this purpose. This exit method works with all cores except with MAME 2003-Plus.

**To reproduce :** 
Start Retroarch with mame2003-plus with 1942, send a `pkill retroarch` command.  Normally Retroarch should exit and make a save state (if the  "Auto Save State" option is enabled).

_Example of result with After Burner :_  
```
/ # pkill retroarch
/ # SDL_PrivateQuit          -> nothing happens, the game still runnning after that.
```

**Other observations :** 

sigterm doesn't work with:

>   -  _1942_,_1943_ 
>   -  _After Burner_
>   - arknoid2
>   - shinobi
>   - superman
>   - xmen

But it works with:

> - _Act-Fancer: Cybernetick Hyper Weapon_ 
> - aerofgt
> - batman
> - _Elevator Action Returns_
> - tmnt

So it seems that the behavior of sigterm is different depending the game (different behaviors from different game drivers ?)

**Comment by mahoneyt944** [comment]
I typically use hotkeys for these functions.
`settings->input->hotkeys`
![Screenshot_20230918-163151](https://github.com/libretro/mame2003-plus-libretro/assets/49591133/66a20cb6-637c-4f84-b5a2-0ea8b4bcfaf4)

**Comment by schmurtzm** [comment]
Hi, thank you for the quick answer ! 

It can't be a solution for us ([Onion OS](https://github.com/OnionUI/Onion)) because we have some special features like pressing a long time the menu button will quit RA and pressing a short time will display an UI with the list of last save states made.

However it's interesting to see that by using hotkey feature RA is able to quit properly any Mame2003+ game.

It make me think that may be it's more the Retroarch SIGTERM implementation which is not good and should copy the behavior of this "quit" hotkey.
Is there a way to trigger this hotkey exit function externally from Retroarch ?

**Comment by mahoneyt944** [comment]
Not that I know of, You should move this issue to the retroarch GitHub page. They maybe able to assist you further.

**Comment by mahoneyt944** [comment]
Seems like this should resolve the issue once merged. Safe to close this now?
https://github.com/OnionUI/Onion/pull/1620

**Comment by schmurtzm** [comment]
Hi not really, the real problem is still here and doesn't apply only to Onion.
The sigterm implementation of this core is still not working, what we have done in Onion is a workaround: we use RA network commands to quit Retroarch instead of using a sigterm. Which means that it solve the situation for Onion but the problem is still here for everyone who use a sigterm to close RetroArch (which is a normal way to do that).

So as sigterm should be implemented in this core and should work like any other core, this issue should stay opened.

**Comment by mahoneyt944** [comment]
My understanding is that a sigterm would be handled by the frontend, are there other cores that have integrated a solution for this on the core side?

**Comment by mahoneyt944** [comment]
Should be fixed with this https://github.com/libretro/RetroArch/pull/16854
