### ISSUE TITLE
Cheats for the game "Big Fight - Big Trouble In The Atlantic Ocean".

### ISSUE THREAD

**Issue by alexb3d** [libretro/mame2003-plus-libretro#1630]
[Pugsy cheats](http://cheat.retrogames.com/) for MAME have cheats for the game "Big Fight - Big Trouble In The Atlantic Ocean" Please could you include them.

This is the xml code for Pugsy:

```
<mamecheat version="1">

  <cheat desc="Infinite Time">
    <script state="run">
      <action>maincpu.pb@E1E3=63</action>
    </script>
  </cheat>

  <cheat desc=" "/>

  <cheat desc="P1 Infinite Lives">
    <script state="run">
      <action>maincpu.pb@E00D=09</action>
    </script>
  </cheat>

  <cheat desc="P1 Infinite Energy">
    <script state="run">
      <action>maincpu.pw@E01E=00D0</action>
    </script>
  </cheat>

  <cheat desc="P1 Select Character"> <comment>Use on or before the player selection screen</comment>
    <parameter>
      <item value="0x10">Kevin</item>
      <item value="0x11">Gear</item>
      <item value="0x12">Zill</item>
      <item value="0x14">Garuda</item>
      <item value="0x15">Mevella</item>
      <item value="0x16">Gonza</item>
      <item value="0x17">Chen</item>
      <item value="0x18">Fharoah</item>
      <item value="0x19">#Dr.D</item>
      <item value="0x1A">#TX-No.3</item>
    </parameter>
    <script state="run">
      <action>maincpu.pb@1573=param</action>
    </script>
  </cheat>

  <cheat desc="P1 Select Colour"> <comment>Use on or before the player selection screen</comment>
    <parameter>
      <item value="0x00">Default</item>
      <item value="0x0F">Alternate</item>
      <item value="0x01">Secret (Kevin Only)</item>
    </parameter>
    <script state="run">
      <action>maincpu.pb@1575=param</action>
    </script>
  </cheat>

  <cheat desc=" "/>

  <cheat desc="P2 Infinite Lives">
    <script state="run">
      <action>maincpu.pb@E04D=01</action>
    </script>
  </cheat>

  <cheat desc="P2 Infinite Energy">
    <script state="run">
      <action>maincpu.pw@E05E=00D0</action>
    </script>
  </cheat>

  <cheat desc="P2 Select Character"> <comment>Use on or before the player selection screen</comment>
    <parameter>
      <item value="0x10">Kevin</item>
      <item value="0x11">Gear</item>
      <item value="0x12">Zill</item>
      <item value="0x14">Garuda</item>
      <item value="0x15">Mevella</item>
      <item value="0x16">Gonza</item>
      <item value="0x17">Chen</item>
      <item value="0x18">Fharoah</item>
      <item value="0x19">#Dr.D</item>
      <item value="0x1A">#TX-No.3</item>
    </parameter>
    <script state="run">
      <action>maincpu.pb@1577=param</action>
    </script>
  </cheat>

  <cheat desc="P2 Select Colour"> <comment>Use on or before the player selection screen</comment>
    <parameter>
      <item value="0x00">Default</item>
      <item value="0x0F">Alternate</item>
      <item value="0x01">Secret (Kevin Only)</item>
    </parameter>
    <script state="run">
      <action>maincpu.pb@1579=param</action>
    </script>
  </cheat>

</mamecheat>
<!-- Cheat file downloaded from http://www.mamecheat.co.uk, see cheat.txt for list of contributors. -->
```

Taking reference from other games, I tried to create them without success, copying this in the cheat.dat file but it doesn't even read them.

```
; [ Big Fight - Big Trouble In The Atlantic Ocean ]
bigfight:0:E1E3:63:000:Infinite Time
:bigfight:62000001:000000:00000000:00000000:Select Character PL1
:bigfight:00010001:1573:00000000:FFFFFFFF:Kevin
:bigfight:00010001:1573:00000001:FFFFFFFF:Gear
:bigfight:00010001:1573:00000002:FFFFFFFF:Zill
:bigfight:00010001:1573:00000003:FFFFFFFF:Garuda
:bigfight:00010001:1573:00000004:FFFFFFFF:Mevella
:bigfight:00010001:1573:00000005:FFFFFFFF:Gonza
:bigfight:00010001:1573:00000006:FFFFFFFF:Chen
:bigfight:00010001:1573:00000007:FFFFFFFF:Fharoah
:bigfight:00010001:1573:00000009:FFFFFFFF:#Dr.D
:bigfight:00010001:1573:00000010:FFFFFFFF:#TX-No.3
:bigfight:0:E00D:09:000:Infinite Lives PL1
:bigfight:0:E01F:68:000:Infinite Energy PL1
```

**Comment by arcadez2003** [comment]
This game was playable before the XML style cheats came in circa MAME126 i suppose if we're lucky we might 
be able to snag compatable cheats for Big Fight from MAME125

**Comment by arcadez2003** [comment]
Ok using examples from our older style cheats i've attempted to mod the values for Big Fight to what MAME78
would expect this is pure guesswork but it might work out try this and let me know either way

; [ Big Fight - Big Trouble In The Atlantic Ocean ]
bigfight:0:E1E3:63:000:Infinite Time
bigfight:0:E00D:09:000:Infinite Lives PL1
bigfight:0:E01F:68:000:Infinite Energy PL1
bigfight:0:E04D:01:000:Infinite Lives PL2
bigfight:0:E05F:68:000:Infinite Energy PL2

**Comment by alexb3d** [comment]
Thank you so much! Thank you very much, I can't activate it.

I copy this code right between "; [ Big Event Golf ]" and "; [ Big Karnak ]". To keep the alphabetical order. I load the game and try to activate a cheat.

I get a warning "there are no cheats for this game".

What am I doing wrong?

**Comment by arcadez2003** [comment]
Hmm i dunno i assume you have the cheat.dat in the correct folder this core expects to find em and the cheats work
for your other games.??

@mahoneyt944 @MistyDreams assuming the above are there any other steps i dont know about with regards to
adding new cheats for use in this core.??

**Comment by mahoneyt944** [comment]
Copy new cheats into cheat.dat, delete cheat.rzip. reload the core.

**Comment by arcadez2003** [comment]
> This core loads cheats from cheat.rzip a compressed format of cheat.dat
> 
> Copy new cheats into cheat.dat, delete cheat.rzip. reload the core. This will create a new cheat.rzip from the new cheat.dat.

Thanks man so @alexb3d do the above then the cheats should then work

**Comment by alexb3d** [comment]
@arcadez2003  @mahoneyt944 Ya están funcionando. Muchas gracias!

Entonces, los que hice al principio estaban bien por los menos los de infinite, voy a intentar añadir los trucos de selección. Si tengo éxito estarpe por aquí.

**Comment by arcadez2003** [comment]
Ok then another happy ending so i guess this can be closed now.

**Comment by alexb3d** [comment]
The cheats for **Select Character** and **Select Colour** are still missing, but if it is not possible to port them, it is closed.

**Comment by mahoneyt944** [comment]
Not showing up or not working? If they are not showing up then you probably have a format error. Not working means it's a bad cheat.

**Comment by alexb3d** [comment]
@mahoneyt944 are not converted.
The pugsy .xml has:
Infinite Time
Infinite Lives
Infitine Energy
Select Character
Select Colour

The code that @arcadez2003 sent me only has:
Infinite Time
Infinite Lives
Infitine Energy

**Comment by alexb3d** [comment]
I think I got it. :O  
I tested them and they work. I only encountered one drawback, the last two characters (I guess they are bosses) have no color, but #Dr.D when you select the alternate color, you see a blue layer.

Please can you check it.

```
; [ Big Fight - Big Trouble In The Atlantic Ocean ]
bigfight:0:E1E3:63:000:Infinite Time
bigfight:0:E00D:09:000:Infinite Lives PL1
bigfight:0:E01F:68:000:Infinite Energy PL1
:bigfight:62000000:000000:00000000:00000000:Select Character PL1
:bigfight:00010000:1573:00000010:FFFFFFFF:Kevin
:bigfight:00010000:1573:00000011:FFFFFFFF:Gear
:bigfight:00010000:1573:00000012:FFFFFFFF:Zill
:bigfight:00010000:1573:00000014:FFFFFFFF:Garuda
:bigfight:00010000:1573:00000015:FFFFFFFF:Mevella
:bigfight:00010000:1573:00000016:FFFFFFFF:Gonza
:bigfight:00010000:1573:00000017:FFFFFFFF:Chen
:bigfight:00010000:1573:00000018:FFFFFFFF:Fharoah
:bigfight:00010000:1573:00000019:FFFFFFFF:#Dr.D
:bigfight:00010000:1573:0000001A:FFFFFFFF:#TX-No.3
:bigfight:62000000:000000:00000000:00000000:Select Colour PL1
:bigfight:00010000:1575:00000000:FFFFFFFF:Default
:bigfight:00010000:1575:0000000F:FFFFFFFF:Alternate
:bigfight:00010000:1575:00000001:FFFFFFFF:Secret (Kevin Only)
bigfight:0:E04D:01:000:Infinite Lives PL2
bigfight:0:E05F:68:000:Infinite Energy PL2
:bigfight:62000000:000000:00000000:00000000:Select Character PL2
:bigfight:00010000:1577:00000010:FFFFFFFF:Kevin
:bigfight:00010000:1577:00000011:FFFFFFFF:Gear
:bigfight:00010000:1577:00000012:FFFFFFFF:Zill
:bigfight:00010000:1577:00000014:FFFFFFFF:Garuda
:bigfight:00010000:1577:00000015:FFFFFFFF:Mevella
:bigfight:00010000:1577:00000016:FFFFFFFF:Gonza
:bigfight:00010000:1577:00000017:FFFFFFFF:Chen
:bigfight:00010000:1577:00000018:FFFFFFFF:Fharoah
:bigfight:00010000:1577:00000019:FFFFFFFF:#Dr.D
:bigfight:00010000:1577:0000001A:FFFFFFFF:#TX-No.3
:bigfight:62000000:000000:00000000:00000000:Select Colour PL2
:bigfight:00010000:1579:00000000:FFFFFFFF:Default
:bigfight:00010000:1579:0000000F:FFFFFFFF:Alternate
:bigfight:00010000:1579:00000001:FFFFFFFF:Secret (Kevin Only)
```

**Comment by mahoneyt944** [comment]
Knowing the behavior of other games that use alternate palettes for player selectable characters, it's quite possible there isn't an alternate palette for the boss characters. Does this functionality work in newer mame or is it only in this core this issue occurs?

**Comment by alexb3d** [comment]
Por eso pienso que son jefes, no tienen mas paletas.
Si, lo he probado el MAME actual, y tiene la misma capa azul.

**Comment by mahoneyt944** [comment]
That's likely the case then.
