### ISSUE TITLE
Dragoon might (dragoona.zip) is not supported or its a bug?

### ISSUE THREAD

**Issue by kounabi22** [libretro/mame2003-plus-libretro#1645]
Dragoon might (dragoona.zip) is not supported or its a bug?because i see Dragoon might (japan) is supported.

**Comment by grant2258** [comment]
It should work the same as dragoonj by adding the rom to the driver to be honest. Is there much difference between the two versions?

**Comment by kounabi22** [comment]
It have english text and thr blood is green.

**Comment by arcadez2003** [comment]
Just missed it by looks 

0.79: R. Belmont added Dragoon Might (ver AAB).

**Comment by grant2258** [comment]
delete your nvram/dragoonj.nv file (make sure mame is closed when you do thus) It will create the nvram properly next time you run the game in mame.
 
violent level 2 in the service mode menu sets the blood green in the service menu, something must have changed your settings. The writing is not in English (not all of it) for me for me. 



![Screenshot from 2023-10-21 13-58-13](https://github.com/libretro/mame2003-plus-libretro/assets/136645825/7418fae5-582c-49c4-9a35-d20f5be85321)
![Screenshot from 2023-10-21 08-30-40](https://github.com/libretro/mame2003-plus-libretro/assets/136645825/3846550d-f9b5-4651-8060-0bafea49d264)
![Screenshot from 2023-10-21 08-27-10](https://github.com/libretro/mame2003-plus-libretro/assets/136645825/9349a82e-c2b4-4858-b205-0ae8a6eb24f1)

**Comment by arcadez2003** [comment]
Here is the support for the English set if someone wants to add it just need to add the rom decs to driver.c
[kongx.zip](https://github.com/libretro/mame2003-plus-libretro/files/13060758/kongx.zip)

They removed the speedhack when adding this set i've left it in but i'd assume it'll only work with 
the japan set so this verison will be slower same deal with Fantastic Journey only lower spec devices
would notice this.

**Comment by grant2258** [comment]
Ill add the sets from mame current shortly, just need to pop into tescos.

**Comment by kounabi22** [comment]
yes it works , ty
