### ISSUE TITLE
libretro adin

### ISSUE THREAD

**Issue by grant2258** [libretro/mame2003-plus-libretro#1655]
```
@grant2258 I have received many complaints over the past few months regarding back and forth behavior between you and HaploCalypse. Personally I feel this arguing is completely pointless, it is the equivalent of arguing how many angels can stand on the head of a pin. Instead, what seems to be going on is some kind of personal slight and arguments and theories being weaponized to try to 'get back' at them. This personal antagonism against Haplocalypse and other fbneo devs has got to stop. Please don't do this anymore, none of this drama and these personal slights and beefs helps the emulation scene in any way.

Let us just get back to doing retro emulation coding instead of arguing over pointless things like this. Personal arguments should not further devolve into pointless arguments where we try to 'own' someone with some slight technicality that doesn't even matter.

If this behaviour continues we will need to start moderating, and I hope instead we can rely on all of you to be functioning adults instead that can leave personal grievances and ad hominems to the side and just focus on the actual code instead. If you don't like a person, ignore him and stay out of his way, and don't respond to the person. That way not everyone gets dragged down into a pool of pointless drama where people have to suddenly start to pick sides.
```
I havent spoken to anyone in libretro in months so apart from @mahoneyt944  and @arcadez2003 i have no idea what your talking about and its getting a bit old with you making excuses and doing the same thin every time with barbudreadom. He constantly acts out you lock subject and make stuff up. I also have no idea who HaploCalypse is. I agree the subject is closed for the licensing but the other stuff I have no idea what your talking about. Github isint the place for this but making statements like this then locking just puts fuel on the fire. We dont have issues as we dont talk so stop the usual trend im only concerned about licensing. He the one calling me a nut case and preaching licensing yet your lecturing me.

**Comment by mahoneyt944** [comment]
@grant2258 are you on discord or anything so I can DM you?

**Comment by grant2258** [comment]
I dont use discord or social media and to be honest, I have no issues with you or libretro admin. I see no need for private conversation on a public platform. Not interested in getting into all this left for a good while when my dad died and come back to this nonsense.

**Comment by mahoneyt944** [comment]
No problem, sorry to hear.

libretro voiced some concern about the interaction in the fbneo repository. Obviously we want to keep the peace between the parties, so in an attempt to do so, I ask that you initiate any of your concerns in this repository

**Comment by grant2258** [comment]
@mahoneyt944 I did bring it up here libretro admin made accusations that im not even aware of. I also told the fbneo dev in that thread to bring and issues up here as well.

**Comment by mahoneyt944** [comment]
Libretro, nor I see any issue with the licensing. So I do not believe any action will be required to amend at this time but I appreciate the willingness to correct the potential situation.

I will look into these other accusations you mentioned and get back to you.

I'm not telling you where you can and cannot comment, you're free to do so. But I will say there historically has be tension from time to time with members of fbneo and members from here which doesn't offer much value to anyone. I'm sure you don't want any unnecessary drama for something you do as a hobby either. So we just want to keep the peace. I'm simply offering a hassle free solution to voice your concerns here where I'd be happy to help. I hope that doesn't come off in a negative light, because I just want to help resolve some of these concerns peacefully.

**Comment by grant2258** [comment]
Only one person involved here and i explained the licensing dont talk to any other fbneo members and happen to think they are all nice talented people dink makes the project work. If there is one person complaining dont make it many.

**Comment by mahoneyt944** [comment]
barbudreadom is haplo so that maybe where that confusion came from. For reference anyways. Any who, the licensing is fine. so no worries

**Comment by arcadez2003** [comment]
Late to the party so to speak and not wanting to get involved "which is unlike me i know" im just curious as to
what the licensing issue was related too

**Comment by arcadez2003** [comment]
> barbudreadom is haplo so that maybe where that confusion came from.... Any who, the licensing is fine. so no worries

Well that clears it up then if i had £10 for everytime he has a dig at this project i'd worth be a fair few bob by now :)

Anyway a bit rich to complain to libretro admin about grants behavour apparantly while at the same time using 
discriminatory language towards him such as this.....

"You really are a nutcase"

That in itself should invalidate any complaint.!!

Anyway i'll leave it at that as my views on those of tittle tattle to others have got me into trouble in the past LOL.

**Comment by Wilstorm** [comment]
@grant2258 - I'm sorry to hear about your Dad. I lost mine 13 years ago, real suddenly, and there isn't a day that goes by I don't wish for a moment of his time. I don't know if it ever goes away, but you get used to the pain, and you'll even have a good day here and there, hopefully. Hang it there, I'll keep you in my prayers, in regards to.

Yeah, "nutcase" (I read the thread), I agree with @arcadez2003 that is seriously old school derogatory slang...I haven't heard that in years. I'll never get some people and walking with the trash talk, I've seen it more than once. Try that in a professional, in person setting and HR would kindly walking your ass to the door. Some, just get to keep doing it... man, what I wouldn't give to do it old school in a dark alley. Some times the old ways are the best ways. I still think you guys are the saints of skid row.

I agree, Dink has always been kind and helpful, he has a good heart and makes FBNeo what it is... I also do believe for the most part the scene has good folks and I thank them for keeping it alive. I'll always take my hat off to the OG "trio" of this core... arcadez, grant & Mark.

Well, hmmm... "Please just talk into this tin can, hooked to a string, and know that it goes nowhere and no-one will ever hear your concerns, thank you." In a word, subjection... repression? Email or DM me... I'll be sure to "file 13" it after I tell you what and how to think... at best, akin to the politic landscape of today. I always thought you were just spirited about retro gaming and this was your "Moby Dick" if you know the novel. Thanks for keeping it real and keeping it alive, I'm looking forward to trying out a Pi 5 at some point... I think the back order is out to February...

**Comment by grant2258** [comment]
You know how the rodeo goes @arcadez2003 more interested in nipping any issues with the core than giving a crap about some guy crying wolf when acting like a stupid wee boy, making storys up and silence people. 

@Wilstorm its been a while since it happened just a few weeks after my cat died so its not too bad just have to get get on with things, there was no big reason for leaving just real life takes over. Im not really active much at all just fixed the mame build for libretro a few months back for libretro. I dont have much to say about the situation its the same shit different accusation. Was looking at the pi5 myself but waiting to make sure the first batches are good since the early pi 4 had issues.
