### ISSUE TITLE
Track & Field trackball hack?

### ISSUE THREAD

**Issue by wn2000** [libretro/mame2003-plus-libretro#1657]
See related discussions here:
https://www.reddit.com/r/MAME/comments/102ldoa/track_and_field_trackball/

Basically there was an aftermarket conversion kit that turns trackball input into button presses.

I'm thinking that this could be done in the libretro input layer: Read mouse events and fake button presses.

Anyone interested or have better ideas?

**Comment by wn2000** [comment]
I'm giving this a spin :-) Trying with `88games`.

I see there's an existing hack in the driver that adds a fake button 4.

https://github.com/libretro/mame2003-plus-libretro/blob/eddec6d603a21d5620ff6a2cb890ec90133cdb02/src/drivers/88games.c#L179-L180

When pressed, it alternates button 1 and 3 presses in every frame.

https://github.com/libretro/mame2003-plus-libretro/blob/eddec6d603a21d5620ff6a2cb890ec90133cdb02/src/drivers/88games.c#L79-L84

So my idea is to add a fake ANALOG port. Then whenever the reading from that analog port is large enough, do the same button1/button3 alternation.

I added the following after the player1-4 buttons (used `IPT_AD_STICK` as I'm testing with an Xbox controller first, will change to  trackball if it works):
```
PORT_START
PORT_ANALOG(0xff, 0x00, IPT_AD_STICK_X, 100, 10, 0, 0)
```
But calling `readinputport(3)` inside `cheat1_r()` always returns 0.

I looked in the TAB menu and saw the ANALOG input showing up, and is mapped to RP1's left analog stick by default.

What else am I missing? How can I get an analog input on this port?

**Comment by mahoneyt944** [comment]
Not familiar with this game, but Port 3 is already in use by the coin selection. You need to add your fake port to a fake port, one the game doesn't already use.

**Comment by wn2000** [comment]
Hmmm I initially added the port to the end, so `readinputport(6)` for example. But that also did not work (always 0).

**Comment by mahoneyt944** [comment]
Curious, can you map the analog stick to the button 4 hack in the mame menu?

**Comment by wn2000** [comment]
> Curious, can you map the analog stick to the button 4 hack in the mame menu?

Yes I just tried that. It works.

The analog stick also works in games like After Burner 2, which uses `AD_STICK_X` etc.

**Comment by mahoneyt944** [comment]
Do you still need a custom analog port or is that sufficient enough?

**Comment by wn2000** [comment]
> Do you still need a custom analog port or is that sufficient enough?

Oh I see what you mean.
I still need a custom analog port.
First, I want to eventually use mouse to control it. As far as I remember mouse cannot be assigned to a button in the MAME menu.
Second, having an analog input is more flexible to control how the speed of scrolling affects the button pressing behavior.
For example, I can accumulate the relative mouse movement over frames, and only issue a button press when it exceeds a certain value.
If I assign an analog control to a button it would only do an analog-to-digital conversion on that particular frame.

Any other idea of adding a fake analog input?

**Comment by wn2000** [comment]
FWIW I got it working on FBNeo.
Still hoping it can work on mame2003 plus as well.

**Comment by wn2000** [comment]
> trackfld input is in it's own driver, I made this branch which assigns some defaults to an analog port and logs onscreen for testing purposes. This should get you started. https://github.com/libretro/mame2003-plus-libretro/compare/Port

Thanks. The on-screen logs are really nice. Didn't know about that.
I saw you added then deleted stuff from 88games driver. I tried to add the port and logging to 88games but it still shows 0, even when the default value for the port is set to 0x80.
Have you tried in 88games? Not sure if I'm missing anything.

**Comment by mahoneyt944** [comment]
I didn't try the 88games driver but it should be the same essentially. I initially added it before checking if trackfld was in that driver, so that's what that was about.. Share your code for 88games and I'll see what's going on.

**Comment by wn2000** [comment]
Thanks it's working now. I initially used the AD_STICK type together with a range min/max of (0, 0), thinking that should mean "no limit", but looks like it literally means "0 to 0". That's why I always get a 0 reading.
Once I set a non-zero range, *or* set the type to TRACKBALL, it starts to get a reading.
Oddly though, if I set the default value of the analog port to 0x7fff, I get a reading of 32766 when the analog control is "centered".
So now I'm setting the default value to 0 and it stays at 0 when not touched.

Current change to 88games:
```diff
--- a/src/drivers/88games.c
+++ b/src/drivers/88games.c
@@ -73,15 +73,36 @@ static READ_HANDLER( cheat1_r )
        int res;
        static int cheat = 0;
        static int bits[] = { 0xee, 0xff, 0xbb, 0xaa };
+       static int motion = 0;
+       bool fake_press = false;
+       int16_t rel_motion;

        res = readinputport(1);

+       /* button 4 "run like hell" cheat */
        if ((readinputport(0) & 0x08) == 0)
+       {
+               fake_press = true;
+       }
+       else
+       {
+               /* track ball input */
+               rel_motion = (int16_t)readinputport(5);
+               motion += abs(rel_motion);
+               if (motion > 100)
+               {
+                       fake_press = true;
+                       motion %= 100;
+               }
+       }
+
+       if (fake_press)
        {
                res |= 0x55;
                res &= bits[cheat];
-               cheat = (cheat+1)%4;
+               cheat = (cheat + 1) % 4;
        }
+
        return res;
 }

@@ -269,9 +290,10 @@ INPUT_PORTS_START( 88games )
        PORT_DIPNAME( 0x80, 0x00, DEF_STR( Demo_Sounds ) )
        PORT_DIPSETTING(    0x80, DEF_STR( Off ) )
        PORT_DIPSETTING(    0x00, DEF_STR( On ) )
-INPUT_PORTS_END
-

+       PORT_START
+       PORT_ANALOG(0xffff, 0, IPT_TRACKBALL_X | IPF_CENTER | IPF_PLAYER1, 100, 10, 0, 0)
+INPUT_PORTS_END
```
Thanks for all the help!

**Comment by mahoneyt944** [comment]
Good 👍
