### ISSUE TITLE
Kiki Kai Kai and Mexico 86

### ISSUE THREAD

**Issue by arcadez2003** [libretro/mame2003-plus-libretro#1661]
Sorry to drop this on ya fellas but since my xbox died im unemulated you could say so have no way of testing
Kiki Kai Kai to make sure it's working fine with the new mcu dump it should be ok with the same hookup as for
Kick N Run but ya never know.

So could one of ya's try it out for me just boot it up and play it a little same deal for Mexico 86 as i need to know it's fine using..

WRITE_HANDLER( kicknrun_f008_w )
{
	cpu_set_reset_line(1,(data & 4) ? CLEAR_LINE : ASSERT_LINE);
	cpu_set_reset_line(2,(data & 2) ? CLEAR_LINE : ASSERT_LINE);

}

Or do i need to retain that dummy CPU call as per how it was originally minus the kiki prot sim call obviously.??

WRITE_HANDLER( mexico86_f008_w )
{
	cpu_set_reset_line(1,(data & 4) ? CLEAR_LINE : ASSERT_LINE);
 	if (Machine->drv->cpu[2].cpu_type != CPU_DUMMY)
	{
		/* mexico 86 */
		cpu_set_reset_line(2,(data & 2) ? CLEAR_LINE : ASSERT_LINE);
	}
        else
	{
		/* simulation for KiKi KaiKai */
	//	kikikai_mcu_running = data & 2;
	//	if (!kikikai_mcu_running)
	//		kikikai_mcu_initialised = 0;
	}
}

Here is the new mcu dump just add it to your kiki kai kai romset and fire it up
[a85-01_jph1020p.zip](https://github.com/libretro/mame2003-plus-libretro/files/13843474/a85-01_jph1020p.zip)

Thanks in advance and fingers crossed for the mcu as the game is broken without it.

**Comment by grant2258** [comment]
Getting a error screen big yean by defaut,

![Screenshot from 2024-01-06 00-48-04](https://github.com/libretro/mame2003-plus-libretro/assets/136645825/0f89eb10-cbc9-45be-85a7-e2cb05a83b51)


WRITE_HANDLER( kicknrun_f008_w )
{
cpu_set_reset_line(1,(data & 4) ? CLEAR_LINE : ASSERT_LINE);
if (Machine->drv->cpu[2].cpu_type != CPU_DUMMY)
{
/* mexico 86 /
cpu_set_reset_line(2,(data & 2) ? CLEAR_LINE : ASSERT_LINE);
}
else
{
/ simulation for KiKi KaiKai */
// kikikai_mcu_running = data & 2;
// if (!kikikai_mcu_running)
// kikikai_mcu_initialised = 0;
}
}

just gives a black screen

**Comment by arcadez2003** [comment]
Hi thanks for trying @grant2258 i assume that pic is for Mexico 86.?? does kiki kai kai work with the same hookup 
as used for Kick N Run....

WRITE_HANDLER( kicknrun_f008_w )
{
cpu_set_reset_line(1,(data & 4) ? CLEAR_LINE : ASSERT_LINE);
cpu_set_reset_line(2,(data & 2) ? CLEAR_LINE : ASSERT_LINE);
}

Mexico86 is just a bootleg of Kick N Run we can worry about that one later.

**Comment by grant2258** [comment]
I only tested  kiki kai kai should i be testing mexico86 ?

**Comment by arcadez2003** [comment]
> I only tested kiki kai kai should i be testing mexico86 ?

Aye i was hoping Kiki would have worked with the same hookup as for Kick N Run...

WRITE_HANDLER( kicknrun_f008_w )
{
cpu_set_reset_line(1,(data & 4) ? CLEAR_LINE : ASSERT_LINE);
cpu_set_reset_line(2,(data & 2) ? CLEAR_LINE : ASSERT_LINE);
}

And whether Mexico 86 still played with the above or needed a CPU DUMMY call in there...

WRITE_HANDLER( kicknrun_f008_w )
{
cpu_set_reset_line(1,(data & 4) ? CLEAR_LINE : ASSERT_LINE);
if (Machine->drv->cpu[2].cpu_type != CPU_DUMMY)
{
/* mexico 86 /
cpu_set_reset_line(2,(data & 2) ? CLEAR_LINE : ASSERT_LINE);
}
else
{
/ simulation for KiKi KaiKai */
// kikikai_mcu_running = data & 2;
// if (!kikikai_mcu_running)
// kikikai_mcu_initialised = 0;
}
}

Kiki wont work with the above as the DUMMY Call would throw it off i think it's for the 3+4 player inputs which
can be accessed in Kicknrun / mexico86 dips so im thinking we need to retain that for Mexico86

This is a bummer ya know as i was expecting Kiki to hang off the Kick N Run M6801 hookup it should do i wonder
what the problem is.?? more study required .

**Comment by arcadez2003** [comment]
Right as per these commits im hoping both Kiki Kai Kai and Mexico86 will be good to go....
https://github.com/libretro/mame2003-plus-libretro/commit/70c76b9cdcd937eeae5fc566bee12e603ddf3fdb
https://github.com/libretro/mame2003-plus-libretro/commit/43b5d1f40e0ec591d36d0212076884caa76dc9f7

Fingers crossed and im sorry to bother ya with this i need to get a setup where i can compile and test again.

**Comment by grant2258** [comment]
Not any bother been tinkering with this model1 nonsense but vf isint running up to speed on the my 95 core and this core on a  i7 (works fine in mame current) not sure where the bottle neck is at least I got the v60 done though! Now for the good news both games are running fine job well done! (mexico86 and kikikai)

**Comment by arcadez2003** [comment]
Great news big yin and thanks again for testing these, as for Model 1 did you just port the code across from here.??
ifso check the clocks as they'll need to change depending on what version of the V60 your using.

**Comment by grant2258** [comment]
I would normally have taken a look if i wasnt fighting with working out different versions of mame. Honestly I really think I should just update to mame 105 but that would be no fun!.
