### ISSUE TITLE
Tempest has no player 2 buttons or spinner

### ISSUE THREAD

**Issue by rdagger** [libretro/mame2003-plus-libretro#1663]
I'm trying to play Tempest on a cocktail table with 2 spinners.  One is on the mouse X axis and the other on the Y axis.
Unfortunately, the input settings only offer player 1 inputs for the spinner and buttons.

Here's the input screen in 2003 plus:
![Mame2003plus_tempest](https://github.com/libretro/mame2003-plus-libretro/assets/106355/0c5864c9-00f2-4574-bf52-4f48740d51cc)

In MAME 2010 you have the input options for separate player 2 buttons and a spinner.

Here's the input screen in 2010.
![Mame2010_Tempest](https://github.com/libretro/mame2003-plus-libretro/assets/106355/96a81f93-ccca-48a5-9435-8a6c38961b7e)

The video quality is much better in 2003 plus.

**Comment by arcadez2003** [comment]
We need this fix from later builds..

0.102u3: RansAckeR fixed cocktail mode and input in Tempest.

I'll look into it sometime

**Comment by mahoneyt944** [comment]
I noticed in the description that the cocktail mode may have been planned but not implemented. Looking at mame2010, it looks like they just replaced the p1 hooks with special ports to essentially inject both players over this port. I imagine with custom read functions and a little bit of logic to check against the cocktail DSW this should work out.

**Comment by arcadez2003** [comment]
Yeah i just noticed this...
0.112: Stephane Humbert updated Tempest to support 2nd Player controls.

The first fix above is for the screen flipping and this one will add the 2nd input by looks

**Comment by mahoneyt944** [comment]
I patched in the cocktail controls, to what I believe it should be for this core. https://github.com/libretro/mame2003-plus-libretro/commit/99644ccca84ea7eb1630d5af7b01b22a88824bc8

Still needs the fix for screen flipping, bugs out slightly when you pick the level difficulty.

@rdagger are you basically using a single mouse as two spinners? P1x and P2y?

**Comment by mahoneyt944** [comment]
@arcadez2003 the flip screen is still a little buggy not sure what that fix was exactly but likely need it too

**Comment by arcadez2003** [comment]
@mahoneyt944 This is the fix circa MAME102.u3 
https://github.com/libretro/mame2003-plus-libretro/commit/c3e15ebd518a1f32f869cb46dd789ede80c16e4a

**Comment by rdagger** [comment]
@mahoneyt944 I'm using a single mouse as two spinners.  Thanks!

**Comment by mahoneyt944** [comment]
That's probably all it needed!, thanks @arcadez2003 for getting that solved. @rdagger is everything good on your end? can we close this?

**Comment by rdagger** [comment]
@mahoneyt944 won't be able to test for a few days, but it sounds great, thanks guys!

**Comment by mahoneyt944** [comment]
@arcadez2003 update, unfortunately still bugging out a little. Noticed bumping the dial can cause it to correct. So might just be a conflict reading the port when it switches.

**Comment by arcadez2003** [comment]
> @arcadez2003 update, unfortunately still bugging out a little. Noticed bumping the dial can cause it to correct. So might just be interference reading the port when it switches.

Aye it might just be

**Comment by mahoneyt944** [comment]
Yeah it's something like that, if you don't move the cocktail dial it bugs out on the player 2 level select, moving the dial corrects the issue. Probably need to log this port and see what's happening.

**Comment by mahoneyt944** [comment]
For some reason when this port is low it flickers the flip bit as the dials rotates. When switched to high, it works normally but I had to flip the cabinets bits to play nice with it. Seems to work perfect now. https://github.com/libretro/mame2003-plus-libretro/commit/b61da7548eaca13bf091f820e6f83619bddd54fa

I haven't followed the logic of port_custom in newer mame to see how exactly it binds these functions to the port, so perhaps it does a similar inversion behind the scenes? Either way this should do it for tempest here.

**Comment by mahoneyt944** [comment]
I also found that the difficulty dip switch is reversed now. Other than that it plays well, might need a better way of linking the ports than adding them together as I think that's causing the oddity.

**Comment by mahoneyt944** [comment]
Inputs fully working correctly now, #1668 😁

**Comment by rdagger** [comment]
Did a quick test and everything looks great, thanks!

**Comment by arcadez2003** [comment]
Alright then another happy ending so we can close this down.
