### ISSUE TITLE
Donkey Kong Remix

### ISSUE THREAD

**Issue by arcadez2003** [libretro/mame2003-plus-libretro#1672]
Im not really into hacks unless they offer up something substantial over the original game
well having six new extra levels and three new bonus rounds this one fits the bill i reckon.

The original commit is here it's using braze roms and code mostly....
https://github.com/Robbbert/hbmame/commit/c3a1fc65931f661679d75c1db3d2950f8600a5e9

I had to make some changes to the CPU1 plus the USER1 rom loading to use our ole Braze code
for that reason can i ask @mahoneyt944 @grant2258 @MistyDreams if one ya's has a spare
moment can you boot up the game and give it a quick play to make sure everything is good.

No hurry for this and thanks in advance.

**Comment by mahoneyt944** [comment]
I see there's a Christmas addition and a spooky one, are these worth while?

**Comment by grant2258** [comment]
@arcadez2003 dont have these roms to test unfortunately.

**Comment by arcadez2003** [comment]
> I see there's a Christmas addition and a spooky one, are these worth while?

Maybe at Xmas and Halloween ha ha ha

**Comment by arcadez2003** [comment]
> @arcadez2003 dont have these roms to test unfortunately.

i'll see if i can trackdown a romset for it

**Comment by arcadez2003** [comment]
@grant2258 
[tester.zip](https://github.com/libretro/mame2003-plus-libretro/files/14030102/tester.zip)

**Comment by grant2258** [comment]
Bad news its stuck at the title screen

**Comment by arcadez2003** [comment]
Thanks for trying it out well this is a bummer as it should just hang onto the braze dkongx code i 
wonder what is throwing it offside.

**Comment by arcadez2003** [comment]
This likely
https://github.com/libretro/mame2003-plus-libretro/commit/ea3919785d10704ecc9af7120712d9dc301e7c7e

**Comment by mahoneyt944** [comment]
> This likely [ea39197](https://github.com/libretro/mame2003-plus-libretro/commit/ea3919785d10704ecc9af7120712d9dc301e7c7e)

Not this unfortunately.

**Comment by arcadez2003** [comment]
It's likely a banking issue the original commit is here....
https://github.com/arcadez2003/mame/commit/ecab5ab7f9cac30930a3ce1062225afe5fe83a23

Looking at our braze banking code it was extensively rewritten by looks so maybe although it's 
good for dkongx obviously that might not be the case for this version. sometimes the simple 
changes are what's needed i wonder if using the original values for the main CPU and braze 
decrypt will get the job done......

ROM_REGION( 0x10000, "maincpu", 0 )
	ROM_LOAD( "c_5et_g.bin",    0x0000, 0x1000, CRC(ba70b88b) SHA1(d76ebecfea1af098d843ee7e578e480cd658ac1a) )
	ROM_LOAD( "c_5ct_g.bin",    0x1000, 0x1000, CRC(5ec461ec) SHA1(acb11a8fbdbb3ab46068385fe465f681e3c824bd) )
	ROM_LOAD( "c_5bt_g.bin",    0x2000, 0x1000, CRC(1c97d324) SHA1(c7966261f3a1d3296927e0b6ee1c58039fc53c1f) )
	ROM_LOAD( "c_5at_g.bin",    0x3000, 0x1000, CRC(b9005ac0) SHA1(3fe3599f6fa7c496f782053ddf7bacb453d197c4) )

	ROM_REGION( 0x10000, "braze", 0 )
	ROM_LOAD( "dkremix.bin",    0x0000, 0x10000, CRC(f47c13aa) SHA1(c8516e27028d371a1f7b198f6d91f6a10bf99d3f) )

or maybe we need to use a decrypt call directly...
	ROM_REGION( 2*0x20000, REGION_CPU1, 0 )

**Comment by arcadez2003** [comment]
This might sort it or not..
https://github.com/libretro/mame2003-plus-libretro/commit/f1b1412f1b384a4cb68103a9ef06f83d15d40075

**Comment by grant2258** [comment]
its the banking for sure ill have a look after ive had my dinner. From looking at the code its not switch the copy properly if its what i think it is it will be trivial to fix

**Comment by grant2258** [comment]
@arcadez2003 I dont think this copying is working properly for the bankswitches it just keeps the decrypted bank as always set

**Comment by grant2258** [comment]
tried the cpu_setbank dkongx doesnt boot properly dkremix doesnt even request a bank change this is a a todo list item. Ill try when I have time more time will first need to comfirm this actually works on hbmame. If its does Ill need to look up what the later mame code is actually doing with the bank sets because we seem to copy the decrypted offsets at the same index for bank1 and 2 it might be correct though. Dkongx seems to boot on the old code that way but it wont boot with cpu_set_bank it just boots the menu real quick then drops to default dkong.

**Comment by arcadez2003** [comment]
Well this is a right fucker ain't it if i'd known it would be soo much hastle i would not have added
it here but it looked so simple hang it off our braze code and forget about it :)

**Comment by grant2258** [comment]
still have a few things to test one major pain is the eprom read is within the 0x8000. I think core usually just picks the first memory match as we dont have address spaces can try do a workaround for the eprom  at some point.

**Comment by arcadez2003** [comment]
> still have a few things to test one major pain is the eprom read is within the 0x8000. I think core usually just picks the first memory match as we dont have address spaces can try do a workaround for the eprom at some point.

Now funny you mentioned the EEPROM it's just came back to me i rememeber robert talking on the
MAME Chat a couple of years back about how he was attempting to add Donkey kong Remix but there was a problem with the eeprom which was preventing it from working.

**Comment by arcadez2003** [comment]
Also both dkongx and this one are not meant to have traditional dip switches as per games of that era
Circa Donky kong, those are handled via the eeprom data i assume.?? anyway in current MAME the
dips switches are blanked with unknown or unused calls.

Ours are not i noticed likely just copied and pasted from dkong inputs maybe that's what is throwing the game off.??

**Comment by arcadez2003** [comment]
PORT_START      /* DSW0 */
	PORT_DIPNAME( 0x01, 0x01, DEF_STR( Unused ) )
	PORT_DIPSETTING(    0x01, DEF_STR( Off ) )
	PORT_DIPSETTING(    0x00, DEF_STR( On ) )
	PORT_DIPNAME( 0x02, 0x02, DEF_STR( Unused ) )
	PORT_DIPSETTING(    0x02, DEF_STR( Off ) )
	PORT_DIPSETTING(    0x00, DEF_STR( On ) )
	PORT_DIPNAME( 0x04, 0x04, DEF_STR( Unused ) )
	PORT_DIPSETTING(    0x04, DEF_STR( Off ) )
	PORT_DIPSETTING(    0x00, DEF_STR( On ) )
	PORT_DIPNAME( 0x08, 0x08, DEF_STR( Unused ) )
	PORT_DIPSETTING(    0x08, DEF_STR( Off ) )
	PORT_DIPSETTING(    0x00, DEF_STR( On ) )
	PORT_DIPNAME( 0x10, 0x10, DEF_STR( Unused ) )
	PORT_DIPSETTING(    0x10, DEF_STR( Off ) )
	PORT_DIPSETTING(    0x00, DEF_STR( On ) )
	PORT_DIPNAME( 0x20, 0x20, DEF_STR( Unused ) )
	PORT_DIPSETTING(    0x20, DEF_STR( Off ) )
	PORT_DIPSETTING(    0x00, DEF_STR( On ) )
	PORT_DIPNAME( 0x40, 0x40, DEF_STR( Unused ) )
	PORT_DIPSETTING(    0x40, DEF_STR( Off ) )
	PORT_DIPSETTING(    0x00, DEF_STR( On ) )
	PORT_DIPNAME( 0x80, 0x80, DEF_STR( Unused ) )
	PORT_DIPSETTING(    0x80, DEF_STR( Off ) )
	PORT_DIPSETTING(    0x00, DEF_STR( On ) )
INPUT_PORTS_END

Worth a try i suppose

**Comment by grant2258** [comment]
no luck with the buttons on and off. I think ill try this on my port and see if its comes to life. If its not too much work will test if the dma update will fix this issue.

**Comment by arcadez2003** [comment]
It seems this is not the official version of the game......

"After a long talk with sock master last night, HE confirmed this was NOT his game that he sells retail. After looking at the roms, he said someone took the "Christmas Edition" of Remix, and reverse engineered it to make it look and play like the original remix. He said there was a LOT of work to accomplish this, and that it was not just a graphics hack. The person that hacked it had to be very familiar with Z80 programming. At first, he thought someone dumped his roms from the board, and was not happy about it, but after digging in to it, and seeing what all the person did, he seemed pretty happy."

**Comment by grant2258** [comment]
thanks for the update @arcadez2003  ive been trying some things in the background. I was wondering why the service mode wasnt working on mame current. Regardless there is some issue that needs fixed I really need a debugger and z80 reference its been a while since my spectrum days!

**Comment by arcadez2003** [comment]
I've asked excalibur to try it out using my original commits in MAMEoXtras just to see if it plays there

**Comment by grant2258** [comment]
I did test it on the port I did I havent done the extra memory maps though but dkongx works as is and remix still fails my spidey senses say its related to the dma failure we can see in donkey x screen but can pass it pressing a button.

**Comment by arcadez2003** [comment]
hey there
good news i managed to get donkey kong remix to boot up and play.its working fine on the core and that includes sound.

this is what i did,btw this method worked with all the dipswitches turned off and also turned on.if that is any help.

once the game boots up and gets to the screen where it just hangs do the following

1.go into the ingame menu and go to the reset option and reset the game.
2.then on the xbox controller you have to insert a credit just after you have reset the game but you you then need to hit the start button very quickly.its a quick button press on both one after another.

**Comment by grant2258** [comment]
doesnt seem to work on plus or my core. The service modes arent working either service and service1 isint inserting a coin.

**Comment by arcadez2003** [comment]
Yes @grant2258 some progress which is always good, im using my original code minus your banking
changes i defo think now that the issue is either the Eeprom saving or the inputs being wrong which is
throwing off the service mode.

But ofcourse as i always say i could be wrong :)

**Comment by grant2258** [comment]
Well unless your differs from plus im not sure why we can reproduce a boot our end

**Comment by grant2258** [comment]
on another note on first boot the sound comes before the freeze on resetting no sound work. Tried setting mcustaus and setting the banks to no avail. I think ill justy look at the dma I cant get this to boot at all with your instructions so will just plod on.

**Comment by arcadez2003** [comment]
@grant2258 i've sent a tester to xcalibur where i've changed the IN2 inputs to match up with later MAME

PORT_START /* IN2 */
PORT_BIT( 0x01, IP_ACTIVE_HIGH, IPT_UNKNOWN ) /* connection not labeled in schematics - reset */
PORT_BIT( 0x02, IP_ACTIVE_HIGH, IPT_UNKNOWN ) /* connection not labeled in schematics - freeze or reset */
PORT_BIT( 0x04, IP_ACTIVE_HIGH, IPT_START1 )
PORT_BIT( 0x08, IP_ACTIVE_HIGH, IPT_START2 )
PORT_BIT( 0x10, IP_ACTIVE_HIGH, IPT_SERVICE ) /* not connected - held to high - used as service */
PORT_BIT( 0x20, IP_ACTIVE_HIGH, IPT_UNKNOWN ) /* not connected - held to high */
PORT_BIT( 0x40, IP_ACTIVE_HIGH, IPT_SPECIAL ) /* status from sound cpu */
PORT_BIT( 0x80, IP_ACTIVE_HIGH, IPT_COIN1 )

It's just since it seems to freeze then need a reset and has coin troubles from what i hear this is the
area which would control all that

**Comment by grant2258** [comment]
That wont have any effect on my port as I had and would need to press the service key. I did compile it and check for you to confirm though I doesn't make a difference you input might be different though. I cant seem to get plus to boot at all though might have to add a keyboard reset to the core or add the reset menu back to test cant to do it quick enough just used f3 then coin on my core.  As for the colors I hear you but I think and golden orange iron bru shade would be the dogs bollox for the gurders :) 


```
	PORT_START      /* IN2 */
	PORT_BIT( 0x01, IP_ACTIVE_HIGH, IPT_SERVICE ) PORT_NAME(DEF_STR( Service_Mode )) PORT_CODE(KEYCODE_F2)
	PORT_BIT( 0x02, IP_ACTIVE_HIGH, IPT_UNKNOWN )
	PORT_BIT( 0x04, IP_ACTIVE_HIGH, IPT_START1 )
	PORT_BIT( 0x08, IP_ACTIVE_HIGH, IPT_START2 )
	PORT_BIT( 0x10, IP_ACTIVE_HIGH, IPT_UNKNOWN )
	PORT_BIT( 0x20, IP_ACTIVE_HIGH, IPT_UNKNOWN )
	PORT_BIT( 0x40, IP_ACTIVE_HIGH, IPT_SPECIAL )	/* status from sound cpu */
	PORT_BIT( 0x80, IP_ACTIVE_HIGH, IPT_COIN1 )

```

**Comment by grant2258** [comment]
here is a patch to boot and insert a credit. It does work on plus as well

```
static int bitty=0;

static READ_HANDLER( dkong_in2_r )
{
	if (bitty ==3 ) 
	{
		bitty++;
		return 0x80;
	}
	bitty++;
	return input_port_2_r(offset) | (mcustatus << 6);
}
```

**Comment by arcadez2003** [comment]
Aye a workaround to bypass some issues is in many ways as good as a fix, you've had your Irn Bru
the night by looks :)

**Comment by grant2258** [comment]
I think this is a symptom of a problem else where to be honest I checked the mame and it logs zeros straight through in dkong_in2_r then there is also the lack of dma on our port. You can patch it up if you like ill keep on digging in a little at the weekend. Got a crap load of pat testing as well think ill be working saturday by the looks of things.

**Comment by arcadez2003** [comment]
It sounds like an awful amount of work for one game i mean you already found a workaround 
i can isolate it just for dkremix, but at the end of the day it's up to yourself.

**Comment by grant2258** [comment]
Yea tend to agree, unless other game present issues not really worth the effort.

**Comment by arcadez2003** [comment]
Yeah i'll close this down and add in the coin hack you created later today thanks again for your 
help with this

Cheers!!

**Comment by mahoneyt944** [comment]
@arcadez2003 @grant2258 I noticed with that that coinage and lives selection isn't working which got me thinking there might be an issue with the input ports, since cocktail mode does work. I stumbled across this and figured it might improve things but haven't had time to plug it in.  Also note the service mode reset for nvram described at the bottom. Might be useful to generate a clean boot.

![Screenshot_20240208-014523](https://github.com/libretro/mame2003-plus-libretro/assets/49591133/d90c5b16-5b6f-47d0-a308-a3b884e64168)

**Comment by mahoneyt944** [comment]
![Screenshot_20240208-014523_1](https://github.com/libretro/mame2003-plus-libretro/assets/49591133/03a7d2a6-b29c-46cd-aa71-139487f19229)

**Comment by mahoneyt944** [comment]
@arcadez2003 @grant2258 I noticed with that that coinage and lives selection isn't working which got me thinking there might be an issue with the input ports, since cocktail mode does work. I stumbled across this and figured it might improve things but haven't had time to plug it in.  Also note the service mode reset for nvram described at the bottom. Might be useful to generate a clean boot.

![Screenshot_20240208-014523_1](https://github.com/libretro/mame2003-plus-libretro/assets/49591133/334fda18-6c0f-481b-8a49-6bd18238019b)

**Comment by grant2258** [comment]
Already looked at this on the dkforums and couldnt get any of the setting or combos  working even on mame standalone. Its a hack and not the original remix so that could be the reason in itself. I never triex with xmas mix though to be fair as it was already working.

**Comment by mahoneyt944** [comment]
I think they have to be changed in the service menu, but I haven't been able to get that to open, if it even opens for this version? But seems to follow the notes I've found... that is that only the cab dip will work and the others are ignored

**Comment by grant2258** [comment]
The service menu works fine in the xmas remix it should show up on first boot. Arcadez posted a link about it dkremix not being the original dump. The eprom and braze banking dont call in our port. Since its a hack of a hack that might be normal would be easy to verify if these things are called in mame current or not.  Im pretty sure its the missing  dma causing our issues.

**Comment by mahoneyt944** [comment]
Curious to why having the coin bypasses the issue. Without it, it seems like it's when the flashing effect of the title screen would normally start is where it hangs. maybe there's a interrupt issue or missing op. Does sanitizer show anything?

**Comment by grant2258** [comment]
you would need to log it in the cpu loop as there is no debugging in this core if your still looking into it.
