### ISSUE TITLE
Hammer Away 

### ISSUE THREAD

**Issue by arcadez2003** [libretro/mame2003-plus-libretro#1682]
@grant2258 fancy taking a run at this sometime.??
[MAME2005 Segas18.zip](https://github.com/libretro/mame2003-plus-libretro/files/14202399/MAME2005.Segas18.zip)

Original commit...
https://github.com/arcadez2003/mame/commit/226bed1cf3a0684a8f8ce446a82a1cbcb219f575

I might have made a mistake with the banking as per the above i thought it was the same as 5987 mapping except for this bank..
			case ROM_BOARD_837_7525:    mapper.map_as_rom(0x00000, 0x80000, 0xf80000, "rom1base", 0x80000, write16_delegate(FUNC(segas18_state::rom_837_7525_bank_w), this));

i made it this which might just be wrong i tried tweaking it back in the day but to no avail..
	{ 0x25/2, 0x00000, 0x80000, 0xf80000, 0x80000, MRA16_BANK16,          rom_837_7525_bank_w,   NULL,                  "ROM 1/banking" },

As it stands the game is working but the top tile layer is missing i've added the code i have to your MAME2005 driver an
irq was required for the sound so i've hooked that up via how i think it needs to be done circa 2005 but i cant be 100% 
on that.

**Comment by grant2258** [comment]
Ive made a branch will have a peek of whats going on when I get the time m8.

**Comment by grant2258** [comment]
fix is here all is good in the hood :) https://github.com/grant2258/mame2005/commit/7ff13da7c3dff7b2a0b9eefb764e01de405afc1f

**Comment by arcadez2003** [comment]
I guess the only question that remains is will it work here using the same hack as Clockwork Aquario there is only 
one way to find out i suppose.

**Comment by grant2258** [comment]
Worth  try there is issues with tiles later on in aquario in the old code sega video code can still finish the game though. Hamaway looks like is simpler but cant tell till you try though. I would imagine it will be mostly fine and probably minor bugs if any.

**Comment by arcadez2003** [comment]
If you dont mind i wanna start with adding in DD Crew im keen to know if like Aquario some gfx niggles can be sorted
by using mistys system16 updated drawing i should have the code done later today.

**Comment by grant2258** [comment]
No probs will look at it at some point. I just took a seven day free trial a the the amcplus website obviously you can only do that once though. 

I really need to look at my tv packages, I honestly dont think its worth what im payin for it. Sky seems a better option but has crap internet. All the decent channels have there own subscriptions so netflix and amazon dont have much to offer either.

**Comment by arcadez2003** [comment]
Aye i know sometimes it's rose tinted but i pine for the ole days where we only had four channels or five if you were 
lucky and you got all the top shows and sport with not a streaming service to be seen, i'll likely switch back to freesat
when my SKY contract is up later this year.

**Comment by grant2258** [comment]
Ive managed to get hamaway working had to use the the new  sega_ic due to the banking code we have. It lacks vdp priorities (as does the old code) . 

Its hacked  quick haved system 18 video code to use the new segac_ic in the video and the and io functions needed for it. The old video wasnt an option due to needed banking code needed.  It lacks vdp priorities (as does the old code) .  Its hacked  a so will need the code below converted to work and you can remove the segaic related code that was added. I just have no interest in dealing with the older video code  to be honest. It works and plays havent heavily tested though.

```
static WRITE16_HANDLER( rom_837_7525_bank_w )
{
	if (!ACCESSING_LSB)
		return;
	offset &= 0xf;
	data &= 0xff;

	/* tile banking */
	if (offset < 8)
	{
	//	int maxbanks = m_gfxdecode->gfx(0)->elements() / 1024;
		data &= 0x9f;

		if (data & 0x80) data += 0x20;
		data &= 0x3f;

	    segaic16_tilemap_set_bank(0, offset, data);
	}

	// sprite banking
	else
	{
		//printf("%02x %02x\n", offset, data);
		// not needed?
	}
}
```

this is the memmap required if you want to use the old code

```
static MEMORY_READ16_START( hamaway_readmem )
    { 0x000000, 0x07ffff, MRA16_ROM },
   	{ 0X200000, 0X27ffff, MRA16_RAM }, /*rom/bank */
	{ 0x400000, 0x40ffff, SYS16_MRA16_TILERAM },
	{ 0x410000, 0x410fff, SYS16_MRA16_TEXTRAM },
	{ 0x500000, 0x500fff, SYS16_MRA16_SPRITERAM }, //should be 7ff but needs fff for video code
	{ 0x500000, 0x5007ff, segaic16_spriteram_r }, 
	{ 0x840000, 0x841fff, SYS16_MRA16_PALETTERAM },
	{ 0xa00000, 0xa03fff, misc_io_r },
	{ 0xc00000, 0xc0ffff, segac2_vdp_r },
	{ 0xff0000, 0xffffff, SYS16_MRA16_WORKINGRAM },
MEMORY_END

static MEMORY_WRITE16_START( hamaway_writemem )
    { 0x000000, 0x07ffff, MWA16_ROM },
	{ 0x3e0000, 0x3e001f, rom_837_7525_bank_w },
	{ 0x400000, 0x40ffff, SYS16_MWA16_TILERAM, &sys16_tileram },
	{ 0x410000, 0x410fff, SYS16_MWA16_TEXTRAM, &sys16_textram },
	{ 0x500000, 0x500fff, SYS16_MWA16_SPRITERAM, &sys16_spriteram },
	{ 0x840000, 0x841fff, SYS16_MWA16_PALETTERAM, &paletteram16 },
	{ 0xa00000, 0xa03fff, misc_io_w },
   	{ 0xc00000, 0xc0ffff, segac2_vdp_w },
	{ 0xff0000, 0xffffff, SYS16_MWA16_WORKINGRAM, &sys16_workingram },
MEMORY_END
```

**Comment by arcadez2003** [comment]
@grant2258 i'll push the commit threw later and good job BTW

**Comment by grant2258** [comment]
Someone else might have the patience with the old video code always best to reach consensuses on the approach to take.

**Comment by arcadez2003** [comment]
Well as for the approach im happy to walk this path i cant see others objecting as it's not as if the other system18
games are affected just Hammer Away and DD Crew by looks.

One last thing can you try DD Crew asp i just wanna know if the sound is working at least videowise it should be ok 
until level two where the sprites will end up behind the cable car i was hoping  switching to the newer sys16 video 
or your new system18 drawing might sort that

And i think im done with trying to splice newer Sega titles in this older core it's too much hastle i was hoping for
Thunderblade sometime but that one can be played in FBN anyhow.

**Comment by grant2258** [comment]
Ill need get the dat to make the rom to test dd crew. Ill do that in the morning, need to get something to eat then bed. The only code that uses the  segaic is hamaway. 

Aquario and dd crew are using the old code with alt sprite drawing that the old code didn't handle well. Its quite confusing using the old video code has a few paths for issues that come up with it. Its most likely the vpd priorities causing the issues you talking about in ddcrew that would need probably need to be done proper to fix them issues.

**Comment by arcadez2003** [comment]
There is no hurry big yin when you get a spare moment and all that the romset is the original version from this 
core with the addition of the decrypted main cpu roms from ddcrewud

**Comment by grant2258** [comment]
There was a crash in the pal ram reads and a rom definition issue nothing major. I did add the proper address for the sound. There are some sounds and the odd time some music will play its not completely right.

**Comment by arcadez2003** [comment]
Thanks for that im just gonna push all this code through we can deal with objections if there are any down the road

**Comment by arcadez2003** [comment]
As for DD Crew even with the later drivers the sound in this game is not great until they updated the sound core
of course im not suggesting that for here for one second, im thinking this one might have slightly different handling
that the others alreay playable in the ole system18 driver hence the troubles.

**Comment by grant2258** [comment]
Well we can look into adding to the system18 going forward when it suits us. Its better than not working at all at least. If you know round about when the sound was fixed that would be very helpful.

**Comment by arcadez2003** [comment]
When the segas18 driver was created the sound was working for DD Crew so that would be MAME88.u7

**Comment by grant2258** [comment]
It most likely the sound banking ill have a look at at that since its simple emough to change to mame current banking there is nothing fancy going on. I also want to fix the priorities at some point so the new games are playable.

**Comment by grant2258** [comment]
got the priority code hooked up a bit concerned one of the changes in the segac2 will effect come the other drivers. I really don't want to fragment the sega video code  further as  ill add this code if/when I get the time to test other drivers. I just need new inputs for ddcrew and aquario due to the io changes. Apart from that all three games are good to go. The sound core could do with an update but the banking is set properly now as well. https://github.com/grant2258/mame2003-plus-libretro/tree/system18

**Comment by arcadez2003** [comment]
By looks you've updated the segac2 video code to slightly later MAME that is the version im using on the xbox core
since 2016 and i've never bumped into any significant gfx issues with the other Sega games nor has any user reported
any problems.

But as i always say ya never know

**Comment by arcadez2003** [comment]
@grant2258 some great work you've done here BTW if you wanna spend a little more time on this there are two
other games which would benefit from your updates namely Alien Storm only the bootleg works currently and it's
a real hackjob missing certain backgrounds and enemies as the bootleggers just ripped out the VDP.

The others are Laser Ghost a decent enough LG game and where's Wally which is nothing to write home about i suppose
it all depends on whether you've had enough of this or not :)

**Comment by mahoneyt944** [comment]
Just tried moonwalk with the ost samples and the games is broken now.

**Comment by grant2258** [comment]
Just revert it for now ill move these new drivers to a separate driver, not sure when ill have the time for that though the old sound banking will fix it your issue and break ddcrew. I can see the offsets are off in the sound roms in question  are there to workaround the sound core issues. The proper fix the sound core that needs updated from 95u4 if remember correctly. I not really willing to do that sound core at this time anyway

**Comment by mahoneyt944** [comment]
Ok

**Comment by grant2258** [comment]
The old code is doing things a very odd way https://github.com/libretro/mame2003-plus-libretro/blob/e15cd2be08898202a634b260882b349a32b8316b/src/drivers/system18.c#L1348-L1363 Its easier for me to move the new drivers somewhere else rather than fix a lot of things I dont need too :)

**Comment by mahoneyt944** [comment]
Yup that seemed to fix up the issue I saw. Nice work

**Comment by arcadez2003** [comment]
So where do we stand currently with Clockwork Aquario DD Crew and Hammer Away.?? it's just so i know what to writeup 
for the changelog

**Comment by grant2258** [comment]
Yea they are all done matey

**Comment by arcadez2003** [comment]
Good stuff i've updated the changelog
