### ISSUE TITLE
Wild Fang / Tecmo Knight changes

### ISSUE THREAD

**Issue by arcadez2003** [libretro/mame2003-plus-libretro#1689]
Hi fellas

Long story short i was cleaning away all my src files i had kicking around and bumped into some fixes i'd backported for
Wild Fang / Tecmo Knight from way back in 2021 bascially the code is to add a screen shaking effect when enemies bust
through brick walls or if you land after certain jumps.

From memory i'd fully tested these changes didn't notice any problems but i wanted to run them by ya's firstly before
commiting and it looks like i forgot about it, well i suppose finding an ole fix you've done is as good as a new one :)

If someone has a spare min can you do a code review for me with regards to the video changes basically im concerned
that the code was written after the scrolling layers were split into seperate defines depending on type eg text, front and back
while our code has just one type regardless of the layer in question.

So i simply reworked these new calls which handle some offsets to just use one single scroll type as per our code so just
wondered if you thought this was the correct way to go about this.??

Original commit
https://github.com/arcadez2003/mame/commit/e1feb6722444762508e70306325ee3ff7bede0b5

And the proposed MAME2003+ version of the above is here
https://github.com/libretro/mame2003-plus-libretro/pull/1687

No hurry for this i'll just leave stacked in the PR section for now

**Comment by arcadez2003** [comment]
Oh forgot this actually breaks the flip screen for gaiden, wildfang, raiga but it looks like i added the fix for this
from a couple of MAME builds later.

**Comment by grant2258** [comment]
I can certainly test the game after I look into the system 18 fixes. Someone else can do the code review since im only a contributor and dont feel like im in a position to review other peoples code, since im not a professional coder by any standards.

**Comment by arcadez2003** [comment]
Well when i say code review i mean gimmie your opinion around whether i can keep the ole single scroll type 
for use with the later additon of the offsets or should i update that part of the video drawing to support multi scroll by layer
to make sure of it.

i dont need ya to test anything thanks i did that back in the day but TBH i might just push this through users will let us know
if there are any problems i suppose.

**Comment by arcadez2003** [comment]
Infact im just gonna close this and do the merge if there are problems i'll sort it

**Comment by grant2258** [comment]
played the first level and the screen is shaking away at time looks liek its all good. I noticed aquario was a black screen as well. I rarely check this core to be honest just as well I did. I managed to fix the sound banking as well. I was messing with my core and hamaway had missing sounds that require 96u4 soundcore update to fix. I assume you already have that xbox port is just a heads up in case you need to add it should just be a straight copy  of the rf5c68.c either way.

**Comment by arcadez2003** [comment]
Nah funny enough i didn't update that as rolling back soundcores was not something i had much experience with
so on my core some of the segas18 games can sound a little rough in places using the ole rf5c68, good news on 
Tecmo Knight though i already knew the screen shaking effects worked.

It was more a case of whether shortcutting the code would offer up negative effects elsewhere in the games
anyway i've pushed it through now so we'll see if anyone opens up a report down the road i think everything
should be good though we'll see.
