### ISSUE TITLE
fd1089 decryption

### ISSUE THREAD

**Issue by mahoneyt944** [libretro/mame2003-plus-libretro#1694]
Is the fd1089 decryption fully working? Noticed it was hooked to afighter and alexkidd1 but these games don't boot for me. I found an older key decryption and got afighter, alexkidd1, and aliensyb to boot with but not going to waste time if the current fd1089 implementation will work instead.

**Comment by arcadez2003** [comment]
I thought i'd added a decrypted or was it unprotected set for Action Fighter.?? but i know the driver has been
updated since then so maybe that changed.

**Comment by grant2258** [comment]
yes both sets are working fine @mahoneyt944 . Not sure why your having issues unless your missing the keys .

**Comment by mahoneyt944** [comment]
Must have had an old dump with bad keys. Good to know they work. I do have a key for aliensyb still if that's wanted ? The old decryption has hard coded keys included.

**Comment by grant2258** [comment]
The key for every rom is available in mame, is up to you if you want to use old code. Not sure if every single key is available  under the old code,its s not a big deal either way unless someone wanted to add a particular game that doesnt have a key in the old code you will have to hack a new key in at that point.
