### ISSUE TITLE
Another port target Cyborg Force

### ISSUE THREAD

**Issue by arcadez2003** [libretro/mame2003-plus-libretro#1704]
Should we add this one.??
https://ozzyouzo.itch.io/cyborg-force

FBN already have we should be able to build the rom loading tables from this...

	<software name="cyborgforce">
		<description>Cyborg Force!</description>
		<year>2023</year>
		<publisher>NEO.BYTE.FORCE</publisher>
		<sharedfeat name="release" value="MVS,AES" />
		<sharedfeat name="compatibility" value="MVS,AES" />
		<part name="cart" interface="neo_cart">

			<dataarea name="maincpu" width="16" endianness="big" size="0x400000">
				<rom loadflag="load16_word_swap" name="cyborg-p1.bin" offset="0x000000" size="0x100000" crc="bb7602c1" sha1="abf329a40f34c88f7325b255e3bc090db1edaca4" />
				<rom loadflag="load16_word_swap" name="cyborg-p2.bin" offset="0x100000" size="0x300000" crc="2b61415c" sha1="0e3e4faf2fd6e63407425e1ac788003e75aeeb4f" />
				

				
			</dataarea>
			<dataarea name="fixed" size="0x040000">
				<rom offset="0x000000" size="0x020000" name="cyborg-s1.bin" crc="cd19264f" sha1="531be2305cd56d332fb7a53ab924214ade34a9e8" />
			</dataarea>
			<dataarea name="audiocpu" size="0x020000">
				<rom offset="0x000000" size="0x010000" name="cyborg-m1.bin" crc="9c0291ea" sha1="3fa67c62acba79be6b3a98cc1601e45569fa11ae" />
			</dataarea>
			<dataarea name="ymsnd" size="0x1000000">
				<rom name="cyborg-v1.bin" offset="0x000000" size="0x800000" crc="debeb8fb" sha1="49a3d3578c087f1a0050168571ef8d1b08c5dc05" />
				<rom name="cyborg-v2.bin" offset="0x800000" size="0x800000" crc="debeb8fb" sha1="49a3d3578c087f1a0050168571ef8d1b08c5dc05" />

      </dataarea>

      <dataarea name="sprites" size="0x2000000">

          <rom loadflag="load16_byte" name="cyborg-c1.bin" offset="0x000000" size="0x1000000" crc="0" sha1="0" />
          <rom loadflag="load16_byte" name="cyborg-c2.bin" offset="0x000001" size="0x1000000" crc="0" sha1="0" />
        </dataarea>

Although i'd be guessing on the text layer and audio roms as we require to use one of several variables for those for 
example here is Last Hope.......

	NEO_SFIX_64K( "NGDT-300-S1.bin", CRC(0c0ff9e6) SHA1(c87d1ea8731ac1e63ab960b8182dd1043bcc10bb) )

	NEO_BIOS_SOUND_128K( "NGDT-300-M1.bin", CRC(113c870f) SHA1(854425eb4be0d7fa088a6c3bf6078fdd011707f5) )

It'll be trial and error i suppose until we find the correct combo using NEO_SFIX and NEO_BIOS_SOUND

EDIT looking at the rom load values i think it's....
NEO_SFIX_128K
NEO_BIOS_SOUND_64K

**Comment by arcadez2003** [comment]
Well using the xml i have this.....

ROM_START( cyborgforce )
	ROM_REGION( 0x400000, REGION_CPU1, 0 )
	ROM_LOAD16_WORD_SWAP( "cyborg-p1.bin", 0x000000, 0x100000, CRC(bb7602c1) SHA1(abf329a40f34c88f7325b255e3bc090db1edaca4) )
	ROM_LOAD16_WORD_SWAP( "cyborg-p2.bin", 0x100000, 0x300000, CRC(2b61415c) SHA1(0e3e4faf2fd6e63407425e1ac788003e75aeeb4f) )

	NEO_SFIX_128K( "cyborg-s1.bin", CRC(cd19264f) SHA1(531be2305cd56d332fb7a53ab924214ade34a9e8) )

	NEO_BIOS_SOUND_64K( "cyborg-m1.bin", CRC(9c0291ea) SHA1(3fa67c62acba79be6b3a98cc1601e45569fa11ae) )

	ROM_REGION( 0x1000000, REGION_SOUND1, ROMREGION_SOUNDONLY )
	ROM_LOAD( "cyborg-v1.bin", 0x000000, 0x800000, CRC(debeb8fb) SHA1(49a3d3578c087f1a0050168571ef8d1b08c5dc05) )
	ROM_LOAD( "cyborg-v2.bin", 0x800000, 0x800000, CRC(debeb8fb) SHA1(49a3d3578c087f1a0050168571ef8d1b08c5dc05) )
	
	NO_DELTAT_REGION

	ROM_REGION( 0x2000000, REGION_GFX3, 0 )
	ROM_LOAD16_BYTE( "cyborg-c1.bin", 0x000000, 0x1000000, CRC(0) SHA1(0) )
	ROM_LOAD16_BYTE( "cyborg-c2.bin", 0x000001, 0x1000000, CRC(0) SHA1(0) )
ROM_END

The sound roms have the same crc and SHA1 that cant be right and on the GFX3 both the crc and the SHA1 read 0
which again cant be right, im convinced about some of the rom boot values either comparing vs FBN the xml looks
totally wrong in places fucking thing.....

https://github.com/finalburnneo/FBNeo/commit/7d0cf15913da3b464f1daa76c9be8d94c10e8de7

But hey ho it's early days

**Comment by arcadez2003** [comment]
BTW just to recap i did ask ya your thought on if you think this is worth adding the fact i've built the rom doesn't
mean the decision has already been made, it's just i never tried this before eg i tended to wait until another dev
had done it and copy theirs.

So i wanted to give it a bash but after this shitshow i dont think i'll try it via an xml again :) 

Anyway easy enough to use FBN Crc's and obtain the SHA1's via another method.

**Comment by grant2258** [comment]
Our neogeo roms really do need fixed its using an older bios thats why we cant use the fbneo and old mame sets. That aside I dont know anything about this game I dont see any issues adding it.

**Comment by arcadez2003** [comment]
Yeah it's not a quality issue the game looks good it's more a case of who released the rom.?? did the release have the
blessing of the game authors.?? and will we get a DMA request if added.?? 

That's what is bothering me although FBN support it and soon HBMAME will be adding it as well so im assuming they 
wouldn't have supported it without double checking firstly, anyway add it and worry about that later might be the best
solution.

**Comment by grant2258** [comment]
if in doubt leave it till its more clear we get enough hassle form all ends as it is imho

**Comment by arcadez2003** [comment]
Aye sounds like the best idea to leave it for now and see what happens with the other cores, but for testing im gonna
add it to my xbox core so @mahoneyt944 can you tell me how to create the SHA1's again as although you've told me
twice before i've forgotten again doh.!!!!!!

**Comment by grant2258** [comment]
you could add it just dont put it driver.c

**Comment by arcadez2003** [comment]
Release notes which came with the rom......

CYBORG FORCE

NEOGEO version for emulators.
When using this rom with Mame you will need to use or adapt file ./hash/neogeo.xml
which describes rom layout.

Enjoy!!

Contact us? 

discord:
https://discord.gg/3HPSpXPuxJ

X: 
https://twitter.com/neobyteforce

neobyteforce@gmail.com

Reading the above it sounds like the authors have publically released it silly me i didn't read this till now.

**Comment by grant2258** [comment]
if you have zip installed just right click on a file and it will have the option on the context menu. I use sha1sum for linux. Here a website that will do it for you as well https://emn178.github.io/online-tools/sha1_checksum.html

**Comment by arcadez2003** [comment]
Thanks @grant2258 that is a handy site to know about, alright im gonna add in the game i'll need some help here
as per which of these to use for the game i think it's NEO_SFIX_128K and NEO_BIOS_SOUND_64K but as always i
could be wrong..

Here is the you know what for testing purposes
https://files.catbox.moe/q4ib1o.zip

**Comment by grant2258** [comment]
Game boots fine not sure what it should look life looks good to me though job well done m8.

**Comment by arcadez2003** [comment]
Thanks for tryin it out your second one to say the game is fine so i think we can call this another happy ending :)

**Comment by ozzyyzzo4096** [comment]
> Release notes which came with the rom......
> 
> CYBORG FORCE
> 
> NEOGEO version for emulators. When using this rom with Mame you will need to use or adapt file ./hash/neogeo.xml which describes rom layout.
> 
> Enjoy!!
> 
> Contact us?
> 
> discord: https://discord.gg/3HPSpXPuxJ
> 
> X: https://twitter.com/neobyteforce
> 
> [neobyteforce@gmail.com](mailto:neobyteforce@gmail.com)
> 
> Reading the above it sounds like the authors have publically released it silly me i didn't look at this till now.

i can confirm that you can freely support cyborg force without probz ;-)

cheers,

OzzyOuzo.

**Comment by arcadez2003** [comment]
@ozzyyzzo4096 a double thanks firstly for the game and letting us support it cheers.!!!!
