### ISSUE TITLE
ThunderForce AC Prototype Bootleg

### ISSUE THREAD

**Issue by arcadez2003** [libretro/mame2003-plus-libretro#1708]
Hi fellas

Can someone give this new set i've added a quick whirl sometime as i cant be 100% certain it'll work as per this commit...
https://github.com/mamedev/mame/commit/93a3473cc75b929b76a07769233e915b5c399dc8#diff-c6f410126d1ebdc0141a2d8b11a34d9d13c3b6d0148e8888e33523d6d191d2d2

As it seems to have some sorta IO hack to ignore something called read direction whatever that is, anyway it might work
without it i hope so at anyrate conformation either way would be nice.

Cheers.

**Comment by mahoneyt944** [comment]
Seems to be working for me, only tested player 1 though. Odd controls, one button toggles your speed setting and another switch front to rear fire... directionally the controls seem proper.

**Comment by mahoneyt944** [comment]
![tfrceacjpb-240414-114846](https://github.com/libretro/mame2003-plus-libretro/assets/49591133/ee7067a1-dce4-41e4-8079-efc13cb08cb9)

**Comment by mahoneyt944** [comment]
![tfrceacjpb-240414-115025](https://github.com/libretro/mame2003-plus-libretro/assets/49591133/c4035980-ed21-4b0e-917c-b134f247d98a)

**Comment by arcadez2003** [comment]
@mahoneyt944 Thanks for trying this out we can close this then
