### ISSUE TITLE
XMl rom data has errors

### ISSUE THREAD

**Issue by israelperez** [libretro/mame2003-plus-libretro#1724]
just randomly came across this, not sure if the issue is in the mame core or export of the rom data. Also not sure if this is the only instance of there are other roms with the same issue.

in mame2003-plus.xml the rom "4in1boot" has the description 
Puzzle King (PacMan 2 with Tetris &amp; HyperMan 2 &amp; Snow Bros
its seems to be missing the ending ")" or the end of that string. not sure if its just the ) or there is more missing

**Comment by mahoneyt944** [comment]
The closing ")" just isn't in the description. I'll add it
https://github.com/libretro/mame2003-plus-libretro/blob/ab725a7f30a133551742b400089e8fffdf29d84a/src/drivers/snowbros.c#L1821

**Comment by mahoneyt944** [comment]
Fixed
