### ISSUE TITLE
Issues from mame menu pause

### ISSUE THREAD

**Issue by mahoneyt944** [libretro/mame2003-plus-libretro#1735]
when paused for a few seconds audio fails to resume. Fixes on core reset. Seems to be related to the interrupts. 
lethalen
Gijoe

**Comment by mahoneyt944** [comment]
Fixed https://github.com/libretro/mame2003-plus-libretro/commit/5f0dff30123f6f891f15a577900ebdc17799d775

**Comment by mahoneyt944** [comment]
So https://github.com/libretro/mame2003-plus-libretro/commit/5f0dff30123f6f891f15a577900ebdc17799d775 fixed lethalen and gijoe but doesn't work with midres. I tested #1738 and it fixes midres but breaks lethalen. So back to the drawing board.

**Comment by arcadez2003** [comment]
Right i've been busy elsewhere i just scanned the pr's so can someone explain what is going on with regards to these
core changes which will highly likely result in a ton of game breakage.??

**Comment by mahoneyt944** [comment]
Well it started off as fixing "show gfx" which is under the input (general tab), a feature that was stripped and broken. And with the pause like feature added to fix the above, it allowed the core to pause while in the mame menu, which is nice. Unfortunately we're finding this game for that game which doesn't like this pausing. So unless we find a easy workaround I'll have to snip out some of this code. Fortunately though, it can all be disabled by commenting out the calls to `cpu_pause(true)` so it's not too invasive to revert..just 2 lines of code.

**Comment by mahoneyt944** [comment]
https://github.com/libretro/mame2003-plus-libretro/commit/a5646f7531755c6caf2e078447bc8afdd4542767 this should work with everything, I tested about 50 games and it looks good. If you find any games that break, post them here. But I think I got it 😅

**Comment by mahoneyt944** [comment]
Also if we are concerned with possible regressions with this we can easily put a core option in to allow pause or not and just put the check in the beginning on cpu_pause and just return if it's disabled.

**Comment by arcadez2003** [comment]
Alright then no worries but the ole rule still applies you break it ya fix it :)

**Comment by mahoneyt944** [comment]
> Alright then no worries but the ole rule still applies you break it ya fix it :)

That's fair 😅
