### ISSUE TITLE
Segas32 sprite loading / bank issue

### ISSUE THREAD

**Issue by mahoneyt944** [libretro/mame2003-plus-libretro#1794]
@grant2258 made this for the issue, seems it's only effecting a couple of them.

Games using 0x800000 REGION_GFX2 size:
- arescue
- holo
- radm
- radr
- sonicp
- Spidey (working)
- spideyj (working)

Oddly Spidey and spideyj are already working as is, but the others prefer the 0x1000000 loading.

Branch for testing:
https://github.com/libretro/mame2003-plus-libretro/compare/master...Bank

Maybe a region length issue?

**Comment by mahoneyt944** [comment]
Think I found the issue. Let me see.

**Comment by mahoneyt944** [comment]
Still no luck but I found the commit where it changed
https://github.com/mamedev/mame/commit/85c788bb9ab6127c51d0546c601b7b5860d4339a

**Comment by grant2258** [comment]
> @grant2258 made this for the issue, seems it's only effecting a couple of them.

Not sure what you mean the pull request I had fixed this loading.

**Comment by mahoneyt944** [comment]
The issue is that `numbanks` is set wrong using the latest video code in our core. It should be what I commented out which yields `8` for sonicp, the older code yields `2` for sonicp. Not sure why our core doesn't like this line. But that's all that's needed to make the latest romloading work with the latest video code. Is this a memory issue with this core?

**Comment by grant2258** [comment]
Im well aware of the changes and the reason, however im not sure why your opening an issue on it considering the pr in question addressed it to use the new loading.

**Comment by mahoneyt944** [comment]
The goal wasn't just to use the new loading but also to use the newest banking, I'm trying to keep our video code, when possible, in line with current mame.

Current mame uses a required region ptr for this where we use `spritebase` pointer.

So the reason for this issue is to see if we can get our region pointer working properly with the latest video code.

**Comment by grant2258** [comment]
@mahoneyt944 you need to adapt our core to the code clearly memory_region_length length is returning bytes you need adapt that as 8 bytes is 2 int32s. Im not sure where the issues is unless you need help with the conversion just divide memory region by 4.

**Comment by mahoneyt944** [comment]
For now I'm just using this so it's working, but I think `spritebase` should be pointing to a region of size 0x800000 or 0x1000000. Instead we get 0x200000. 
```
UINT8 numbanks = (memory_region_length(REGION_GFX2) >> 20)/4;
```

Spritebase is set here
https://github.com/libretro/mame2003-plus-libretro/blob/e04cf9cba96b20b06c56d39a06d4cffff9529477/src/vidhrdw/segas32.c#L1786

**Comment by grant2258** [comment]
@mahoneyt944 semantics are unimportant when you get the same result it you choose to divide with a shift just >>22 and you dont need the extra divide.

```
(memory_region_length(REGION_GFX2)   >>22 
(memory_region_length(REGION_GFX2) / 0x400000
(memory_region_length(REGION_GFX2) >> 20)/4
```

The pointers are done in 32 bit so you need >>20  or   0x100000 * bank 

Its juts using shits vs * or / is personal preference Im still not sure what the issues here.
