### ISSUE TITLE
Save states don't load correctly after restart (corrupted)

### ISSUE THREAD

**Issue by carlosefr** [libretro/mame2003-plus-libretro#1799]
Saving the state, quitting the emulator, starting it again and then loading the same save state does not work correctly. These are some games where I can reproduce this (sometimes there is graphical corruption, other times the game just crashes):

* Paperboy
* Super Sprint
* A.P.B.
* Ironman Ivan Stewart's Super Off Road
* Hot Rod

And these are some games where save states seem to work OK (at least as far as I tested):

* Assault
* Badlands
* Indiana Jones and the Temple of Doom
* Tempest
* Marble Madness
* Track & Field

I tested this using the latest source available as of now (at commit 389511ca3afc931a285db1604084bc1ef6ae3656) on an Intel machine (x86_64).

**Steps to reproduce:**

1. Launch one of the affected games above;
2. Let it start, insert a coin, start playing;
3. Save the state;
4. Play some more;
5. Reload the state (should work);
6. Quit;
7. Launch the game again;
8. Reload the state (the game will crash, or the screen will be all corrupted).

**Comment by grant2258** [comment]
The save state are fixable but very time consuming, this core is marked as basic save state support. By all means leave the issue open if someone chooses to fix them. Ive fixed a few but generally unless I have good reason to fix them Ill leave it be.

**Comment by schmurtzm** [comment]
Probably related to this one : https://github.com/libretro/mame2003-plus-libretro/issues/1433

**Comment by mahoneyt944** [comment]
Moved to #1807
