### ISSUE TITLE
Sample Support Changes

### ISSUE THREAD

**Issue by arcadez** [libretro/mame2003-plus-libretro#18]
The following samples have been updated to support new and improved versions these 
will replace the existing samples from mame2003 and can easily be found via Twistys MAME 
samples site.

dkong
dkongjr
vanguard

These ones are new to this core and not supported in mame2003 again they can be
grabbed via Twistys site

cosmica
fantasy
sasuke

**Comment by Wilstorm** [comment]
Hey Arcadez I was going to let you know that a few sounds are missing when using samples that I found.

•Depth Charge - no sound
•Donkey Kong - half sound, missing several pieces
•Zaxxon - no sound

Depth Charge and Zaxxon aren't enhanced but just regular samples. Donkey Kong seems to missing sounds looking at the DAT.

sample name="run01.wav"/>
sample name="run02.wav"/>
sample name="run03.wav"/>
sample name="jump.wav"/>
sample name="dkstomp.wav"/>

What is missing is effect00.wav, effect01.wav and effect02.wav which are needed.

**Comment by arcadez** [comment]
Hi there

Firstly just wanna mention with regards to Depth Charge and Zaxxon the samples for those
games have not changed, so the ones you always used in mame2003 should work in this 
core unless there is a problem i've not noticed on the Rpi setup side after splitting off this
core.

Donkey kong however is a different story........

0.86u3: Donkey Kong sample improvements [Peter Rittwage, Derrick Renaud]. Added samples (run01, run02, run03, jump and dkstomp.wav).

The above samples replace the older inferior ones which were effect.00.wav etc etc, these are
missing for a reason as if you did try to use them all you would get is silence, i just played
dkong again in my test core and can confirm the game has full sound.

I'll check the code again later just to make sure i didn't miss something when i ported the
changes across.

Regards.

**Comment by Wilstorm** [comment]
I can't verify right now but I thought the effect wav's where for the girder stomp in the intro, etc. I can test it again around noon.

**Comment by arcadez** [comment]
Yes thats correct but when the samples were changed in MAME86.u3 those became obsolete
and were replaced with new samples with different names although they still provide the 
same sounds in game.

Do you get what i mean..??

**Comment by Wilstorm** [comment]
Thanks Arcadez, I think so so you back ported them and the sample names changed but effects are the same? I could have sworn I was not getting the girder stomp sound and the running sounds yesterday but I will test again around noon.

**Comment by arcadez** [comment]
The samples might be broken in this core if your not getting those sounds, i might need some
help on the Rpi setup side as i dont have much experience with this just to make sure 
everythings hooked up correctly.

**Comment by Wilstorm** [comment]
Setup is a breeze and the docs are great. If you skip all the shaders and extra config steps you really only need to know one thing. Where are the samples and ROMs folder and copy them over. I definitely don't know the development side but if there's anything I can do on the setup side just let me know. I think Mark and Grant know both sides. I will verify the samples for sure here in a few hours. Some times I jump in and out of games quickly when testing and miss things.

**Comment by ZappaUtopia** [comment]
I've been following the Retropie thread on this and as @maxbeanz has said, no samples work (on RPi) in 2003plus.

**Comment by Wilstorm** [comment]
It does look like no samples work. If the audio comes from the ROM set itself it does indeed work but not from the samples. For example dkong the music and barrel smash are fine but the girder stomp, running or jumping do not. I tested this for several ROMs and it seems consistent with samples.

**Comment by arcadez** [comment]
Daft question time you do have the sample paths setup for mame2003-plus and the sample in
the correct folder eg.......... /libretro system dir/mame2003-plus/samples/

**Comment by arcadez** [comment]
Another daft question @Wilstorm you do have samples enabled in your emulators options
please check this just to make sure.

**Comment by Wilstorm** [comment]
>Daft question time you do have the sample paths setup for mame2003-plus and the sample in
the correct folder eg.......... /libretro system dir/mame2003-plus/samples/

That might not be so daft. I actually have my samples in /home/pi/RetroPie/BIOS/mame2003-plus/samples. It's the same location lr-mame2003 uses so I copied them there. Wrong location? If that's the case we (Max, Zuppa and I) all assumed the wrong location. I can test this at noon-ish as I have a monitor right now but no speakers.

Also samples are/were enabled in the core options I checked that last week.

**Comment by Wilstorm** [comment]
what is the /libretro system directory = /opt/retropie/configs/arcade/samples *or* /home/pi/RetroPie/roms/arcade/mame2003-plus/samples

**Comment by ZappaUtopia** [comment]
My samples are also in `/home/pi/RetroPie/BIOS/mame2003-plus/samples/` and ON in RetroArch.

**Comment by arcadez** [comment]
Ok let's rule out a setup file problem on the Rpi side simply remove the -plus prefix from
the folder and see of it now picks up the samples......

/home/pi/RetroPie/BIOS/mame2003/samples/

**Comment by ZappaUtopia** [comment]
I tried renaming the directory to 

`/home/pi/RetroPie/BIOS/mame2003/samples/`

Unfortunately still no samples. When running a game it automatically creates another `mame2003-plus` directory.

**Comment by Wilstorm** [comment]
These directories did **not** work:

```/opt/retropie/configs/arcade/samples```
```/home/pi/RetroPie/roms/arcade/mame2003-plus/samples```

I already have all the samples in this directory and they do work fine for lr-mame2003 when using the Arcade folder but I don't get sound in mame2003_plus_libretro:

```/home/pi/RetroPie/BIOS/mame2003/samples```

**Comment by Wilstorm** [comment]
Updated above comment to exclude to more directories:

```/opt/retropie/configs/mame-libretro/samples```
```/home/pi/RetroPie/roms/mame-libretro/samples```

**Comment by ZappaUtopia** [comment]
@arcadez @markwkidd OK guys, i've cracked it !! If you put the samples in the `mame2003-plus` directory they work ! They don't work inside the samples directory.

**Comment by arcadez** [comment]
Hmmm at least we know the samples are working in this core all be it in the wrong place :)
what'ya reakon the paths are not set correctly somewhere..??

And thanks for getting to the bottom of this!!

**Comment by markwkidd** [comment]
Could you see if you are getting any details about the samples in your log?
I'm not on this end, but I'm in Windows.

I apologize that I haven't had time to finish debugging the sample info
logging yet. It would be handy now.

**Comment by ZappaUtopia** [comment]
I don't really have a log, nothing was reported. To confirm, the samples work in 

`/home/pi/RetroPie/BIOS/mame2003-plus/`

**Comment by markwkidd** [comment]
Oh I'm sorry I misread your earlier message. Glad it's working now! Woot!

**Comment by Wilstorm** [comment]
Any chance to move it into the folder? If I am understanding that correctly they have to be dumped in the folder along with cheat.dat, hiscore.dat, mame2003.xml, etc. instead of using the samples folder?

**Comment by Wilstorm** [comment]
I can confirm also samples do work directly in the mame2003-plus folder vs. the samples folder. Is it a simple path change to get them back together in a sub folder or more complicated?

**Comment by markwkidd** [comment]
definitely fixable. eta less than one week

**Comment by Wilstorm** [comment]
Sounds perfect, thanks Mark! :)

**Comment by markwkidd** [comment]
Hello samples testers. Could you rebuild from the latest source and try out samples again?

**Comment by markwkidd** [comment]
@arcadez what do you think about closing this issue down now?

**Comment by ZappaUtopia** [comment]
As no-one else is bothering, I can confirm that Samples are now working in the correct `samples` folder.
