### ISSUE TITLE
Add more Sony ZN1/ZN2 games

### ISSUE THREAD

**Issue by patrickli** [libretro/mame2003-plus-libretro#1805]
There are a few ZN1/ZN2 games added after MAME 0.78. Would be nice if their definitions can be added. At the least of the following and their variants are missing.

* `bldyror2` Bloody Roar 2
* `bam2` Bust a Move 2
* `hvnsgate` Heaven's Gate

**Comment by arcadez2003** [comment]
The emulation of the Sony PSX arcade hardware is not good circa MAME78 as such it would take a heap of work 
to get the games upto a playable standard before we even thought about adding new titles to the core.

**Comment by patrickli** [comment]
Yeah I can see the driver is missing quite a lot of things. Closing this then.
