### ISSUE TITLE
Savestate Support - Improvement and Requests

### ISSUE THREAD

**Issue by mahoneyt944** [libretro/mame2003-plus-libretro#1807]
#1799 #1433 Moving these issues to a dedicated section as they are essentially the same type of request. Savestate support in this core is basic, many drivers(roms) are not supported and must be fixed on an individual basis which is very time consuming. This can cause many issues such as failure to allow saving/ loading at all, unsupported auto_savestate features or incorrect behavior of, as well as jumbled graphics or audio failure when loading savestates.

This issue ticket does not guarantee support will be added for any particular game, but submissions will be considered on a case by case basis.

**Comment by mahoneyt944** [comment]
Request: segas32 savestate support fix https://github.com/mamedev/mame/commit/90152f33d5114828a53f38fc9a1913af71e683d6

**Comment by schmurtzm** [comment]
I understand that the diag of this issue is time consuming due to the number of drivers, however if your trigger the save state once the game (and all its assets) is totally loaded then the issue would be solved for all the games / drivers in one time. 

Some solutions / Workaround was given in the #1433 and their implementation were not tested (probably due to the bad atmosphere between the interlocutors... so I think that it is a little a shame to close it for now but yes, why not testing the solutions previously proposed here). May be it deserve a more clean implementation but a temporary working workaround would be very welcome anyway while a cleaner solution is being put in place 🙂

(The impact of this issue on mame2003+ is major, many handhelds have auto save state enabled to resume at power one so many distribs are using mainly FBNeo just because of this problem... that's a shame)

**Comment by carlosefr** [comment]
If the savestate in this core is game-by-game, could the core refuse to save states unless the game is listed (somehow) as supporting them?

I probably wouldn't have opened #1799 if the core had refused to save. But since it did save, I was bummed that I couldn't restore it on restart.

**Comment by mahoneyt944** [comment]
Problem is some games have partial support, enough to make and load a save, but not complete enough to actually work as intended and there isn't a list specifying the level of support in this core per game. Later mame added a savestate support flag in the driver for this, which we don't have. So it's a guessing game which are supported or not.

**Comment by carlosefr** [comment]
That's why I suggested putting this behavior behind a core option. Even if, at first, only a handful of games would be known to support save states, it would help build a list of working games slowly over time, while allowing anyone to just "enable experimental save states" and deal with whatever issues arise from that.

At the very least it would make the level of savestate support in this core explicit. It would also reflect the "game-dependent" status mentioned in the documentation quite literally.

**Comment by mahoneyt944** [comment]
Compiling a list of known working games is possible, through community work, sure. There's also the issue noted in #1433 where the savestate works fine when loaded manually, but not as an auto load state which is working and not working on a per game basis. So it would be quite the workload to record every game under several different circumstances but it's possible.

**Comment by mahoneyt944** [comment]
https://github.com/libretro/mame2003-plus-libretro/compare/master...Cereal

Here's a hacky solution to add some delay for auto savestate loading. It works for 1941, 1942, and 1943. But no real way of knowing if it will play nice with other games or not. We basically penalize state loading by 1 second when it tries to load a state earlier than that.

**Comment by mahoneyt944** [comment]
Already found some games...pacman and mspacman are not auto loading. They have longer boot ups and likely need a longer wait time to "ready" the machine. There likely isn't a solution for all games.

**Comment by mahoneyt944** [comment]
Here's an update https://github.com/libretro/mame2003-plus-libretro/compare/master...Cereal

Uses a 5 second delay for auto load states or states manually loaded before 5 seconds. Fail safe at 10 seconds.

Tested autostates:
- mspacman
- pacman
- 1941
- 1942
- 1943
- le2
- contra

**Comment by mahoneyt944** [comment]
Reverted commit again. I don't think there's anyway to predict the readiness of a machine in this core to reliability use auto load savestate..... @grant2258 how do you feel about just disabling auto load savestates in the core?

**Comment by grant2258** [comment]
@mahoneyt944 not sure why your asking me but fwiw the core has done what is expected. 

https://github.com/libretro/libretro-core-info/blob/50aa833e885e2132bad1e919ba2ebe687cf64b91/mame2003_plus_libretro.info#L19-L20

If a user overrides these setting its not a valid issue on our end. If basic savestates are allowing auto load/save to  its a front end issue imho. It would be better clarifying it the "higher ups" whoever that may be.   It should be able to be over ridden in the case someone wants to work on save states.

**Comment by mahoneyt944** [comment]
Auto is considered a "basic" feature because the API requires the core to be "ready" by the end of `retro_load_game()`, which mame2003+ isn't. Some machines, like crusnusa, need to load to the title screen before a state can be loaded (many seconds into the game) and this is way outside the expectation. I see no real way to account for this in a workaround, you'd have to test custom delays for every game.....that's why I think disabling the auto feature is probably the most honest solution, this would still allow manual state loading of course.

I'm not sure if the frontend tries multiple attempts to load an auto state, but I suspect simply adding this to retro_unserialize would disable auto loading, maybe with a message notifying the user.
```
if (cpu_getcurrentframe() == 0 ) return false;
```

If there are no objections to disabling the broken feature, I'll go that route.


@arcadez2003 is included in this discussion too.

**Comment by grant2258** [comment]
@mahoneyt944 I dont really think it matters if its disabled or not. Your time would be better fixing the save states. I think libretro definition of  save states lacks any consistency or even basic meaning. I would say its more of an after thought. Your examples of save states not working are just states that need fixed properly rather than finding a magic timer that might work sometimes.

**Comment by mahoneyt944** [comment]
Some states, even the ones that are working, won't work if loaded on the initial frame, like 1943, otherwise it works fine. How would this state be fixed?

**Comment by grant2258** [comment]
1934 clearly isint working properly just because it works after a frame doesn't mean it working somethings clearly missing have you checked the cpu soundcores /sound and gfx, or are you assuming because it works after a certain time its fine ? Im not sure how your evaluating the 1943 savestates are working

**Comment by grant2258** [comment]
@mahoneyt944  i enabled auto load and save and it doesnt appear to do anything is there are you sure you over rides arent on?

**Comment by mahoneyt944** [comment]
I'm sure there's hundred of games needing support fixed but the reality is no one of going to be able to fix all of them to make auto states work properly. Right now.a lot of hand helds are using auto states as a default options, so this core generally is loading working games incorrectly. So if we disable auto loading, at least the games won't crash on load when/ if savestate support isn't perfect per game.

**Comment by grant2258** [comment]
Well if the use never applies the core info override the issue will never happen as the auto saves wont happen with basic. The fact it works on auto load is in basic is a frontend bug for sure. 

Changing settings to what the core shouldn't do causes the issue so its something that should be fixed properly for all cores in the fronted with basic save states. If you feel strongly about it do as you wish its not really the core causing the issue seems a pointless endeavor fixing it here and leaving the issue wide open to other cores.

**Comment by mahoneyt944** [comment]
I can verify if basic should be including features such as auto states or not with libretro. I know this isn't the default setting for RA as I use all default settings and it's off by default. However, if many handhelds are forcing this option on, users of this core will have bad experiences on handhelds. I'm under the impression that everything being "ready" by end of `retro_load_game()` is essential for many features to work properly, such as run ahead, rewind, savestates, etc. I don't believe there's a build flag disable auto states specifically, just the menu option, so a workaround might be necessary. I'll see what I can find out.

**Comment by mahoneyt944** [comment]
Auto save and auto load both function for me. If I go to setting and toggle on both options then start a game like baluba, get into game, open Ra, close content. baluba.state.auto is created, then on load it auto loads

**Comment by grant2258** [comment]
Strange I have to goto setting->core  and over ride core in for auto save to work. If your editing the core info make sue its not cached in core settings as well. Also check your core info file or update them

**Comment by mahoneyt944** [comment]
Retroarch 1.17.0
![Screenshot_20240727-092010](https://github.com/user-attachments/assets/9bef3bce-634f-4f16-9bb8-ae8a3062beaf)

**Comment by grant2258** [comment]
@mahoneyt944 thats a really old version of RA at saying that, the save states work on the rasperry pi on the current retroarch master with basic saves like your getting. 

The latest commit on manjaro linux wont autosave unless you set the core override. There is also a double setting for the core saves so something funky is going on with RA. Im sure Ra will pick it up sooner or later for the auto saves not working properly in manjaro linux.
 

I did look at the saving code and basic should trigger the auto load/save the solution is change the core info too  savestate = "false" on the repo and use the override to enable it for testing.

you can see the duplicate setting the first two.

![Screenshot from 2024-07-27 14-53-02](https://github.com/user-attachments/assets/9f3ec9f9-ae74-44af-bd08-457c089fcbad)

**Comment by mahoneyt944** [comment]
Hmmm I wonder if it designates a "save file" differently than a "savestate file"? That is odd.

**Comment by mahoneyt944** [comment]
Just installed 1.19.1 and auto state save and loading works still. Tested with cclimber

**Comment by grant2258** [comment]
not sure whats happening as it works on the pi and I peeked at the code basic saves should be auto loading/saving so its a bug in  there somewhere that will effect all cores. Anyhow thats unrelated to our issue setting savestates to false should fix the issue https://github.com/libretro/libretro-core-info/blob/master/mame2003_plus_libretro.info is where you want to put the changes.

**Comment by mahoneyt944** [comment]
I'll ask libretro if they want to set it false in the info file or disable auto loading from the core.  This will effect mame2003 too. Doesn't matter to me as long as things work

**Comment by mahoneyt944** [comment]
So after talking to libretro, it seems if we set support to false, this will also ignore the basic, serialized, or deterministic option too...meaning it's disables all savestate features unless a user bypasses this under `settings->core->bypass core info savestate features` (advanced options must be enabled to see this). So setting false would not allow users to manually load and save savestates either. In this case if we want to preserve manual saving and loading, we'd have to disable auto load on the core side.

**Comment by mahoneyt944** [comment]
@schmurtzm this should prevent games from autoloading savestates, https://github.com/libretro/mame2003-plus-libretro/pull/1812

Let me know how that commit works for you.

**Comment by grant2258** [comment]
> this will also ignore the basic, serialized, or deterministic option too...meaning it's disables all savestate features unless a user bypasses this under `settings->core->bypass core info savestate features` (advanced options must be enabled to see this).

All these states will be effected they wont work properly its makes sense to disable it on the front end level . There is also no way to this super option off., Unless someone is willing to work on the save states like the example I gave you on 1943 it would be best to disable them until they are worked on.

There is also the issue that it will save on exit and people will post issues that auto load is broke. Youll need  to stop the auto save on exit as well to avoid issues.You might want to put a frontend notice up its disabled to avoid issues. 

I dont use the core anyway so maybe someone will want randomly functional savestates who knows. It does seems a big effort to keep something that partially working that will open up issues that no one is willing to fix.

**Comment by mahoneyt944** [comment]
All those delay changes were reverted. 

For the time being auto load / save are basic features, the case is made that these should be at least serialized. But until then, there's no way to disable the feature so we need to disable it to still allow manual loading of states. A lot of savestates do work, so I don't want to totally disable them all.

No matter what it's a lose lose. It is what it is.

**Comment by grant2258** [comment]
At least RA has common sense to disable rewind and runahead. Its a shame they can apply the same logic to auto load. The thing is for anyone working on this the skipping the first frame could potentially cause issues in drivers like neogeo that do work. I doubt anyone is going to fix save states anyway is a really odd way to work around what is imho a front end oversight on the auto load.

**Comment by mahoneyt944** [comment]
Overriding the savestate settings is experimental at best, and not supported. So I don't plan to cater to anyone trying to do that.

I'm not sure I'm following what you're saying. Using the default settings, Auto loading is disabled meaning the frontend shouldn't be able to load the state automatically, but that doesn't mean a user can't decide to manually load this file after the fact. We just don't want games to crash on load automatically. What a user does after the game starts isn't for me to decide.

**Comment by grant2258** [comment]
> Overriding the savestate settings is experimental at best, and not supported. So I don't plan to cater to anyone trying to do that.
as is auto load/save you seem to cater for them.

I would waste my time on anything libretro because they are happier for people to make messes of cores instead you end up with situations like this. I  dont see this going anywhere productive the issues still remains of auto loads being problematic.

**Comment by mahoneyt944** [comment]
I don't see how disabling the feature is problematic it doesn't work anyway. The states shouldn't automatically load on their own using the latest commit. If you can get it to automatically load then document what steps you take to get it to and we'll take it from there.

**Comment by grant2258** [comment]
@mahoneyt944 they do load your fix prevents the saving not the loading if you override the and the state is there it will still load. I tested it. After all is said and done it is what it is half a band aid

**Comment by mahoneyt944** [comment]
Idk what settings your using. Not a single game automatically loads a state when I have the option enabled to.

**Comment by grant2258** [comment]
> Idk what settings your using. Not a single game automatically loads a state when I have the option enabled to.

1)overide core states load 1943 or any game
2) exit and the autosave is stores
3) undo overide core states load 1943 or any game
game has issues due to state existing

reasons this could happen someone could enable for a game that works with states. Result the fix doesnt really fix anything in way that would keep the core stable with experimental options when disabled.

**Comment by mahoneyt944** [comment]
> 3) undo overide core states load 1943 or any game
> game has issues due to state existing

This doesn't happen for me. In fact the log tells you it fails to load. So unless you're on an old build or something it's your settings doing something different.

```
[MAME 2003+] Core is incompatible with automatic savestate loading.
[State]: Failed to load state from "/storage/emulated/0/RetroArch/states/mspacman.state.auto".
```

**Comment by grant2258** [comment]
I am at the latest commit for plus will take a sceen shot and post the log.

```
Commit 8ffa3c773640956c02dfbcd7d5dc8e3a12fc6773 (HEAD -> master, origin/master, origin/HEAD)
Author: mahoneyt944 <49591133+mahoneyt944@users.noreply.github.com>
Date:   Sat Jul 27 23:11:41 2024 -0400
```

[MAME 2003+] Core is incompatible with automatic savestate loading.does not activate here for some reason. Using RA  RetroArch 1.19.1 (Git 33d9def3b3)

**Comment by mahoneyt944** [comment]
I'm using the latest stable build installed yesterday
![Screenshot_20240728-171626](https://github.com/user-attachments/assets/27c07a76-2140-4a1e-a6f6-fbb6dc68b6c0)

**Comment by mahoneyt944** [comment]
Are you using the default info file?

**Comment by grant2258** [comment]
yea im using the default info file its not that. Your commit is from the 5th of june ill test that version of ra

**Comment by grant2258** [comment]
still not getting a response with the same version of RA

```
troarch -L mame2003_plus_libretro.so /media/storage/Download/Emulation/roms/arcade/mame2003-plus/1943.zip -v                                        ✔ 
[INFO] [Config]: Looking for config in: "/home/grant/.config/retroarch/retroarch.cfg".
[INFO] RetroArch 1.19.1 (Git 427e3fa6f6)
[INFO] === Build =======================================
[INFO] CPU Model Name: Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
[INFO] Capabilities: MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE42 AES AVX AVX2 
[INFO] Version: 1.19.1
[INFO] Git: 427e3fa6f6
[INFO] Built: Jul 28 2024
[INFO] =================================================
[INFO] [Input]: Found input driver: "x".
[INFO] [Core]: Loading dynamic libretro core from: "mame2003_plus_libretro.so"
[INFO] [Overrides]: Redirecting save file to "/home/grant/.config/retroarch/saves/MAME 2003-Plus/1943.srm".
[INFO] [Overrides]: Redirecting save state to "/home/grant/.config/retroarch/states/MAME 2003-Plus/1943.state".
[INFO] [Environ]: GET_VFS_INTERFACE. Core requested version >= V1, providing V3.
[INFO] [Environ]: GET_LOG_INTERFACE.
[INFO] [Environ]: PERFORMANCE_LEVEL: 10.
[INFO] [Content]: Content loading skipped. Implementation will load it on its own.
[libretro INFO] [MAME 2003+] Full content path /media/storage/Download/Emulation/roms/arcade/mame2003-plus/1943.zip
[libretro INFO] [MAME 2003+] Git Version  8ffa3c77
[libretro INFO] [MAME 2003+] Content lookup name: 1943
[libretro INFO] [MAME 2003+] Driver index counter: 1789. Matched game driver: 1943
[libretro INFO] [MAME 2003+] ==== BEGIN DRIVER CONTENT ATTRIBUTES ====
[libretro INFO] [MAME 2003+] * Supports 2 players with 2 distinct controls.
[libretro INFO] [MAME 2003+] * Supports 2 distinct button controls.
[libretro INFO] [MAME 2003+] * Uses multiplayer control labels.
[libretro INFO] [MAME 2003+] * Uses 8-way joystick controls.
[libretro INFO] [MAME 2003+] ==== END DRIVER CONTENT ATTRIBUTES ====
[INFO] [Environ]: SYSTEM_DIRECTORY: "/home/grant/.config/retroarch/system".
[INFO] [Environ]: SAVE_DIRECTORY: "/home/grant/.config/retroarch/saves/MAME 2003-Plus".
[libretro INFO] [MAME 2003+] content path: /media/storage/Download/Emulation/roms/arcade/mame2003-plus
[libretro INFO] [MAME 2003+]  system path: /home/grant/.config/retroarch/system
[libretro INFO] [MAME 2003+]    save path: /home/grant/.config/retroarch/saves/MAME 2003-Plus
[INFO] [Environ]: GET_CORE_OPTIONS_VERSION.
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_V2.
[ERROR] [Environ]: GET_VARIABLE: mame2003-plus_nvram_bootstraps - Invalid value.
[ERROR] [Environ]: GET_VARIABLE: mame2003-plus_four_way_emulation - Invalid value.
[ERROR] [Environ]: GET_VARIABLE: mame2003-plus_crosshair_enabled - Invalid value.
[ERROR] [Environ]: GET_VARIABLE: mame2003-plus_crosshair_appearance - Invalid value.
[ERROR] [Environ]: GET_VARIABLE: mame2003-plus_dialsharexy - Invalid value.
[ERROR] [Environ]: GET_VARIABLE: mame2003-plus_dial_swap_xy - Invalid value.
[ERROR] [Environ]: GET_VARIABLE: mame2003-plus_cheat_input_ports - Invalid value.
[ERROR] [Environ]: GET_VARIABLE: mame2003-plus_override_ad_stick - Invalid value.
[ERROR] [Environ]: GET_VARIABLE: mame2003-plus_use_alt_sound - Invalid value.
[libretro INFO] options.frameskip:0
[INFO] [Environ]: SET_AUDIO_BUFFER_STATUS_CALLBACK.
[ERROR] [Environ]: GET_VARIABLE: mame2003-plus_vector_resolution - Invalid value.
[ERROR] [Environ]: GET_VARIABLE: mame2003-plus_vector_antialias - Invalid value.
[ERROR] [Environ]: GET_VARIABLE: mame2003-plus_vector_beam_width - Invalid value.
[ERROR] [Environ]: GET_VARIABLE: mame2003-plus_vector_translucency - Invalid value.
[ERROR] [Environ]: GET_VARIABLE: mame2003-plus_vector_flicker - Invalid value.
[ERROR] [Environ]: GET_VARIABLE: mame2003-plus_vector_intensity - Invalid value.
[ERROR] [Environ]: GET_VARIABLE: mame2003-plus_neogeo_bios - Invalid value.
[ERROR] [Environ]: GET_VARIABLE: mame2003-plus_stv_bios - Invalid value.
[INFO] [Environ]: GET_LED_INTERFACE.
[INFO] [Environ]: SET_CONTROLLER_INFO.
[libretro INFO] [MAME 2003+] Opening ROM file: 1943.01
[libretro INFO] [MAME 2003+] Opening ROM file: 1943.02
[libretro INFO] [MAME 2003+] Opening ROM file: 1943.03
[libretro INFO] [MAME 2003+] Opening ROM file: 1943.05
[libretro INFO] [MAME 2003+] Opening ROM file: 1943.04
[libretro INFO] [MAME 2003+] Opening ROM file: 1943.15
[libretro INFO] [MAME 2003+] Opening ROM file: 1943.16
[libretro INFO] [MAME 2003+] Opening ROM file: 1943.17
[libretro INFO] [MAME 2003+] Opening ROM file: 1943.18
[libretro INFO] [MAME 2003+] Opening ROM file: 1943.19
[libretro INFO] [MAME 2003+] Opening ROM file: 1943.20
[libretro INFO] [MAME 2003+] Opening ROM file: 1943.21
[libretro INFO] [MAME 2003+] Opening ROM file: 1943.22
[libretro INFO] [MAME 2003+] Opening ROM file: 1943.24
[libretro INFO] [MAME 2003+] Opening ROM file: 1943.25
[libretro INFO] [MAME 2003+] Opening ROM file: 1943.06
[libretro INFO] [MAME 2003+] Opening ROM file: 1943.07
[libretro INFO] [MAME 2003+] Opening ROM file: 1943.08
[libretro INFO] [MAME 2003+] Opening ROM file: 1943.09
[libretro INFO] [MAME 2003+] Opening ROM file: 1943.10
[libretro INFO] [MAME 2003+] Opening ROM file: 1943.11
[libretro INFO] [MAME 2003+] Opening ROM file: 1943.12
[libretro INFO] [MAME 2003+] Opening ROM file: 1943.13
[libretro INFO] [MAME 2003+] Opening ROM file: 1943.14
[libretro INFO] [MAME 2003+] Opening ROM file: 1943.23
[libretro INFO] [MAME 2003+] Opening ROM file: bmprom.01
[libretro INFO] [MAME 2003+] Opening ROM file: bmprom.02
[libretro INFO] [MAME 2003+] Opening ROM file: bmprom.03
[libretro INFO] [MAME 2003+] Opening ROM file: bmprom.05
[libretro INFO] [MAME 2003+] Opening ROM file: bmprom.10
[libretro INFO] [MAME 2003+] Opening ROM file: bmprom.09
[libretro INFO] [MAME 2003+] Opening ROM file: bmprom.12
[libretro INFO] [MAME 2003+] Opening ROM file: bmprom.11
[libretro INFO] [MAME 2003+] Opening ROM file: bmprom.08
[libretro INFO] [MAME 2003+] Opening ROM file: bmprom.07
[libretro INFO] [MAME 2003+] Opening ROM file: bmprom.04
[libretro INFO] [MAME 2003+] Opening ROM file: bmprom.06
[libretro INFO] [MAME 2003+] Succesfully loaded ROMs.
[libretro INFO] [MAME 2003+] RetroArch will perform the rotation.
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[libretro INFO] [MAME 2003+] 

CONTROLS: 

GAMEINFO: 1943 - The Battle of Midway (US)
1987 Capcom

CPU:
Z80 6.000000 MHz
Z80 3.000000 MHz (sound)

Sound:
2xYM2203 1.500000 MHz

Screen Resolution:
256 x 224 (V) 60.000000 Hz

[libretro INFO] [MAME 2003+] Preparing emulated CPUs for execution.
[libretro INFO] [MAME 2003+] 1943 hiscore memory map found in hiscore.dat!
[INFO] [SRAM]: Skipping SRAM load.
[INFO] [Core]: Version of libretro API: 1, Compiled against API: 1
[INFO] [Core]: Geometry: 224x256, Aspect: 0.750, FPS: 60.00, Sample rate: 48000.00 Hz.
[INFO] [Audio]: Set audio input rate to: 48000.00 Hz.
[INFO] [Video]: Set video size to: 504x672.
[INFO] [Wayland]: Compositor doesn't support zxdg_decoration_manager_v1 protocol
[INFO] [Wayland]: fractional_scale_v1 enabled
[INFO] [EGL] Found EGL client version >= 1.5, trying eglGetPlatformDisplay
[INFO] [EGL]: EGL version: 1.5
[INFO] [GL]: Found GL context: "wayland".
[INFO] [GL]: Detecting screen resolution: 1920x2160.
[INFO] [EGL]: Current context: 0x560189c8c670.
[INFO] [GL]: Vendor: AMD, Renderer: AMD Radeon RX 480 Graphics (radeonsi, polaris10, LLVM 18.1.8, DRM 3.49, 6.1.99-1-MANJARO).
[INFO] [GL]: Version: 4.6 (Compatibility Profile) Mesa 24.1.3-manjaro1.1.
[INFO] [GL]: Using resolution 504x672.
[INFO] [GL]: Default shader backend found: glsl.
[INFO] [Shader driver]: Using GLSL shader backend.
[INFO] [GLSL]: Checking GLSL shader support ...
[WARN] [GL]: Stock GLSL shaders will be used.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GL]: Using 4 textures.
[INFO] [GL]: Loaded 1 program(s).
[INFO] [GL]: Using GL_RGB565 for texture uploads.
[INFO] [Joypad]: Found joypad driver: "udev".
[INFO] [Wayland]: Enabling idle inhibitor
[INFO] [Video]: Found display server: "null".
[INFO] [PulseAudio]: Requested 24576 bytes buffer, got 18432.
[INFO] [Audio]: Started synchronous audio driver.
[INFO] [ALSA] Using ALSA version 1.2.12
[INFO] [Microphone]: Initialized microphone driver.
[INFO] [Display]: Found display driver: "gl".
[ERROR] Rewind unavailable because this core lacks serialised save state support.
[INFO] [Environ]: SET_INPUT_DESCRIPTORS:
[INFO] [Playlist]: Loading history file: "/home/grant/.config/retroarch/content_history.lpl".
[INFO] [Playlist]: Loading history file: "/home/grant/.config/retroarch/content_music_history.lpl".
[INFO] [Playlist]: Loading history file: "/home/grant/.config/retroarch/content_video_history.lpl".
[INFO] [Playlist]: Loading history file: "/home/grant/.config/retroarch/content_image_history.lpl".
[INFO] [Playlist]: Loading favourites file: "/home/grant/.config/retroarch/content_favorites.lpl".
[INFO] [Environ]: SET_GEOMETRY.
[libretro INFO] watchdog armed
[libretro INFO] [MAME 2003+] loading 1943.hi hiscore memory file...
[INFO] [Config]: Saved new configuration to "/home/grant/.config/retroarch/retroarch.cfg".
[INFO] [Core]: Content ran for a total of: 00 hours, 00 minutes, 05 seconds.
[INFO] [Core]: Unloading game..
[libretro INFO] [MAME 2003+] saving 1943.hi hiscore memory file...
[INFO] [PulseAudio]: Pausing.
[INFO] [Core]: Unloading core..
[INFO] [Core]: Unloading core symbols..
[INFO] [Core]: Saved core options file to "/home/grant/.config/retroarch/config/MAME 2003-Plus/MAME 2003-Plus.opt".
```

**Comment by grant2258** [comment]
when the state is there as mentioned above I  get this at the end.
INFO] [State]: Loading state "/home/grant/.config/retroarch/states/MAME 2003-Plus/1943.state.auto", 68392 bytes.
[INFO] [State]: Core does not support save states.

![Screenshot from 2024-07-28 22-40-53](https://github.com/user-attachments/assets/dd2638f4-0258-43a3-a2b1-f87cc429c867)

**Comment by mahoneyt944** [comment]
"Core does not support save states." Is suspect, That's a frontend message. Trace that message back to Ra and see what triggered it

**Comment by grant2258** [comment]
to what end do we trace that though itll be in tasks/task_save.c and the code ill trace will be from the 5th of june.

**Comment by mahoneyt944** [comment]
If the frontend is saying "Core does not support save states." That almost certainly has to be set by the info file, no? I have no idea why it would say that. Especially if it's not even calling retro_unserialize().
```
savestate = "true"
savestate_features = "basic"
```

**Comment by mahoneyt944** [comment]
Maybe try deleting the retroarch.cfg

**Comment by grant2258** [comment]
ive already tried that. I also changed it to true. The same thing is happening.

```
at ~/.config/retroarch/cores/mame2003_plus_libretro.info                                                                                             ✔  28s  
# Software Information
display_name = "Arcade (MAME 2003-Plus)"
authors = "MAMEdev, MAME 2003-Plus Team, et al (see license and changelog)"
supported_extensions = "zip"
corename = "MAME 2003-Plus"
license = "MAME Noncommercial"
permissions = ""
display_version = "2003-Plus"
categories = "Emulator"

# Hardware Information
manufacturer = "Various"
systemname = "Arcade (various)"
systemid = "mame"

# Libretro Information
supports_no_game = "false"
database = "MAME 2003-Plus"
savestate = "true"
savestate_features = "basic"
cheats = "false"
input_descriptors = "true"
memory_descriptors = "false"
libretro_saves = "false"
core_options = "true"
core_options_version = "2.0"
hw_render = "false"
disk_control = "false"
notes = "(!) Unless using Full Non-Merged romsets, BIOS files must be inside the ROM directory.|See libretro core documentation for more information about content paths.|"

description = "Based on a snapshot of the MAME codebase circa 2003 (v0.78), 'MAME 2003-Plus' is compatible with MAME 2003-Plus latest ROM sets. Contributors have backported support for an additional 350 games that are not included in the standard v0.078 ROM set, as well as other functionality not originally present in the underlying codebase. MAME 2003/-Plus cores have tighter integration with libretro features than the more modern snapshots and are significantly faster, though this comes at a substantial reduction in both accuracy and compatibility. These cores are ideal for very weak hardware, such as Raspberry Pi and other Single-Board Computers and consoles, where even FBNeo may be too demanding. If you do not need the additional libretro features and your device can run any newer snapshot core or FBNeo, those are probably better choices for most users."

```

**Comment by mahoneyt944** [comment]
I can try on windows pc at some point and see if it's platform specific?

**Comment by grant2258** [comment]
This is based on your older june 5th commit would need to check against master to see if its changes since then. There is certainly differences on the x64 and pi.

**Comment by grant2258** [comment]
This is fairly odd behavior i deleted the retroarch.cfg and deleted the core dir it had the same result. 

It only seems to have fixed by removing the whole .config/retroarch directory. I guess a clean install was in order ill retest this during the week now that the save state support seems to be working like it should.

**Comment by grant2258** [comment]
I need to trace a way to recreate my previous issue that I had with the core info saying Core does not support save states. Yhays fixed now.

I checked on the pi both this pc and the pi do the auto load and save even with your patch. Can you confirm you have autosave and load activated?  Ill bring both platforms to master to recheck later on but both are loading the state.

**Comment by mahoneyt944** [comment]
Here's a short clip. I open RA, enable auto save and load, load 1943. The game starts normal without loading the auto state. Next I open RA and select to to manually load the auto state, it loads correctly, finally i reset the core and it restarts normally.
https://youtu.be/OPK1TYChfJI?feature=shared

**Comment by grant2258** [comment]
@mahoneyt944 you need to set auto load.save to be the default in the config not a manual load. Then load again to test when its default so it can create the files. 

I updated the pi to the latest config.

on the pi it always saves the autoconfig and loads it no matter what causing issues with problematic games
(im holding off deleting the ./config retroarch as this made the main pc work better)

on the pc it only happens if you override the core saves then it creates the autosave which causes issues when its disabled.

Unless there is issues with the core.

**Comment by mahoneyt944** [comment]
I'll download the latest nightly and try again. I tried leaving those settings as default and reloading Ra but no matter what I do I can't autoload the state.

**Comment by mahoneyt944** [comment]
Works perfectly fine for me on the nightly build as well
![Screenshot_20240729-011745](https://github.com/user-attachments/assets/5c77f9d2-5c69-4ad7-af90-e76e353ffee9)

**Comment by grant2258** [comment]
yeap I pointed out above is an ra bug only works with manual launch through the gui. Nothing we can do to fix it our end its is what it is. Retropie launches this way so could be an issue for them as well.

**Comment by mahoneyt944** [comment]
> it fails when launching from the command line.
> retroarch -L ../mame2003-plus-libretro/mame2003_plus_libretro.so /media/storage/Download/Emulation/roms/arcade/mame2003-plus/1943.zip

Hmm I can't try that on my phone, I wonder it the info file.settings are overridden by the command line launch method

**Comment by grant2258** [comment]
adding --config=~/.config/retroarch/retroarch.cfg fixes it at least its another lesson learnt. Strange all the config settings work for the other stuff without that. You would think it would use the default path like when you launch it. No the   retro_unserialized doesnt get run without the config line.

**Comment by mahoneyt944** [comment]
That's odd.

> adding --config=~/

Does this need added to RetroPie then?

**Comment by grant2258** [comment]
dont know dont use it anymore but it complains about playlisits and saving the error with saving the config file. 

ERROR] [Config]: Failed saving configuration to "~/.config/retroarch/retroarch.cfg".
ERROR] Failed to write to playlist file: ""

I dont use RA like I said can just launch manually for testing though might be easier that way to avoid issues from using the command line.

**Comment by mahoneyt944** [comment]
I would think it should default to that if not specified though through command line too. I'll have to see if this is intentional or not. Might be an oversight

**Comment by grant2258** [comment]
Oh its chore for me easier to just load the rom up from the command line takes less time bash autofills the rom name options when you type the first few chars. I would probably use it if I used RA for anything but the pi5 I just use standalone mame.

**Comment by mahoneyt944** [comment]
Well at least that mystery is figured out. I'll have to see what RetroPie does when loading up. Haven't turned on my pi in a very long time. Idk if the sd card will even boot..
. Seemed to have issues in the past when left to sit for long periods of time.

**Comment by mahoneyt944** [comment]
> Request: segas32 savestate support fix [mamedev/mame@90152f3](https://github.com/mamedev/mame/commit/90152f33d5114828a53f38fc9a1913af71e683d6)

Do we have support for saving pointers?

**Comment by grant2258** [comment]
> Does retro_unserialized get called when you load this way? Not sure how else it could load a state without it.

its doesnt run in any case with the command line perhaps the savestate path isint set so it works that way. Its something to with the command line best launching manually. its is strange though as there isint any issues with the other settings working without the config.



> Do we have support for saving pointers?

just save it as the array size there is no pointer support

**Comment by mahoneyt944** [comment]
> just save it as the array size there is no pointer support

I'll have to try plugging it in, would be nice for testing the sonic bug.

**Comment by grant2258** [comment]
yea should be easy enough to implement it from the link you posted. The command line still isint working retroarch doesnt process the ~ properly so the paths arent set.
```
retroarch -L ~/.config/retroarch/cores/mame2003_plus_libretro.so /media/storage/Download/Emulation/roms/arcade/mame2003-plus/1943.zip  --config= /home/grant/.config/retroarch/retroarch.cfg 
```

it still fails the same way regardless manual works so it could well be an issue for anything using launchers retropie and anything else using emulation station.

**Comment by mahoneyt944** [comment]
I'll ask libretro about it

**Comment by grant2258** [comment]
you might as well close this and open an issue on ra if there is any issues regarding it wont be from our end.
