### ISSUE TITLE
Xmen 6 Player version there is a fix in latest MAME

### ISSUE THREAD

**Issue by arcadez2003** [libretro/mame2003-plus-libretro#1829]
As per the title there is a gfx fix in latest MAME to sort some colour issues on screen two so i wanted to ask 
before i just add it willy nilly do we actually need it.?? as maybe it only affected the later video code.

**Comment by grant2258** [comment]
I just tried it on mame0268 didnt notice any colour issues unless I just missed them. I would need to know what im looking for because I havent personally seen anything glaringly obvious.

**Comment by mahoneyt944** [comment]
I know in our video code there's a timing issue between the two screens, most obviously when the round object drops in attract mode....Can't remember if it's a planet or moon or something by memory, but one side lags behind the other.

**Comment by arcadez2003** [comment]
> I just tried it on mame0268 didnt notice any colour issues unless I just missed them. I would need to know what im looking for because I havent personally seen anything glaringly obvious.

Aye the commit was just done the other day so it'll be MAME 267 before it'll be included but yeah as you say if it's
not obvious then it'll be one of those little niggles that diehards tend to spot.

**Comment by arcadez2003** [comment]
> I know in our video code there's a timing issue between the two screens, most obviously when the round object drops in attract mode....Can't remember if it's a planet or moon or something by memory, but one side lags behind the other.
> 
> Edit: ![xmen6pu-240817-174108](https://private-user-images.githubusercontent.com/49591133/358870119-0fb19da5-8344-4375-a7a8-7b6252264930.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5MzIwNDYsIm5iZiI6MTcyMzkzMTc0NiwicGF0aCI6Ii80OTU5MTEzMy8zNTg4NzAxMTktMGZiMTlkYTUtODM0NC00Mzc1LWE3YTgtN2I2MjUyMjY0OTMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE3VDIxNTU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjZWVjMWNhOGUyNTBkMWNlZjNjNjQ3Mzc0ODg2OTE3MjU4MTRhZmY2ODIzNzVhNjM5MzdjZjU2NGQ5YTZlYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.va66TCTXhyVQGpj6f9A7UdcddfJG93aduuI0ufPZNHk)

Hmm it's worth checking MAME testers to see when this was fixed.

**Comment by mahoneyt944** [comment]
I know the video code says that there are many places where the left and right screen are mixed up. So it could be something as simple as that.

**Comment by arcadez2003** [comment]
Alright then a few niggles here and there nothing to overly concern ourselves with then and that fix i mentioned
is from what you guys have said not required for here, might as well close this down.
