### ISSUE TITLE
core dump - milliped

### ISSUE THREAD

**Issue by theflyingape** [libretro/mame2003-plus-libretro#1834]
FWIIW, recent compiles will fail running older analog game content, such as Centipede and Millipede, on RPi 4/400/5, but not Atari Football, Tempest, or Midway Kick.

After SET_CONTROLLER_INFO message, it fails with `malloc() invalid size (unsorted)` aborted core dump.

I have an 8BitDo retro keyboard and Trackball as a mouse device and were working perfectly 2 months ago.
Perhaps simple regression tests can be constructed to sample some mainstream content from 70s,80s,90s.
I've moved my Analog game playlists over to latest MAME.

**Comment by grant2258** [comment]
This is should already be fixed try the newest source.

**Comment by mahoneyt944** [comment]
@theflyingape yes update to the latest source and try again. It should all be working now.

**Comment by theflyingape** [comment]
I can confirm it did compile/work testing those two titles -- _thank you_ -- formerly, `git pull && make` did not produce this result. Instead, I dumped the source tree (instead of `make clean`) in order to get this working.
