### ISSUE TITLE
problem with the interrupt tab  pause that was implemented

### ISSUE THREAD

**Issue by grant2258** [libretro/mame2003-plus-libretro#1836]
This ones not too serious start xevious go to the tab menu when the game starts straight away  then exit. The game doesn't boot. Its something that is probably worth fixing in case another game suffers from this issue down the line and your at the very least aware of a potential issue.

**Comment by mahoneyt944** [comment]
Some games can't be interrupted when booting or they lock up. I think this is protection built into some startups. I think galaga does the same

**Comment by grant2258** [comment]
> Some games can't be interrupted when booting or they lock up
well that can happen anytime not just on boot. Its just not handling every case put to it properly. I had troubles with thunderblade but when i changed the interrupts  it dint trigger it anymore. Hopefully there is no issues with other games. Its worth keeping the one causing the issue. Are you storing the cpu context the menu and popping it in restore?

**Comment by mahoneyt944** [comment]
When cpu_pause is turned on it just halts all the cpus and the core runs with inactive cpus appearing to be "paused". In most cases this is true, since its not receiving new data, but there are some cases that won't pause.... such as code that directly draws to the screen (galagas star field comes to mind here) since its essentially a hack. The sound latches are not paused which doesn't really hurt much unless the sound was extra long, you get a little silence silence for a second but normal operation resumes on the next sound call.

I don't currently have a solution for interrupting a startup sequences....As the game expects it to be uninterrupted and a real machine wouldn't have a mame menu. We don't catch any states or anything / restore anything right now. It just stops and starts

**Comment by grant2258** [comment]
halting a cpu can effect a lot of things will deal with it if it becomes an issue. Ill take a look at some point. It would make more sense creating a pause action that ran the user interface loop and updated the video. The ui probably hooked in at the vblank

**Comment by mahoneyt944** [comment]
Doesn't really matter to me, I just got it working as a lot of this code was worked around or broken. So it's "a way" but surely not the only way. It definitely is harder when the core has to interact with the frontend. Fwiw I think games like galaga actually locked up on startup going into the mame menu even without pausing, I suspect because the timing is still skewed but never looked into it.

**Comment by grant2258** [comment]
I tested without the cpu pause and the games are fine. If it does cause an in game issue we can add core option to toggle it on off. 

The input polls might be an issue doing a separate pause action as they arent stored and read in the mame loop as well, they used to be stored but if it becomes and issue in game we can review it then.

**Comment by mahoneyt944** [comment]
Ok I'll close this for now then. Let me know if you find a game not complying in game.

**Comment by grant2258** [comment]
> Ok I'll close this for now then. Let me know if you find a game not complying in game.

Only time I use the core is when updating something im not going to test other people updates that should happen by the person implementing a feature that effects things core wide. Quite a few games cause issue opening the tab menu when booting though. If someone comes across it you'll know what the issue is at least since the games that had problems before work.

**Comment by mahoneyt944** [comment]
It was tested plenty.....there's just not a solution for this yet, it's a known issue. Right now the workaround is to wait until the game loads before jumping into the menu, which is a small price to pay. I haven't found any games that fail after they have been allowed to fully initialize and many work fine even if you don't wait. Like I said there maybe a way to backup to the last instruction or something which might fix it.....other wise, bypass the feature or rewrite all the pause and showgfx code with a new approach.

**Comment by mahoneyt944** [comment]
@grant2258 this should fix all those issues. https://github.com/libretro/mame2003-plus-libretro/commit/9234555754e6b01d24ef4f3472ae3b8ec27c5736

**Comment by grant2258** [comment]
good stuff will check it out since im looking at namcos bugs

**Comment by mahoneyt944** [comment]
Thanks. Couple of things that I left alone that we might want to change.

1. Move `time_to_reset` to the bottom of mame_frame() to allow it to reset when the menu is active. Right now it pends until the menu is closed. Could also force close the menu on reset instead.
2. Black screen behind menu vs the games bitmap (preference thing)

**Comment by grant2258** [comment]
time_to_reset will reset the cpu andtime_to_quit will close mame. Unless you want to exit mame or reset the game on opening the menu I dont really see a reason to use this.

**Comment by grant2258** [comment]
If you prefer it that way thats fine but i think youll need to add some logic to the reset code to close the mame menu if its open when reset is called from the ra ui.

**Comment by grant2258** [comment]
The pause seems to working fine tested with a good few games. Since only RA calls the machine_reset i think that would be the ideal place to close the mame menu if its open and changes the pause to zero. Its up to you if you want it though.

**Comment by mahoneyt944** [comment]
I was looking over some of the legacy code in Xtreme and I think I I might add pause_bitmap unless you think the black screen is a better background? I'm undecided.

**Comment by grant2258** [comment]
That is just a personal preference @mahoneyt944 both are ok with me since your doing the coding you can decide which you like best. The functionality of the pause is fine now  with no potential interrupt issues waiting to happen it was on the functionality I was concerned with.
