### ISSUE TITLE
Analog on starwars

### ISSUE THREAD

**Issue by mahoneyt944** [libretro/mame2003-plus-libretro#1849]
For some reason when I start this one the analog is off to the side not centered on screen and the center changes while playing? Is this normal or a bug. Using a onscreen stick so not a drift issue.
![starwars-240822-055300](https://github.com/user-attachments/assets/17276815-bc7c-4ac4-87fb-f29ed5c6e84a)

**Comment by grant2258** [comment]
I would test it on mame current if i was you. It uses a Yoke controller with a big reach you would need to sick a pen or something on your joystick to get a better reach for any kind of sane control I would imagine.

**Comment by mahoneyt944** [comment]
It's an onscreen stick which auto snaps to center. But the center isn't the center of the screen. If you start the game without pressing any direction does it aim like in my pic above?

**Comment by grant2258** [comment]
yes @mahoneyt944 I cant test on plus at the moment but in mame it starts that way everyt ime you boot you have to move the analog stick on all directions i do a few circles then the diagonals and it works fine on mame after doing that.

**Comment by mahoneyt944** [comment]
Ok then sounds about what I'm getting here
