### ISSUE TITLE
TODO: Port Outrun CD Soundtrack patch 

### ISSUE THREAD

**Issue by markwkidd** [libretro/mame2003-plus-libretro#185]
Hello again @KMFDManic -- In answer to one thing you said in your last message to it's probably easiest to reach me by tagging me in github, because honestly you are the only person I talk to on reddit, but I can use either or both. No problem.

Today's question from me: Could you point out where we could look at the Outrun OST patch you wrote? I looked at the two repos of yours that I am familiar with and I can't find it yet!

**Comment by KMFDManic** [comment]
https://github.com/KMFDManic/mame2003-xtreme

I was doing a restructure.  It is now reposted:)  Keep me updated on whether or not you will be able to help on the hi score implementation (external dat preferable, as it may work more optimally on the Mini:)

**Comment by grant2258** [comment]
done and big thanks to @KMFDManic appreciated
