### ISSUE TITLE
Dragon Saber

### ISSUE THREAD

**Issue by Cibomatto2002** [libretro/mame2003-plus-libretro#1853]
On level 2 in the lava you can see something is not right I checked on the new MAME and I don't see this bug. here is a video.

https://www.youtube.com/shorts/1es69nZASJI

**Comment by arcadez2003** [comment]
In order to fix this we'd need to update some of the Namco video code to MAME88 or so and alotta the games
would take a rather large hit in the performance dept, which is a big no no for this core as per the lower spec
devices MAME2003+ is aimed at.

0.87u3: Phil Stroffolino fixed older System2 ROZ system; in particular Dragon Blade glitches are no more.

I actually did this update for my Xbox MAME core maybe 10 years or so ago but had to roll back on it 
as the games dropped by 40fps down to 20fps.

**Comment by Cibomatto2002** [comment]
The game needs to be set to imperfect graphics in the live compatibility table.  Do I need to close this?

**Comment by arcadez2003** [comment]
Yeah fair enough i can see the game has issues, as for closing wait and see if anyone else chimes in
as to whether we should attempt this update or not.

**Comment by grant2258** [comment]
Considering this core is aimed at low end in my perception a rpi3 is considered a baseline this update wouldnt be worth it if tanked so much on an xbox admittedly it would probably need tested to give a concrete answer but arcadez testing pretty much answers the question for me. 

I seen some interesting debates on the system16 and some games for me are faster with the newer video code considering the way the old one draws the screen not entirely surprising but  the old video code is still there as well as the new and only problematic games use the newer code when needed like the segaxbd we added lately. Perhaps we can limit the new video code at that one specific game only as a compromise. 

I wouldn't recommend what was done with system32 updating it to the latest mame and take the hit. Both me and arcades in the past looked at this and fixing the issues lead to a tanking. Its nice to have systems working but there has to be a balance. 

Whats done is done, I know today's low end runs mame mostly all 80s and 90s if you have a pi5 use mame current. If you have something older use plus. If your aiming at pi5 as low end you would probably be using a base something similar to advanced mame to get the most out the systems that require the extra beef. In short im with arcadez with this one.

I would like to hear mahoneyt944  thoughts on this update in a comparison with the system32 stuff pretty sure its less of a hit in the fps department on lower end. Maybe the bar is higher with lower end hardware improvements.

If that is the case it might be worth using a later mame base and keep this code for older hardware. This topic always muddles me at times,. I think its just sometimes people want a certain system to work. It probably worth adding the arm32 asm core for the v60 after these updates that in mame2000 in not really motivated to doing that myself though. It probably doesnt support the IO stall we need in its current state for some games.

**Comment by arcadez2003** [comment]
Yeah it's not a straight forward update either as quite a few other namco drivers etc etc would be caught up in this
so the workload is not on the lighter side however that has not always stopped us previously :)

However as i said previously we'd be robbing peter to pay paul as to fix the gfx for Dragon Saber will in turn
hit the performance for that game and quite a few others.

**Comment by mahoneyt944** [comment]
You guys would have more knowledge on this system than I, so I don't have a strong opinion either way. I suppose if you think the hit isn't worth the reward, it would be be fine to leave it as imperfect or if it's wanted to try to add it to an isolated driver.

With system32 I felt the vast improvement was worth the hit and users had a higher demand for it. KMFDManic was able to squeeze some better performance out of the new code to boot and with the multi32 speedup hack I added we still try to balance accuracy and speed to some degree.

**Comment by arcadez2003** [comment]
> You guys would have more knowledge on this system than I, so I don't have a strong opinion either way. I suppose if you think the hit isn't worth the reward, it would be be fine to leave it as imperfect or if it's wanted to try to add it to an isolated driver.
> 
> With system32 I felt the vast improvement was worth the hit and users had a higher demand for it. KMFDManic was able to squeeze some better performance out of the new code to boot and with the multi32 speedup hack I added we still try to balance accuracy and speed to some degree.

Yeah i agree with ya with regards to Sega System 32 as for this update looking at the driver no other games barring
Dragon Saber and Mach Breakers aka Numan Athletics 2 actually benefit from it so we'd be taking a performance hit 
for a fair few games to just fix two which is not a good ratio.

As for how big the hit would be we'd only know if we done the graft and i gotta admit im not bursting with
enthusiasm to work on it as i'd need to split up all the mem maps as they merged em as part of the changes.

**Comment by arcadez2003** [comment]
On a seperate note I noticed Final Lap 2 is tagged as not working maybe by adding the proper sprite roms
from MAME79 would sort this.?? i've not much experience with these games as they played in slow motion 
on the xbox.

**Comment by grant2258** [comment]
Ill update the core and give it a shot and let you know how it goes.

**Comment by grant2258** [comment]
The sound has a drone  a little drone and the gfx are quite right but is shows signs of life. At least its booting now. Wasnt able to get it to accelerate in a straight line either probably need a calibration havent tested a lot just a boot check for some feedback.

![Screenshot from 2024-09-05 21-05-28](https://github.com/user-attachments/assets/278dfaf0-c3c2-49b2-a51d-4c744407002d)

**Comment by arcadez2003** [comment]
Yeah looks ok apart from the road what about Final Lap and or Final Lap 3 does the road draw correctly for those ones.??

As for the update you'd likely have to start from the MAME79 changes and work forward from there but hey man
just a warning the workload looks really on the highside.

**Comment by grant2258** [comment]
finallap controls work but turning is weird.  Finalap3 has road markings at least but has the same control issues as  finalap2. I might look up the controls touching this video code would require too much testing with the amount of games involved for me.

**Comment by arcadez2003** [comment]
With alotta the Namco Sytem 2 games you had to enter a service type mode to init the controls but our ole driver
doesn't firstly have the code to access said input service modes nor the way and means to save the settings afterwards
im sure this was done via an eeprom but i'd have to check.

Yeah i agree it's too much work to update the video code as for Final Lap 2 missing the road i wonder if we need this...

0.97u3: Brian Troha added Final Lap road clut PROM to all Final Lap sets.

Then again Final Lap 1 and 3 have the road drawing correct with our current code so maybe the reason why it doesn't
display correctly for Final Lap 2 lies elsewhere.

**Comment by arcadez2003** [comment]
Alright i hooked up the road colur clut proms for the Final Lap and Suzuka 8H games which hopefully will sort
the road gfx niggles also added one for Four Trax, i'll also backport a fix for bad oversized sprites in the above
from MAME234.

**Comment by arcadez2003** [comment]
Apparently we should be using the Japan set of Marvel Land as it turns out the US version is a prototype
with missing game elements and it ends on level 3-4 instead of 4-5, they swapped the sets around for current
MAME i'll likely do the same for here sometime.

**Comment by grant2258** [comment]
The road looks as good as getting yer gnashers shined up at the dentist. I think ill look at the controls but there is another bad rom in finalap2 at least Ill need to check what cpu4 is actually doing and if its input related.

**Comment by arcadez2003** [comment]
Good to hear the road is sorted now as for that bad rom maybe there is a redump i'll need to check the WIP
i know they switched to using another CPU type to handle the IO's as per CPU4

**Comment by arcadez2003** [comment]
Right then i think we can close this as the workload is too high for a large namco update to fix the gfx
niggles in one game
