### ISSUE TITLE
Rom set generated from ~2019 has several games failing on current lr-mame-2003-plus (installed from binary)

### ISSUE THREAD

**Issue by ceberz** [libretro/mame2003-plus-libretro#1860]
This is really more of a question than an issue but I wasn't sure where else to ask.

I have a 0.78 rom set that I generated from lr-mame-2003-plus's XML file sometime in 2019. I was rebuilding my RetroPie from scratch and installed the latest lr-mame-2003-plus from binary, and then found several games that wouldn't run (Super Gem Fighter Min Mix is one example). I found that I still had the XML file that I'd used to generate the rom set, and compared it to the current version to see that the game's manifest had indeed changed.

This broke my understanding of a fixed, versioned rom set. Is it that lr-mame-2003-plus has since changed and requires a different version? The RetroPie documentation says that the core looks for "MAME 0.78-MAME 0.188," but if it supports 0.78 then why do I have some games that failed to run? If I just need to rebuild the rom set, I should use the current version's XML file right?

Thanks in advance for any help in understanding this. On the bright side I have an excuse to learn how to use ClrMamePro again.

**Comment by arcadez2003** [comment]
Sometimes the romsets change in this case it was due to updating the CPS2 driver to use a newer style of
rom decryption, as you said a rom scanning program will get all your sets matched up for this core..

Regards

**Comment by mahoneyt944** [comment]
> MAME 0.78-MAME 0.188

This should really say 0.78 - current, but yes always build with the latest xml file either downloaded from here or generated yourself from the mame menu. I would also advise building the core from source if you don't want to be running an old binary

**Comment by ceberz** [comment]
Thanks for the help!
