### ISSUE TITLE
sample changes talk

### ISSUE THREAD

**Issue by grant2258** [libretro/mame2003-plus-libretro#187]
all that has changed so far  is the the file ext .wav has been added to the dat for ost.  Mark will be dealing with this and plans some updates so its just a thread to keep it all in one place. Oh i added outrun btw

**Comment by grant2258** [comment]
well I had a strange problem today with my samples dir not working and it was the retropie end.

if your having problems with samples not loading do this 

cd /opt/retropie/configs/mame-libretrodo
rm retroarch.cfg
cp retroarch.cfg.rp-dist retroarch.cfg

**Comment by markwkidd** [comment]
agreed it makes sense to log the paths, will push a commit in a moment

**Comment by grant2258** [comment]
the strange thing is the default retroarch.cfg is pretty much not setting much  at all

**Comment by dankcushions** [comment]
this isn’t a retropie problem. if you delete or overwrite your config to retroarch defaults, what can retropie do? :) the rp-dist file is a copy of the retropie default retroarch.cfg for that system, so that reverts back to retropie’s settings as you’ve found.

**Comment by grant2258** [comment]
well you start mame save your config then your system is broke that cant be right

**Comment by markwkidd** [comment]
the paths are now being logged

**Comment by dankcushions** [comment]
> well you start mame save your config then your system is broke that cant be right. i never editing any of my files only save from rgui. I dont know what caused the issue
 
retropie’s default cfgs have (for example) the relevant system directory path for a retropie installation. if you delete or overwrite these files, retroarch will generate its own defaults, which don’t have the same paths (why would they?).

**Comment by grant2258** [comment]
@dankcushions the rp-dist file just includes a files in /otp/retropie which doesnt set much at all you should take a look

**Comment by grant2258** [comment]
this is the dist file 

# Settings made here will only override settings in the global retroarch.cfg if placed above the #include line

input_remapping_directory = "/opt/retropie/configs/mame-libretro/"

#include "/opt/retropie/configs/all/retroarch.cfg"

**Comment by dankcushions** [comment]
a retroarch generated default mame-libretro retroarch.cfg overrides or ignores the settings that are in /all/retroarch.cfg, and/or via the commandline arguments sent. i forget which.

the retropie version does not. you can’t expext retropie to function properly if you delete/reset its config.

**Comment by dankcushions** [comment]
here’s the crucial line you miss when you reset your configs to retroarch defaults: 

`#include "/opt/retropie/configs/all/retroarch.cfg"`

**Comment by grant2258** [comment]
I wasnt aware until now you cant save your config. ill do core from now on it will probably why so many people have broken mames with rewind enabled  Maybe this file should be read only :)

**Comment by dankcushions** [comment]
if you save your config it shouldn’t actually break anything as it will already have the stuff the /all/.cfg loaded. it will just leave you with one huge .cfg.

the problem is if you delete the cfg - retroarch will then generate a new one, and it will not be right for retropie. perhaps the runcommand could check for missing .cfg on launch, and regenerate if neccesary. might have a think about that one!

ultimately retropie isn’t fully locked down. it’s for tweakers, so we assume that people who are deleting and editing configs know what they’re doing. recalbox is a better choice if you wanted a (more) closed system. 

> cblogging stuff

again, logging in retropie can be handled by the verbose mode option in runcommand, but you have an issue open for that.

**Comment by grant2258** [comment]
again mame does full debug now your original failure wont be in the buffer because mame outputs so much in full debug. The point here is retroarch should be printing log cb info to the command line anyway. Ill wait for @markwkidd to confirm. We are just repeating the same thing.

**Comment by grant2258** [comment]
close this for now
