### ISSUE TITLE
dfjail

### ISSUE THREAD

**Issue by grant2258** [libretro/mame2003-plus-libretro#1893]
@arcadez2003 can you look at dfjail when it was added to mame. According to a fbneo dev there are missing components in fbneo. 

Apart from the pallet handling and inputs even our older segaic should handle it. Im planning to look over this at more at xmas. I managed to add a skeleton to see if it boots and its getting to the test screen.I would appreciate if you can see anything missing, perhaps something im looking past. It doesn't seem any different to the other Korean games. Obviously its a request for your opinion feel free to ignore it.

**Comment by grant2258** [comment]
Added the inputs games running fine just need to add the  pallet handling and the fix the sound up properly currently its missing speech.

![Screenshot From 2024-12-01 16-39-12](https://github.com/user-attachments/assets/10326d6d-ce30-4ae2-a042-c2400a1ea487)

**Comment by grant2258** [comment]
fixed palette need to sort the new sound maps was a pretty easy addition compared to some. 
![Screenshot From 2024-12-01 17-03-22](https://github.com/user-attachments/assets/3437f574-96c2-45b6-897c-0f18349c9246)

**Comment by arcadez2003** [comment]
Just noticed this now which is a good time to happen upon it when all the hard work is done :)
just the speech left to do then is there extra code required for that or is it just a case of rolling
back the sound rom loading as per we done with clockwork Aquario and a few others.??

**Comment by grant2258** [comment]
@arcadez2003  looks like its a dac and banking to be honest I was more interested in seeing if  the game working. I didnt even look at the sound memory maps just lucked out the standard one worked as is. Might as well close this for now games added. Will be one of us that will sort the sound in due time anyway and its marked as Imperfect sound. At least people on low end can play the game now.

**Comment by grant2258** [comment]
The speech has been added putting a request in now. Your very welcome @wn2000 its a game that I had never played before its pretty decent as well.

**Comment by wn2000** [comment]
Wow that was quick. Thanks again!
