### ISSUE TITLE
Can't insert coin in jparkmb/twinktmb

### ISSUE THREAD

**Issue by litaniast** [libretro/mame2003-plus-libretro#1901]
Insert coin button doesn't work on both games, so I can't play them.

Recently the PIC data of jparkmb is dumped so it's playable on mainline MAME(from 0.272). twinktmb is not playable on mainline either.

I think GAME_NOT_WORKING flag needed for them.

**Comment by grant2258** [comment]
I tested these they work fine just press p1 and p2 credit button at the same time and you'll get 9 credits.

**Comment by mahoneyt944** [comment]
Well I'm glad there's a work around to get coins in. Is that how current mame is? That seems like the port bits are off or something?

**Comment by mahoneyt944** [comment]
This looks it might work for these games if someone has a second to plug it in and see
https://github.com/libretro/mame2003-plus-libretro/blob/3fc99dfd31b91a9c46bc540261ac9058cbc8e168/src/drivers/segac2.c#L6349

**Comment by mahoneyt944** [comment]
Well this works the same as pressing both coin buttons. Though idk if that's the solution we want. I think the input rapidly enters coins which is why you get 9. Might need a coin lockout or some logic to ignore the press after the initial one until it's repressed so it just enters 1 coin at a time.
https://github.com/libretro/mame2003-plus-libretro/compare/master...Test

**Comment by arcadez2003** [comment]
> current mame uses a pic, you could compare the drivers to see if that is the issue not sure off hand, told arcadez we can credit up when we discussed it so I don't think anyone looked into it much more to be honest.

Yeah they just dumped a PIC or three for jurassic Park, Sonic 3 and Twinkle Tales however due to the trouble i had
trying and failing to hookup the PIC which drives the sound for Hard Times, im not sure if the code would be good 
for here hence i left it be.

**Comment by mahoneyt944** [comment]
@litaniast pushed update to allow coins to be entered easier. https://github.com/libretro/mame2003-plus-libretro/commit/bd51bc81b8616ce10480d3928dfa908f62df97d7

**Comment by litaniast** [comment]
Thanks. Confirmed.
