### ISSUE TITLE
A bug in src/mame2003/core_options.c

### ISSUE THREAD

**Issue by noword** [libretro/mame2003-plus-libretro#1904]
In `static void set_variables(void)`
Line 900:
```
static unsigned effective_options_count; 
```
`effective_options_count` is not initialized to 0，and I don't know why it is a static variable.

This caused a weird [bug](https://github.com/noword/Emu4VitaPlus/issues/11#issuecomment-2525365894).

When I change line 900 to:
`unsigned effective_options_count = 0;         /* the number of core options in effect for the current content */`
It fixed.

This problem also in here:  https://github.com/libretro/mame2003-libretro/blob/master/src/mame2003/core_options.c

**Comment by mahoneyt944** [comment]
I'm guessing that the code doesn't expect `retro_load_game()` to run more than one time in the same session. I see no harm in making that change though.

**Comment by mahoneyt944** [comment]
Pushed an update
