### ISSUE TITLE
a 'unified with FBA retropad` input mode

### ISSUE THREAD

**Issue by markwkidd** [libretro/mame2003-plus-libretro#191]
Now that @dankcushions has laid down the tracks to have various default controller mappings, I just want to log an idea for future reference.

There was a PR to mame2003 in October by @barbudreadmon that didn't reach consensus but proposed to unify the default retropad mappings for mame2003 and final burn alpha (fba). This is the PR: https://github.com/libretro/mame2003-libretro/pull/123

We've even referred to this discussion in our own discussions of the retropad mapping here. In my lack of firsthand experience with the new retropad modes due to my reliance on keyboard input right now, can I ask: how far apart are our existing retropad mapping options from the defaults in final burn alpha?

If we don't have "FBA Mode", is it worth adding to the lineup? It seems like that would definitely please people who use both cores with a gamepad/joypad/retropad.

**Comment by dankcushions** [comment]
the 'modern' layout i did is the same as the FBA mode, which was also the same as the layout in https://github.com/libretro/mame2003-libretro/pull/123

**Comment by markwkidd** [comment]
Thanks, I'm jotting a few Getting Started thoughts into the wiki for this repository. I've just added a note to that effect here: https://github.com/libretro/mame2003-plus-libretro/wiki

I don't think that repo wikis are a good long term doc solution for an individual core, but the good thing is that markdown is compatible with the libretro docs and the retropie docs
