### ISSUE TITLE
Centre Court

### ISSUE THREAD

**Issue by arcadez2003** [libretro/mame2003-plus-libretro#1913]
Hi fellas it'll soon be xmas and then it's 2025 another year has come and gone i hope it's been a good
un for ya's and next year even better, anyway alotta devs like to dabble with some code during the
festivities so i decided to look into adding Centre Court.

It's still wip but if one of ya's could give it a whirl and lemmie know if it's close or miles away from
working here.?? rather than rabbiting on as per usual i've left some small notes in the driver :)

Interesting story about how this game was dumped it was "rescued" from an abandoned leisure centre
along with a whack a mole Street Fighter game.

**Comment by mahoneyt944** [comment]
Check discord

**Comment by grant2258** [comment]
Is showing signs of life, the inputs dont seen to work you can credit up and start the game though the text shows up fine but the screen is basically mostly black during gameplay and you cant input your name. It will probably be some simple fix up in the mem map, the sound isint working properly either again this could be the mem map as we dont use the auto mapper that the newer  versions of mame does. Seems like @mahoneyt944 has this one covered though so hopefully we bag another sega from crimbo. Hope all goes well for the new year. This year wasnt too bad just went in so fast.

**Comment by arcadez2003** [comment]
> Check discord

No can do as the silly site demands a 2FA check via email when i try to login and i dont have the same address as i once did im sure i could update to use my new email but it's late and i cant be assed :)

that is the internet circa 2024 yet more barriers standing in the way of what i want to do.

Yip as i always say i just love all this advancement it's so much better than 20 years back :)

**Comment by arcadez2003** [comment]
Thanks for taking a look guys it's becoming a regular thing eh i'll need to either call it a day or set up
a proper bona fida dev environment so i can dabble and test without asking for help every two mins
as it's not really fair is it.

**Comment by arcadez2003** [comment]
> Hope all goes well for the new year. This year wasnt too bad just went in so fast.

Aye the older ya get the quicker each year seems to pass as for how well 2025 will turn out to be.??
i guess that all depends on if the ruling classes wisen up cos they're taking us down a path which
can only lead to us all playing a true life version of Fallout.

**Comment by mahoneyt944** [comment]
I wonder how difficult it would be to add a Xbox to the buildbot if it isn't already.

**Comment by arcadez2003** [comment]
> I wonder how difficult it would be to add Xbox to the buildbot if it isn't already.

My xbox died and i threw it out a while back and if that is not enough a windows update 
killed my VS2003 compiler it just starts up and then closes back down hence i can no longer 
compile any of  my ole sources.

Yip i just love all this advancement with all new and better stuff LOL

**Comment by arcadez2003** [comment]
Im sounding like im suffering from techophobia here :) but i'll be honest i preferred the world
20 years back things were simpler you only had 5 tv channels and they had everything that was 
worth watching for free vs 100 different pay tv streaming options 

Ya bought a game which ya owned outright it worked outta the box without having to spend 
half a day setting it all up only to become an unpaid beta tester.

Ya could walk down the street without some fuckwit bumping into ya as whatever is 
happening on their smartphone is more important than navigating around the real world.

And we dealt in reality over fantasy eg being forced to join in with the delusions of the mentally ill
who want to pretend they're something which they're clearly not otherwise it's a hate crime.!!!

Yip lemmie hit rewind i wanna go back to the naughties :)

**Comment by grant2258** [comment]
@arcadez2003 its not an issue checking if somethings working. All you need to compile retroarch and this core is mingw64. RA used to have guide to install mingw not sure if they still have it though. The worlds certainly a more complicated place these days.

**Comment by mahoneyt944** [comment]
I didn't have much luck with cencourt either. Same results as grant.

**Comment by arcadez2003** [comment]
> I didn't have much luck with cencourt either. Same results as grant.

I wonder if hanging it off the passing shoot gfx offsets and such will sort most of the problems
leaving just the inputs.?? anyway this is no biggie i can easily just remove it we have a couple
of working bootlegs.

It would have been nice to have had an bonafida official set though

**Comment by grant2258** [comment]
@arcadez2003 leave it there for now ill have a little peek, dont delete it quite yet might be fixable. I cant look at right at this moment but will let you know if i hit a brick wall with it. I assumed mahoneyt944 had it fixed or knew what the issue was.

**Comment by mahoneyt944** [comment]
If nothing else just tag it not working I wouldn't totally remove it. Might be a gfx decode issue or something.

**Comment by mahoneyt944** [comment]
@grant2258 removing the driver init hookup will bring back the graphics. This one must not need inverted like the the bootlegs. Though it's still not aligned correctly.

**Comment by grant2258** [comment]
@mahoneyt944 just use the newer segaic, it can be used in system16 or segas16b or you can mess about with the old code if you prefer.

**Comment by mahoneyt944** [comment]
Tbh I've forgotten more than I remember about system16 lol. It's probably not a big fixup either way but I'd have to get reacquainted. Not sure about the sound though.

**Comment by grant2258** [comment]
The sound issue is likely the banking not being done properly. Ill try get it up and running at the same time passing shot itself most likely has decrypted sets as well do we want to add these as well or just cencourt? 

The 8123 protection doesnt look too hard to implement its not really needed. Like @arcadez2003 said we can use the decrypted rom from passing shot. If there would be anything beneficial to adding the 8123 decryption beyond this one game it could be added just not sure if there is any games we are missing because of this particular decryption being missing.

**Comment by mahoneyt944** [comment]
It's probably ok without it unless you just want to add the decryption. I think we have a working romset for all the decrypted sets anyhow.

**Comment by grant2258** [comment]
Had a quick chance to get this tested and the game is working fine with sounds. Ill just need to address the inputs. I used the new segasic and updated segas16b driver for testing though. The sound command is at 0xc00006 (this differs from the bootleg)   Im pretty sure the banking needs addressed on the old driver. I could be remembering wrong though.

**Comment by grant2258** [comment]
> It's probably ok without 8123 protection unless you just want to add the decryption. I think we have a working romset for all the protected sets anyhow.

@mahoneyt944 I was asking about this for games that could need this outside this driver. It doesnt look hard at all to implement  was more a question if there was any need for it.

**Comment by arcadez2003** [comment]
> > It's probably ok without 8123 protection unless you just want to add the decryption. I think we have a working romset for all the protected sets anyhow.
> 
> @mahoneyt944 I was asking about this for games that could need this outside this driver. It doesnt look hard at all to implement was more a question if there was any need for it.

We have some mc8123 decryption already although it's in the older format before they switched it
over to use the key style...

* Added support for the English Virtual console version of Wonder Boy in Monster Land and added the mc8123 decryption so that the Japanese versions work [arcadez]
* 
*  Updated the mc8123 decryption and hooked it upto Altered Beast, Ninja Kid II, Ufo Senshi Yohko Chan and Wonderboy In Monsterland [arcadez]

Apart from the above the remaining games that use it are mostly in freekick.c and the System E
version of Fantasy Zone II and Opa Opa although with the latter we do have a decrypted set.

**Comment by grant2258** [comment]
Cheers for the info was just checking if the mc8123 was something we needed. I should guessed you already done it for where it was needed. Like I said in the pull request feel free to move these games to  the older driver the memory map was fine btw apart from the sound command needing added.
