### ISSUE TITLE
Audio problems with Sega System 16/18 

### ISSUE THREAD

**Issue by darksaviorx** [libretro/mame2003-plus-libretro#195]
These bugs also exist in mame2003. Bootleg versions are used if the main version won't load at all due to its protection. I'm using a Pi3b+.With the little I've tested, this is what I've noticed:

Moonwalker bootleg (moonwlkb.zip): Higher pitched audio. 
Shinobi (shinobi.zip) : Drum audio channel stops working a few seconds into the second level.
Shinobi (shinobl.zip): Music plays at a lower volume than the sound effects/voices. Voices don't play all the way. Example, when you jump, instead of saying "OOOH!", he says "OOH". Drum audio channel is fine on the 2nd level. Since the main version works, it's not really needed to be fixed, but it's weird how the drum channel works.
E-Swat bootleg (eswatbl.zip): No voice audio. Music plays at a lower volume than the sound effects.
Golden Axe (goldnaxe.zip): Music plays at a lower volume than the sound effects/voices. 

I compared them to lr-fbalpha which emulates them fine for the most part..except Shinobi. FBA has lower pitched voices and music.

**Comment by grant2258** [comment]
@darksaviorx dont use either one as a benchmark for the pitch compare with the latest mame pitch to see which one is right. There has been a change to fba alpha audio in the last day or two please compare them both again and also test both with robocop as well its easier to tell timing pitch changes with this game

**Comment by darksaviorx** [comment]
@grant2258 Oh, there's no doubt the audio pitches are wrong, I just wanted to have an example for people to compare if they had their doubts. You're right, mame is a better benchmark.

**Comment by grant2258** [comment]
ill look into this and see sound timing if its wrong ill try tighten up the sound timing code if thats whats causing it

**Comment by arcadez** [comment]
These games are all fine audio wise when using MAME84, so i guess something changed
either on the system16 side or in the sound cores the games use i'll look into this later.

**Comment by darksaviorx** [comment]
@grant2258 Woops, my bad. I used shinobi2.zip to test it with lr-alpha. I re-tested with shinobi.zip and the only flaw is the incomplete voice effects problem that shinobl.zip has with mame-2003-plus.

**Comment by grant2258** [comment]
i think that is a 078 mame bug as well @darksaviorx  not sure if arcadez updated the system16 driver

**Comment by darksaviorx** [comment]
@grant2258 I'll test on latest mame when I can. Briefly looking at that video, it has the right pitch, the voices don't get cut, but amazingly it has the missing drums in level 2. I wonder if a board revision fixed that.

**Comment by grant2258** [comment]
which set has the missing drums shinobi or shinobl and ill play till level 2 and check on mame 078

**Comment by arcadez** [comment]
Nope the Sega drivers are all as they were in this core originally the only difference being
i added some graphical fixes for Hang-on and Sonic Boom which in no way affected
the sound in any of the games.

**Comment by grant2258** [comment]
yea cant see that having any effect on the audio just want to see if this problem is on mame078 as well and we can search from there just want to clearly identify it

**Comment by grant2258** [comment]
@darksaviorx ok so shinobi is fine apart from the  samples cutting im pretty sure it does this on mame078 as well. 

is moon walker ok or does it need looking at?

**Comment by darksaviorx** [comment]
@grant2258 As I mentioned in my starting topic, the exact same bugs happen on plain lr-mame2003 as well. 

Also, to summarize:
Using 2003 normal or plus: shinobi.zip = Everything fine except for the drums that get cut off in level2.
Using 2003 normal or plus or lr-fbalpha: shinobl.zip = voices cut near the end in both. I get drums in both. 

Using 2003 normal or plus: moonwlkb.zip has high pitched audio. No need to compare it to anything. It's easy to tell.

**Comment by grant2258** [comment]
@darksaviorx  thanks well that rules timing core issues out for shinobi at least ill look at moonwaker on mame078 and mame2003-plus and see if its something new that was introduced. Does the moon walker bootleg work ok in fba?

**Comment by darksaviorx** [comment]
@grant2258 I've only tried the real moonwalker in fba and the audio is fine. I do get slowdowns on my poor pi..the whole reason I prefer 2003-plus when I can.

**Comment by grant2258** [comment]
just tested on mame078 the samples seem wrong pitched on that as well doesnt seem like anything new was introduced which is some good news

**Comment by arcadez** [comment]
I always played these games in MAME84 and they sounded perfectly fine so i compaired the
code vs this core and we match up totally with regards to all the System 16 based games
so i feel there as good as their gonna get pre the MAME89-94 huge update for all the Sega 
games

However these are some improvements on the system18 side which we are missing here
Moonwalker is a system18 game i might look into backporting these changes and with a
bit of luck it'll sort the issues mentioned here.

**Comment by arcadez** [comment]
Ok i noticed something at some point after MAME72 the MAME dev's added a new RF5c68 
soundcore then in MAME79.u1 they reverted this change i can only assume this was done for 
good reason and guess what the system18 games use this.

On spec i added this core from mame2003 to my test build and bang the sound is worse
in the three playable system18 games i tested so i am gonna do what the mame dev's did
and just revert this soundcore to what it was previously

R. Belmont reverted the RF5c68 to old version 

@darksaviorx lemmie know if this solves the problems in moonwalker

**Comment by grant2258** [comment]
sound better to me @arcadez !

**Comment by darksaviorx** [comment]
@arcadez Moonwalker audio issue is fixed. Thanks!

**Comment by arcadez** [comment]
Ok then another happy ending i'll close this now

**Comment by grant2258** [comment]
@arcadez do you still have the source to the big system16 update would like to try fix it if possible

**Comment by arcadez** [comment]
I dont have a backup copy of it however the original commits and reverts are here.........

https://github.com/libretro/mame2003-plus-libretro/commits?after=bb1a6b8897448b576fd9dc796e88a874817fb509+419&author=arcadez

After i tested it out i noticed all the games would stall on a black screen on boot, i suspected
it might be something to do with some memory map changes.......

static MEMORY_WRITE16_START( alexkidd_writemem )
	{ 0x410000, 0x410fff, SYS16_MWA16_TEXTRAM },
	{ 0x400000, 0x40ffff, SYS16_MWA16_TILERAM },
	{ 0x440000, 0x440fff, SYS16_MWA16_SPRITERAM },
	{ 0x840000, 0x840fff, SYS16_MWA16_PALETTERAM },

static ADDRESS_MAP_START( alexkidd_writemem, ADDRESS_SPACE_PROGRAM, 16 )
	AM_RANGE(0x410000, 0x410fff) AM_WRITE(SYS16_MWA16_TEXTRAM) AM_BASE(&sys16_textram)
	AM_RANGE(0x400000, 0x40ffff) AM_WRITE(SYS16_MWA16_TILERAM) AM_BASE(&sys16_tileram)
	AM_RANGE(0x440000, 0x440fff) AM_WRITE(SYS16_MWA16_SPRITERAM) AM_BASE(&sys16_spriteram)
	AM_RANGE(0x840000, 0x840fff) AM_WRITE(SYS16_MWA16_PALETTERAM) AM_BASE(&paletteram16)

Maybe i forgot to define the extra writes you see above but it could be anything i suppose, i meant
to look at the code again but never got around to it

**Comment by arcadez** [comment]
Well it's not good as it broke everything :) the reverts from Nov 25 apart from the sharrier.c and
Rf5c68 soundcore changes is where we are at Sega 16/18 wise just now

**Comment by grant2258** [comment]
ill debug where its crash probably tomorrow cause im off work ill update you with info if you like when i find anything out. Unless your completely fed up with it m8

**Comment by arcadez** [comment]
Nah not totally fed up at all it's just i've ran outta things i can backport atm, i originally tried the
update due to bug reports which in the end turned out to be on the RA side i think you fixed
these display problems with Altered Beast etc etc.

So since i did the Hang-on fix already there is not much left to make updating the Sega core
all that viable just some small graphical improvements i think plus sound for Tough Turf 
although it has broken gfx anyway.

**Comment by grant2258** [comment]
https://github.com/grant2258/mame2003-plus-libretro/tree/system16

its in its original state as it was then outrun ost if gone and any changes you made since then but just want to try fix it without more complications at least its ready to start testing for me

**Comment by grant2258** [comment]
shinbi gives a Segmentation fault thats great news for tracing it!

**Comment by grant2258** [comment]
ok mr arcadez good news and bad i got it working well outrun and shinobi are without any code code changes to you code. The input code was segfaulting ill need to look into what going on there.

is there anything in particular i should be testing ?

**Comment by grant2258** [comment]
im an idiot have it running on windows too looks like a few fixes are needed not much tbh are you still interested in still integrating this?

**Comment by arcadez** [comment]
Not really but feel free if ya wanna do it ;)

**Comment by grant2258** [comment]
I'll fix it up and archive it for future use on other cores if they need it

**Comment by grant2258** [comment]
ok well im sorry to say this but it was a rookie mistake i made i had compile the new code with the old system16.h header this caused segfaults. 

This does add to 2 games the code just works as is on windows and retropie as is @arcadez it might be related to the sound problems i fixed that got the ole tapper games working.

**Comment by grant2258** [comment]
i know the outrun ost needs added to this is there anything else youve changed I need to pull into this code?

**Comment by grant2258** [comment]
@markwkidd or anyone else can you do me a solid when you have time.

Ive added arcadez big sega update here can you compile and test the system 16 games are running ok for you. Im testing on the pi and linux tomorrow. I still have to change the logging so dont add it yet I want to do everything in one commit. I keen to see if altered beast scrolling improves

**Comment by arcadez** [comment]
I've been reading the reports about the sound troubles in the system16 games they use a
combination of quite a few sound cores across the different games i suppose i could check
them vs MAME84 sometime their all handled in machine system16.c of course i cant rule
out not being an expert on how these games should sound eg "they sound alright to me"
maybe they are borked in MAME84 also..??

There is a slight change for system18 and a reclock of the sound core those games use but
apart from that no mention of any big fixup for the system16 games, as @grant2258 mentioned
it could be a panning issue where the sound is set too high for some sounds which then drown
out the others or infact it's just the way of in some cases hacky bootlegs.

**Comment by arcadez** [comment]
@grant2258 apart from the sound sample additions for say Outrun the code should be
the same in the update to what we have now more or less barring a few game additions
some small gfx fixes and sound in Tough Turf.

Talking of Tough Turf i was able to get one of the versions displaying correctly i might revist
this again

**Comment by grant2258** [comment]
@arcadez here is your system16 updates from nov so you have a backup. Im going to delete my branch and start over.

Ill need to add moonwalker ost as well the super hangon changes should be in there anyway i just didnt touch that one before because you fixed the road im guessing this update done it

**Comment by grant2258** [comment]
[arcadez.zip](https://github.com/libretro/mame2003-plus-libretro/files/2545162/arcadez.zip)

**Comment by arcadez** [comment]
Thanks but i dont think i'll need it anymore, alright to finally put this to bed i've been over
the sound code and sound cores which the Sega system 16 games use everything barring
a few small changes for the system 18 games is the same i can only conclude that this core
has the exact same code to drive the sound for these games as MAME84.

This means one of two things the same sound niggles are present in the core i always used and
i just never noticed :) or there is something going on with this core which might be causing it..??

Finally there is an improved version of the UPD7759 sound core which required a rewrite to fix
up the sounds in Cotton when it was made playable this might explain why you dont get the
reported bugs with later MAME builds.........

0.91u2: uPD7759 rewrite, fixing sound in System 16 games [Aaron Giles].

The above is doable i think for this core the testing of all the games afterwards is what put's
me off a ton of Sega and Konami games use this.

**Comment by grant2258** [comment]
im not sure what audio is missing from shinobi i would need to hear the difference tbh. I notice any audio issue again we wouldn unless someone pointed it out clearly

**Comment by arcadez** [comment]
First post in here lists em minor stuff though.

**Comment by grant2258** [comment]
anyway i just posted her because i didnt want to make a new issue about the video fixes tbh. They do work ill add the ost stuff in and get them merged at some point.

**Comment by darksaviorx** [comment]
I'll paste/refine what I said in the retropie forum: 

Re-testing with mame2003-plus (might be a few weeks old): shinobi.zip = missing audio channel in level2 if you wait a few seconds. shinobl.zip= Music low, Jump audio cuts out. Volume for sfx seems high. Audio channel intact. By audio channel I mean the drums/beats whatever. I prefer shinobi.zip fixed and not use bootlegs. 

mame-2010 (0.139). shinobi.zip= Jump audio has pop/static. Audio channel intact. shinobi2.zip seems perfect.

For e-swat I used the bootleg version eswatbl.zip since eswat.zip gives me a black screen. I used mame2003-plus. Missing voices. 

My suggestion, if possible, being ignorant in coding, is backporting the non-bootleg sets of system16/18 along with newer driver from 2010 or beyond since that seems to work fine with both shinobi and eswat. Maybe others but I haven't done extensive testing in the rest.

**Comment by arcadez** [comment]
Backporting the newer drivers is not possible too much incompatible code plus our M68k CPU
cant handle the FD encryption most of them would require, a better bet would be to backport
the improved UPD7759 sound but it would require a fair amount of graft which being honest
here i dont wish to undertake

**Comment by darksaviorx** [comment]
I understand. Thanks for taking the time of looking into it.
