### ISSUE TITLE
Creating a datfile for this new core

### ISSUE THREAD

**Issue by arcadez** [libretro/mame2003-plus-libretro#2]
Ok dont be scared if you wanna talk datfiles then dont worry i wont bite well not much anyway :)
i recently spent a couple of hours updating the Neogeo driver phasing out the Kwacks roms
adding ones which match up with MAME plus their full CRC and SHA info.

I was however due to code limitations unable to do one for kof2003 as the decryption code
had changed by the time that game was playable to the extent it would not easily drop into
this core without me having to update a whole lotta Neogeo related code which infact would
have been worse as every rom would have needed updated rather than just the handfull i
added support for.

Lemmie know if this has helped with regards to datfile creation..?? also any others you may be
having issues with..?? but if the worst comes to the worst i do have a backup plan which we
should be able to create a full datfile from but it's rather hacky and well better left as a last
resort.

**Comment by markwkidd** [comment]
Thanks for this post @arcadez , I just saw it.

Could you post the CRC & SHA info for those non-Kawaks NeoGeo ROMs? It would be great to merge those into @Riverstorm 's draft DAT file.

(you can take a look at the draft DAT here if you haven't seen it): https://drive.google.com/open?id=1A5t_nfjzoQCTN9tHarGmhEXNVM4rSRm-

**Comment by arcadez** [comment]
This should be of some help hopefully

[url]https://www.sendspace.com/file/v0cwbi[/url]

**Comment by markwkidd** [comment]
@grant2258 do you mind if we move conversation about the DAT generator over to an issue. Since it seems like it's going to be more than a 1-PR kind of fix.

I've removed all the logging in usrintrf.c from the current master branch. I think the problem is still log related somehow, just not those lines. At any rate, with a freshly compiled RetroArch and a freshly compiled mame2003-plus-libretro I still have a segfault when I try to generate the XML DAT here.

**Comment by grant2258** [comment]
i need to get to work but is it doing it in windows and on linux or just windows?

**Comment by markwkidd** [comment]
Sadly segmentation fault in both Windows and Ubuntu.

No worries about work - I have been tagging you in a lot of things I realize but I am almost to the end of my weekend and I'm trying to wrap up my notes. Feel free to take days or longer to reply -- that happens with me.

In fact it will unfortunately be a couple of weeks before I'm back home for a weekend day to spend working on emulation again.

**Comment by markwkidd** [comment]
I may have a tendency to talk to myself in github.

Think I have the fix just pushed. It was a logging line over in osd.c that was choking on our xml file somehow I guess. It's not a popular line of code already so it's gone.

**Comment by grant2258** [comment]
nice find mark just finished a shift going to grab a coffee and some zzzzs

**Comment by grant2258** [comment]
well we are at a point again we have to decide to keep the nodump as valid because it broke a merge with a badly configured prototype driver. Personally i think the driver should be patched in this case its really up to you guys where to go with this one. See the thread https://retropie.org.uk/forum/topic/13638/lr-mame2003-driver-improvement-and-backport/312

**Comment by grant2258** [comment]
i just fixed the driver conflicts and added the nodumps back in

**Comment by arcadez** [comment]
Hmmm it's the same roms eh but marked bad_dump in both the prototype clones, 
the only reason for this is likely they never got a dump of those soundroms for
both of the prototype versions and just used the same ones from the parent rom.

This is why they tagged em as a bad_dump in those versions as they couldn't be sure
the prototypes actually used the same soundroms, anyway you could have just removed
that flag totally from both of those roms like so..........

ROM_REGION( 0x30000, REGION_SOUND1, 0 )	/* 192k for ADPCM samples */
ROM_LOAD( "hydr1037.bin",  0x00000, 0x10000, CRC(b974d3d0) SHA1(67ecb17386f4be00c03661de14deff77b8ca85d0) )
ROM_LOAD( "hydr1038.bin",  0x10000, 0x10000, CRC(a2eda15b) SHA1(358888ffdeb3d0e98f59e239de6d7e1f7e15aca2) )
ROM_LOAD( "hydr1039.bin",  0x20000, 0x10000, CRC(eb9eaeb7) SHA1(cd8e076b07588879f1a0e6c0fb9de9889480bebb) )

Hmm i wonder if they actually got the correct dumps or the driver still has that flag in latest
MAME im curious now so i'll check it out later

**Comment by grant2258** [comment]
nit was originally nodumps that causes the problem baddump is the right thing to do here so we know the sets still need a newdump

**Comment by grant2258** [comment]
I think clrmamepro doesnt like the baddump status tag ill fix it not to print the status flag when i get in from work

**Comment by grant2258** [comment]
i would like to retract that last comment the dat is  fine i had my scanner on none merge and rebuilder on split the tags are fine

**Comment by arcadez** [comment]
Just a heads up the dat will now be slightly different due to some recent changes.......

A working version of glass is now supported (glasskr.zip)
Mustache Boy will require the T5182 sound rom to be inside (mustache.zip)
Metal Slug 5 and  Samurai Showdown 5 now use a different redump of the soundrom
The King Of Fighters 2003 Decrypted (kof2003d.zip) is no longer supported
SNK Vs Capcom : SVC Chaos the whole rom has been changed to match up
with MAME also the name of the rom has changed to (svc.zip)

BTW these two are official Capcom CPS2 and Neogeo games and are supported currantly
in MAME i dunno how some fella on the Rpi forums seems to think they're unofficial hacks

Hyper Street Fighter 2 (Asia) (hsf2a)
SNK Vs Capcom : SVC Chaos (svc.zip)

**Comment by Wilstorm** [comment]
Sorry guys I thought you guys were also getting those same few ROMs as not found when using the current set and rollback since no one said otherwise. When rebuilding from scratch you're at 100% with official ROMs? I usually follow what Pleasuredome does so I am curious to find out what I am missing. When I generate XML DAT from the TAB menu is it dumped somewhere? My DAT is several days old from last week.

gamez-fan I am holding you to the no biting promise. :)

**Comment by grant2258** [comment]
it gets dumped in the bios folder

**Comment by Wilstorm** [comment]
@grant2258 Thanks Grant I looked all over the config folder then all over under the mame2003-plus ROM folder. I never thought to look in the place that actually makes sense. :) One more quick question the best way to get the most current DAT is with the built-in generator? That's a really slick feature you added.

**Comment by grant2258** [comment]
The dat generated from mame is the one that version mame requires it grab it's data from the the drivers sources. It was mark that added this feature to the mame menu

**Comment by arcadez** [comment]
Just a heads up Explosive Breaker didn't make the cut so i've removed it from the newly
supported games list, however the japan version of this game Bakuretsu Breaker is now
playable in this core via my Kaneko16 updated from a while back.

Regards
