### ISSUE TITLE
Golden Axe II (ga2.zip)

### ISSUE THREAD

**Issue by Loggahead** [libretro/mame2003-plus-libretro#201]
It loads in mame2003 but but gives a warning message that the video emulation is not 100%.  Once in the game, shadows are artifacted with white pixels in them.  I tested this in lr-mame2003 and lr-mame2003+

**Comment by Wilstorm** [comment]
I've been redoing my snaps here's what the shadows look like during play.

![ga2](https://user-images.githubusercontent.com/8192258/40081003-59a161dc-5852-11e8-983e-376ef3aa91d5.png)

**Comment by arcadez** [comment]
I have a updated driver which fixes the shadow problems with the tiles and sprites
most noticable on level 2 in the caves and with certain enemies on most of the
later levels.

Unfortunately due to incompatable code namely inputs and memory maps
from MAME99 i cant backport it to this core :(

**Comment by Loggahead** [comment]
Yep, I agree, definitely playable!  Thanks so much!

**Comment by grant2258** [comment]
there was a fix done for sprite priories can remember what version of mame done this the priority problems show at the waterfall

**Comment by markwkidd** [comment]
Does it seem like there is anything else to try or test here, or can the issue be closed?

**Comment by Wilstorm** [comment]
@markwkidd - I think it can be closed. It does run ok but has some shadows issues that can't be fixed easily or incompatible code @arcadez pointed out.

**Comment by Loggahead** [comment]
I agree, can be closed!
