### ISSUE TITLE
Rampage (rampage.zip) audio issues:

### ISSUE THREAD

**Issue by Loggahead** [libretro/mame2003-plus-libretro#202]
When Rampage loads there is a lot of whining and static noise that stays throughout the title screen and doesn't go away until gameplay starts.  It's worth mentioning that I used to play Rampage in lr-mame2010 and it worked fine other than a few audio bumps and clicks when the game first loaded.  Now, it does the same thing in 2010 as it's doing in 2003+

**Comment by grant2258** [comment]
https://github.com/libretro/mame2003-plus-libretro/issues/175 check this setting

**Comment by grant2258** [comment]
this is how the sound should be https://www.youtube.com/watch?v=Au7UYaqpJw8

**Comment by Loggahead** [comment]
All I get is static white noise through out the entire title screen.  When I put a quarter in, I can hear the credit input sound but the static is playing.  The static whitenoise doesn't go away until I am actually controlling the character.  The game doesn't crash though.

Where is this rewind option? I was reading through that thread but didn't see where to actually check that setting?

Note that I have romsets for both 2003 and 2010 and I used to play Rampage in mame2010 on retropie 4.3.  Now that I am on 4.4 it does the same thing on mame2010?  Weird huh?  Maybe I can make a video of what's happening.

**Comment by grant2258** [comment]
if you have pressed select +x  and saved your retroarch.cfg you probably broke your lr-mame settings

**Comment by grant2258** [comment]
[INFO] [Config]: loading config from: /opt/retropie/configs/mame-libretro/retroarch.cfg.
[INFO] [overrides] no core-specific overrides found at /home/pi/.config/retroarch/config/MAME 2003-plus/MAME 2003-plus.cfg.

I would start by deleting them 2 configs

then type 
cd /opt/retropie/configs/mame-libretro/
cp retroarch.cfg.rp-dist retroarch.cfg

that should bring you back to your defaults

**Comment by Loggahead** [comment]
I have not saved a retroarch.cfg.  I only use the main one.  Inside emulators, I only use core or game remaps using RA which save out as .rmp.

**Comment by grant2258** [comment]
well i would try this if was you it fixed any issues i had

**Comment by Loggahead** [comment]
I'm at work now so I can't 100% verify it.  But I'm 99% sure that's what my retroarch.cfg looks like.  Like I said, I purposefully don't mess with separate retroarch.cfg's and only use the global one.

I will doublecheck though.

**Comment by grant2258** [comment]
ill try debug this more the issue doesnt exist in windows or Linux (x64) however it is present on retropie (arm)  since its doing it in mame2003 and 2010 i think we can safely say its something in the setup that end

**Comment by grant2258** [comment]
well i still have retropie 4.3 on sd card complied thelatest mame2003+ no problems at all on that. It must be a sound driver issue or a retroarch issue on 4.4 you probably want to report this on the retropie forums it is a big update and its still early days

**Comment by Loggahead** [comment]
Roger that.  I made a video of it and am uploading it to Youtube now.  It's no worries on testing in windows, you were just doing what you could to help verify.  

I did verify that my retroarch.cfg is empty.

**Comment by Loggahead** [comment]
https://www.youtube.com/watch?v=AjVQxcEShMg&feature=youtu.be

**Comment by ZappaUtopia** [comment]
@grant2258 Just for the record, I m using Retropie 4.4 and do NOT have this static issue.

**Comment by grant2258** [comment]
@ZappaUtopia  well i have a pi 2+b and am using the audio jack. I think the hdmi audio will probably be ok if its that old bug thats came back

**Comment by Loggahead** [comment]
I am using an audio jack as well.  Sounds like you're on to something.

**Comment by markwkidd** [comment]
There are some threads on the retropie forums about adding a custom commandline or something like that fixes audio out from the 1/8" jack. It seems like that's the issue here. Can this be closed?

**Comment by Loggahead** [comment]
This can be closed!
