### ISSUE TITLE
[Request] Sega Rally Championship (srallyc) backport

### ISSUE THREAD

**Issue by thatman84** [libretro/mame2003-plus-libretro#220]
Come across this game today and got excited but its not running well on current mame cores on shield TV.

If it hits anyones radar and has "back-port-compatibility" it could be a nice addition.

I believe the driver goes back to .80 version if @markwkidd is correct.

Many Thanks

Toby

**Comment by arcadez** [comment]
Sega Rally is flagged as not working on the latest MAME but two CPU's and a bucket load
of code which are not compatable with the MAME2003 core kinda rules it out anyway.
