### ISSUE TITLE
Add sound to Deep Scan

### ISSUE THREAD

**Issue by UDb23** [libretro/mame2003-plus-libretro#241]
It's actually more a feature request than an issue. There do is an issue with sound but even latest mame does not provide sound for Deep Scan.
The fact is that vicdual machines had same mainboard but different specific soundboards.
On the other hand recently support for sound daughterboard in N-sub (another vicdual rom) has been added (by writing a sample player) . I posted a comment on that github commit ([here](https://github.com/mamedev/mame/pull/2192)) requesting if this could help also for getting sounds in Deep Scan. 
If more people will request it there too, maybe the developer creates a sample player also for deep scan and then it should be possible to backport it.

**Comment by markwkidd** [comment]
I saw your comments on the mamedev PR about this, but does this request have its own issue over in their repo?

There is no need to close this issue here but it would be good to try to get a definitive answer as to whether 'upstream is friendly' to this.

**Comment by UDb23** [comment]
Just opened the issue [there](https://github.com/mamedev/mame/issues/4532).
I think we can close this one, thanks.
