### ISSUE TITLE
Lethal Enforcers image mirrored 

### ISSUE THREAD

**Issue by cucholix** [libretro/mame2003-plus-libretro#243]
Lethal Enforcers was ported to plus few days ago, it runs pretty well on Wii U, but the game image is mirrored, the d-pad controls are inverted too.
![img_20180527_155554194](https://user-images.githubusercontent.com/16081693/40593014-42536570-61f3-11e8-973e-a8dc420c40f8.jpg)

Thanks for including this game on plus!

**Comment by grant2258** [comment]
https://github.com/libretro/mame2003-plus-libretro/issues/133

**Comment by markwkidd** [comment]
As I feared @cucholix this will need to be part of the bigger fix so there's not a quick fix just for Lethal Enforcers. It's on the radar though... LE will need to wait a little longer

**Comment by SaucySarah** [comment]
Temporarily, you can manually reverse the controls for left and right and play all the mirrored games, but with mirrored text !

**Comment by SaucySarah** [comment]
For this game you can flip the screen in the service menu (F2) and then reverse the Up & Down controls. You reload by moving to the top of the screen and firing.

@markwkidd or @grant2258 I am using RetroPie. I have a joypad but I also have a mini keyboard that has a touch pad on it. Do you know how to get this to work as a mouse ? At the moment it doesn't do anything (it did in an older version of RetroArch). I have tried changing the Mouse Index but still no luck.

**Comment by grant2258** [comment]
@SaucySarah  make sure the mouse option is enabled in mame options. If that doesnt help try change the input interface to simultaneous since the mouse pad is build into the keyboard its worth a try.

**Comment by SaucySarah** [comment]
Still couldn't get the touchpad to work. Does anyone on here have something similar to this and is able to use the touchpad as a mouse on any RetroArch emulator ? Please let me know how you did it.
![mini wireless keyboard](https://user-images.githubusercontent.com/39570125/40885185-5603677a-6719-11e8-82ae-d07e7a3f6031.png)

**Comment by grant2258** [comment]
i have a rii keyboard like that for my tv box will have look when i get time. Is a normal mouse work for you sarah?

**Comment by SaucySarah** [comment]
Yes, if I plug in a wired mouse and change the Mouse Index it works but I have had no luck getting this touch pad working.
