### ISSUE TITLE
xmen6p - support for players 5 and 6

### ISSUE THREAD

**Issue by markwkidd** [libretro/mame2003-plus-libretro#245]
Right now we only provide up to four RetroPad mappings, but it would be pretty easy to add Players 5 and 6 on top of what we have -- mostly just copy and paste.

Do we actually have any games that support that many players in our gamelist?

**Comment by grant2258** [comment]
only one hard dunk 

game name=harddunk
 
http://www.gamesdatabase.org//Media/SYSTEM/Arcade/Cabinet/big/Hard_Dunk_-_1994_-_Sega.jpg

**Comment by markwkidd** [comment]
I bet there is also an audience for the 6-player x-men game. Also a potential party classic.

I just hooked up the retropad interfaces for players 5 and 6 -- as expected it was just a matter of copy pasting and making some edits. The new compiles fine and I think the change is harmless so I went ahead and committed t but DISCLAMER: I haven't tested out the P5 and P6 inputs myself.

**Comment by grant2258** [comment]
although we have this game only 4 players are hooked up in the driver 

	<game name="xmen6p" cloneof="xmen" romof="xmen">
		<description>X-Men (US 6 Players)</description>
		<driver>xmen6p</driver>
		<year>1992</year>
		<manufacturer>Konami</manufacturer>
		<rom name="065ucb04.10d" size="131072" crc="0f09b8e0" sha1="79f4d86d8ec45b39e34ddf45860bea0c74dae183" region="cpu1" offset="0"/>
		<rom name="065ucb05.10f" size="131072" crc="867becbf" sha1="3f81f4dbd289f98b78d7821a8925598c771f01ef" region="cpu1" offset="1"/>
		<rom name="xmen17g.bin" merge="xmen17g.bin" size="262144" crc="b31dc44c" sha1="4bdac05826b4d6d4fe46686ede5190e2f73eefc5" region="cpu1" offset="80000"/>
		<rom name="xmen17j.bin" merge="xmen17j.bin" size="262144" crc="13842fe6" sha1="b61f094eb94336edb8708d3437ead9b853b2d6e6" region="cpu1" offset="80001"/>
		<rom name="065-a01.6f" merge="065-a01.6f" size="131072" crc="147d3a4d" sha1="a14409fe991e803b9e7812303e3a9ebd857d8b01" region="cpu2" offset="0"/>
		<rom name="xmen1l.bin" merge="xmen1l.bin" size="1048576" crc="6b649aca" sha1="2595f314517738e8614facf578cc951a6c36a180" region="gfx1" offset="0"/>
		<rom name="xmen1h.bin" merge="xmen1h.bin" size="1048576" crc="c5dc8fc4" sha1="9887cb002c8b72be7ce933cb397f00cdc5506c8c" region="gfx1" offset="100000"/>
		<rom name="xmen12l.bin" merge="xmen12l.bin" size="1048576" crc="ea05d52f" sha1="7f2c14f907355856fb94e3a67b73aa1919776835" region="gfx2" offset="0"/>
		<rom name="xmen17l.bin" merge="xmen17l.bin" size="1048576" crc="96b91802" sha1="641943557b59b91f0edd49ec8a73cef7d9268b32" region="gfx2" offset="100000"/>
		<rom name="xmen22h.bin" merge="xmen22h.bin" size="1048576" crc="321ed07a" sha1="5b00ed676daeea974bdce6701667cfe573099dad" region="gfx2" offset="200000"/>
		<rom name="xmen22l.bin" merge="xmen22l.bin" size="1048576" crc="46da948e" sha1="168ac9178ee5bad5931557fb549e1237971d7839" region="gfx2" offset="300000"/>
		<rom name="xmenc25.bin" merge="xmenc25.bin" size="2097152" crc="5adbcee0" sha1="435feda697193bc51db80eba46be474cbbc1de4b" region="sound1" offset="0"/>
		<chip type="cpu" name="68000" clock="16000000"/>
		<chip type="cpu" soundonly="yes" name="Z80" clock="7159090"/>
		<chip type="audio" name="YM2151" clock="4000000"/>
		<chip type="audio" name="054539" clock="48000"/>
		<video screen="raster" orientation="horizontal" width="288" height="224" aspectx="4" aspecty="3" refresh="60.000000"/>
		<sound channels="2"/>
		<input players="4" control="joy8way" buttons="3" coins="4" service="yes"/>
		<driver status="preliminary" color="good" sound="good" palettesize="2048"/>
	</game>

**Comment by markwkidd** [comment]
It's never that easy! I should have known :man_facepalming:

**Comment by markwkidd** [comment]
@arcadez do you have any experience hooking up new player inputs? I don't see anything in the driver history specifically about the higher player numbers being available in later versions of MAME either

**Comment by arcadez** [comment]
Nah not really as the xbox only supported 4 inputs anyway, listen check the service mode
for the game as although it's a 6 player version it might not default to that.

**Comment by kurrono** [comment]
Hey grant can u do killer instinct custom OST for retroarch only ? I know psx classic and other mini consoles are slow to run the game..kyland explain me that...

**Comment by mahoneyt944** [comment]
@markwkidd is this still relevant or not? Trying to clear out old issues to get it back to manageable level.

**Comment by mahoneyt944** [comment]
Moved to #875
