### ISSUE TITLE
improved Wii support (including "split cores")

### ISSUE THREAD

**Issue by markwkidd** [libretro/mame2003-plus-libretro#247]
### [Bounty contributions make a difference - please donate at this link today to support this enhancement](https://www.bountysource.com/issues/59029084-improved-wii-support-including-split-cores)

Wiimpathy from gbatemp was gracious enough to send this diff patch which has some clues about two things regarding Wii (not WiiU):

1. #ifdefs in the general codebase that improve the experience for Wii users
2. Makefile changes to produce the "split cores" that are necessary for mame2003-plus to fit in the memory constraints of the original Wii

We could try to implement these. For now I wanted to make an issue so it could be tracked:

[Mame2003-plus_Wii_0.zip](https://github.com/libretro/mame2003-plus-libretro/files/2055184/Mame2003-plus_Wii_0.zip)

The discussion and the full source is here: https://gbatemp.net/threads/mame-2003-plus.499497/

**Comment by mahoneyt944** [comment]
Handling this issue in #1416
