### ISSUE TITLE
S905x TV box test m92.cpp and m107.cpp game.has choppy sound

### ISSUE THREAD

**Issue by ji125443** [libretro/mame2003-plus-libretro#262]
The simulation speed is normal, especially for Gun Force II.The roar of the waves was very rough

**Comment by grant2258** [comment]
is it a beelink or tronsmart box your using ?

**Comment by grant2258** [comment]
what fps are you getting ? are you getting in Gun Force II?

**Comment by ji125443** [comment]
Full speed 60fps, but mame2010 simulation speed and music are normal.

**Comment by ji125443** [comment]
Using the tronsmart box.

**Comment by grant2258** [comment]
yea the tempo/pitch is off i mame078 as well for Gun Force II its just the way the driver came. it is an issue

**Comment by grant2258** [comment]
looks like the games cpu should be a v33 and v35 mame is using a v33 and v30 ill need to look into the differences in a v30 and v35 and see if we can get a better clock speed without messing the emulation up

**Comment by grant2258** [comment]
to be honest i get some choppy sound on the raspberry pie now and because of slowdown. 

It runs ok on a pc the only problems is the pitch it wrong basically. If you want less chopping try putting some frameskip options on

**Comment by ji125443** [comment]
It seems that the v33 CPU series of games all have the problem of abnormal game music, but the simulation speed is normal, that is, music is abnormal.

**Comment by grant2258** [comment]
well it could be v30 v35 differences.  or sound encryption either way its the way this driver is for mame078 so someone will have to look at it all to fix it its not some thing new just is something that will need fixed at some point you can hear how slow the speech is in rtypeleo when you start the game.

**Comment by arcadez** [comment]
0.80u2: R. Belmont added channel status readback to the IREM GA-20 PCM sound, which fixes some occasional odd voice-stealing behavior I've heard playing R-Type Leo. Please enjoy R-Type Leo LOUDLY now.

**Comment by grant2258** [comment]
READ_HANDLER( IremGA20_r )
 {
-	/* Todo - Looks like there is a status bit to show whether each channel is playing */
-	return 0xff;
+	int channel;
+
+	if (!Machine->sample_rate)
+		return 0;
+
+	stream_update(IremGA20_chip.channel, 0);
+
+	channel = offset >> 4;
+
+	switch (offset & 0xf)
+	{
+		case 0xe:	// voice status.  bit 0 is 1 if active. (routine around 0xccc in rtypeleo)
+			return IremGA20_channel[channel].play ? 1 : 0;
+			break;
+
+		default:
+			logerror("GA20: read unk. register %d, channel %d\n", offset & 0xf, channel);
+			break;
+	}
+
+	return 0;
 }

you recon that would change the pitch @arcadez

**Comment by arcadez** [comment]
Im updting the soundcore just now, some changes will be needed at driver level likely, only
m92 and m107 use the IREMGA20 which will cut down on games that will needed testing
afterwards

**Comment by grant2258** [comment]
https://www.youtube.com/watch?v=m2mluCFipwM

0:50 listen the speech the pitch is well shifted on mame 078

**Comment by grant2258** [comment]
just tested the pitches are where they should be at in gun force 2 and r-typeleo job well done 👍

**Comment by arcadez** [comment]
Another happy ending :)

**Comment by grant2258** [comment]
i really should test this core on my  S912 its probably faster than my pie and i can use my pi as a tv box

**Comment by grant2258** [comment]
@KMFDManic you might be interested in these sound fixes i remember watching you video on the irem games and the imperfect sound just tagging you to keep you updated on this

**Comment by KMFDManic** [comment]
@grant2258 Thanks for the heads up.  Irem games are certainly very important to many:)  I can retest things on MAME 2003 Plus when I get a chance.

**Comment by ji125443** [comment]
It's very important to me.

**Comment by arcadez** [comment]
Sound issues with the Irem 92 and 107 games have been sorted, time to close this
