### ISSUE TITLE
player 2 problems

### ISSUE THREAD

**Issue by grant2258** [libretro/mame2003-plus-libretro#271]
have a slight problem so far in testing ive only been starting sft2 and checking the buttons. Today i tried both players.

The left right up and down is working fine for p1 but it isint for p2.

the rest of the buttons are fine 

I tried on retropie window and debian all have the same behaviour.  I also  tested on fba both joysticks are functioning.  

im going to reverse back to 

4287e81 

ill let you know if that helps

good news this everything woks at commit 4287e81.  However I cleared all the previous core options. Ill try do the same on my windows box at the latest commit.

The bug still exists in the lastest windows build with old core options deleted.

Well its seems the problem whatever is causing it is in  content-specific flags changes and not the retropad code so thats some good news at least. 

anyone that is having problems just revert to 4287e81 until its fixed

https://gist.github.com/grant2258/ba06b002a8a6b0cf5a6a847450681401

**Comment by grant2258** [comment]
ok i done a branch to  4287e81

here is the compare from our current code I can see the samples ost_samples are just missing a if condition no big deal there easy to fix. 

I however dont see anything that will effect the up down left right not working in p2 with these changes. 

Its my first night back at work unless its something to do with the dual joystick changes. Im not sure what else it would be ill try setting that to off.

**Comment by markwkidd** [comment]
Ah ok, I'm reading through github messages in chronological order. It was the Dual Joysticks core option that did this.... yet another reason to only apply that option to games that do actually have Dual Joysticks.

**Comment by grant2258** [comment]
no it worked fine before it was the contents flag that changed this

**Comment by grant2258** [comment]
https://github.com/libretro/mame2003-plus-libretro/issues/271 i closed the thread it stopped working when done the contents flag changes
