### ISSUE TITLE
Dip switches not showing in mame menu

### ISSUE THREAD

**Issue by gomisensei** [libretro/mame2003-plus-libretro#289]
build 050ba51, dip switch setting no longer appears on the mame menu, same with the key binding menu, so I can't set keys/controls for the dip switches, or manually assign buttons (such as the mame menu button, or test mode).

**Comment by gomisensei** [comment]
updated to 5aa6f12, dip switches is back, i assume the missing bindings menu is meant to be gone?  I now have no way to switch my mame menu key...

**Comment by grant2258** [comment]
you choose you controls buy going into retroarch press select + x then go to the controls menu anch choose what retropad type you want for each contoller

**Comment by gomisensei** [comment]
no, you can't set stuff like mame ui key in retroarch, so every time I press they key that i previously set, which has now become what used to be my pause key, it pops up the mame menu.  I also can't set the service mode select keys in retroarch.  SInce you mention it, I don't mind having some arbitrary retropad setup, but I why is it the ONLY method of setup we have for buttons?  It's quite unintuitive to switch around to a custom configuration.

**Comment by grant2258** [comment]
its retroarch there is keyboard retropad and simultaneous

**Comment by grant2258** [comment]
youll need to ask mark to or fr500 to explain retroarch mappings/bindings once you undertsand that you can do what you need too. It just all new once its documented hopefully it will be become clear for you.
