### ISSUE TITLE
Link: viewing libretro buildbot logs

### ISSUE THREAD

**Issue by markwkidd** [libretro/mame2003-plus-libretro#29]
Howdy @arcadez and @grant2258 you might find it useful to look in the #buildbot channel of the libretro discord chat server: https://discord.gg/E6SWGxr

That is a good way to get a quick idea of whether things are compiling equally well for all platforms.

**Comment by grant2258** [comment]
cheers mark registers an account and seen there is a problem with the android build is a hand source of information

**Comment by markwkidd** [comment]
Android compilation does not make much sense to me. I worked with some other folks to try to describe it in the libretro docs, but I don't think we ever even got them written correctly either! https://buildbot.libretro.com/.docs/compilation/android/

Now that you can see #buildbot on discord, can you see the #programming channel? This link may get you there: https://discordapp.com/channels/184109094070779904/419255960465309700

That is a channel to chat about libretro development. I regularly turn to the discord chat for help and advice

**Comment by grant2258** [comment]
Cheers Mark this will help me on me quest of learning the research a pi.
It's nice to see so much activity on the old mame cores

**Comment by markwkidd** [comment]
Closing this. The Discord link will be in the docs though!
