### ISSUE TITLE
Bubble Bobble not loading:

### ISSUE THREAD

**Issue by Loggahead** [libretro/mame2003-plus-libretro#303]
Just noticed that when I start Bubble Bobble in 2003+ it crashes back to ES and doesn't load the game.  The rom works fine in regular lr-mame2003.  I am running this on an rpi3b with retropie 4.4 and the rom is from a tested .78 set (not verified for 2003+)

This could be a rom version issue but since Bubble Bobble worked just fine under 2003, I am assuming that it hasn't been changed for some reason in 2003+?  If it has, just let me know and I'll get the correct rom version for it and will close this issue.

Just in case that's not it, thought I'd post here about it.  I did not check the log yet.

**Comment by Wilstorm** [comment]
@Loggahead - I am not sure what ROM exactly you're referring to but bubbobr1, bublbobl and bublbobr all have been updated/changed and require an update. I believe Arcadez worked his magic and implemented several changes that are much more accurate than their 2003 counterparts.

New additions exclusive to 2003+ are bublbob1 & bublboblp.

**Comment by Loggahead** [comment]
That would be my issue.  Pretty sure I'm just using bublbobl.zip and its from a verified collection of .78 roms.

**Comment by Wilstorm** [comment]
I think you're only missing one ROM and should be set. If you add this file to your archive I believe it will work with either version as long as you don't run it through a ROM management program and remove the 2003 unneeded ROMs.

```
<rom name="a78-01.17" merge="a78-01.17" size="4096" crc="b1bfb53d" sha1="31b8f31acd3aa394acd80db362774749842e1285" region="cpu4" offset="f000"/>
```

I also noticed some "strange" processing behavior with ClrMamePro and the lr-fbalpha DAT. Mainly BIOS merge information. Some games aren't being processed correctly depending on how "interpret" the DAT merge information. I wrote the ClrMamePro developer and he acknowledged it was worth a look. He said he would rethink the merge element and make it more restrictive potentially.

**Comment by Loggahead** [comment]
Roger all of that.  I will play around with it tonight.  So is the mame 2003 plus xml file here on git hub the actual DAT file I use with ClrMamePro?

**Comment by Wilstorm** [comment]
Yeah it's on the code page under metadata here

[mame2003_plus DAT](https://github.com/libretro/mame2003-plus-libretro/tree/master/metadata)

**Comment by Wilstorm** [comment]
@Loggahead - 0.78 is a good base as it's contains roughly 4720 games that are identical. There's 133 new games that are exclusive to Plus and 39 games that have been updated. Bubble Bobble happens to be one of the 39 updated games! ;) 

When I created a set I used the newest MAME (currently 0.198) as my rebuild source so I am not sure if there's an older set that will have a majority of the updates and additions or if they are scattered through out the sets. Most are official MAME ROMs and a few unofficial ROMs.

**Unofficial ROMs:**
```
Hyper Street Fighter II: The Anniversary Edition (Asia 040202) [folder: hsf2a - size: 45mb]
missing rom: hs2ax.03 [size: 524288] [CRC32: 5f3d7397] [SHA1: 96f327dd998105ad5dc46bc9d3b741805a840d68]
missing rom: hs2ax.04 [size: 524288] [CRC32: 59acf108] [SHA1: e68fe233681175b29a35badab249c2b892b23af3]
```

**Updated ROMs:**
```
alcon.zip
avengrgs.zip
bloodwar.zip
bonkadv.zip
brapboys.zip
bubbobr1.zip
bublbobl.zip
bublbobr.zip
cabal.zip
chinagat.zip
countrnb.zip
esckids.zip
fireshrk.zip
fjbuster.zip
gtmr.zip
hachamf.zip
hedpanic.zip
hydrap.zip
hydrap2.zip
jdredd.zip
jdreddb.zip
multchmp.zip
mustache.zip
nbajamex.zip
neogeo.zip
omega.zip
rockn.zip
saiyugou.zip
samesam2.zip
samesame.zip
shogwarr.zip
slapfigh.zip
tdragon.zip
titlef.zip
tmekprot.zip
vimana.zip
vimana1.zip
vimanan.zip
winspike.zip
```

**New ROMs:**
```
1943mii.zip
acpsx.zip
airattck.zip
airattcka.zip
arescue.zip
asurabus.zip
avengrgsj.zip
backfire.zip
baryon.zip
bbbuster.zip
boogwing.zip
boogwinga.zip
brapboysj.zip
bsharkjjs.zip
bublbob1.zip
bublboblp.zip
cabala.zip
cabalus.zip
cabalus2.zip
candance.zip
ccastlej.zip
chainrec.zip
charlien.zip
countrb2.zip
crswd2bl.zip
cutefght.zip
darkmist.zip
dblewing.zip
ddream95.zip
deluxe5.zip
denjinmk.zip
dietgo.zip
dietgoe.zip
dietgoj.zip
dietgou.zip
dkongx.zip
dogosokj.zip
downtowj.zip
dreamwld.zip
drgnwrld.zip
dynagear.zip
esckidsj.zip
fixeighb.zip
gaialast.zip
ghostlop.zip
glasskr.zip
gnbarich.zip
gunmast.zip
hachamfb.zip
hcrash.zip
hcrashc.zip
hedpanicf.zip
hedpanico.zip
hookj.zip
hoops96.zip
hsf2a.zip
hvysmsh.zip
hvysmsha.zip
hvysmshj.zip
ikari3nr.zip
inyourfa.zip
ironclad.zip
joemacr.zip
joemacra.zip
kbash2.zip
killbld.zip
kof2001.zip
kof2002.zip
lasthope.zip
lethalen.zip
magdrop.zip
magdropp.zip
matrim.zip
mchampdx.zip
mchampdxa.zip
midresbj.zip
msgogo.zip
mslug4.zip
mslug5.zip
multchmpk.zip
mwarr.zip
nslasherj.zip
nslashers.zip
olds.zip
olds103t.zip
osman.zip
packbang.zip
pktgaldj.zip
pktgaldx.zip
plegends.zip
pnyaa.zip
progear.zip
progearj.zip
pturn.zip
puzlstar.zip
pzloop2j.zip
ragtime.zip
ragtimea.zip
riot.zip
rockn2.zip
rockn3.zip
rockn4.zip
rockna.zip
rolcrush.zip
rotd.zip
sabotnba.zip
samsh5sp.zip
samsho5.zip
sbishi.zip
sbishik.zip
sengoku3.zip
skullfng.zip
skullfngj.zip
sonicbom.zip
suprridr.zip
svcboot.zip
swatpolc.zip
tangtang.zip
teetert.zip
tgm2.zip
tgm2p.zip
thoop.zip
vasara2.zip
vasara2a.zip
vbowl.zip
vbowlj.zip
vmetal.zip
wbmlvc.zip
wcvol95.zip
wcvol95x.zip
wingforc.zip
zintrckb.zip
zupapa.zip
```
