### ISSUE TITLE
Certain games run with awful electronic sound on MAME 2003.

### ISSUE THREAD

**Issue by WandeingLagomorph793** [libretro/mame2003-plus-libretro#305]
When I load certain games in the mame2003 core in RetroArch, They run but have this horrible electrical noise when I do, this doesn't happen on every game but It does with most of them.

I don't think I can send the rom files but the games, with the file names are

Sailor Moon ( sailormn)

Moon Patrol (mpatrol)

The New Ghostbusters II (ghostb)

and Narc (narc)

This happens on other games like Burger Time, Heavy Barrel and the Double Dragon games, but my workaround for those is running them on the FBA cores, they run there without issue, but the four mentioned games won't run there.

My setup is Retroarch 32bit 1.7.3

MAME2003 0.78, with the roms gotten from a corresponding romset

Surface Pro 3

**Comment by grant2258** [comment]
try this https://retropie.org.uk/forum/topic/17828/rampage-sound-issue-retropie-4-4/3  if it doesnt help let us know. 

Remember to reboot after you change it

**Comment by grant2258** [comment]
i tried all of these games none had problems im assuming your running windows unless someone else sees this bug I would try updating your soundcard driver

**Comment by Wilstorm** [comment]
@grant2258 @WandeingLagomorph793 - I tested the listed games on a Raspberry Pi 3 running RetroPie 4.3 and I had no sound issues with any of the games.

**Comment by markwkidd** [comment]
I'm going to close this issue. OP. All signs point to this being an issue with your soundcard driver, windows configuration, or RetroArch rather than a bug with this emulator core. I hope you are able to work it out!
