### ISSUE TITLE
[Android 7.0] MAME2003 fails to start some roms correctly

### ISSUE THREAD

**Issue by SapphireTactician** [libretro/mame2003-plus-libretro#33]
Android user here. :) At the advice of @markwkidd I was instructed to open an issue that I opened at `mame2003-libretro` here as well. I was able to get logs but sadly they seem perfectly normal to me and @markwkidd . I can't program or compile but as an active Android user, I'm more than willing to do any testing that needs to be done so long as someone is willing to walk me through whatever needs to be done.

### Description:

I tested several roms, mostly Taito games, from the MAME 2003 non-merged reference set, on the Android version of RetroArch using the MAME2003 core. With the exception of `bubsympu` and `bublbob2`, these all get stuck on a blank screen, meanwhile the aforementioned two get stuck on a screen saying "Service Switch Error" 

Upon further requested testing `splatter` crashes RetroArch before it can successfully reach the title screen, and `altbeast` doesn't have sound.

### Specs:

**OS:** Android 7.0 Nougat (_32-bit_)
**RetroArch Version:** 1.7.1
**MAME 2003 Core Commit:** a4f22ed
**Device:** Motorola Moto G5 Plus (_32GB Model_)
**CPU:** Qualcomm® Snapdragon™ 625 (_64-bit, 2 GHz Octo-core_)
**GPU:** Adreno 506 (_650 MHz_)
**RAM:** 2 GB

It's important to note that the affected roms load and play perfectly fine on both Lakka for Raspberry Pi 3B and RetroArch for Debian when using the MAME 2003 core.

*****

### Expected Behavior:

The roms should load and play just fine.

*****

### Actual Behavior:

The roms get stuck on a blank screen or "Service Switch Error" message. Upon further requested testing, Splatterhouse (*rom name `splatter`*) crashes RA, and Altered Beast (*rom name `altbeast`*) has no sound.

*****

### Steps to Reproduce:

* Launch RetroArch for Android
* Load Core
    * Download Core
        * Arcade (MAME 2003)
* Download any of the following non-merged roms from the MAME2003 Reference Set:
    * `bubsympu`
    * `bublbob2`
    * `bublbobr`
    * `sailormn`
    * `zookeep`
* Load Content
* Select one of the aforementioned roms
* Select the `Arcade (MAME 2003)` core

*****

### Example:

Video of problem, recorded with Google Play Games screen recorder: https://streamable.com/u5e1j

*****

### Logs:

When using an affected rom: `sailormn` [RA_Android7_MAME2003-grep.txt](https://github.com/arcadez/mame2003-plus-libretro/files/1864203/RA_Android7_MAME2003-grep.txt)

**Comment by markwkidd** [comment]
Thank you for the AWESOME bug report.

There is a theory this relates to unaligned memory access bugs but I wouldn't know!

**Comment by grant2258** [comment]
whats the service key binded to on android try pressing the service key then reset

**Comment by SapphireTactician** [comment]
It's binded to keyboard inputs. I tried remapping them to retropad buttons and resetting as advised, but no luck. Issue persists.

**Comment by grant2258** [comment]
what confusing is there is no bublbobr rom in mame078/2003

**Comment by SapphireTactician** [comment]
It's right here in the reference set I'm looking at, I'd link to it but rules are we can't. :-/

**Comment by grant2258** [comment]
sorry i meant bulbob2

**Comment by SapphireTactician** [comment]
Oh, crap, I must've made a typo, meant `bublbob2`. Good catch. Will fix original post.

**Comment by grant2258** [comment]
this is just for me ignore it for now its so i can look into it when i get time
bubsympu  src/drivers/taito_f3.c
bublbob2 src/drivers/taito_f3.c
bublbobr src/drivers/bublbobl.c
sailormn src/drivers/cave.c
zookeep  src/drivers/qix.c

**Comment by grant2258** [comment]
is there anything in the logs for the other games

**Comment by grant2258** [comment]
RetroArch: Loading state: "/storage/emulated/0/RetroArch/states/MAME 2003/sailormn.state.auto".
03-30 12:37:06.472  7209  7225 I RetroArch: State size: 882501 bytes.
03-30 12:37:06.472  7209  7225 I RetroArch: Saving state: "RAM".
03-30 12:37:06.472  7209  7225 I RetroArch: State size: 881401 bytes.
03-30 12:37:06.476  7209  7225 E RetroArch: Failed to load state from "/storage/emulated/0/RetroArch/states/MAME 2003/sailormn.state.auto".
03-30 12:37:06.483  7209  7225 I RetroArch: [MAME 2003] Searching for sailormn hiscore memory map in internal .dat.

there might be an issue with  the space  in MAME 2003 

change it to MAME2003 OR MAME_2003 thats just a guess from the logs though

**Comment by grant2258** [comment]
will need a full log of failing game to get somewhere to start

**Comment by SapphireTactician** [comment]
The rom folder doesn't contain any spaces or other potentially invalid characters. The space is generated by RetroArch in the `/states` folder. Renaming it simply causes RA to spawn a new folder with the same possibly offending name.

I'll get you a full log of the games I've tried and experienced these issues with. Unfortunately, I have to leave for a bit but I'll get on it as soon as I return home.

**Comment by SapphireTactician** [comment]
>are these games working ok on linux/windows x64 mark ?

Yes, they play perfectly fine on my Debian x64 build of RA, and the RPi 3b build of Lakka.

**Comment by grant2258** [comment]
Disable save states and try

**Comment by arcadez** [comment]
I haven't read every post which means it's never a good idea to chime in :)
but I know alotta those Taito F3 games will boot with a service mode error
until you actually active the service mode then save and exit.

Similar to Run And Gun this will create an eerom save and the games will boot as
normal everytime after.

**Comment by SapphireTactician** [comment]
Disabled automatic saving and loading of states. Not sure if it's even possible to disable the save state feature entirely.

This log contains all the mentioned games. I used Close Content first when switching between games.

[RA_Android7_MAME2003-grep_20180330-1704.txt](https://github.com/arcadez/mame2003-plus-libretro/files/1864790/RA_Android7_MAME2003-grep_20180330-1704.txt)

**Comment by SapphireTactician** [comment]
At a closer look, it seems that at least the affected Taito games seem to be constantly restarting on their own as `bublbob2` / `bubsympu` flashes between "Wait A Moment..." and "Service Switch Error"

**Comment by arcadez** [comment]
When games constantly reset like your describing above it might be a platform specific
problem with some of the CPU IRQ commands getting lost in the shuffle or the CPU is
plain just not perforoming correctly a compile or build issue maybe.??

Taito F3 games all use the M68EC020 CPU core for android devs that will likely be a good
place to start when trying to trackdown the cause.

**Comment by grant2258** [comment]
How do you get the latest compiled android version ill have a look

**Comment by grant2258** [comment]
i think the issue is the the original save state messed up your nvram for this game. Try press service button keep it in and press reset. If that doesnt work delete the file from the nvram folder and try again

**Comment by SapphireTactician** [comment]
I disabled all options in the `Saving` settings menu though and deleted all save states and save files from the `states` and `saves` folders respectively. Pressing and holding the service button while reseting didn't work. Deleting the `nvram` folder didn't work either.

**Comment by grant2258** [comment]
You need to clear the nvram folder as well m8

**Comment by grant2258** [comment]
im going to look into compiling retroarch  myself and start using a x64 env to see whats going on with the namcos1 driver. The thing is if it is casting it should be effecting all 64 bit environments

**Comment by SapphireTactician** [comment]
As per your instructions I cleared the NVRam folder this time instead of deleting it altogether, still no luck.

I ran the program listed in the article you sent me. The Android version is 32-bit but the CPU is 64-bit

**Comment by grant2258** [comment]
Very strange this one as it works on other 64bit envs

**Comment by SapphireTactician** [comment]
Maybe because the OS is only 32-bit?

**Comment by grant2258** [comment]
to be honest i dont know much about compiling for androids apart from building new kernels

**Comment by grant2258** [comment]
do me a favour run splatter.zip and tell me if your title screen is messed up where it says splatter house

**Comment by SapphireTactician** [comment]
Can't make it to title screen, RetroArch crashes during what I'm guessing is the rom check (*was cycle through several colors at full screen*)

**Comment by grant2258** [comment]
I. Going to look at this particular driver when i get time. If i get it
fixed ill need you to test it if thats ok. I think mark is right about the
alignment issue somewhere

**Comment by SapphireTactician** [comment]
I'll be more than happy to test anything you have for me to try. Thanks.

**Comment by grant2258** [comment]
we had some issues on 64 bit with altered beast which i fixed with the m68k core again it was casting in this one. can you start altbeast and make sure the characters have heads on them when the game starts and make sure all is well on the android side for that fix

**Comment by SapphireTactician** [comment]
Game starts, heads are visible, but there's no sound.

**Comment by grant2258** [comment]
What commit are you on for mame2003

**Comment by SapphireTactician** [comment]
Where would I find that information? The title bar for Core Information says `MAME 2003 0.78 a4f22ed`

**Comment by grant2258** [comment]
that is the info edited the post above to include romnames

**Comment by SapphireTactician** [comment]
Only tested `altbeast` sound did not work on it. Just tested `altbeas2` , again everything is fine except for sound not working.

>What commit are you on for mame2003 it should tell you when you load the core after mame2003

Do you mean this: `a4f22ed` ?

**Comment by grant2258** [comment]
yes that os the commit your at i. There is something going on with the android build the sound not working in altbeast isint normal

**Comment by SapphireTactician** [comment]
Added the requested information to the original post.

**Comment by markwkidd** [comment]
It does seem there is information in the docs about how to set up a debugger for RetroArch in Android but I don't know anything about this process or whether it will be helpful.

Therefore I don't want to ask you to put a lot of time into getting a debugger set up, but maybe this is not a challenge for you: https://docs.libretro.com/tech/debugging/

**Comment by SapphireTactician** [comment]
@markwkidd Looks like it wants me to install the Android SDK and NDK, and then compile it myself. I attempted to do that but then hit a wall when it came to installing the SDK (*command line only, don't want to bog this old PC down with the full Android Studio GUI since I'd prefer to simply compile via command line*) and NDK because it's just a `.zip` file with no instructions of where it should be on a Linux file system.

If someone is able to build a debug build of RA and the MAME2003 core, I'll install it and use it. If not, then I need a walkthrough of how to do it myself that handholds me through the entire process of getting the environment set up.

**Comment by grant2258** [comment]
@markwkidd 

looks like ive found a big issue mark might explain the mysteries. I need to read up on makefiles they are a mystical force to reckoned with for me at the moment .

**Comment by markwkidd** [comment]
Intriguing!

I've started learning about Makefiles over the last few months via my work
with libretro but they still seem like black magic to me.

For example, the BUILD_BIN2C flag and logic that I added to the mame2003
Makefile are not very well done because I'm still learning the syntax. Let
me know if I can help or if it's something we can ask for help on from more
experienced libretro/Makefile devs.

**Comment by SapphireTactician** [comment]
As of commit 9d82c48 / PR 356 over at MAME2003-libretro

The previously mentioned games all work:

- [x] `splatter` no longer crashes RA and now works
- [x] `altbeast` has sound working again
- [x] `bublbobr` now works
- [x] `bublbob2`now works
- [x] `bubsympu` now works
- [x] `sailormn` now works
- [x] `zookeep` now works

In addition, I tested the following games I have:

- [x] `athena` (*Athena*) has working sound again
- [ ] `bakubaku` (*Baku Baku Animal*) Error: Failed to Load Content (*occurs even on Debian 9 64-bit, so at least it's not an Android only issue. I might be missing a needed bios*)
- [x] `baraduke` (*Baraduke*) works fine
- [ ] `bubblem` (*Bubble Memories*) Produces an error that says `PUSH TEST SWITCH BACKUP DATA FAILED`. Works fine after pressing the Service Button and performing a Factory Reset
- [x] `circusc` (*Circus Charlie w/ Level Select*) has working sound again
- [x]  `circusc2`(*Circus Charlie*) has working sound again
- [x] `digdug` (*DigDug*) works fine
- [x] `digdug2` (*DigDug 2*) works fine
- [x] `docastl2` (*Mr. Do's Castle*) works fine
- [x] `docastle` (*Mr. Do's Castle*) works fine
- [x] `dorunru2` (*Do! Run Run*) works fine
- [x] `dorunrun` (*Do! Run Run*) works fine
- [x] `dowild` (*Mr. Do's Wild Ride*) works fine
- [x] `drgnbstr` (*Dragon Buster*) works fine
- [ ] `galaga88` (*Galaga '88*) Player and enemy sprites are missing on Android only
- [x] `mappy` (*Mappy*)works fine
- [x] `mario` (*Mario Bros.*) works fine
- [x] `mpatrol` (*Moon Patrol*) works fine
- [x] `mrdo` (*Mr. Do!*) works fine
- [ ] `neobombe` (*Neo Bomberman*) Error: Failed to Load Content (*occurs even on Debian 9 64-bit, so at least it's not an Android only issue. I tried placing the required bios in both the system directory and the roms directory. No luck*)
- [x] `nrallyx` (*New Rally X*) works fine
- [x] `ordyne` (*Ordyne*) works fine
- [x] `pacland` (*Pac-Land*) works fine
- [x] `pengo` (*Pengo*) starts at Game Over screen instead of title screen but otherwise works fine
- [x] `phozon` (*Phozon*) works fine
- [x] `rainbow` (*Rainbow Islands*) works fine
- [x] `rthunder` (*Rolling Thunder*) works fine
- [x] `suprmrio` (*VS. Super Mario Bros.*) Bad sound emulation on ARM processors but otherwise works fine
- [x] `tetrisp2` (*Tetris Plus 2*) works fine
- [x] `tnzs` (*The New Zealand Story*) works fine
- [x] `todruaga` (*The Tower of Druaga*) works fine
- [x] `valkyrie` (*Valkyrie no Densetsu*) works fine

**Comment by grant2258** [comment]
i have pushed that commit here as well need to make sure its not doing a global none optimize though. Ill compile on the pie a check how neogeo games are running

**Comment by grant2258** [comment]
this is just notes games that use video_start_generic() 

Search "video_start_generic()" (14 hits in 11 files)
  C:\Users\grant\Downloads\mame078s\src\vidhrdw\bosco.c (1 hit)
	Line 136: 	if (video_start_generic() != 0)
  C:\Users\grant\Downloads\mame078s\src\vidhrdw\btime.c (1 hit)
	Line 139:     if (video_start_generic() != 0)
  C:\Users\grant\Downloads\mame078s\src\vidhrdw\digdug.c (1 hit)
	Line 85: 	if (video_start_generic() != 0)
  C:\Users\grant\Downloads\mame078s\src\vidhrdw\galaga.c (1 hit)
	Line 131: 	if (video_start_generic() != 0)
  C:\Users\grant\Downloads\mame078s\src\vidhrdw\geebee.c (4 hits)
	Line 63: 	if( video_start_generic() )
	Line 74: 	if( video_start_generic() )
	Line 84: 	if( video_start_generic() )
	Line 94: 	if( video_start_generic() )
  C:\Users\grant\Downloads\mame078s\src\vidhrdw\generic.c (1 hit)
	Line 64: logerror("Error: video_start_generic() called but videoram_size not initialized\n");
  C:\Users\grant\Downloads\mame078s\src\vidhrdw\gunsmoke.c (1 hit)
	Line 101: 	if (video_start_generic() == 1)
  C:\Users\grant\Downloads\mame078s\src\vidhrdw\lazercmd.c (1 hit)
	Line 84: 	if( video_start_generic() )
  C:\Users\grant\Downloads\mame078s\src\vidhrdw\mpatrol.c (1 hit)
	Line 205: 	if (video_start_generic() != 0)
  C:\Users\grant\Downloads\mame078s\src\vidhrdw\rallyx.c (1 hit)
	Line 159: 	if (video_start_generic() != 0)
  C:\Users\grant\Downloads\mame078s\src\vidhrdw\taitosj.c (1 hit)
	Line 201: 	if (video_start_generic() != 0)

**Comment by markwkidd** [comment]
@SapphireTactician maybe grant has a different idea but it sounds like the `galaga88` bug should have its own issue posted.

Thanks again for your comprehensive report.

`bubblem`: I have added an nvram patch file that can be copied to the users device to bypass the factory reset process. That is the only other thing that can be done for that other than the user pressing the service button and going through the reset themselves.

Regarding the other titles on your list, no BIOS files should be needed with mame2003 or mame2003-plus **if** you are either using the MAME 2003 Reference Set v3 or if you have processed your collection in ClrMamePro as `Non-Merged` and with `Split BIOS Sets` **disabled** in ClrMamePro's "Advanced" settings. 

Does your log say anything useful when you try to start `neobombe` and `bakubaku`?

**Comment by SapphireTactician** [comment]
@markwkidd Sorry for taking so long to get back to you. How does the patch work? Is it automated?

>Does your log say anything useful when you try to start `neobombe` and `bakubaku`?

Sadly, I don't see anything out of the ordinary, but you're more than welcome to take a look for yourself in case I missed something.

[RA_Android7_MAME2003-grep_20180418-1240.txt](https://github.com/libretro/mame2003-plus-libretro/files/1925522/RA_Android7_MAME2003-grep_20180418-1240.txt)

>it sounds like the `galaga88` bug should have its own issue posted.

Will do

**Comment by grant2258** [comment]
i think the lastes round of bug fixes you done will fix any issues we had mark

**Comment by markwkidd** [comment]
@SapphireTactician yeah there is nothing in those logs. Silent failure.

Pardon me for asking in case it's been asked before but are you starting retroarch with the `--verbose` flag when you get those logs?

**Comment by SapphireTactician** [comment]
@markwkidd No, was never instructed to. Also not sure how to launch applications directly through ADB, only that I should use `logcat` and `grep` when viewing and copying the terminal output. I tried again after changing `logcat` to verbose mode with the `*:V` option but I observed no difference in the output, so I'm assuming that RA itself has a verbose mode, but idk how to access that via Android.

**Comment by markwkidd** [comment]
I'm not sure it would reveal anything more, so I don't advocate putting too much effort into figure out verbose mode yet. There's been plenty to learn from your reports so far, thank you.

**Comment by SapphireTactician** [comment]
@markwkidd You mentioning verbose mode gave me an idea. Since `bakubaku` and `neobombe` also failed on my Linux PC, and not just Android, I ran verbose mode on Linux to see if I could gain additional insight... apparently my zips for two were somehow incomplete and missing files, perhaps they got corrupted somehow. Replaced the files and tried again, both games work (*although `bakubaku` has a warning about inaccurate video emulation and no sound, meanwhile `neobombe` mode select menu is I think in Spanish with no way to change the language. Should I make the latter a separate issue?*)

![screenshot_20180418-235717](https://user-images.githubusercontent.com/24427487/38971341-ba0acfda-4368-11e8-9b38-1da3d682cf38.png)

**Comment by grant2258** [comment]
we should be giving verbose information when roms are missing though

**Comment by SapphireTactician** [comment]
Closing as `Fixed` as per @markwkidd . Thank you @grant2258 , @markwkidd , and @arcadez plus anyone else who may have been involved that I haven't spoken to for all your hard work. Can finally enjoy these gems on my phone.

@markwkidd I'll open the language issue with Neo Bomberman as a separate issue as advised.

**Comment by markwkidd** [comment]
@grant2258 I don't know how to get verbose logs in android but I'm sure there is some way.

I literally wrote the logging docs at https://buildbot.libretro.com/.docs/guides/generating-retroarch-logs/#generating-logs-in-android (or a lot of that doc) but I had to refer to other sources on Android since I have never used RetroArch that way. If we find out let's add that info to the retroarch docs though

**Comment by SapphireTactician** [comment]
@markwkidd May I suggest building a separate .apk that has the verbose option enabled by default? If it doesn't impact performance, maybe it should be the default in general?

**Comment by markwkidd** [comment]
@SapphireTactician as someone who personally doesn't use Android but wants
to support it, that sounds great. The buildbot is already costing something
like $100-$150 a month to operate now from my understanding so it may not
be practical.

That being said, I hate to redirect you through the github maze, but adding
"Verbose Builds" is an issue for the
http://github.com/libretro/libretro-super repository. If you want to tag me
I'd follow you over there. I contribute to that repo sometimes but I have
little influence over how the buildbot is allocated though!
