### ISSUE TITLE
Storm Blade And Ultra X Weapons

### ISSUE THREAD

**Issue by arcadez** [libretro/mame2003-plus-libretro#337]
If you play either game you'll see how messed up they are graphically in this core, of the two Storm Blade fares the worst as apart from corruption down the left hand side of the screen on levels 3 and 6 "this is present all through Ultra X Weapons" we also have to contend with the lack of proper shadow tile support which totally breaks level 2.

So since Storm Blade is a great game i plan to backport some changes into the SSV driver and video files later today which will sort all of the above, the code is fully tested however i never know how it will perform on the libretro side so we'll need to keep an eye out for game breakage although i do feel
this should go pretty smoothly.

**Comment by Wilstorm** [comment]
Nice! Scrolling shooters are a win-win! :)

**Comment by arcadez** [comment]
Ok the code is ready i'll add it shortly, alotta tat in the driver but some diamonds in the rough
that would be worth testing afterwards to make sure they are still good on the libretro side.....

Change Air Blade
Dyna Gear
Driftout 94
Storm Blade
Twin Eagle II
Vasara
Vasara 2
Ultra X Weapons

**Comment by arcadez** [comment]
Please test the above when you get a chance and lemmie know if you bump into any problems
with regards to Ultra X Weapons i know it's playable in MAME84 as for 78 due to these WIP
comments im not sure.......

0.74u2: Olivier Galibert fixed some V60 floating point operations and made core exit on unhandled opcodes, note UltraX doesn't work again.
0.74: Workaround for a V60 crash causing Ultra X not to run on some systems [Tomasz Slanina].
0.73: Tomasz Slanina added 'Ultra X Weapons / Ultra Keibitai' (Banpresto + Tsuburaya Prod. 1995). Some gfx offset problems / alignment (sprite handle can move?).
0.68: Added (Testdriver) Ultra X Weapons / Ultra Keibitai.
29th August 2003: Tomasz Slanina fixed the interrupts and register layout in the V60 CPU core, making Ultra X Weapons run (with graphics glitches).

**Comment by Wilstorm** [comment]
@arcadez @grant2258 - Here's a list of the ROMs I tested below. Just let me know if any are incorrect or I missed any for the changes implemented. All of them launched and played fine. I don't know some of the Japan games intimately enough to know if minor things are incorrect or my memory isn't quite as good as it once was. I forgot about Drift Out '94 which was quite fun to play again! ;)

A few throw up known issue warnings about cocktail mode. Storm Blade starts upside down but the Dip Switch Settings fix the issue and stores the change in the .cfg file and _not_ the .nvram file.

```
cairblad.zip
drifto94.zip
dynagear.zip
stmblade.zip
twineag2.zip
ultrax.zip
vasara.zip
vasara2.zip
vasara2a.zip
```

**Comment by arcadez** [comment]
Thanks for testing i guess we could make Storm Blade flip the screen by default via the dip
setup in the ssv.c driver, and that would save folks having to do themselfs.

**Comment by Wilstorm** [comment]
@arcadez - Thanks for the new games.That would be great if it's easy. If they are upside down I usually make a .cfg or an .nvram file if there's no bootstrap/trouble booting and make a backup for reinstalls. I have about 15 or 20 .cfg files and half dozen .nvram files. Off topic but two games that don't well with the default .cfg for joysticks are Smash T.V. and Total Carnage. The up, down, left and right don't match up at all for firing but I suppose there's plenty of examples that don't work well at defaults but that's always been that way with MAME.

**Comment by SaucySarah** [comment]
Hi, I just tried the games listed above on the Android build (latest commit https://github.com/libretro/mame2003-plus-libretro/commit/8a38d02361d1282fae84177a284e7e2ab2b6de86).

 `drifto94` has weird sound.
`stmblade` still started upside down and also has weird sound.

Is this supposed to be the current state of these because @Wilstorm didn't mention anything like this ? I don't mind, I just wondered if this happens for everyone else.

**Comment by Wilstorm** [comment]
@SaucySarah - Long story short I do apologize but half my testing is unfortunately with no audio (based off my location at the time). If I test anything in the future with no audio I will make note of it or make sure I have audio for testing if it's audio related, such as the OST's which well you need audio to test! ;)

I do definitely run each game including clones I may identify (listed above), insert credits and play for a few minutes. I did note Storm Blade starts inverted but easily fixed through dip switch settings. Arcadez discussed potentially modifying the ssv.c driver to set it as default.

**Comment by SaucySarah** [comment]
@Wilstorm Yeah, @arcadez latest commit was supposed to correct Storm Blade's upside down screen but it still appeared upside down for me (I corrected it in the dipswitchs like you say). Just wondered if it also happened to anyone else (with the latest commit) and the weird audio on said games. I am using the Android version so if anyone can confirm if any of this Doesn't happen on the Raspberry Pi version.

**Comment by arcadez** [comment]
If you had booted Storm Blade before the commit you'd need to delete your cfg save as it would
store the previous dip settings, as for weird sound it's been reported before for other games
in this driver however they are fine for us on the ole xbox.

It might be a sound issue on the RA side or maybe the sound core these games use might have
had some fixes in later MAME builds i'll check it out sometime.

**Comment by Wilstorm** [comment]
@arcadez @SaucySarah - Let me test this tonight on the Pi at home and I'll let you know in the morning if not later tonight on the audio.

That's interesting...so...hmmm...if dip switch settings flipped the screen, an update flipped the screen do old dip switch settings flip it back upside down! ;)

**Comment by Wilstorm** [comment]
@arcadez @SaucySarah - I did some testing last night and I agree the audio is a bit rough on a few games.

I found Driftout '94 to the the worse for me. I drones on like an alarm clock type sound over and over overshadowing the gameplay audio.

Storm Blade most of the music is a bit rough but ok except for those high pitched notes that play over and over. You'll know what I mean when you listen to it.

Ultra X Weapons has a really rough muddy sound, almost like really bad distortion.

Twin Eagle II was the best for me there's some definite background "static noise" but nothing really flagged as annoying to me.

I know it's subjective so I decided to record them and upload [samples for each game](https://ufile.io/svryv)  (from 10 up to around 20 seconds) that way you can listen to them for yourself. The total zip is only about 2MB. You might need to turn up your volume to hear the finer details of the audio. In listening to the audio only for a few seconds it doesn't sound as bad as when you're playing them for several minutes. Then they can get a bit annoying but you can't deny they graphics are really nice, the games run smooth and look great!

**Comment by SaucySarah** [comment]
@Wilstorm Thanks for confirming what I reported. So it's not an Android specific bug, it's probably a RetroArch problem because Arcadez said it works fine on the XBOX.

**Comment by nemo93** [comment]
I do confirm driftout 94 is working smooth with .139 on the pi (using mame-2010). I didn't test much long but the sound issue during name selection etc is not there with this version.

**Comment by grant2258** [comment]
@arcadez my theory about the bad sound is it could be something to do with the interrupts. RA needs the audio and video to be in complete sync. It may be more forgiving in a sound buffer scenario on the timing.

the code im referring to is here

https://github.com/libretro/mame2003-plus-libretro/blob/3adbd2e0cde31442d7f559ca876d352fa59d2da6/src/vidhrdw/ssv_vidhrdw.c#L352

**Comment by grant2258** [comment]
ok i managed to track down the problem i put a pull req to fix the sound problem in this core ill fix it in mame2003 as well since its there as well.

once this is pulled https://github.com/libretro/mame2003-plus-libretro/pull/372 please test again thanks

**Comment by arcadez** [comment]
Nice job pinning down the cause!!

**Comment by Wilstorm** [comment]
Nice Grant! Have all these games been added to 2003 also or what games are corrected in the 2003 pull request? Also the clip link above is not working.

**Comment by grant2258** [comment]
I reset the repository when it was fixed thats why the clips gone sorry about that. The only thing changed in mame2003 is the sound bug is fixed no driver updates mame2003 is static we cant change roms ect. just means the sound will work in driftout 94 in mame2003.

**Comment by Wilstorm** [comment]
Ok, thanks for clarifying and thanks for the fixes, Driftout '94 is a great game! ;)

**Comment by grant2258** [comment]
it fixes all the ssv games in this thread basically not sure what one work in mame2003 and what ones dont

**Comment by grant2258** [comment]
*ones

**Comment by Wilstorm** [comment]
I haven't tested these but made a list of Plus exclusive and Plus/2003 (both).

**Plus Exclusive:**
```
dynagear "Dyna Gears"
gdfs "Banpresto", "Mobil Suit Gundam Final Shooting"
hypreact "Mahjong Hyper Reaction (Japan)"
vasara2 "Vasara 2 (set 1)"
vasara2a "Vasara 2 (set 2)"
```

**Plus and 2003:**
```
cairblad "Change Air Blade (Japan)"
drifto94 "Drift Out '94 - The Hard Order (Japan)"
eaglshot "Eagle Shot Golf"
eaglshta "Eagle Shot Golf (alt)"
hypreac2 "Mahjong Hyper Reaction 2 (Japan)"
janjans1 "Lovely Pop Mahjong Jan Jan Shimasyo (Japan)"
keithlcy "Dramatic Adventure Quiz Keith and Lucy (Japan)"
koikois2 "Koi Koi Shimasyo 2 - Super Real Hanafuda (Japan)
meosism "Meosis Magic (Japan)"
mslider "Visco / Datt Japan"
ryorioh "Gourmet Battle Quiz Ryohrioh CooKing (Japan)"
srmp4 "Super Real Mahjong PIV (Japan)"
srmp4o "Super Real Mahjong PIV (Japan, older set)"
srmp7 "Super Real Mahjong P7 (Japan)"
stmblade "Storm Blade (US)"
survarts "Survival Arts (USA)"
sxyreact "Pachinko Sexy Reaction (Japan)"
twineag2 "Twin Eagle II - The Rescue Mission"
ultrax "Ultra X Weapons - Ultra Keibitai"
vasara "Vasara"
```

**Comment by grant2258** [comment]
These drives are working good feel free to close the sound problems are fixed too on the libretro port
