### ISSUE TITLE
Possible DAT issue

### ISSUE THREAD

**Issue by Wilstorm** [libretro/mame2003-plus-libretro#338]
I rebuilt both MAME sets after updating the DATs last night. Everything looks good but one thing kind of threw up a red flag. Here's the list of ROMs that are only in 2003.

```
cabal2
chindrag
fghthsta
fghthstw
urashima
```

The two that seem suspect are ```fghthsta``` and ```fghthstw```. I believe they are both clones which struck me as odd to partially remove clones and leave others including the parent. ```fghthist``` seems to be the US version in one and the World version in the other. The Alternate hardware ROM versions are different by an i in hist. 

What seems to be missing is the regular US version from Plus and also they seem to be inconsistent in the parent ROM and clones. The US version is the parent in 2003 and the World version is a clone but in Plus the World version is the parent but has no US version. The Alternate hardware version is consistent in both versions but are different ROM names. The partial header DAT info is below to illustrate.

I think ```cabal2``` and ```urashima``` have been 2003 exclusive for a while but I am not sure about ```chindrag```.

**2003 DAT:**
```
<game name="fghthist"> <description>Fighter's History (US)</description>
<game name="fghthsta" cloneof="fghthist" romof="fghthist"> <description>Fighter's History (US Alternate Hardware)</description>
<game name="fghthstw" cloneof="fghthist" romof="fghthist"> <description>Fighter's History (World)</description>
```
**Plus DAT:**
```
<game name="fghthist"> <description>Fighters History (World ver 43-07)</description>
<game name="fghthista" cloneof="fghthist" romof="fghthist"> <description>Fighters History (US ver 42-05, alternate hardware)</description>
```

**Comment by grant2258** [comment]
Arcadez updated that driver it now has 4 roms

<game name="fghthist">
		<description>Fighters History (World ver 43-07)</description>
		<driver>fghthist</driver>
		<year>1993</year>
		<manufacturer>Data East Corporation</manufacturer>
		<rom name="kx00-unknown.bin" size="524288" crc="fe5eaba1" sha1="c8a3784af487a1bbd2150abf4b1c8f3ad33da8a4" region="cpu1" offset="0"/>
		<rom name="kx01-unknown.bin" size="524288" crc="3fb8d738" sha1="2fca7a3ea483f01c97fb28a0adfa6d7980d8236c" region="cpu1" offset="2"/>
		<rom name="kz02.18k" size="65536" crc="5fd2309c" sha1="2fb7af54d5cd9bf7dd6fb4f6b82aa52b03294f1f" region="cpu2" offset="0"/>
		<rom name="mbf00-8.8a" size="1048576" crc="d3e9b580" sha1="fc4676e0ecc6c32441ff66fa1f990cc3158237db" region="gfx1" offset="0"/>
		<rom name="mbf01-8.9a" size="1048576" crc="0c6ed2eb" sha1="8e37ef4b1f0b6d3370a08758bfd602cb5f221282" region="gfx2" offset="0"/>
		<rom name="mbf02-16.16d" size="2097152" crc="c19c5953" sha1="e6ed26f932c6c86bbd1fc4c000aa2f510c268009" region="gfx3" offset="1"/>
		<rom name="mbf04-16.18d" size="2097152" crc="f6a23fd7" sha1="74e5559f17cd591aa25d2ed6c34ac9ed89e2e9ba" region="gfx3" offset="0"/>
		<rom name="mbf03-16.17d" size="2097152" crc="37d25c75" sha1="8219d31091b4317190618edd8acc49f97cba6a1e" region="gfx3" offset="400001"/>
		<rom name="mbf05-16.19d" size="2097152" crc="137be66d" sha1="3fde345183ce04a7a65b4cedfd050d771df7d026" region="gfx3" offset="400000"/>
		<rom name="mbf06.15k" size="524288" crc="fb513903" sha1="7727a49ff7977f159ed36d097020edef3b5b36ba" region="sound1" offset="0"/>
		<rom name="mbf07.16k" size="524288" crc="51d4adc7" sha1="22106ed7a05db94adc5a783ce34529e29d24d41a" region="sound2" offset="0"/>
		<rom name="kt-00.8j" size="512" crc="7294354b" sha1="14fe42ad5d26d022c0fe9a46a4a9017af2296f40" region="proms" offset="0"/>
		<chip type="cpu" name="ARM" clock="7000000"/>
		<chip type="cpu" soundonly="yes" name="HuC6280" clock="4027500"/>
		<chip type="audio" name="YM2151" clock="3580000"/>
		<chip type="audio" name="MSM6295" clock="7627"/>
		<chip type="audio" name="MSM6295" clock="7627"/>
		<video screen="raster" orientation="horizontal" width="320" height="240" aspectx="4" aspecty="3" refresh="60.000000"/>
		<sound channels="2"/>
		<input players="2" control="joy8way" buttons="6" coins="2" service="yes"/>
		<driver status="protection" color="good" sound="good" palettesize="2048"/>
	</game>
	<game name="fghthistu" cloneof="fghthist" romof="fghthist">
		<description>Fighters History (US ver 42-03)</description>
		<driver>fghthistu</driver>
		<year>1993</year>
		<manufacturer>Data East Corporation</manufacturer>
		<rom name="kz00-1.1f" size="524288" crc="3a3dd15c" sha1="689b51adf73402b12191a75061b8e709468c91bc" region="cpu1" offset="0"/>
		<rom name="kz01-1.2f" size="524288" crc="86796cd6" sha1="c397c07d7a1d03ba96ccb2fe7a0ad25b8331e945" region="cpu1" offset="2"/>
		<rom name="kz02.18k" merge="kz02.18k" size="65536" crc="5fd2309c" sha1="2fb7af54d5cd9bf7dd6fb4f6b82aa52b03294f1f" region="cpu2" offset="0"/>
		<rom name="mbf00-8.8a" merge="mbf00-8.8a" size="1048576" crc="d3e9b580" sha1="fc4676e0ecc6c32441ff66fa1f990cc3158237db" region="gfx1" offset="0"/>
		<rom name="mbf01-8.9a" merge="mbf01-8.9a" size="1048576" crc="0c6ed2eb" sha1="8e37ef4b1f0b6d3370a08758bfd602cb5f221282" region="gfx2" offset="0"/>
		<rom name="mbf02-16.16d" merge="mbf02-16.16d" size="2097152" crc="c19c5953" sha1="e6ed26f932c6c86bbd1fc4c000aa2f510c268009" region="gfx3" offset="1"/>
		<rom name="mbf04-16.18d" merge="mbf04-16.18d" size="2097152" crc="f6a23fd7" sha1="74e5559f17cd591aa25d2ed6c34ac9ed89e2e9ba" region="gfx3" offset="0"/>
		<rom name="mbf03-16.17d" merge="mbf03-16.17d" size="2097152" crc="37d25c75" sha1="8219d31091b4317190618edd8acc49f97cba6a1e" region="gfx3" offset="400001"/>
		<rom name="mbf05-16.19d" merge="mbf05-16.19d" size="2097152" crc="137be66d" sha1="3fde345183ce04a7a65b4cedfd050d771df7d026" region="gfx3" offset="400000"/>
		<rom name="mbf06.15k" merge="mbf06.15k" size="524288" crc="fb513903" sha1="7727a49ff7977f159ed36d097020edef3b5b36ba" region="sound1" offset="0"/>
		<rom name="mbf07.16k" merge="mbf07.16k" size="524288" crc="51d4adc7" sha1="22106ed7a05db94adc5a783ce34529e29d24d41a" region="sound2" offset="0"/>
		<rom name="kt-00.8j" merge="kt-00.8j" size="512" crc="7294354b" sha1="14fe42ad5d26d022c0fe9a46a4a9017af2296f40" region="proms" offset="0"/>
		<chip type="cpu" name="ARM" clock="7000000"/>
		<chip type="cpu" soundonly="yes" name="HuC6280" clock="4027500"/>
		<chip type="audio" name="YM2151" clock="3580000"/>
		<chip type="audio" name="MSM6295" clock="7627"/>
		<chip type="audio" name="MSM6295" clock="7627"/>
		<video screen="raster" orientation="horizontal" width="320" height="240" aspectx="4" aspecty="3" refresh="60.000000"/>
		<sound channels="2"/>
		<input players="2" control="joy8way" buttons="6" coins="2" service="yes"/>
		<driver status="protection" color="good" sound="good" palettesize="2048"/>
	</game>
	<game name="fghthista" cloneof="fghthist" romof="fghthist">
		<description>Fighters History (US ver 42-05, alternate hardware)</description>
		<driver>fghthista</driver>
		<year>1993</year>
		<manufacturer>Data East Corporation</manufacturer>
		<rom name="le-00.1f" size="524288" crc="a5c410eb" sha1="e2b0cb2351782e1155ecc4029010beb7326fd874" region="cpu1" offset="0"/>
		<rom name="le-01.2f" size="524288" crc="7e148aa2" sha1="b21e16604c4d29611f91d629deb9f041eaf41e9b" region="cpu1" offset="2"/>
		<rom name="kz02.18k" merge="kz02.18k" size="65536" crc="5fd2309c" sha1="2fb7af54d5cd9bf7dd6fb4f6b82aa52b03294f1f" region="cpu2" offset="0"/>
		<rom name="mbf00-8.8a" merge="mbf00-8.8a" size="1048576" crc="d3e9b580" sha1="fc4676e0ecc6c32441ff66fa1f990cc3158237db" region="gfx1" offset="0"/>
		<rom name="mbf01-8.9a" merge="mbf01-8.9a" size="1048576" crc="0c6ed2eb" sha1="8e37ef4b1f0b6d3370a08758bfd602cb5f221282" region="gfx2" offset="0"/>
		<rom name="mbf02-16.16d" merge="mbf02-16.16d" size="2097152" crc="c19c5953" sha1="e6ed26f932c6c86bbd1fc4c000aa2f510c268009" region="gfx3" offset="1"/>
		<rom name="mbf04-16.18d" merge="mbf04-16.18d" size="2097152" crc="f6a23fd7" sha1="74e5559f17cd591aa25d2ed6c34ac9ed89e2e9ba" region="gfx3" offset="0"/>
		<rom name="mbf03-16.17d" merge="mbf03-16.17d" size="2097152" crc="37d25c75" sha1="8219d31091b4317190618edd8acc49f97cba6a1e" region="gfx3" offset="400001"/>
		<rom name="mbf05-16.19d" merge="mbf05-16.19d" size="2097152" crc="137be66d" sha1="3fde345183ce04a7a65b4cedfd050d771df7d026" region="gfx3" offset="400000"/>
		<rom name="mbf06.15k" merge="mbf06.15k" size="524288" crc="fb513903" sha1="7727a49ff7977f159ed36d097020edef3b5b36ba" region="sound1" offset="0"/>
		<rom name="mbf07.16k" merge="mbf07.16k" size="524288" crc="51d4adc7" sha1="22106ed7a05db94adc5a783ce34529e29d24d41a" region="sound2" offset="0"/>
		<rom name="kt-00.8j" merge="kt-00.8j" size="512" crc="7294354b" sha1="14fe42ad5d26d022c0fe9a46a4a9017af2296f40" region="proms" offset="0"/>
		<chip type="cpu" name="ARM" clock="7000000"/>
		<chip type="cpu" soundonly="yes" name="HuC6280" clock="4027500"/>
		<chip type="audio" name="YM2151" clock="3580000"/>
		<chip type="audio" name="MSM6295" clock="7627"/>
		<chip type="audio" name="MSM6295" clock="7627"/>
		<video screen="raster" orientation="horizontal" width="320" height="240" aspectx="4" aspecty="3" refresh="60.000000"/>
		<sound channels="2"/>
		<input players="2" control="joy8way" buttons="6" coins="2" service="yes"/>
		<driver status="protection" color="good" sound="good" palettesize="2048"/>
	</game>
	<game name="fghthistj" cloneof="fghthist" romof="fghthist">
		<description>Fighters History (Japan ver 42-03)</description>
		<driver>fghthistj</driver>
		<year>1993</year>
		<manufacturer>Data East Corporation</manufacturer>
		<rom name="kw00-3.1f" size="524288" crc="ade9581a" sha1="c1302e921f119ff9baeb52f9c338df652e64a9ee" region="cpu1" offset="0"/>
		<rom name="kw01-3.2f" size="524288" crc="63580acf" sha1="03372b168fe461542dd1cf64b4021d948d07e15c" region="cpu1" offset="2"/>
		<rom name="kz02.18k" merge="kz02.18k" size="65536" crc="5fd2309c" sha1="2fb7af54d5cd9bf7dd6fb4f6b82aa52b03294f1f" region="cpu2" offset="0"/>
		<rom name="mbf00-8.8a" merge="mbf00-8.8a" size="1048576" crc="d3e9b580" sha1="fc4676e0ecc6c32441ff66fa1f990cc3158237db" region="gfx1" offset="0"/>
		<rom name="mbf01-8.9a" merge="mbf01-8.9a" size="1048576" crc="0c6ed2eb" sha1="8e37ef4b1f0b6d3370a08758bfd602cb5f221282" region="gfx2" offset="0"/>
		<rom name="mbf02-16.16d" merge="mbf02-16.16d" size="2097152" crc="c19c5953" sha1="e6ed26f932c6c86bbd1fc4c000aa2f510c268009" region="gfx3" offset="1"/>
		<rom name="mbf04-16.18d" merge="mbf04-16.18d" size="2097152" crc="f6a23fd7" sha1="74e5559f17cd591aa25d2ed6c34ac9ed89e2e9ba" region="gfx3" offset="0"/>
		<rom name="mbf03-16.17d" merge="mbf03-16.17d" size="2097152" crc="37d25c75" sha1="8219d31091b4317190618edd8acc49f97cba6a1e" region="gfx3" offset="400001"/>
		<rom name="mbf05-16.19d" merge="mbf05-16.19d" size="2097152" crc="137be66d" sha1="3fde345183ce04a7a65b4cedfd050d771df7d026" region="gfx3" offset="400000"/>
		<rom name="mbf06.15k" merge="mbf06.15k" size="524288" crc="fb513903" sha1="7727a49ff7977f159ed36d097020edef3b5b36ba" region="sound1" offset="0"/>
		<rom name="mbf07.16k" merge="mbf07.16k" size="524288" crc="51d4adc7" sha1="22106ed7a05db94adc5a783ce34529e29d24d41a" region="sound2" offset="0"/>
		<rom name="kt-00.8j" merge="kt-00.8j" size="512" crc="7294354b" sha1="14fe42ad5d26d022c0fe9a46a4a9017af2296f40" region="proms" offset="0"/>
		<chip type="cpu" name="ARM" clock="7000000"/>
		<chip type="cpu" soundonly="yes" name="HuC6280" clock="4027500"/>
		<chip type="audio" name="YM2151" clock="3580000"/>
		<chip type="audio" name="MSM6295" clock="7627"/>
		<chip type="audio" name="MSM6295" clock="7627"/>
		<video screen="raster" orientation="horizontal" width="320" height="240" aspectx="4" aspecty="3" refresh="60.000000"/>
		<sound channels="2"/>
		<input players="2" control="joy8way" buttons="6" coins="2" service="yes"/>
		<driver status="protection" color="good" sound="good" palettesize="2048"/>
	</game>

**Comment by Wilstorm** [comment]
Ok, I see fghthist, fghthista, fghthistj & fghthistu in Plus and in 2003 I see fghthist, fghthsta & fghthstw. It seems the parent ROM is same name but different/newer(?) versions in Plus vs 2003. Also fghthsta and fghthista seems to be in the same boat being one letter off (i) but a slightly different/newer(?) version in Plus also.

I'm ok with that I'll make a note as it threw me off when I was looking at it last night thinking this doesn't look quite right with matching names for World vs. US versions.

**Comment by markwkidd** [comment]
I've had a chance to build a set recently and everything seemed to go correctly. OK to close this issue @Wilstorm ?

**Comment by Wilstorm** [comment]
@markwkidd - Yeah it always built properly. Basically I think it's just a different version of the game from a newer MAME code base backported. I don't think it's an issue at all but more of a make note if a parent/clone fails to run it might belong to the "other" parent, derived of the same name. I always compare sets after each build and saw some oddities but in sticking with the DATs it shouldn't be an issue at all. I will close it.
