### ISSUE TITLE
Issues with Thunderjaws

### ISSUE THREAD

**Issue by Wilstorm** [libretro/mame2003-plus-libretro#339]
The game seems to have some random and intermittent graphical issues and lockups. In the screenshots below you can see player 2 is still on the screen when his game is over. Also the Player 2 game will just end and go back to displaying add credits to continue play for no reason. Player 1 has two sprites, one dead and one playable sometimes. Shown on the screen. Sometimes the whole screen will just randomly scroll down with random graphics occasionally too. It might play well for minutes or seconds it's very random. It's the same for 2003 and Plus on a Pi 3.

![thunderj-180823-184941](https://user-images.githubusercontent.com/8192258/44591748-26023280-a784-11e8-9bc6-f532c5ad3c17.png)

![thunderj-180823-185011](https://user-images.githubusercontent.com/8192258/44592561-927e3100-a786-11e8-9c8e-d66e20d3ee57.png)

![thunderj-180823-185006](https://user-images.githubusercontent.com/8192258/44592597-aa55b500-a786-11e8-8592-1e27fd767a8b.png)

**Comment by grant2258** [comment]
how long do you have to play for this to start or does it just happen sometimes

**Comment by Wilstorm** [comment]
It varies but usually it starts within a few minutes. At first it's still playable then eventually the screen scrolls down real slow like in screenshots 2 and 3. You can do a reset or exit to fix the issue but then it starts again after a few minutes.

**Comment by Wilstorm** [comment]
If it's alright I am going to piggy back on this issue with another one instead of creating a bunch of new issues unless it's preferred. In Thundercade (tndrcade). The games works fine but something is weird with Player 2's scoring. I think it happens when adding credits to restart Player 2 after they die. In the screenshot below you can see how unbalanced Player 2's score is after a few minutes of play of just riding and not even shooting. This doesn't seem to happen to Player 1 when adding more credits after dying and restarting the game. I've been doing screenshots and most of the games are fine but getting into the T's here I am finding a few with errors. :)

![tndrcade-180823-180100](https://user-images.githubusercontent.com/8192258/44597636-eba19100-a795-11e8-986c-1c4e36e0e7f8.png)

**Comment by arcadez** [comment]
With regards to Thundercade this might actually not be a bug per say but an oversight by
the game dev's which is present on the pcb..?? have you tried it latest MAME to see if the 
player2 score is cleared when continuing.??

As for Thunderjaws it's likely a problem on the libretro side as in MAME78 this game should work fine

**Comment by Wilstorm** [comment]
@arcadez - I appreciate you taking a look. Thunderjaws is pretty buggy in Libretro I tried several times with all kinds of weird errors but still a classic. Love watching those sharks blow up! :) I might try to go see "The Meg" for an afternoon getaway as the wife has no interest. Would love to see another classic like the original good ol' Jaws.

I haven't tested Thundercade in current MAME. I haven't fired it up in months even though I keep it current but I'll give it a test and see.

**Comment by grant2258** [comment]
have your tried running  Thunderjaws on mame078 and see if its new i bootted teh game up seemed fine on windows anyway I didnt play ut that long to be fair

**Comment by grant2258** [comment]
@arcadez i found a handy site for getting mame diff info ect https://git.redump.net/mame/refs/?h=memory dont know if you knwo about this or know i think it starts at mame 0.121 anything below that  I use mame-history on the mamedev github page

**Comment by Wilstorm** [comment]
@grant2258 @arcadez - You guys are correct ThunderJaws does indeed work fine in regular MAME so something was broken when ported to Libretro, shame for a decent game! =/

**Comment by grant2258** [comment]
I just played it on windowss for a while it was all good on mame2003+ ill try i on the pie

**Comment by Wilstorm** [comment]
@arcadez - Thanks, you're alt game suggestion for Head-on was spot on I will give it a shot!

**Comment by Wilstorm** [comment]
@grant2258 - I'm on RP 4.3 and I think RA is 1.7.1, I think. Both are older and not current though either way.

**Comment by grant2258** [comment]
if you get no joy try this 

cd  /opt/retropie/configs/all
cp retroarch.cfg retroarch.cfg.bak
cp retroarch.cfg.rp-dist retroarch.cfg

cd /opt/retropie/configs/mame-libretro
cp retroarch.cfg retroarch.cfg.bak
cp retroarch.cfg.rp-dist retroarch.cfg

**Comment by grant2258** [comment]
if you want to restore your original configs you have them saved anyway

**Comment by Wilstorm** [comment]
@grant2258 - Joysticks are ok, no issues at all really except the graphical snafus shown above when in game playing. I guess it must be RA causing the graphical issues as I am on the current version of Plus and the RP script.

**Comment by grant2258** [comment]
Try compiling ra from source else update to 1.7.3 for ra

**Comment by Wilstorm** [comment]
@grant2258 - I am almost done doing screenshots and then I will get current to see if it fixes the issue. Right now I have my Pi setup heavily modified for screenshots, pausing, fast forward, frame walking, etc. to get screenshots that are played and not just 2 seconds into the game. 

Here's another game Tough Turf (tturfu.zip) that has a graphical issue. Basically if your character stands still it's ok if you move then it flickers back and forth between normal to the graphic block shown in the snap below. It's not that you guys need to fix any of these but I am just listing them so everyone is aware and if there's any easy fix great and if not that ok too.

![tturfu-180824-183914](https://user-images.githubusercontent.com/8192258/44737345-5b29c000-aab7-11e8-82d3-7db2b44bc263.png)

**Comment by grant2258** [comment]
Well I would only report them if they are a problem with current and a normal setup. I. Not sure what your modifying or what timeframes you taking taking screenshots at but not every frame is perfect in every game

**Comment by Wilstorm** [comment]
@grant2258 - It is a normal setup. What I am modifying is RA settings such as Hotkey + Left Shoulder for screenshots, Hotkey + Right Trigger for pause, Hotkey + Left Shoulder for frame advance, etc. All standard RA settings right from the menu. I just prefer to modify the all/retroarch.cfg file directly vs using menus.

What is shown above is normal play, nothing fancy going on. I figured being current with Plus even using RA 1.7.1 would have been ok but I'll refrain from posting anymore errors or testing until current as per your request. =/

**Comment by Wilstorm** [comment]
@arcadez - You have a ton of MAME institutional knowledge. I did test on official 0.78 on Windows and you're right the same issues. Thanks for the tip on the bootleg I will slot that one in place of the US version.

**Comment by SaucySarah** [comment]
Just to confirm, I tried Thunderjaws on latest Android build and it seems fine, no graphical glitches (only played to the end of the 'Rolling Thunder !' type level).

**Comment by Wilstorm** [comment]
@SaucySarah - That's interesting. Does the Droid use RA as the frontend? Do you know which version or do you use something else entirely? I struggled a little with the frontend being the cause of the graphical issues. Also RetroPie has Emulationstation thrown into the mix which I don't if it's considered another front-end or a fancy game launcher or what not and some combination of the three is the cause because it does run fine with official MAME 0.78 on Windows. I would assume the core itself isn't the issue as I think Droid and Pi are both ARM but compiled slightly different?

**Comment by SaucySarah** [comment]
On Android my RetroArch version is 1.7.3 and mame2003plus https://github.com/libretro/mame2003-plus-libretro/commit/8a38d02361d1282fae84177a284e7e2ab2b6de86. I have only played 1 player though, maybe 2 player screws up the graphics ?

**Comment by Wilstorm** [comment]
@SaucySarah - You might be on to something there. I played up to the lab entrance single player a few times and I couldn't get it to reproduce the errors. Then I played 2 player and it happened once out of three plays. I don't know if it's worth tracking down even. There's nothing worse than intermittent errors that you can't reproduce on demand.

**Comment by grant2258** [comment]
@Wilstorm emulation station is just a launcher but retroach is setup different on retropie. Regardless of that fact new versions of ra sometimes change things that fixes a big that will effect older versions. It like windows patching a bug if you dont update some new stuff wont work. Is there any reason you wont update it?

**Comment by Wilstorm** [comment]
@grant2258 - I am not trying to be a pain in the ass and will upgrade to the newest version soon. My focus has been mostly singular in purpose. I am so close to finishing up my in game screenshots. So close. I was banging them out left and right in the beginning but this last leg has been rough. It's like the last mile of a race. I am dragging ass and procrastinating a bit. When I upgrade it would be to RetroPie 4.4 on Jesse which had a few rough spots on release and was another reason I held off a bit. Then testing results would be current and valid. I am on RP 4.3 currently. I do understand the value of using the current version as half our department is in house programmers and half the apps our organization uses have been developed in-house. I've been in the field I good 30 years so that's why I validated your request for any testing that could be version related until I can get current again.

**Comment by Wilstorm** [comment]
Here's some interesting information on EmulationStation. Well not the original author but the RetroPie fork. Since they use RA also I would say they basically use two front-ends or embedded front-ends?

EmulationStation is the official graphical frontend of the RetroPie project. EmulationStation is not an emulator, rather it is a polished game launcher that includes:

Controller and keyboard support
Custom themes
Scraper for box art and game metadata

**Comment by grant2258** [comment]
emulation station just launches ra from the command line so the only time you will ever see retroarch is when you press your hotkey and see thw rgui menu to set the core options ect.

**Comment by grant2258** [comment]
are you still having these issues since updating your retropie @Wilstorm

**Comment by Wilstorm** [comment]
@grant2258 - Thanks, I'll update current and test it this weekend. I am having some weird input lag when selecting keys in the TAB screen. It might be 2 or 3 seconds before it registers. I know there's been a boatload of updates these past days so I need to update and if it happens after getting current I'll open an issue.

**Comment by grant2258** [comment]
gamelist.xml is that emulation station ?

**Comment by Wilstorm** [comment]
I did use a scraper then went back and redid my own screenshots in HD. RA has settings to dump snaps right in the images folder with the proper name if you want. The scraped default ones pretty much suck. I only have about 330 HD snaps from the set but they cover all the old classics.

**Comment by Wilstorm** [comment]
And I removed all the extra version info from behind the title so it looks cleaner. I spend more time tweaking than playing. I'm doing it wrong. :/

**Comment by Wilstorm** [comment]
Sorry, last post and I should sleep a few hours. I am a night owl for sure. I just watched a movie called "Ingrid Goes West" talk about messed up. Anyway the Arcade folder in RetroPie makes that list look like one seamless game list. I am actually running 2003, Plus, FBA and AdvMAME. I setup AdvMAME (being a non-Libreto core) to match RA so to the user it's one list of arcade games that all use the same controls to start, run and exit games.

**Comment by grant2258** [comment]
@Wilstorm i want to rule out emulation station from this issue. Could you give me the full path to your mame2003_plus roms so I can give you a command line to paste.

**Comment by Wilstorm** [comment]
Yeah I just use the defaults. It's either /home/pi/RetroPie/roms/mame-libretro or arcade. I go back and forth between the two.

**Comment by grant2258** [comment]
well you need to pres f4 to get to the command line when your in emulation station to stop it the run the the game from the command line

it will be one of the below depending on where you 2003 plus roms are


/opt/retropie/emulators/retroarch/bin/retroarch -L /opt/retropie/libretrocores/lr-mame2003/mame2003_libretro.so --config /opt/retropie/configs/mame-libretro/retroarch.cfg "/home/pi/RetroPie/roms/mame-libretro/thunderj.zip"

/opt/retropie/emulators/retroarch/bin/retroarch -L /opt/retropie/libretrocores/lr-mame2003/mame2003_libretro.so --config /opt/retropie/configs/mame-libretro/retroarch.cfg "/home/pi/RetroPie/roms/arcade/thunderj.zip"

 if you arent overclocked and its not emulation station im at a loss I cant reproduce this on a pi windows or linux. That why id like you to try this. If its an emulation station issue best post on the retropie forums.

**Comment by Wilstorm** [comment]
Ok, thanks I will try it via command line but isn't ES still loaded? After working at the command line I usually just type "exit" to restart ES.

**Comment by grant2258** [comment]
yea es will reload when you type exit

**Comment by Wilstorm** [comment]
So it's not a shell but truly exiting ES? I will try it out and let you know. It's random but usually on the first level somewhere random before the lab.

**Comment by grant2258** [comment]
yea its the only way i can update my game list xml  properly you can change this yourself while es is running

**Comment by Wilstorm** [comment]
Cool, I always wondered. Do you happen to know the command that brings up that colored information when exit ES?

**Comment by grant2258** [comment]
its just the bash login text type bash and it should appear

**Comment by Wilstorm** [comment]
Thanks Grant for all the information, I will test it and let you know how it turns out. I'm finishing up some cheese flick on Netflix and better sleep a few hours before work. Man I never get enough sleep! 😴

**Comment by grant2258** [comment]
no probs i better get some sleep myself work calls me tonight

**Comment by markwkidd** [comment]
Where did this issue wind up? Is this this still active?
