### ISSUE TITLE
a name for this emulator core

### ISSUE THREAD

**Issue by markwkidd** [libretro/mame2003-plus-libretro#340]
Hi folks, and especially @arcadez . FWIW: the later it gets in the year, theoretically the more free time I will be having again so I look forward to being able to make more code contributions again.

I wanted to start a discussion about a thought that I've had for a long time now. Thanks to all the backports, this is definitely no longer "MAME as it was in 2003", which is the tagline for mame2003-libretro. However I think that when new users see mame2003-plus listed in the RetroArch downloader or RetroPie, it probably sounds old and out of date.

**Consider what it would be like if AdvanceMAME was instead named "MAME 2006". I don't think it would be as popular!**

I would like to encourage arcadez to agree to renaming this core to something that expresses that this emulator is a high-performance, low-overhead version of MAME.

I won't lie -- I even have a specific suggestion. After months the best name I can think of to express this idea is :zap: **Lightning MAME** :zap:, which no active projects are using at the moment. 

I don't think the new name has to be Lightning MAME, but I do hope folks will come to agree that a fresh, distinct, cool name would help make this emulator more widely known.

**Comment by markwkidd** [comment]
I would guess that over time, MAME 2000, MAME 2008, and MAME 2010 will fade away unless someone really decides to invest time and energy like we've been doing here.

I would bet that the same thing will actually happen to MAME 2003 eventually, compared to MAME 2003-Plus. Once we have figured out a few slowdowns (probably related to my logging API project) this core will be superior in every way to MAME 2003.

Given a few years I wouldn't be surprised if only MAME 2003-Plus (hopefully with a different name :sunglasses: ), MAME 2016, and current MAME are widely used among the current MAME cores. That is just my guess, but I'd call it an educated guess.

**Comment by robertvb83** [comment]
I use mame2003-plus for my raspberry pi powered arcade.
"2003" in fact is not fitting perfectly with some roms taken from far later versions!
Thats also the reason why the romset it pretty hard to get complete as it is a mixture of many parts of many mame versions
Lightning mame is fine with me but i am still thinking

**Comment by twinaphex** [comment]
The last thing we need is more opaque vague renamings of cores. 

MAME 2003 Plus is just fine. I really do not want to go down this road.

Also, this is hardly important. Focus on stuff that actually matters. A name change is useless.

**Comment by twinaphex** [comment]
> I would guess that over time, MAME 2000, MAME 2008, and MAME 2010 will fade away unless someone really decides to invest time and energy like we've been doing here. I would bet that the same thing will also happen to MAME 2003 eventually unless there is a major issue with this core.

These MAME versions are meant to be 'frozen in time' versions of MAME. The entire reason why I proposed to @arcadez and others to make a new fork of MAME 2003 is precisely because to some, they want these older MAME versions to remain ' frozen in time' instead of continuous development.

**Comment by arcadez** [comment]
Yeah i must admit like @twinaphex i felt MAME2003-plus was a perfectly fine name for this core
i cant mind who it was that originally stated we cant call it this but i have an idea :)

**Comment by robertvb83** [comment]
Would you say that plus is still related to 2003 very much? Then i understand you favor mame2003-plus.
Bit i think right now this thing has evolved and includes features of later mame versions and even unique features and lots of games from later mame versions.... So i had the feeling that 2003 is not really ewhat it is anymore

What about "classic mame" or "retro mame" as it is fany nowadays to call things retro :-)

**Comment by Wilstorm** [comment]
> i cant mind who it was that originally stated we cant call it this but i have an idea :)

I do recall that bedtime story. =/

> What about "classic mame" or "retro mame" as it is fany nowadays to call things retro :-)

Win-win I like them both. Covers the golden age of video games nicely Plus some! ;) 

@markwkidd - I agree with your sentiments on other cores unless folks are willing to sink some serious development to bring them inline. Last I checked no ones in line and we aren't getting any younger. The millennial's have little interest in 8-bit. I am good either way. Running with Plus or "rebranding". It's my core of choice for the Pi no matter what you call it just don't call me late for supper...

**Comment by arcadez** [comment]
Ok then it seems we are gonna stick with MAME2003-plus for now, i'll close this down
should anyone feel like revisiting this again at some future date then feel free.
