### ISSUE TITLE
ddragon is not starting

### ISSUE THREAD

**Issue by robertvb83** [libretro/mame2003-plus-libretro#342]
ddragon is not starting after latest update from source today. please see reference to #336

**Comment by robertvb83** [comment]
i did some more testing... if i delete the custom ost in the samples folder, the game starts and is working again. only with the custom-ost game is still not starting

**Comment by robertvb83** [comment]
I am on retropie with retroarch 1.7.3
I tested ddragon.zip

**Comment by grant2258** [comment]
can you post you commit numbers for ra and mame2003plus there is no problems my end

**Comment by robertvb83** [comment]
![20180828_075832](https://user-images.githubusercontent.com/36081149/44703554-63263780-aa98-11e8-94ea-a3fe1a0a68ef.jpg)

**Comment by robertvb83** [comment]
![20180828_080215-1](https://user-images.githubusercontent.com/36081149/44703708-f19ab900-aa98-11e8-940f-23e0e34bce54.jpg)

**Comment by grant2258** [comment]
strange its working fine for me lets wait and see if anyone else is having any issues.

**Comment by robertvb83** [comment]
Are you testing this on a raspberry pi? This is strange. Before showering i launched ddragon and started a timer. after coming back it took another 5 minutes and then it startet
Total: 20 minutes launching time... This is insane :-)
So it is working but somehow launching with ost takes soooo long

**Comment by robertvb83** [comment]
KMFDManic's megaupload repository

**Comment by robertvb83** [comment]
I redownliaded the sound. Ok so now i just opened the ddragon.zip sound file and found an additional MacOS folder, deleted it and now everything starts just fine
