### ISSUE TITLE
[Killing Blade] Not working?

### ISSUE THREAD

**Issue by nemo93** [libretro/mame2003-plus-libretro#346]
Doesn't launch either with a rom from 0.78 or .78+ on 2003+. Launch with Mame0.139 but slow. 

Killing Blade (killbld.zip). I'm using roms which include the bios so I should be good.  I'm wondering if I should use a bootleg or another specific version? Sorry as I'm not an expert and don't know where to look without asking :(

**Comment by arcadez** [comment]
Listen buddy this is a dev site not really the place for requests and such, but we do welcome
bug reports which this is not, this game works perfectly fine if you happen to have the correct
romset.
