### ISSUE TITLE
[Requests] adding sound?

### ISSUE THREAD

**Issue by nemo93** [libretro/mame2003-plus-libretro#347]
hi, I'm truly impressed by this core and I'd love it to be my sole arcade Emu on Pi. I have to rely on FBA still for few games and I'm wondering if the following could be supported on 2003+ please. 

Apologize if you don't like or don't want people to submit requests. If that's the case then I'll close that one immediately.

* batsugun
* dogyuun
* grindstm (grindstormer)
* kbash
* outfxies (outfoxies, game is awesome)
* raiden2 (gfx issue as well on this core)
* tturf (tough turf)
* vfive (v-v)

Thank you.

**Comment by arcadez** [comment]
Outta all of the above due to incompatable code only Tough Turf is doable, but since it
has graphical problems which cant be fixed in this core then it's not really worth adding the
sound.
