### ISSUE TITLE
[Driftout '94] sound issue

### ISSUE THREAD

**Issue by nemo93** [libretro/mame2003-plus-libretro#348]
Game does launch and run perfect. However after the home screen while picking up a name / car the sound goes "crazy". Not sure how best I could describe but definitely there's a sound issue you can hear clearly at this stage.

Tried with a .78 and .78+ romset (drifto94.zip).

**Comment by arcadez** [comment]
We're talking about the sound problems with some of the SSV games in another issue thread
so i'll close this to avoid duplication.
