### ISSUE TITLE
[Request] faster emulation?

### ISSUE THREAD

**Issue by nemo93** [libretro/mame2003-plus-libretro#349]
Hi, below games are running but slow. Wondering if there's any chance to speed them up somehow? If not I'll close the case.

* jchan (Jackie Chan - The Kung-Fu Master)
* jchan2 (Jackie Chan in Fists of Fire - not supported in this core by the way, just asking!)
* jdreddp (Judge Dredd, Midway)
* nbbatman (Ninja Baseball Bateman. Awesome, plays fine however there are slowdowns eg. beginning of each stage when you have the "rotating map")
* primrage (Primal Rage)
* rayforce

Thank you.

**Comment by arcadez** [comment]
It's just the limitations of the hardware your using, in theory there might be a way to speedup
the games but it's above my paygrade :)
