### ISSUE TITLE
[Request] better support for SEGA systems?

### ISSUE THREAD

**Issue by nemo93** [libretro/mame2003-plus-libretro#350]
Another request to support SEGA games not bootleg. Not sure I understand the difference between parent and bootlegs but anyway some SEGA games are not running or not properly (eg. slow).

* alexkidd
* astorm
* dbzvrvs (doesn't launch currently)
* ddcrew
* ddux
* eswat
* fantzn2
* ga2 (Golden Axe 2. Does work full speed however the shadows are glitchy)
* gforce2
* mwalk
* outrun
* pdrift
* toutrun

**Comment by Wilstorm** [comment]
You might want to browse through the issues here as several of these games have been addressed in one form or another on if they work, a suggested alternate set or a currently known issue. Those with issues may or may not receive an update in the future. These guys work on this in their spare time so you have to be patient. Not to discourage but I see several in the list above where the bootlegs work fine for like ddcrew, eswat, alexkidd, I think astorm, ga2 (the shadows issues are known). I thought Outrun worked if I remember correctly. Anyway don't hesitate to try some of the bootleg versions as they run very well and only the elitist would know the difference. 

A parent ROM may vary such as the world release of a game (vs a specific country or region), last current version, official release, etc.

A bootleg can be an alternate set such as levels in a different order, harder, faster, bugs fixed, updates, text in other languages, etc. Or maybe it's a decrypted MCU until a proper decryption or dump of the game may be obtained.

**Comment by arcadez** [comment]
Outta all of the above games due to code limitations in this core only dbzvrvs would be doable
but since it sucks balls im not gonna work on it :)
