### ISSUE TITLE
[Request] more games?

### ISSUE THREAD

**Issue by nemo93** [libretro/mame2003-plus-libretro#351]
Another one and again I'll close it if you don't like it! Would it be possible to add support of the following games please? Note: these do work on FBA.

* bgaregga (Battle Garegga)
* ddp2 (DoDonPachi II - Bee Storm)
* ddpdoj (DoDonPachi Dai-Ou-Jou)
* ddpdojblk (DoDonPachi Dai-Ou-Jou Black Label)
* dmnfrnt (Demon Front)
* drgnbowl (Dragon Bowl)
* espgal
* gforce2 (Galaxy Force 2)
* ket (Ketsui: Kizuna Jigoku Tachi)
* kov2 (Knights of Valour 2 / Sanguo Zhan Ji 2 / Sangoku Senki 2)
* martmast (Martial Masters)
* svg (Spectral vs Generation)
* theroes (Thunder Heroes)
* CPS3 games (SF3s, Redearth, Jojos)

Thank you.

**Comment by arcadez** [comment]
Again you have to understand that this core is in no way compatable with the source code
from later MAME versions which support the above games, if it was im sure someone would
have added em all by now ;)

From your list Dragon Bowl and Thunder Heros would be doable it's just finding the time i
do have other projects i contribute to ya know ;) BTW isn't Battle Garegga already playable.??

**Comment by Wilstorm** [comment]
Maybe to add to this if you use RetroPie they have a folder named "Arcade". You can add ROMs from any supported MAME emulator (even non-Libretro cores such as AdvMAME which has the best vector game support), start the ROM and then pick from a list of installed emulators. It will remember which emulator you chose from there on out when you launch that game.

Also if a majority of your ROMs are from one MAME emulator you can pick one as a default for games that aren't tagged for a specific emulator.

This allows you to mix and match games from all emulators but they appear as a single pane of glass and look as though they are all one emulator in a single list, it's incredibly useful.

**Comment by nemo93** [comment]
Thank you for taking time to answer. Apologize for the spam. I haven't tried Garegga as I didn't find rom except for .139 (where it works perfect).

Thanks @Wilstorm that's what I'm going on to use from now on.

**Comment by Wilstorm** [comment]
@nemo93 - Uuf da, I don't have anything to add here to all these open issues except to say I enjoy your passion. That comes and goes for me depending on my free time but it's always there and there's just nothing like your first passionate love....classic arcade games! ;)
