### ISSUE TITLE
[Small gfx glitches] 2 CPS2 games

### ISSUE THREAD

**Issue by nemo93** [libretro/mame2003-plus-libretro#353]
In Darkstalkers (dstlk.zip) at the character selection screen you could see the image of the currently selected character to flicker. Not sure this is intended. I've tried with 0.78 and .78+ romset. Haven't tried on .139 yet.

In Dungeons & Dragons: Tower of Doom (ddtod.zip) at the home screen asking to insert credits you can see the third "insert coin" to barely appear/to flicker. Tried on 0.78 and .78+ romset. Haven't tried on .139 yet.

**Comment by arcadez** [comment]
Well these are little glitches which dont really affect the gameplay i tend not to bother with em
but maybe someone might come along and want to work on ironing these niggles out sometime

**Comment by nemo93** [comment]
Thanks @Wilstorm. Exactly. It was simply a feedback from my end and as @arcadez stated it's far from being a game breaking bug. I'm ok to close that one then.
