### ISSUE TITLE
[Power Instinct Legends / Gogetsuji Legends] Issue

### ISSUE THREAD

**Issue by nemo93** [libretro/mame2003-plus-libretro#354]
plegends.zip

Game does launch and looks ok until the character selection screen. There if you select characters you may see some axes appearing on screen and then game slows down and stop responding.

Tested on .78 and .78+.

**Comment by arcadez** [comment]
Thanks for the bug report i know the what's causing the above as for fixing it i might need
some advice from @markwkidd @grant2258

**Comment by grant2258** [comment]
I can confirm this is happening when starting the game right now. I havent used the pie in a long time though so ill need to verify my romsets thats on the pie first before u can say it is a problem as this version of mame will load bad crc by default if the filename is the same.

**Comment by arcadez** [comment]
Yeah i remember this now i left out some code from the mem map then plain forgot about it, the problem with Power Instinct Legends is it reads some extra ram data and feeds it to the CPU like so...........

AM_RANGE(0x600000, 0x6fffff) AM_READ(MRA16_ROM) AM_REGION(REGION_CPU2, 0)	// extra data ROM space

Connected with the above

	ROM_REGION16_BE( 0x100000, REGION_USER1, 0 )	/* 68000 extra data roms */
	ROM_LOAD16_BYTE( "d15.u4",  0x000000, 0x80000, CRC(6352cec0) SHA1(a54d55b8d642e438158268d0d41880b6589e48e2) )
	ROM_LOAD16_BYTE( "d17.u5",  0x000001, 0x80000, CRC(7af810d8) SHA1(5e24f78a228809a001f3f3372c1b32ea05070e17) )

We cant have that AM_REGION hookup in M78 so im studying some drivers to see how they
handled those sort of reads it seems to be they used some trampolines i'll try and make one 
for our driver and hopefully that will sort the game out.

**Comment by grant2258** [comment]
its still not getting past the character selecttion screen but some gfx show when it freezes looks like your close before it was the ax on the screen

**Comment by grant2258** [comment]
we getting a load of unmapped memory reads

**Comment by arcadez** [comment]
I'll try one last thing if it doesn't work we'll tag the game as not working

**Comment by nemo93** [comment]
Thank you. It works nicely now!

**Comment by arcadez** [comment]
I've tried to sort the background characters once again please give Power Instinct 2 and Legends
a quick whirl to see if i was successful or not :)

**Comment by Wilstorm** [comment]
@arcadez - Everything look ok here, tested on the Pi 3. Here's a few screenshots below.

**Gogetsuji Legends:**
![plegends-180921-174024](https://user-images.githubusercontent.com/8192258/45909169-fa478c00-bdc5-11e8-940d-912fa38b2fd4.png)

**Power Instinct 2:**
![pwrinst2-180921-173611](https://user-images.githubusercontent.com/8192258/45909172-fddb1300-bdc5-11e8-99eb-8551619c9d9d.png)

**Comment by arcadez** [comment]
All good then the background characters are moving.?? thanks for testing BTW

**Comment by grant2258** [comment]
i just checked the bg characters are moving

**Comment by Wilstorm** [comment]
@arcadez - yes they are dancing, singing, playing instruments, swaying. Every scene tested had background movement.

**Comment by arcadez** [comment]
Thanks for letting me know fellas cheers,
