### ISSUE TITLE
[Outrunners] screen issue

### ISSUE THREAD

**Issue by nemo93** [libretro/mame2003-plus-libretro#355]
hi, game does launch at good speed. Yet it appears only to top left quarter of the screen despite having selected only single monitor in dipswitches. Tested on .78 and .78+ (orunners.zip).

Game screen is ok on .139 however it's too slow.

Thank you.

**Comment by arcadez** [comment]
There is an option in the dips to switch the screen to single display either screen A or B
you could do that to get the display full screen, but some folks have reported these dip
settings to not work on the RPI you'll need to try and and see

There is no fix that i can do for this per say i'll leave to the boys that work on RA side

**Comment by nemo93** [comment]
I do confirm that even by using the dips behaviour is the same. As it's RA then I'll close that one.

**Comment by arcadez** [comment]
Check this vid it seems this fella has got Outrunners to work in single screen mode in mame2003

**Comment by grant2258** [comment]
no idea how he done this I recon you would need to force the screen to 4:3 for this to work

**Comment by grant2258** [comment]
you can get this full screen on ra if you do a custom ratio as well

**Comment by SaucySarah** [comment]
I think they are using MAME 2010 or MAME4Droid 139 on Android because they have 'Auto-Frameskip' in the top right of the screen which isn't available in 2003.

**Comment by KMFDManic** [comment]
@nemo93 I personally got this issue resolved awhile back by using Custom Resolution, like in this video:

4:18 Mark

https://youtu.be/cRS_AU8zOwk

**Comment by nemo93** [comment]
Thanks @KMFDManic for the video and follow-up! Much appreciated. I'm closing that one off as it's not related to a bug (issue was with me :)).

**Comment by markwkidd** [comment]
This is a popular game, which I can tell because people regularly post about this single screen issue. I have donated $10 to start a bounty for a proper fix in mame2003 and mame2003-plus.

Here is the issue for the bounty, including the link for others to donate: https://github.com/libretro/mame2003-libretro/issues/155
