### ISSUE TITLE
[TMNT] intro sound issue

### ISSUE THREAD

**Issue by nemo93** [libretro/mame2003-plus-libretro#357]
Another issue that I'm not 100% sure about. It's with first "Turtles" game (either the 4 or 2 players versions). All runs perfect except that the sound of the famous intro music is not there. As far as I recall you can hear it during intro of course but also during the intro scene prior starting the first stage (where turtles come down a building).

Tested on .78 // .78+ and .139 romset.

**Comment by grant2258** [comment]
ill look into this I know it used to be fine

**Comment by arcadez** [comment]
If i mind correctly the music he's talking about comes via the UPD7759

**Comment by grant2258** [comment]
the issue is fixed once the pull request is accepted was the dynamic ost sample loading causing this @KMFDManic  you will need some sort of ost check to fix this in your repo as well

**Comment by nemo93** [comment]
Awesome work. Thank you. If you don't mind I may have a couple more issues to submit. I have a testing romset of nearly ~340 games and except 20 roughly they all work flawlessly on this Mame version. So great and game list keeps from growing! Impressive.
