### ISSUE TITLE
ICS2115 Sound {PGM}

### ISSUE THREAD

**Issue by arcadez** [libretro/mame2003-plus-libretro#368]
The sound in all the PGM games is pretty bad until the MAME boys created a new ICS2115.....

https://github.com/dinkc64/mame/commit/a72a5357884fee391660d33b7cc5368235742929#diff-94a04bad1c8148021999840f961020bc

Unfortunately this new core was in no way compatable with MAME78 and not loving the sound
in the Cave PGM games i decided on spec to check the original sources advancemame ported
the driver from and whatya know it seems the fella who backported the code to get the CavePGM
games to work in ole MAME also updated the ICS2115 :)

But again this ICS2115 sound core was not compatable here so i decided to just take the changes we
needed and kinda like @grant2258 did with the new V60 CPU roll the code back to MAME78 standards
and bingo a huge huge sound improvement for all the PGM games 👍 

The fun didn't stop there however as i lost a whooping 45fps for the games when using the
newly updated sound core  so the usual give with one hand take away with the other :( 
luckely i've pinned down the cause........

static void recalc_timer(struct ics2115 *chip, int timer)
{

//double period = chip->timer[timer].preset* (chip->timer[timer].scale << 16) / 60000000000.0;

double period;
double counter;
	if(chip->timer[timer].scale) 
	{
		int sc = chip->timer[timer].scale;
		counter = (((sc & 31)+1) * (chip->timer[timer].preset+1)) << (4+(sc >> 5));
		//period = 1000000000 * counter / 33868800;
		period = counter / 33868800;
	} 
	else period = 0;

	if(chip->timer[timer].period != period) {
		chip->timer[timer].period = period;
		if(period)
			timer_adjust_ptr(chip->timer[timer].timer, TIME_IN_SEC(period), chip, TIME_IN_SEC(period));
		else
			timer_adjust_ptr(chip->timer[timer].timer, TIME_NEVER, chip, 0);
	}
}

By keeping the old timer code the games get back the fps they lost and now sound and play
rather lovely

static void recalc_timer(struct ics2115 *chip, int timer)
{
	double period = chip->timer[timer].scale*chip->timer[timer].preset / 33868800.0;
	if(period)
		period = 1/62.8206;
	if(period)
		logerror("ICS2115: timer %d freq=%gHz\n", timer, 1/period);
	else
		logerror("ICS2115: timer %d off\n", timer);

	if(chip->timer[timer].period != period) {
		chip->timer[timer].period = period;
		if(period)
			timer_adjust_ptr(chip->timer[timer].timer, TIME_IN_SEC(period), chip, TIME_IN_SEC(period));
		else
			timer_adjust_ptr(chip->timer[timer].timer, TIME_NEVER, chip, 0);
	}
}

**Comment by markwkidd** [comment]
NICE!

**Comment by grant2258** [comment]
very nice job and great explanation

**Comment by Darknior** [comment]
So excellent <3
