### ISSUE TITLE
easy one just want to make sure its not going to effec anything

### ISSUE THREAD

**Issue by grant2258** [libretro/mame2003-plus-libretro#37]
mame2003_plus-libretro.so need renamed to mame2003_plus-libretro.so for retroarch either that or the info file name on retroarch needs updating not sure which one is best to change any thoughts mark

@markwkidd

**Comment by markwkidd** [comment]
Yesterday I submitted a PR to fix the `.info` file to read
`mame2003_plus_libretro.so`
-- it may take a day or two for that change to make it down to the buildbot
but I think this is already done. :)

**Comment by markwkidd** [comment]
https://github.com/libretro/libretro-super/pull/777

**Comment by grant2258** [comment]
that fix is already through we will need to change the makefile name our end to match the new info name

**Comment by arcadez** [comment]
Listen i've not got much experience with the Rpi setup side i freely admit this, can on you
fellas when ya get a spare moment check this over to make sure it hookups correctly with
this core.

im gonna look it over later but i did make a copy of the original mame2003 Rpi setup file
and renamed what i thought to be all relevant core declerations to mame2003-plus but
this was rejected for some reason and if you look at the currant setup file it seems to
just use mame2003 for most of the install paths.

Would this not be incorrect for things like nvram or samples as the paths are named with
a plus prefix in this core

**Comment by grant2258** [comment]
ill have a look when i get in from work just about to leave. It does look ok to install. Ill just need to verify it all on install and see if there is any problems as for the samples cant test i dont have any. Just need a set for one game that works your side to do the rpi setup test.

**Comment by arcadez** [comment]
Im thinking if this could be the problem..?? as it's missing the -plus prefix

md_ret_require="$md_build/$(_get_name_lr-mame2003)_libretro.so"

**Comment by arcadez** [comment]
@grant2258 here are Donkey Kong, Donkey Kong JR and Vanguard with samples...........

https://www.sendspace.com/file/j2tcdq

**Comment by markwkidd** [comment]
I think this issue is close-able?

**Comment by grant2258** [comment]
indeed it is mark
