### ISSUE TITLE
Volume peak on VS (NES Video System) Games

### ISSUE THREAD

**Issue by mistervampi** [libretro/mame2003-plus-libretro#387]
Hello guys

WHen i try to play any VS (NES Video System) Games on the mame2003 or 2003-plus cores on the Switch version of Retroarch the Volume just explodes. I checked the Audio Settings and all are in the normal values ( 0db )

I made a video of the issue with VS Super Mario. 
https://www.youtube.com/watch?v=_3OulgPK4Ik

Hope you can fix it. 

Thanks

**Comment by markwkidd** [comment]
@mistervampi glad to see you here. I noticed that you said this happens with any Vs game -- it's great that you have already been testing this with more than one romset. It might also be a little easier to fix if every one of those games is affected :)

There are about [25 Vs titles that are functional in mame2003-plus](https://github.com/libretro/mame2003-plus-libretro/blob/55c58429bf89cbf0bb6b046583f7b09791862586/src/drivers/vsnes.c#L2773-L2820). Can you give an idea about how many of those you have had a chance to check out? Did you test about 5, 10, etc?

Some preliminary notes for myself or for other coders.

Maybe we could drop the volume across all Vs romsets here: https://github.com/libretro/mame2003-plus-libretro/blob/55c58429bf89cbf0bb6b046583f7b09791862586/src/sound/nes_apu.c#L761

That feels like a bit of a hack though. I'm not familiar with the MachineSound struct yet -- here's where it first appears in the driver: https://github.com/libretro/mame2003-plus-libretro/blob/55c58429bf89cbf0bb6b046583f7b09791862586/src/sound/nes_apu.c#L723

**Comment by markwkidd** [comment]
@mistervampi I've started working on a fix in this PR: https://github.com/libretro/mame2003-plus-libretro/pull/388

I will be mostly away from internet access the next couple of days so I don't have time to compile and test this now but I think the sound levels are probably just too high in the MAME driver meaning that lowering them is possible. To be continued.

**Comment by mistervampi** [comment]
Hello. Thanks for taking they time to check and reply.

Just for the record, i've tested all the VS Games of the 0.78 romset and this issue is present only in the Switch version. 

take your time to fix it.

your work is trully awesome

Thanks!

**Comment by markwkidd** [comment]
@mistervampi there is an attempted fix in the latest nightly version of mame2003-plus which I'd like for you to try. However depending on how the Switch cores are loaded you may have to wait for another RetroArch nightly to be released before you'll be able to download an updated mame2003-plus core if it's like some of the other console RetroArch ports.

In other words I am not familiar with the build process for Switch -- are the cores "statically" bundled with RetroArch so that you have to update RA to update the cores? Or can you update individual cores?

**Comment by mistervampi** [comment]
@markwkidd Hello, Yes i can update individual cores. Is not necessary to apply an entire RA update to update the cores. In fact I've just updated the mame-2003 and mame-2003plus cores from the last nightly build and the issue still present on both updated cores. i'll be waiting for the next nightly build to give a try. i'll keep you informed about the results :)

Thank you.

**Comment by grant2258** [comment]
@mistervampi can you go to setting->audio and tell us what your audio volume level (db) is set too

**Comment by mistervampi** [comment]
@grant2258 Hello. In all my test value in the audio volume level setting is 0 (db)

**Comment by markwkidd** [comment]
What happens if you lower the volume in retroarch below 0db? I'm curious if
the distortion still exists, just at a lower level, or if the distortion
disappears.

**Comment by grant2258** [comment]
@markwkidd Vs mario  uses the one dac not the dual dac so ive put a pull req in to lower that volume

**Comment by markwkidd** [comment]
Ah ok thank you! Merged.

**Comment by grant2258** [comment]
no problems i monitored the db levels from ra in windows and it was reaching clipping levels with cs super mario we are in the green no with that game with the new levels. If we have more issues with sound levels might be best to monitor the levels with audacity

https://manual.audacityteam.org/man/meter_toolbar.html#recording

**Comment by markwkidd** [comment]
@mistervampi could you try the latest nightly version of the core again and let us know?

**Comment by mistervampi** [comment]
@markwkidd Still nothing. The volume keeps exploded :(

**Comment by grant2258** [comment]
@mistervampi  ive put a pull request in for a fix details are here. Im not sure when this is compiled but i looked into it more and have updated some parts of the soundcore to mame 0.80

**Comment by grant2258** [comment]
On another note can you test outrun for debugging this tell me if it does the same thing if it does we might just need to lower the volume by -8db for the switch

**Comment by grant2258** [comment]
this one can be closed too is solved

**Comment by markwkidd** [comment]
@mistervampi I'm closing this issue as fixed as of the mame2003-plus build on 11/22. If you have any other trouble please post again. Thank you for reporting the issue!
