### ISSUE TITLE
LibNX - Large ROM loading failure

### ISSUE THREAD

**Issue by SeongGino** [libretro/mame2003-plus-libretro#389]
## Issue:

MAME 2003 (and MAME 2003 Plus) has issues when loading larger ROMsets sequentially in a single user session (I.E. when loading multiple ROMs without exiting to the system menu). These ROMs are otherwise noted to work as intended when loaded separately across different user sessions.

### Steps to reproduce:

1) Launch a large-size ROM using a MAME 2003-compatible ROMset: examples include mk2.zip, mk3.zip, narc.zip, etc.
2) Either launch another ROM directly thereafter, or close content and launch another ROM from the same ROMset with the same core.

This will end in a system-level crash (Error 2168-0002, a generic LibNX error)

### Steps to reproduce 2:

1) Launch a large-size ROM using a MAME 2003-compatible ROMset: examples include mk2.zip, mk3.zip, narc.zip, etc.
2) Close content and exit RetroArch, returning to the Homebrew Launcher.
3) Load RetroArch again, and load the same or likewise large ROM using a similar ROMset with the same core.

This will end in a RetroArch generic "Failed to load content" error. This will now occur with every subsequent ROM loaded with MAME.

### Tested on:

RetroArch: 1.7.5 (LibNX version)

### Notes:

A workaround exists, by loading the same/like-sized ROMs but alternating between either MAME 2003 or MAME 2003 Plus, depending on the core used directly beforehand, to return to expected behavior. The steps to reproduce above, however, remain applicable.

This only applies to the LibNX version of RetroArch for Nintendo Switch, and is not a core issue acknowledged on other platforms (I.E. x86_64, ARM, etc.). This has been tested using Homebrew Launcher as a system application, meaning RetroArch has a total ~400MB available RAM to use. This issue has been noted since before the official RetroArch for Nintendo Switch release (formerly known as "RetroNX").

**Comment by grant2258** [comment]
please try adding 
run_game_done();
 
to https://github.com/libretro/mame2003-plus-libretro/blob/5154f023c1545b6fae0d8d98d50504a2b314c1e3/src/mame2003/mame2003.c#L1030-L1036

see if your problem goes away if it doesnt ill dig into the code more when i get time

**Comment by grant2258** [comment]
jesu done some testing please remove mame_done and change the code to

**Comment by mahoneyt944** [comment]
@SeongGino do you still experience issues with our latest build. This is quite old.

**Comment by mahoneyt944** [comment]
This is very outdated if you still experience these issue with our current build open a new issue thank you.
