### ISSUE TITLE
Retropie setup file

### ISSUE THREAD

**Issue by arcadez** [libretro/mame2003-plus-libretro#39]
As per trying to sort the broken sample support some Rpi users have reported i think we 
need a proper Rpi setup file for mame2003-plus which is totally seperate from the original
mame2003 core as i suspect the folder paths are not being picked up correctly due
the one we have currently still using some parts of the mame2003 declerations.

I think this looks correct although if someone with more experience is this dept could cast
an eye over it that would be cool thanks.

https://www.sendspace.com/file/xq0102

**Comment by arcadez** [comment]
Alright i've pushed the above file on the Rpi setup side, hopefully this will sort the
samples should the commit be accepted

**Comment by arcadez** [comment]
Ok as i suspected my push has been flagged as not appropriate which is not surprising due
to my lack of experience on that side of things, i still think the samples breakage is on
the Rpi setup side.

Although we cant rule out one of my commits from when i split off this core being the problem
i've been looking over the changes and nothing stands out hence i think it's on the Rpi side
anyway i'll leave it to those more versed in all things Pi to hopefully come up with a better
solution

Regards.

**Comment by markwkidd** [comment]
Can you link to your RetroPie commit that wasn't accepted? Maybe I can help
rewrite

**Comment by arcadez** [comment]
https://github.com/RetroPie/RetroPie-Setup/pull/2359

**Comment by markwkidd** [comment]
@arcadez I have just pushed some changes to `common.c` which I thought would let us figure out a bit more about what is going on with sample loading. However I'm not seeing those new log lines appear at all on my Windows RetroArch rig when I start `dkong.zip` and begin a game.

I will try to come back to this later when I have more time again but I think some logs that show the path and what files are trying to be loaded would be a good addition to the core and will help with this troubleshooting.

**Comment by arcadez** [comment]
@markwkidd sorry to be a pest can you update the retropie setup file once more as 
arcadez needs to be changed to libretro, i'd do it myself but as you know if never ends
well for me whenever i try to commit a change over there :)

**Comment by markwkidd** [comment]
Will do!

**Comment by markwkidd** [comment]
I think this is a great step forward. Also, the user base for this core is
bigger than ever. I think it's going to continue to get more and more
attention

**Comment by arcadez** [comment]
Well in no small part thanks to you surely as being able to create a datfile via the emulator
means it will be far easier for people to round up the correct roms for the extra games this
core supports over and above the original version 

People will love the dat creator as it now makes this core a viable alternative for the average 
user where as before maybe only the hardcore would have attempted to trackdown all the roms
from scratch, plus alotta games now have sound in this core which again is something alotta folks
will like ;)

**Comment by markwkidd** [comment]
And all that happened after grant's mame2003-libretro project came along and demonstrated how close to functional the ol' xml code really was :)

now if I can just lure a veteran libretro dev in to fix the vector antialiasing code then I will retire!

**Comment by Wilstorm** [comment]
I have to agree with Arcadez. It really is a great feature. In other emulators that add new games you need to update the DAT by hand or as Arcadez said track them from scratch because there's no way generate a new DAT with the changes. 

With mame2003_plus_libretro. You can instantaneously generate a new DAT incredibly easy on the fly. The old/original method required the MAME executable being run with parameters from a command line. 

Also these older MAME versions used listdat vs listxml which usually requires a 32-bit machine or it will fail to run. That's a big deal when everything is 64-bit nowadays unless you have an old PC or if you are using VMWare or something to virtualize old OS's.

**Comment by markwkidd** [comment]
Hey @arcadez I think this can be closed now
