### ISSUE TITLE
[Bounty: $50] implement libretro lightgun API 

### ISSUE THREAD

**Issue by markwkidd** [libretro/mame2003-plus-libretro#400]
## Current lightgun support

**MAME 2003-Plus 'supports lightguns' in the following way:**

1. The lightguns must be set in hardware or the operating system to emulate a mouse
2. We rely on undocumented RetroArch behavior that passes mouse input directly to the core even though this core does not implement the mouse input interface
3. MAME 2003-Plus has a lightgun input interface -- however we do not use this MAME code within the core, instead using the mouse input fallback codepath for lightguns

## Resolution

Connect the libretro lightgun API to the MAME 0.78 lightgun OSD API. The overall approach is to implement these features on both sides and normalize input values for MAME use.

MAME:
- osd_lightgun_read

libretro:
- RETRO_DEVICE_LIGHTGUN

**Comment by markwkidd** [comment]
Even though I eventually want to add some bounty money to this issue myself and promote it to people who would be interested, I'm currently focused on hyping the RetroArch integral artwork bounty so this will have to wait its turn.

**Comment by markwkidd** [comment]
Bounty up to $25 -- thanks @TillmanZ

**Comment by grant2258** [comment]
I would do this if i had a lightgun!

**Comment by markwkidd** [comment]
@nayslayer mentioned that they might take a shot at this

(pun intended) 😜

**Comment by markwkidd** [comment]
Bounty up to $50 - thanks @Thatman84!

**Comment by nayslayer** [comment]
Okay, I can probably do that - this seems easy enough - but is there anyone who can assist with testing? I personally don't own a lightgun (never even knew they can work on anything but old CRTs anyway), so anything I do will be (probably tedious) guesswork.

**Comment by markwkidd** [comment]
I think you should be able to configure a mouse as a lightgun via retroarch
and the lightgun api. (Basically the opposite of how the core now
'supports' lightguns internally if they appear to be mice)

If you can't get a mouse to work via the libretro lightgun API in retroarch
then I'll work with you to figure out an alternative.

**Comment by dougan78** [comment]
I am willing to test.  I have 2 light guns. (3 total mice inlcuding the tracbkall).
Mouse 0 Trackball
Mouse 1 Aimtrak 1
Mouse 2 Aimtrak 3

 When I currently test duckhunt on mame 2003+ core I get mouse 0 working fine.  Mouse 1/2 are like they are not hooked up or using the raw mode.  Meaning the cross hair jumps around all over the screen.  Tested setting input to raw/dinput seting the mouse # in input bindings.  None of that works.  Need more info or have instructions let me know

**Comment by nayslayer** [comment]
@dougan78 That's good news. I'll make a crude version for testing by tomorrow. What operating system / platform are you using?

**Comment by dougan78** [comment]
Windows 7 x64.

**Comment by grant2258** [comment]
there is some example code and info i posted here if your interested @nayslayer

**Comment by grant2258** [comment]
im sure this will be easy i would have done it myself if i had a light gun. I cant even help with testing on this one. I cant find any cheap ones either. I havent looked very hard though.

**Comment by dougan78** [comment]
No biggie I will have a go at it later today and post results.  Cheers!

**Comment by nayslayer** [comment]
Thanks, this is something to work with. Please clarify: does the official core track the lightgun position with the setup you tested? You can revert to the official core by going to `Online Updater>Core Updater` menu and tapping the MAME 2003 Plus core.

**Comment by grant2258** [comment]
the mouse or pointer will move two cross hairs in mame2003 + it probably the code that been hacked up somewhere from mame2003

**Comment by grant2258** [comment]
ok looked into it its an ra setup issues all playets are set to mouse index 0 by default

**Comment by dougan78** [comment]
I can retest with with adjusting the mouse index and testing both guns.  Duhh only tested one.  Additionally from my experience if only 1 mouse works all mice control the one mouse typically.  Seeing the other crosshair jumping around erratically was wierd.  Normally if there is a issue with absolute vs relative coordinates I would see the erratic jumping around issues from past experience and testing various other cores for multimouse support.

**Comment by dougan78** [comment]
Let me test again both cores and play with it again and get back to you.

**Comment by dougan78** [comment]
ok, this time, I think i did things a bit better:

Duckhunt Testing Regular Core:

Bind Input Player one Mouse 0 - Trackball
Bind Input Player two Mouse 2 - Gun 2

Gun 1:  Works fine with trackball, can shoot
  
Gun 2: Crosshair all over the place nothing, buttons do nothing


Mame with Special build:


Bind Input Player one Mouse 0 - Trackball
Bind Input Player two Mouse 2 - Gun 2

Gun 1:  Works fine with trackball, can shoot
GUn 2:  Works fine with gun can shoot

Lethalj testing with special core

Bind Input Player one Mouse 0 - Trackball
Bind Input Player two Mouse 2 - Gun 2

Gun 1:  Works fine with trackball, can shoot, no offscreen reload
  
Gun 2: Works fine, can shoot, no offscreen reload

DId notice the crosshair ghosting on the testing mame build from time to time but that looked like a different crosshair as the one I was aiming at was stead.

Hope that helps!

**Comment by 6alileo** [comment]
Is there a special branch of the "special core"? I'd like to test using a mouse as well. I'm working with flyinghead in troubleshooting the lr-reicast core to get mouse to work in RetroPie environment.

**Comment by grant2258** [comment]
the mouse already works in mame2003+ in the retropie environment

**Comment by mahoneyt944** [comment]
@markwkidd  Lightguns work now as far as I know. I think this can be closed.

**Comment by markwkidd** [comment]
I'm going to take a shot at this. I'll post any updates along the way in this issue.

In a nutshell, the job IMO is to connect the libretro lightgun API to the MAME 0.78 lightgun OSD API; implement these features on both sides and normalize input values for MAME use.

MAME:
- osd_lightgun_read

libretro:
- RETRO_DEVICE_LIGHTGUN

**Comment by markwkidd** [comment]
Work is going slow because this effort has led to substantial refactoring of the existing input code. However, I do have a buggy preliminary implementation which gives me reason to believe this will be complete relatively soon.

**Comment by mahoneyt944** [comment]
Nice work, i merged the input updates. The logging looks much better now. The logging needs a good sweeping but this is a great start.

**Comment by markwkidd** [comment]
Update: my WIP implementation seems to be working in all the essential ways although it's incomplete.

At the moment, the PR implements a select-able RETRO_GUN type accessed in RetroArch through the Controls in the Quick Menu. That codepath is a "lightgun only" input mode -- although the libretro concept of a lightgun incorporates quite a few buttons and a dpad so it has coin, start, and a few BUTTONX codes mapped. It's working in the same way that other cores with selectable Lightgun device types work. 

Next I'm going to add lightgun polling to the retropad input device types. From my understanding, we can still poll the lightgun when a retropad is selected, much the same as we can poll the mouse or pointer when a gamepad is in use.

The outcome will be that if someone has a lightgun mapped in their frontend, it should Just Work no matter what input subtype is selected. If they want input exclusively from the libretro lightgun abstraction, they pick the "Lightgun" entry in their Controls menu.

**Comment by markwkidd** [comment]
News!! Lightgun support is now merged into the master branch!

Due to the way that github/bountysource works, this issue closed automatically. I have created a new issue to carry forward with bug reports and other discussion: https://github.com/libretro/mame2003-plus-libretro/issues/1036
