### ISSUE TITLE
Retroarch crashes at core loading

### ISSUE THREAD

**Issue by davernos** [libretro/mame2003-plus-libretro#412]
Hello, I've just installed Retroarch via package installation on Ubuntu 18.04. Downloaded latest mame2003+ source code, compiled it and moved the .so to the core directory. Retroarch now lists the new core, but it crashes when trying to load it.

I've produced logs with: 
`retroarch --menu --verbose >> retroarch.log 2>&1`

But I think its not showing anything relevant.
Any clues?
[retroarch.log](https://github.com/libretro/mame2003-plus-libretro/files/2500836/retroarch.log)

**Comment by davernos** [comment]
Sorry, for some reason github was doing weird things :)

**Comment by grant2258** [comment]
ok first of all this looks like the cause.

[INFO] [Font]: Using font rendering backend: freetype.
Protocol error: bad 3 (Window); Sequence Number 11
 Opcode (20, 0) = GetProperty
 Bad resource 0 (0x0)

are other cores working for you?

**Comment by davernos** [comment]
Yes, Mame2003 is working.

**Comment by grant2258** [comment]
Turn threaded video off and try again this seems like a retroarch issue to me. Are other cores working?

**Comment by davernos** [comment]
This happens when I try to load the core from the main menu. Other cores seem fine.

**Comment by grant2258** [comment]
i have mint installed ill see if its happening there when I get time

**Comment by grant2258** [comment]
@davernos update your assets and core info files and also update the core from the online updater

**Comment by davernos** [comment]
There is no online updater anymore for cores. It's installed/updated via deb packages.

**Comment by grant2258** [comment]
thats not true at all got to the retroarch menu and pick online updater. Its part of RA. you might want to compile RA yourself depending what version you are on latest in 1.7.5

**Comment by davernos** [comment]
Well... have a look at:

https://www.reddit.com/r/RetroArch/comments/85mhos/core_auto_update_is_not_available_on_the_online/

**Comment by grant2258** [comment]
that because your using ppa. I assumed you compiled RA because you compiled the core

read here if you want to keep updated the package way I just compile RA myself and use the online updater. I have no idea if this pa is still supported.

**Comment by davernos** [comment]
Yes, that's what I said on the first post:

> I've just installed Retroarch via package installation on Ubuntu 18.04

I'm trying the snap, it seems a different branch and the core download/update option is available.

Thanks for your help @grant2258 !

**Comment by grant2258** [comment]
no problems at all hope you get your problems solved

**Comment by davernos** [comment]
> if you need help compiling RA let me know

No need, the snap is updated and fully functional. The core is loading perfectly.
Thanks a lot!

**Comment by grant2258** [comment]
no problems at all
