### ISSUE TITLE
Smash T.V., Total Carnage, Cloak & Dagger or other games using the right stick/buttons to fire works incorrectly

### ISSUE THREAD

**Issue by Wilstorm** [libretro/mame2003-plus-libretro#424]
Smash T.V., Total Carnage, Cloak & Dagger and other right stick/button firing games don't work out of the box using the default controller mappings per the Retroarch diagram. All of them fire the same but incorrectly out of the box. It seems to be a mapping issue as they require a remap file to work correctly. I am using RetroPie 4.4.2 on a Raspberry Pi 3. I am using current mame2003-plus from commit 3aa83da.

```
Up = does not fire at all
Down = fires correctly down
Left = fires diagonally up/right
Right = fires left
```

**Comment by Wilstorm** [comment]
@arcadez - Oooops, yes, sorry, make that Smash T.V. :)

**Comment by Wilstorm** [comment]
Updated the proper title and game name guys, sorry I must have Nintendo on my mind.

**Comment by grant2258** [comment]
I know what you meant is fixed please clear your cfg dir again as the offsets have changed ta

**Comment by grant2258** [comment]
https://github.com/libretro/mame2003-plus-libretro/pull/426 when it pulled its ready to test

**Comment by Wilstorm** [comment]
Yeah, I am fine with resetting my cfg's for testing. You want me to delete my default.cfg and rom.cfg after updating? I mapped my 360 exactly like RA's default diagram mappings so the button positions for A, B, X and Y and right stick are mapped to defaults.

If it helps any this issue seems to only effect the 2nd joystick of dual joystick games. It's the exact same issue with 2003, complete with the wrong mappings and firing direction all match the same. A remap fixes the issue there also. I simply change say MAME button 1 = Retropad1 B, vs. A or whatever it's currently mapped to and it's fixed.

**Comment by grant2258** [comment]
well i had a fix but i took note you wanted to use the r stick for certain functions so i have mapped the up down left and right and it for you its not analog at moment will be in future obviously.

**Comment by Wilstorm** [comment]
Yeah you almost need the right joystick to fire, to make it decently playable. If you use buttons you press 1 button for a direction or 2 buttons for an angle, so you're sliding your fingers all around the 4 buttons to play which doesn't work well. The right stick for firing isn't analog just digital directional fire on Smash TV and Total Carnage?

**Comment by grant2258** [comment]
its digital

**Comment by grant2258** [comment]
@Wilstorm https://github.com/libretro/mame2003-plus-libretro/pull/428#issuecomment-433626407

is ready to compile enjoy i could have just added it the way it was but i seen you wanted access to the rstick in mame so i mapped  it for you.

**Comment by Wilstorm** [comment]
Ok thanks good sir, I will update and test to let you know the results. Do I need to wipe out my MAME default.cfg and game.cfg for this to work?

**Comment by grant2258** [comment]
yea I  changed the input settings offesets. 

mame writes these on first run and reads them there in after. If it changes and you dont clear it you get strange mapping. 

This rarely happens ill let you know if this ever needs done in this case it does

**Comment by grant2258** [comment]
smash tv driver looks like it was hacked up

https://github.com/libretro/mame2003-plus-libretro/blob/master/src/drivers/midyunit.c#L310-L335

that will need put back to its original state. The reason the buttons are dancing around changing controller types in RA gampad, 6 pad and 8 button ect this can be fixed and will be ajust test with robotron for now if your happy enough we can remove the hacks

**Comment by grant2258** [comment]
the fix is in a pull request here to fix smash/total car 
https://github.com/libretro/mame2003-plus-libretro/pull/430 

just let us know how you get on with robotron cant see there being any issues. Just dont want more stuff to undo if you have issues. Once your happy with that let mark know

**Comment by Wilstorm** [comment]
Ok, thanks, will do. We are doing our Saturday chores and some honey-do list items. Once finished I'll sit down and do some testing and report back.

**Comment by grant2258** [comment]
no rush just letting you know its ready to test.

**Comment by Wilstorm** [comment]
This is genius sir, it seems to be working perfectly. If you don't delete your ```default.cfg``` or ```game.cfg``` you can manually edit the ```default.cfg```. As for individual ROMs you would need to edit each manually because they aren't inheriting from the ```default.cfg```.

If you delete your ```default.cfg``` and all ```game.cfg``` configs that use the right stick then everything is inherited from ```default.cfg``` as you start each game.

I also tested hotkeys and they are now workable with the right stick as well as NOT mappings. That is a big deal as it opens up a lot more hotkey options and NOT flexibility for games that RA isn't capable of doing.

The only thing, which is minor is players 3 & 4 don't auto fill in neither the left or right stick RetroPad values. Both players have those 8 fields set to NONE.

I have to say this is really impressive you went way beyond just fixing a few RetroPad to MAME mappings so the games fire correctly for dual stick games. You also added in a right stick usage, right stick hotkeys, removed the double inputs and NOT mappings all work, very impressive good sir, wow! :)

**Comment by Wilstorm** [comment]
If people want to utilize these new features they will need to wipe their default.cfg and some of their game configs (those that use the right stick) and then add back in their "other" custom remap settings or manually edit them all by hand but I think it's well worth it either way, truly incredible! ;)

**Comment by grant2258** [comment]
glad its all work as it should ill tell mark to pull the fix for smash and total car

**Comment by grant2258** [comment]
well I seen your comments on the other thread so i thought you could do with the right stick was only a few lines of code

**Comment by grant2258** [comment]
@Wilstorm when you say edit config do you mean mame configs or ra configs its the mame ones that need cleared

romdir/mame2003-plus/cfg

these configs arent standard text files

**Comment by Wilstorm** [comment]
Sorry what I do is delete the default.cfg and let it pull the new settings from RA(?), then I go into the game and any field that has been changed from the default.cfg is highlighted white so I enter on the field and press the left stick left twice to reset the field back to default value of default.cfg and it unhighlights or a few games I just deleted it to reset. I wish you could edit the game.cfg directly.

**Comment by Wilstorm** [comment]
Yeah, it works great here and will close it out.

I didn't directly delete all my cfg's so I may take a quick snap with my phone and go back through to reconfigure the custom settings like pinball on the shoulders or I think I finally settled on a config I really like for Outrun. In the Outrun config it shows button 1, button 2, button 3 and button 4 which are inputs for gas, brake, hi & low. It's not intuitive so taking a phone snap before wiping it out really helps to just go in and reconfigure Button 1 = RetroPad1 B, etc.

I think that's why with 2003 players have some serious complex configs in a hierarchy and wiping them all by deleting everything just isn't an option so they are adverse to development. I read more than one post that flat out said they would be hard pressed to start over if they lost all their work put into their current arcade cabinets. I think these types of changes are worth the effort to go back through and reconfigure everything.

Anyway when you go back and play 2003 it feels so broken to me now. After your update to Offroad it was great to play last week. In 2003 you can only press nitro on a controller. All of these small updates are really starting to add up to put some serious weight on 2003. I am sure at some point it will get phased out or at a minimum the other lesser used emulator! ;)

Thanks again for these wonderful updates! ;)

**Comment by grant2258** [comment]
no problems at all glad its positive feedback 👍. As far as outrun button names go any user can submit button names details are here.

https://github.com/libretro/mame2003-plus-libretro/wiki/Submitting-Button-Names

**Comment by grant2258** [comment]
I believe the only thing that has kept mame2003 back and still is one person not wanting any change at all. I do feel right now once the default keys are decide for mame. 

Ive already posted my thoughts on the two options. I believe the solution for the ipac is set all the keys to none as default the joypads will pick up anyway when you bind the in ra config and add a hotkey enable setting and it will work out of the box.

**Comment by Wilstorm** [comment]
@grant2258 - I read through that doc yesterday after reading Mark's article but I am so green I still can't do it with the write-up. It would have to be a step-by-step example. Then one on how to submit a PR even, I've never done one of those even. I'm a rookie the then Nth degree,

I know who you're thinking of I am sure of it! ;) Yes I did see you offered the analog code in a post to get some of those games working but he doesn't even acknowledge you when you ping him directly. It's sad really when folks just completely ignore posts to issues like that when addressed directly. Even if you're short on time a quick hey, thanks, I see the update/issue and I'll look into it. 

I have nothing against him, I think he's knowledgeable and speaks well about most things and blow smoke on others but I think he let's on he can code more than he really can. I've asked him many times about his coding, I even asked for help in understanding his own code when it came to custom view portals and he would ignore all my questions, even when I was sincere. 

My thought was he was the wing-man to the actual behind the scenes programmer who did most of the work on 'his' script. It was really fancy for a guy just starting in programming. Maybe he did the actual coding, I don't know but he deflects anyone on the forum who ask for updates now which would require pulling "database" information on all games for each core which someone else did for him. The script is 100% reusable and people wish to continue to use it but when FBA updated to .43 (now .44) a new database text file needs pulled. I think to code something you have to understand the issue 100% inside and out so my few questions were so trivial for a short python script and should have been easy to answer. I really wanted to help on the project. It's a long story across many threads across weeks and months.

I think he fully understands the concepts and can navigate Github but he can _not_ do the actual coding on his own beyond the simple. 

He's the only guy that I never could get along with on the forums, It's ok to not know everything but he always did, even when he didn't. I never thought less of anyone who didn't know something ever. I really tried and the rest of the folks are great but alas it's water under the bridge now and I spend very little time there now because of him in all honestly. I miss half the information passing through now but I simply just don't care I guess. Well I do care but I don't know. I just don't care for him I guess and that's ok too. We were never meant to like everyone.

Anyway if he doesn't start doing something at some point this core will be more widely used simply by attraction disregarding any promotion.
