### ISSUE TITLE
outrunners screen

### ISSUE THREAD

**Issue by crazyrexz** [libretro/mame2003-plus-libretro#425]
as it title, outrunners isnt fullscreen , any workaround to fix this? tia

**Comment by grant2258** [comment]
https://github.com/libretro/mame2003-plus-libretro/issues/355

**Comment by markwkidd** [comment]
This is a popular game, which I can tell because people regularly post about this single screen issue. I have donated $10 to start a bounty for a proper fix in mame2003 and mame2003-plus.

Here is the issue for the bounty, including the link for others to donate: https://github.com/libretro/mame2003-libretro/issues/155

**Comment by Wilstorm** [comment]
I tried custom settings filling the screen and centering up the game with a custom viewport but it didn't work for me. I tried these settings below for a 1080p display. Has any been able to get it to work on Plus with that method?

```
aspect_ratio_index = "22"
custom_viewport_width = "1436"
custom_viewport_height = "1080"
custom_viewport_x = "242"
custom_viewport_y = "0"
```

**Comment by arcadez** [comment]
Sega Multi32 games share the same video with System32 check multi32 in vidhrdw system32
there are triggers to handle the monitors maybe those if  !multi32 defines need to be retroarched..??
ya know like how the code was changed for the dcs sound over how it's defined in the original
MAME source.

**Comment by grant2258** [comment]
we can close this one too just waiting for the video code to be pulled in mame2003 and the code has been tested. It working like a charm nayslayer will bring it in himself is on my reop in a branch if anyone wants to test it.
