### ISSUE TITLE
idea: use BIN2C process on rungun.nv

### ISSUE THREAD

**Issue by markwkidd** [libretro/mame2003-plus-libretro#43]
This is a note to myself, but also an encouragement to find any other games that can be made (more) playable by using the nvram loader to bypass some issue like `rungun`.

I think the same process that I used to build `hiscore.dat` into the core binary could be used to build in nvram patches like `rungun.nv` directly into the mame2003-plus source so there is no need to script its deployment or even put a big annoying instruction on the screen like I did for `rungun`.

It will be even easier than `hiscore` because for that file I wanted to keep a 'source' file in the repository and have logic to update what is built into mame2003 in case people add hiscore memory maps for new games. For something like `rungun` it would never be updated, so it can go directly into the source file and removed as `rungun.nv` from metadata/nvram.

bin2c works by processing a binary file into a c-source character array that can be added to any source file. Seems like all I need to do is process `rungun.nv` then add that data to `rungun.c`. Then, unnder the same condition where I have the warning message now (ie no `rungun.nv` found in the libretro save path in a subdirectory called `nvram`) then load the copy of `rungun.nv` that is stored as the array.

From that point on, the users own nvram file called `rungun.nv` will be written to that path as usual with any changes based on their use of the game. In other words, the built-in character array data will only be used the first time the core is executed and only if there is not a nvram file already on disk in that location.

I may be able to modify my `hiscore.dat` code to do this or if not it shouldn't be that much different.

**Comment by grant2258** [comment]
Well it could cause problems depending how the driver works but just make sure it works on a game to game basis

**Comment by markwkidd** [comment]
@SapphireDrew reports that the latest commit is successfully booting into `bubblem` via the new bin2c bootstrap method.

That seems like enough to close this issue for now -- if certain platforms have problems using this method maybe I can set up some `#ifdef` routes but maybe this does in fact work for everyone. Endian issues are the only thing I can specifically even worry about.
