### ISSUE TITLE
feedback on blog post for libretro

### ISSUE THREAD

**Issue by markwkidd** [libretro/mame2003-plus-libretro#431]
Hello all, and particularly @arcadez and @grant2258

Back in June I told twinaphex that I would write a blog post to give an overview of what MAME 2003-Plus is. It has taken me a laughably long time to get to this, but I have a draft now.

If you have time could you take a look at the draft for feedback purposes? Here's the link: https://github.com/libretro/mame2003-plus-libretro/wiki/Introducing-MAME-2003-Plus

Does it do an accurate and exciting job of talking about the main benefits of using this core? The most important thing to know if if there are any errors but I would also like to hear about things that should be added.

I'm also going to ask twinaphex for feedback in order to make sure this is going to be appropriate for libretro.com

**Comment by grant2258** [comment]
the only issues i see is 16 way joysticks should be 8 way its 4 buttons in it but 8 combos possible. xmame should be mame apart from that it all looks good mark.

**Comment by markwkidd** [comment]
Thanks for that catch on the joysticks, I was apparently spazzing out when I wrote that part :)

I've also clarified the xmame bit.

**Comment by grant2258** [comment]
Lol 16 bits is always better than 8!

**Comment by markwkidd** [comment]
For anyone following along, I just fixed about a dozen ugly typos in the draft. I must have been getting tired towards the end of my work yesterday, lol. Now it's in a little better shape!

**Comment by markwkidd** [comment]
Thanks @Wilstorm I think you're on point about the DAT generator. I added two more sentences and a screenshot to the relevant section: https://github.com/libretro/mame2003-plus-libretro/wiki/DRAFT:-Introducing-MAME-2003-Plus#building-correct-romsets

For the life of me I can't find the place where I wrote "MAME 200" or "mame200" instead of "2003". Could you point out exactly where that is? hehe

**Comment by arcadez** [comment]
@markwkidd I just had a quick read through it's a good write up although im not sure
im the leader per say :)

**Comment by markwkidd** [comment]
Thanks for taking a look @arcadez -- 

I am sensitive to wanting to portray your leadership role accurately. I have just updated the draft to use this language:

>This core was first established when arcadez began adding games to a new fork of MAME 2003. In addition to contributions from arcadez, the core has since then benefited from the contributions of new and veteran MAME hackers and backporters.

I'm hoping that feels a little more natural.

FWIW I cannot find my "mame200" typo anywhere so I am going to assume I caught it already in this morning's edits. (?)

**Comment by Wilstorm** [comment]
@markwkidd - The link is no longer pointing to the draft, I'll look through and be more precise if you could link it again?

@arcadez - I was thinking in context maybe something like George "Arcadez" Washington one of the founding fathers, now sits permanently carved on the side of a mountain in the Black Hills forever playing video games with the other founding fathers, until the wind, rain or a big tornado alone erode it, like so or something...

**Comment by markwkidd** [comment]
@Wilstorm sorry, I didn't realize that the wiki wouldn't automatically redirect after a title change: https://github.com/libretro/mame2003-plus-libretro/wiki/Introducing-MAME-2003-Plus

**Comment by Wilstorm** [comment]
@markwkidd - It looks like it's been corrected. It's a nice article, well written! :)

**Comment by markwkidd** [comment]
Shazaam! With only one final tweak, the piece is now published: https://www.libretro.com/index.php/introducing-mame-2003-plus-a-high-performance-libretro-arcade-emulator/

Share it with your friends, share it with your grandma! 😎
