### ISSUE TITLE
Sound issue: Tenchi wo Kurau II: Sekiheki no Tatakai (CPS Changer)

### ISSUE THREAD

**Issue by SumavisionQ5** [libretro/mame2003-plus-libretro#433]
It seems that there are some sound emulation issues. 
1) There is no BGM when selecting a character.
2) When you finish stage 1, all sound is gone. The game gets mute.
Everything goes well with other versions of Warriors of Fate, such wof, wofa and wofj. Only wofch has sound issues.
Hope you can figure it out. Thank you.
Rgds.

**Comment by arcadez** [comment]
Alright i made a slight oversight with the REGION_CPU2 boot values when backporting the romset
hopefully this will sort the sound problems

**Comment by SumavisionQ5** [comment]
Thank you very much for fixing this!
