### ISSUE TITLE
use the frontend to display 'missing samples warning' 

### ISSUE THREAD

**Issue by markwkidd** [libretro/mame2003-plus-libretro#440]
Now that @grant2258 straightened out the logic that was segfaulting with incorrect romsets it got me 
thinking.

Sometime, maybe when I've got a three day weekend, I'd like to see if I can display a MAME UI/visual error message when the romset is wrong in addition to writing an error message to the log. Not a high priority improvement, but it would be cool 🕶 

edit: bparker06 from RetroArch has used the nuklear barebones UI library to add status messages to a different core. I don't remember the details although I think it was a PSX emulator core. I'll try to find out. This is nuklear: https://github.com/vurtun/nuklear

**Comment by markwkidd** [comment]
hehe @grant2258 what do I see when I log into Discord this morning? You are talking about this same concept in #programming

**Comment by markwkidd** [comment]
r5 in the #programming channel mentioned this additional information: 

> bparker used ugui on beetle-psx. I think it writes a message directly to the core's [framebuffer]
https://github.com/libretro/beetle-psx-libretro/tree/master/deps/ugui

**Comment by grant2258** [comment]
well we might just need to adjust our view of the mame ui no point in using something else when mame has it built in.

**Comment by grant2258** [comment]
I do still firmly believe ra should be capable of showing a dialog box with information and a yes/no action maybe im expecting too much but ill implement it like we discussed on #programming for now.

**Comment by markwkidd** [comment]
I just had my mind blown by the news that the libretro API already allows us to display status messages via the frontend. the callback is `RETRO_ENVIRONMENT_SET_MESSAGE` which I'll definitely be looking into for use in this core!

**Comment by grant2258** [comment]
https://github.com/libretro/mame2003-plus-libretro/blob/3701ec3497e8439c28e2d43d59d216ceff255a6e/src/common.c#L1344-L1363

this is where you can add the messages

**Comment by grant2258** [comment]
there is one little request i do have can you leave the log_cb in as well when you update this.

**Comment by markwkidd** [comment]
We should definitely keep log_cb intact.

Note to self: also use the OSD to display brief warning for romsets that are have a status of preliminary, baddump, nodump, or  protection.

**Comment by grant2258** [comment]
Well this reminds me something does need fixed up. Ill tell you how to trigger this segfault make a new empty file call it boom.zip load it up youll get  setfault. 

Now rename this empty zip to wboy.zip load it it will say you have missing roms.  (wboy) is a valid driver name.

Now when we get crash reports im thinking someone could be using a wrong erm set name we dont have. This is next on my todo list. Wont take long to track it down and that and fix that lil sucka.

**Comment by grant2258** [comment]
@markwkidd there is a problem with error since it set bail you dont see it because the core closes down.

 You might want to put a sleep in there for a second or two whatever you think is enough to see the message.

**Comment by grant2258** [comment]
i didnt see any message at all when i made a wboy.zip. Hmmm my notifications might be off for some reason i dont see anything when i press gamefocus  mode i.m using a default config pretty sure i didnt change anything ill have a hunt about might be my end

**Comment by markwkidd** [comment]
When you set a message like this via the frontend it also logs into the console. Can you confirm you see the new code logging a message to the console at least? (I did in my testing before merging the new code)

**Comment by grant2258** [comment]
looks like I did have them off but i just see the failed to load content notification now. That is enough of a hint to be honest will flag the warnings that the important bits

**Comment by markwkidd** [comment]
Alrighty, I've implemented a simple global function to make it about as easy to set a frontend message as it is to use `log_cb`: https://github.com/libretro/mame2003-plus-libretro/blob/29881d6ba74a6d3b5913092ae12b30b568b3e4db/src/mame2003/mame2003.c#L84-L89

I used that function to display a somewhat generic message when there are driver warnings: https://github.com/libretro/mame2003-plus-libretro/blob/29881d6ba74a6d3b5913092ae12b30b568b3e4db/src/usrintrf.c#L2505

Ta-da! Right now it's just one generic message when there are driver warnings. I'm not sure whether it would be any better to include details when there is a limited amount of space.
![screenshot 2018-12-10 15 05 56](https://user-images.githubusercontent.com/19554678/49758749-c164d800-fc8d-11e8-9cfe-03390a7b354c.png)

**Comment by grant2258** [comment]
how do you disable serialization mark at least this gives users some feedback hopefully is isint turned off when people set the skip warnings ect!

**Comment by markwkidd** [comment]
@grant2258 here's the current serialization approach: https://github.com/libretro/mame2003-plus-libretro/issues/175#issuecomment-390328928

Because our driver declarations don't have the serialization metadata like more recent MAME, all I know to do is add it to drivers where we know there are problems. Basically the same situation as the controls.c where the serialization metadata would need to be enabled driver-by-driver.

**Comment by markwkidd** [comment]
@grant2258 do you know a good place to hook in a warning **if the romset supports audio samples, but no samples are found**? At first readthrough I didn't see a good spot.

**Comment by grant2258** [comment]
https://github.com/libretro/mame2003-plus-libretro/blob/8dff23b3a58809e29794f9de2e6f37e29aa54cd0/src/common.c#L447

set a flag here then clear the flag on print else it will make a message for every sample missing

**Comment by markwkidd** [comment]
Thanks @grant2258 I've just merged a PR that lets me close this issue! Woo! https://github.com/libretro/mame2003-plus-libretro/pull/541

Of course if more frontend messages are needed more can be added!

**Comment by grant2258** [comment]
nice work! i dont see any games marked with GAME_DOESNT_SERIALIZE ?

**Comment by grant2258** [comment]
im off to bed myself left some info for you in ra got the games i know of crashing running
