### ISSUE TITLE
Counter Run crashes on launch

### ISSUE THREAD

**Issue by Wilstorm** [libretro/mame2003-plus-libretro#441]
Counter Run (countrun) seems to crash on launch. Adding credits doesn't seem to change anything. I am also able to get into the TAB menu/dip switches but there's not much in there. Here's a screenshot below of what the game looks like on launch.

![countrun-181030-170654](https://user-images.githubusercontent.com/8192258/47753786-bec29c00-dc66-11e8-8c61-223330a84055.png)

**Comment by Wilstorm** [comment]
Nevermind sirs, I found the working bootleg. Thanks! The original and Boot Leg Set 2 crash but Bootleg Set 1 is working.

**Comment by arcadez** [comment]
Updated the changelog to mention only the set 1 bootleg is playable

**Comment by Wilstorm** [comment]
@arcadez - Thanks and thanks for the tip on the game. It's a nice upgrade to Head On! I'm not sure what it is about those type of game I find good fun! I've also found Arcadeitalia very useful too.
