### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by robertvb83** [libretro/mame2003-plus-libretro#449]
@markwkidd @grant2258 Today i could not get updating from source to finish successfully... it stops at some point with no end
![20181103_232140](https://user-images.githubusercontent.com/36081149/47957918-be583700-dfbf-11e8-82f5-7c110a3111f9.jpg)

**Comment by grant2258** [comment]
pi ? try clean your source dir and go again

**Comment by grant2258** [comment]
is compiling fine on the pie for me just finished .

![ok](https://user-images.githubusercontent.com/6128601/47958208-b77cf480-dfbe-11e8-8f87-07cd349c0018.png)

**Comment by robertvb83** [comment]
Yes i am running on pi... i deleted the source and updated again.... over night it did not finish.This morning i tried again and it worked... to me this is a mystery. This is a computer, how can this depend on luck?Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: grant2258 <notifications@github.com> Datum: 04.11.18  00:18  (GMT+01:00) An: libretro/mame2003-plus-libretro <mame2003-plus-libretro@noreply.github.com> Cc: robertvb83 <robertvb@gmx.de>, Author <author@noreply.github.com> Betreff: Re: [libretro/mame2003-plus-libretro] Does not compile (#449) is compiling fine on the pie for me just finished .


—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/libretro/mame2003-plus-libretro","title":"libretro/mame2003-plus-libretro","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/libretro/mame2003-plus-libretro"}},"updates":{"snippets":[{"icon":"PERSON","message":"@grant2258 in #449: is compiling fine on the pie for me just finished .\r\n\r\n![ok](https://user-images.githubusercontent.com/6128601/47958208-b77cf480-dfbe-11e8-8f87-07cd349c0018.png)\r\n"}],"action":{"name":"View Issue","url":"https://github.com/libretro/mame2003-plus-libretro/issues/449#issuecomment-435628390"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/libretro/mame2003-plus-libretro/issues/449#issuecomment-435628390",
"url": "https://github.com/libretro/mame2003-plus-libretro/issues/449#issuecomment-435628390",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [libretro/mame2003-plus-libretro] Does not compile (#449)",
"sections": [
{
"text": "",
"activityTitle": "**grant2258**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@grant2258",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"libretro/mame2003-plus-libretro\",\n\"issueId\": 449,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"libretro/mame2003-plus-libretro\",\n\"issueId\": 449\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/libretro/mame2003-plus-libretro/issues/449#issuecomment-435628390"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 406069152\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by grant2258** [comment]
type dmesg to stop any errors. The only think ive see causing problems on a pi with compiling is a sdcard going bad and overclocking too high
