### ISSUE TITLE
todo mame ui clear key_behavior choice

### ISSUE THREAD

**Issue by grant2258** [libretro/mame2003-plus-libretro#451]
see topic here .

to me what we have is the correct behavior ie it sets it do default. 

When you select a new key it changes and to get your default back you just do the magic key press.

Some people want it to set to none which makes the point of having defaults useless to me its a great feature you can change it or get the default back. If you want it TO set  none you should be setting your general default to none.

**Comment by grant2258** [comment]
just for reference i tried this in mame078 the behavior is identical

**Comment by grant2258** [comment]
@markwkidd the code change to set input(this game) to none are here I still can see a real use for it but the team can decide what they are going to do. 

https://github.com/grant2258/mame2003-plus-libretro/commit/5026078816fcc6e2f1ee6a68ca710f8f937d3e2a

**Comment by markwkidd** [comment]
As you know I've posted in the retropie forum thread, although I should probably post again there. I'm not all that excited about this change.

It seems like with this change you basically "lose" access to the default once you customize a game, and once the default is gone you have no way to get back to it from within the core unless you remember what it was or research the answer.

One way that I could imagine the MAME remapper UI being better would be if it had a command at the top of the mapping submenu that resets the mappings back to default. I might be interested in adding a `Reset All to Defaults` action at the top of the menu like that as an alternative to my `Delete current CFG` concept.

**Comment by grant2258** [comment]
it can be a core option or you can put a toggle in the code im still waiting on solid information on this

**Comment by markwkidd** [comment]
Somehow that conversation got off on the wrong foot, but I too would like to know more.

Right now I can't see a situation where the `None` mapping would be needed except as a workaround to a bug but I am willing to believe. I need to reread the thread but I put my energy for now into Dip Switches I think.

**Comment by grant2258** [comment]
i believe mark will be taking care of this when he get the time. ill close for now since its more a todo thing now
