### ISSUE TITLE
ui_text.c and ui_text.h issue

### ISSUE THREAD

**Issue by grant2258** [libretro/mame2003-plus-libretro#452]
enums and structure do not line up properly

https://github.com/libretro/mame2003-plus-libretro/blob/dbb1bc2af35abaf583c821d5e7e54ba1dddd24dc/src/ui_text.h#L15

https://github.com/libretro/mame2003-plus-libretro/blob/dbb1bc2af35abaf583c821d5e7e54ba1dddd24dc/src/ui_text.c#L17

**Comment by grant2258** [comment]
nmi is all good i acctually checked it 

UI_mame, MAME
UI_copyright,        ----- Copyright Warning -----
Copying game data without permission is forbidden by copyright law. If you are not entitled to emulate this system, please exit now.

UI_returntomain, Return to Main Menu
UI_returntoprior, Return to Prior Menu
UI_anykey, Press Any Key
UI_on, On
UI_off, Off
UI_NA, NA
UI_OK, OK
UI_INVALID, INVALID
UI_none, (none)
UI_cpu, CPU
UI_address, Address
UI_value, Value
UI_sound, Sound
UI_sound_lc, sound
UI_stereo, stereo
UI_vectorgame, Vector Game
UI_screenres, Screen Resolution
UI_text, Text
UI_volume, Volume
UI_relative, Relative
UI_allchannels, ALL CHANNELS
UI_brightness, Brightness
UI_gamma, Gamma
UI_vectorflicker, Vector Flicker
UI_vectorintensity, Vector Intensity
UI_overclock, Overclock
UI_allcpus, ALL CPUS
UI_historymissing, History not available
UI_leftarrow,
UI_rightarrow,
UI_uparrow,
UI_downarrow,
UI_lefthilight,
UI_righthilight,
I_knownproblems, There are known problems with this game:
UI_imperfectcolors, The colors aren't 100% accurate.
UI_wrongcolors, The colors are completely wrong.
UI_imperfectgraphics, The video emulation isn't 100% accurate.
UI_imperfectsound, The sound emulation isn't 100% accurate.
UI_nosound, The game lacks sound.
UI_nococktail, Screen flipping cocktail video is not supported by MAME 2003 for this title. If your frontend implements the libretro Shader API, an appropriate mirrored cocktail video shader may be available.
UI_brokengame, THIS GAME DOESN'T WORK PROPERLY
UI_brokenprotection, The game has protection which isn't fully emulated.
UI_no_serialization, This game does not have libretro serialization support.
UI_workingclones, There are working clones of this game. They are:
UI_typeok, Type OK on Keyboard, or Left, Right on Joystick to continue
UI_inputgeneral, Input (general)
UI_dipswitches, Dip Switches
UI_analogcontrols, Analog Controls
UI_calibrate, Calibrate Joysticks
UI_bookkeeping, Bookkeeping Info
UI_inputspecific, Input (this game)
UI_gameinfo, Game Information
UI_history, Game History
UI_resetgame, Reset Game
UI_generate_new_xml_dat, Generate Alternative XML DAT
UI_generate_old_xml_dat,   Generate XML DAT
UI_returntogame, Return to Game
UI_cheat, Cheat
UI_memorycard, Memory Card
UI_keyjoyspeed, Key/Joy Speed
UI_reverse, Reverse
UI_sensitivity, Sensitivity
UI_tickets, Tickets dispensed
UI_coin, Coin
UI_locked, (locked)
UI_loadcard, Load Memory Card
UI_ejectcard, Eject Memory Card
UI_createcard, Create Memory Card
UI_loadfailed, Failed To Load Memory Card!
UI_loadok, Load OK!
UI_cardejected, Memory Card Ejected!
UI_cardcreated, Memory Card Created OK!
UI_cardcreatedfailed, Failed To Create Memory Card!
UI_cardcreatedfailed2, (It already exists ?)
UI_carderror, DAMN!! Internal Error!
UI_enablecheat, Enable/Disable a Cheat
UI_addeditcheat, Add/Edit a Cheat
UI_startcheat, Start a New Cheat Search
UI_continuesearch, Continue Search
UI_viewresults, View Last Results
UI_restoreresults, Restore Previous Results
UI_memorywatch, Configure Watchpoints
UI_generalhelp, General Help
UI_options, Options
UI_reloaddatabase, Reload Database
UI_watchpoint, Watchpoint
UI_disabled, Disabled
UI_cheats, Cheats
UI_watchpoints, Watchpoints
UI_moreinfo, More Info
UI_moreinfoheader, More Info for
UI_cheatname, Name
UI_cheatdescription, Description
UI_cheatactivationkey, Activation Key
UI_code, Code
UI_max, Max
UI_set, Set
UI_conflict_found, Cheat conflict found: disabling
UI_no_help_available, Help not available yet
UI_watchlength, Number of bytes
UI_watchdisplaytype, Display Type
UI_watchlabeltype, Label Type
UI_watchlabel, Label
UI_watchx, X Position
UI_watchy, Y Position
UI_watch, Watch
UI_hex, Hex
UI_decimal, Decimal
UI_binary, Binary
UI_search_lives, Lives (or another value)
UI_search_timers, Timers (+/- some value)
UI_search_energy, Energy (greater or less)
UI_search_status, Status (bits or flags)
UI_search_slow, Slow But Sure (changed or not)
UI_search_speed, Default Search Speed
UI_search_speed_fast, Fast
UI_search_speed_medium, Medium
UI_search_speed_slow, Slow
UI_search_speed_veryslow, Very Slow
UI_search_speed_allmemory, All Memory
UI_search_select_memory_areas, Select Memory Areas
UI_search_matches_found, Matches found
UI_search_noinit, Search not initialized
UI_search_nosave, No previous values saved
UI_search_done, Previous values already restored
UI_search_OK, Restoration successful
UI_search_select_value, Select a value
UI_search_all_values_saved, All values saved
UI_search_one_match_found_added, One match found - added to list
UI_last_mame_entry

**Comment by markwkidd** [comment]
hehe one time near the beginning of my time working on mame2003 I really did get these two structures out of alignment and I didn't realize it since I hadn't done `make clean` so I was thinking "oh no, I've done it again"

I'm going to be settled in Seattle starting tomorrow so I will have to catch up on all of the planning and testing that has been going on lately. You've been keeping busy again, exciting to see alerts popping up

**Comment by grant2258** [comment]
yea wanted something tested then it got blured into a tab menu feature so that went out the window
