### ISSUE TITLE
possible regression for Armv7 CortexA7 / (S)NESC platform

### ISSUE THREAD

**Issue by markwkidd** [libretro/mame2003-plus-libretro#454]
I'm creating this issue to have a place to follow up on a preliminary report from @Swingflip about a performance difference between mame2003 and mame2003-plus for the Nintendo Classic consoles.

The original post is in this PR from the other repo: https://github.com/libretro/mame2003-libretro/pull/390

Swingflip wrote:
> ...I did a similar thing for mame2003+ but performance was poor during testing so I wanted to recheck compilation flags before PR. Message on discord and we can chat about it if you wish 👍🏻

@swingflip I've heard something from @KMFDManic regarding a performance regression in mame2003-plus that may be related, but right now we don't have a test case isolated to begin the troubleshooting process.

**Comment by swingflip** [comment]
Worked out the issue, not related to the core. 

Issue can be closed as invalid.

**Comment by markwkidd** [comment]
Good working with you, come back anytime! :)
