### ISSUE TITLE
Weird graphics issue with Metal Slug 2 or 3

### ISSUE THREAD

**Issue by raidenii** [libretro/mame2003-plus-libretro#455]
Trying to emulate Metal Slug 2 and 3 with mame2003-plus, however the graphics only takes half of the screen, as the screenshot shows. Also the palette is wrong. However, there is no issue with MS1, 4 or 5 - didn't test X.
![mslug3](https://user-images.githubusercontent.com/2512813/47969505-ae376a80-e046-11e8-95a0-d8306affdd3a.png)
And the debug log:
[ralog.txt](https://github.com/libretro/mame2003-plus-libretro/files/2546272/ralog.txt)

**Comment by grant2258** [comment]
can you update mame2003+ your not on the latest and report back

**Comment by raidenii** [comment]
Same.
![mslug3](https://user-images.githubusercontent.com/2512813/47969566-577e6080-e047-11e8-9202-dc288eac0317.png)

**Comment by grant2258** [comment]
i need to get the neogeo bios

**Comment by raidenii** [comment]
It's fully merged set, but I can separate the bios out...
[neogeo.zip](https://github.com/libretro/mame2003-plus-libretro/files/2546291/neogeo.zip)

**Comment by grant2258** [comment]
no no i needed to get the bios myself sorry i `wasnt clear yes there is  a problem with mslug2 mslug3 and mslug3n thanks for the report!

**Comment by srk15372** [comment]
Hi, the same problem on different neo geo games, the graphics takes half of the screen.
I have rebuilded a perfect set with last dat files and clrmamepro (0 missings with separates bios).
strange behaviour
thanks

**Comment by grant2258** [comment]
can post the games please

**Comment by raidenii** [comment]
Also happen on kof99, samsho3 and samsho5. Other kofs and samshos work fine.

**Comment by srk15372** [comment]
I only test art of fighting  I will test others games  thanks

**Comment by grant2258** [comment]
@arcadez its not the driver it works fine here. 

Its possible the button mapping or nvmapping macro changes in the driver definitions at a guess

**Comment by grant2258** [comment]
its the vector changes here that broke it

065c96db833dbc2533138255e75bbf028dfd6a25

**Comment by grant2258** [comment]
pull request to fix this is in thanks for the reporting the issue

**Comment by grant2258** [comment]
@markwkidd this fix is needed for 2003 as well

**Comment by arcadez** [comment]
Hmm i wonder how many more games got broken due to the vector graphical changes..??
i guess we'll never know good work @grant2258 putting this right, this was a bounty fix
wasn't it.?? ya should claim it back :)

**Comment by grant2258** [comment]
not interested in cash this a my lil hobby

**Comment by arcadez** [comment]
Yeah i know bigman same here im not interested moneywise either, but i suppose if you take on a
bounty you have to make sure your code changes dont fuck up other games in the process :)

**Comment by raidenii** [comment]
Thanks for the efforts! Will test once the buildbot updates (I'm too lazy to compile myself)

**Comment by raidenii** [comment]
All good, thanks for the quick fix!
