### ISSUE TITLE
Killer Instinct - Low FPS

### ISSUE THREAD

**Issue by purplesanz** [libretro/mame2003-plus-libretro#458]
Whenever an FMV is displayed or one of the top of buildings stages rotate at the beginning of a match, the FPS drop to 40s. Also, during any match (or whole game overall), even when the FPS counter stays at 60, the framerate feels choppy compared to any other MAME core. Framerate also drops when a fireball breaks into sparks.

Service mode is also broken. Some options cannot be set, and fps go too fast when trying to set the volume in-game.

**Comment by markwkidd** [comment]
Thank you for taking some more time to document the issue for us. (For other folks, this started as a forum thread here: https://forums.libretro.com/t/mame-2010-2nd-player-remap/16025)

Bringing over my notes from that thread:

* purplesanz already tested Killer Instinct in MAME 0.78 which I understand from the forum post has some or all of the same timing issues.
* There was a timer fix in 0.116u4.

**Comment by grant2258** [comment]
the dcs hack isint implement on our end if fixed it on mame2003 though so test the dcs hack on that and let us know

**Comment by markwkidd** [comment]
I'm looking at the MAME 0.80 source right now.

this caught my attention
> 0.79u2: Replaced Custom sound with DMA-driven DAC.

**Comment by markwkidd** [comment]
I'm looking at the MAME 0.80 source right now.

this caught my attention
> 0.79u2: Replaced Custom sound with DMA-driven DAC.

**Comment by arcadez** [comment]
That's a whole different soundcore hint it's slower, i'll happily bet both Killer Instinct games will
nosedive in performance if you hook em to it MK2 and MK3 certainly would.

**Comment by markwkidd** [comment]
Hm.. For what it's worth the OP mentioned in the forums that Killer Instinct runs at full speed on their system via MAME 2010. Although it has some controls issues for P2 in MAME 2010 so that's when this discussion began about how it performs worse in MAME 2003-Plus than it does in MAME 2010, at least for this setup.

**Comment by grant2258** [comment]
what is his setup ?

**Comment by markwkidd** [comment]
@grant2258 sorry I made some noise in the thread.

Are you asking @purplesanz to try Killer Instinct in the regular MAME 2003 core, and disable the DCS Hack core option when doing the testing?

**Comment by arcadez** [comment]
Well for starters MAME 2010 wont have the DCS speedup's so as @grant2258 suggested find out
the setup he's using and mention to him to try disabling and enabling the speedups to see if
it makes any difference to the performance

**Comment by grant2258** [comment]
@markwkidd yes has to be mame2003 is just defined at compile time for us. if it makes a difference ill fix it here so it toggles with the core option, The shadows go on and off in mk2  active/disabled

**Comment by arcadez** [comment]
You know i am struggling to see why the Killer Instinct games could be slower in this core vs Mame 2010
i mean for starters we have the faster CPU's, timer code, and memory handlers add to that the DCS
speedups plus the games have speedups of their own and are using the fastest MIP's settings.

If there was a change to disable the dcs speedups by default then maybe if he turns em on that
will solve the problems, if not we can look at the timer changes it'll be both the driver and the 
CPU though that will need to be altered.

**Comment by grant2258** [comment]
You know i hope he isint on a pie and expecting a miracle

**Comment by purplesanz** [comment]
> what is his setup ?

I'm sorry. i3-3220 @3.30 GHz, 8 Gb RAM, GTX 660.

> You know i am struggling to see why the Killer Instinct games could be slower in this core vs Mame 2010

Believe me, so am I, but trust me, they are.

**Comment by grant2258** [comment]
im wondering if this could be file access speed issues game history loading takes a fair bit of time on my ssd for the libretto port. Less than a second on mame078 itself

**Comment by purplesanz** [comment]
UPDATE: I got rid of some of the slowdown by disabling Hard GPU Sync in RetroArch. I have no idea why, but seems like MAME 2003 and MAME 2003 Plus are the only two cores that won't play nice with Hard GPU Sync, which is weird, since I use it with every other core (including MAME 2010, MAME 2014 and MAME 2016) in order to achieve less input lag, and I never had any issues with it before.

Ok, that took care of the huge FPS drop when playing FMVs and when fireballs break into sparks, I don't know if the core is intended to work that way (without Hard GPU Sync), in which case, I'm sorry, my bad.

However, the framerate difference is still there and it is VERY noticeable. I wish I could show you, is it possible to upload videos here?

**Comment by purplesanz** [comment]
> Could you download normal mame078 @purplesanz and see how it runs there if it is faster

It is not, I tried that already. It is actually cool that you mention Progetto Snaps, since they have a very clear example of what I'm talking about:  [http://www.progettosnaps.net/videosnaps/mp4/kinst.mp4](url)  See what happens when the stage is rotating at the beggining of the match? That's exactly what happens in MAME 0.78b and both MAME 2003 & MAME 2003 Plus cores, and I know it is not very noticeable in the video, but the overall speed of the game is not accurate, feels as if it was running at 40 - 45 FPS when compared to MAME 2010 (or any newer version).

**Comment by arcadez** [comment]
Ok if this indeed was the fix then there will be a problem implementing it here............

0.116u4: Fixed timer_set in the MIPS core and Kinst driver [Zsolt Vasvari].

from mips3.c and mips3drc.c

/* due to accuracy issues, don't bother setting timers unless they're for less than 100msec */
	if (compare_mame_times(newtime, MAME_TIME_IN_MSEC(100)) < 0)
		mame_timer_adjust(mips3.compare_int_timer, newtime, cpu_getactivecpu(), time_zero);

This code is designed to work with the mame timer handling from after the big CPU and mem
changes during the later MAME78 dev cycle, compare_mame_times is not a part of our 
core setup.

i doubt it could be added to our cpuexec.c and timer.c without updating the whole timer handling 
and since every CPU and driver would be affected it's not a road i wanna travel down, plus as a kicker
it would make this core slower anyway.

**Comment by arcadez** [comment]
Well it's playable barring a drop in fps here and there, xbox users would have killed to get 45fps
for the Killer Instinct games then again maybe not :)

**Comment by purplesanz** [comment]
> @purplesanz do you know what the most recent libretro MAME core you have access to that can run Killer Instinct at full speed?

That would be MAME 2016 without Hard GPU Sync or any Frame Delay, which sucks for input lag. That's why I love how it performs in MAME 2010, with Hard GPU Sync ON and Frame Delay 5 the input lag is almost not noticeable, and FPS won't drop at all, it's perfect.
MAME can also run it at full speed most of the time, it is just that moment when the game makes a transition from an FMV to a match, that the audio stutters and crackles like crazy (same thing happens with MAME 2016 when Hard GPU Sync is on).

**Comment by markwkidd** [comment]
I've just been having some **Killer Instinct Chat** ™️ with @barbudreadmon who was saying that `kinst` tops out at about 40fps with this core even with very fast hardware:

> i tried kinst with mame2003-plus on my pentium n3710 (turboed at 2.56Ghz), it was barely running at 40 fps iirc
> which is still faster than with fba on my i7

I don't have any real point in adding this to the discussion except as another datapoint

**Comment by grant2258** [comment]
have you checked the cpu load when running the game on a i7 ?

**Comment by barbudreadmon** [comment]
@grant2258 that was a test with the mips3 standard interpreter in fba (the x86_64 dynarec runs at full speed), this is preliminary emulation stuff currently, and yeah my cpu was at 100% :)

**Comment by grant2258** [comment]
is the mame Dynamic Recompiler  your using or another one ?

**Comment by barbudreadmon** [comment]
No, it was written by a fba developper, afaik there is no "pure" mips3 dynarec for x86_64 in mame, just the old x86_32 one, and the more recent "UML" one.

**Comment by Panderner** [comment]
I heard killer instinct runs full speed on Pentium 4 PCs using older versions of Mame but it lacks mips3 arm dynarec. it may be slow for all Android Devices even a snapdragon 855+

**Comment by bluestang2006** [comment]
On an overclocked Pi 4 the exact description by the OP occurs. The slowdowns at those specific instances are exactly the same. 

If you also disable sound altogether, the game plays way too fast. 

It seems like the Pi 4 is capable (overclocked). I’d be willing to throw in a bounty if this is achievable.

**Comment by mahoneyt944** [comment]
#1100 takes this discussion further. Moving this issue there, also added CPU clock scale core option to help increase performance

**Comment by Panderner** [comment]
But how about ARM CPUs?

**Comment by mahoneyt944** [comment]
You'll have to expand your question a bit. But we added a new core option "CPU clock scale" which allows you to modify the clock speed of the emulated state. This has shown promise of increasing about 15 fps or so but requires tinkering to get a setting that works on your specific platform. For most cases the default setting should be used but if your looking to pull a few more fps this may be the key. For me I find a setting of about 40 to 60 yields the best results on my arm based platform.

**Comment by maxmag-soft** [comment]
Using Xiaomi Mi 9, Snapdragon 855 (ARMv8), Retroarch Plus APK, 1.10.3 Mame 2010 (0.139 932e6f2) core,
Loaded Killer Instinct 2
FPS is slow ingame, on the intro, and the sound is stuttering all the time.
Can this issue be related to this behavior that I am reporting?

Killer Instinct 1 plays nicely, with minor drops during gameplay

**Comment by mahoneyt944** [comment]
This repository is for mame2003-plus not mame2010, so I can't comment on the performance of mame2010. This core should be less demanding in general so I would recommend it over mame2010 in that regard. Altering the clock speed isn't exactly a magic fix, but can yield a slightly better experience. I would consider that option experiential for the tinker-er type of user
