### ISSUE TITLE
cheat-related controls issue

### ISSUE THREAD

**Issue by grant2258** [libretro/mame2003-plus-libretro#464]
There was a post on the froums about these games. I did ask for peoples setup which i never got but looked it up myself in the end.

What is happening this is a dual joystick games but a hack has been added for single joystick control. 

The problem we have is mame Lstick and the mame p1 joystick both point to the dpad and the hack will mess with dual stick control although the game seemed to up down left right fine just using the dpad itself.

possible solutions

1) add a option to set input to none in the tab menu

2)  map the lstick in and use the analog l/r stick for dual joystick games

3) remove the single player hack

2 isint a real viable option if you where using and arcade panel you would have the same problem

1 setting the key to none is an option on the table but not a real long term solution for the average RA user that doesnt want to read  the book of setting up mame controls

to me removing the hack and leaving the driver like it should be is the right solution here. 

Even though i think this is the solution for this game.  The mapping the lstick for digital use and the adding the set to none aren't off the menu thats something that can be decided separately form this issue

**Comment by grant2258** [comment]
ok ive been digging in a big more and found on the original mame78 the only way the p1 up/down/left/right activates to any binding is when you start with mame with the -cheat on the command line. It seems to always be activated on out port. So it would only have this problem if you had cheats on. 

https://github.com/libretro/mame2003-plus-libretro/blob/240ef74756167e9d6bfc5821b10391f05f5eaded/src/drivers/namcos2.c#L1372-L1378

now here is the effect of this in our dipswitches
https://pastebin.com/hdk7vrMx

now here is the controls that could be effected 
https://pastebin.com/TXmR15Zm

My suggested remedy it return the cheat on off as an option in the core options and remove any hacks if any are related to this change.

**Comment by grant2258** [comment]
commit that changed the input ports behavior https://github.com/libretro/mame2003-plus-libretro/commit/fabdfac34c219ae9ccea191ab4d45d30c2f9d69c#diff-c7698bf8bb6ee8a6035a02a296c7a9b4

**Comment by grant2258** [comment]
i would help if i pointed you in the diff direction sorry about that

 https://github.com/grant2258/mame2003-plus-libretro/commit/439ac137c7aa7f6429b409c124fa5dd2266429f1

**Comment by grant2258** [comment]
@markwkidd the pull request is in to fix this. 

All the relevant information is here a condition on the cheat ports input  ports wasn't checked was all. This could effect many games and its dealt with at the level that fixes the problem. It has the potential to mess with many games. 

https://github.com/libretro/mame2003-plus-libretro/pull/465

**Comment by grant2258** [comment]
@markwkidd this should go to mame2003 as well when as is or as a core option

**Comment by markwkidd** [comment]
@grant2258 the cheat engine is one of those areas of MAME input which I never paid much attention to, which has come back to bite me.

Do I understand one of your posts to say that it would be possible to remove the cheats from the .dat file which affect input mapping, and therefore avoid this issue altogether?

Is it possible to figure out which games have such cheats. I'm browsing around in the `cheat.dat` right now but I don't see that there is necessarily a keyword I can search for.

**Comment by grant2258** [comment]
The issue is fixed ill explain it when I get in from work. It's nothing to with the cheats

**Comment by grant2258** [comment]
Ok going to try keep this simple when you updated the cheat system you inadvertently always mapped the extra dip switches (that i knew about) and input (that i didnt know about).

lets look at the assault example here is the input code

https://github.com/libretro/mame2003-plus-libretro/blob/a3ebe179ad617e68028e83ada86fe91a42c97afd/src/inptport.h#L131-L133

This is the part your looking at that caused a problem

https://github.com/libretro/mame2003-plus-libretro/blob/a3ebe179ad617e68028e83ada86fe91a42c97afd/src/inptport.h#L131-L133

PORT_BIT( 0x08, IP_ACTIVE_LOW, IPT_JOYSTICK_RIGHT | IPF_CHEAT )

dip switches or any other type of ports will be added when you enable the mame cheat system.

now I didnt want to re introduce the options.cheat variable in case it had any effects on the code you changed a while back I even left a comment in the pull request.

here is the part of the you changed 

https://github.com/libretro/mame2003-plus-libretro/blob/f0f794c577bd0492f6143328109704e79e68cc5f/src/inptport.c#L1840

https://github.com/libretro/mame2003-plus-libretro/blob/f0f794c577bd0492f6143328109704e79e68cc5f/src/inptport.c#L1847

it was originally 

if ((in->type & IPF_UNUSED) || (!options.cheat && (in->type & IPF_CHEAT)))

that was changed to 
if ((in->type & IPF_UNUSED) )

now you can see what happening here its added an extra joystick input. Both the dpad and 8 way are mapped to the same thing. 

This is not an original input port of the game so what happened there is we bind both  8way joystick and leftjoytsick to the dpad casing a conflict. This condition should never happen it only did because the input was always enabled for IPF cheat.

Hope this explains it for you. Sorry if it doesn't make sense i just finished a shift
