### ISSUE TITLE
create a RetroArch RDB and thumbnail pack for this core

### ISSUE THREAD

**Issue by markwkidd** [libretro/mame2003-plus-libretro#472]
If there was an RetroArch RDB for this core, RA users could use the content scanner to make a playlist automatically. There is a tool in https://github.com/libretro/libretro-database that creates RDB files out of -- I believe -- dir2dat DAT files.

If there was a thumbnail pack for this core, RA users could download thumbnails within the GUI and have a nice playlist. This requires a set of thumbnails that have a filename corresponding to the `game_driver->description`, in other words the thumbnail has to be named `Q-Bert (US Set 1).png` instead of `qbert.png`.

I have produced these kinds of things before, so presumably I can refresh myself and do it again.

**Comment by 2xtime** [comment]
@markwkidd This would also be great for your Retroarch Playlist Buddy ! It makes the correct names for the playlist by reading the mame datfile but doesn't make the screenshots the same name. Someone has reported this problem on your Playlist Github.

**Comment by markwkidd** [comment]
@2xtime if you create a new playlist with Playlist Buddy taken from the DAT that is currently in this repo (from November 11) you should have another hundred or two matching thumbnails now compared to last week.

Do you have any coding or scripting experience? The process of correcting the game names so that they match the MAME names that in the RetroArch thumbnail repository is a very simple process but it is a bit time consuming. I could really use some help :)

**Comment by markwkidd** [comment]
## Database progress:
  * Today there is a new MAME2003-Plus RDB file available when you use the RetroArch online updater to update databases.
  * This database will recognize "Full Non-Merged Sets" (aka non-merged "Separate BIOS Sets" disabled in the ClrMamePro settings as is described in the docs: https://docs.libretro.com/library/mame2003_plus/#step-3-building-mame-2003-plus-romsets
  * As with all RetroArch scanner support for MAME, the romset zips need to be torrentzipped
  * The scanner will recognize all games that are not flagged as `NOT_WORKING`

## Thumbnail update:
  * I have a working repository set up which people are free to use that should match the vast majority of titles in the new RDB database. It's not ready for widespread public use but folks are still free to use it in the meantime: https://github.com/markwkidd/mame2003-plus-thumbnails

**Comment by markwkidd** [comment]
Things are advancing nicely in general on this project although the most current copy of my playlist/database scripts have concerningly omitted a working romset `tetris` that should be included: https://github.com/libretro/libretro-database/issues/748#issuecomment-442725578

I'll be looking into that as soon as I can.

**Comment by markwkidd** [comment]
Alrighty, there is now a complete RDB for RetroArch in the RA downloader and a complete thumbnail repository (in terms of title and snap images) at this URL: https://github.com/markwkidd/mame2003-plus-thumbnail-sources

Closing as completed.
