### ISSUE TITLE
Request: Arcade Classics (prototype)

### ISSUE THREAD

**Issue by UDb23** [libretro/mame2003-plus-libretro#474]
As mame2003 has good trackball support, I'd love to see Atari's "[Arcade Classics](http://www.progettoemma.net/index.php?gioco=arcadecl)" (Super centipede and Missile command II) fixes after mame .78 implemented in mame2003 plus.

**Comment by arcadez** [comment]
What's up with Arcade Classics..?? last time i gave it a whirl both games seemed fine to me

**Comment by arcadez** [comment]
You seem to assume two things here that firstly the above code can easily be backported or will
even function correctly in this core and secondly i have infinite amounts of free time to invest in 
this project 

I can assure you on both cases your wrong :)

**Comment by UDb23** [comment]
No assumptions , just kindly asking as I'm building a trackball dedicated control panel. 
I didn't know about the complexity of that implementation. According to your reply it does is complicated to do so I fully understand you got other priorities. :-)
