### ISSUE TITLE
create a doc on how to compile a test branch on this repo or someone else's repo

### ISSUE THREAD

**Issue by markwkidd** [libretro/mame2003-plus-libretro#475]
This comes up from time to time and it would be good to have something in the wiki. I'm pretty sure grant has written out the retropie procedure several times in the past so I'll try to find that and start with it as the first draft.

two audiences/sets of instructions:
* people on retropie
* people in windows or linux desktop (I can write this)

**Comment by grant2258** [comment]
retropie instruction will be identical is just you will need to put the fit pull somewhere specific. Once you finish you doc ill edit it for retropie usage.

**Comment by markwkidd** [comment]
We now have a guide for compiling PRs for testing, based of course on your notes, which is close enough for now: https://github.com/libretro/mame2003-plus-libretro/wiki/How-to-compile-a-PR-for-testing

That can be expanded as needed to other scenarios. Closing this issue.
