### ISSUE TITLE
TAB input goes crazy ocassionally

### ISSUE THREAD

**Issue by Wilstorm** [libretro/mame2003-plus-libretro#477]
When configuring input on a game in the TAB menu occasionally it goes crazy. It will put random inputs or lag for several seconds but usually it will start defaulting to the defaults when any key is pressed and it takes seconds to fill in the field. You press a key and then seconds later it might fill in or if you do del/del it will sit there waiting for input and if you do del/del again it will fill something in but not always the defaults. The only way to break out of it is exit the game and then go back in and continue configuring. I can't find a pattern as it's completely intermittent but I do seem to see it regularly-ish now.

**Comment by grant2258** [comment]
The input menu wasnt touched at all i havent touched the code for it at all. I cant reiterate this enough back your cfg dir up and delete your old configs all of them not just the default.  It will only set to sefault or the key pressed.

Make sure your in input mode its keyboard or mame if your using the keyboard/ipac , retroarch is just for retropads and what ever retropad binds you have set to keys in your RA config.

**Comment by grant2258** [comment]
My pi is running fine as well to be honest. The only time ive ever had problems with the pi is when I overclocked it. see https://github.com/libretro/mame2003-plus-libretro/issues/449 if you are overclocked and you files are corrupt youll need to start again.  Hopefully someone else can report these issues as if they are having them. 

Mame has nothing to to with the gamelist.xml emulationstation deals with that

**Comment by Wilstorm** [comment]
Check, I did delete my cfg's. Check I also have "MAME" set and Input Remapping enabled.

I do overclock. The Pi is a super simple overclock compared to a PC unless your doing a simple FSB multiplier. The PC I am typing this on now is running at 5Ghz from 3.6Ghz. Intel Ivy Bridge, black, unlocked multiplier. 

The issue I see mostly is people use other peoples numbers with a Pi and that just doesn't work. Each one has slightly different silicone. I've yet to purchase one that's at the top of the "bell curve". Basically I baseline, make small bumps and vcore adjustments and then stress test the piss out of it. Then rinse and repeat then eventually you start locking up, back it down and go to the next parameter and work it up. Once dialed in then just drill it with stress tests for hours and hours, days if you like. Even a single lockup or game drop is an unstable overclock. It takes hours across days really to do it proper and most don't take the time. You need some good passive or active cooling. Cases that make direct contact with the die are far superior and don't require active cooling. It's not for everyone that's for sure.

Ok I will close this case and thanks for taking a look!

**Comment by grant2258** [comment]
well its not solved if its still an issue leave it open could be a bug and relevant. Feel free to reopen anytime you didint need to close it

**Comment by grant2258** [comment]
for what it worth my overclocking only worked properly on my pi 2 when i baught a decent power supply. That wasnt the reason I got the power supply though. The psu I was using was causing ground loop issues.with my dell monitor you know the ones that take a power input like a laptop does it would just flash on an off all the time. Im using a pi 3b+ now no real point in overclocking that at all its a 1.4 anyway
