### ISSUE TITLE
Super Sprint (All ver.) - RetroArch crashes when the car should explode

### ISSUE THREAD

**Issue by iosadosd-quarto** [libretro/mame2003-plus-libretro#478]
When playing Super Sprint (be it the parent or one of the clones) the game works normally until you bump into a wall at a certain speed: the car should explode, but instead RetroArch crashes.

I tried playing the same game on standard MAME 2003 (not Plus) but it crashes either way; the game works normally on standalone MAME 0.78.

I'm using RetroArch stable v1.7.5 on a Windows 10 notebook with an i7-8550 CPU, 16 GB of RAM and a NVIDIA GeForce MX 150 with 4 GB of VRAM.

I'm attaching a log file, hope it helps.

[retroarchlog.txt](https://github.com/libretro/mame2003-plus-libretro/files/2568293/retroarchlog.txt)

**Comment by arcadez** [comment]
You get the same with Championship Sprint.??

**Comment by grant2258** [comment]
yea both are doing it just leave the attract mode on an ssprint crashes as soon as you jump over the middle section. cssprint does it when you finish the second lap on windows10 64 at least. Im betting its casting again somewhere.

**Comment by grant2258** [comment]
tested on the pi with our core and ssprint has sound and does the laps tested on real mame078 in windows10 64 bit doesnt crash but doesnt have sound.  Im leaning toward a casting bug I hate finding them arse

**Comment by iosadosd-quarto** [comment]
@grant2258 have you tried crashing into a wall on RPi to see if RetroArch crashes?

Also I'm pretty sure that there was sound when I tried on standalone MAME 0.78... granted, I did try one of the clones, but what matters is that the emulator didn't crash when I crashed my car.

**Comment by grant2258** [comment]
@iosadosd-quarto i didnt need to just leave the attract mode on (dont put credits in) and it will crash quick in ssprint, apb segfaults, paperboy has no sound and segfaults sometimes. All are fine on the pi (32 bit)

**Comment by iosadosd-quarto** [comment]
> @iosadosd-quarto i didnt need to just leave the attract mode on (dont put credits in) and it will crash quick in ssprint, apb segfaults, paperboy has no sound and segfaults sometimes. All are fine on the pi (32 bit)

Oh, ok. I asked just in case crashing into the wall (and triggering the exploding car animation) was perhaps a separate condition for reproducing this bug.

**Comment by grant2258** [comment]
its probably all related try apb itll just crash as well

**Comment by markwkidd** [comment]
The original xmame 0.78 readme, that made it into early mame2003 readme, said something beautifully minimal along the lines of "64 bit will have issues" 🙃 🤕

**Comment by grant2258** [comment]
well they just used 32 bit compilers then the issue goes away when you do that

**Comment by markwkidd** [comment]
I wonder if there is ever any benefit to compiling with 64 bit support. Could maybe our makefile be adjusted to use 32 bit compilation and instantly have an improved experience for many people?

**Comment by grant2258** [comment]
@arcadez is the t11 only used in these games ?

**Comment by grant2258** [comment]
@markwkidd just compile in msys32

**Comment by markwkidd** [comment]
I'm thinking about the buildbot too :)

**Comment by grant2258** [comment]
@markwkidd and @arcadez  are you guys familiar with this syntax 

https://github.com/libretro/mame2003-plus-libretro/blob/4add8cb8327dfb0db9dd974bdfa5d723a2e0eaeb/src/cpu/t11/t11.c#L511
?

**Comment by arcadez** [comment]
The T11 is only used by Atari System 2 hardware im not all that familiar with it TBH

**Comment by grant2258** [comment]
Well im not convinced its the cpu still need to look into it more. It could be banking related. This is just the point its crashing at not necessarily the cause. Just posting here for when I get time to look into it again.

src/vidhrdw/atarimo_vidhrdw.c:547:22: runtime error: index -1 out of bounds for type 'rectangle [1024]'
[libretro INFO] [MAME 2003+] loading apb.hi hiscore memory file...
ASAN:DEADLYSIGNAL
=================================================================
==24247==ERROR: AddressSanitizer: SEGV on unknown address 0x7f8af3af58d2 (pc 0x7f89e286eceb bp 0x000000000000 sp 0x7ffcfb4cb540 T0)
==24247==The signal is caused by a READ memory access.
    #0 0x7f89e286ecea in ROPCODE src/cpu/t11/t11.c:111
    #1 0x7f89e297e519 in t11_execute src/cpu/t11/t11.c:510
    #2 0x7f89e0fd98ba in cpunum_execute src/cpuintrf.c:1109
    #3 0x7f89e0fc860f in cpu_timeslice src/cpuexec.c:606
    #4 0x7f89e0fc7178 in mame_frame src/cpuexec.c:360
    #5 0x7f89e0f791e3 in retro_run (/home/grant/.config/retroarch/cores/mame2003_plus_libretro.so+0x38091e3)
    #6 0x5580fec62af2 in core_run /home/grant/libretro-super/retroarch/core_impl.c:448
    #7 0x5580fec72585 in runloop_iterate /home/grant/libretro-super/retroarch/retroarch.c:3494
    #8 0x5580fec5e373 in rarch_main frontend/frontend.c:141
    #9 0x5580fec5e4c9 in main frontend/frontend.c:169
    #10 0x7f8a00de0b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
    #11 0x5580fec50409 in _start (/usr/local/bin/retroarch+0xd91409)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV src/cpu/t11/t11.c:111 in ROPCODE
==24247==ABORTING

**Comment by grant2258** [comment]
(gdb) l
106	
107	static INLINE int ROPCODE(void)
108	{
109		int pc = PCD;
110		PC += 2;
111		return *(UINT16 *)(&t11.bank[pc >> 13][pc & 0x1fff]);
112	}
113	
114	
115	static INLINE int RBYTE(int addr)
(gdb) print PCD
$1 = 29152
(gdb) print pc
$2 = 29150
(gdb) print PC
$3 = 29152
(gdb) print *(UINT16 *)(&t11.bank[pc >> 13][pc & 0x1fff])
Cannot access memory at address 0x8000e68029de
(gdb)

**Comment by grant2258** [comment]
can somone close this please is fixed
