### ISSUE TITLE
Street Fighter 2 CE. Lockup on Intro

### ISSUE THREAD

**Issue by BlockABoots** [libretro/mame2003-plus-libretro#481]
Have noticed that Street Fighter 2 CE locks up on the intro just when the guy punches the other guy. Here is the log

[retroarch-log.txt](https://github.com/libretro/mame2003-plus-libretro/files/2568672/retroarch-log.txt)

Also i have noticed that the standard World Warrior audio has a constant tone more or less at the same point as the issue above using the sf2.zip rom

**Comment by grant2258** [comment]
sf2.zip Is not sf2ce

**Comment by grant2258** [comment]
Please update your mame2003+ core as well

**Comment by BlockABoots** [comment]
Yeah i do have the latest core (i update via RA just before posting). Here is my system specs:

Windows 10
Intel i7 4770k cpu
GTX 1070
16GB Ram
SOUNDBLASTER XF-I Titainium

Im starting to wonder if its an audio issue, as i just tried Altered Beast and the audio craps out on the attract sequence

**Comment by grant2258** [comment]
turn rewind off if its on as well

**Comment by BlockABoots** [comment]
yes they are all off

**Comment by grant2258** [comment]
damn i had all the rom loading code enabled looks like someones changes it a bit so i cant rule out a bad rom atm. Ill need to check that code over again and put the logging back

**Comment by BlockABoots** [comment]
do you want me to send you the sf2 rom im using?

**Comment by grant2258** [comment]
no need i looked up the code errors will show they are all still on. it just missing starting verify and finish is all good. 

i see a few RA errors and warnings in your log though
0(279) : warning C7050: "mask_config" might be used before being initialized

[INFO] [GL]: VSync => off
[INFO] [WGL]: wglSwapInterval(0)
[WARN] [WGL]: wglSwapInterval() failed.
[INFO] [GL]: VSync => on
[INFO] [WGL]: wglSwapInterval(-1)
[WARN] [WGL]: wglSwapInterval() failed.

[ERROR] Failed to create rendering backend: freetype.
[ERROR] Failed to create rendering backend: stb-unicode.
[INFO] [Font]: Using font rendering backend: bitmap.
[ERROR] Failed to create rendering backend: freetype.
[ERROR] Failed to create rendering backend: stb-unicode.

you might want to ask about this on discord

**Comment by markwkidd** [comment]
Can you try changing your RetroArch video driving to one of the direct3d options? I would always like to rule out GL video driver

 I use d3d9 but you can probably use d3d10 or d3d10 on that hardware

**Comment by BlockABoots** [comment]
Tried d3d9 and d3d10 and go the same issue.

On a whim i decided to do a fresh install of Retroarch and low and behold im not getting any lockups anymore, so im not sure what the issue was.......maybe it was shader releated?

**Comment by grant2258** [comment]
no idea what it was to be honest it was something RA side not the core
