### ISSUE TITLE
add metadata such as cocktail mode to DAT file

### ISSUE THREAD

**Issue by markwkidd** [libretro/mame2003-plus-libretro#489]
Apparently at some point I had a reason to remove cocktail metadata from the DAT file. I can't recall what the reason was but at any rate there's no reason now that I can think of now not to include that information.

In addition to cocktail mode information, is there anything else that we should add to the DAT?

Conceivably we might even add something that wasn't originally part of MAE 0.78 DAT if we wanted to. Is there anything cool we want to add that more recent DATs include, etc?

**Comment by grant2258** [comment]
well it was me that added it and you removed it cant remember the reason why though. It not really important atm unless we add them video changes.
Im not commenting on the mame2003 issue anymore unless its to nayslayer. 

I wasted enough time in the past with dank he can do what he likes with 2003 but his opinions shouldnt be passed down to our core though. It seems he know less than he comments on at times and just holds onto idealism's  an he perceives them not the reality of the matter. Thats the impression I get anyway im glad im out of the politics my code can just be accepted or not makes my life easier.

**Comment by markwkidd** [comment]
@grant2258 I can't see any sign of cocktail info being added (or removed) from `info.c` in the history view: https://github.com/libretro/mame2003-plus-libretro/commits/master/src/info.c

Is there any chance you still have this code somewhere in your own repository?

**Comment by grant2258** [comment]
yea it was me that added it at some point then we removed it ill look over the history and see if i can find it

**Comment by markwkidd** [comment]
there hasn't been a use case for adding this to the DAT in the last couple of years, so I'll close the issue. we can reopen it or open a new one for other DAT enhancements
