### ISSUE TITLE
Ultra Tank visible/invisible option doesn't work

### ISSUE THREAD

**Issue by Wilstorm** [libretro/mame2003-plus-libretro#491]
With Ultra Tank (ultratnk). There's 3 options that may be set for each game. It's similar to the old Atari Combat game but the Atari had a lot more selection options.

1) Open Game Field / Walls plus mines
2) Visible Tank / Invisible Tank
3) Steer Shot / Bouncing shots

The game runs perfectly for two players and all the options work except the visible/invisible tank option. You always stay visible toggled either way. Is that an easy fix by chance or not so much?

**Comment by grant2258** [comment]
i would hazzard a guess it the video code that needs updated for this option just a guess though

**Comment by Wilstorm** [comment]
I know it's a super simple game with minimal graphics of a few colors but we had a lot of fun playing it back in the day. I don't know if the Arcade game first or the Atari 2600.

**Comment by arcadez** [comment]
Here's your fix..........

0.103: Merged the Sprint 4/Ultra Tank drivers [Stefan Jokisch]: Hardware collision detection (computer is now able to manoeuvre around barriers). Sprite fixes (invisble tank option works, tank explosion sequence). Playfield fixes (text colors are different). Watchdog and coin lockout added. Sync and color proms added. Motor sound fix (previously this was hooked up to the wrong address). Misc internal fixes like cpu speed, RAM size etc. Changed M6502 CPU1 clock speed to 756000 Hz. Fixed cpu1/gfx1 rom loading. Added proms ($0) and user1 ($0 - sync).

Note the first word is merged this means two drivers become one which = alotta work, you might
need to start a bounty to garner some interest as i doubt anyone on here is gonna wanna do it.

**Comment by Wilstorm** [comment]
@arcadez - No need for a bounty. If it was an easy fix great, if not, great. It's a pretty old old school game from the 70s. I appreciate you checking into it.
