### ISSUE TITLE
Sega Model 1 WIP

### ISSUE THREAD

**Issue by arcadez** [libretro/mame2003-plus-libretro#495]
Been trying to add support for Virtua Fighter to the MAME 72 codebase however im getting
some strange behavior on boot where as i dont even get to the nag screen after the roms load
all i get a blank screen and my xbox HDD makes a funny whining noise :)

Anyway i suspect it could be one of a few things maybe the V60 and M68k CPU's at this point
in the MAME dev cycle are not correct or it could be the ROMBANK1 or the Mirror i added
both of which are in the mem map, or none of the above and something silly i missed which
the game requires.

I cant make a debug build to further track what is going on at boot so i thought i'd hand over
my current WIP if anyone feels like adding it to their mame2003+ fork and see if they can at
least get the game to boot and function.

Sega Model 1 WIP 
https://www.sendspace.com/file/3ki3g8

**Comment by twinaphex** [comment]
Virtua Fighter 1 and Virtua racing in MAME 2003 Plus would definitely be awesome!

**Comment by grant2258** [comment]
done a quick test getting a few.

src/vidhrdw/model1.c: In function 'video_update_model1':
src/vidhrdw/model1.c:1517:2: error: too few arguments to function 'sys24_tile_dr                                                                                                                aw'
  sys24_tile_draw(bitmap, cliprect, 7, 0);

obviously our core is using a different sys24_tile_draw' ill check what the extra flags are when i have time. going to looking into this hatari bug before i forget.

id added here if anyone wants to mess with it.

https://github.com/grant2258/mame2003-plus-libretro/tree/model1

thanks again mr arcadez

**Comment by arcadez** [comment]
@twinaphex Virtua Fighter would be doable, Virtua Racing however in a no go as we would
require a new TGP CPU core which is not compatable in any way shape or form with MAME78

**Comment by arcadez** [comment]
@grant2258 we'll likely need to update vidhrdw system24.c and segaic24.c, wont be difficult right
enough but i thought see if we can get it to boot firstly.

**Comment by grant2258** [comment]
ill need to find the rom will let you now if have any luck with it booting

**Comment by arcadez** [comment]
It seems we wont need to update anything system24 vid related as the code is lining up
with MAME86 which is the build i took the model1 driver etc etc, @grant2258 try doperoms
and serach for vf.zip then all you should have to do is rename it to vf1.zip

Anyway i can send ya the correct rom later on should you have troubles tracking it down
if we do get this to work i'll rename the rom to vf to make it easier to obtain

**Comment by arcadez** [comment]
Ah damn it i forgot since we changed our V60 CPU both the CPU's in the model 1 driver will need
reclocked and then some new code to fix the sound after the above will be needed trivial stuff
right enough plus i have the code for this already.

So if the game does boot dont panic if it's slow as shit and has no sound as we'll fix that down
the road and it'll perform pretty nicely in this ole core.

**Comment by grant2258** [comment]
well ill need to add the makefile changes they didnt auto add and i updated my roms its been needing done for a good while to be honest. anyway no more excuses time to get this tested

**Comment by arcadez** [comment]
Alright while your on that i sent in another driver with the CPU's reclocked and the sound code
changes

**Comment by grant2258** [comment]
ok ill update can confirm it is booting animation is off though will send screenshots if its still doing it after these updates

**Comment by grant2258** [comment]
good news the jobs a good one its working mate sound as well 👍

**Comment by grant2258** [comment]
![vf1-181125-004944](https://user-images.githubusercontent.com/6128601/48974287-2db7c880-f04c-11e8-92b8-028857ffc678.png)

**Comment by grant2258** [comment]
sorry i took so long doing a few things at once as per usual

**Comment by grant2258** [comment]
here is the before your last commit looked like yoga maybe we can call this a hack of virtual yoga!

![vf1-181125-004609](https://user-images.githubusercontent.com/6128601/48974299-6c4d8300-f04c-11e8-80fc-4e4f4884bfc0.png)

**Comment by grant2258** [comment]
ive added you so you can update my repo arcadez i tried to add mark cant seem to find his username

**Comment by arcadez** [comment]
Result!! i'll review all the code to make sure i didn't mess up along the lines plus there is a speedup
via model1 video which i have to double check just to make sure i added it correctly, fancy that it 
worked in MAME78 but not via 72 on the ole xbox.

BTW i have Virtua Racing as well however due to lack of the aforementioned CPU the TGP sim does
mess up if you crash plus after two laps it keeps pulling ya in for a pitstop making it near damn impossible to win a race, it's fucked basically so i dont really see we can add it here but if folks
want it then well it wont be too hard to drop it in.

**Comment by grant2258** [comment]
well if that cpu will help with more than one game it might be worth porting it else its just keep it the way it is and make it as game not working at least you can get two laps!

**Comment by arcadez** [comment]
@grant2258 if we add Virtua Racing it's just gonna cause us all sorts of bug reports, i can bring it
up to this point, but if you crash the game locks up and you need to do an ingame reset and start 
the levels again if you get not too bad at it and actually avoid crashing then it's still gonna pull ya into the pit lane on laps 3 and 4 making winning a race more or less impossible

0.107u3: Olivier Galibert fixed track lookup implementation in Virtua Racing, bringing the game much closer to playable.

We need this CPU but i could never get it to work in MAME84, there were some big changes to
how the CPU's function around MAME110 but certainly someone with more experience of coding
might be able to backport it to MAME78

0.114: Ernesto Corvi updated Virtua Racing to use the TGP core, based on guessing from the Daytona TGP code with some modifications needed for Virtua Racing, the real TGP program is an internal ROM and still needs dumping - Game now playable. Added MB86233 (16MHz) CPU3 and 8k TGP rom (vr-tgp.bin).

but hey we got Virtua Fighter so not a total loss :)

**Comment by arcadez** [comment]
Here is the new Model 1 code it's 100% ready to go feel free to push it when you get a chance
i'd do it myself but the logerror calls need sorted to RA standards and i dunno how to make this
git auto change em im dumb thay way TBH :)

https://www.sendspace.com/file/nscj06

**Comment by arcadez** [comment]
Of all the Sega Model 1 games only Virtua Racing has it's TGP internal rom dumped hence the
extra CPU we dont support being required, the rest are using TGP sim code Virtua Fighter is
good the other two Wing War and Star Wars Arcade are still tagged as unplayable in current
MAME.

The TGP sim is not 100% for both Wing War and Star Wars Arcade there was some WIP done
that more or less brings SWA upto a near playable status not that long ago we'd need to see 
just how playable via youtube to see if it's worth trying to support it here.

**Comment by twinaphex** [comment]
Didn't know Model 1 was still this premature even in current-day MAME.
