### ISSUE TITLE
Poker Ladies buttons don't work

### ISSUE THREAD

**Issue by zanac** [libretro/mame2003-plus-libretro#497]
This game never worked in fba/mame cores cause you cannot map buttons to keep cards, only deal Button can be mapped so you can only Switch all cardsy...

**Comment by grant2258** [comment]
Buttons: 8 [Card A|Card B|Card C|Card D|Card E|Deal|Cancel|Flip Screen]

"P1 A", KEYCODE_A, IP_JOY_NONE )
"P1 B", KEYCODE_B, IP_JOY_NONE )
"P1 C", KEYCODE_C, IP_JOY_NONE )
"P1 D", KEYCODE_D, IP_JOY_NONE )
"P1 E", KEYCODE_E, IP_JOY_NONE )
"P1 Deal", KEYCODE_LCONTROL, IP_JOY_NONE )
"P1 Cancel", KEYCODE_LALT, IP_JOY_NONE ) 
"P1 Flip", KEYCODE_SPACE, IP_JOY_NONE )

goto input interface anc choose or keyboard look at the keycodes to what the keys are if something isint working right on the keyboard let us know. Im not ver familiar with these games
