### ISSUE TITLE
adding Donkey Kong Remix hack

### ISSUE THREAD

**Issue by markwkidd** [libretro/mame2003-plus-libretro#504]
@arcadez did you ever succeed at adding the Donkey Kong Pauline Edition hack to the mame2003 codebase? I had a memory that it was already in mame2003-plus but I may have imagined this?

**Comment by markwkidd** [comment]
Maybe I mistakenly got that idea back at this point on the retropie forums: https://retropie.org.uk/forum/topic/2889/mame-development-lr-mame2003-updates/115

That is not a CHANGELOG from your work on the 2003 codebase I think 😜

**Comment by grant2258** [comment]
looks like its just a gfx hack just add the new roms and game declare in if you want it mark should work

**Comment by markwkidd** [comment]
Alright, maybe this is one for me to add :) give me a little time and I'll come back to this unless someone beats me to

**Comment by arcadez** [comment]
Donkey Kong Remix is on the go but it's only a demo with two all new levels HBMAME supports it
i think.?? i've played it and it's pretty decent i suppose they'll release the full game once they've hit 
their PCB sales targets.

**Comment by markwkidd** [comment]
(changing the title to reflect the previous message by arcadez -- there's always one more romset I guess!)

**Comment by markwkidd** [comment]
@arcadez I didn't realize you meant that it was a driver all ready for our core. I thought it would be something like a driver from the xbox version lol. I'm adding it now, thanks!

**Comment by arcadez** [comment]
So the DU are working on dumping the PCB for Donkey Kong Remix, some weird bank switching
between the different versions of the game are holding up proceedings although since the board
is still being sold im not sure it'll be added to MAME this year.

Anyway at some future date we may support it here.
