### ISSUE TITLE
touchscreen lightgun support

### ISSUE THREAD

**Issue by gomisensei** [libretro/mame2003-plus-libretro#507]
just started using retroarch/mame2003plus on android, and noticed there is no way to use the touchscreen to emulate lightgun shots.  would this be something that could be implemented in this core?

**Comment by grant2258** [comment]
if you can translate the it to mouse x/y the you probably can

**Comment by markwkidd** [comment]
Agreed -- right now you need to be able to have your touchscreen appear as a mouse. I believe that some Android users have been able to do so with touchscreens but I don't know myself.

An implementation of the libretro lightgun API should make support more robust, at least with RetroArch and other frontends that also have the lightgun API. @gomisensei there is a bounty foundraiser, and a search for developers: https://github.com/libretro/mame2003-plus-libretro/issues/400

**Comment by grant2258** [comment]
the mouse support is very primitive the way its been added it. looks like the mouse would control 2 players the way it is atm. 

I dont know nothing about android. Ill check what device it shows as and see if it can be added as a lightgun to mame instead of a mouse. I need to check if mame has lightgun code handling i think it does though would need to double check though. The only thing stopping me doing and coding on this is I dont have a lightgun to test any code lol.

**Comment by grant2258** [comment]
src/inptport.c:1910:            case IPT_LIGHTGUN_Y:                                                                                                                                             src/inptport.c:1973:            /* The OSD lightgun call should return the delta from the middle of the screen                                                                                   src/inptport.c:1976:            in place of a physical lightgun.  When the OSD lightgun returns 0, then control                                                                                  src/inptport.c:1978:            lightgun returns a value it overrides both mouse & analog joystick.

looks like this is doable with somone that has a lightgun to test code with

**Comment by grant2258** [comment]
here is some code from the windows port for example might help someone with a lightgun to add and test the code.

void osd_lightgun_read(int player,int *deltax,int *deltay)
{
	POINT point;

	// if the mouse isn't yet active, make it so
	if (!mouse_active && (use_mouse||use_lightgun) && !win_has_menu())
	{
		mouse_active = 1;
		win_pause_input(0);
	}

	// if out of range, skip it
	if (!use_lightgun || !win_physical_width || !win_physical_height || player >= (lightgun_count + use_lightgun_dual))
	{
		*deltax = *deltay = 0;
		return;
	}

	// Warning message to users - design wise this probably isn't the best function to put this in...
	if (win_window_mode)
		usrintf_showmessage("Lightgun not supported in windowed mode");

	// Hack - if button 2 is pressed on lightgun, then return 0,0 (off-screen) to simulate reload
	if (use_lightgun_reload)
	{
		int return_offscreen=0;

		// In dualmode we need to use the buttons returned from Windows messages
		if (use_lightgun_dual)
		{
			if (player==0 && lightgun_dual_player_state[1])
				return_offscreen=1;

			if (player==1 && lightgun_dual_player_state[3])
				return_offscreen=1;
		}
		else
		{
			if (mouse_state[0].rgbButtons[1]&0x80)
				return_offscreen=1;
		}

		if (return_offscreen)
		{
			*deltax = -128;
			*deltay = -128;
			return;
		}
	}

	// Act-Labs dual lightgun - _only_ works with Windows messages for input location
	if (use_lightgun_dual)
	{
		if (player==0)
		{
			point.x=lightgun_dual_player_pos[0].x; // Button 0 is player 1
			point.y=lightgun_dual_player_pos[0].y; // Button 0 is player 1
		}
		else if (player==1)
		{
			point.x=lightgun_dual_player_pos[2].x; // Button 2 is player 2
			point.y=lightgun_dual_player_pos[2].y; // Button 2 is player 2
		}
		else
		{
			point.x=point.y=0;
		}

		// Map absolute pixel values into -128 -> 128 range
		*deltax = (point.x * 256 + win_physical_width/2) / (win_physical_width-1) - 128;
		*deltay = (point.y * 256 + win_physical_height/2) / (win_physical_height-1) - 128;
	}
	else
	{
		// I would much prefer to use DirectInput to read the gun values but there seem to be
		// some problems...  DirectInput (8.0 tested) on Win98 returns garbage for both buffered
		// and immediate, absolute and relative axis modes.  Win2k (DX 8.1) returns good data
		// for buffered absolute reads, but WinXP (8.1) returns garbage on all modes.  DX9 betas
		// seem to exhibit the same behaviour.  I have no idea of the cause of this, the only
		// consistent way to read the location seems to be the Windows system call GetCursorPos
		// which requires the application have non-exclusive access to the mouse device
		//
		GetCursorPos(&point);

		// Map absolute pixel values into -128 -> 128 range
		*deltax = (point.x * 256 + win_physical_width/2) / (win_physical_width-1) - 128;
		*deltay = (point.y * 256 + win_physical_height/2) / (win_physical_height-1) - 128;
	}

	if (*deltax < -128) *deltax = -128;
	if (*deltax > 128) *deltax = 128;
	if (*deltay < -128) *deltay = -128;
	if (*deltay > 128) *deltay = 128;
}

**Comment by nayslayer** [comment]
This is somewhat confusing. Isn't there support for mouse emulation on touchscreens already? The "Mouse Device" core option, I mean. Then it's handled [here](https://github.com/libretro/mame2003-plus-libretro/blob/438c099745ccc4a14431a5aa4251a15099e922b6/src/mame2003/mame2003.c#L1044) in a way a touchscreen should be.

**Comment by grant2258** [comment]
i havent used andriod much im actually trying to compile code for it atm so i dont need the build bot.

**Comment by nayslayer** [comment]
@grant2258 I bid you good luck to that. Learning to use the Android SDK seems like a full time job =/

@gomisensei Could you please try different `Mouse Device` core options and check if they work? I believe the `Pointer` choice should make it work, at least it's the default for iOS.

**Comment by grant2258** [comment]
nothing much was well received with mame2003 with any input changes to be fair @retro-wertz

**Comment by markwkidd** [comment]
OP -- I will assume optimistically that you changed your mouse in the core options to the `pointer` type and now this is working for you. If you have done that and are still having issues please post here again.
