### ISSUE TITLE
No sound for dkong3 for armhf build

### ISSUE THREAD

**Issue by metchebe** [libretro/mame2003-plus-libretro#515]
Donkey Kong 3 (`dkong3`) has no sound in both of my ARM devices:

- Raspberry Pi 3 running LAKKA, with updated core in /storage/cores
- NVIDIA Shield Tablet K1 running the latest Retroarch with updated core

I do get sound in my Kubuntu amd64 machine.

**Comment by grant2258** [comment]
what the commit number you are on ?

**Comment by metchebe** [comment]
MAME 2003-Plus 403e71c on the Shield (just updated and tested now)

**Comment by grant2258** [comment]
ok ill compile it on retropie and check it out.

**Comment by grant2258** [comment]
its working fine on the raspberry pi

**Comment by grant2258** [comment]
@metchebe do me a favour run suprmrio.zip if your sounds messed up let me know.

@markwkidd  the fsigned doesnt appear to be working on android for the make file

**Comment by markwkidd** [comment]
Could it be a sample loading/path issue? Do other romsets with samples work?

**Comment by grant2258** [comment]
no its not sample paths i can tell you that much for nothing

**Comment by grant2258** [comment]
android is fixed i can provide a bin for a pi3b+ if you want normal pi3 had different flags

**Comment by metchebe** [comment]
> @metchebe do me a favour run suprmrio.zip if your sounds messed up let me know.

On the SHIELD, yes, it _was_ messed up, however after the update to cab0621 it is fixed (`dkong3` and `suprmrio`), thank you.

I forgot to specify that my Raspberry Pi is a 3B (non plus). If you could clarify, are you saying that it needs a special binary (i.e. not the armhf one from the buildbot)? I'm not sure I understand correctly.

**Comment by metchebe** [comment]
Nevermind, I tried the same build (cab0621) on the Raspberry Pi 3B and it's fixed, thank you @grant2258 !

**Comment by grant2258** [comment]
Well the thing is the generic build for armhf are just for all arm devices to work they arent optimized for pi 1,2,3 ect.

It look like the makefile changes are good for armhf and the android.  It really up to ra/lakka if they want to add bins for rasp 1,2,3 and 3b+ for the best optimization. It was just the way the two build where compiling. I did leave the lakka people a message

**Comment by grant2258** [comment]
this can be closed is fixed
