### ISSUE TITLE
asterix rom seems doesn't work on android shield tv

### ISSUE THREAD

**Issue by srk15372** [libretro/mame2003-plus-libretro#521]
HI, I made a perfect romset with datfiles generated and clearmpro (0 missing) but the rom "asterix" doesn't seem to work on android shield tv. The same rom load succefully on windows pc.
Is it an android limitation? Thanks

**Comment by grant2258** [comment]
is working fine here on android. Try updating your mame2003-plus core

**Comment by srk15372** [comment]
hi, weird, I just updated and continue to crash retroarch will try another rom version but clearmamepro claims all my romset is clean without error or missings
thanks

**Comment by grant2258** [comment]
are you using ra from playstore is has issues grab the nightly

**Comment by srk15372** [comment]
so I updated retroarch to the last revision and core too, but no luck.
I pick an another asterix rom  0.78 rom and 0.139 rom but no luck.
I might have a problem on my setup.
I will investigate  thanks

**Comment by grant2258** [comment]
well problematic things seem to appear in the switch, wii, and android. Ill have  look for anything obvious when i get time. Its been ok on the pi windows and linux and on my samsung android phone.

**Comment by srk15372** [comment]
Ok thanks for your verification
Will wait no worries thanks
Regards

**Comment by grant2258** [comment]
there is a new build for mame on the build  bot if you want to try it

**Comment by srk15372** [comment]
So I test your last build  unfortunely it crash again even the clones of asterix
Sorry

**Comment by grant2258** [comment]
see if anyone else is having troubles its working gor me atm doesn't mean there isint a problem

**Comment by srk15372** [comment]
Hi will investigate thanks maybe the latest revision isn't available at this time on the builbot

**Comment by grant2258** [comment]
im using a a5 2017 Samsung Android 8.0 working fine there thanks for the feedback @2xtime

**Comment by srk15372** [comment]
hi, thanks for your report, I'm at work now but will test for sure after work and will report results  thanks again for your time spend on it.

**Comment by srk15372** [comment]
so I test the last revision core of mame2003  n° 8680cf4, recreate an xml dat file and rebuild my romset with clearmpro with 0 missing 0 errors. but the rom asterix still crash on android shield tv (oero version)
it work like a charm on windows pc.
so don't understand what is wrong with shield tv since its seems ok on android phone. weird

**Comment by grant2258** [comment]
the only thin i would suggest to try is delete your saves/mame2003-plus folder and make sure you not using the playstore version of RA

**Comment by srk15372** [comment]
I delete the mame2003plus save folder and I have one of the last nighites of retroach picked up these days on their website. but nothing still crash. maybe the android shield tv is a bit different from the android phones.

**Comment by grant2258** [comment]
since this bug is so strange the last thing you could try is backup your Retroarch folder then delete it and try again maybe something in here is corrupted

**Comment by srk15372** [comment]
ok thanks I will try. I have ever deleted all entries on the retroarch option config files to be sure there isn't any settings whitch corrupt the rom., but no luck.

**Comment by grant2258** [comment]
well core over rides will store in the config folder its the only other thing i can think of

**Comment by srk15372** [comment]
yes I have ever test to delete it too but no luck.
even the new game dkong pauline edition doesn't work. but run fine on windows.
something wrong with my setup
will have to made a new default installation

**Comment by grant2258** [comment]
well that was fixed a day ago there was a problems with it make sure your core is up to date

**Comment by srk15372** [comment]
hi, you are right for dkong pauline edition. after the last revision and update it works  thanks
but for asterix no luck.
regards

**Comment by srk15372** [comment]
so I'm able to play asterix now ! 
by disable the rewind option in mame2003 plus, the game launch fine
so do you have this option enable during your test ?
thanks again for your time to help me 
regards

**Comment by grant2258** [comment]
This is a know issue with some games. This option isint on by default and shouldn't have been enabled when installing a new retroarch. version. It will usually write the retroarch config again when install ra on android. Its good you got it working though.

**Comment by srk15372** [comment]
yeah thanks for all
regards

**Comment by markwkidd** [comment]
@grant2258 
> 0.136u1: Fabio Priuli added driver data struct and save states to Asterix.

Asterix probably needs the flag I created to reflect that it doesn't have serialization support. Then the core will disable serialization and this crash would probably not happen. I suspect that would prevent that issue for this one game.

Does that make any sense? That's my only way to deal with this. It's the opposite of current MAME though, where every driver has a SUPPORTS_SAVE flag **except** those that do not support save.

Maybe we could extract a list of romsets that don't support save from the source of the earliest MAME version that has the SAVE flag in order to have a list to apply to our own source, or something like that.

**Comment by grant2258** [comment]
I dont think using a later version of mame with different drivers will help with this issue it probably wont be accurate we really have different  roms and drivers in our version in some cases.

I think flagging per case will have to do for now. This option is not on by default on android so when in stalling and ne ra the default config should have been in place.

I guess the best way to fix this is to detect the issue instead of crashing that might be easier said than done though.

**Comment by grant2258** [comment]
@markwkidd ive fixed the logging up in games that do work the load is never called in the unserialize

**Comment by grant2258** [comment]
ok mark ive done a little nasty hack here that stops asterix and fshark crashing. I have no idea is serialize size can be done dynamically
