### ISSUE TITLE
Game name inconsistencies

### ISSUE THREAD

**Issue by 2xtime** [libretro/mame2003-plus-libretro#523]
Only a minor thing. I noticed in the datfile that there are a lot of game names beginning with '`The`'. A few are correctly written with '`, The`' at the end of the name.

**Comment by srk15372** [comment]
yeah, about 60 games are names like this, I manually change that one by one on my xml hyperspin description. not to long

**Comment by grant2258** [comment]
Well the real titiles where probably written "the gamename."  not "gamename, the" you would need to speak to mark about this. I would need to check mame current all them would need changed as well if thats not the case. Is there a reason the convention needs to be changed ?

**Comment by markwkidd** [comment]
I'm open for name changes that follow the current MAME version of the name.

@2xtime and @srk15372 if you are interested in helping make name updates, I could write up a simple process for you to use. A couple of questions for anyone interested in correcting names:
  * Do you have any coding experience in any language? (Not mandatory but important to know.
  * Do you have any experience submitting changes via git or github? (Also not mandatory, but important to know)

**Comment by grant2258** [comment]
what do you need to change this for just out of curiosity?

**Comment by grant2258** [comment]
this is the naming convention in the latest mame for this game


GM-2340)", MACHINE_SUPPORTS_SAVE )                                                                                                                                                               ../mame/src/mame/drivers/neogeo.cpp:11714:GAME( 1997, lastbladh,  lastblad, neobase,   neogeo,    mvs_led_state, empty_init, ROT0, "SNK", "The Last Blade / Bakumatsu Roman - Gekka no Kenshi (N GH-2340)", MACHINE_SUPPORTS_SAVE )                                                                                                                                                               ../mame/src/mame/drivers/neogeo.cpp:11715:GAME( 1997, lastsold,   lastblad, neobase,   neogeo,    mvs_led_state, empty_init, ROT0, "SNK", "The Last Soldier (Korean release of The Last Blade)",  MACHINE_SUPPORTS_SAVE )                                                                                                                                                                         ../mame/src/mame/drivers/neogeo.cpp:11727:GAME( 1998, lastbld2,   neogeo,   neobase,   neogeo,    mvs_led_state, empty_init, ROT0, "SNK", "The Last Blade 2 / Bakumatsu Roman - Dai Ni Maku Gekk a no Kenshi (NGM-2430 ~ NGH-2430)", MACHINE_SUPPORTS_SAVE )                                                                                                                                      ../mame/src/mame/drivers/readme.txt:2053:./neogeo.cpp:11713:GAME( 1997, lastblad,   neogeo,   neobase,   neogeo,    mvs_led_state, empty_init, ROT0, "SNK", "The Last Blade / Bakumatsu Roman -  Gekka no Kenshi (NGM-2340)", MACHINE_SUPPORTS_SAVE )                                                                                                                                             ../mame/src/mame/drivers/readme.txt:2054:./neogeo.cpp:11714:GAME( 1997, lastbladh,  lastblad, neobase,   neogeo,    mvs_led_state, empty_init, ROT0, "SNK", "The Last Blade / Bakumatsu Roman -  Gekka no Kenshi (NGH-2340)", MACHINE_SUPPORTS_SAVE )                                                                                                                                             ../mame/src/mame/drivers/readme.txt:2055:./neogeo.cpp:11715:GAME( 1997, lastsold,   lastblad, neobase,   neogeo,    mvs_led_state, empty_init, ROT0, "SNK", "The Last Soldier (Korean release of  The Last Blade)", MACHINE_SUPPORTS_SAVE )                                                                                                                                                       ../mame/src/mame/drivers/readme.txt:2065:./neogeo.cpp:11727:GAME( 1998, lastbld2,   neogeo,   neobase,   neogeo,    mvs_led_state, empty_init, ROT0, "SNK", "The Last Blade 2 / Bakumatsu Roman  - Dai Ni Maku Gekka no Kenshi (NGM-2430 ~ NGH-2430)", MACHINE_SUPPORTS_SAVE )

**Comment by 2xtime** [comment]
It was just a small OCD thing ! I have 50 games in my collection that begin with 'The' which is annoying in terms of alphabetical order ! But then I noticed that 4 games had ', The' at the end of the game name ?! As I said, it's no big deal, I can just batch change it manually with Notepad++ in my own gamelist. I'll close this one.

**Comment by grant2258** [comment]
i can change them 4 for you its not a problem
