### ISSUE TITLE
[RA/XMB Icon] missing mame2003-plus Icon

### ISSUE THREAD

**Issue by 5schatten** [libretro/mame2003-plus-libretro#543]
I'm not sure if this is the correct place to create this issue but looks like mame2003-plus is still missing a propriate icon in the XMB menu of Retroarch?
It looks like a generic placeholder/rocket instead of a small mame logo with release year like mame2010 has.

**Comment by grant2258** [comment]
im seeing rockets for everything in mine

**Comment by markwkidd** [comment]
@5schatten do you mind creating this issue over in the RetroArch repository? I might be able to help resolve it but it will depend on the RA developers involvement. Their repo is here: https://github.com/libretro/RetroArch/issues

If you do create an issue there, please tag me.

**Comment by markwkidd** [comment]
closed via https://github.com/libretro/retroarch-assets/pull/265. thanks for reporting this @5schatten and sticking with it as we bounced from repo to repo. It was worth the persistance!
