### ISSUE TITLE
About (thndzone.zip), picture mapping problem?

### ISSUE THREAD

**Issue by ji125443** [libretro/mame2003-plus-libretro#548]
As shown in the figure......
![thndzone-181218-114926](https://user-images.githubusercontent.com/25021120/50153757-560cad00-0302-11e9-9682-f471485214bf.png)
![thndzone-181218-114950](https://user-images.githubusercontent.com/25021120/50153758-56a54380-0302-11e9-9b34-24fab18bfe37.png)

**Comment by grant2258** [comment]
looks like the sprite priority isint so good at times

**Comment by arcadez** [comment]
Does it do this in standard MAME2003..?? reason i ask is this driver was caught up in the video
changes to deco16ic.c which was part of getting Night Slashers and some others to work

**Comment by grant2258** [comment]
ive updated  the driver further some improvments when going in rooms now and transparency

**Comment by arcadez** [comment]
well just one small change in vidhrdw dassault will fix it

**Comment by grant2258** [comment]
well boogie wings isint liking it :( thata a game stopper for me

**Comment by arcadez** [comment]
Yeah deco can really be a case of rob peter to pay paul, ya fix one but break another or many others :)
that's why im glad we found a fix in dassault video so we dont have to touch deco16ic at all

**Comment by grant2258** [comment]
yea just tested here working great mate well done!

https://github.com/grant2258/mame2003-plus-libretro/commit/523314286595d48927c0a1870dbedd33e20a5202

theres is a specific fix in there for boogiewings that why i went up that far in the fixes will leave test it with the other games and see how they fare with it

**Comment by grant2258** [comment]
its up to date as of MAME 0.118u6

**Comment by grant2258** [comment]
ok got it sorted all seems good Ill need to do testing before even considering adding this

**Comment by arcadez** [comment]
Every Deco16 and 32 bit game will be affected i dont envy ya having to test all those :)
