### ISSUE TITLE
About (hardhea2.zip), picture mapping problem?

### ISSUE THREAD

**Issue by ji125443** [libretro/mame2003-plus-libretro#553]
As shown in the figure......
![hardhea2-181219-105024](https://user-images.githubusercontent.com/25021120/50215950-73ec1780-03bf-11e9-9c94-dd1117a64721.png)
![hardhea2-181219-105039](https://user-images.githubusercontent.com/25021120/50215951-73ec1780-03bf-11e9-9602-0e008818f023.png)
![hardhea2-181219-105052](https://user-images.githubusercontent.com/25021120/50215954-7484ae00-03bf-11e9-9719-6ff72ba79759.png)

**Comment by grant2258** [comment]
this game says its not working properly @ji125443  

@markwkidd  the old gui used to tell you this information on why the rom didnt work what rom if any where working. that should be restored or we going to have a lot of threads like this. As it stands now the user wont know what romset works if any do

**Comment by arcadez** [comment]
Seems we just missed it

0.78u5: Luca Elia fixed Hard Head 2 - Game now playable. Changed Z80 CPU1/2/3 clock speeds to 6MHz.

**Comment by arcadez** [comment]
Someone wanna finish this off for me the code is done just need to add into this core.......

Hard Heid 2

https://www.sendspace.com/file/aqmfhf

**Comment by grant2258** [comment]
heid the baw 2 would be a great arcade name! ill add it tomorrow unless mark beats me to it mate.

**Comment by grant2258** [comment]
woke up decided to add it is done and tested mate another job well done cheers. 

Ill get round to testing the code i done for teh deco16ic  no games have had any miss haps so far boogiewings is working fine too with no updated to the driver so is looking good.
