### ISSUE TITLE
Sound issue with Space Invaders

### ISSUE THREAD

**Issue by UDb23** [libretro/mame2003-plus-libretro#562]
In Space Invaders (invaders.zip) I get distorted sounds on the 4 bass tones played in a loop in background.
It's a sort of crackle for a fraction of a second and happens frequently but apparently random.
Using Retropie 4.4, RA 1.7.3 lr-mame 2003plus: 8678668 on a Pi3 B+ (no overclock).
Sample are Twisty's.
Lr-mame2003 with same samples has no distortions.

Recorded sound [here](https://github.com/UDb23/share/blob/master/temp/SI%20distortion.m4a).

**Comment by grant2258** [comment]
can you include the samples for you 2003 plus here. Ill put them on my pi3b plus. Is there anything special i need to do to get this to happen. 

I played about a bit on windows could not recreate this. I dont know if its the recording sounds badd all in to me.

A note on artwork is it on or off for this to happen. If it only happens when artwork is on you might want to reconsider using 1080p artwork on the pi at least.

**Comment by grant2258** [comment]
@UDb23 can you try this and see how you go. 

https://retropie.org.uk/forum/topic/17828/rampage-sound-issue-retropie-4-4/4

**Comment by UDb23** [comment]
Thanks @grant2258 for looking into this.
Samples are [these](http://samples.mameworld.info/wav/invaders.zip).

Followed your suggestion and removed the backdrop zip so the game will start without any mame artwork (but still with RA overlay ): sound now seems ok.
That points to the newly implemented backdrop (mame art) function;  slowing down the game on the Pi and consequently sound gets distorted ? The strange thing is that only that bass sound is involved. Shooting and other samples seem ok even with backdrop. Something related to the code that handles the 4 tone loop ?

**Comment by UDb23** [comment]
Multiple games that had backdrops need samples so this issue may impact these too.

**Comment by grant2258** [comment]
it could be to do with the artwork itself. Ill try test when i get more time. Ill test with the orginal one from mr do and yours. Im wondering if its because your stretching the screen size from what it used to be to somethign else I would need more time to look into it. If its just happening on the pi it will be processing power no doubt

**Comment by UDb23** [comment]
Test done. If backdrop covers only the game area sound work ok!
Also checked with background covering full 1080p with both core provided game area and 960x720: sound issue is there again.
This makes it quite tricky as to get full artwork you need to combine "cropped" backdrop with dedicated RA bezel/overlay to get the final correct look to the game & good sound at same time.
Any chance to optimise backdrop code ?

Anyway it's good to know that there is this workaround for the Pi.
Will create new specific backdrop + dedicated bezel for SI.

**Comment by markwkidd** [comment]
@UDb23 there is a artwork resolution multiplier in the core options, with a default setting of `2`.

2 really is better than 1 for this setting but I'm curious about the sound quality without the artwork being multiplied -- could you try it on `1` to find out?

**Comment by markwkidd** [comment]
@UDb23 completely separate request from changing the resolution multiplier -- could you also try this slightly altered version of your SI backdrop from the repo?

[invaders.zip](https://github.com/libretro/mame2003-plus-libretro/files/2717255/invaders.zip)

**Comment by UDb23** [comment]
Will do and let you know,

**Comment by UDb23** [comment]
@markwkidd Test Results:
res multiplier =1: much better sound (almost ok I would say)
slightly altered version of your SI backdrop: no effect, distorted sound is the same.

**Comment by robertvb83** [comment]
Hmm getting correct bckdrop only with corresponding bezel would be a drawback. I would prefer multiplier=1

Btw. I could not notice any sound issue with my screen resolution 1280 x 1024... i will test in detail and give feedback

**Comment by UDb23** [comment]
@markwkidd What is the meaning of that artwork resolution multiplier in the core option?

**Comment by grant2258** [comment]
you scaling 2x when you render the game bitmap id you set it 2x

normal scale
https://github.com/libretro/mame2003-plus-libretro/blob/e4982998cf04779ac35a09ed92d3339232209d5f/src/artwork.c#L1477

2x scale
https://github.com/libretro/mame2003-plus-libretro/blob/e4982998cf04779ac35a09ed92d3339232209d5f/src/artwork.c#L1505

this also applies to underlays ect

**Comment by markwkidd** [comment]
The artwork multiplier is now 1x by default.

Is there anything else that can be done to resolve this issue?

**Comment by UDb23** [comment]
it seems a Pi performance issue. Workaround being dedicated RA overlay+ backdrop covering only game area. Don't think anything else can be done (unless someone is able to write much faster rendering code)
