### ISSUE TITLE
WIP driver for Mirax

### ISSUE THREAD

**Issue by arcadez** [libretro/mame2003-plus-libretro#566]
Mirax was a game i liked the look of so i backported the driver to MAME84 some 3 years ago now
it was never a target for this core as i couldn't get the sound to work, anyway last night i decided
to revisit it and dink from the FBA dev team to helped me out and long story short it now has
full on sound and music.

So i decided to roll mirax.c back further so we can support it here but for some reason the game
refuses to boot when using my MAME72 test core but since this is not the first time i've had games
not work in that core but they're fine in this one eg B-Rap-Boys, Shogun Warriors and Virtua Fighter
i thought @grant2258  or @markwkidd would you like to add mirax.c to your test branch when you
get a spare moment or so and lemmie know if the game will work in MAME2003+

mirax.c MAME 78 and for comparison 84 drivers

https://www.sendspace.com/file/ju6srl

**Comment by grant2258** [comment]
the game is audio is working and it sounds like the inputs are working ie credits are heard and firing ect.

the gfx arent working at  though at least in 64 bit will test it on the pie in a bit will take a while to compile will see if it works on 32 bit. This all i get on the screen.

![mirax-190104-175557](https://user-images.githubusercontent.com/6128601/50702852-16f09280-104a-11e9-8775-5b71979eb63c.png)

**Comment by grant2258** [comment]
sound isint working right on the pi just garbled noises

**Comment by grant2258** [comment]
getting a few unmapped writes for cpu0

cpu #0 (PC=0000156A): unmapped memory byte write to 0000F900 = C0
cpu #0 (PC=00001051): unmapped memory byte write to 0000F506 = 00
cpu #0 (PC=00001054): unmapped memory byte write to 0000F507 = 00

**Comment by arcadez** [comment]
Hmm this looks like a problem with the CPU IRQ's .?? the setup seems correct i wonder why the 
game works in 84 but not 78 with the same code more or less maybe 78 handles things like this
slightly differently hence the problems...........

O=CPU1  1=CPU2  2=CPU3

Sound CPU to main CPU comms

static WRITE_HANDLER( mirax_sound_cmd_w )
{
	soundlatch_w(0, data & 0xff);
	cpu_set_irq_line(1,IRQ_LINE_NMI, PULSE_LINE);
}

Main CPU to sound CPU comms

static INTERRUPT_GEN( mirax_vblank_irq )
{
	if(nmi_mask)
	cpu_set_irq_line(0, IRQ_LINE_NMI, PULSE_LINE);
}

	ROM_REGION( 0xc000, REGION_CPU1, ROMREGION_ERASE00 ) // put decrypted code there

	ROM_REGION( 0x10000, REGION_CPU2, 0 )
	ROM_LOAD( "mxr2-4v.rom",   0x0000, 0x2000, CRC(cd2d52dc) SHA1(0d4181dc68beac338f47a2065c7b755008877896) )

	ROM_REGION( 0xc000, REGION_CPU3, 0 ) // encrypted code for the main cpu
	ROM_LOAD( "mxp5-42.rom",   0x0000, 0x4000, CRC(716410a0) SHA1(55171376e1e164b1d5e728789da6e04a3a33c172) )
	ROM_LOAD( "mxr5-4v.rom",   0x4000, 0x4000, CRC(c9484fc3) SHA1(101c5e4b9d49d2424ad80970eb3bdb87949a9966) )
	ROM_LOAD( "mxs5-4v.rom",   0x8000, 0x4000, CRC(e0085f91) SHA1(cf143b94048e1ebb5c899b94b500e193dfd42e18) )
	
Protection decryption data share between fake CPU1 and CPU3

static DRIVER_INIT( mirax )
{
	UINT8 *DATA = memory_region(REGION_CPU3);
	UINT8 *ROM = memory_region(REGION_CPU1);

**Comment by arcadez** [comment]
Actually as per dink CPU3 is faked and CPU1 is the real one

**Comment by arcadez** [comment]
Well good news and bad, the good being this actually is as you expected the correct way to handle things..........

ROM_START( mirax )
	ROM_REGION( 0xc000, REGION_CPU1, ROMREGION_ERASE00 ) // put decrypted code there

	ROM_REGION( 0xc000, REGION_USER1, 0 ) // encrypted code for the main cpu
	ROM_LOAD( "mxp5-42.rom",   0x0000, 0x4000, CRC(716410a0) SHA1(55171376e1e164b1d5e728789da6e04a3a33c172) )
	ROM_LOAD( "mxr5-4v.rom",   0x4000, 0x4000, CRC(c9484fc3) SHA1(101c5e4b9d49d2424ad80970eb3bdb87949a9966) )
	ROM_LOAD( "mxs5-4v.rom",   0x8000, 0x4000, CRC(e0085f91) SHA1(cf143b94048e1ebb5c899b94b500e193dfd42e18) )

	ROM_REGION( 0x10000, REGION_CPU2, 0 )
	ROM_LOAD( "mxr2-4v.rom",   0x0000, 0x2000, CRC(cd2d52dc) SHA1(0d4181dc68beac338f47a2065c7b755008877896) )

static DRIVER_INIT( mirax )
{
	UINT8 *DATA = memory_region(REGION_USER1);
	UINT8 *ROM = memory_region(REGION_CPU1);

works a treat in MAME84 however in my 72 test core the game is still not booting i guess it must
be something else maybe the memory map.?? anyway i've been on this for three days now gonna
call it quits for now and work on something else, we might return to mirax.c someday or cut our
losses and just say fuck it :)

**Comment by grant2258** [comment]
Ill double cjeck the memory map it looked good to me. The think is the timing could be different in mame084 and  our an we arent using any interrupt acknowledges ect so its could be the interrupt timing is off. Is this code fullly functional in mame084 ?

**Comment by arcadez** [comment]
Game boots and is fully playable in 84 in 72 i get that green screen on boot, the code is the same more or less between the two builds but i do suspect we are losing an IRQ somewhere hence the stall
when the game should be booting up.

One other thing i noticed is in 78 you have two ways to handle an NMI IRQ command where as in 84 there is only one.

	cpu_set_input_line(1, INPUT_LINE_NMI, PULSE_LINE);

VS 

	cpu_set_irq_line(1, IRQ_LINE_NMI, PULSE_LINE);

or 

	cpu_set_nmi_line(1,  PULSE_LINE);


on spec i tried using the alt version on both then one or the other but same deal

**Comment by arcadez** [comment]
Fuck it!! just dump mirax.c im sick of looking at it :) add it to the it wont work in this core 
for some reason list.

**Comment by grant2258** [comment]
well found something of interest i put debugging on

[libretro ERROR] [MAME 2003+] Error in InputPort definition: expecting PORT_START

a few times.

check if i fooked anything up mate

https://github.com/grant2258/mame2003-plus-libretro/blob/input_fix/src/drivers/mirax.c

its possible if the dipswitches arent right the game wouldnt boot

**Comment by markwkidd** [comment]
You could try to run it in MAME standalone to get an NVRAM file and put that in place here to see if it gets you place a place where some initialization is failing. (I say as the MAME driver rookie.)

**Comment by grant2258** [comment]
its not in mame078

**Comment by grant2258** [comment]
the rom has no nvram loading at that 106 or 132 im pretty sure it the input ports 078 probably needs them wrapped around a
static PORT_READ_START( mirax_readport )
	{ 0xf000, 0xf000, input_port_0_r },
	{ 0xf100, 0xf100, input_port_1_r },
	{ 0xf200, 0xf200, input_port_2_r },
	{ 0xf400, 0xf400, input_port_3_r },

PORT_END

or something along them lines

**Comment by grant2258** [comment]
odd i cant reproduce this now must be a problem somewhere seemed to borked sometimes and not others. Ill file this as a mystery like you. I think its something to do with the interrupts to be fair.  Even robocops credit sound doesnt work cant seem to trace that at all.

**Comment by arcadez** [comment]
It's defo a problem with our Z80 CPU not being compatible most likely with the op-codes
in the driver i'll check it out vs MAME84

**Comment by arcadez** [comment]
Moving on to other things :)
