### ISSUE TITLE
Ability to access Mame input menu when using keyboard input type

### ISSUE THREAD

**Issue by voodoo84** [libretro/mame2003-plus-libretro#571]
Being aware of technical differences between "retroarch" and "keyboard" input methods, I'm using keyboard input, which is natural because I'm playing on a computer. Plus it's really handy to have standard Mame shortcuts such as Tab, F2, start on 1-4, insert coins on 5-8 etc.

But, there is no access to keyboard remap menu as there was in regular Mame. I still have to go through pad mapping abstraction which can really get confusing at the moments.

Would you care to add access to Mame's standard "Player # controls" into Tab menu, which would greatly simplify the process? Is it even possible because of the Libretro API?

**Comment by grant2258** [comment]
goto options Legacy Remapping (!NETPLAY) and enable it. Be aware not to use hotkeys.

 You can get round this by using game focus or set enable hotkeys so you have to press what thats set to and the hotkey

**Comment by voodoo84** [comment]
Fantastic, thank you. Please don't remove "legacy remapping" option ever!
