### ISSUE TITLE
is warriors backdrop of appropriate quality

### ISSUE THREAD

**Issue by markwkidd** [libretro/mame2003-plus-libretro#574]
Hi @UDb23 -- is the warriors artwork OK to keep in here?

I want to make sure you know that just because I added it as a sample for development purposes doesn't mean that I believe that version of the artwork is a masterpiece or anything like that.

If it should be replaced and you are in the mood feel free to add it to your list. Thanks for your work on this!

**Comment by grant2258** [comment]
not everything has to be 1080p the gfx arent that detailed unless you think it looks bad as is

**Comment by UDb23** [comment]
Considering it is a fluo and background, even if somewhat blurry, I think it is ok. Maybe some areas like the round and square logo could be enhanced a bit.
Did a quick search and no higher res image (or photo to use to recreate) is available.
Unfortunately for these old games it's often quite difficult to get good quality images/scans of the original backdrop cardboards or bezels. In some cases was able to get photos from owners of the real thing ,but majority would not even bother to answer mail or PM.

**Comment by UDb23** [comment]
You're lucky! just found good quality scans of that backdrop.
It's actually made of multiple cardboard parts on top of each other.
Now I need to find out how the actual "global composition" should look !
Got a youtube low res vid as a reference. It looks somewhat different from Mr Do's ...
