### ISSUE TITLE
Some games don't honor the Timing Skew settings

### ISSUE THREAD

**Issue by vanfanel** [libretro/mame2003-plus-libretro#575]
Hi there,

Some games, like Pang and Super Pang, Hamering Harry, etc.. are not adjusted to the host's framerate even if Max Timing Skew is set to a high enough value.
These games have their framerate adjusted in the FBA core with the same settings.
Is this known/intended on this core?

**Comment by grant2258** [comment]
there is an option for this if you want to use the timing skew. The games do run properly as is but if you insist on idealism an option has been added fixing the timing skew in ra is the user responsibility.

Bypass audio skew (Restart core)

**Comment by vanfanel** [comment]
@grant2258 : Thanks for the response! Got it to work, no issue here so I'm closing this. Thanks!!
