### ISSUE TITLE
Overlays cover on-screen display (OSD)

### ISSUE THREAD

**Issue by Wilstorm** [libretro/mame2003-plus-libretro#581]
When using game overlays they cover the Retroarch OSD. Everything works fine but the text is 100% covered by overlays unless you set the opacity lower then you can see it's actually back there. Is there a way to move the OSD so it's on top when using overlays. I am on RetroPie 4.4.4 RA 1.7.5 - commit 8ff5a43.

**Comment by markwkidd** [comment]
This is almost certainly a RetroArch bug but I'll see if anyone else here has an idea that it might come from within the core

**Comment by Wilstorm** [comment]
Ok, just let me know if you need me to open a issue with Retroarch I can do that also.

**Comment by markwkidd** [comment]
@Wilstorm I will go ahead and say I'm pretty sure this is a frontend issue. Would you go ahead with a RetroArch issue report? IMO it would be particularly effective if you could get a screenshot of the bug.

**Comment by Wilstorm** [comment]
@markwkidd - Just post on Github - Libretro / RetroArch? I don't know if there's much in the way of a screenshot. I press the "Pause" hotkey combo for example and the OSD message isn't available to view. Basically the screenshot would be just the game screen if that makes sense.

**Comment by markwkidd** [comment]
Ah ok. I thought there might be situations where the text was only partially hidden. Thanks.

**Comment by Wilstorm** [comment]
@markwkidd - If you set the opacity to say 50% then it does show through but that looks like the regular message but lighter due to the opacity. Maybe that would be useful?

**Comment by Wilstorm** [comment]
Mark I opened an [issue](https://github.com/libretro/RetroArch/issues/7989) on the RA page.

**Comment by markwkidd** [comment]
Thanks for getting this located where it needs to be. It's been confirmed as an RA issue over there, so are you OK closing this one? It's out of our hands I'm afraid.

**Comment by Wilstorm** [comment]
@markwkidd - Sounds good and thanks. I will close this out.
