### ISSUE TITLE
well thats me banned form retropie forums

### ISSUE THREAD

**Issue by grant2258** [libretro/mame2003-plus-libretro#583]
Ill just be checking here for issues. I wont be fixing any retropie problems specifically. ill put more time into lakka where the devs are level headed.

maybe he is from london hmmm mind boggles lol
https://retropie.org.uk/forum/topic/18856/crackling-sound-mame2003/21

**Comment by markwkidd** [comment]
:( I think I may try to spend less time on that forum myself. It's a great
project but I don't like that it's making me grumpy at times.

It's just a hobby I say. It's not worth losing sleep, I tell myself

**Comment by grant2258** [comment]
amen to that mark wont loose any sleep in all honesty

**Comment by arcadez** [comment]
Fuck that crappy lamer forum :)

**Comment by Wilstorm** [comment]
@grant2258 - Wow, I guess the friendly holiday season and cheer is over. =/

**Comment by grant2258** [comment]
yea will close this old news hopefullly the forums are helpful to users i wont be wasting time supporting the project in any shape or form

**Comment by grant2258** [comment]
yea will still be doing work on the core just from the retroarch frontend point of view. They will need to fix any specific retropie issues themselves no need for end users to suffer at al they can just put the work in when and if its needed.

**Comment by Wilstorm** [comment]
That sounds great. Really my main reason is for the retro-gaming, the consoles are just a nice bonus. You have had me thinking for months now (from a comment you made long ago) that at some point, when the price is right, I plan to build a much more powerful micro rig and run current MAME. I have had some of the best times with this older core for sure though and plan to use for a long time to come. I still get a bit awe struck when I see all these games running on that tiny Pi.

**Comment by Wilstorm** [comment]
@grantt2258 - You've been unbanned from the RP forums. I just found out from mitu who corrected me that I was wrong when I said you had been. Yay Grant! ;)

**Comment by grant2258** [comment]
Welll to be honest im pretty much done with the retropie end(not the users some of the mods). Ill help users all I can in here if they post issues. I was banned dont know by whom or who undone it doesnt matter in the big picture. Ill help users on here I can.,

**Comment by Wilstorm** [comment]
I understand what you're saying but I'm glad you have that option available if you want to utilize it though. Someone understands your value to the Plus project, which really is a cornerstone or a triangle...you guys are a trifecta! ;)

**Comment by grant2258** [comment]
lol just want no drama @Wilstorm not saying i wont go to any links posted if pointed to them. If there is bugs on the pi they do need addressed. The good thing is we have lots of platforms running on arm bugs will show up when they are there. mitu is one of the good ones on the forum i like that dude

**Comment by Wilstorm** [comment]
That sounds great and I agree I like mitu too, very friendly. :)
