### ISSUE TITLE
SH2 CPU

### ISSUE THREAD

**Issue by arcadez** [libretro/mame2003-plus-libretro#596]
I just dropped a small speedup for the SH2 CPU from MAME79 into our core, i'd be keen to hear back at some point from users on lesser hardware eg the Rpi etc etc if any of the following games perform any better or have indeed got broken in the process......

Avengers In Galatic Storm
Lode Runner - The Dig Fight
Sol Divide - The Sword Of Darkness
Strikers 1945 II
Strikers 1945 III
Gunbird II
Daraku Tenshi - The Fallen Angels
Dragon Blaze
Die Hard Arcade
Cotton 2
Cotton Boomerang
Guardian Force
Cyvern
Sengeki Strikers
Gals Panic 4
Gals Panic S2

**Comment by grant2258** [comment]
Avengers In Galatic Storm ranfull fps  for me on the pi3b+ anyway but ill give the rest a whirl and let you know if any of them run slow. Ill get back to you on that.

**Comment by robertvb83** [comment]
I am on RPie 3B+

Most of the games worked just fine before the changes.

However i tested cotton 2. Before update it was unplayably slow with seconds of input lag. This became significantly faster after updating. Unfortunately it is still unplayably slow!

So yes the speed has increased but games that played well before are still fine, games that were unplayable are faster now but still not in the playable range

**Comment by grant2258** [comment]
soory been a bit busy with coding and getting the car ready for its mot tomorrow ill test on the pi3B+ and let you know how i go thats the fastest one atm I havent forgot
