### ISSUE TITLE
submitting CFG and NV files that unlock controls

### ISSUE THREAD

**Issue by markwkidd** [libretro/mame2003-plus-libretro#604]
Some games require changes to their dipswitches or service menus to enable all of the player control sets that they can support.

While we are not at the moment adding these kinds of bootstraps to the nvram bootstrap system, I am instead welcoming submissions of `cfg` and/or `nv` files for those games. Submissions will be stored within the `metadata` folder of this repository to make it possible for users to download and install them, thereby bypassing the configuration process.

@Wilstrom has agreed to submit at least these one or two in order to serve as a model. Thanks again! Other folks are very welcome to do as well,as this is not a project I'll be leading myself.

**Comment by markwkidd** [comment]
Possibly spacewar is a candidate for this: https://github.com/libretro/mame2003-plus-libretro/pull/617#issuecomment-456426932

Frankly spacewar is more like the nvram bootstraps than adding additional controls... it apparently doesn't appear to the user to be working unless dipswitch ports are mapped

**Comment by grant2258** [comment]
nvram has nothing to do with this issue.  it was code that was being disabled for none legacy in the  ui mode thats since been fixed. 

https://github.com/libretro/mame2003-plus-libretro/blob/fa03fe1414cbc3ef18c93ffbdd354bd16551f432/src/drivers/cinemat.c#L262-L277

**Comment by Wilstorm** [comment]
Here's a list of games that potentially need additional players unlocked. Such as games that default to 2 players vs. 4, etc. Like Dungeons & Dragons: Shadow over Mystara has only 2 players by default but it's nice to have all 4 characters to choose from when playing.

```
Captain America and the Avengers (.cfg)
captaven.zip
captavna.zip
captavne.zip
captavnj.zip
captavnu.zip
captavuu.zip

Captain Commando (.cfg)
captcomj.zip
captcomm.zip
captcomu.zip

Dungeons & Dragons: Shadow over Mystara (.nv)
ddsom.zip
ddsoma.zip
ddsomj.zip
ddsomjr1.zip
ddsomr1.zip
ddsomu.zip
ddsomur1.zip

Karate Blazers (.cfg)
karatblu.zip
karatblz.zip

Mystic Warriors (.cfg)
mystwarr.zip
mystwaru.zip

The Combatribes (.cfg)
ctribe.zip
ctribeb.zip
```

**Comment by Wilstorm** [comment]
I put ```.cfg``` or ```.nv``` after the game list to note if the tweak needs to happen from the dip switch settings in the TAB menu (.cfg) or F2 menu (.nv).

**Comment by Wilstorm** [comment]
Speaking of games @markwkidd had listed Space War above which is a great vector game but I don't think it works correctly in this core. 

Most of the best vector games already work but this is one of those beauties that was skipped due to the start option inputs I would guess. It would probably require some OSD for the buttons 0-9. I tried it but there's to many buttons to map to a controller or panel but it is a true classic for 2 players.

**Comment by mahoneyt944** [comment]
@Wilstorm  can you update from source and test these?

max players fixed
- nbahangt
- nbamaxht
- openice
- captaven (all versions)
- karatblz (both versions)
- mystwarr (both versions)
- viostorm (all versions)
- metamrph (both versions)
- ddragon3 (all versions)
- ctribe (both versions)

**Comment by mahoneyt944** [comment]
Moved to #875
