### ISSUE TITLE
todo: input core options re-engineering

### ISSUE THREAD

**Issue by markwkidd** [libretro/mame2003-plus-libretro#621]
Because I rely on issues for my own organization, I'm creating this one to track the obvious need for me to re-engineer some of the input-related core options.

https://github.com/libretro/mame2003-plus-libretro/issues/619
https://github.com/libretro/mame2003-plus-libretro/issues/609

**Comment by markwkidd** [comment]
https://github.com/libretro/mame2003-plus-libretro/pull/617#issuecomment-456437534

**Comment by grant2258** [comment]
@markwkidd one thinh that needs to change is before the quickmenu ->controls where used to change the mame global mapping. Now they are per game basis so the structure should be read from the mame game input structures

**Comment by grant2258** [comment]
https://github.com/libretro/mame2003-plus-libretro/pull/630

pretty much fixed all these issues apart from the ra stuff like fingers not showing up on some games.

**Comment by mahoneyt944** [comment]
@markwkidd I think this could be closed now.

**Comment by markwkidd** [comment]
makes sense to me!
