### ISSUE TITLE
put flac support behind PS3 ifdefs or switch to libFLAC with PS3 ifdefs

### ISSUE THREAD

**Issue by markwkidd** [libretro/mame2003-plus-libretro#622]
According to @twinaphex in order for the cores to build on PS3 we can compile in FLAC support for PS3 but we will need a version of libFLAC with ifdefs for PS3. There may already be a core that has such a libflac.

The alternative would be to use some #ifdefs to remove flac from the PS3 build only. Because FLAC is not my code, I'm in favor of this second, simpler option. At least in the short term. @grant2258 this is your work -- do you have an opinion?

**Comment by grant2258** [comment]
dont care what you do with it and it isint my work per say gpstar done the original code up and i added libretro libflac to our port and fixed the issues it had. I dont really mind what you do with it.

**Comment by markwkidd** [comment]
do you remember which repo you sourced the libretro libflac port from?

**Comment by grant2258** [comment]
twinaphex gave me the link

**Comment by markwkidd** [comment]
nice, thank you. I'd like to see if we can address this upstream, again even if it is to disable flac for PS3, but to do it in that repo

**Comment by markwkidd** [comment]
new issue for discussion https://github.com/libretro/libretro-deps/issues/8

**Comment by grant2258** [comment]
http://p.0bl.net/83548 i dont even see any errors maybe the makefile needs fixed ?

**Comment by grant2258** [comment]
what the issue with libflac in mame2003+ i cant see any errors on the build log or linking errors
all there is at the end is COPY CMD: cp -v ./mame2003-plus_libretro_ps3.a /home/buildbot/buildbot/ps3/dist/ps3//mame2003-plus_libretro_ps3.a
cp: cannot stat './mame2003-plus_libretro_ps3.a': No such file or directory
/c/usr/local/cell/host-win32/ppu/bin/ppu-lv2-ar.exe q mame2003_plus_libretro_ps3.a src/sound/ymdeltat.o
notice the problem ?
mame2003-plus_libretro_ps3.a and mame2003-plus_libretro_ps3.a
is a filename miss match

just pasted this from libretro so your up to date

**Comment by grant2258** [comment]
think the fix goes here not sure what all  the fields are for
https://github.com/libretro/libretro-super/blob/8f96f2e2d0fcf0d838b64fd950e443f8fdda4357/recipes/playstation/ps3#L25

**Comment by grant2258** [comment]
put a pull request in to fix this 

https://github.com/libretro/libretro-super/pull/945

you can close this once its pulled

**Comment by grant2258** [comment]
we can close this one here and leave the one on libretro deps open mark its fixed compiles fine was the buildbot that needed a fix

**Comment by markwkidd** [comment]
Thanks!
