### ISSUE TITLE
Risky Challenge WIP

### ISSUE THREAD

**Issue by arcadez** [libretro/mame2003-plus-libretro#627]
One of Irem's finest games is Risky Challenge, i didn't think it was possible to get it to work in
older cores such as this due to incompitable changes to the NEC CPU, we cant use configs via
the CPU init in MAME78, plus apart from that the workload would have been huge anyway
that's if i had gone about things the "correct way"......

https://github.com/dinkc64/mame/commit/b469de6db7d6f578b75abe75fdb477ed0438e545#diff-ec7525c4b8833e6b25229b07367eb28c

99% of Irem games have encrypted CPU's the code for which was hacked long ago and MAME
boots the games via decrypted tables in irem_cpu.c, this leaves the other 1% eg Risky Challenge
for example which expects part of the code to be unencrypted while also at the same time 
like the other Irem games to be encrypted as well hence why it didn't work until the above commits.

So how did i get it going you might be thinking.?? or not.?? anyway im gonna tell ya's either way :)
via the most atorcious of hackyness, pre the game working MAME dev were debugging it via
some code in irem_cpu.c

    /* robiza note:
	 for "gussun" and "riskchal" is necessary an hack to not decrypt not encrypted routines
	 we need a real nec v25+/35+ core to support 0x63 (brkn for "break native") instruction
	 for now we use "cd" (int) instruction + hack */

	if (m90_game_kludge==1) /* for riskchal */
		{
			for (A = 0xa8fd;A < 0xa90c; A++)
				rom[A + diff] = rom[A];
			for (A = 0x12b3a;A < 0x12b4b; A++)
				rom[A + diff] = rom[A];
			for (A = 0x13500;A < 0x13510; A++)
				rom[A + diff] = rom[A];
			for (A = 0x14be5;A < 0x14bf5; A++)
				rom[A + diff] = rom[A];
			for (A = 0x130de;A < 0x130eb; A++)
				rom[A + diff] = rom[A];
			for (A = 0x147a4;A < 0x147bf; A++)
				rom[A + diff] = rom[A];

		}
	if (m90_game_kludge==2) /* for gussun */
		{
			for (A = 0xa8fd;A < 0xa90c; A++)
			    rom[A + diff] = rom[A];
			for (A = 0x1369c;A < 0x136ac; A++)
				rom[A + diff] = rom[A];
			for (A = 0x14ec8;A < 0x14ed8; A++)
				rom[A + diff] = rom[A];
			for (A = 0x13246;A < 0x13253; A++)
				rom[A + diff] = rom[A];
			for (A = 0x14a7d;A < 0x14a98; A++)
				rom[A + diff] = rom[A];
		}

}

So on spec i added this code then updated the gussun decryption table and finally added the brkn
command to the nec CPU and bingo to my surprise the game booted and is fully playable, although
for now it does have some small gfx niggles the worst being the water as it rises up the screen being
transparent when it should be blue, i hope to fix this shortly although since the graphical code
changed when they updated the NEC CPU to a 16-bit data bus im struggling to rollback the
changes to the y-scrolling required to sort this, i may have to round up my ole buddy dink
to help advice me here.

To be on the safe side just to make sure the hacks dont negatively affect all the other Irem games
which dont need em i decided to seperate em off into another decryption table that only
Risky Challenge will use, i've also tested a good whack of em and they all passed with flying
colours despite the small break instruction changes to the NEC CPU.

Still Awake :)

@grant2258 could you possibly run a wee debug on Risky Challenge for me.?? there seems to be a
slight bug for those of an impatiant nature where as the game will crash sometimes if you press
a button to skip by the highscore calc screen between levels quicker, as dink thought it might be
a dip issue but if indeed it's as i suspect a side effect of the hacky CPU workaround then nothing
can be done i dont think, still it would be good to know what's causing this crash if possible.

Anyway should you not press any buttons while the game is on the high score screen between levels
then you'll be fine, lastly the jap clone Gussun Oyoyo doesn't work right with the hacks as unlike
Risky Challenge it can reset randomly after you complete a level so i've left it as not working

Thanks for reading if you got this far :)

**Comment by grant2258** [comment]
Ill have a wee look will need to get the roms. I did update our ire encryption tables to  a higher mame version just went high enough to fix ninja base ball batman sound. Ill have a look should be able to trace it if it does crash.

**Comment by grant2258** [comment]
it does seem to be freezing itself but there was no segfault or anything you ill put a little more time into this on the linux box its better for debugging

**Comment by arcadez** [comment]
Yeah it doesn't do this in FBA so likely a wee bug, i'll look into fixing this down the road, currently with
dink im working on trying to add the video code to fix the water colour but it's not straight forward
as to how they handle this in later MAME vs our ole core.

**Comment by arcadez** [comment]
hmmm @grant2258 since you updated the irem decryption files that will likely have fixed a number
of games over and above Ninja Baseball Batman, Match it II / Shinsen- Shou II should actually be
playable it would be worth booting it up to see sometime and promote it to working.

**Comment by grant2258** [comment]
yea its the sounds that fecks up on most of them

**Comment by arcadez** [comment]
Aye that's Shinsensho II working now, apart from your opcode changes all it needed was the 
input and dips added.
