### ISSUE TITLE
Artwork files overwriting existing artwork files

### ISSUE THREAD

**Issue by Wilstorm** [libretro/mame2003-plus-libretro#629]
@markwkidd - I was wondering if the artwork is overwritten after every update or the frequency? If it does frequently would it be beneficial to only copy the artwork files from the metadata if it doesn't exist in the artwork folder?

I usually tweak overlays/artwork brightness settings as I don't like them to bright or another scenario is using 3rd party artwork vs. the default artwork in game. I actually prefer UDb23's "UV2" backdrop vs the one that's in the Omega Race archive as the default so I have to manually create my own artwork file as he has 3 options for Omega Race.

I know this doesn't address updates to artwork as people would need to manually copy them over but it it's automatic it wipes out tweaked settings and alternate artwork so maybe a prompt to overwrite or a core setting possibly that defaults to ```No```.

**Comment by grant2258** [comment]
you might want to post this on the retropie github issues https://github.com/RetroPie/RetroPie-Setup/issues

**Comment by Wilstorm** [comment]
Ha! You know as well as I do that will just get you in hot water. =/ He closes issues and redirects you to the forums immediately.

I thought this was a core feature. Art is submitted to the core updates directly. I don't think RetroPie is copying the artwork from the metadata folder to the BIOS/mame2003-plus/artwork folder.

**Comment by grant2258** [comment]
at saying that ill se what mark things about separate configs for the modes. It a lot of extra files as well though. That why ill take it under advice. You cant expect two use both system I personally only use legacy mode to be honest.

**Comment by Wilstorm** [comment]
I am not quite sure what you're saying above. Was this meant to be in the other thread?? 

The only thing I am saying as new artwork is submitted to Plus through a PR it overwrites my existing artwork. I was hoping we could maybe A) not overwrite files that already exist and/or B) maybe a core option set to disabled as default and when enabled will overwrite the existing Plus artwork and/or C) a confirmation box before overwriting all artwork.

**Comment by grant2258** [comment]
was the wrong thread ill delete it sorry

**Comment by Wilstorm** [comment]
Ok, I kind of like the idea of a core option that when enabled will overwrite artwork when updated or however that script is triggered. I think I'll leave it up to Mark's discretion if he wants to leave it as is or change it at all.

I don't think Buzz likes folks posting over there until a thread has been setup and discussed on the RP forums. I have to be honest I really like what Mark wrote on the RP forums about being a peer to Buzz and I just as soon let him discuss any suggestions or changes in that thread since he is already posting in there.

**Comment by Wilstorm** [comment]
I just created a home folder with alternate @UDb23 backdrop artwork and tweaked brightness settings then created a small script I can run anytime to copy them to the Plus artwork folder. Others with similar issues may do the same or just use the default artwork as is.
