### ISSUE TITLE
Option to set analog deadzone radius.

### ISSUE THREAD

**Issue by rsn8887** [libretro/mame2003-plus-libretro#633]
I would like to request a core option to set the analog deadzone in percent, instead of hard-coding it to always 20%, which is quite large IMO.

**Comment by grant2258** [comment]
ok ive put your option on as default. 

ps you will know when you joystick needs a higher deadzone if the keyboard controls dont work while playing an analog game in mame

**Comment by mahoneyt944** [comment]
@rsn8887 please close this issue unless you still need help with this topic.
