### ISSUE TITLE
update some games to current MAME names

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/mame2003-plus-libretro#641]
puyopuyo.zip > puyo.zip
ichidant.zip > ichir.zip
spidey.zip > spidman.zip

**Comment by arcadez** [comment]
Not sure what ya wanna do here i assume you want to change the romnames in the drivers
which support them so they match up with current MAME builds.?? keep in mind if this was
to be done everyone would need to have the renamed roms or they would not show in
the romlist.

I could see many bug reports around games have disappeared from my romlist should we
go down this route.

**Comment by grant2258** [comment]
agree with arcadez it probably different romsets as well changing the name wont make newer romsets work.

**Comment by arcadez** [comment]
Yeah defo in the case of Puyo Puyo we only support the English bootleg puyopuyo.zip for example
in current MAME puyo.zip is a totally different version of the game.

**Comment by arnoldsecret** [comment]
maybe supporting both romsets so that newer ones can go along with older ones?

**Comment by grant2258** [comment]
that would be pointless if you updated the drivers why would you use the old ones

**Comment by arnoldsecret** [comment]
closed due to lack of interest.
