### ISSUE TITLE
MS32 games - low fps

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/mame2003-plus-libretro#646]
Tested on bbbxing and gratia.

**Comment by grant2258** [comment]
yea there is something funky happening could be cpu speed related

**Comment by arcadez** [comment]
It's related to the changes to the V60 CPU core we need to remove the divider, then check for
other games using it :)

**Comment by grant2258** [comment]
./src/drivers/model1.c:508:    MDRV_CPU_ADD(V60, 16000000)
./src/drivers/multi32.c:700:    MDRV_CPU_ADD(V60, MULTI32_CLOCK/2)
./src/drivers/system32.c:2077:  MDRV_CPU_ADD(V60, MASTER_CLOCK/2)

do we need to remove the divider in ther other two ? to fix the sound it would require a  YMF271 sound core update

**Comment by arcadez** [comment]
Nope as in those two the divider is done via the driver rather than the CPU.....

#define MASTER_CLOCK		32215900

**Comment by grant2258** [comment]
ah ok cheers matey ill look into the soundcore update as my next possible thing to do. It really confusing at times they way they work with the clocks in drivers

**Comment by grant2258** [comment]
updated to soundcore to mame 086  playable without having to mute your sound now. Arcadez fixed the speed already so can close this thread now

**Comment by arcadez** [comment]
Nice work bigman!! let's close this one down then

**Comment by grant2258** [comment]
well still seemed bland went a little one better ive include the soundcore filesand a small mp3 of how gratia sounds with it for you if you want to update you older cores.

[ymf271.zip](https://github.com/libretro/mame2003-plus-libretro/files/2834925/ymf271.zip)
