### ISSUE TITLE
No D-Pad control after update

### ISSUE THREAD

**Issue by qthegaijin** [libretro/mame2003-plus-libretro#652]
Updated from source, now no controllers D-Pad work in game, only the analog controls. Changing settings in retroarch seems to do nothing.

Is this from the analog controller addition? Is there a way to turn it off? 

Changing the setting in Options to Digital Only doesn't change the behavior either...

I will do a recompile from scratch and report back.

**Comment by grant2258** [comment]
1) delete your savefiledir/mame2003-plus/cfg  contents there been a lot of updates .

 mame works 100% in native mode legacy(tab menu),  none legacy is very incomplete.

**Comment by janderclander14** [comment]
Just to add that after the latest updates, I got a segmentation fault error when running 4-way games (such as pacman). Runcommand log states line 1007: 16318

**Comment by grant2258** [comment]
did you delete your  savefiledir/mame2003-plus/cfg dir? 

You have to be careful when compiling if you dont do a clean compiles changes to the menu structure will cause segfaults if you dont clean compile. Input structure changes have the same issues if certain ones are changed.

for example here 
https://github.com/libretro/mame2003-plus-libretro/blob/ad16a1e86afdd061746d868e0cb7594e700c1197/src/mame2003/mame2003.c#L73-L110

and here

https://github.com/libretro/mame2003-plus-libretro/blob/ad16a1e86afdd061746d868e0cb7594e700c1197/src/input.h#L20-L122



If youve done all the above can you post a log what settings your using and what game is segfault for you.  im assuming your using a PI by the Runcommand.log.

**Comment by grant2258** [comment]
scratch that ist crashing in windows thats really odd that part of the code wasnt touched at all ill have a look into the 4 way crashes

**Comment by grant2258** [comment]
@markwkidd seems this is causing issues

https://github.com/grant2258/mame2003-plus-libretro/blob/cb0d50f3a539705e87f3c6308914a16b23919aaf/src/mame2003/mame2003.c#L1539

was libretro-common changed?

**Comment by grant2258** [comment]
@janderclander14 found the issue for the 4way causing this a pull request is in its a one line change if you want to do it yourself or just wait for the pull request to be done.

**Comment by qthegaijin** [comment]
After a completely new compile and clearing out all folders, switching to Digital now enables the D-Pad. I have yet to test Pacman, etc out yet but it appears that everyones on top of that already.
