### ISSUE TITLE
Issue dump

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/mame2003-plus-libretro#657]
All games tested on PS4 controller.

birdtry - ball, player, cloud graphics problem
bigrun - priority problems, fixed in newer MAME version
blueshrk - no targeting reticule
~~boothill - no way to aim gun~~
~~bowler - trackball sensitivity low, fouls everytime ball crosses dotted line~~
champbb2 - green screen
~~copsnrob - no way to move car~~
cgangpzl - hangs on bootup screen
~~crater - can only move right or left, no way of tuning tank~~
~~dangerz - moving the turret up/down all the way, screen jumps up/down~~
demoneye - wrong colors
~~dotron - can't move target reticule~~
exterm - high hz sound when booted up
finallap - black track
findout - wrong colors
fourtrax - priority problems
gametngk - double sprites, priority problems
gstriker - priority problems
gslgr94 - menu graphic issue
~~gunbustr - can only move cursor, can't move player~~
~~hardyard - retroarch crashes when in-game~~
hitme - no card graphic
huncholy - doesn't get past bootup
minferno - flashing fire graphics
~~ixion - no way to aim turret~~
vshoot - glitchy menu, needs optimizations
knckhead - glitchy controls
~~kroozr - right stick doesn't work~~
logger - delayed timing, jitter on player when climbing ladders
looping - fluctuating frames
m79amb - no targeting reticule
machbrkr - glitchy controls & graphics
medlanes - bg color should be black
~~montecar - can't shift gear~~
nebulray - bg glitch
nyny - fluctuating frames
otwalls - racket and player control simultaneously
orbit - stuck on select game screen
pignewt - stuck on glitched graphic
poundfor - can't navigate menu
quarterb - stuck on initial input
~~radm - wheel too sensitive~~
radr - stuck on networking check
redalert - static noise
~~roadriot - can't turn vehicle~~
~~rrreveng - wheel too sensitive~~
seawolf - no targeting reticule
seawolf2 - no targeting reticule
sharkatt - crash by the time game start
~~shuffle - trackball sensitivity low, fouls everytime ball crosses dotted line~~
~~slither - cmos invalid~~
snakepit - whip and player control simultaneously
~~spcenctr - hooked up the same controls as lightgun/trackball~~
spacefev - can't get past game select
~~spacewar - can't start game~~
~~sprint4 - can't shift gear~~
starblad - missing graphics
subs - can't move player
~~sundance - none of the controls work besides coin and start~~
sws96 - menu graphic issue
sws97 - menu graphic issue
suzuka8h - road graphic issue
suzuka8h2 - road graphic issue, brake lever not hooked up
~~tailg - hooked up the same controls as lightgun/trackball~~
~~term2 - no targeting reticule~~
tetrisp - double sprites on menus
thief - glitched-up walls
topsecx - bottom screen cut-off
trivquiz - wrong colors
trivtwo - wrong colors
~~tron - can't aim in most games~~
turbotag - can't drive down
undrfire - no targeting reticule
~~videopin - none of the controls work besides coin and start~~
~~viper - turret only goes up or down~~
~~wacko - fire and move control simultaneously~~
~~warrior - can't move sword aim~~
~~zwackery - can't hit left or right~~

*Update - crossed out control issues fixed through mame tab menu

**Comment by grant2258** [comment]
@markwkidd im expecting a lot more posts like this because users no longer have notifications.

@arnoldsecret i went to check the first one in the list and its marked as un-emulated protection

There is no way im hunting and going though all that list when mame used to tell users when they had bad drivers  untill it was decided to disable on screen. I do appreciated the list but until the information is presented like it used be im not wasting my time manually looking every one up.

**Comment by grant2258** [comment]
@arnoldsecret use legacy mode and press l3 to access the mame tab menu to see what controls are set for games. and set you controls up there if you dont like how the are. The is no way to do this in none legacy mode unless its direction button or a normal mame button.

ie  zwackery dial is mapped to keys z/x

**Comment by arcadez** [comment]
Most of the games mentioned on that list are just inputs that need to be setup by the user on
their end, however there are some which could be improved and or fixed by backporting code
from newer MAME cores problem is we dont have the time to do em all :)

**Comment by grant2258** [comment]
speaking of porting mr acrades i have another pressie for you. Im still testing this as it used in a lot of games. 

I updated fm core of the ym to  mame 0127 no small task doing this eithe. robocop now  has its missing sounds back back ported from.
[newfm.zip](https://github.com/libretro/mame2003-plus-libretro/files/2841191/newfm.zip)

**Comment by arcadez** [comment]
Brave man!! i always tended to steer clear of soundcores as much as possible due to the testing
required afterwards, i updated the YM2151 once then spent days testing every game that used it
which was no small number never again :)

So what sounds in Robocop were missing.??

**Comment by grant2258** [comment]
the credits and the sounds when you get an item like bullets ect

**Comment by arcadez** [comment]
Nice work bigman!! i have no other projects on the go i'd use the code in currently but it'll
always be here in this core should anyone want it for another project.

**Comment by arcadez** [comment]
undrfire - no targeting reticule

I could never get the crosshair to show when using MAME on the xbox although i've seen
Underfire in later MAME vids on youtube with it, the code is unchanged in the driver so i assume
you add it via another method..??

Anyway there is a fake dip linked to vidhrdw/undrfire.c which i think was supposed to hack a
crosshair onto the screen in older MAME but all i get is a message on screen no crosshair
so im wondering does it show in this core..........

	PORT_START	/* Fake DSW */
	PORT_BITX(    0x01, 0x00, IPT_DIPSWITCH_NAME | IPF_TOGGLE, "Show gun target", KEYCODE_F1, IP_JOY_NONE )
	PORT_DIPSETTING(    0x00, DEF_STR( No ) )
	PORT_DIPSETTING(    0x01, DEF_STR( Yes ) )
INPUT_PORTS_END

**Comment by grant2258** [comment]
@arcadez the code needs to be in the driver usually the video code for this to work. like operation thunderbolt.

here is the code it calls 

https://github.com/libretro/mame2003-plus-libretro/blob/6a252a14b22c6e793f765cbbe3b89daeb7139b3c/src/drawgfx.c#L3519-L3537


https://github.com/libretro/mame2003-plus-libretro/blob/6a252a14b22c6e793f765cbbe3b89daeb7139b3c/src/vidhrdw/othunder_vidhrdw.c#L313

**Comment by grant2258** [comment]
newer mames seem to have port support for input tags

	PORT_START_TAG(P1X_PORT_TAG)
	PORT_BIT( 0xff, 0x80, IPT_AD_STICK_X ) PORT_CROSSHAIR(X, 1.0, 0.0, 0) PORT_SENSITIVITY(25) PORT_KEYDELTA(13) PORT_REVERSE PORT_PLAYER(1)

	PORT_START_TAG(P1Y_PORT_TAG)
	PORT_BIT( 0xff, 0x80, IPT_AD_STICK_Y ) PORT_CROSSHAIR(Y, 1.0, -0.057, 0) PORT_SENSITIVITY(25) PORT_KEYDELTA(13) PORT_PLAYER(1)

	PORT_START_TAG(P2X_PORT_TAG)
	PORT_BIT( 0xff, 0x80, IPT_AD_STICK_X ) PORT_CROSSHAIR(X, 1.0, 0.0, 0) PORT_SENSITIVITY(25) PORT_KEYDELTA(13) PORT_REVERSE PORT_PLAYER(2)

	PORT_START_TAG(P2Y_PORT_TAG)
	PORT_BIT( 0xff, 0x80, IPT_AD_STICK_Y ) PORT_CROSSHAIR(Y, 1.0, -0.057, 0) PORT_SENSITIVITY(25) PORT_KEYDELTA(13) PORT_PLAYER(2)

this is for othunder again

**Comment by grant2258** [comment]
for slither just press player2 start button to save cmos setting it tells you this on the screen

**Comment by arcadez** [comment]
@grant2258 yeah i know how the crosshairs are handled by the video code and that underfire
doesn't have one setup, i just wasn't sure if there was indeed more general fake crosshair code that 
could be called from the src and wondered if this wasn't working correctly on the xbox core.

i guess not then :)

**Comment by arcadez** [comment]
term2 - no targeting reticule

Im pretty sure you have to set this up yourself, on first boot of the game there should be screen
to configure the guns, or it can be done via the service mode.

**Comment by grant2258** [comment]
hardyard is fixed now https://github.com/libretro/mame2003-plus-libretro/pull/660 was alignment issues.

looping - fluctuating frames can you please explain this works fine here.

**Comment by arnoldsecret** [comment]
during looping gameplay sometimes it slows down and speeds up at various times.

**Comment by grant2258** [comment]
I  never noticed and fps drop you sure its not the effect of gravity emulated in the game or is it random ?

**Comment by arnoldsecret** [comment]
https://drive.google.com/open?id=1K0yMttKxF4bQiMQxe2OEv675cNPIPQm_

**Comment by arnoldsecret** [comment]
I'll be closing this one, feel free to reference it.
