### ISSUE TITLE
[Request] 7z compression support

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/mame2003-plus-libretro#679]
title.

**Comment by markwkidd** [comment]
First, my understanding is that 7z is losing popularity for distribuying
Mame romsets.

That said, what is the total file size savings for a mame2003-plus
collection in 7z versus zip? I have a feeling the savings would be less
than 10% of a complete collection.

That is not to say 10% is not worth it, but I'd like to know what the
possible gain is.

**Comment by KMFDManic** [comment]
Roughly 24 percent if I recall correctly from my previous testing with 7z.

**Comment by rek607** [comment]
Yes. It would be around 25%, it depends a lot of the content of the pack.

**Comment by markwkidd** [comment]
@mahoneyt944 looking back from the year 2021, I feel even less interest in 7z support. however I may be wrong in my priorities. do you think it's ok to close this, or do you want to keep it on the list for the future?

**Comment by mahoneyt944** [comment]
Nah.

**Comment by nicjansma** [comment]
Hi!

I realize this is closed but would like to share some feedback.

I'm seeing about a 14% byte savings with 7z vs zip.

```
dir *.zip
            4859 File(s) 15,962,747,176 bytes
```

```
dir *.7z
            4859 File(s) 13,726,670,152 bytes
```

However, when you're working with complete ROM sets, this is > 2.2 GB of savings, which is significant, especially on smaller systems or like my handheld that has only a 32 GB microSD card.

Would really like to see mame2003+ support 7z.

**Comment by KMFDManic** [comment]
7z may be supported by a lot of Cores.  But, you will find out, overall, .zips or not even compressed, tends to have better overall performance on lower spec platforms.  On some of the platforms I utilize, MAME 2003, as a lower example.  You can try this, for yourself, with a core that does support 7z, such as Final Burn Alpha or Final Burn NEO.  Go into RetroArch Settings, Onscreen Display, turn on Memory Usage.  You should see a difference between 7z and zip. 

 For the Mini Classics, for example, which only have 256 MB of RAM, on the low end, the zip versus 7z, is the difference between a game crashing or working, as ive calculated from tests, around 80MB, give or take, which ends up being the size of the rom, the core, retroarch, if it has to decompress more than 80MB (this is mainly for MAME (compressed audio samples)/FBA/FBNEO Cores, and stuff like PrBoom Doom Sigil  (compressed wad audio samples), the game will generally crash, unless we utilize virtual ram.

So, keep in mind, zip is less stress on memory, than 7z, decompression wise.

With that being said, it likely wouldn't be overly difficult to implement 7z, with a little scrutiny.  Just gauging how it was added in other Cores, it should be fairly easy to replicate here.  But, it would, of course, need testing, to ensure it doesn't break overall stability of the Core.

https://github.com/libretro/fbalpha/commits/master/src/dep/libs/lib7z

From a personal standpoint, I have found .zip to be more than adequate for general usage, to avoid memory issues.  7z was initially very nice.  But, with 256 MB of RAM, and certain cores not playing well with that, I have stuck to zip as a standard.
