### ISSUE TITLE
Golden Tee Games Itech32 Bit Hardware

### ISSUE THREAD

**Issue by arcadez** [libretro/mame2003-plus-libretro#680]
Just about to backport the final games im gonna add support for in this core, as we've quite
honestly ran outta viable targets, these were quite often requested on the xbox MAME ports
and some consider them the best golf games released in the arcades.

![gt97](https://user-images.githubusercontent.com/35177309/53845198-2cc5f980-3fa0-11e9-9c61-b09bdd69ef11.png)

One thing of note was the trackball settings were not upto scratch with the values they defaulted
to in MAME the ball didn't move fast enough when you took a shot so there was no way you
could make the par.

Upping the analog speed and sensitivity fixes this the downside being sometimes you have to
be carefull when close to the hole you dont overshoot it, making slight movements of the
analog stick will help in that regard the games tell ya to do this anyway.

Now this might just be a problem with the Xbox gamepad and the xbox MAME cores but you
can certainly tweak the analog settings im defaulting to in this core to find your prefered setup.

DEV Talk

Straightforward to add although i did have to tweak the romload tables due to these
games being added after the MAME79 mem changes as a result im guessing on the fake CPU1
hookup but all the rest of the 32 bit games set this value and the games seem fine with it........

 /* Maximum sftm code size */
#undef  CODE_SIZE
#define CODE_SIZE   0x0400000

ROM_START( gt3d )	/* Version 1.93N for the single large type PCB P/N 1082 Rev 2 */
	
    ROM_REGION( 0x8000, REGION_CPU1, 0 ) /* correct.?? */

    ROM_REGION32_BE( CODE_SIZE, REGION_USER1, ROMREGION_DISPOSE ) /* correct.?? */

PS i never bothered fixing up Drivers Edge there would have been a fair amount of graft plus
the game would likely not have performed too well and we'd have to due to the changes
drop a sound speedup which would have made all the other games take a hit in the fps dept.

**Comment by grant2258** [comment]
Well I havent tested em yet but ive started to attempt to port mame084 for future use if needed. 

ive got a tiny compile working its segfaulting at the moment but hopefully it will come to fruit one day. We are reaching a point where we need memory maps and timing to make any progress without a lot of graft being involved.

**Comment by arcadez** [comment]
Good the hear Lemmie know if you want my Xbox MAME84 src sometime, it has everything i've added to this core plus more besides.

**Comment by grant2258** [comment]
Well i got the core up and running somewhat. I just done my work on getting mappy to run some games run others dont and the some have messed up gfx. Ill try get this in a workable state in time. I really dont think we need a mame084 core in itself but if we reach the end of the line here this could be a new base to work form.

**Comment by arcadez** [comment]
Nice progress bigman, ironing out the niggles might take some time though

**Comment by grant2258** [comment]
well got the endian problems sorted all looks good just need to fix the vector games up. Im going to tidy this up a little. And just rename the main  files changes for libretro.

I plan on porting to sdl as well so its available to others on lower end hardware if it comes to something. Makes more sense that way.

**Comment by grant2258** [comment]
Well eveything seems to be up and running having some touchups on the input and add analog but for all purposes its working. 

I need to double check the makefile i just copied the mame2003 for the cpu and sound cores no doubt ill be missing some shouldnt take too long to sort then its once this parts done.  Midres with working sound on the pi!

**Comment by arcadez** [comment]
Well done i knew you'd have it more or less done in short order, we'll need to have a discussion
sometime around what stuff you'd like to see added to this new core, i dont think every addition 
and fix from this core would need to be ported across but the Data East games should be worth
consideration

Additonally we have more scope to work on stuff that was not possible in this core
