### ISSUE TITLE
Datafile non compliant

### ISSUE THREAD

**Issue by ebolefeysot** [libretro/mame2003-plus-libretro#681]
Hello
I'm the developer of romcenter and  @markwkidd submit an issue about loading mame2003plus datafile (https://bitbucket.org/ebolefeysot/romcenter/issues/128/mame-2003-plus-libretro-core-xml-error).

According to the dtd included in the dat header, the <driver> tag is defined like this:

        <!ELEMENT driver EMPTY>
            <!ATTLIST driver status (good|preliminary|test) #REQUIRED>
            <!ATTLIST driver color (good|imperfect|preliminary) #REQUIRED>
            <!ATTLIST driver sound (good|imperfect|preliminary) #REQUIRED>
            <!ATTLIST driver palettesize CDATA #REQUIRED>

In the datafile, we find:
`<driver>puckman</driver>`
and then later in the same game section
`<driver status="good" color="good" sound="good" palettesize="16"/>`
The 'driver' tag appears two times. The first tag is not compliant. 
In my opinion, it should be removed, as there is no definition in the dtd for 'sourcefile' data.

**Comment by grant2258** [comment]
see if this dat file is good for you

[mame2003-plus.zip](https://github.com/libretro/mame2003-plus-libretro/files/2935709/mame2003-plus.zip)

**Comment by ebolefeysot** [comment]
Yes, it's loading.
Thanks.
ps: I have fixed that case in the final release of romcenter anyway.

**Comment by markwkidd** [comment]
Thank you both. I have just removed those two lines in `info.c` for both MAME 2003 and MAME 2003-Plus.
