### ISSUE TITLE
core limitation

### ISSUE THREAD

**Issue by frezeen** [libretro/mame2003-plus-libretro#682]
mame2003+ dont send right refresh rate to MME4CRT on RPi cause core limitation.
can u indagate e fix this?
mme4crt is a RA fork with crtswitchress resolution support for libretro cores
https://mme4crt.alphanudesign.co.uk/forum/portal.php

edit: retroarch latest release 1.7.6 has crtswitchress support from mme4crt work. bug is present to official RA too

**Comment by grant2258** [comment]
try chamge change options -?>Bypass audio skew (Restart core); to disabled and restart the core this will conform to ra core timimg

**Comment by frezeen** [comment]
enabled or disable it dont have effect on this.
example problem: neogeo games running at vertical refresh rate 60.000Hz with tearing on mame2003+, fbalpha running them at original refresh rate 59.180Hz with no tearing

**Comment by grant2258** [comment]
options ->Bypass audio skew (Restart core) set this to disabled and restart the core it. with this on the sound sets the timing

**Comment by frezeen** [comment]
sorry im so stupid... testing neogeo only with disabled "bypass audio skew". dont know about neogeo mame2003+ driver at 60Hz.
robocop , 1944, and other games working perfect now with disabled.
im really sorry for losing your time

**Comment by markwkidd** [comment]
@frezeen can you clarify: are you seeing the correct 59.180hz with Bypass Audio Skew set to Enabled or Disabled?

**Comment by frezeen** [comment]
no, 59.180Hz is for neogeo in fbalpha.. mame2003+ running neogeo at 60Hz.  i have correct vertical refresh rate now with other games like 1944, robocop and others with bypass audio skew set to "disabled".
(disabled mean: "dont bypass audio skew but use it")
