### ISSUE TITLE
erratic results with nonstandard monitor refresh rates on RasPi

### ISSUE THREAD

**Issue by fzacchi** [libretro/mame2003-plus-libretro#684]
I've written a set of scripts (for RetroPie on the Raspberry Pi) that activate the correct nonstandard refresh rates for each game that needs them on LCD monitors. LCDs go by 1 Hz increments, so for example with R-Type and Mortal Kombat the monitor runs at 55 Hz, with Neo Geo games at 59, with Double Dragon at 57 and so on.

Every arcade core I've tested (lr-fbalpha, lr-mame2003 and lr-mame2010) exhibits the correct behavior: the game ends up falling within the audio timing skew range so scrolling is perfectly smooth.

On lr-mame2003-plus instead I get even choppier scrolling than running the monitor at the standard 60 Hz and the frame rate displayed by the OSD is somewhat erratic. Fiddling with the core options hasn't solved anything for me. Any tips?

Repro steps:
drop to the command line and activate 55 Hz mode

vcgencmd hdmi_cvt 1920 1080 55 0 0 0 1
tvservice -e "DMT 87" && sleep 0.2 && fbset -depth 8 && fbset -depth 16

launch emulationstation without rebooting

launch Mortal Kombat (mk) with lr-mame2003, insert coin and watch the spinning character carousel
relaunch it with lr-mame2003-plus, do the same and notice the difference

**Comment by grant2258** [comment]
I dont get this really customizing everything with a script needlessly. Emulators should be setting this themselves.  It does work as is if you dont mess with refresh rates both option below will work.
 
just  change your audio skew to 0.01 (restart required) and turn  options bypass audio skew  =off
or
bypass audio skew  = on 

bypass audio skew  = off will work for your scrip too but its not needed if you change the audio skew in ra settings

https://github.com/libretro/mame2003-plus-libretro/issues/684

**Comment by fzacchi** [comment]
Emulators can't switch the monitor refresh rate on the Pi yet. And you can't get the same effect if the monitor runs at 60 Hz against a game that's something else anyway.

**Comment by grant2258** [comment]
yea cause plus does it itself unless you ask it not too

**Comment by fzacchi** [comment]
My script doesn't change the video_refresh_rate variable in the RA core, it changes the actual monitor refresh rate, system-wide, before launching any emulator. Also, I can't find the bypass audio skew option anywhere, on the 1.7.6 RA version for the Raspberry Pi.

**Comment by grant2258** [comment]
dont worry about the internal details to get mame to let ra or your script set the timing go to the quick menu (start + select) then options youll see it at the bottom it in the core options

**Comment by fzacchi** [comment]
Bypass audio skew isn't there in the standard 1.7.6 retropie build, updating from source (to 1f6f39a) makes it appear. With the option disabled the script works.

**Comment by mahoneyt944** [comment]
@fzacchi please close this issue unless you still need help with this topic.
