### ISSUE TITLE
Custom Rom

### ISSUE THREAD

**Issue by mahoneyt944** [libretro/mame2003-plus-libretro#691]
Hi, does anyone know how to run a custom/ modified rom on Mame2003plus for my retropie setup? I own a legitimate Midway Tron arcade cabinet where I purchased and installed a free play chip. The rom is downloadable free from the person who wrote it here [TRON Freeplay](http://www.arcadecollecting.com/hacks/tron/) 

I have be playing an emulated version of Tron, "Tron2.zip", on mame2003plus but I plan to install the emulated version in the real cabinet and preserve the original board. I'd like to use the Freeplay rom, 6/25 version, through emulation though and add a dipswitch setting (switch 4) to turn Freeplay on/off in the Mame like my real cabinet does.  I have no idea how to configure it to do this. I replaced the one file in the zip rom folder but then Mame won't load it. I assume it has to do with the checksum or how the roms are described in Mame. Can anyone point me in the right direction? I assume this shouldn't be too hard to do? I believe it's the "d2" chip, or pro0.

**Comment by markwkidd** [comment]
First you can try to open up your `tron2` romset zip file and swap the `d2` (or `pro0`) rom file with your hacked one. Chances are it will have `d2` or `pro0` in the filename. You will need to name your replacement the exact same way and then put it into the romset zip.

**Comment by mahoneyt944** [comment]
I tried this but then the rom won't load. I also tried to open the original rom and changing one letter in a text label, saving and loading that which also does not play.

**Comment by markwkidd** [comment]
Can you post a log?

If you are using RetroPie there is some way specific to your platform of doing that which involves Runcommand. I can't immediately find docs which explain the process, but some other rpi owners also post here in case you don't know how to generate logs.

**Comment by barbudreadmon** [comment]
> First you can try to open up your tron2 romset zip file and swap the d2 (or pro0) rom file with your hacked one. Chances are it will have d2 or pro0 in the filename. You will need to name your replacement the exact same way and then put it into the romset zip.

That method worked with fbalpha, the file to replace was named `scpu_pga.d2`

**Comment by grant2258** [comment]
works on tron and tron2 (set one and two) as long as you add the extra dip switch to activate the mode also both and copy over the appropriate roms

**Comment by grant2258** [comment]
```
	PORT_DIPNAME( 0x08, 0x08, "freeplay" )
	PORT_DIPSETTING(      0x08, DEF_STR( Off ) )
	PORT_DIPSETTING(      0x00, DEF_STR( On ) )
```

for the dip switches you will need a new set of inputs as well or both original sets will show the extra dip switches

**Comment by mahoneyt944** [comment]
Where does the dip switch setting go? I'm new to all of this

**Comment by grant2258** [comment]
well the driver would need updated not a big deal im sure mark can add it for you if arcadez doesnt have any objections. Its a simple addition and i noticed mark sent you here so i cant see any problems with him adding it for you.

**Comment by mahoneyt944** [comment]
So what would I have to do to get it going then? Update the zip file? I'm
not familiar with Mame at all and it's inner workings

**Comment by grant2258** [comment]
what pi are you using ill compile you a quick binary that will add the dip switch until mark adds it for properly for you

**Comment by mahoneyt944** [comment]
Rpi3b+, so I just need to make the zip file and update the binary

**Comment by grant2258** [comment]
im making you an updated binary with an extra dip switch for tron ill post when its compiled.

for tron.zip rename 625_V11.BIN to scpu_pga.bin then add it to the zip
for tron2.zip  rename 625_V11.BIN  to pro0.d2

you can do this now the game will run but you need the extra dip switch to activate it but your 2 roms will work as usual. 

ill add instructions here of how to get the binary and copy it over when its compiled

**Comment by mahoneyt944** [comment]
I executed the first line and it copied the file. Then I try to run the 2 line and it says 
```
mv: cannot stat 'mame2003_plus_libretro.so' No such file or directory
```

**Comment by grant2258** [comment]
well only a contributor here. Im sure someone will officially make a comment on it. 

if they agree they can just add it as a separate set. Yes unfortunately updating mame2003-plus  would remove the customization. Its just so you can use it at the moment. The only real option is to add the new set because that rom is the only difference .

**Comment by mahoneyt944** [comment]
Also the Freeplay rom has a minor glitch. If you press start a second too long it will automatically start another game after you die. This goes away if you press start more quickly. I believe the glitch is it registers start game twice on a longer press of the button. I think if the start function could have a few seconds of delay after it's pressed before it's active again it would be perfect glitch free.

**Comment by grant2258** [comment]
I read something about this when you mentioned the rom apparently it was made free after this glitch was found. Any solutions to fix it on real hardware ?

**Comment by mahoneyt944** [comment]
As long as you press start quickly it works all the time. So to fix the start button just needs a delay after it's pressed for about 10 seconds for both player 1 and player2 start button. The input is just activating twice when the start button holds too long

**Comment by arcadez** [comment]
Maybe we need................

	PORT_BIT_IMPULSE( 0x04, IP_ACTIVE_LOW, IPT_START1, 1 )
	PORT_BIT_IMPULSE( 0x08, IP_ACTIVE_LOW, IPT_START2, 1 )

**Comment by mahoneyt944** [comment]
What does that do exactly?

**Comment by grant2258** [comment]
that could do the trick also free play wont work at all if you dont remove 	PORT_BIT( 0xf8, IP_ACTIVE_LOW, IPT_UNUSED ) from the dip switches. coin mech perhaps ?

**Comment by mahoneyt944** [comment]
As long as once start is pressed, it can't be immediately activated again for maybe 10 seconds to be safe then the glitch will be gone. A delay or disable function would do it.

**Comment by grant2258** [comment]
ok updated the build

```
cd ~
wget https://github.com/grant2258/mamemagic2003/raw/master/mame2003_plus_libretro.so  
sudo cp mame2003_plus_libretro.so /opt/retropie/libretrocores/lr-mame2003-plus/
```
it added as a set now so you can put your normal tron roms back

copy this to your roms dir (the free custom rom)
[tronfp.zip](https://github.com/libretro/mame2003-plus-libretro/files/3082955/tronfp.zip)

restart emulation station so it sees the rom and let aradez know if his PORT_BIT_IMPULSE fix worked for you since you know how to trigger it

**Comment by mahoneyt944** [comment]
Is the file in tronfp.zip that you just posted modified? 

To use it now after updating the build do I just copy tron2.zip contents and create a tronfp.zip with Freeplay rom?

**Comment by grant2258** [comment]
tronfp.zip is just the what's on the free download page no modifications. tron is the parent rom it its there you wont need to copy the contents all you will need is the one file form the site in a zip called tronfp.  Again depends how you build your sets but is your using split sets all you need is one file else copy the needed missing ones

**Comment by mahoneyt944** [comment]
I wouldn't want to use tron2.zip if I have a free play version working, so I'd remove tron2.zip completely.... right now my tron2.zip contains the Freeplay rom so I can just rename it to tronfp.zip and be good as a stand alone file? 

I'm guessing input pulse mod is just in the ```mame2003_plus_libretro.so``` build?

**Comment by grant2258** [comment]
yes the input pulse has been added to the driver all you need to do is load the game

**Comment by mahoneyt944** [comment]
Ok, I'll try when I get home

**Comment by mahoneyt944** [comment]
I tried to launch tronfp.zip but it doesn't load from es. Did you use tron2.zip to make the Freeplay set? That's what I use. I renamed my tron2.zip that had the Freeplay rom in it to tronfp.zip now it won't boot.

**Comment by grant2258** [comment]
well i have the pull request its up to the devs if they want it added. No real way to fix this in real hardware unless you patch whats causing the issue. Glad its working for you ill leave the binary there for you in the mean time. arcadez always seems to find a solution :)

**Comment by mahoneyt944** [comment]
Could the real hardware driver be patched?..... Or perhaps add a delay to the Freeplay rom after it exectues either p1 or p2 start functions? It's seems to me if you edit the Freeplay rom and add a timer to the end of the start function it might fix it.
