### ISSUE TITLE
Toaplan 2 Samples From ThunderMAME

### ISSUE THREAD

**Issue by arcadez** [libretro/mame2003-plus-libretro#697]
We dont have the V25 CPU which would be required to add sound to the remaining Toaplan2
games which are silent in this core nor can it be backported, as i recall we also ran into trouble
with the Ghox HD647180 MCU when backporting it to this build but there is another option........

I've just added the code from ThunderMAME which will give us sound in the following games........

Batsugun
Batsugun Special Ver
Dogyuun
Ghox
Grind Stormer
Teki Paki
V-Five

The samples can be found here................

http://www.mediafire.com/?5bw1qpq2x4die

They're rather meaty in size although it should not be a problem with the systems that use
this core, on the xbox however we had to reduce the quality somewhat so the samples were
around 20mb or so otherwise we'd run out of mem on boot.

The games still sound great even with the lower quality samples only reason i mention this
is i dont have the sound programe i used handy on my PC nor can i mind what it was
audacity i think, anyway im gonna add the code blind later today and get you guys to
test the games out for me as they'll outta mem with my test core due to sample sizes.

This will leave one game without sound Knuckle Bash as they never made samples for 
that one although some code from around MAME88 can be added to fake the OKI sfx
i might go ahead and add it as it's better to have partial sound than none.

**Comment by grant2258** [comment]
agreed partial sound defo is better than none. This core can support flac as well all they would need to do is convert the wavs would save some space

**Comment by arcadez** [comment]
Actually it's gonna be a bit more work to pull this off, Ghox and Teki Paki are easy however for
Batsugun, Dogyuun and V-Five there is some extra sample code in the vidhrdw tied in with video
buffering and some input code not compatable with this core.

So i'll stick it on the backburner for now but i've went ahead and added the OKI hacks for 
Batsugun and Knuckle Bash so at least both of those games will now have partial sound at least
i've also fixed a video problem with Batsugun on level one where some stuck sprites or is it a tile layer
are obscuring the first boss................

Start of level one
![bats0000](https://user-images.githubusercontent.com/35177309/56461987-75503f80-63b3-11e9-8d3d-f801b2a43dd8.png)

Returns on first boss
![bats0002](https://user-images.githubusercontent.com/35177309/56461990-7b462080-63b3-11e9-9b9e-c5c4453b078e.png)

**Comment by grant2258** [comment]
yea complications always do seem to come up its better to have some partial updates than none at all.

**Comment by arcadez** [comment]
Ok digged a little deeper it seems the video changes i was on about earlier are just to flip on
some buffering via the dips, so i worked around it and finished up this port...............

https://github.com/amadvance/advancemame/commit/7cd833c74921a02f4f3d3d3664ddea7584fe9fd5

I was able to dig out some Ghox samples and the game now has music and Sfx im confident
Teki Paki will be good also as i've used the sample code for that one previously that just leaves
the code for the other 3 games i've never tried out in the older cores.

V-Five boots not tried the samples yet to see if they'll work

There seems to be a problem with Batsugun and Dogyuun both games lock up on boot and
never leave the rom loading screen i've been trying to sort this since last night but no joy as 
yet

I'll endeavour to plod on :)

**Comment by arcadez** [comment]
Hmmm still they wont boot, not to talk down another dev but i would have preferred to just lift
code directly from the ThunderMAME build which has the Toaplan samples like i did the last time
as obviously i cant rule out a mistake was made with regards to Batsugun and Dogyuun when
backporting to the AdvanceMAME core as i have no source to compare it to.

The site which used to have the src is gone now it seems :(

**Comment by grant2258** [comment]
https://www.zophar.net/mame/thundermame.html dont know if this source is any good for you

**Comment by arcadez** [comment]
Nah only certain ThunderMAME builds supported the Toaplan samples and this is not one of em

**Comment by grant2258** [comment]
well the hacks are ported to franken mame as well here https://github.com/oboewan42/frankenmame/blob/master/src/mame/drivers/toaplan2.c

**Comment by grant2258** [comment]
skip the frakenmame https://shmupmame.wordpress.com/download/ Shmupmame 4.2 has the thundermame hacks

**Comment by arcadez** [comment]
Thanks for heids up bigman i've already got Ghox and Teki Paki, Batsugun, Dogyuun and V-Five
have full sound via the V25 CPU by MAME 130 or so i'll need older ThunderMAME src's to get the sample code for those.

Anyway feel free to try em out as i cant rule out Xbox fuckiness as the reason Batsugun and
Dogyuun dont wanna boot in my test core they might actually work here as we've seen before
with B-Rap Boys and Virtua Fighter.

No hurry bigman i've included everything which would be required minus the samples for
Batsugun, Dogyuun, Teki Paki and V-five which can be grabbed from the link above

https://www.sendspace.com/file/2ey6wx

**Comment by grant2258** [comment]
Batsugun and Dogyuun is loading fine in this core just to let you

**Comment by arcadez** [comment]
Arghhhhhhhh i was looking at the samples and noticed batsugun had far more than the others
but i was fixated with it maybe being the MCU sim code which was at fault, so is it simple case 
of just doubling the default to #define MIXER_MAX_CHANNELS 32 ??? i cant seem to spot the
same code in later MAME builds to check how many channels they support.

Nice spot by the way that's the benefit of being able to debug :)

**Comment by grant2258** [comment]
well ghox works fine but batsgun starts like i said credit sounds title scree music when you select your ship  then when the games about to start it segfaults. Im not sure if its doing on on your core or not. I know the sample code has been altered for custom ost could be causing problems or the driver itself. No doubt itll be something simple thats a nightmare to find

**Comment by arcadez** [comment]
So your telling me even when changing the default Max channels Batsugun will still be messed up..??

i'd come up with this as a possible workaround.............

WRITE16_HANDLER( batsugun_snd_cpu_w )
{	
	if (data == 0x00)
	{
		play_bat1 = 0;
	}

	if (data >= 0x01 && data <= 0x0a)
	{
		sample_start (0, data , 1);
		play_bat1 = 0;
	}

	if (data == 0x0b && play_bat1 == 0)
	{
		sample_start (0, data , 1);
		play_bat1++;
	}

	if (data >= 0x0c && data <= 0x10)
		sample_start (0, data , 0);

	if (data >= 0x11 && data <= 0x12)
		sample_start (1, data , 0);

	if (data == 0x13)
		sample_start (2, data , 0);

	if (data == 0x14)
		sample_start (3, data , 0);

	if (data == 0x15)
		sample_start (4, data , 0);

	if (data == 0x16)
		sample_start (5, data , 0);

	if (data == 0x17)
		sample_start (6, data , 0);

	if (data == 0x18)
		sample_start (7, data , 0);

	if (data == 0x19)
		sample_start (8, data , 0);

	if (data == 0x1a)
		sample_start (9, data , 0);

	if (data == 0x1b)
		sample_start (10, data , 0);

	if (data == 0x1d)
		sample_start (11, data , 0);

	if (data == 0x1e)
		sample_start (12, data , 0);

	if (data == 0x1f)
		sample_start (13, data , 0);

	if (data == 0x20)
		sample_start (14, data , 0);

	if (data == 0x22)
		sample_start (15, data , 0);

	if (data >= 0x23 && data <= 0x28)
		sample_start (16, data , 0);

	if (data == 0x29)
		sample_start (17, data , 0);

	if (data == 0x2a)
		sample_start (18, data , 0);

	if (data == 0x2d)
		sample_start (19, data , 0);

	if (data == 0x2e)
		sample_start (20, data , 0);

	if (data == 0x2f)
		sample_start (21, data , 0);

	if (data == 0x30)
		sample_start (22, data , 0);

	if (data == 0x32)
		sample_start (23, data , 0);

	if (data == 0x33)
		sample_start (24, data , 0);

	if (data == 0x34)
		sample_start (25, data , 0);

	if (data == 0x36)
		sample_start (26, data , 0);

	if (data == 0x37)
		sample_start (27, data , 0);

	if (data == 0x3a)
		sample_start (28, data , 0);

	if (ACCESSING_LSB)
	{
		mcu_data = data;
		/* batsugun_okisnd_w(data); */
	}
	 /*logerror("PC:%06x Writing command (%04x) to the NEC V25+ secondary CPU port %02x\n",activecpu_get_previouspc(),mcu_data,(offset*2)); */
#if 0
	if (!strcmp(Machine->gamedrv->name,"batsugun") || !strcmp(Machine->gamedrv->name,"batugnsp"))
	{
     #define MIXER_MAX_CHANNELS 30
	}
#endif
}



Ok always the problem when backporting from newer cores, listen we have can do Ghox and Teki Paki
those will be fine we'll have partial sound for Batsugun and V-five will have to remain silent, full sound
in two and at least the OKI Sfx in the other will still be a win.

**Comment by grant2258** [comment]
agreed vfive didnt work for me either though havent tested the rest

**Comment by arcadez** [comment]
Yeah same here Ghox is working for me i've just dug out some samples for Teki Paki and their good
but like you i get nothing with V-Five i'll check the code again to see if i missed something

**Comment by arcadez** [comment]
Ok code is in for Ghox and Teki Paki both games are fine and will have full on sound if users have
the samples in the correct folder, here are two special trimmed down versions of the samples
which will have the following benefits........

1) they'll use less memory when booting up and while playing the game handy on low spec systems
2) they'll be less of a performance hog as the game will load em quicker and easier
3) they'll save ya some space which is always good :)

Toaplan 2 Reduced Size Samples
https://www.sendspace.com/file/s09s4m

**Comment by grant2258** [comment]
I did notice the code wants the wav format in a certain format was it the wav files causing the issues? well dont on fixing it ill have a wee look at it when i get in job well done mr arcadez!

**Comment by arcadez** [comment]
I was hoping ya might take a wee peek, im stilling looking at it myself the fading and sample vol
code stands out as maybe being wrong for this core but it could be something else entirely.

**Comment by grant2258** [comment]
well i know we dont support stereo wavs the ost have a uniqe way of handling it. Ill take a wee peek at the weekend and let you know if i find anything

**Comment by grant2258** [comment]
teki and ghox working with reduced and normal samples mate just tested forot all about this with the data east stuff i was doing sorry aboot that think we can close this now

**Comment by arcadez** [comment]
Aye V-Vife will be too much trouble by looks, lets quit while we're winning :)
