### ISSUE TITLE
YMF271 Soundcore Update to MAME110

### ISSUE THREAD

**Issue by arcadez** [libretro/mame2003-plus-libretro#704]
Just a heads up i used @grant2258's YMF271 soundcore he backported to MAME2003_plus
on my xbox MAME84 core and noticed a huge drop in performance as much as 50fps on
the Seibuspi games Raiden Fighters 2 and Jet while Raiden Fighters and Viper Phase 1 were
around 40fps slower.

And around the same with the MS32 games that i tried Desert War and Gratia, now that's not
say the same would happen here but someone might wanna checkout the MS32 games using
libretro builds on some of the lesser platforms to test the performance on these games in
this core.

The same thing happened when i used the YMF271 from MAME110 another dev had done for
his shmupmame project, so either it's just more of a performance hog with the improvements 
to the YMF271 core or the timing is off for older cores such as this.

I bumped into a similar issue when backporting the ICS PGM soundcore from the same
build however lucky for me i was able to just roll the timer code back to M78 to bring the 
PGM games back up to full on speed once more.

**Comment by arcadez** [comment]
Games affected in this core test em on systems like the Rpi and let us know if there is problem
with the speed in these................

Best Bout Boxing
Desert War
The Game Paradise - Master of Shooting
Tetris Plus
P-47 Aces
Gratia - Second Earth
Tetris Plus 2 (MegaSystem 32 Version)

**Comment by grant2258** [comment]
It was a pain doing this particular core the timing should be good for mame078 (it will need redone for mame084 though) as i done the core update and added the original timing code the old one had. 

Im pretty sure i tested gratia on the pi that was the reason i done this update. lll check the ms32 games when i get from work. it  only the ms32 that uses the 271 on this core at the moment as far as i can remember

**Comment by grant2258** [comment]
need to update my retropie and compile mame2003+ version on it is pretty old just getting static noice on gratia and a few other games at the moment. Ive been messing with another version of mame so ill update it all and compare mame2003 and mame2003+ speed wise

**Comment by grant2258** [comment]
it does appear to be running slow ill need to see if this is just the soundcore or the cpu core update as well. Changing the clock speeds could have a knock on effect t easy enough to revert to the to the soundcore before this and the original soundcore. If that fails might have to revert the v60 updates to get the speed up.

**Comment by arcadez** [comment]
I have a feeling it's the soundcore buddy that's MAME for ya YMF271 improvements in one hand 
a performance drop in the other due to it, listen i tried out your original commit when you first
updated the PCM code in the soundcore before the full blown update and the speed was still good.

**Comment by grant2258** [comment]
best reverting and keeping the code somewhere in a branch in case we need to revisit it again for this port. The speed loss isint worth it for this port its  aimed at lower hardware will need to look at that code and  profile it see if we can do anything with it at some point wont take any offense to reverting it mate

**Comment by arcadez** [comment]
No problem we can revert back to using the original soundcore but there are some small improvements
for the YMF271 from MAME84 which i'll backport it wont be as good as the one you ported from
MAME110 but it'll have to do as we need the speed in this ole core.

**Comment by grant2258** [comment]
ive already done that just revert this one ill will got to the mame084 one should be done already matey

**Comment by grant2258** [comment]
you can just revert the 110 and itll goto to the 084 version else just add these files saved you messing with github
[Desktop.zip](https://github.com/libretro/mame2003-plus-libretro/files/3154694/Desktop.zip)

**Comment by arcadez** [comment]
Nae bother bigman just gonna huv ma tea n toast first

**Comment by grant2258** [comment]
im off tae bed work calls as per usual hopefully it all works out. Is a shame its slowing down so much will need to check if it optimized in later mame versions because the difference is day and night

**Comment by arcadez** [comment]
Night night big yin dont let the bedbugs bite :)

**Comment by arcadez** [comment]
Ok reverted YMF271 to the previous version that will get the ms32 games back upto speed.

**Comment by arcadez** [comment]
Ok problem has been solved closing
