### ISSUE TITLE
Please Test F1 Super Lap

### ISSUE THREAD

**Issue by ghost** [libretro/mame2003-plus-libretro#709]
As per a request that dropped in my inbox over at Neosource i decided to try and get this
game to work, the key was adding the v-blank prot which i didn't think would be compatable
in this core into the right place and reworking the prot code to hang off our older V60 CPU
for the reads and writes.

I've fully tested this on my xbox MAME72 core and everything is fine the game plays well
due to the older faster video code only fly in the ointment might be the fact i wasn't sure
if i've added the change required in the V60 correctly to this core.

Original code is

UINT32 am2Error1(void)
{
	//f1lap trips this, why?
	logerror("CPU - AM2 - 1 (PC=%06x)\n", PC);
	return 0;
	
}

I think this is correct for here

static UINT32 am2Error1(void)
{
	/* f1lap trips this, why? */
	log_cb(RETRO_LOG_ERROR, LOGPRE "CPU - AM2 - 1 (PC=%06x)", PC);
	return 0;
}

Just need @markwkidd or @grant2258 if you guys are still around.?? to try and boot F1 Super Lap
and lemmie know if it works.?? it should do but ya never know in this game.

On a seperate note im glad i got this request as it spiked my interest in trying to get this goin using
the older system32 driver it plays at around 40-45fps on my xbox in MAME84 where as when i added
this game to my segas32 driver with the slower video code i only got 5-10fps and that was even when
i underclocked the v60, lucky for us the older video code is good for this game which is not always the
case for some of the others eg Golden Axe RODA or Slipstream.

**Comment by arcadez** [comment]
There's been an World version of F1 Super Lap dumped it might be worth adding it here as we only
support the jap version in this core which has alotta non english writing on the important play screens
eg choose manual or auto gear change before you start and how to use the overtake turbo button.

The roms will have to change right enough which some folks never like :)

**Comment by arcadez2003** [comment]
@Wilstorm i'd like to take you up on your offer to test a game for me, it wont take long just need
you to boot up F1 Super Lap and tell me if it loads ok, previously it would get hung up on a pcb
comms screen that should be sorted now.

@twinaphex fixed a compile error with the original commit so you should be able to update to
the latest build now.

**Comment by arcadez2003** [comment]
Confirmed to be working fine so can close this now
