### ISSUE TITLE
Launching unsupported ROM in verbose mode yields error "flagrall" driver not found

### ISSUE THREAD

**Issue by jmccorm** [libretro/mame2003-plus-libretro#710]
I have lr-mame2003-plus as my default emulator and I started to track down why certain games weren't launching (so I could fix ROM issues, change their emulator, etc). As I was working with bgaregga ("Battle Garegga", which I thought might have been a Neo Game game), I copied it into my current working directory and I launched lr-mame2003-plus in verbose mode. received the following error:
```
# /opt/retropie/emulators/retroarch/bin/retroarch -L /opt/retropie/libretrocores/lr-mame2003-plus/mame2003_plus_libretro.so --config /opt/retropie/configs/arcade/retroarch.cfg --verbose bgaregga.zip
[INFO] RetroArch 1.7.6 (Git 9750719)
[INFO] Redirecting save file to "./bgaregga.srm".
[INFO] Redirecting savestate to "./bgaregga.state".
[INFO] === Build =======================================
[ ... ]
[INFO] CRC32: 0x21c4f3f4 .
[libretro INFO] [MAME 2003+] Content path: bgaregga.zip.
[libretro INFO] [MAME 2003+] Content lookup name: bgaregga.
[libretro ERROR] [MAME 2003+] Driver index counter: 4896. Game driver not found for flagrall!
[ERROR] Failed to load content.
[INFO] Unloading game..
[INFO] Unloading core..
[INFO] Unloading core symbols..
```

After playing around a bit I discovered that if I supplied any unsupported ROM, it would yield that same error. (And I believe that this goes back to the parent mame2003-plus project.) If I may offer two suggestions of what I'd like to see:

1. The error condition correctly caught in --verbose mode
2. Also, in regular use outside of verbose mode, a quick one-line error "<filename> is unsupported" or such which would be endlessly helpful to those less skilled who are trying to diagnose their own issues.

Thanks much and nice work!

**Comment by jmccorm** [comment]
Thank you for bearing with the edits here. Still getting the hang of github.

**Comment by arcadez2003** [comment]
grant2258 has fixed this issue
