### ISSUE TITLE
smashtv.zip on mame2003plus

### ISSUE THREAD

**Issue by rek607** [libretro/mame2003-plus-libretro#712]
Can't shoot at all. Can't configurate any button for shooting. The game image was not centered in screen, would be great to have it centered.

**Comment by arcadez2003** [comment]
You need to map it to stick two on your gamepad if you haven't tried that already, failing that it
might be a core issue with the inputs alotta changes were made in that dept which im not privy to.

**Comment by rek607** [comment]
It didn't solve the problem. I put it to work on classic mame2003. I think there's work to be done on this ROM yet. Thank you

**Comment by arcadez2003** [comment]
So i take it Smash TV and Total Carnage are fine in MAME2003..?? there's been a commit a wee
while back that changed @twinaphex original input modifications in midyunit.c i suppose that
was done due to the major overhall of the input code in this core.

This is not ideal really as im not really up to speed on all the input modifications and of the guys who were heavily involved in these input changes one has been banned from further contributing to this project and the other is not around so much just now.

So i guess it falls on me now to tidy up this mess not of my making and well i never really supported all
these input mods to begin with, all i can do is revert the changes in midyunit.c and then you can try out the games and see if they are now controlable once again.

**Comment by Wilstorm** [comment]
I just tested both games and they seem fine here. The screen is centered. 

I am using a controller and not a arcade panel with joysticks/buttons. Movement and firing both look good on an XBOX 360 controller. Left/Right sticks mapped by default. 

Go into RA -> Quick menu -> Options and check settings "Control mapping", "Input Interface" and "Legacy Remapping". What steps are you using to setup inputs?

I tested with a Pi 3B+, m3plus 2751318, RA 1.7.6 & RP 4.4.12.

**Comment by arcadez2003** [comment]
Yeah that's always been the thing i've noticed most with regards to this core lots of bug reports 
where one user states a game has issues or is totally broken while another says it's the opposite.
i think half the time this is due to folks using different build versions on different frontends on 
different platforms/systems all with a different setup.

This used to drive me mad when i first started out on this core, what im just gonna do here is
direct anyone who reports input troubles across to the Rpi forums where hopefully those who
were involved in the core input updates can offer up the advise on how to remap etc etc.

Thanks for testing BTW :)

**Comment by Wilstorm** [comment]
@arcadez2003 - You bet. Another thing I thought of if it's working for him on mame2003. 

It could be the input setup. Grant implemented a fairly complex input setup. I understand most of it but there's a few pieces I don't quite get what the best combination of options is for particular setups. I have mine setup mainly like mame2003 but only allow RA inputs in the TAB menu. Hopefully Grant and Mark will share those pieces and help people on the forums. His input setup is really tricky to say the least.

In the TAB menu Retropad inputs can be from a controller or a keyboard, IPAC, etc. and are designated as Retropad A, B, C, etc. from either device but movement keys like up, down, left and right just raw inputs for a lack of better words. They are designated just as they are up, down, left and right. I don't know quite how to explain it but that's where all the analog and digital options come into play. 

As far as the screen being centered mine is centered on the Pi and running full screen. It looks perfect from testing.

**Comment by arcadez2003** [comment]
Yeah i gotta be honest there was a huge debate around the input setup and updating and changing it
it ran into 100's and 100's of posts and i fully admit it bored me and i dropped outta reading about it
and keeping an eye on all the commits.

I was in the against camp as i seen the potential for your average user to get all bamboozled and that
would lead in turn to more bug reports, but i kept quiet as i seen @markwkidd and @grant2258 were
keen on making these changes.

From what i understand the input reworking and reordering has not been finished and been put on
the backburner for another day, but yeah hopefully the core input update will be finished streamlined
and simplified at some future date.

**Comment by rek607** [comment]
Hello again and sorry for my delay writing back. Sometimes I write on my phone while I'm walking to work and I found out I've been a bit cryptic about this issue. I am using a XBOX 360 gamepad and this are my setup for controls:

Control mapping: digital
Input interface: retropad
Legacy remapping: enabled

RetroPie 4.4.6, RetroArch 1.7.6, fe85fb0 mame2003-plus

As I said can't map on mame2003-plus the firing buttons (analog right stick would be great also!). Even though is not a bug could be useful to solve it in order to make easier remapping controls for this game for non-advanced mame2003-plus users instead of using any other core emulator.
My added suggestion is the right side of the game, it has a border which could be softened by moving the game screen to that side. Maybe it's a bit dumb?

Thank you for your answers, are very appreciated!

**Comment by mahoneyt944** [comment]
I just tested this on the current build. When you start up, you get an error on first boot but the game automatically corrects it and loads up fine without having to manually restart. Next boot passes. A bootstrap would fix it but not required. The game plays and controls just fine. The screen is slightly shifted to the left but not too bad almost not noticable. Could probably correct the screen position but other than that it's good.

**Comment by Wilstorm** [comment]
@mahoneyt944 - I think the main issue is his input settings and mappings. The game has always worked and mapped properly to a controller. 

Funny thing, I think we discussed a bootstrap but @markwkidd decided to focus only on those that don't boot (which makes sense) but I still had to create one for my "reinstall" folder just to get rid of that CMOS error. Anyway have a good evening (or morning)! ;)

**Comment by mahoneyt944** [comment]
The screen sizing is in midyunit.c driver.

**Comment by mahoneyt944** [comment]
@arcadez2003  This changes to the midyunit.c driver seem to adjust the screen position to be closer but these are just my guesses. Do you know anything about these?

```
static MACHINE_DRIVER_START( smashtv )
	MDRV_IMPORT_FROM(yunit_cvsd_6bit)
	MDRV_VBLANK_DURATION(COMPUTED_VBLANK(255, 288, MKLA5_FPS))
	MDRV_VISIBLE_AREA(0, 399, 0, 254)
MACHINE_DRIVER_END
```

**Comment by mahoneyt944** [comment]
Looks like these values were changed around .112 ish I'll try those values out when I get a chance.

**Comment by mahoneyt944** [comment]
Grabbed from .114

```
static MACHINE_DRIVER_START( trog )
	MDRV_IMPORT_FROM(yunit_cvsd_4bit)
	MDRV_SCREEN_VISIBLE_AREA(0, 395, 20, 275)
MACHINE_DRIVER_END


static MACHINE_DRIVER_START( strkforc )
	MDRV_IMPORT_FROM(yunit_cvsd_4bit)
	MDRV_SCREEN_VISIBLE_AREA(0, 399, 20, 274)
MACHINE_DRIVER_END


static MACHINE_DRIVER_START( smashtv )
	MDRV_IMPORT_FROM(yunit_cvsd_6bit)
	MDRV_SCREEN_VISIBLE_AREA(0, 409, 20, 275)
MACHINE_DRIVER_END


static MACHINE_DRIVER_START( hiimpact )
	MDRV_IMPORT_FROM(yunit_cvsd_6bit)
	MDRV_SCREEN_VISIBLE_AREA(0, 395, 20, 275)
MACHINE_DRIVER_END


static MACHINE_DRIVER_START( term2 )
	MDRV_IMPORT_FROM(yunit_adpcm)
	MDRV_SCREEN_VISIBLE_AREA(0, 399, 20, 275)
//  MDRV_SCREEN_VISIBLE_AREA(0, 403, 20, 274)
MACHINE_DRIVER_END


static MACHINE_DRIVER_START( mk )
	MDRV_IMPORT_FROM(yunit_adpcm)
	MDRV_SCREEN_VISIBLE_AREA(0, 399, 20, 273)
MACHINE_DRIVER_END


static MACHINE_DRIVER_START( totcarn )
	MDRV_IMPORT_FROM(yunit_adpcm)
	MDRV_SCREEN_VISIBLE_AREA(0, 399, 20, 275)
MACHINE_DRIVER_END
```

**Comment by mahoneyt944** [comment]
I've commit a change to help center the screen. https://github.com/libretro/mame2003-plus-libretro/commit/c07898dc59a40e3126fd1a54882bbe2328fffd07

**Comment by arcadez2003** [comment]
0.114u1: Changed TMS34010 CPU clock speed to 5MHz, visible area to 399x253 and VSync to 27.407585 Hz.

@mahoneyt944 The code changes circa MAME114 were tied into solving a couple of graphical niggles with Total Carnage and the Y-Unit  versions of Mortal Kombat, we cant backport these improvements as the games will take a performance hit, personally i'd leave the clock and Vsync changes well alone but adding the new screen sizes should not be a problem.

**Comment by mahoneyt944** [comment]
Yeah that's kinda where I was at. The screen looks more centered now and plays fine. Good enough.
