### ISSUE TITLE
astorm.zip on mame2003plus

### ISSUE THREAD

**Issue by rek607** [libretro/mame2003-plus-libretro#713]
Not loading. There's no 2 players version so you can't choose character. In 3 players version characters are predefinied (P1 = CH1, P2=CH2 and so on).

**Comment by arcadez2003** [comment]
We dont support the FD1094 decryption which Alien Storm requires, the bootleg version of this
game is playable here though.

**Comment by arcadez2003** [comment]
only the bootleg version of Alien Storm is playble in MAME2003, closing this down as there is no bug
