### ISSUE TITLE
suggestion: porting Demon Front (dmnfrnt.zip)

### ISSUE THREAD

**Issue by rek607** [libretro/mame2003-plus-libretro#714]
Having seen new additions to MaMe, I thought porting this game for the emulator would be amazing. I usually play it on FBA.

**Comment by arcadez2003** [comment]
Arm7 CPU would be required and this would not be easy to backport to this core, performance would
also be an issue on most of the platforms that use this core as the Arm7 is very demanding

**Comment by arcadez2003** [comment]
Ok closing this down we appreciate new game suggestions but in this case we dont have the
required CPU plus as stated performance will be an issue for example with Knights Of Valour 2
we only got 5fps on the xbox this will be the same for any PGM games which require the ARM7.

FBA has special speedups for these games hence they'll play pretty well using an Rpi best to
stick with that emulator to play Demon Front etc etc.
