### ISSUE TITLE
asterix.zip bgm music problem on Mame2003Plus

### ISSUE THREAD

**Issue by rek607** [libretro/mame2003-plus-libretro#715]
Works fine but music gets hanged after a few minutes of playing the game.

**Comment by arcadez2003** [comment]
i did make a commit to improve the sound pitch in Asterix, i suppose if other users have the same
problems with the sound the commit can be rolled back.

**Comment by arcadez2003** [comment]
Ok just tried Asterix although i used my standalone MAME72 test core rather than this one, the sfx and music are fine so the problem is not of my making at least, you never mentioned what platform or
frontend your using retroarch maybe.?? 

You might wanna play around with the RA or MAME2003+ sound settings to see if how you have those setup is throwing off the sound in some of the games.


DEV Notes

Asterix uses YM2151 and Konami KO53260 to drive the sound there have been some changes in
those soundcores in MAME2003+ not by me right enough, those changes or just how users
have the sound setup in whatever frontend their using might be the cause we wont know for
sure until more people report the same issue.

**Comment by rek607** [comment]
Sorry for not mentioning my setup. I'm using a raspberry pi 3B with retropie 4.4.6 and retroarch 1.7.6, using mame2003plus by default. How can I see or manage my sound drivers?

**Comment by arcadez2003** [comment]
I forgot i made so changes to the YM2151 soundcore which was to fix the sound dropping out in
Mustache Boy and The Lost Castle In Darkmist, the problems your having with Asterix sound very
similar so i have reverted those code changes for now.

Update to the very latest build try Asterix again and let me know if the sound problems are sorted.

**Comment by arcadez2003** [comment]
> 
> 
> Sorry for not mentioning my setup. I'm using a raspberry pi 3B with retropie 4.4.6 and retroarch 1.7.6, using mame2003plus by default. How can I see or manage my sound drivers?

I dont use RP or RA myself so im not really versed in how those frontends work you'd need to ask
on the Rpi forums about how to change the sound settings, but for now let's focus on finding out
if the recent change to the YM2151 soundcore i've just done fixes the problems with Asterix.

**Comment by Wilstorm** [comment]
I played this last night but never experienced any hangs or sound issues. It actually sounded pretty good.

I am running a Pi 3B+, m3plus 2751318, RA 1.7.6 & RP 4.4.12.

**Comment by arcadez2003** [comment]
Hmmm different Rpi's different RP builds and Asterix is fine for one user and not the other, man
it's enough to drive ya around the bend :) im used to the xbox scene where we were all on the same 
page more or less with regards to the hardware and software used.

So it was more cut and dry when it came to people reporting an issue with a given game, from now
on a minimum of 25 users have to report the same problem before im even gonna look at it :)

Anyway thanks for the reports.

**Comment by arcadez2003** [comment]
> 
> 
> Sorry for not mentioning my setup. I'm using a raspberry pi 3B with retropie 4.4.6 and retroarch 1.7.6, using mame2003plus by default. How can I see or manage my sound drivers?

Im not fully up on RP amd RA having never used those programs, your better asking how to access
and or change the sound settings over at the Rpi forums.

**Comment by Wilstorm** [comment]
Another thing possibly is I only played about 5 minutes. @rek607 how long did you play before it hangs? 

I don't anything special with sound drives on RetroPie. I just load the game and go with the defaults and the sound has always worked.

**Comment by arcadez2003** [comment]
Yeah i tested it on MAME72 on my xbox with and without the YM2151 timer changes which i was 
wondering might be a possible reason for the sound dropping out in Asterix and like you it was
a-ok for me and i played it well into level 2.

**Comment by rek607** [comment]
It hanged in the first 5 minutes randomly. I played again the game with both characters yesterday with no issue at all... Weird thing! When it hanged the other it just happened every single time. I can't understand it.
