### ISSUE TITLE
sonic.zip gets hanged on mame2003plus

### ISSUE THREAD

**Issue by rek607** [libretro/mame2003-plus-libretro#717]
I can see the insert coin screen and ranking. If I insert a coin in order to start, it gets hanged (backout) and resets afterwards.

**Comment by arcadez2003** [comment]
Try sonicp.zip im sure that's the version that works in these older cores

**Comment by arcadez2003** [comment]
I guess you have the warning screens turned off, sometimes it's best to leave it on until your 100%
familiar with your romset and what versions of certain games actually work in this core.......

GAMEX(1992, sonic,    0,        sys32_hi, sonic,    sonic,    ROT0, "Sega", "Sonic (Japan rev. C)", GAME_NOT_WORKING | GAME_UNEMULATED_PROTECTION ) <<<<<<<<<<<<<<<<<<<-

GAMEX(1992, sonicp,   sonic,    sys32_hi, sonic,    sonic,    ROT0, "Sega", "Sonic (Japan prototype)", GAME_IMPERFECT_GRAPHICS ) <<<<<<<<<<<<<<<<<<<<<<,-

**Comment by arcadez2003** [comment]
Not a bug so this can be closed

**Comment by mahoneyt944** [comment]
This is old, but note to the OP.

sonic.zip and sonicp.zip are now fully playable with recent updates to this core.
