### ISSUE TITLE
D-pad not working on Nintendo Switch

### ISSUE THREAD

**Issue by cminois** [libretro/mame2003-plus-libretro#719]
The D-pad of any controllers (joy-con, pro controller) is not working with the mame2003-plus core whereas it works perfectly with the mame2003 core. Please could you tell me how to make it work?

**Comment by arcadez2003** [comment]
There was a huge update done to the input handling for MAME2003-plus, im not privy to all 
the changes, plus although i dev on this core i dont use it personally so i cant advise you on how
to go about setting up the correct keymappings to work with your Joycon D-pad.

Feel free to raise this issue on the Rpi forums im sure someone more versed in the mame2003-plus
input structure will be able to help

https://retropie.org.uk/forum/topic/17766/mame2003-plus-hundreds-of-new-games-improved-input-features-new-bugs-now-with-runahead-support

**Comment by cminois** [comment]
I finally find how to activate D-pad by changing control mapping from analog to digital in the core options.

**Comment by arcadez2003** [comment]
Ok happy ending
