### ISSUE TITLE
F1 Super Lap unprotected rom support

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/mame2003-plus-libretro#720]
https://github.com/mamedev/mame/commit/952b2d2de4da444f8b1906ebecb86e246f1b0ce2

might be worth adding, this one's a World version.

**Comment by arcadez2003** [comment]
Sure as the version we support has many how to play screens in Japanese and it would be handy
to have an English language version at least, plus with it being unprotected we can be sure the
emulation of F1 Super Lap will be more or less perfect in this core.

I'll look into adding this asp it's just the roms would require a large reshuffle and alotta users are
not keen on that so i gotta weigh it up.

**Comment by mahoneyt944** [comment]
@arcadez2003 are we still looking to add this or no?

**Comment by arcadez2003** [comment]
Leave it with me

**Comment by arcadez2003** [comment]
Actually i think we'll just leave this one as we already support a perfectly playable version of F1 Superlap

**Comment by mahoneyt944** [comment]
Is the version we support English? I think that was the main goal anyhow.

**Comment by arcadez2003** [comment]
Two min job to support the world version i'll do it if you then update the dat file deal.??

**Comment by mahoneyt944** [comment]
How many sets?

**Comment by arcadez2003** [comment]
Just 2 sets World and Japan.

**Comment by mahoneyt944** [comment]
I can sometime this weekend I guess, I just did a bunch of midway bootstraps and I've had enough for the day lol.

**Comment by Wilstorm** [comment]
I don't think you need to update the DAT manually. You should be able generate a current DAT in game.

**Comment by arcadez2003** [comment]
Yeah this will need updated to reflect the rom changes for f1lap, i'd do it myself but i dont have the special git tools
setup on my PC, i'll update the catver.ini right enough.

**Comment by Wilstorm** [comment]
Ah, hey Arcadez, sorry, yeah I meant you could generate it in game after the PR and upload but I know what you're saying now. It's to large to manually update! ;) I do have the tools setup for larger files if you need I can do a PR if @mahoneyt944 doesn't have it setup but I think he had a few PR's updating the DAT.

**Comment by mahoneyt944** [comment]
I just updated the dat by hand in desktop git when I did neogeo. Probably what I'll do here too. Half way done

**Comment by Wilstorm** [comment]
@mahoneyt944 - Ok, sounds good. You can also generate a current DAT in any game and diff the file. It only takes a moment but if you're ok manually doing it that works just fine too.

**Comment by mahoneyt944** [comment]
Done.

**Comment by Wilstorm** [comment]
@mahoneyt944 - Fast, thanks! :)

**Comment by mahoneyt944** [comment]
@Wilstorm any chance you'd want to test all the max player changes? Posted a list in #604

**Comment by Wilstorm** [comment]
@mahoneyt944 - Yeah for sure I'm just heading out from work here but over the weekend I'll get them loaded and give them a go!

**Comment by mahoneyt944** [comment]
Some of the midway games now have new bootstraps too. So the sound should be better for those without CMOS errors. Hard to tell if any are too loud but I think they are close.

smashtv
smashtv4
smashtv5
smashtv6
nbahangt
nbamaxht
wwfmania
Openice
