### ISSUE TITLE
beathead - retroarch crash

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/mame2003-plus-libretro#721]
`[libretro ERROR] cpunum_get_localtime() called for invalid cpu num!`
maybe this might be the problem?

**Comment by arcadez2003** [comment]
Sounds like a core timing issue maybe, does beathead work in mame2003 libretro.??

**Comment by arnoldsecret** [comment]
mame2003 also crashes beathead

**Comment by arnoldsecret** [comment]
in addition, mame2003 non-libretro has beathead working just fine.

**Comment by arcadez2003** [comment]
Yeah im aware it works on non libretro builds, nailing down the issue on the libretro side
which is causing the game to not work will always be the tricky part.

**Comment by arnoldsecret** [comment]
clarification: it seems that it's not a core timing issue, that error shows up on verbose no matter what game gets launched, likewise, the verbose doesn't show anything noteworthy post-game launch.

**Comment by arcadez2003** [comment]
grant2258 sent me a fix for this Beathead should work now
