### ISSUE TITLE
midwunit - support nbamht

### ISSUE THREAD

**Issue by meowthed** [libretro/mame2003-plus-libretro#723]
It's added in MAME 0.81u5, before the DCS sound update in 0.84u3.

**Comment by arcadez2003** [comment]
It's just another version of a game we already support, it wont offer anything new gameplay wise.

**Comment by krisztianb** [comment]
Why would you close this just like that?

NBA Maximum Hangtime includes the following additions:

* New rosters for 1997 season including player trades and college rookies.
* Hot spots : Each player has a hidden spot on the court where they are more accurate. You'll know you're on it when a pulsing circle appears at your feet and you hear a sound effect from one of Turmell's favorite games, "Robotron - 2084". The announcer usually mentions the hot spot as well.
* Activate outdoor court on match-up screen without having to enter a secret code.

Info copied from: https://www.gamesdatabase.org/mame-rom/nbamht

**Comment by arcadez2003** [comment]
Hint if you want me to add support for this game your not going about it the correct way just sayin :)

**Comment by arcadez2003** [comment]
So @mahoneyt944 are you willing to take a look at this considering how the latest request for this game came about.??

**Comment by krisztianb** [comment]
Thanks for replying. Since this was already closed I wasn't even expecting a reply. I'm sorry if I came across as a bit harsh.

**Comment by mahoneyt944** [comment]
@arcadez2003 I can add the bootstrap. No problem there.

**Comment by arcadez2003** [comment]
@mahoneyt944 thanks man i've done the roms i'll update the driver shortly

**Comment by meowthed** [comment]
closing this as it is now added in the latest commit.

**Comment by mahoneyt944** [comment]
@arcadez2003 looks like we may have lucked out on this one. The bootstrap for the older rev seems to work just fine on this one too, I don't think the rev is signed to the nv like other midway titles.

**Comment by krisztianb** [comment]
Thanks you very much. I'll see if I can get the game running here on my RetroPie.

**Comment by arcadez2003** [comment]
> @arcadez2003 looks like we may have lucked out on this one. The bootstrap for the older rev seems to work just fine on this one too, I don't think the rev is signed to the nv like other midway titles.

Well that was a handy stroke of luck :)

**Comment by krisztianb** [comment]
Hey guys. Could it be that this game was already supported under a different name? I looked at the [compatibility table](https://buildbot.libretro.com/compatibility_lists/cores/mame2003-plus/mame2003-plus.html) and saw that it is listed as **nbamaxht** and not **nbamht**. So I simply renamed the game rom and got it working.

**Comment by mahoneyt944** [comment]
> Hey guys. Could it be that this game was already supported under a different name? I looked at the [compatibility table](https://buildbot.libretro.com/compatibility_lists/cores/mame2003-plus/mame2003-plus.html) and saw that it is listed as **nbamaxht** and not **nbamht**. So I simply renamed the game rom and got it working.

Yes this is what was mentioned by @arcadez2003 in the beginning. Though this rev is slightly newer than what we supported.
