### ISSUE TITLE
fix 9ballsht, coolpool

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/mame2003-plus-libretro#725]
It was promoted to working in MAME 0.96u2. Notable changes that make this game work is:
```
Added the ability to specify internal read/write handlers for CPUs so
that the new debugger can view internal RAM. Hooked this up for the
TMS32025 core. [Aaron Giles]

Fixed window mode 1 in the TMS34010 core, as well as bugs that prevented
misaligned stack accesses from working and a bug that didn't force the
PC to be 16-bit aligned. [Aaron Giles]

Fixed bug in MAC instructions in the TMS32025 core. Also fixed cycle
counting 
problems that led to inaccurate internal timers. [Aaron Giles]
```

**Comment by arcadez2003** [comment]
I tried to get these to work a few months back but ran into trouble with the DSP cpu coms,
i might try again but the differences in how the cpu and rom loading is handled in MAME78
will be problamatic.

**Comment by arcadez2003** [comment]
I remember now the TMS32025 CPU will require some code changes which are not compatable
with this core, so im afraid this request is not doable, pity as these games are pretty decent.
