### ISSUE TITLE
fix hyprduel

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/mame2003-plus-libretro#726]
Good shmup made by the same developer as the Thunder Force series.

**Comment by arcadez2003** [comment]
A little more info around what problems said games have would be nice ;) but yeah i know the
parent version of this game does not work, the fix is to take the graphical roms from the working
japan clone.

However i see a sprite prio fix from MAME82 or so which i'll port over to this core.

**Comment by arcadez2003** [comment]
Aye i see what ya mean the game reboots as soon as you try and start a level, well it did that
for me in MAME72, anyway an update to the graphical handling and a small change to the cpu
synch timer speed and the game is now fully playable.

Thanks for the bug report.
