### ISSUE TITLE
inufuku - support 3on3dunk

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/mame2003-plus-libretro#728]
`- 0.147u2: ShouTime, Smitdogg and The Dumping Union added '3 On 3 Dunk Madness (US, prototype? 1997/02/04)' (Video System Co. 1996). VideoSystem improvements: Moving more sprite functions around preparing them for merging. Further unification of the Video System functions, improved rendering of players in '3 On 3 Dunk Madness' and promoted it to working [David Haywood]. Added correct ROM names and trimmed the speech ROM back to 24Mb [Phil Bennett].`

**Comment by arcadez2003** [comment]
As you read above a huge update to the video system graphics and all related drivers would be required to support this one, obviously too much graft for one extra game.
