### ISSUE TITLE
temporarily hold on making changes to mame2003-plus

### ISSUE THREAD

**Issue by markwkidd** [libretro/mame2003-plus-libretro#73]
Hi @grant2258 and @arcadez -- a couple of the libretro developers are in the middle of updating this codebase in terms of Makefile and the standard libretro-common libraries.

If it's OK with you all, the three of us should wait to merge any new code until mame2003-plus is compiling again.

**Comment by grant2258** [comment]
no problems at all mark wont touch anything. All i Plan to do is change the timing stuff a cleaner way. But i need to do testing and it isint a rush anyway

**Comment by markwkidd** [comment]
Thanks! I just got a message from twinaphex saying that they are done working with this code for now. I'm closing the issue, now it's back to the fun.

**Comment by grant2258** [comment]
i sent wrong screenshot to the vector page wasnt from the latest mame ill take more and change to the right version and sent the shots
