### ISSUE TITLE
Fresh installation on Android, run any game - Crash RetroArch 

### ISSUE THREAD

**Issue by kslawinskiB** [libretro/mame2003-plus-libretro#730]
Install RetroArch nad download this core, when load any game then RetroArch get crash.
Last log row:
[MAME2003+] ... hiscores.dat is not found......

But when you copy .../saves/(this core)/hi folder with content from another RetroArch installation (e.g. Windows, Linux) then everything is ok and any games run correct.

**Comment by telanus** [comment]
OK so for me it fixed when I copied my folder from my PC to /system/mame2003-plus

**Comment by mahoneyt944** [comment]
@kslawinskiB please close this issue unless you still need help with this topic.
