### ISSUE TITLE
fix rougien

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/mame2003-plus-libretro#731]
```
- 0.141u3: Angelo Salese corrected background color in Rougien.

- 0.136u4: Fabio Priuli added driver_data struct and save states to Mermaid driver.

- 0.128u4: Stephane Humbert fixed dipswitches for Rougien. Added 'Difficulty' dipswitch.

- 0.124u1: Roberto Zandona added proper implentation of hardware collision in Mermaid driver, fixed priorities in Rougien and a sprite wrapping bug.

- 0.123u2: Changed palettesize to 68 colors.

- 0.88u3: Curt Coder converted Mermaid driver to tilemaps, merged memory map, cleaned up driver and removed fake input port.

- 6th October 2004: MASH - Fixed gfx banking in Rougien. Game now playable.
```

there's some sound fixes that require adding a sound driver but it might not be possible to backport.

**Comment by arcadez2003** [comment]
I looked at this it's alotta work, im winding down with this core pretty much i dont mind doin the
odd fix here and there if it's not too labour intensive but as you see above the driver and video will
need to be redone and that's before we get to the pallette rewrite and adding the speech samples
so im not gonna work on this personally.
