### ISSUE TITLE
sharkatt - retroarch crash on winx64

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/mame2003-plus-libretro#734]
trying to press start after coin input causes this one to crash retroarch.

**Comment by arcadez2003** [comment]
This one will likely be on the libretro side, as there are no bug reports on mametesters mentioning
a problem like this with Shark Attack.

**Comment by Wilstorm** [comment]
One more quick one and I should get back to work. :) I tested this on a Raspberry Pi 3 with m3plus build aa8e74a and 2003 build aa607d0 using Retroarch 1.7.6 and it seems to run fine. I am able to insert coins, start a game and eat the divers for 50 points a pop! Level 2? 100 points a pop! ;)

**Comment by arnoldsecret** [comment]
it seems that this issue is a Windows x64 problem, not a RPI problem.

**Comment by mahoneyt944** [comment]
Just updated the samples to use the new pause feature. Merge pending.

**Comment by mahoneyt944** [comment]
@arnoldsecret  Is this issue still a problem with our current build? Could you update from source and test?

**Comment by arnoldsecret** [comment]
closing now.
