### ISSUE TITLE
tpgolf - mark as imperfect graphics

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/mame2003-plus-libretro#735]
![tpgolf](https://user-images.githubusercontent.com/41223243/61171304-57f0d300-a5a8-11e9-9ac4-cd92f237d9d7.png)

this version fixes this, but it might not be compatible.

`0.124u1: Added new cpu2 rom and gfx3 roms ($100000, 100001).`

**Comment by arcadez2003** [comment]
Nope actually it's these commits which sort it........

0.91: Fixed some GFX bugs [A nonymous]. Changed VSync to 59.185608 Hz.
27th January 2005: Mamesick forwarded some NeoGeo video hardware emulation changes/improvements from an anonymous contributor which remove a hack previously used for kof94 and fix the auto-anim speed. He also fixed a few minor text errors in MAME. Mamesick fixed many graphical issues, including those in Thrash Rally, TWS96, Top Players Golf and possibly more.

**Comment by arcadez2003** [comment]
I've backported the small fixes required that will fix Top Players Golf and Tecmo World Cup Soccer 96
both of which are totally broken and Thrash Rally which has a few gfx niggles here and there, the
problem was with the tile layer zooming.

Also added this small speedup from MAME78 which should boost the performance in all the NeoGeo
games a bit....

0.84: Some minor NeoGeo rendering speedups [Carlos Santillan].

just waiting for a correct rom pre the MAME79.u2 changes so i can test tws96, for future reference
all these had either the main cpu graphical or sound roms redumped

/*
thw following sets are wrong in mame and should be changed, confirmed against real boards ...
TWS96 SAMSHO3 PULSTAR WHP KABUKIKL NEOBOMBE AOF3 SONICWI3 TURFMAST MSLUG GOALX3
NEODRIFT SSIDEKI4 NINJAMAS RAGNAGRD SAMSHO4 RBFFSPEC TWINSPRI WAKUWAK7 MAGDROP3
SHOCKTRO SHOCKTRA BLAZSTAR
*/
