### ISSUE TITLE
kingofb - noteworthy sprite fix

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/mame2003-plus-libretro#736]
`0.122u4: Roberto Zandona fixed weird sprite priority problems (kingofb37b6gre).`

In MAME2003, boxer sprite gets jagged when it's in front or behind the other boxer.

**Comment by arcadez2003** [comment]
Alotta your recent game requests or fixes would require a lot of work hence me putting them on the back burner for now, this one however was quick and easy the sprites had some encryption in King Of Boxer and Ring King (set3) which was not handled correctly in the video code it's all sorted now via
robizas code from MAME122.u4

I'll add the changes to the core later today, once again thanks for the headsup.
