### ISSUE TITLE
[Request] Tetris The Grand Master (tgmj) support

### ISSUE THREAD

**Issue by gregorulm** [libretro/mame2003-plus-libretro#738]
Is there any chance you could add support for Tetris The Grand Master (tgmj)? This game works very well in the latest versions of standard MAME. However, it has significant lag and would therefore benefit significantly from the run-ahead feature of mame2003-plus.

**Comment by arcadez2003** [comment]
None of the Sony PSX games are playable in MAME78 aka MAME 2003 core, so it would be a huge
amount of graft to get these up and running and alot of the changes i'd have to make it would be
hit and miss as to if i can rollback the code from later versions of MAME so it will function correctly 
in this core.

So for the above reasons im not gonna personally work on this but someone might come along
at some point who feels like taking this huge task on, in the meantime you can always play 
Tetris The Grand Master 2 which i added support for a while back it's the same game more or less.

Regards.

**Comment by gregorulm** [comment]
OK. Thanks for the feedback. I was not aware of the amount of work required to accommodate that request.

**Comment by arnoldsecret** [comment]
um, tekken and tekken2 works, albeit with no sound.

**Comment by gregorulm** [comment]
Tekken and its sequel run on a different board (ZN-2) than TGM (Namco System 11), though.

**Comment by arnoldsecret** [comment]
still the same psx archs though

**Comment by arcadez2003** [comment]
Similar but different just like chicken and turkey :) anyway this has come up before the problem is
the CPU which would be required to drive the sound in the tekken games is not backportable to
this core without a major overhaul which is above my level.

**Comment by gregorulm** [comment]
That's a different issue, though. To add to arnoldsecret's post, would it be possible to cobble together a driver for tgmj, considering that ZN-s and System 11 use the same PSX architecture? I'd assume that a lot of the ZN-2 code could be reused for System 11.
