### ISSUE TITLE
slowdown in two Taito games

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/mame2003-plus-libretro#742]
In Violence Fight (taito_b) and Solitary Fighter (taito_f2), during the fight the game slows down its speed, similar way to what games in the Jaleco MS32 had suffered in standalone.

**Comment by arcadez2003** [comment]
Yeah that's right i fixed these sometime ago in my xbox MAME builds i'll port the changes across
later on.

**Comment by arcadez2003** [comment]
Hmmm i cant remember what fixed these exactly i assumed it was the taito_f2 video improvements
i backported which sort some graphical niggles in Liquid Kids, Gun And Frontier, Pullarulla,
Metal Black and Super Space Invaders 91.

But no both games are still running slow in my test core, as i mind it was one of those accidental
fixes anyway i might be able to track down what code needs to change but if not i'll certainly
port the Taito F2 improvements across to this core.

**Comment by arcadez2003** [comment]
I cant get to the bottom of what i did to fix these games so closing this
