### ISSUE TITLE
rohga - can't seem to add schmeisr

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/mame2003-plus-libretro#743]
When I tried to test it out on my core code it throws an error;

`[libretro ERROR] cpunum_get_localtime() called for invalid cpu num!`

and crashes retroarch.

Here's the driver files.
[rohga.zip](https://github.com/libretro/mame2003-plus-libretro/files/3435456/rohga.zip)
[rohga_vidhrdw.zip](https://github.com/libretro/mame2003-plus-libretro/files/3435457/rohga_vidhrdw.zip)

**Comment by arcadez2003** [comment]
It's a not a very good game so i never bothered adding it when i hooked up Hangzo, ok from
first glance your memory maps are wrong i take it you removed the AM_MIRROR macro from..........

{ 0x3c8000, 0x3c8fff, 0x1000, MRA16_RAM},

You'll have to handle the mirror in the ole style as i did when adding Hangzo first make a copy
of the reads and writes that have a mirror then add the mirror value in this case 0x1000 to the 
copy like so.....

{ 0x3c8000, 0x3c8fff, MRA16_RAM},
{ 0x3c9000, 0x3c9fff, MRA16_RAM}, // mirror of above

You'll need to do this for everyone of them, tedious work but as we cant support direct mirroring
via the mem maps in MAME78 / 2003 it has to be done hence i never bothered adding too many
games which would require this extra effort unless they were worth adding ;)

**Comment by arnoldsecret** [comment]
progress for schmeisr, I managed to make the game work until adding in a coin, which crashes RA.

**Comment by arcadez2003** [comment]
Either dips or memory map most likely, firstly lets look at your mem map i noticed a wee mistake 
which might be throwing off the coining........

Remove the mirror for.........

{ 0x3c8000, 0x3c8fff, MRA16_RAM},
{ 0x3c8000, 0x3c8fff, MWA16_RAM, &deco16_pf1_rowscroll},

**Comment by arnoldsecret** [comment]
no, I mean the game launches fine, is that when you insert coin or wait for attract mode to show up it crashes.

Here's what I did to the read/write mem.
```
static MEMORY_READ16_START( schmeisr_readmem )
	{ 0x000000, 0x0fffff, MRA16_ROM },
	{ 0x280000, 0x2807ff, deco16_104_rohga_prot_r }, /* Protection device */
	{ 0x2c0000, 0x2c0001, rohga_dip3_r }, 
	{ 0x300000, 0x300001, nitrobal_control_r },
	{ 0x310002, 0x310003, schmeisr_control_r },
	{ 0x321100, 0x321101, MRA16_NOP }, /* Irq ack?  Value not used */
	{ 0x3c0000, 0x3c1fff, MRA16_RAM },
	{ 0x3c2000, 0x3c2fff, MRA16_RAM },
	{ 0x3c4000, 0x3c4fff, MRA16_RAM },
	{ 0x3c6000, 0x3c6fff, MRA16_RAM },
	{ 0x3c8000, 0x3c8fff, MRA16_RAM },
	{ 0x3ca000, 0x3cafff, MRA16_RAM },
	{ 0x3cb000, 0x3cbfff, MRA16_RAM }, /* Mirror */
	{ 0x3cc000, 0x3ccfff, MRA16_RAM },
	{ 0x3cd000, 0x3cdfff, MRA16_RAM }, /* Mirror */
	{ 0x3ce000, 0x3cefff, MRA16_RAM },
	{ 0x3d0000, 0x3d07ff, MRA16_RAM },
	{ 0x3e0000, 0x3e1fff, MRA16_RAM },
	{ 0x3e2000, 0x3e3fff, MRA16_RAM }, /* Mirror */
	{ 0xff0000, 0xff7fff, MRA16_RAM },
MEMORY_END

static MEMORY_WRITE16_START( schmeisr_writemem )
	{ 0x000000, 0x1fffff, MWA16_ROM },
	{ 0x200000, 0x20000f, MWA16_RAM, &deco16_pf12_control },
	{ 0x240000, 0x24000f, MWA16_RAM, &deco16_pf34_control },
	{ 0x280000, 0x2807ff, deco16_104_rohga_prot_w, &deco16_prot_ram }, /* Protection writes */
	{ 0x280800, 0x280fff, deco16_104_rohga_prot_w }, /* Mirror */
	{ 0x300000, 0x300001, rohga_buffer_spriteram16_w }, /* write 1 for sprite dma */
	{ 0x310000, 0x310009, MWA16_NOP }, /* Palette control? */
	{ 0x31000a, 0x31000b, deco16_palette_dma_w }, /* Write 1111 for dma?  (Or any value?) */
	{ 0x320000, 0x320001, MWA16_NOP }, /* ? */
	{ 0x322000, 0x322001, deco16_priority_w },
	{ 0x3c0000, 0x3c1fff, deco16_pf1_data_w, &deco16_pf1_data },
	{ 0x3c2000, 0x3c2fff, deco16_pf2_data_w, &deco16_pf2_data },
	{ 0x3c4000, 0x3c4fff, deco16_pf3_data_w, &deco16_pf3_data },
	{ 0x3c6000, 0x3c6fff, deco16_pf4_data_w, &deco16_pf4_data },
	{ 0x3c8000, 0x3c8fff, MWA16_RAM, &deco16_pf1_rowscroll },
	{ 0x3ca000, 0x3cafff, MWA16_RAM, &deco16_pf2_rowscroll },
	{ 0x3cb000, 0x3cbfff, MWA16_RAM }, /* Mirror */
	{ 0x3cc000, 0x3ccfff, MWA16_RAM, &deco16_pf3_rowscroll },
	{ 0x3cd000, 0x3cdfff, MWA16_RAM }, /* Mirror */
	{ 0x3ce000, 0x3cefff, MWA16_RAM, &deco16_pf4_rowscroll },
	{ 0x3cf000, 0x3cffff, MWA16_RAM }, /* Mirror */
	{ 0x3d0000, 0x3d07ff, MWA16_RAM, &spriteram16, &spriteram_size },
	{ 0x3e0000, 0x3e1fff, deco16_buffered_palette_w, &paletteram16 },
	{ 0x3e3000, 0x3e3fff, MWA16_RAM }, /* Mirror */
	{ 0xff0000, 0xff7fff, MWA16_RAM }, /* Main ram */
MEMORY_END
```

**Comment by arcadez2003** [comment]
I think this should hopefully sort it ya missed a couple of mirrors on the reads..........

static MEMORY_READ16_START( schmeisr_readmem )
	{ 0x000000, 0x0fffff, MRA16_ROM },
	{ 0x280000, 0x2807ff, deco16_104_rohga_prot_r }, /* Protection device */
	{ 0x280800, 0x280fff, MRA16_RAM }, /* Mirror */
	{ 0x2c0000, 0x2c0001, rohga_dip3_r }, 
	{ 0x300000, 0x300001, nitrobal_control_r },
	{ 0x310002, 0x310003, schmeisr_control_r },
	{ 0x321100, 0x321101, MRA16_NOP }, /* Irq ack?  Value not used */
	{ 0x3c0000, 0x3c1fff, MRA16_RAM },
	{ 0x3c2000, 0x3c2fff, MRA16_RAM },
	{ 0x3c4000, 0x3c4fff, MRA16_RAM },
	{ 0x3c6000, 0x3c6fff, MRA16_RAM },
	{ 0x3c8000, 0x3c8fff, MRA16_RAM },
	{ 0x3ca000, 0x3cafff, MRA16_RAM },
	{ 0x3cb000, 0x3cbfff, MRA16_RAM }, /* Mirror */
	{ 0x3cc000, 0x3ccfff, MRA16_RAM },
	{ 0x3cd000, 0x3cdfff, MRA16_RAM }, /* Mirror */
	{ 0x3ce000, 0x3cefff, MRA16_RAM },
	{ 0x3cf000, 0x3cffff, MRA16_RAM }, /* Mirror */
	{ 0x3d0000, 0x3d07ff, MRA16_RAM },
	{ 0x3e0000, 0x3e1fff, MRA16_RAM },
	{ 0x3e2000, 0x3e3fff, MRA16_RAM }, /* Mirror */
	{ 0xff0000, 0xff7fff, MRA16_RAM },
MEMORY_END

**Comment by arnoldsecret** [comment]
well, even after using the code in question, I still can't figure out why is my retroarch crashing. Code seems fine to me but can't get a log during the crash since the standard logging to text as found on the libretro docs is possibly changed.

**Comment by arcadez2003** [comment]
Yip it's crashing in my test build also, as you say all the driver code as well as the decryption
protection and video code are all fine, if i had to guess the core is not liking our workarounds
for the mirrors.

Yet it likes the same thing for Double Wings, Hangzo and Rohga Armor Force welcome to the
joys of backporting code meant for newer builds and trying to shoehorn it into an older core
such as this one 

Ya win some lose some let's forget about it and move on.
