### ISSUE TITLE
Backport Cave Cv1000 driver (3rd gen Cave shmups)

### ISSUE THREAD

**Issue by RaduNastase** [libretro/mame2003-plus-libretro#751]
Can this be done? It would be great to have a fast cv1000 driver for smartphones. This also needs CPU underclock option in order to work well, as cv1000 games geneneraly use less than 50% of the SH3 CPU.

**Comment by arcadez2003** [comment]
We dont have the SH3 CPU for starters, and i dont think it's possible to backport the newer CPU
cores into MAME2003, it's certainly above my level and there would likely be a load of code in
the driver and associated files which would have incompatable code also.

So it's a no go unless someone with more talent than me comes along :)

**Comment by RaduNastase** [comment]
Oh, i get it man. Thanks anyway, it's a great job you guys did here so far!

**Comment by blisstik** [comment]
mame2016 has cv1000, although it does have some slowdowns on arm hardware

**Comment by RaduNastase** [comment]
Actually Cv1000 is perfectly playable on mobiles, using the Mame 2014 core (the fast one, based on 0.157). Even the unsupported dumps like Daiffukatsu Black Label and Akai Katana can be made to run on this core. They work excellently on a Snapdragon 855.
