### ISSUE TITLE
Gaiapolis doesn't properly initialize/Possible backporting of Monster Maulers?

### ISSUE THREAD

**Issue by KMFDManic** [libretro/mame2003-plus-libretro#753]
@arcadez2003 @markwkidd This one might be for you two:)  And, as always, thanks!

mystwarr.c driver

PC RetroArch with the Core runs Gaiapolis fine.  But, it doesn't initialize properly on some of the other platforms.  A similar issue affected Run and Gun awhile back.  Monster Maulers, being on the same driver in MAME 2010, etc, should hopefully be able to be backported.  Seems to be EEPROM relative, as far as both Gaiapolis and Monster Maulers.

markwkidd fixed Run and Gun with an nvram bootstrap
  
This was the known issue:

**Run and Gun** Fixed already by markwkidd

EEP ROM 35E shows up bad - hold down F2 and TAP Reset F3 to init the EEPROM properly. When the message appears, let go of F2.

**Monster Maulers** Initializes on PC RetroArch with MAME 2010.  But not on other platforms

The first time you run the game, the EEPROM 28B shows as BAD in the RAM/ROM Check. Hold down the Test switch F2 and then also hit F3 to reset the machine, creating the EEPROM for you.

**Gaiapolis**  Initializes on PC RetroArch with MAME 2003 Plus.  But not on other platforms

The first time you run the game, the EEPROM 28B shows as BAD in the RAM/ROM Check. Hold down the Test switch F2 and then also hit F3 to reset the machine, creating the EEPROM for you.

**Comment by arcadez2003** [comment]
Bootstraps were always done by @markwkidd never having done one myself im not sure of what
boot values to give either of the games as you can see they're different for each one i dunno
how you go about getting these.............

https://github.com/libretro/mame2003-plus-libretro/blob/8b2e0b304f450f116cef8fb52cc77806d676efe8/src/bootstrap.c

As for Monster Maulers we already support the japan version Kyukyoku Sentai Dadandarn
however i suppose it would be easy enough the add support for the English version of
this game..........

0.82u2: R. Belmont added Monster Maulers (Europe ver EAA).
enough to add it here

**Comment by KMFDManic** [comment]
Yeah, @arcadez2003 , @markwkidd was awesome in helping me get Run and Gun going with Xtreme.  Hopefully, he can shed some light on these other 2 great games!  The Japan version is absolutely fine, if the bootstrap fix can be applied to that.  Odd that this works ok on PC, but fails on some of the other platforms.  There are always other things to look into:)  

By the way, the last Release I posted went quite well with the Mini Classic Users, Xtreme/Plus alike.  So, thanks again!

**Comment by markwkidd** [comment]
Hi folks, I hope you're doing well. I saw my name and I felt like popping
in.

Historically, a lot but not all of my time working on emulation came when I
wasn't feeling well enough to do other work. Frustratingly, the last few
months I have been stuck in bed more than ever but my health doesn't allow
me to fill that time with interesting things like coding and documenting
right now.


I am working towards a recovery and I have every intention of resuming my
hobbies as I get better.

🤖


.

**Comment by Wilstorm** [comment]
@markwkidd - It's been a while! It's good to hear you're still out there fighting the good fight. I hope all goes well and for a speedy recovery. Getting old(er) is the pits! ;)

**Comment by arcadez2003** [comment]
@markwkidd Sorry to hear your a bit under the weather, im sure you'll perk up soon enough.

**Comment by mahoneyt944** [comment]
@KMFDManic  added boot strap merge pending #851

**Comment by mahoneyt944** [comment]
@KMFDManic could you test the new boot strap on the platforms you had issues with? Update mame 2003 plus from source.

**Comment by mahoneyt944** [comment]
@KMFDManic  final step to close this issue #872 now supported merge pending.

**Comment by mahoneyt944** [comment]
@KMFDManic you can close this issue as it's now supported in #872 , merge pending. Thank you.

**Comment by KMFDManic** [comment]
@mahoneyt944 awesome:) Will take a look at latest coding later today.  Thanks again:)
