### ISSUE TITLE
Backport the RNG of Stadium Hero

### ISSUE THREAD

**Issue by litaniast** [libretro/mame2003-plus-libretro#754]
https://github.com/mamedev/mame/commit/880f2b7ae1582db69443e922880ecd1ab1096eb0

Latest mainline MAME has awesome improve of Stadium Hero, the baseball game of Data East.
Current emulation of that game has different behavior from real PCB. in current stable MAME (and of course MAME2003) has only flyball, CPU doesn't steal a base, and music doesn't change.

Look at the real PCB video.

https://www.youtube.com/watch?v=6azneK6uUnA

But recently, it finally fixed in MAME, it will be adopted in MAME 0.215 version. At last, batters can now hit ground ball, runners steal the base, and music changes!!

I think it can be backported easily in MAME2003-plus.

**Comment by arcadez2003** [comment]
I think it can be backported easily in MAME2003-plus.

Not really as our stadhero.c driver is totally different, it might be possible to backport these
changes but that would require us to update the driver while at the same time making sure
it's still compatible firstly with the MAME2003 codebase and the wider DECO code which
ties together a whole host of DATA EAST games.

Check our driver vs the latest MAME one and you'll see what i mean.

**Comment by litaniast** [comment]
Maybe, method in fbneo could be used? (same behavior fix, but different method)

https://github.com/finalburnneo/FBNeo/commit/c50e7196794b226db54763da22b98cd1bc7e3d30#diff-ad3375158facca9285ee268d5a6ec076

**Comment by arcadez2003** [comment]
It'll have to go here, what to do though drop it in below case 4 or create a new case for it.......

Option 1

static READ16_HANDLER( stadhero_control_r )
{
	switch (offset<<1)
	{
		case 0: /* Player 1 & 2 joystick & buttons */
			return (readinputport(0) + (readinputport(1) << 8));

		case 2: /* Credits, start buttons */
			return readinputport(2) | (readinputport(2)<<8);

		case 4: /* Byte 4: Dipswitch bank 2, Byte 5: Dipswitch Bank 1 */
			return (readinputport(3) + (readinputport(4) << 8));

                        return mame_rand() & 0x3f;	
	}

	logerror("CPU #0 PC %06x: warning - read unmapped memory address %06x\n",activecpu_get_pc(),0x30c000+offset);
	return ~0;
}

Option 2

static READ16_HANDLER( stadhero_control_r )
{
	switch (offset<<1)
	{
		case 0: /* Player 1 & 2 joystick & buttons */
			return (readinputport(0) + (readinputport(1) << 8));

		case 2: /* Credits, start buttons */
			return readinputport(2) | (readinputport(2)<<8);

		case 4: /* Byte 4: Dipswitch bank 2, Byte 5: Dipswitch Bank 1 */
			return (readinputport(3) + (readinputport(4) << 8));
                
                case 5:
                        return mame_rand() & 0x3f;	
	}

	logerror("CPU #0 PC %06x: warning - read unmapped memory address %06x\n",activecpu_get_pc(),0x30c000+offset);
	return ~0;
}

**Comment by arcadez2003** [comment]
Alright via advice from dink im gonna make it case 6, try it and let me know if it worked or not

**Comment by litaniast** [comment]
Sorry. It doesn't work either.

**Comment by arcadez2003** [comment]
Fair enough it was worth a try at least.
