### ISSUE TITLE
Screen rotate not working in Vulkan driver of RA

### ISSUE THREAD

**Issue by bryc** [libretro/mame2003-plus-libretro#755]
I use the Vulkan renderer in RetroArch. All vertical games appear sideways when they should adjust automatically. Affected games include Contra and 1942. SF2CE and Rtype2 are unaffected.

**Comment by markwkidd** [comment]
That's an issue with the Vulkan driver not implementing some of the liberto
API rather than an issue with this core.

**Comment by bryc** [comment]
Hm never mind. I had 'Allow Rotation' disabled in Settings > Core.
