### ISSUE TITLE
Config file as binary / gibberish

### ISSUE THREAD

**Issue by Speedy2662** [libretro/mame2003-plus-libretro#757]
When I try to open the MAME config file (from saves > mame2003+plus > cfg folder) it comes up as this:
![image](https://user-images.githubusercontent.com/8947452/68712878-8a313200-0594-11ea-899f-43f4c78fee0a.png)
instead of the normal plaintext file.

**Comment by Wilstorm** [comment]
I don't think those files are in any type of "human-readable" form but I do agree it would be nice search and replace inputs on a class of game like fighters, shumps or all SF and clones, etc. 

It seems unnecessary to "encrypt" them. I've tried looking up the how's and why's but never could found the answer. I think it was just ported over from regular MAME and not a Libretro thing and probably won't change unless it's some quick/easy coding.
