### ISSUE TITLE
Fighters History Sprite Priority issue (deco32.c) Ryoko stage 

### ISSUE THREAD

**Issue by Riddler1** [libretro/mame2003-plus-libretro#760]
Running on retropie lr MAME 2003-plus.

See Video Link below (Old man and Child chasing cat in background)  https://youtu.be/3oad3bmaE3o

Driver known to have unencrypted elements but thought a fix was mentioned in: https://github.com/libretro/mame2003-plus-libretro/commit/3b2245564823961e9dcfd2b134c6d3609f183bb7

**Comment by arcadez2003** [comment]
Yeah the deco32 backport code was by a couple of other dev's i only ported it across to this core
not having got that far in the game i assumed it was sorted as our deco32 video code has the
fixes, but i've just spotted something they forgot to add to the driver connected to fix.

I'll add it in now lemmie know if that sorts the problems.............

https://github.com/libretro/mame2003-plus-libretro/commit/a50d28e82d679e6c8295668db2164f9e67c8827b

**Comment by Riddler1** [comment]
Yes, you fixed it! Working great 👍

https://youtu.be/qtFLXTRV5qk

**Comment by arcadez2003** [comment]
Another happy ending, i'll close this down now and thanks for the bug report cheers!!
