### ISSUE TITLE
None of the Golden Axe games work on Android

### ISSUE THREAD

**Issue by Zingam** [libretro/mame2003-plus-libretro#761]
No Golden Axe ROM by SEGA I tried works for me on Android.
goldenaxe.zip
ga2.zip
etc.
Including a few games from Capcom like: Armored Warriors, Dynasy Warriors.

**Comment by arcadez2003** [comment]
Check your roms to make sure they are correct for MAME78

**Comment by Riddler1** [comment]
Hello, i tested and confirm that the 0.78 set for "goldnaxe" does work on both my Android device and retropie. 

However "goldnaxj"  & "goldnabl" 0.78 sets both only load to a black screen in both Android and retropie (mame options tab is available). Unable to access service mode also.

**Comment by Riddler1** [comment]
Tested mame2003-Plus on Android device (Samsung Galaxy S8):

Armored Warriors - "armwar" & "armawaru" 0.78 rom sets both work on my android device
Warriors of Fate - "wof" & "wofu" 0.78 rom sets both work on my android device
Dynasty Wars - "dw" & "dwj" 0.78 rom sets both work on my android device

**Comment by Zingam** [comment]
Thank you for the info. I forgot to reply earlier. I was out of the emulation game for a while. My ROM collection was 15+ years old, so I had to find new ROMsets. I was confused because some of the old ROMs worked.
