### ISSUE TITLE
Metamorphic Force - Bonus Stage Intro Text (mystwarr.c)

### ISSUE THREAD

**Issue by Riddler1** [libretro/mame2003-plus-libretro#762]
After Stage 2 the bonus stage begins but the intro text that reads "break the statue" is broken.

Not sure if this is IRQ or scroll data issue. Screenshots below show broken and working examples.

Broken:  (MAME 2003 & 2003-plus)
 ![20191208_172654_1](https://user-images.githubusercontent.com/43607359/70473093-40226a00-1ac8-11ea-97e9-fe4c33a4a5ed.gif)

Working: (Final burn)
![20191208_172924_1](https://user-images.githubusercontent.com/43607359/70473127-516b7680-1ac8-11ea-8674-f5af2cb43734.gif)

**Comment by arcadez2003** [comment]
Does it do this in MAME2003 also.?? Nothing in the MAME WIP which mentions a fix for this
i'll ask dink about it later, as i know he's done alotta video fixes for the Konami games which
didn't get ported across to MAME.

**Comment by arcadez2003** [comment]
Actually this is the fix........

https://github.com/dinkc64/mame/commit/4b1dbd6f00944b5c266350e15ac6d45d55353b67#diff-68d2c9c7ca85df42b597fa1e23fb5301

i can change the vis area and the sprite callback but this ole core does not have direct per game
mapping to the graphical chip, so the mystwarr.c games will likely all share the same K053252
routines somewhere in the konamiic video file i'll need to check it out sometime


	MCFG_DEVICE_MODIFY("k053252")
	MCFG_K053252_OFFSETS(24, 15)

**Comment by Riddler1** [comment]
> Does it do this in MAME2003 also.?? Nothing in the MAME WIP which mentions a fix for this
> i'll ask dink about it later, as i know he's done alotta video fixes for the Konami games which
> didn't get ported across to MAME.

Thanks for taking a look. Yes it happens in MAME 2003 also. 👍

**Comment by arcadez2003** [comment]
Ok as i said i can tweak the vis area and change the sprite callback, if i make the changes will you test 
the game for me give it a right good play.?? as i need to know if doing two outta the three fixes
will sort the issue you pointed out but at the same time not break something else.

**Comment by Riddler1** [comment]
> doing

Ok, Yes. Im happy to give it a thorough play test when you are ready.

**Comment by Riddler1** [comment]
Just to add that after Stage 4 there is a second and final bonus game with the same intro text issue:
![20191209_191749_2](https://user-images.githubusercontent.com/43607359/70472416-f5ecb900-1ac6-11ea-9b96-454ba537dd65.gif)

After the bonus stage the text appears correct:
![20191209_191749_1](https://user-images.githubusercontent.com/43607359/70472440-000eb780-1ac7-11ea-8944-97a5eb4b40e8.gif)

**Comment by arcadez2003** [comment]
Alright try it again and hopefully with a bit of luck it'll be sorted.

**Comment by Riddler1** [comment]
Hi, i updated and tested but both bonus stages are still the same broken text. No other issues seen in the game but....

I noticed the change has also created a glitch in the womans face after you choose a character. Maybe revert this change i think.

Before:
![20191210_200024_1](https://user-images.githubusercontent.com/43607359/70564823-c605ea00-1b88-11ea-83da-d32e8595120f.gif)

After:
![20191210_200450_1](https://user-images.githubusercontent.com/43607359/70564825-c69e8080-1b88-11ea-80fc-f0bf8e842947.gif)

**Comment by arcadez2003** [comment]
Yip better to switch back the code to what it was before.
