### ISSUE TITLE
Cyclone and DrZ80

### ISSUE THREAD

**Issue by duduke** [libretro/mame2003-plus-libretro#765]
Can those commits:
https://github.com/libretro/mame2000-libretro/commit/ad07ac38747bd8abc74ea143dd73b7a05ee4d3be
https://github.com/libretro/mame2000-libretro/commit/1e09c86764f74b2a0ebad601df745cb7995d5c7f

Be ported to the mame2003-plus core? Can they be enabled for Pi0 as well?

**Comment by arcadez2003** [comment]
I've never heard of the Cyclone or the DrZ80, certainly unlike MAME2000 this core does not
support either of them, so i cant port the above commits into this core for obvious reasons

Regards

**Comment by frangarcj** [comment]
I'm porting those but I'm trying to figure out how to change an already inited driver

**Comment by arcadez2003** [comment]
what do you mean by inited driver.??

**Comment by frangarcj** [comment]
https://github.com/libretro/mame2000-libretro/commit/1e09c86764f74b2a0ebad601df745cb7995d5c7f#diff-c9ef03e11cee1e52c6ef5fc5cad11184R821

I got an error of wrong number of cpus later

**Comment by frangarcj** [comment]
```
static data32_t cpu_readmem24bew_dword(offs_t address)
{
  89bd88:       e24dd014        sub     sp, sp, #20
  89bd8c:       e58d0004        str     r0, [sp, #4]
        data32_t result = cpu_readmem24bew_word(address) << 16;
  89bd90:       e59d0004        ldr     r0, [sp, #4]
  89bd94:       ebe44bfb        bl      1aed88 <cpu_readmem24bew_word>
!!!             e1a03000        mov     r3, r0 !!!
  89bd9c:       e1a03803        lsl     r3, r3, #16
  89bda0:       e58d300c        str     r3, [sp, #12]
        return result | cpu_readmem24bew_word(address + 2);
  89bda4:       e59d3004        ldr     r3, [sp, #4]
```

Some advance!!!

**Comment by frangarcj** [comment]
It works, I'll make a PR later
