### ISSUE TITLE
sparkman 2p - ez fix from dink

### ISSUE THREAD

**Issue by dinkc64** [libretro/mame2003-plus-libretro#771]
@arcadez2003,
In sparkman, 2p's bomb button doesn't work (it's stuck).  To fix it, try changing this line in drivers/suna8.cpp:
{ 0xc080, 0xc080, input_port_4_r }, // Buttons
to:
{ 0xc080, 0xc081, input_port_4_r }, // Buttons

best regards,
- dink

**Comment by arcadez2003** [comment]
Thanks for the heids up bigman but Sparkman disnae work in this core and it would require alotta
work to update suna8.c to the version where all the games actually work.

**Comment by dinkc64** [comment]
alright buddy, if you need help with anything you know where to find me!

best regards,
- dink
