### ISSUE TITLE
arcadez2003 and arnoldsecret - 2FA

### ISSUE THREAD

**Issue by twinaphex** [libretro/mame2003-plus-libretro#774]
Hi @arcadez2003 and @arnoldsecret ,

we are required to start enabling 2FA on our Libretro organization. Is it possible for you to enable this for your user account?

**Comment by arnoldsecret** [comment]
will do.

**Comment by arcadez2003** [comment]
TBH i fully expect to be closing my github account very shortly as i consider myself to be retired
from active dev on this core and more generally, so for that reason i see no point in me setting
up 2FA for an account im about to dispense with.

Regards.

**Comment by twinaphex** [comment]
Alright, that's your decision and we'll respect it.

**Comment by arnoldsecret** [comment]
that leaves me to take head of the core, which I'm seriously don't have the patience right now to work on. I think most of the work here is already done btw.

**Comment by twinaphex** [comment]
Alright guys, in case it matters, 2FA is no longer required thanks to Github.
