### ISSUE TITLE
No way to remap "Mame Menu" key, always hardcoded to L3

### ISSUE THREAD

**Issue by rsn8887** [libretro/mame2003-plus-libretro#777]
There needs to be a way to remap the name menu to something other than hard-coded L3. The Mame menu is needed to set dipswitches to change difficulty. It is also used in game with dial/analog controls to set analog sensitivity. Many controllers don't have L3 buttons so they cannot bring up the Mame menu.

**Comment by WindyWinston** [comment]
You can bring up the MAME menu in the core options 'Display MAME menu'. Select 'Input (general)' and then you can map a key/button to the 'Config Menu' option (first on the list).

**Comment by Darknior** [comment]
Thanks you teach it to me too :)

**Comment by Wilstorm** [comment]
If you don't have L3 on your controller you'll probably need to plug in a keyboard momentarily and use the TAB key while in game to pull up the MAME menu. I believe under "Input (General)" the option is named "Config Menu". Just press the enter key and then you may reassign a new keyboard key, controller button or a combination of both. Then you'll have a few ways to get into the menu. You can also do combination's like shift+c, button 1+2 or left stick+button 1, etc.

**Comment by rsn8887** [comment]
How cool I did not know all that. Since the core option "Display Mame menu" actually works, I will close this.
