### ISSUE TITLE
Mame menu is still needed for dipswitches and more

### ISSUE THREAD

**Issue by rsn8887** [libretro/mame2003-plus-libretro#778]
Dipswitches and other game settings like analog/digital sensitivity can only be set via Mame menu, which can only be brought up via hardcoded L3 mapping.

The Mame menu options like dipswitch settings and analog sensitivity settings etc. should be implemented as core options ideally, similar to FBNeo core.

**Comment by Wilstorm** [comment]
I don't believe this will happen any time soon due to the amount of coding that would be involved to convert/move those options from the MAME TAB menu to the Libretro core. Most of the core guys are done and only making tweaks and additions here and there when they find a good fit or easy game to add. It's always good to think positive though! :)

**Comment by mahoneyt944** [comment]
You can set the name menu to any button combination you'd like. I use "player1 start, player 2 start and x" as my mame menu toggle.

**Comment by gomisensei** [comment]
> You can set the mame menu to any button combination you'd like. I use "player1 start, player 2 start and x" as my mame menu toggle.

That's not the MAME emhu, it's the RetroArch menu.... I would definitely approve of being able to set a key combo for the mame menu, or at least change the default binding for it.

it's set tp L3 by this core, (L2 by mame2010) but there's also a core option to turn the menu on/off, there should be an option to turn the L3 bind off.

**Comment by mahoneyt944** [comment]
No, retroarch menu is select + x....You can change your mame menu toggle key under "input general", the top option is "config menu". Bind any combination of keys you'd like.

**Comment by Wilstorm** [comment]
@gomisensei - The L2 input may easily be set it to “None” which effectively shuts it off or as @mahoneyt944 pointed you can assign it to any button combination you want and/or not mappings with focus input.

**Comment by mahoneyt944** [comment]
@rsn8887 please close this issue unless you still need help with this topic.
