### ISSUE TITLE
Build failures

### ISSUE THREAD

**Issue by twinaphex** [libretro/mame2003-plus-libretro#794]
Hi @arcadez2003 ,

after merging the PRs, there are some build failures now -

Android -

http://paste.libretro.com/207831

iOS -

mame2003_plus: [Status: fail] [recipes/apple/cores-ios9-generic] [Finished: 2020-05-21 13:37:30.377743+00:00] [http://paste.libretro.com/207830]

**Comment by arcadez2003** [comment]
Hi @twinaphex 

I'll review the code later but lets see if the buildbot compile settles down first, on first glance everything seems correct for tnk3b which is what the build failure is complaining about, i'll go
over it with a fine tooth comb tonight.

**Comment by twinaphex** [comment]
Thanks, much appreciated.

**Comment by arcadez2003** [comment]
I think the build is good now eh.?? it's seem to compile across all the platforms which is a good sign.

**Comment by twinaphex** [comment]
Yeah I think these issues are resolved now. Thank you. Going to close this.
