### ISSUE TITLE
Can't press pedal on Pole Position 1/2

### ISSUE THREAD

**Issue by litaniast** [libretro/mame2003-plus-libretro#809]
No pedal button is assigned, it makes that series aren't playable

Both Pole Position and Pole Position 2

**Comment by arcadez2003** [comment]
I had the same problem years back, but then i learned how to remap games via the MAME options

**Comment by litaniast** [comment]
How to remap? In mame2003-plus core, it can't be remapped in MAME Options

**Comment by arcadez2003** [comment]
This core had a large overhaul to the input system, if you cant find the remap this game options then
your better posting over at the Rpi forum and someone will likely have the answer i dont use this core so i cant advise ya further.

**Comment by litaniast** [comment]
Ah. Turn on 'Legacy Remapping (restart)' and can be remapped them.

**Comment by mahoneyt944** [comment]
@litaniast please close this issue unless you still need help with this topic.
