### ISSUE TITLE
lrescue bitstream tunes

### ISSUE THREAD

**Issue by mahoneyt944** [libretro/mame2003-plus-libretro#810]
@arcadez2003

I'm just about finished creating new independent drivers for lunar rescue to properly use the current lrescue samples but I hit a snag on the bitstream tunes that it uses injunction with the samples. After a few failed attempts to get sound when you re-enter the ship and at the 1st bonus, I was able to improperly force sound by using ```SN76477_enable_w(board, !(data & 0x08));``` in the handler but this is not correct. Any ideas for how to get the right tone? See the sndhrdw driver in my repository. https://github.com/mahoneyt944/mame2003-plus-libretro/blob/lrescue/src/sndhrdw/8080bw_sndhrdw.c

**Comment by arcadez2003** [comment]
Not really, as unfortunately those samples for Lunar Rescue as you know require speaker.c support
you've just bumped into some incompatible code which cant be backported to MAME78 without
radically overhauling the sound core handling.

And i seriously doubt you'd wanna update every sound core and driver just to support some samples in one game :)

**Comment by mahoneyt944** [comment]
> Not really, as unfortunately those samples for Lunar Rescue as you know require speaker.c support
> you've just bumped into some incompatible code which cant be backported to MAME78 without
> radically overhauling the codebase.
> 
> And i seriously doubt you'd wanna update every sound core and driver just to support some samples in one game :) same kinda deal as to why we cant update all the Sega drivers as we'd
> also have needed to update the input handling and every driver using it which is a total non starter

Well, the code I'm using activates sound at the right places it's just not quiet right. I think if we passed new arguments or wrote a sub function it would be fine. It's close right now. I'll get it

**Comment by mahoneyt944** [comment]
Got trick implemented ;) working. Just need to tweak it a tad.

**Comment by mahoneyt944** [comment]
pull request made.
