### ISSUE TITLE
Can't add UniBios 4.0

### ISSUE THREAD

**Issue by rek607** [libretro/mame2003-plus-libretro#816]
I'm trying to use on mame2003plus the uni-bios_4_0.rom for my neogeo games. I tried adding the bios to every single game and selecting it from options in retroarch, but I can't even select it even after rebooting the Pi 3B I normally use. How can I solve this?

**Comment by mahoneyt944** [comment]
@rek607 I don't play neogeo games but I believe you need to rename the bios file to `neogeo.zip` all lowercase then place it in the same folder you ROMs are in

**Comment by mahoneyt944** [comment]
@rek607 unibiid 4.0 is not currently supported

https://github.com/libretro/mame2003-plus-libretro/blob/master/src/drivers/neogeo.c#L1477

**Comment by mahoneyt944** [comment]
@rek607 supported #873 , merge pending.
