### ISSUE TITLE
F-1 Grand Prix Star 2 isn't playable at all

### ISSUE THREAD

**Issue by litaniast** [libretro/mame2003-plus-libretro#817]
![f1gpstr2-200614-224035](https://user-images.githubusercontent.com/4857928/84594940-4129bf00-ae90-11ea-9727-205bef80aea2.png)
Screenshot says all.

I ran Windows x64 version and Linux armv7-neon version, both occur.

**Comment by arcadez2003** [comment]
Check your romset has the redumped gfx, if that's not the issue i'll look into it

https://github.com/libretro/mame2003-plus-libretro/commit/f77e381a887ade30190d348b3a2e187bd2c57976#diff-8880b04ae5adeba9c7f924d442c770b8

**Comment by litaniast** [comment]
Oops, even the full romsets of mame2003-plus in archive.org, that error occur. but I didn't notice that so I changed **current** MAME romset that game and now it works. 

Thanks.

**Comment by arcadez2003** [comment]
Nae bother, things like this would have flagged up if this core had it's warning screens
switched on by default, but no matter you got it working in the end.
