### ISSUE TITLE
adding berzerkf and berzerkg?

### ISSUE THREAD

**Issue by yepyepyep4711** [libretro/mame2003-plus-libretro#818]
since berzerk is already covered, I thought this might be a low hanging fruit. berzerkg is recognized by mame2010, berzerkf need a more recent mame version.

Seriously, the audio is these versions is funny :)

**Comment by mahoneyt944** [comment]
Berzerk's sound is supported through samples in mame 2003 plus, I think newer versions of mame use a dedicated sound driver to emulate sound more properly without samples. So it wouldn't be as easy as adding the rom to the list.

**Comment by yepyepyep4711** [comment]
ah damn. You're right. Well that's that then. Thanks for answering.
