### ISSUE TITLE
Is there a list of new games added to original mame 2003 ?

### ISSUE THREAD

**Issue by gentlemagic** [libretro/mame2003-plus-libretro#839]
I use mameui 2003 to know which games working on that version and want to know which games added to this plus

**Comment by arcadez2003** [comment]
Seek and always you will find...........

https://github.com/libretro/mame2003-plus-libretro/blob/master/CHANGELOG.md

**Comment by mahoneyt944** [comment]
@gentlemagic please close this issue unless you still need help with this topic.
