### ISSUE TITLE
Travis CI failing checks

### ISSUE THREAD

**Issue by mahoneyt944** [libretro/mame2003-plus-libretro#842]
@markwkidd @twinaphex @arcadez2003 @evilwraith 

Seems there may be an issue here. Under the build history it shows all failures since the PSClassic support was added. Please review.

**Comment by arcadez2003** [comment]
It's @evilwraith you should be tagging as the PS Classic commit was his............

https://github.com/libretro/mame2003-plus-libretro/commit/92c9691e36eb1f2e5ef0e2227ae993aa9fa1d900

**Comment by mahoneyt944** [comment]
@arcadez2003

Yeah I agree, but I wasn't sure if @evilwraith still followed the core and I don't know much about Travis to know if the fix is simple or not. So I was just trying to identify the issue and get input on it.

**Comment by evilwraith** [comment]
I'm not really involved in the project any more but from what I see on that, you shouldn't merge the Travis change. The project moved to internal build pipelines shortly after I moved on.

**Comment by mahoneyt944** [comment]
> I'm not really involved in the project any more but from what I see on that, you shouldn't merge the Travis change. The project moved to internal build pipelines shortly after I moved on.

I can revert the Travis change but what about the Makefile changes? Does that also need reverted?

**Comment by mahoneyt944** [comment]
Reverting Travis fixed the build checks. Merge pending.
