### ISSUE TITLE
Some games have a mirrored display, eg. Operation Thunderbolt

### ISSUE THREAD

**Issue by ghost** [libretro/mame2003-plus-libretro#85]
As the title says, the display is mirrored horizontally. I checked the Dipswitches but there's no option to flip it. I'll just leave this here in case there's a fix.

**Comment by grant2258** [comment]
we know about the mirror issues there will be more than one game it needs fixed and gets us closer to fixing vector games as well

**Comment by markwkidd** [comment]
@KMFDManic reports that Discs of Tron has this problem as well

**Comment by KMFDManic** [comment]
@markwkidd Haha:)  You must have watched my video:)  I find this mirrored display really fun:)

**Comment by grant2258** [comment]
see https://github.com/libretro/mame2003-plus-libretro/issues/81#issuecomment-383092146
