### ISSUE TITLE
Dragon Spirit is flipped vertically for player 2 by default

### ISSUE THREAD

**Issue by Wilstorm** [libretro/mame2003-plus-libretro#86]
Dragon Spirit (dspirit) seems to be flipped for player 2 be default (cocktail mode). Grant added instructions how to flip it correctly through service mode. Would it be beneficial to have it default player 2 as if it was a upright cabinet?

**Comment by grant2258** [comment]
not if someone is using retropie on cocktail setup

**Comment by markwkidd** [comment]
I think it's best to *not* default into cocktail mode whenever possible.
People setting up cocktail cabinets usually have to go into dipswitches in
mame anyway. If we have to be standard, let's be standard on upright mode I
think.

**Comment by markwkidd** [comment]
Actually what if we made cocktail mode a libretro core option.

dthen we could set the default dipswitches as indicated by the core option

**Comment by grant2258** [comment]
its not always dip switches mark it set in the service menu

**Comment by grant2258** [comment]
no problems I opened a thread a while back about the mirrored issue we do know about it but its good to have game to look back on when testing. actually i can probably find them all with grep in the driver directory

**Comment by markwkidd** [comment]
I have no idea yet if it's technically possible but I really love the idea
of `cocktail-display` being a core option.

**Comment by grant2258** [comment]
we are missing rotation code that all that why these games are mirroring like that.

**Comment by Wilstorm** [comment]
> I have no idea yet if it's technically possible but I really love the idea of `cocktail-display` being a core option.

Agreed that would be incredibly useful. One fell swoop to flip them all if you're running a dedicated cab or you can...FLIP...the other way if needed!

**Comment by grant2258** [comment]
well cocktail flips are something different we need to fix up the rotation code so kick displays properly, It means im going to have to learn more retroarch stuff

**Comment by Wilstorm** [comment]
> It means im going to have to learn more retroarch stuff

...stuff...did that have a positive ring in your voice...I think I heard it...yes...I never heard 'stuff' said so positively before...

**Comment by markwkidd** [comment]
Maybe the ring you hear is Dragon Spirit.

**Comment by grant2258** [comment]
did frodo drop a ring?
