### ISSUE TITLE
libretro hack

### ISSUE THREAD

**Issue by markwkidd** [libretro/mame2003-plus-libretro#866]
As far as I can tell, this repository was just part of the collateral damage of a larger hack of the libreto organization. I'm not involved day to day, and this is a much larger issue than our repository, but hopefully more information will become available soon. Keep an eye on the libreto site, social media, and forums in the meantime.

**Comment by mahoneyt944** [comment]
@markwkidd i just posted on the forums about this under the help section. I also have a full copy of mame2003-plus just updated before the loss. If we need it.

**Comment by mahoneyt944** [comment]
@twinaphex

**Comment by mahoneyt944** [comment]
@markwkidd @libretro @twinaphex

Can someone force my repositories master back to the official master here. It's 100% accurate to what we had before loss. Not sure who has rights here to do so. https://github.com/mahoneyt944/mame2003-plus-libretro

**Comment by mahoneyt944** [comment]
@markwkidd can close this now 😎

**Comment by markwkidd** [comment]
Thanks!
