### ISSUE TITLE
Getting screen tearing in the 2003 Plus core

### ISSUE THREAD

**Issue by Cibomatto2002** [libretro/mame2003-plus-libretro#881]
using the Lakka nightly build 9-10-2020

Pie 4

I have tried a few games in MAME 2003 Plus and you can see screen tearing.

Play the game Alpha Mission II / ASO II - Last Guardian you can let the demo run to see it.

Here is a video for you to see.

https://www.youtube.com/watch?v=qEy1_abb6jE&feature=youtu.be

**Comment by mahoneyt944** [comment]
Are you using a bios for neogeo? We now support uni bios 4.0

**Comment by Cibomatto2002** [comment]
Yes using a bios for neogeo games not sure about bios 4.0 can say on Windows 10 this does not happen.

**Comment by mahoneyt944** [comment]
I would give unibios 4.0 a try to see if there's any improvements. It's now free to download from the creators website. Name it "uni-bios_4_0.rom" and place it in you ROMs zip folder or neogeo.zip then select it from retroarches core options. It's listed as "unibios40"

**Comment by Cibomatto2002** [comment]
I got it working all "I did was disabled audio skew.

Thanks for your time and help
