### ISSUE TITLE
Kick is rotated 90 degrees and backwards for players 1 and 2

### ISSUE THREAD

**Issue by Wilstorm** [libretro/mame2003-plus-libretro#89]
Kick (Upright) (kick) plays rotated 90 degrees on it's left and right side for player 1 and 2. Also all the text is backwards on the screen. No dip switches are available to correct the orientation. It's like the original arcade was mounted 90 degree rotated and used a mirror to project the image.

![kick](https://user-images.githubusercontent.com/8192258/38895277-3885dacc-4255-11e8-88fc-4cf36a1bbc2c.jpg)

**Comment by grant2258** [comment]
issue is know no need to open a thread for every game we know mame2003 isint handling rotations properly.  post issues in here https://github.com/libretro/mame2003-plus-libretro/issues/81

**Comment by ZappaUtopia** [comment]
But `kicka `works fine ?

**Comment by grant2258** [comment]
no its ok leave them open keep the issue alive just any new ones post in the main thread so its central for testing

**Comment by Wilstorm** [comment]
Ok will do.

**Comment by grant2258** [comment]
rotation is fixed flipping still needs done

**Comment by grant2258** [comment]
https://github.com/libretro/mame2003-plus-libretro/issues/133
