### ISSUE TITLE
DCS2 dilemma

### ISSUE THREAD

**Issue by arcadez2003** [libretro/mame2003-plus-libretro#892]
Ok on spec i just removed the DCS speedups from the dcs2 sound init to see if they were the reason for the issues that
have been reported with the games in the seattle driver, seeing as the problems with those games on certain platforms
are unrelated to the speedups afterall shall we add em back in.??

Only two drivers midvunit.c and seattle.c actually use the dcs2 sound variant and only the v-unit games will make any use
of the speedups, the dilemma is around the implementation let's delve into the history of the DCS sound and speedups
in this core.

Midway speedups came in three flavours two soundcores and the main CPU, in this core we only had the CPU speedups
as by MAME78 both of the soundcore speedups had  been removed.

So to improve the performance in MK2, MK3, NBA Hangtime, Rampage WT etc etc we added back in the DCS soundcore
speedups, this was easy as the code was already present and correct all we had to do was drop in the speedup handling.

When it comes to dcs2 sound using the older speedup code is more problematic as simply put dcs2 sound did not exist
when the older dcs soundcore supported the speedups.

Pre MAME76 they had dcs_ram sound the speedups are there in the init but disabled.........

void dcs_ram_init(void)
{
	/* find the DCS CPU */
	dcs_cpunum = mame_find_cpu_index("dcsram");

	/* borrow memory for the extra 8k */
	dcs_sram_bank1 = (UINT16 *)(memory_region(REGION_CPU1 + dcs_cpunum) + 0x4000*2);

	/* install the speedup handler */
#if (!DISABLE_DCS_SPEEDUP)
//	dcs_speedup1 = install_mem_write16_handler(dcs_cpunum, ADSP_DATA_ADDR_RANGE(0x04f8, 0x04f8), dcs_speedup1_w);
//	dcs_speedup2 = install_mem_write16_handler(dcs_cpunum, ADSP_DATA_ADDR_RANGE(0x063d, 0x063d), dcs_speedup2_w);
#endif

	/* create the timer */
	dcs.reg_timer = timer_alloc(dcs_irq);
	dcs.sport_timer = timer_alloc(sport0_irq);

	/* reset the system */
	dcs_reset();
}

Post MAME76 dcs_ram is no more replaced with dcs2 and seattle.c is supported 

void dcs2_init(offs_t polling_offset)
{
	UINT8 *romsrc;
	int page, i;

	/* find the DCS CPU */
	dcs_cpunum = mame_find_cpu_index("dcs2");

	/* borrow memory for the extra 8k */
	dcs_sram_bank1 = (UINT16 *)(memory_region(REGION_CPU1 + dcs_cpunum) + 0x8000);
	
	/* borrow memory also for the expanded ROM data and expand it */
	romsrc = memory_region(REGION_CPU1 + dcs_cpunum) + ADSP2100_SIZE;
	dcs_expanded_rom = (UINT16 *)(memory_region(REGION_CPU1 + dcs_cpunum) + 0xc000);
	for (page = 0; page < 8; page++)
		for (i = 0; i < 0x400; i++)
			dcs_expanded_rom[0x400 * page + i] = romsrc[BYTE_XOR_LE(0x1000 * page + i)];
	
	/* create the timer */
	dcs.reg_timer = timer_alloc(dcs_irq);
	dcs.sport_timer = timer_alloc(sport0_irq);

	/* RAM based doesn't do auto-ack, but it has a FIFO */
	dcs.auto_ack = 0;
	dcs.output_full_cb = NULL;
	dcs.input_empty_cb = NULL;
	dcs.fifo_data_r = NULL;
	dcs.fifo_status_r = NULL;
	
	/* install the speedup handler */
	if (polling_offset)
		dcs_polling_base = install_mem_read16_handler(dcs_cpunum, ADSP_DATA_ADDR_RANGE(polling_offset, polling_offset), dcs_polling_r);

	/* reset the system */
	dcs_reset();
}

As you can see no dcs speedups at all but different ones based on polling the ADSP CPU, now in theory you could as i've
done just add the old ones back in and have two sets of speedups, but some questions pop into my head firstly why
were the dcs speedups disabled for these games.?? and why were they then removed.?? and lastly would any harm be
done to the games by adding them back in.??

Also how they set em up for the v-unit games is worth looking at.............

	/* install the speedup handler */
#if (!DISABLE_DCS_SPEEDUP)
//	dcs_speedup1 = install_mem_write16_handler(dcs_cpunum, ADSP_DATA_ADDR_RANGE(0x04f8, 0x04f8), dcs_speedup1_w);
//	dcs_speedup2 = install_mem_write16_handler(dcs_cpunum, ADSP_DATA_ADDR_RANGE(0x063d, 0x063d), dcs_speedup2_w);
#endif

Notice speedups used are 1 and 2 but not 3 and 4 looking at the handlers for these it seems they're using or not using in
this case the wrong ones anyway............

static WRITE16_HANDLER( dcs_speedup1_w )
{
/*
	MK3:     trigger = $04F8 = 2, PC = $00FD, SKIPTO = $0128
	UMK3:    trigger = $04F8 = 2, PC = $00FD, SKIPTO = $0128
	OPENICE: trigger = $04F8 = 2, PC = $00FD, SKIPTO = $0128
	WWFMANIA:trigger = $04F8 = 2, PC = $00FD, SKIPTO = $0128
	NBAHANGT:trigger = $04F8 = 2, PC = $00FD, SKIPTO = $0128
	NBAMAXHT:trigger = $04F8 = 2, PC = $00FD, SKIPTO = $0128
	RMPGWT:  trigger = $04F8 = 2, PC = $00FD, SKIPTO = $0128
*/

static WRITE16_HANDLER( dcs_speedup2_w )
{
/*
	MK2:     trigger = $063D = 2, PC = $00F6, SKIPTO = $0121
	REVX:    trigger = $063D = 2, PC = $00F6, SKIPTO = $0121
	KINST:   trigger = $063D = 2, PC = $00F6, SKIPTO = $0121
*/

static WRITE16_HANDLER( dcs_speedup3_w )
{
/*
	CRUSNUSA: trigger = $063A = 2, PC = $00E1, SKIPTO = $010C
*/

static WRITE16_HANDLER( dcs_speedup4_w )
{
/*
	CRUSNWLD: trigger = $0641 = 2, PC = $00DA, SKIPTO = $0105
	OFFROADC: trigger = $0641 = 2, PC = $00DA, SKIPTO = $0105
*/

Looks like we need speedups 3 and 4 for the midway v-unit games, so what to do add em back into the dcs2 init.?? or just
leave em disabled.?? certainly only a handful of games use dcs2 sound and of those even less would benefit from
speedups which might be no good anyway, obviously someone testing Cruis'n USA, Crusi'n World and War Gods to
see if they get any kind of boost in the performance dept while making sure there is no game breakage would be handy.

**Comment by mahoneyt944** [comment]
I would just put them back in, they can be disabled by the user anyhow if there is any issues.
