### ISSUE TITLE
[Switch] Slow loading when cheat.dat is in system folder

### ISSUE THREAD

**Issue by RetroMarioBros** [libretro/mame2003-plus-libretro#894]
Edited: updated issue with new findings.

Original:
Mame2003-plus core doesn´t work correctly on Switch
only a black screen appears and a console restart is required
no game works,
Previously, it worked correctly.

**Comment by arcadez2003** [comment]
Two questions does MAME2003 work.?? and when did you last use MAME2003+ and it was working.??

**Comment by RetroMarioBros** [comment]
does MAME2003 work.? 
Yes , Mame 2003 works
when did you last use MAME2003+ and it was working.??
I don't know exactly, but in stable 1.9.0 the core works fine

**Comment by mahoneyt944** [comment]
I don't think there's been any updates to plus that wasn't also done to mame2003. Can you get a log and post it here?

**Comment by RetroMarioBros** [comment]
I think here is the issue: I think here is the issue: it need -fcommon for it build the core correcty on switch for gcc10

Add -fcommon to libnx build for gcc10 compatibility.(Makefile)

**Comment by mahoneyt944** [comment]
@RetroMarioBros are you positive the current mame2003 is working because the makefile in 2003 is identical to the one in plus regarding switch?

**Comment by RetroMarioBros** [comment]
@mahoneyt944 I just tried the 2003 core and it also goes black.
So fcommon must be in both makefiles

**Comment by mahoneyt944** [comment]
Ok let's test it out. I'll add it to plus

**Comment by RetroMarioBros** [comment]
@mahoneyt944 2000 also has problems

**Comment by mahoneyt944** [comment]
I just added fcommon to CFLAGS for switch. Once we confirm that works I'll port it to other mames. Let me know when you test the nightly. You'll need to give it time to build the new change.

**Comment by RetroMarioBros** [comment]
Nothing a Black screen again!
I send you retroarch logs

**Comment by mahoneyt944** [comment]
Let's check these out.
```
[INFO] [Environ]: SYSTEM_DIRECTORY: "/retroarch/cores/system".
[INFO] [Environ]: GET_SAVE_DIRECTORY.
[libretro INFO] [MAME 2003+] Check for trailing slash in path: /
[libretro INFO] [MAME 2003+] Removed a trailing slash in path: 
[libretro INFO] [MAME 2003+] Check for trailing slash in path: /retroarch/cores/system
[libretro INFO] [MAME 2003+] Trailing slash removal was not necessary for path given.
[libretro INFO] [MAME 2003+] Check for trailing slash in path: /retroarch/cores/savefiles
[libretro INFO] [MAME 2003+] Trailing slash removal was not necessary for path given.
[libretro INFO] [MAME 2003+] content path: 
[libretro INFO] [MAME 2003+]  system path: /retroarch/cores/system
[libretro INFO] [MAME 2003+]    save path: /retroarch/cores/savefiles
```
It looks like your content path is at root and our trailing slash removal is effectively deleting the file path since it's only a slash to begin with. I can probably add another condition to not remove the trailing slash if the path is only a slash.

**Comment by RetroMarioBros** [comment]
I am attaching a log of a working version of mame 2003 with the same game to compare

[retroarch__2020_10_03__23_06_29.log](https://github.com/libretro/mame2003-plus-libretro/files/5322309/retroarch__2020_10_03__23_06_29.log)
[retroarch__2020_10_03__23_06_23.log](https://github.com/libretro/mame2003-plus-libretro/files/5322310/retroarch__2020_10_03__23_06_23.log)

**Comment by mahoneyt944** [comment]
well your working versions and non working versions all trim the slash in the content path and being as these additions were not done in mame2000 its probably something else.

update retroarch and mame2003-plus to the newest version then log a game but enabled debug so we can really see whats happening.

**Comment by mahoneyt944** [comment]
try backing up your .cfg files somewhere safe then delete the default.cfg and .cfg for the game your trying and try to load it again. you may be using a version of plus that uses old cfgs

**Comment by RetroMarioBros** [comment]
nothing, the games do not load, and it is necessary to restart

**Comment by mahoneyt944** [comment]
alright, well enable debug for your log and post that with the lastest plus version

**Comment by RetroMarioBros** [comment]
[retroarch__2020_10_04__00_18_44.log](https://github.com/libretro/mame2003-plus-libretro/files/5322370/retroarch__2020_10_04__00_18_44.log)
[retroarch__2020_10_04__00_18_58.log](https://github.com/libretro/mame2003-plus-libretro/files/5322371/retroarch__2020_10_04__00_18_58.log)

**Comment by mahoneyt944** [comment]
ok let me do some tests and I see if I can get a solution

**Comment by mahoneyt944** [comment]
Ok so I tried something out. I changed it to not remove a slash if the path is only a slash. Let the nightly not catch up and let me know.

**Comment by RetroMarioBros** [comment]
black screen again ...😢😢😢

**Comment by mahoneyt944** [comment]
Well there's definitely something up with build. We'll have to see what we need in the makefile.

**Comment by mahoneyt944** [comment]
Do you have the debug log of the lastest build?

**Comment by RetroMarioBros** [comment]
no, the console freezes, I don't have access to the retroarch menu

**Comment by RetroMarioBros** [comment]
[retroarch__2020_10_04__23_56_19.log](https://github.com/libretro/mame2003-plus-libretro/files/5324471/retroarch__2020_10_04__23_56_19.log)
[Uploading retroarch__2020_10_04__23_56_25.log…]()

**Comment by rsn8887** [comment]
Please try -fcommon again @mahoneyt944 but add it two lines higher so it also becomes added to cxxflags not only to cflags. -fcommon is needed for libnx and Vita now in cflags and cxxflags in ALL cores.

**Comment by mahoneyt944** [comment]
@rsn8887 should I be writing out fcommon twice for libnx and vita? In cxxflags and cflags? Or just in cxxflags?

**Comment by rsn8887** [comment]
You should write it in cflafs BEFORE cxxflags is defjned. That way it gets pulled into cxxflags with the rest of cflags.

**Comment by mahoneyt944** [comment]
@RetroMarioBros ok. We finally got fcommon were is should be thanks to @rsn8887. Please let's the nightly bot catch up and test this change.

**Comment by RetroMarioBros** [comment]
perfect, we will wait to see the build is built, if it works this should be added to the other mames cores
@mahoneyt944 
Thanks @rsn8887

**Comment by mahoneyt944** [comment]
>if it works this should be added to the other mames cores

Already added to mame2003 as well and a pull request was made for mame2000. I don't have access in 2000 though so it must be merged by whoever does.

**Comment by RetroMarioBros** [comment]
Great! Hopefully that's the issue and fixes the eternal black screen .... fingers crossing

**Comment by RetroMarioBros** [comment]
The same in last build , black screen

**Comment by RetroMarioBros** [comment]
Mame 2003 works now , i try games : donkey kong , 3 wonders , 1941,altered best @mahoneyt944

**Comment by mahoneyt944** [comment]
@RetroMarioBros so mame2003 works but not plus? Ok. I'll see what's different

**Comment by RetroMarioBros** [comment]
Yes, the games work ... I have noticed that the same game in mame 2003 takes a few seconds longer to load than in mame 2000 (for example 1941 )
Mame 2003 + doesnt work 😢
It seems that the core does not completely freeze the console, but rather slows it down when loading the game ... in such a way that it does not start at all (and it is necessary to restart, to be able to use it again)

**Comment by mahoneyt944** [comment]
@RetroMarioBros ok so are you using mame2000, mame2003, and mame2003-plus all the latest nightly builds? And with these

Mame2000 working
Mame 2003 working but slow
Mame2003-plus working but slow

Did I get that right?

**Comment by RetroMarioBros** [comment]
[retroarch__2020_10_07__01_11_01.log](https://github.com/libretro/mame2003-plus-libretro/files/5337375/retroarch__2020_10_07__01_11_01.log)
[retroarch__2020_10_07__01_11_10.log](https://github.com/libretro/mame2003-plus-libretro/files/5337376/retroarch__2020_10_07__01_11_10.log)
@mahoneyt944

**Comment by rsn8887** [comment]
I just tried latest buildbot core builds from Oct. 7 and I get the following.

Mame2003 plus:
- Mario Bros: ~36 seconds loading time
- Cyberbots (a much bigger game than Mario): ~22 seconds loading time

Mame 2003:
- Mario Bros: ~36 seconds loading time
- Cyberbots: ~28 seconds loading time

I don't see the 5 minutes loading time. Maybe some recent commit made it faster, or it was grossly exaggerated before.

**Comment by rsn8887** [comment]
We did some more tests. It seems to be an issue due to either Retroarch or the Switch toolchain upgrade.

The following tests led me to that conclusion:

- I build mame2003 plus using the code July 6, statically linked to latest Retroarch code, and it was still loading slow.

- @angel_hp tested the buildbot build from August 22 it was the last one that loaded fast. That build was from the buildbot, built using gcc 8-based toolchain and, of course, statically linking the Retroarch code from that day as well.

I tried linking latest mame2003plus with Retroarch code from August 21 to double check whether some change to Retroarch caused the slowness. However, when I do that, I get a core build that crashes on starting a game.

**Comment by rsn8887** [comment]
It seems to be toolchain related, because I built the core from July 6 with Retroarch from Aug. 21 and it still loads slow.

**Comment by mahoneyt944** [comment]
Yeah, I've been testing the core on Android and it super fast. No issues or delays. Rpi it's completely normal as well. It's definitely a switch issue with the build..

**Comment by rsn8887** [comment]
I tried using -O2 instead of -O3 on Switch, still loads slow.

**Comment by mahoneyt944** [comment]
Here's the main resync https://github.com/libretro/mame2003-plus-libretro/commit/f160a1dac905f079bc007e6e8f056b28e3cb7c24

Lots of audio changes.

**Comment by mahoneyt944** [comment]
Updated this issue again.

**Comment by mahoneyt944** [comment]
@RetroMarioBros Is this still an issue after updating retroarch and this core?

**Comment by RetroMarioBros** [comment]
Yes , when cheat.dat is in mame2003 plus system folder is very slow
@mahoneyt944

**Comment by RetroMarioBros** [comment]
Yes , when cheat.dat is in mame2003 plus system folder is very slow
@mahoneyt944

**Comment by KungFuJoe23** [comment]
Don't have much to add other than I'm experiencing the same issues.

Mame 2003 Plus and Mame 2003 both just hang with a black screen if either cheat.dat is present (requires hard reboot of switch).

Without cheat.dat, they both work, but 2003 Plus appears to load a few seconds slower than 2003.

**Comment by KungFuJoe23** [comment]
Just tried using the mame2003+ core from the 1.7.8 build and everything is working again. ROMs load faster and cheats are working.

Something definitely changed from around 1.7.8 and 1.8+.

**Comment by mahoneyt944** [comment]
I think there was a gcc change over around then. The cores, I believe, are larger in general now too. Maybe @m4xw might be able to weigh in on this though.

**Comment by ckeisc** [comment]
I am seeing a very similar slow down of rom loading in MAME 2003 Plus core on New Nintendo 3DS. In 1.9.0 release, no slow down. Puyo Puyo loads in ~30 seconds. In 1.9.1 till the latest 1.9.3, it takes 4 minutes and 30 seconds to load the same rom (~500kb zipped). The app is completely non responsive during the 4 and half minutes. But once the rom loads, game seems to run just fine, no further slow down.

I am not seeing any cheat.dat in my system folder so not sure if it has anything to do with that file.

**Comment by mahoneyt944** [comment]
@twinaphex any specific updates effecting 3ds?

**Comment by mahoneyt944** [comment]
This issue seems to have parallel with #1054, it's recommended to disable the autosave hiscore core option to improve load times. Please open a new issue if this fix does not improve the load time. thanks!

**Comment by mahoneyt944** [comment]
3ds and switch should be fixed now with or without using cheat.dat. please use the latest commit at the time of this post.

**Comment by KungFuJoe23** [comment]
Posting to confirm that the last nightly fixes the cheat.dat issue. Tested with mame2003-plus.

Thank you!

**Comment by mahoneyt944** [comment]
Yes. cheat.dat is compressed on first load to create cheat.rzip..... Delete both cheat.dat and cheat.rzip if you want a new database to be used instead.

Glad it's working for you now 👍
