### ISSUE TITLE
D.D. Crew boots but only shows random color patterns

### ISSUE THREAD

**Issue by Wilstorm** [libretro/mame2003-plus-libretro#90]
D.D. Crew (ddcrew) boots but only shows weird color patterns. No input or coins work.

**Comment by grant2258** [comment]
dd crew is broke on mame078 as well it does need a driver fix

**Comment by arcadez** [comment]
It needs an updated M68k CPU plus FD1094 decryption as well, long story short a shitload of graft ;)

**Comment by grant2258** [comment]
m68k is updated

**Comment by arcadez** [comment]
What MAME build did you take it from..?? it would need to support the decryption routines
these Sega games use.

**Comment by grant2258** [comment]
i updated the core not the interface

**Comment by arcadez** [comment]
Yeah im familiar with this as i've already done it all for another core, the biggest hurdle apart
from all the new drivers and related machine and video code would be the input handling
for the segaorun, segahang, sega x and y boards which wont be compatable with this core
plus we would need to update a couple of soundcores also.

It would be possible however to bypass the need for a CPU update by using the decrypted
versions which MAME now supports making the Sega16A Sega16B drivers a viable target 
but as you say it's alotta hard graft and im not up for it personally ;)

**Comment by arcadez** [comment]
Anyway i rabbit on as usual when all i had to say is DD Crew dont work in this core 
might as well close this now
