### ISSUE TITLE
Double Dragon (attract mode) Sprite issue

### ISSUE THREAD

**Issue by Riddler1** [libretro/mame2003-plus-libretro#903]
Rom = Ddragon.zip
Retroarch 1.8.8
Mame 2003-plus (f0ea72e)

The cutscene sprite for Williams vanishes after he punches Spike (supposed to be Marian) and the kidnapped Marian sprite is replaced with  Spike (Jimmy).

As they walk all off screen to the right, the last few frames shows Marian sprite being carried away. 

Issue only occurs in attract sequence cutscene, not when player starts game.

https://youtu.be/KjdDVS8GbyE

**Comment by Riddler1** [comment]
Notice at the last few frames before they leave the screen, the sprite changes back to normal....

![Screenshot_20201012-110711_Video Player](https://user-images.githubusercontent.com/43607359/95737576-cfb41e80-0c7f-11eb-9f72-0000263251d0.jpg)
![Screenshot_20201012-110645_Video Player](https://user-images.githubusercontent.com/43607359/95737581-d0e54b80-0c7f-11eb-9bb2-62eb5f0478fe.jpg)
![Screenshot_20201012-110613_Video Player](https://user-images.githubusercontent.com/43607359/95737583-d17de200-0c7f-11eb-8af1-20ebe8a57855.jpg)

**Comment by Riddler1** [comment]
Notice at the last few frames before they leave the screen, the sprite changes back to normal....

![Screenshot_20201012-110711_Video Player](https://user-images.githubusercontent.com/43607359/95737671-f96d4580-0c7f-11eb-896b-5bc24fc62f01.jpg)
![Screenshot_20201012-110645_Video Player](https://user-images.githubusercontent.com/43607359/95737673-fa05dc00-0c7f-11eb-95f1-3e832f48348b.jpg)
![Screenshot_20201012-110613_Video Player](https://user-images.githubusercontent.com/43607359/95737677-fa9e7280-0c7f-11eb-8d8f-3aaaf0b8f697.jpg)

**Comment by Riddler1** [comment]
Notice at the last few frames before they leave the screen, the sprite changes back to normal....

![Screenshot_20201012-110613_Video Player](https://user-images.githubusercontent.com/43607359/95737870-418c6800-0c80-11eb-9399-1080f51a46bd.jpg)
![Screenshot_20201012-110645_Video Player](https://user-images.githubusercontent.com/43607359/95737891-494c0c80-0c80-11eb-9665-8884c6dc9d00.jpg)
![Screenshot_20201012-110711_Video Player](https://user-images.githubusercontent.com/43607359/95737911-4fda8400-0c80-11eb-954b-03aabff413b0.jpg)

**Comment by arcadez2003** [comment]
A minor issue maybe there is a fix from later MAME.?? i'll look into it sometime, more serious of course is the crash which
can occur at the very end of the game when the 2 players fight it out for the gal, i've been looking into this over the past
few days and i think i've come up with a good solution.

**Comment by arcadez2003** [comment]
@Riddler1 i've ported across a fix via @grant2258 for the problems in Double Dragon you reported.........

https://github.com/grant2258/blaster-barcade/commit/84d597223165700d3beb2f653c4bbfb0ec494875

**Comment by Riddler1** [comment]
Cool thanks. updated and tested. Works great. 👍
