### ISSUE TITLE
in retroarch mac os, remap mame controller keys so slow.

### ISSUE THREAD

**Issue by lencil** [libretro/mame2003-plus-libretro#904]
1.macOS Catalina, mbp 16 inch 5600M
2.RetroArch 1.9.0 and nightly 2020/10/16
3.video driver "gl", ui driver "ozone"
4.load any mame-2003+ game
5.press "tab", open mame menu
6.change "input keys"
7.when reset keys, so slow to waiting.

issue only in mac, in switch and windows, no issue.

**Comment by mahoneyt944** [comment]
Is this in the black mame menu or in the retroarch remap menu?

**Comment by lencil** [comment]
> Is this in the black mame menu or in the retroarch remap menu?

not in retroarch remap.
in mame black native menu. [tab]

**Comment by mahoneyt944** [comment]
Did you try deleting your default.cfg in the cfg folder and letting the core create a new one? When did this issue first happen?

**Comment by lencil** [comment]
> Did you try deleting your default.cfg in the cfg folder and letting the core create a new one? When did this issue first happen?

when update from 1.8.9 to 1.9.0, I found this issue.
I'll have a try deleting default.cfg as you mentioned above tonight.

**Comment by mahoneyt944** [comment]
If it started happening after a retroarch update the issue might be within retroarch and not the core itself.

**Comment by lencil** [comment]
reset config file, not work, so slow set "Input (this game)", resetting a key cost about 6 ~ 10 seconds.

**Comment by lencil** [comment]
> > Did you try deleting your default.cfg in the cfg folder and letting the core create a new one? When did this issue first happen?
> 
> when update from 1.8.9 to 1.9.0, I found this issue.
> I'll have a try deleting default.cfg as you mentioned above tonight.

also updated cores with retroarch.

**Comment by mahoneyt944** [comment]
Can you post a video?

**Comment by mahoneyt944** [comment]
@lencil please download the latest nightly and see if you still have an issue.

**Comment by lencil** [comment]
> @lencil please download the latest nightly and see if you still have an issue. If so try to get a video of the issue. Let me know

still the issue

**Comment by lencil** [comment]
here's the video
[mame2003plus.zip](https://github.com/libretro/mame2003-plus-libretro/files/5397466/mame2003plus.zip)

**Comment by mahoneyt944** [comment]
@lencil ok a new commit was made. Please update again and test.

**Comment by lencil** [comment]
nightly build is OK
