### ISSUE TITLE
Pig Newton has no sound - sound works in MAME 0.106

### ISSUE THREAD

**Issue by Wilstorm** [libretro/mame2003-plus-libretro#91]
Pig Newton (pignewt) crashes to a black screen on boot. No input or coins work.

**Comment by arcadez** [comment]
Thanks for the bug report although keep in mind should this game be fixed it wont
have any sound as was the case in MAME78

regards

**Comment by Wilstorm** [comment]
That's alright I don't imagine it's very high on anyone's play list. Should I just close it? I was basically listing bugs as I worked through my list. With all the updates I ported several games back over from AdvMAME and noticed it crashed with no sound it really would be a stale game.

**Comment by SapphireTactician** [comment]
Can confirm. I noticed that if ytou wait long enough though, the screen fills horizontally with blue dots for some reason. So it's not totally frozen per se, but yeah, it's not responsive to anything and never makes it to the title screen.

Running RA with the verbose option doesn't display anything remarkable in my terminal output aside from this which caught my attention:

```
cpu.u25      NOT FOUND (NO GOOD DUMP KNOWN)
WARNING: the game might not run correctly.
```

**Comment by grant2258** [comment]
this game is fixable its the same deal as as the last games that where fixed

**Comment by SapphireTactician** [comment]
@Wilstorm Keep in mind that MAME 2003 Plus is compatible with games from the MAME 2010 Reference Set. As a workaround, use the MAME 2010 version. However, it lacks sound and has a warning about such.

**Comment by grant2258** [comment]
its the nodump bad dump scenario again the reason i havent fixed it like the lastest mame does it there is a big retropie thread about this issue on some other games and i dont want a repeat of that

**Comment by SapphireTactician** [comment]
I understand, I was just telling OP what they could do in the meanwhile.

**Comment by grant2258** [comment]
ah no problems :)

**Comment by grant2258** [comment]
@Wilstorm  i dont mind anything about the issue just trying to figure out if there is a new option we can use or add to to make it clearer other than bad baddump since we are using tags. if someone else sees that they might think it wrong aswell is just a general comment.

**Comment by Wilstorm** [comment]
Guys I am ok with closing this issue. I know there's so many other games that could use some work that are much funner and more popular to play. An honorable mention would have been more practical then opening an issue as there's many games that don't run proper and not every one needs an open issue I would guess. If someone is really jonesing for a fix AdvMAME runs it perfect *with* full audio. I just played it last night for a while and I am good for a while. :)

**Comment by markwkidd** [comment]
I wouldn't mind keeping the issue open for now to revisit in a future round of work.

**Comment by markwkidd** [comment]
I have updated the title to reflect the current status of this issue even though it's still not an active one.

**Comment by arcadez** [comment]
Ok i looked at this the other day Pig Newton would require a sound core which was coded
new for MAME106 and as such it's in no way compatable with this core so it's a no go.
