### ISSUE TITLE
Konami speech driver sound increase UPD7759

### ISSUE THREAD

**Issue by Riddler1** [libretro/mame2003-plus-libretro#913]
I'd like to increase the volume for the uPD7759. has the volume slider menu been disabled in this core?

![20201101_195357](https://user-images.githubusercontent.com/43607359/97812829-193eca80-1c7c-11eb-86bd-df2010f4d976.jpg)

...if it is not enabled can you merge this below change for me so i can test it? 

https://github.com/Riddler1/mame2003-plus-libretro/commit/3ba83019fbe122d96300553be6a565052a3f69c2

**Comment by mahoneyt944** [comment]
Tmnt has a few different sounds going to the mixer. So we'll have to be sure it doesn't start clipping by turning it up. I'll merge the change but I'll need you to test and confirm there's no clipping.

**Comment by Riddler1** [comment]
ok i'll test, thanks

**Comment by arcadez2003** [comment]
Tmnt just uses the UPD7759 for the intro song right.??

**Comment by mahoneyt944** [comment]
@arcadez2003 I think I read that somewhere yeah

**Comment by mahoneyt944** [comment]
https://github.com/libretro/mame2003-plus-libretro/blob/cb95f909e3fb685a24295bef58d5ef6c1e1c9469/src/drivers/tmnt.c#L304-L316

**Comment by mahoneyt944** [comment]
It does raise the speech volume 100 might be a little too loud though coming from 60. Maybe somewhere between there

**Comment by Riddler1** [comment]
the UPD7759 does not affect the intro music, song speech or insert credit voice

It affects the voice volume when you see character talk in the cutscenes with a speech bubble and Donatello & Raphael attack sounds.


![Screenshot_20201102-113304_Video Player](https://user-images.githubusercontent.com/43607359/97864110-ffdf6200-1cff-11eb-8900-07c531e2e306.jpg)



Increasing to 100 makes it much better to hear when the character talks BUT.... 

Donatello & Raphael attack sounds are going to be higher than Leo & Michaelangelo!

Leonardo & Michaelangelo attack sounds are set to use the YM2151

I see why it was set to 60 now.... to balance out the characher attack sounds.

Maybe revert the change for now.....

**Comment by mahoneyt944** [comment]
Good. This isn't related the voice volume change, but I think maybe the intro song should be louder too to match the game volume. It seems very quiet to me then the gameplay kicks in pretty loud. Should probably be more balanced.

**Comment by Riddler1** [comment]
ah yes, i didn't really notice till you point it out. 

So the Theme tune music seems to be controlled by the "Samples" interface. It is set to "100" already so can it go beyond that?

otherwise lowering the stage music will mean taking down both YM2151 channels to 60% which should sound a lot more even.

The other two sound channels, "K007232" are for drums and beat so can be left at 20%

**Comment by mahoneyt944** [comment]
When I get a chance I'll tweak these volumes around to get a good even sound and let you test. Shouldn't be too hard.

**Comment by arcadez2003** [comment]
Well preferably users would adjust the slider sound levels to their own liking, rather than changing the sound in the drivers
everyone has a different setup with regards to what TV, device or frontend they're using if we alter the sound in tmnt to
please one we might then upset 100's more :) 

@Riddler1 head over to the Rpi forum and ask about the slider controls and how to access em in MAME2003+ im sure
someone will then chime in with an answer.

**Comment by Riddler1** [comment]
yep, that would be the ideal solution, hopefully the slider control can be made accessible.
👍

**Comment by arcadez2003** [comment]
Ah right i knew this core was halfway through a huge update to the inputs, i never knew they actually removed
the slider controls which is a bit daft oh well im sure they'll be fixed again some day.

**Comment by mahoneyt944** [comment]
I'm guessing ra was going to pickup these settings but never did when they got removed from the ui? Not sure. The functions are blanked. I think the best we can do right now is tweak the levels to a happy medium. I have a few different audio setups I can test sound levels on to get a decent level preset and I always back check levels against a variety of other games to see that it comes in on a similar level. That way when users like me use bridged channel / amplifier setups the volume is correct. These setups are the most prone to clipping due to combining stereo wave lengths to a single speaker. So volume level issues are more apparent. I find when this setup comes out sounding right, more typical setups sound even better and will be less likely to have clipping issues. Plus, of course, I always welcome testers to get a better overall confirmation.

**Comment by Riddler1** [comment]
@mahoneyt944 Great, i'll be happy to test what you come up with.

**Comment by mahoneyt944** [comment]
Try the new level out just committed

**Comment by Riddler1** [comment]
Good i think, returning the speech to the original level and bringing the music down does keeps the changes made but in reverse. 👏

and not to get too geeky about it but i used a decibel meter to check the difference between the theme intro music and when stage1 music kicks in. Looks quite even but the stage1 music is just teeny tiny bit louder but still a good change.

![20201107_140142](https://user-images.githubusercontent.com/43607359/98443386-d90b9c00-2102-11eb-89f9-f55cd3144dd6.jpg)

**Comment by mahoneyt944** [comment]
Yeah the level sound seems to be close but there's a few sound effects that are louder. Leo's sword clank, kicking the sewer lid in the air, windows breaking. Not sure which sound controls those yet

**Comment by Riddler1** [comment]
Well played!

I made a list of the sound effects that are used by which module, which may come in handy....

Leo sword clank = YM2151
kick sewer lid = YM2152
windows breaking = YM2151		
bad guys jump out of water = YM2151
Enemy Exploding = YM2151
Turtle hits metal object (Sign post/traffic cone/TNT barrell/Baxter Stockman boss) = YM2151
Dymanite Exploding = YM2151
Machine gun (foot soldier/Rocksteady) = YM2151
Bebop & Rocksteady clash heads = YM2151
Sewer rockets launch = YM2151
Sewer spike gate falling = YM2151
Bebop Jumping on Car (Stage 2) = YM2151
Bebop Ray Gun = YM2151
Shell Shock Dizzy sound = YM2151
Fire Hydrant break and water squirt = YM2151		
Falling in a manhole = YM2151
collecting a pizza = YM2151
Bill Board falling sound (stage 2) = YM2151
Turlte lands on water (sewer) = YM2151
Mice squeeking (sewer) = YM2151 
Mousers breaking wall = YM2151
Car engine (Highway stage) = YM2151
Turtke Van engine (Highway stage) = YM2151
Car Horn (Foot soldiers in car)  
Motorbikes engine (foot soldier on motorbikes) = YM2151

Enemy getting hit = UPD7759
Enemy being thrown against wall = UPD7759
Turtke gets hit with Knife from White footsoldier = UPD7759	
Girl on scateboard Screamin = UPD7759
Pizza Time! pickup = UPD7759
"Hurry!" bomb hit sound = UPD7759

Boss takes a hit = 7232
Boss Death Cry = 7232
Turtle gets punched = 7232

**Comment by mahoneyt944** [comment]
If those are accurate it looks like ym2151 controls most sound clips so it probably good where it is for that. 7232 might be a little low but that was also the drum beat I believe?  7759 seems ok, maybe a pinch low but we start to get into the subjective range of what sounds right. I may tweak it more later but it's pretty good right now.
