### ISSUE TITLE
Support for Botanic english version

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/mame2003-plus-libretro#917]
http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=botanic&search_id=

current `botanic` romset has French text.

**Comment by mahoneyt944** [comment]
Would be easy enough to add, but it means renaming roms
https://github.com/libretro/mame2015-libretro/commit/846719469b6226d45a6baa9b922b8254452ac8ce

**Comment by mahoneyt944** [comment]
There's also this
https://github.com/libretro/mame2015-libretro/commit/72be21f816be1ec778cf56b40eccc52e72784327

**Comment by arcadez2003** [comment]
Well when i added support for Botanic to this core a while back i played a few levels and it never crashed
maybe i was lucky.?? or only the English version is affected by this.??

Either way it's easy enough to update the romsets and fixup the inputs should anyone feel like it ;)

**Comment by mahoneyt944** [comment]
The fix was only done to the English version, something to do with the coin slots / protection. I suspect the ports are guess work on this one, which was probably causing an issue.

**Comment by mahoneyt944** [comment]
I started a branch for this, almost ready. There's a few issues I see.

Our inputs are 8way, current mame 4way.

The english inputs are messy in current mame ( botanici ). Even noted this way. It's first copied from bagman, then modified to botanicf, then modified to botanici. The dip switches get messy and are likely wrong in current mame. So we need to sort these a little before committing.

**Comment by mahoneyt944** [comment]
Well it's working, but it's being drawn upside down 😂

**Comment by mahoneyt944** [comment]
This should do it.
https://github.com/libretro/mame2003-plus-libretro/commit/0a7053db5b0695a66211e79e4b44595c6aef0ad2
