### ISSUE TITLE
berabohm - possible improvement

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/mame2003-plus-libretro#921]
![berabohm-201115-102401](https://user-images.githubusercontent.com/41223243/99161412-07096580-272d-11eb-834e-dfbf3913183c.png)
Note: fixed as of latest build

0.89: Nicola Salmoria fixed inputs and DAC sounds in Beraboh Man, two sounds at the same time were causing severe slowdowns. Added 'Invulnerability' and 5x 'Unknown' dipswitches.

**Comment by arcadez2003** [comment]
I booted this game up earlier using my xbox MAME72 core  as i was testing Botanic sound anyway, and the game was 
fine graphically so i dunno if this is one of those libretro endian issues.?? someone would have to try out this game
to see if they're getting the same problems.

As for the DAC and inputs fixes it's noted

Regards

**Comment by mahoneyt944** [comment]
@arnoldsecret see if this does anything. Ported from grant. https://github.com/libretro/mame2003-plus-libretro/commit/79317f2ed3da87fcd805f18c7b26a4485da93726

**Comment by arnoldsecret** [comment]
still hasn't picked up by the buildbot yet, currently on commit https://github.com/libretro/mame2003-plus-libretro/commit/0353570ddd2e6d9d32bffc89278e1b37f5d61f8e

**Comment by mahoneyt944** [comment]
The buildbot was getting overhauled. Check the libretro page for updates.

**Comment by arnoldsecret** [comment]
closed for the first bit, second one is up to arcadez2003.

**Comment by arcadez2003** [comment]
Well @arnoldsecret it doesn't have to be up to me, i mean you've contributed codewise to this core im confident
you could tackle it yourself, instead of being a backseat driver jump behind the wheel :)
