### ISSUE TITLE
Chase Bombers

### ISSUE THREAD

**Issue by arcadez2003** [libretro/mame2003-plus-libretro#923]
Do me a wee favour guys will one of ya's just boot up Chase Bombers and lemmie know if it's working
ok in this core, i'd expect it to be a little slow on certain devices right enough but apart from that
all being well it should be fully playable.

Regards

**Comment by mahoneyt944** [comment]
I can test it on Android when the nightly bot catches up.  I noticed this game uses a two gear shifter like pole position. Maybe we can add the the same gear notification through the ui for this game too.
https://github.com/libretro/mame2003-plus-libretro/blob/b31b606e03c3aa3405d1a798add74d57f62bd434/src/vidhrdw/polepos_vidhrdw.c#L534-L541

**Comment by mahoneyt944** [comment]
Also I noticed later mames with this extra rom hooked up. Not sure when it was added?
https://github.com/mamedev/mame/blob/7b657d9b61f204d27db43d9f9c41fc58a6f6a683/src/mame/drivers/undrfire.cpp#L808

**Comment by mahoneyt944** [comment]
Seems like it plays pretty well. Some graphical glitches when going over the bridge I noticed. Might be due to the missing eeprom? Otherwise plays well on Android.

![cbombers-201118-080137](https://user-images.githubusercontent.com/49591133/99534086-df0c4300-2974-11eb-844a-8fadb6612171.png)
![cbombers-201118-080202](https://user-images.githubusercontent.com/49591133/99534087-df0c4300-2974-11eb-99a0-b42c4e1f53b0.png)

**Comment by mahoneyt944** [comment]
Is the screen position/ size off? There's black a strip at the top of the screen shots. Not sure if that's normal or not.

**Comment by arcadez2003** [comment]
"I can test it on Android when the nightly bot catches up. I noticed this game uses a two gear shifter like pole position. Maybe we can add the the same gear notification through the ui for this game too?"

It's possible i suppose

"Also I noticed later mames with this extra rom hooked up."

Just an eeprom with auto configs by looks, certainly that code does not look compatible with MAME78 
it could be reworked right enough, but not something i'd wanna bother with TBH.

"Is the screen position/ size off? There's a black strip at the top of the screen shots. Not sure if that's normal or not."

The game uses the exact same screen sizing as Under Fire, i'll check though to see if that was changed in later builds
certainly the game does have an imperfect graphics flag in current MAME, the only gfx fix i could find after
the game was added to MAME is this..............

0.156: Fixed TC0480SCP text layer colors (see Chase Bombers). Improved documentation (TC0620SCC is the 6bpp tilemap chip) [Alex Jackson].

However that might be to sort the prototype japan set which did have some issues when it was supported..........

0.152: Unigame added clone Chase Bombers (Japan Prototype). Angelo Salese fixed ADC irq generation in Chase Bombers, fixes (Japan Prototype) and marked it as such. Sports lots of gfx bugs tho (ROM_LOADing issue(s), alpha / color blending et al).

I'll check it out later, and hey Thanks for testing Chase Bombers it's a clear Mario Kart rip off but not a bad game, i suppose
with 4 players linked up it would have been quite the riot, as things stand in MAME you've only got the 1player option against
the CPU but it's still a fun racer.

**Comment by arcadez2003** [comment]
Yip the screen sizes are correct for Chase Bombers, the black border is still there as per recent video uploads of the gameplay..........

https://www.youtube.com/watch?v=W8GCdrIjomg

**Comment by mahoneyt944** [comment]
@arcadez2003 no problem. it's fun to play. Here's a picture of the bridge normal and the bridge glitched out.
![cbombers-201118-154206](https://user-images.githubusercontent.com/49591133/99585757-c3289180-29b4-11eb-9eb8-3f6cce4f75a1.png)
![cbombers-201118-154145](https://user-images.githubusercontent.com/49591133/99585771-c6bc1880-29b4-11eb-8bf6-4c1a4c4cbe03.png)

**Comment by arcadez2003** [comment]
Yeah it does that in the current MAME builds as well, there might be a fix someday
