### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by arcadez2003** [libretro/mame2003-plus-libretro#926]
http://paste.libretro.com/219101

It doesn't look like anything i've changed but ya never know :)

**Comment by mahoneyt944** [comment]
I had this happen two weeks ago, "no space left." This is an issue with the new buildbot I'm pretty sure. I'll push it to the libretro team though.

**Comment by mahoneyt944** [comment]
I asked on discord and was told this:

"Thtas old bot, so thats on life support and i hardly want to bother as we transition harold if you dont mind stick to new infra for the time being, whatever the bot does from this point on will be eventually lost"

**Comment by mahoneyt944** [comment]
While libretro changes over the infra just ignore the build bot. New system is taking over.
