### ISSUE TITLE
IREM92 game Breakage

### ISSUE THREAD

**Issue by arcadez2003** [libretro/mame2003-plus-libretro#927]
hi @mahoneyt944 it seems this commit is causing trouble with certain m92 games.................

https://github.com/libretro/mame2003-plus-libretro/commit/3018acc8be427352587bdca713d1f1c84d05c506#diff-22e2ec84229d832257e9da6a9706f630d807c183e2a99ce8d769c5a3952718ba

In the Hunt as reported on the Rpi forums has no sound now and Ninja Baseball Batman stalls on the 
winners dont use drugs FBI screen, there may be other games in the driver with issues i'll check em later

But a classic case of why when you makes changes which will effect multiple games in any given driver you
need to test in depth to make sure there are no problems, i know it's tedius i hate doin it myself but it's better
to be safe than sorry.

**Comment by mahoneyt944** [comment]
I guess we'll have to see.... If only a few games are bugged, maybe there's another commit we need for those few to still work ......or we could separate the memory map for the games it helped? If it's a bunch we can just comment it back out. I didn't think much of this commit, seemed pretty safe ha, win some ...lose some.

**Comment by mahoneyt944** [comment]
@arcadez2003 you know what, I think I ported it wrong....maybe that should be "cpu_set_irq_line". Here's what I ported from:
```
static WRITE16_HANDLER( m92_sound_reset_w )
{
	cputag_set_input_line(space->machine, "soundcpu", INPUT_LINE_RESET, (data) ? CLEAR_LINE : ASSERT_LINE);
}
```

**Comment by Wilstorm** [comment]
Hopefully you can get it working again. =/ In The Hunt is a staple game in my library. It's a classic game and one of the few decent sub games, not many good sub games out there.

**Comment by mahoneyt944** [comment]
It's been fixed up for now with a temp fix. Need to look at that backport though and make sure it's right. Might actually work properly if we convert it correctly.

**Comment by arcadez2003** [comment]
> 
> 
> It's been fixed up for now with a temp fix. Need to look at that backport though and make sure it's right. Might actually work properly if we convert it correctly.

Well it disnae matter how you get to the destination along as you get there :) as it stands we have the sound fix for Perfect
Soldiers and we isolate the sound reset from all the other games via a new mem map to prevent em breaking and it's win win ;)

**Comment by mahoneyt944** [comment]
I'm glad I ported it right then. When things goof up I start second guessing. Any issues with m107 reported?

**Comment by arcadez2003** [comment]
> 
> 
> I'm glad I ported it right then. When things goof up I start second guessing. Any issues with m107 reported?

Nah i tested all the games beforehand ha ha ha

**Comment by mahoneyt944** [comment]
Nice.
