### ISSUE TITLE
Potential fix up for stubborn games on lower spec! Frameskip enhancements. (Very Experimental, for now!)

### ISSUE THREAD

**Issue by KMFDManic** [libretro/mame2003-plus-libretro#928]
@mahoneyt944 This is just heresay, for the moment.  But, I am going to dig deeper into the implementations this has to offer.  It may greatly help with games, such as Cruis'n USA and World and Killer Instinct on anything sub RetroPie 4.  More info:

**The actual dependency to pull this off**

https://github.com/libretro/RetroArch/pull/11451

**Application of it with a Core**

https://github.com/libretro/snes9x2005/pull/77

Again, this will be quite experimental, and probably best to test a separate branch with this.  I will have to properly get this into a RetroArch Build on my end, as well as test this on PC/Android, etc.  But, I feel this can really be helpful.  And, thanks to the wonderful work of:

@jdgleaver whom I just had to ping:)  Thanks man!  I think this can also go a long way with possibly helping improve Atari Jaguar and a select number of other stubborn Cores!

No lower spec system left behind:)

**Comment by mahoneyt944** [comment]
This could be useful once it's been successfully tested and bugs worked out.

**Comment by arcadez2003** [comment]
Sure as @mahoneyt944 said already this is something you'd implement in your own core firstly and draft in a
serious testing squad to iron out the kinks before we'd think about supporting it here as the potential for 
game breakage would likely be very high.

**Comment by arnoldsecret** [comment]
hmm, it's like how the MAME4Droid port works, right

**Comment by KMFDManic** [comment]
@arcadez2003 @mahoneyt944 @arnoldsecret @hunterk definitely not stable.  But, here is my current WIP with it for N64.  I am gonna close the issue, for now, til I have more appropriate time to hopefully work this into MAME 2003, just as well as N64!

https://www.youtube.com/watch?v=8pt4NrMi5Y4
