### ISSUE TITLE
$250 Bounty - Vector image quality (incl comparison of mame2003_plus and Advmame)

### ISSUE THREAD

**Issue by Wilstorm** [libretro/mame2003-plus-libretro#93]
### edit: $250 Bounty  (as of 8/2018)  - [Link to mame2003 vector github issue](https://github.com/libretro/mame2003-libretro/issues/332)

Something seems off or the settings are not taking effect. They are located in ```/opt/retropie/configs/all/retroarch-core-options.cfg```. The settings I used for each emulator are listed below with screenshots. Quite different if you go back and forth a few times between the two. I tried matching the settings where possible. Also I see no flicker with mame2003_plus. 

**mame2003_plus settings I used:**

```
mame2003-plus-vector-resolution-multiplier = "1"
mame2003-plus-vector-antialias = "enabled"
mame2003-plus-vector-translucency = "enabled"
mame2003-plus-vector-beam-width = "1"
mame2003-plus-vector-flicker = "10"
mame2003-plus-vector-intensity = "2.5"
```

![tempest](https://user-images.githubusercontent.com/8192258/38902121-c54f39c6-4264-11e8-9a40-bbc12c9e98bc.jpg)

**MAME 0.78 settings I used:**

```
mame2003-plus-vector-resolution-multiplier = "1"
mame2003-plus-vector-antialias = "enabled"
mame2003-plus-vector-translucency = "enabled"
mame2003-plus-vector-beam-width = "1"
mame2003-plus-vector-flicker = "10"
mame2003-plus-vector-intensity = "1"
```

![tempest02a](https://user-images.githubusercontent.com/8192258/39057512-fea11f7a-447e-11e8-9d72-4e5da706c084.jpg)

**AdvMAME settings I used:**

```
vector/display_resizeeffect filter
vector/display_rgbeffect triad3dot
vector/display_scanlines no
vector/display_antialias yes
vector/display_beam 1.2
vector/display_flicker 10
vector/display_translucency yes
vector/display_intensity 2.5
```

![tempesta](https://user-images.githubusercontent.com/8192258/38902129-ce056a68-4264-11e8-84e6-d6cbb89ab76a.jpg)

**Comment by markwkidd** [comment]
flicker definitely works here with the latest source. Try setting `mame2003-plus-vector-flicker = "100"` just to establish a baseline with the core options.

**Comment by markwkidd** [comment]
Hmm. I don't see how the beam option is supposed to work in the source. Maybe it really isn't doing anything.

**Comment by Wilstorm** [comment]
Mark I should get a chance to test this today. I think the beam option is imperative in the sense it's needed to pull off those nice thin lines for that oscilloscope vector look.

**Comment by markwkidd** [comment]
@Wilstorm  Do you have access to Windows or a Windows virtual machine? I'd be interested in your thoughts on how good you can get vector quality. I just did basic tests to demonstrate that antialias was working but you seem to actually know more about how MAME renders vectors when it's set up well. 

The vector code between MAME 0.78, MAME 2003, and AdvanceMAME on the surface looks almost identical. It makes me think you should be able to do near as well in MAME 0.78 in Windows as you can with AdvanceMAME.

**Comment by Wilstorm** [comment]
I think it requires a 32-bit OS. I actually still have a Windows XP PC at home just for these type of things. 

I am also going to add Cavers AdvMAME vector setup guide as a resource. He has some great information and explains each step and parameter well.

https://retropie.org.uk/forum/topic/1035/how-to-make-vector-arcade-games-look-their-best

**Comment by markwkidd** [comment]
For what it's worth I have run MAME 0.78 in Windows 7 x64, you just have to launch it from the dos console window

Thanks for the settings reference! This is relatively new to  me, I've really only gotten interested since I found the bug

**Comment by ZappaUtopia** [comment]
You could use the Windows version with built in frontend from here http://www.progettosnaps.net/download?tipo=mameui_bin&file=/mameui/packs/MAME32_0.078_25-12-2003.7z

**Comment by Wilstorm** [comment]
Thanks Zappa, that's a really nice looking setup. I will try it and see if I can get a screenshot with what I come up with.

I actually do have a Windows 7 64-bit handy here if needed.

**Comment by Wilstorm** [comment]
@markwkidd - Your hunch is correct. Vector games do look much better on MAME 0.78. I would say acceptable for most gamers but after using AdvMAME I am not quite sure I would cut over. The lines are a bit thicker even at the lowest beam width setting. Which makes them look a bit jaggy. I can't get a screenshot due to the app crashing on Windows 10 and Windows 7 when I press F12.

Settings in MAME 0.78 that look decent listed below. Flicker is a matter of adjusting to taste but at 100 it flashes faster than a neon brothel sign on a Friday night. Beam intensity I bumped down to 1 which looks decent. A lot changes with that setting so you need to play with it. Beam width just made it more blurry the higher the value so I left it at 1 which still seems a bit wide.
```
mame2003-plus-vector-antialias = "enabled"
mame2003-plus-vector-translucency = "enabled"
mame2003-plus-vector-beam-width = "1"
mame2003-plus-vector-flicker = "10"
mame2003-plus-vector-intensity = "1.0"
```

**Comment by markwkidd** [comment]
Is F12 your Windows screenshot key or your MAME screenshot key? Or to put it another way, have you tried both ways of taking a screenshot?

**Comment by markwkidd** [comment]
Also, I don't know about that MAME32 business. Is there any chance you could try the mame 0.78 standard from the windows console if you haven't?

**Comment by Wilstorm** [comment]
I believe MAME32 uses the standard MAME f12 for a screenshot. It does actually write to the snap folder but it's a corrupt image so I tried Windows 7 and the same thing. I believe the MAME32 frontend just needs an update. Let me see if I can get one from a command prompt. A picture tells you all you need to know when you see it.

**Comment by markwkidd** [comment]
You might also try the Windows screenshot method. Press PrtSc to capture
your screen and copy the bitmap to your Windows Clipboard.

Then you can Ctrl-V paste it into something like Windows Paint or PhotoShop
or IrfanView or whatever.

**Comment by Wilstorm** [comment]
> You might also try the Windows screenshot method. Press PrtSc to capture
your screen and copy the bitmap to your Windows Clipboard.

One step ahead of you I tried that right away but apparently how MAME works does not allow Windows to capture output via the Print Screen key. I did a regular capture to verify all was working and then after hitting print screen it pastes the same screen cap.

Yeah I was going to resize to match dimensions and resolution of other caps in Photoshop. I tried it in MAME32 windowed mode but it's blurry due to the AR or something so I need it captured full screen.

**Comment by Wilstorm** [comment]
I added a screenshot of MAME 0.78 running Tempest between mame2003_plus and AdvMAME up above in the first thread. It does fall between the two as far as quality. If you start at the top and go through each pic you'll very clearly see it's smoother as you go down. I think MAME 0.78 is acceptable but AdvMAME's lines are narrower and smoother for sure. It's the spit shine making the difference.

If one thing could be changed from looking at it running for a while I would say beam width. I see it's value is a float but it states 1 or higher any chance it can handle something smaller and get that beam a bit narrower?

**Comment by markwkidd** [comment]
Now that the bounty for addressing this issue is up to $205 I am modifying this issue a little bit to make sure there are some links to https://github.com/libretro/mame2003-libretro/issues/332

**Comment by Wilstorm** [comment]
@markwkidd - Isn't the bounty $250 and _not_ $205?

**Comment by markwkidd** [comment]
Ah yes you're right, thank you! Some libretro repositories have fuller integration with BountySource so this happens automatically, but sadly not the case for mame2003

**Comment by Wilstorm** [comment]
Ah ok, well extra "surprise" funds are always a bonus! :)

**Comment by markwkidd** [comment]
Closing this issue as solved. What a world!
