### ISSUE TITLE
Do we want the world version of safarir?

### ISSUE THREAD

**Issue by mahoneyt944** [libretro/mame2003-plus-libretro#934]
@arcadez2003 Now that the color and sound works (via sample support). Worth a re-rom to support the english version? I think the only difference is the attract screen logo.

![safarir-201215-120953](https://user-images.githubusercontent.com/49591133/102247861-845ffb80-3ece-11eb-8ca1-a46309ad35fb.png)

**Comment by arcadez2003** [comment]
As i always say you dont have to run anything by me buddy, if you wanna add a new romset wire right in :)

**Comment by mahoneyt944** [comment]
I know renaming romsets can be hit or miss with people and the enhancement is just a logo difference I think, so I figured I'd get a general vote on it.

**Comment by mahoneyt944** [comment]
Bump @Wilstorm, @KMFDManic any opinions on this?

**Comment by Wilstorm** [comment]
@mahoneyt944 - I usually try to find a US version of a game if possible, then World and finally European or possibly European over World. If it's not a lot to do or just a few minutes then I am all for "new" games! 👍 You've been doing a ton of good things so I appreciate it either way.

**Comment by mahoneyt944** [comment]
Now supported
![safarir-201216-200422](https://user-images.githubusercontent.com/49591133/102424844-0ab53400-3fda-11eb-8471-1bfdf04af1d0.png)

**Comment by Wilstorm** [comment]
@mahoneyt944 - I appreciate you adding this one! I enjoy these simple choose-your-lane-collision-racers! :)

**Comment by mahoneyt944** [comment]
I enjoy it too. Reminds me of dodgem.
