### ISSUE TITLE
Incorrectly trying to load samples

### ISSUE THREAD

**Issue by mahoneyt944** [libretro/mame2003-plus-libretro#935]
Just fixed up `drivfrcg` video issues (color proms and video code). I noticed it's on galaxian hardware and it tries to load the galaxian samples even though it's not using them, as far as I can tell anyway. This displays the missing samples warning at loading by mistake. Can we remove these in the driver without losing the game sound?

**Comment by arcadez2003** [comment]
Yeah i see a fair few games in this driver are hooked up to MDRV_SOUND_ADD(CUSTOM, galaxian_custom_interface)
you can see the full code for that define in sndhrdw/galaxian, i've only glanced at it but it seems all the games even if
they dont need the galaxian samples per say still need to be hooked up to the code so they use the other sound streams.??

I dont see any easy way to remove the sample trigger from drivfrcg, are any other games in the driver having the same issue.??

**Comment by mahoneyt944** [comment]
I haven't tested but I'd think so.

**Comment by mahoneyt944** [comment]
Drivfrcp (namco) doesn't have this issue.
