### ISSUE TITLE
Datfile (xml) issues

### ISSUE THREAD

**Issue by WindyWinston** [libretro/mame2003-plus-libretro#938]
Hi guys, just updated my old mame2003-plus set and i'm getting some odd things in clrmamepro.

The newly supported `kof2003` (not decrypted version) and `svc` (not bootleg) and being detected as `pgoal` in clrmamepro. They don't seem to be in the datfile (freshly created from 2003plus).

It's asking me to remove my Custom OST of `moonwlkb` and `ddragon` is asking for the 02 files (stereo). This stereo version is nowhere to be found on the internet and as far as I know the custom OST samples were supposed to be removed from the xml dat ?

**Comment by mahoneyt944** [comment]
moonwlkb.zip should be moonwalk.zip it was recently renamed to match the parent rom name at the request of @Wilstorm

**Comment by mahoneyt944** [comment]
What commit version of mame2003-plus are you using? Did you update from source? are you generating your own dat file?

**Comment by mahoneyt944** [comment]
I would google "mame2003-plus romset" and there could be an **archive** site the has ddragon in a optional soundtrack directory. I obviously cannot link to any sites.

**Comment by Wilstorm** [comment]
@WindyWinston - I just rebuilt a set from scratch a few days ago and it built ok. Here's a list of ROM that aren't part of the official MAME or rollback set, the rest should be found in MAME. For the custom OSTs I would follow @mahoneyt944 's advice to get the "-02's".

```
Bubble Bobble (Ultra Version)(USA) [folder: bublboblu - parent: bublbobl - size: 548kb]
missing rom: a78-05u.52 [size: 65536] [CRC32: b31d2edc] [SHA1: b7d317c0b5b86c0bf39b18cfe584bca9d22d4eba]
missing rom: a78-06u.51 [size: 32768] [CRC32: a6345edd] [SHA1: 144f33002ee40acdbfa6a49119092a319048bb00]
missing rom: a78-08u.37 [size: 32768] [CRC32: d544be2e] [SHA1: 1472db52dcd9e17a866ea2766cfea500d8f712ab]

Donkey Kong Remix [folder: dkrdemo - parent: dkong - size: 33kb]
missing rom: dkrdemo.5at [size: 4096] [CRC32: e59d406c] [SHA1: 7698e319ae191bb8bf7deeea5c4f18da04d73f73]
missing rom: dkrdemo.5bt [size: 4096] [CRC32: 660d43ec] [SHA1: 8bba334cec022ea851c4a82f6ecbc91c0708daea]
missing rom: dkrdemo.5ct [size: 4096] [CRC32: f48cb898] [SHA1: 470b8bee7f55e1d828abc0b1ec4b423392c83a78]
missing rom: dkrdemo.5et [size: 4096] [CRC32: f9fdff29] [SHA1: c2eb8f0ede8384369e17d8616f4ce063ae12b6c2]

Final Fight 30th Anniversary Edition [folder: ffightae - parent: ffight - size: 3mb]
missing rom: ff-1m.3a [size: 524288] [CRC32: d5469303] [SHA1: 0c1e33a87eb3ef79e6a5ba80753eb495284e666c]
missing rom: ff-22m.7h [size: 524288] [CRC32: cbdd8689] [SHA1: a75918ee837dfccdd4fd02b716928a2de2003103]
missing rom: ff-23m.8h [size: 524288] [CRC32: 86def74f] [SHA1: 5206cc13bfe40fb4f9c3677629aee89099623ee6]
missing rom: ff-3m.5a [size: 524288] [CRC32: 0c6302bf] [SHA1: 03ee13a67a8a3b92fac462623ace752d77b9e9f1]
missing rom: ff-5m.7a [size: 524288] [CRC32: 91a909bd] [SHA1: 09621cb33a9c26798b1bba186dceb02e5f126e1a]
missing rom: ff-7m.9a [size: 524288] [CRC32: 89f8b4cd] [SHA1: c169c445686d3c79eae2dc42460b8194c491ccb0]

Hyper Street Fighter II: The Anniversary Edition (Asia 040202) [folder: hsf2a - size: 45mb]
missing rom: hs2ax.03 [size: 524288] [CRC32: 5f3d7397] [SHA1: 96f327dd998105ad5dc46bc9d3b741805a840d68]
missing rom: hs2ax.04 [size: 524288] [CRC32: 59acf108] [SHA1: e68fe233681175b29a35badab249c2b892b23af3]

The King of Fighters 2003 (Decrypted) [system: Neo-Geo - folder: kof2003d - parent: kof2003 - size: 125mb]
missing rom: 271-v1d.bin [size: 16777216] [CRC32: 2964f36e]

Mortal Kombat II Plus (Beta 2) [folder: mk2p - parent: mk2 - size: 16mb]
missing rom: su2.l1 [size: 524288] [CRC32: 65d11dd7] [SHA1: bb94cca5a35f8f285d32314f8762c3c52ec48f5b]
missing rom: ug12.l31 [size: 524288] [CRC32: b6d8ff5c] [SHA1: ad974cc0dcdf35c7175f7cb8c620b58b82843523]
missing rom: ug16-vid [size: 1048576] [CRC32: b2af2798] [SHA1: 3d679fb59753b72f961fe60a65e4e03a76b64266]
missing rom: ug20-vid [size: 1048576] [CRC32: d05e970a] [SHA1: 0f07d72c0ae9ed77c79b4a39abbc047df68a6b1d]
missing rom: uj12.l31 [size: 524288] [CRC32: 05ff15a9] [SHA1: 23e9c47644c756d7568b6e5122801b19cf594e9b]
missing rom: uj16-vid [size: 1048576] [CRC32: d70dd149] [SHA1: 1add61f22a68c0bd8dba3fa0da18f5ecc7f51c6f]
missing rom: uj20-vid [size: 1048576] [CRC32: 0f9c9a12] [SHA1: 6c593ab037f9e203e50a13bef1cdbba765a45845]

Ultimate Mortal Kombat 3 Plus (Beta 1) [folder: umk3p - parent: mk3 - size: 27mb]
missing rom: um312u54.bin [size: 524288] [CRC32: a46ee73c] [SHA1: 2ad13bf20b9e42729773307b55fa67e430b1cf87]
missing rom: um312u63.bin [size: 524288] [CRC32: 4f200db2] [SHA1: 25bab2c52df59056e3018d88491de1f2b1a8eed2]
missing rom: umk-u114.bin [size: 524288] [CRC32: b8504598] [SHA1: fce32581d6ff9e1a7455c30fb10812ba9dc70db5]
missing rom: umk-u115.bin [size: 524288] [CRC32: e003a51b] [SHA1: e11c0cb0a9d647f17398b48d0b7d088526a18af8]
missing rom: umk-u116.bin [size: 524288] [CRC32: f6df5c98] [SHA1: e8317cf46d23738223f034c10f0f6f874d72165f]
missing rom: umk-u117.bin [size: 524288] [CRC32: 52ee547e] [SHA1: 97dba4d6dd503a623dad5709767e4617de211af0]

SegaSonic Bros (Japan, prototype) [folder: ssonicbr - size: 640kb]
missing set: SegaSonic Bros (Japan, prototype)
missing rom: ssonicbr.ic31 [size: 262144] [CRC32: 03709746] [SHA1: 0b457f557da77acd3f43950428117c1decdfaf26]
missing rom: ssonicbr.ic32 [size: 262144] [CRC32: cf254ecd] [SHA1: 4bb295ec80f8ddfeab4e360eebf12c5e2dfb9800]
missing rom: ssonicbr.ic4 [size: 131072] [CRC32: 78e56a51] [SHA1: 8a72c12975cd74919b4337e0f681273e6b5cbbc6]

Tron (freeplay) [folder: tronfp - parent: tron - size: 108kb]
missing rom: 625_v11.bin [size: 8192] [CRC32: 402a99dc] [SHA1: d3fdf877f185473d3dbf33cd1a3d0dae4173e479]
```

**Comment by WindyWinston** [comment]
I renamed my `moonwlkb` OST samples to `moonwalk` but clrmamepro still wan't to delete them.

The Custom OST samples were removed from the mame2003plus dat fairly recently so clrmame shouldn't be asking me about moonwlkb and ddragon. (I couldn't find any stereo 02 files for ddragon, even from KMFDManic).

@arcadez2003 recently added the non-bootleg version of SVC and the non-decrypted version of KOF2003 but they are not in the mame2003plus xml dat ?

**Comment by mahoneyt944** [comment]
@WindyWinston I believe you're using an outdated dat. What version of plus are you using?

**Comment by WindyWinston** [comment]
It's says 0353570. My Retroarch says all cores are up to date ? (Windows 10 64bit, Retroarch 1.9.0).

**Comment by WindyWinston** [comment]
This is weird. I just looked on the buildbot and the Windows 64bit cores only go up to 17th November ! Has there been another hack ?

**Comment by mahoneyt944** [comment]
@WindyWinston right now libretro is upgrading their infrastructure so the newest commits are available from the online updater. But can be downloaded from the pipeline directly for a few platforms here https://git.libretro.com/libretro/mame2003-plus-libretro/-/commit/b912300b5d710a282fb6c90fd09bf6b5ac8f6fe1/pipelines?ref=master

For more platforms you can get them here http://artifacts.libretro.com/minio/nightly/

**Comment by WindyWinston** [comment]
Thanks for the links, i'm a month out of date !

**Comment by Wilstorm** [comment]
Yes both are in the current DAT listed below. If you're using a DAT that doesn't have the custom OSTs listed then ClrMamePro will try to delete any extraneous samples in the sample folder.

```The King of Fighters 2003 (World / US, MVS)```
```Snk Vs Capcom  - Svc Chaos (MVS)```

**Comment by mahoneyt944** [comment]
@WindyWinston no problem, install the newest commit from the pipeline  and generate a new dat and you should be good.

**Comment by WindyWinston** [comment]
I'm now using the latest version LOL ! clrmamepro is still asking me for stereo samples of ddragon and moonwalk (the ones with -02, I have the -01's). These shouldn't be in the datfile as they are optional Custom OST ? (and I don't think they are available anywhere, only the mono ones).

**Comment by mahoneyt944** [comment]
@WindyWinston send me an email. mahoneyt944@gmail.com

**Comment by mahoneyt944** [comment]
You can copy and rename the 01 files to create the 02 files for a quick fix. Or generate stereo samples from the 01 samples in an audio editor.

**Comment by Wilstorm** [comment]
@mahoneyt944 - The 01 files are single channel (usually left) so that won't work but duping the 01s would work. Samples only care about the name. Heck you could add your favorite song as the 02 channel if you want. ClrMamePro won't add samples (only remove) so you have to add them manually.

**Comment by mahoneyt944** [comment]
That's what I mean, you can copy the 01 file and rename to get the 02's because mame will accept it though not correct. Or you create a new file in an audio editor by copying the 01 source to a second track then export as stereo.

**Comment by Wilstorm** [comment]
I'm not sure I'm understanding. Basically if you dup and play back 01 out both speakers it's just mono. The 01 and 02 are single channel mono (previously 2 channel stereo together). There is no stereo left to split out of either the 01 or 02 channel. You can take 5.1 or whatever and split that out in to 6 separate mono channels.

Basically they are already "demuxed". They are single channel if you tried to export using sox or whatever to split out channels nothing would happen, you should end up with the same exact file you started with. Sorry not sure of a better way to say it.

**Comment by Wilstorm** [comment]
The left and right channel (01 and 02) are pretty darn close but not exactly the same. I think the reasoning was to split the channels and only play one channel (out both speakers) to keep the size down and to save space. If both are present in the sample pack remux and you got stereo again.

One of the challenges they were having on the NES mini was memory issues due to samples being to large and crashing on unload but I think KMFDManic created a work around using a swap file and it can now handle larger samples.

I have all the original samples KMFDManic and gpstar81 used. I was going to try and tighten up the samples but keep the dynamic range but some of the source material is MP3 only up to 15kHz and you can replace frequencies that have been removed. There's just nothing there from 15 to 20kHz (or above). If I can find the original FLAC or even buy the OSTs if they are reasonable and not some $100 collector thing I'll rerip them in a higher quality and true FLAC for sure.

**Comment by Wilstorm** [comment]
I meant the source material used to create the samples. It's huge like 9GB total.

**Comment by mahoneyt944** [comment]
Sample loading used to have a bug for files over a certain size. We fixed that back when we fixed up journey to support sepways. I'm not positive there aren't other bugs related but these large samples have been working well ever since that fixup. It may not be an issue now. Should be tested again.

**Comment by Wilstorm** [comment]
@mahoneyt944 - Sorry, I meant the issue was on an NES-mini. It's not related to this core, well it is, but I mean it's KMFDManic's derivative works. Everything works fine on m3plus as far as I seen with some massively large samples I've tried...well at least up to 325MB is the largest I've tried so far! :)

**Comment by mahoneyt944** [comment]
> Everything works fine on m3plus as far as I seen with some massively large samples I've tried...well at least up to 325MB is the largest I've tried so far! :)

Ok good lol

**Comment by WindyWinston** [comment]
Slightly unrelated but what is going on with the Retroarch buildbot ? It said the maintenance was for 2 days on the 18th November.  
http://buildbot.libretro.com/nightly/ has no content beyond 18-Nov. Is the new buildbot http://artifacts.libretro.com/minio/nightly ? Where to download the latest nightly of Retroarch ?

**Comment by mahoneyt944** [comment]
They are hoping to have the new system operational by Christmas. Until then it's going to be spotty.

**Comment by WindyWinston** [comment]
Where did you hear this ? Is it Facebook only because i'm not a part of that ?

**Comment by mahoneyt944** [comment]
I talked to the libretro devs on discord about this. In a nut shell, the old build bot is obsolete and will be fully replaced by the new pipeline infrastructure. The new pipeline offers much faster builds so future updates won't be as delayed, most build in just a few minutes. We will also have the CI build integrated for each platform within the cores so we will be able to identify platform specific issues much faster. I'm not involved in the infrastructure stuff personally so I would direct you to speak with @m4xw for specific questions, but I would say just stay posted for updates. There should be some news shortly.

**Comment by m4xw** [comment]
> 
> 
> Slightly unrelated but what is going on with the Retroarch buildbot ? It said the maintenance was for 2 days on the 18th November.
> http://buildbot.libretro.com/nightly/ has no content beyond 18-Nov. Is the new buildbot http://artifacts.libretro.com/minio/nightly ? Where to download the latest nightly of Retroarch ?

We are currently running the backup of that day virtualized while doing the final integration of the new infra.

**Comment by mahoneyt944** [comment]
@WindyWinston looks like the online updater is live again.

**Comment by WindyWinston** [comment]
Thanks for the heads up. So we're back to the old buildbot again ?

Merry Christmas by the way !

**Comment by mahoneyt944** [comment]
The old build bot is gone. The new infrastructure replaced it. Updates from the "online updater" now are way faster now.
