### ISSUE TITLE
Res net functions backport

### ISSUE THREAD

**Issue by mahoneyt944** [libretro/mame2003-plus-libretro#942]
@markwkidd do you have any idea why we use 32 here instead of 18 like I've found in newer mames? I'm looking to backport support for computing resistor net outputs but there's this small discrepancy. Not sure what the effect would be if changed or why we set 32? We could use 32 in the backported code as well but I'd like to confirm what's best. 18 seems to be the standard now.

https://github.com/libretro/mame2003-plus-libretro/blob/5bbe5cafbc89a3c179334ca694c3d342837da30b/src/vidhrdw/res_net.h#L72-L74

**Comment by mahoneyt944** [comment]
Ok so I back ported the code into res_net but left it set to 32. Weights still work as intended. I then tried to fix the colors in strike bowling using 32. It doesn't work. So I changed just the new backported code to use 18, and success! It works. Here's the pr https://github.com/libretro/mame2003-plus-libretro/pull/944/files 

The final step is to figure out if the weights need to be set at 32 like they were in our code or if 18 also works.

**Comment by arcadez2003** [comment]
@mahoneyt944 a fair few games use resnet, testing will be needed after making changes such as these, we should really
try to round up some willing contributors in that dept, as it stands all these drivers are all affected...........

https://github.com/libretro/mame2003-plus-libretro/search?q=res_net

**Comment by mahoneyt944** [comment]
@arcadez2003 so far the code is added but hasn't been integrated in any drivers. All the "weight" code that we use is as it was before the merge. So nothing is effected yet. I want to test the weight code with the value of 18 before any real changed are made.

**Comment by arcadez2003** [comment]
Ok cool are these the commits you wanna backport.??

0.87: Jarek Burczynski fixed a res_net.h related crash in Strike Bowling.
0.84u5: Jarek Burczynski improved colors in Strike Bowling. Added new function: compute_resistor_net_outputs() in res_net.h. This function calculates outputs (not weights) of color circuits where the hardware consists of open collector PROMs.

**Comment by mahoneyt944** [comment]
@arcadez2003 I didn't look at specific commits for sbowling but I got the correct colors in my wip pr #944 , which I'm guessing is the bulk of those commits, but we should look into the crash it mentions.

Using #944 as a test, I fixed up the video code for sbowling to use the new functions. The main issue is that our original weight code uses the value 32. The new version uses 18 for the weight code and 18 for the outputs code I just added. (shared define). So I tried to use 32 with outputs to not disturb anything but 32 doesn't work with the outputs code so what I did was kept 32 for the weights code and added a hard 18 for the outputs code. This allows both to work without any issues but I believe that the weights code should probably be 18 as well but as you pointed out changing that would require a good bit of testing first.

**Comment by arcadez2003** [comment]
Yeah i looked at the original commits circa MAME85 apart from the changes in res_net.h the only other file affected 
was of course driver/sbowling.c where some alterations were done to the res_net handling to line up with the new code
in res_net.h.

Maybe try using the original MAME85 code then if it works fine with Strike Bowling you wont need to worry about setting
different output and weights values on a per game basis, the only thing required then would be to check the MAME Wip
for the drivers affected for a few builds afterwards to look for any fixes that might have then been required for games
which got broken if any eg........

0.87: Jarek Burczynski fixed a res_net.h related crash in Strike Bowling.

**Comment by mahoneyt944** [comment]
Do any other games use `compute_resistor_net_outputs` ? Checking current mame, I'm only seeing sbowling. If so, the backported code is working properly and doesn't interfere with our code.

The possibility of interference comes if we want to change the weights code to also use the value of 18 instead of 32 like newer mames do. It's not necessary but it would be nice to know why it was changed to use 18. The rest of the code is the same.

**Comment by mahoneyt944** [comment]
I looked into 85/ 86 and it looks like they used a value of 8, our mame uses 32, and newer mames use 18. I'm guessing 8 caused the crashes so I was increased to 18? Everything points to using 18 for me. Just got to test I guess.

**Comment by mahoneyt944** [comment]
Ok I activated the new outputs code with 18. Only used in sbowling. And left the weights code set to 32. So no changes are disturbing our code. I need to test the weights code with 18 to see if we need 32 or not. I'll test before changing it.

**Comment by mahoneyt944** [comment]
Here's a test of sbowlings.

Old
![sbowling-201222-180500](https://user-images.githubusercontent.com/49591133/102941418-acc49880-4480-11eb-841a-9fc8a20de3a0.png)

New
![sbowling-201222-180653](https://user-images.githubusercontent.com/49591133/102941439-b5b56a00-4480-11eb-872c-44db4cbabf31.png)

**Comment by mahoneyt944** [comment]
Since this is now working and the code for weights wasn't modified from 32. I'm going to close this. If I get time I'll test the effects of changing the weight code value to 18, but for now everything is working.
