### ISSUE TITLE
[Question] A way to separate vertical game roms ?

### ISSUE THREAD

**Issue by WindyWinston** [libretro/mame2003-plus-libretro#949]
Just a question for the moment. Is there an easy way to separate my collection between vertical/horizontal game roms ? Maybe a batch file or way to make one ? The reason for this is to use a proper shader for the vertical games and also to make mix screenshots in the correct aspect.

Is there also a way to know which games in mame2003plus use more than one monitor ?

**Comment by mahoneyt944** [comment]
The history.dat has orientation notation. I'm not sure that there's an easy way to generate a list currently but I'll let others way in.

**Comment by mahoneyt944** [comment]
My apologies the orientation is in the dat.

**Comment by mahoneyt944** [comment]
With the dat file you can use romlister https://www.waste.org/~winkles/ROMLister/

**Comment by mahoneyt944** [comment]
Here's a pdf tutorial

[Romlister Tutorial.pdf](https://github.com/libretro/mame2003-plus-libretro/files/5740546/Romlister.Tutorial.pdf)

**Comment by WindyWinston** [comment]
This is exactly what I was after, thanks!
