### ISSUE TITLE
Name change to LRMAME 2003 Plus?

### ISSUE THREAD

**Issue by twinaphex** [libretro/mame2003-plus-libretro#974]
Hi there @arcadez2003 and @mahoneyt944 ,

I would like to ask what your thoughts would be on a name change to LRMAME 2003 Plus. Do note - I don't make the final call on this one, this is entirely up to you two since you guys are the main lead developers. I am not forcing anything here. I'm also open to any suggestions you have.

**Comment by arcadez2003** [comment]
TBH im not fussed if you wanna rename the core then wire right in, off the top of my head i have no ideas just now
of a good catchy name but if i think of one i'll chime in :)

**Comment by mahoneyt944** [comment]
@twinaphex 

Is there any reason for changing it? It seems to be a commonly known name at this point. My concern would be adding some confusion for new users when they google and YouTube stuff and find the mame2003-plus core that's no longer called that. Oh I can see the retropie forums already lol....

Why the sudden interest in changing it?

**Comment by twinaphex** [comment]
Yeah, as I said, you guys ultimately make the decision. If you don't want it, that's fine, you two are the main core developers anyway.

**Comment by arcadez2003** [comment]
> 
> 
> @twinaphex
> 
> Is there any reason for changing it? It seems to be a commonly known name at this point. My concern would be adding some confusion for new users when they google and YouTube stuff and find the mame2003-plus core that's no longer called that. Oh I can see the retropie forums already lol...
> 

Yeah certainly there will be some confusion initinally but in time users will get their heads around the name change, however
a fair amount of the source and readme files will need to be updated to reflect this and that is no simple two min task.

> Why the sudden interest in changing it?

I cant speak for the libretro team but certain MAME dev's who i personally despise are trying to gain enough support
to enact legal action with regards to this core, one of the outcomes if it did come to pass is we'd have to rename it to
something else

But that is bridge we can cross further down the road should we need too.

**Comment by m4xw** [comment]
> I cant speak for the libretro team but certain MAME dev's who i personally despise are trying to gain enough support
> to enact legal action with regards to this core, one of the outcomes if it did come to pass is we'd have to rename it to
> something else

None of them owns the trademark tho. Just lots of annoying barking.
We'd happily comply with a official written request by the trademark owner, we just never got asked to change it.

**Comment by arcadez2003** [comment]
> 
> 
> > I cant speak for the libretro team but certain MAME dev's who i personally despise are trying to gain enough support
> > to enact legal action with regards to this core, one of the outcomes if it did come to pass is we'd have to rename it to
> > something else
> 
> None of them owns the trademark tho. Just lots of annoying barking.
> We'd happily comply with a official written request by the trademark owner, we just never got asked to change it.

Yes certainly alot of yapping around licence violations etc etc, the way some of them spoke to me on reddit the other week
you'd think i'd actually commited a crime by contributing towards this core which is laughable

**Comment by m4xw** [comment]
How dare you, creating free and open software

**Comment by mahoneyt944** [comment]
I don't mind the core being a little rogue.
![im-not-fing-leaving-the-show-goes-on](https://user-images.githubusercontent.com/49591133/107117593-4b4a6480-6849-11eb-941c-fb1ad5c0aaa6.jpg)

**Comment by arnoldsecret** [comment]
I was expecting LA2003 (Libretro Arcade 2003) or something, that'll probably please the MAME devs for sure in my opinion.

**Comment by twinaphex** [comment]
Even if we change the name, it's not going to change anything according to this post -

"galibert (MAME Developer)
Let's things be clear: nothing will ever been worked out as long as you or your project is used to push versions of Mame that are old enough to vote. That's saying overtly that all the work we've done since then is useless, and if that's not a personal attack I don't know what is."

At this point given this unreasonable stance, I say we'd not worry about this anymore. We are not removing the core period, it is of use to millions of people. It's unfortunate they can't see that but ultimately it's not our problem either and we don't deserve o be harassed over it by them either.

**Comment by mahoneyt944** [comment]
This isn't something I care to invest any time into. Changing the name won't change the situation with them, they just want this core deleted. So there's no point.

**Comment by twinaphex** [comment]
Yeah, I think you're right. If that's the endgoal of all this, then sorry, that is one ultimatum that is too extreme. This core has its right to exist no matter where they stand on it. If by virtue of us having this core it means they treat us as adversaries and are hostile towards us, so be it.

**Comment by twinaphex** [comment]
To all participants - can we close this issue for now then? Don't think we are going to be making any headway here regardless.

**Comment by mahoneyt944** [comment]
Yeah I think it's safe to close. If we ever decide to change the name it should be under our own ambitions not by threat.

**Comment by twinaphex** [comment]
Exactly. Unfortunately the only conclusion I can come given the ultimatums that are doled out is that MAMEdev should take a long hard look in the mirror at the current way they as a team approach us, and if they can ever start approaching us in a far less hostile and abrasive manner, we are willing to talk about reasonable things. Removing this entire core is not one of them.

**Comment by arcadez2003** [comment]
Their argument is akin to we should never watch an ole movie or listen to an old song as there is remake or a cover
available which must be viewed as simply being better, as it's "newer" as we all know fine and well "newer" does not 
always equate to being better.

They're stuck in their ways pushing "their" vision of what MAME should be onto everyone else, they've turned 
it into their own personal build to all essential purposes and damn what the "little people"  the users might want.

The easiest way to have rendered this core obsolete rather than bitching and moaning about it's existence constantly 
would be to have created a special lighter MAME build optimized so it will perform better on low spec devices, but i guess
that is just too simple an outcome for high and mighty MAME DEV.

Anyway due to this and the whole Sega C2 debacle i've cut all ties with them and left the dumping union as apart from
disagreeing with the current direction of the project, i feel there is no point to continue trying to talk sense into those
so far gone they cannot see reason.

MAME requires new blood to push it forward and make it relevant once again but  while those old duffers continue to 
stick around decade after decade clinging on to the positions of power then MAME like them will remain stuck in a 
previous era.
