### ISSUE TITLE
Retiring from this project

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/mame2003-plus-libretro#976]
@arcadez2003 @mahoneyt944 I'm gonna leave my involvement to the project as I don't feel like contributing much anymore. I feel like I already did enough to make this what it is now, and I'm leaving it all towards you two to improve further.

**Comment by mahoneyt944** [comment]
Sorry to hear, if you ever decide to get back in don't hesitate. Thank you for your contributions.

**Comment by twinaphex** [comment]
@arnoldsecret Any reason for this or anything we could do to change your mind? You disagreed with the decision made on the name change?

**Comment by arnoldsecret** [comment]
Nothing in regards to the name change, I just feel like I'm already done what I've done with this core

**Comment by twinaphex** [comment]
OK, just so long as it is not because of an unresolved grudge then its all good, interests can come and go for people. We thank you for your contributions.
