### ISSUE TITLE
Slight differences in drivers between cores

### ISSUE THREAD

**Issue by Wilstorm** [libretro/mame2003-plus-libretro#978]
@mahoneyt944 - I was wondering if I can shoot a quick question by you. I've been looking at mame2003-plus vs. current MAME/FBNeo and I see a few things that seem off or maybe it's just old vs. current drivers or differences between cores. I'm just trying to understand why the slight variations.

In mame2003-plus I see afighter as horizontal 320x224 but current MAME shows it as vertical 224x320. so does Arcadeitalia.
In mame2003-plus I see ajax as 224x288 in current MAME as 224x304.

**Or in FBNeo:**

In mame2003-plus I see mk2p as 400x254 in FBNeo as 400x256.
in mame2003-plus I see umk3 or umk3p as 400x254 in FBNeo as 400x256.

Are these just errors or slight differences? Anywhere from 2 to 16 pixels wider and afighter seems to be a completely different orientation in m3plus vs. current mame.

The thing about orientation though is more current versions seem to use rotation in degrees vs. horizontal and vertical. That way you know if it was rotated left/right or inverted with 0 being the default upright as 4:3.

**Comment by mahoneyt944** [comment]
That's a loaded question. Some size differences can be related to the graphics code, other times it can just be due to inaccuracies.

You have to change and test each one to verify the desired outcome. Especially with flip screen and cocktail modes if present.

**Comment by Wilstorm** [comment]
@mahoneyt944 - Ok, unfortunately I can't because afighter crashes on m3plus unless it's had an update in the last year and my ROM is outdated. The 16 pixel difference on other games can be close visually so I'm not quite sure who's core is correct. It's a guess for me if this game peep is a bit fatter or slimmer than the original arcade cab.

I do see a lot of differences of these two resolutions across many games though. 304x224 (old cores) vs. 320x224 (newer cores). I see that 16 pixel difference over and over and over. I don't if it was some magical "balanced" resolution that works for many games.

Just looking at some of the newer ROMs you just added. mk2p, umk3, etc. are 254 pixels high where as FBNeo added them 256 pixels high. Why 2 pixel difference between the two cores? Or that's also the difference between the cores graphics code?

Basically I was going to try and make a shader file for FBNeo pulling infor from other DAT's but I don't know who's is correct. Should I use m3plus (304x224) as a reference or current mame (320x224) or a hybrid. 

I built a Python script that pulls info from DAT's but it's more like a spider. :) mame2003 and m3plus are no problem so clean and easy but you have to make fields for every variable because the info is so complete. mame2010 is very incomplete in regards to aspect ratio so I can go only so far with it but found a way to get the job done. Mame2015 and newer I have to track rotation by degress and then calculate the orientation and aspect ratio in addition to display count while looping through every line of a DAT but you have to track when the game changes. Then I can calculate the aspect ratio like 12x3 for ninjaw, etc. The game name field is different for mame2016. The differences between DATs goes on and on. You have to make a lot of exceptions to cover all DAT types.

Basically the plan was to make shader files for Libretro cores (mame2000, mame2003, mame2003, mame2003-plus, mame2015, mame2016, FBNeo, lr-fbalpha2012 and pifba. Also the shader configs align the shadow mask so vertical games don't get a rainbow effect. To me shaders make these old retro games look 10 times better. It was night and day difference when I started using shaders.

**Comment by arcadez2003** [comment]
@Wilstorm afighter = Action Fighter it's never worked in this core

**Comment by Wilstorm** [comment]
@arcadez2003 - Ok, thanks. I saw your post on the RP forums. That's good stuff, a good read. Yeah I don't see any easy way to do this without some errors in the information. 

I would be curious why the 2 pixel difference between m3plus and fbneo for the newer mk ROMs or maybe it was just a typo.

The newer DAT's (mame 0.228) have for example games like Galaxaian (224x256) that have triple vertical resolution. So 256 x 3 = 768. So the game shows it as 768x256. It has something to do with modelines to generate the background stars properly. There's not info in the DAT to reverse that calculation. It's a mess of math and it's still not completely accurate. I think I'm going to just stick with the cores that have the xml info. for now. It was originally intended for mame2003 and I added arguments to use it with mame2003-plus. Both of those DAT's have such good cleanly documented information. I'll close this out and thanks good sir!

Newer DAT's:
```
This explains why your screenshot is 256x224 but the "resolution" is 768x224. The screenshot is the actual pixel-by-pixel screen dump, the resolution is including all the timing information (we're going by the 18.342 MHz "master clock" (in the info case the pixel clock), which is divided by three to provide a 6.144 MHz signal that drives the video logic, described as "pixel clock" in the driver. What is 256 times 3? 768.

And remember this basic equation, where HFP = "Horizontal Front Porch", HBP = "Horizontal Back Porch" and HDISP = "Horizontal Displayed pixels", active area, whatever:
HTOTAL=HSYNC+HFP+HDISP+HBP=HBLANK+HDISP
HBLANK=HSYNC+HFP+HBP

Ergo:
44 pixels front porch
32 pixels horizontal sync
44 pixels back porch
6 pixels left border
256 pixels video
2 pixels right border
---
384 pixels total per line

And scaled from 6.144MHz to 18.432MHz?
132 pixels front porch
96 pixels horizontal sync
132 pixels back porch
18 pixels left border
768 pixels video
6 pixels right border
---
1152 pixels total per line

But given the measurements from schematics in the source code, it's actually:
42 pixels front porch
32 pixels horizontal sync
46 pixels back porch
6 pixels left border
256 pixels video
2 pixels right border
---
384 pixels total per line

And scaled from 6.144MHz to 18.432MHz?
126 pixels front porch
96 pixels horizontal sync
138 pixels back porch
18 pixels left border
768 pixels video
6 pixels right border
---
1152 pixels total per line
```


**Pseudo code for reversing the calculation:**
```
aspect = x / y

if (abs(aspect - 4/3) > 0.2 ) // choose your trigger
{
x = y * 4 / 3
or
y = x * 3 / 4
}

Galaxian : x = 768, y= 224
aspect: 3.43
==> (aspect - 1.33 ) > 0.2
==> x = 224 * 4 / 3 = 299

If you do not want to loose information, just do

y = 768*374 = 576
```
