### ISSUE TITLE
Mspactwin

### ISSUE THREAD

**Issue by mahoneyt944** [libretro/mame2003-plus-libretro#980]
Just saw this gem and pulled up the commit. Looks interesting, 2 player simultaneous play.

https://github.com/mamedev/mame/commit/61e0c1d4da0c146412fcde3713c760dd5a432d57

**Comment by arcadez2003** [comment]
Yeah i seen the posts for this game the other day it's certainly one it would be nice to support in this core, as you can
see from the commit codewise it's certainly chalk to our cheese, there might be a few hurdles to overcome before we
can support this in our ole pacman.c driver.

Are you thinking of taking this on.??

**Comment by mahoneyt944** [comment]
I might down the road if no one else does first. Right now though I'm working on other stuff.

**Comment by arcadez2003** [comment]
Well being honest with ya im busy myself with regards to trying to get the Ghox sound MCU to work in MAME78.

i looked at Mspacman Twin the other day right away i thought it's going to be problematic but i suppose we wont know
until we give it a go, i'll start some prelim work on it see how it goes but i'll likely need to rope ya in for some help and
advise down the road.

**Comment by mahoneyt944** [comment]
Sounds good. I'm sure we can get something going.

**Comment by arcadez2003** [comment]
Hmm after a more in depth look at the commit today long story short there are a fair few hurdles to overcome 
alot of the code is simply not compatible with this core either format wise or it doesn't exist in MAME78 to begin 
with, we'd be trusting to much to luck here that if we mod the code and drop into our ancient pacman.c the game
would actually then work.

This is why i tend to steer clear when it comes to attempting to backport the newest game additions to MAME
unless they're what we call drop in's with minimal changes required, i lucked out with pubball in the sense we
had the code already and what i left out or modded codewise from the original MAME commit made no difference
but at the end of the day it was still luck it even booted in our core...........


https://github.com/mamedev/mame/commit/88339b1ac740a3067900c568133333f111f106bc#diff-5a6ed8d89fae5f679ce8ca81a9abd7d6260ad68850f7943799878ad769221048

https://github.com/libretro/mame2003-plus-libretro/commit/c0eef4f5fce30d87d69951e41874ca571d8cf937

We wont always be so lucky hence better to give a wide berth to new games which in all likelyhood will never
work in this core, but at the end of the day if you fancy giving it a go down the road then you can always rope
me grant and any other devs you know in for some advice ;)

**Comment by mahoneyt944** [comment]
No problem, it's on my tinker list for sometime later.

Right now I just made an additional commit on Cheeky Mouse. The game has good colors now and I added my own lick of madness to the sound triggers. Newer mame updated the dac code a bit. Trying to convert our code to use the newer 8 dac setup was missing some triggers for me. I ended up using a for loop to force the triggers through a single dac instead. This seems to work well, I just need to see if I can backport some of the audio effects possibly.

Honestly not something I've done yet, if you have any idea how we might be able to splice it in? It doesn't work properly in current mame but I think my single dac method might work better if I can hack in the tones. Here's the commit where the tones got added.

https://github.com/mamedev/mame/commit/308c2bb72d370ec873d9737ee35c5817d2c90d7f

**Comment by Wilstorm** [comment]
Nice, this looks great, I didn't know such a game existed. I think my wife would definitely be on board if this game finds its way into the core. 

We were at a pizza joint a while back and tried that Pac-Man Battle Royale. I know that probably won't make it into the core any time soon but it was definitely the center of gaming that day. It's quite fun for 4 players.

**Comment by arcadez2003** [comment]
> 
> 
> No problem, it's on my tinker list for sometime later.
> 
> Right now I just made an additional commit on Cheeky Mouse. The game has good colors now and I added my own lick of madness to the sound triggers. Newer mame updated the dac code a bit. Trying to convert our code to use the newer 8 dac setup was missing some triggers for me. I ended up using a for loop to force the triggers through a single dac instead. This seems to work well, I just need to see if I can backport some of the audio effects possibly.
> 
> Honestly not something I've done yet, if you have any idea how we might be able to splice it in? It doesn't work properly in current mame but I think my single dac method might work better if I can hack in the tones. Here's the commit where the tones got added.
> 
> [mamedev/mame@308c2bb](https://github.com/mamedev/mame/commit/308c2bb72d370ec873d9737ee35c5817d2c90d7f)

I've little experience when it comes to sound cores only having dabbled with a couple of them previously, you'd be
better asking grant2258 TBH

**Comment by mahoneyt944** [comment]
I popped a message to him yesterday. I know it can be done but its not something I've done yet.

I think I'd need to isolate each trigger then splice the individual modifiers in to get the right sound out. Though I'm not sure how portable the code would be, assuming not... I have a suspension we may be able to inject it as hard coded values or some modifier functions.

**Comment by mahoneyt944** [comment]
@arcadez2003 For the hell of it, I made a branch for this. I added the inputs, rom loading, and piggybacked mspacman (which obviously isn't correct) just to see if anything happened. I got this lol:
![mspactwin-210430-063515](https://user-images.githubusercontent.com/49591133/116684397-ebaeb180-a97e-11eb-8a17-8abf8cb634a7.png)

**Comment by arcadez2003** [comment]
CPU related by looks check the original commit there are opcodes to be decrypted

**Comment by mahoneyt944** [comment]
I was just dipping the toes in. I'm going to mess with it more. That was at least a good sign of sorts

**Comment by arcadez2003** [comment]
I seen your latest commits you will need this........

void mspactwin_state::mspactwin_decrypted_map(address_map &map)
{
	map(0x0000, 0x3fff).rom().share("decrypted_opcodes");
	map(0x6000, 0x7fff).rom().share("decrypted_opcodes_mirror");
	map(0x8000, 0xbfff).rom().share("decrypted_opcodes_high");
}

But we cant use "share" a trampoline of sorts will be required check how i got around this in the galaga driver 
and video the code might just be reuseable here, also you might need to add the decrypt call to the rom table

ROM_REGION( 2*0x10000, REGION_CPU1, 0 )	/* 64k for encrypted code */

**Comment by mahoneyt944** [comment]
Should we be in driver init or machine init here?

**Comment by mahoneyt944** [comment]
Also, feel free to add to the branch if you want. I consider the mspactwin branch to be a leisure wip with no real expectations. I plan to throw code at it now and again when I'm bored. Here's a quickie list surely missing stuff:

- the memory maps need fixed up, they are just copied from mspacman as a starting point to separate them. Not checked over at all
- the decode stuff.... may or may not need the mirror op codes
- probably the driver init. Should this be its own machine driver instead?
- rom loading differs in our core. May need to adjust to the way 2003 does it.

**Comment by arcadez2003** [comment]
The game wont boot in my test core if freezes during the rom load screen, likely an xbox issue though
anyway i've went ahead and added some tramps for the decryption and hooked em up via a new memory
map........

[pac.zip](https://github.com/libretro/mame2003-plus-libretro/files/6406282/pac.zip)

**Comment by mahoneyt944** [comment]
It got worse. I think the issue is the differences in rom loading and memory maps. if you look at current mame, they mirror everything where ours looks much different. I also noticed how they share the sprite ram vs our core. maybe we need to hook it up similar to how the sprite ram is? my commit t7, is a crude version that will get the screen i showed above but its very unstable and sometimes just crashes at load.

current
```
	map(0x4ff0, 0x4fff).mirror(0xa000).ram().share("spriteram");
```

2003 read
```
	{ 0x4000, 0x47ff, MRA_RAM },	/* video and color RAM */
	{ 0x4c00, 0x4fff, MRA_RAM },	/* including sprite codes at 4ff0-4fff */
```

2003 write
```
	{ 0x4000, 0x43ff, videoram_w, &videoram, &videoram_size },
	{ 0x4400, 0x47ff, colorram_w, &colorram },
	{ 0x4c00, 0x4fef, MWA_RAM },
	{ 0x4ff0, 0x4fff, MWA_RAM, &spriteram, &spriteram_size },
```

**Comment by mahoneyt944** [comment]
Commit t9 is a tad more stable.

**Comment by arcadez2003** [comment]
The CPU has some encryption it expects to decode it'll check for it and fail to boot without it hence the black screen

**Comment by mahoneyt944** [comment]
Yeah I agree. I pulled it back because the core was just crashing out . Need to look at it more and figure bout why.

**Comment by mahoneyt944** [comment]
Ok so I added the decode back in and tweaked the mem maps. Now it doesn't boot. :( The log shows this below, must be missing something.
```
[MAME 2003+] Error: video_start_generic() called but videoram_size not initialized
[MAME 2003+] Unable to start video emulation
[CONTENT LOAD]: Failed to load content
```

**Comment by arcadez2003** [comment]
if you enable the decode you must add the decrypt call directly to the romtable........

ROM_START( mspactwin )
	ROM_REGION( 2*0x20000, REGION_CPU1, 0 )	/* 64k for encrypted code */

Of course it was a quick paste job using a similar a hookup akin to Galaga this might be incorrect for this game.

BTW look at this you'd need a mirror and a share trampoline map(0x4ff0, 0x4fff).mirror(0xa000).ram().share("spriteram");

**Comment by mahoneyt944** [comment]
The old mem map uses this, not sure if it's accurate or not
```
{ 0xc000, 0xc3ff, videoram_w }, /* mirror address for video ram, */
```

**Comment by mahoneyt944** [comment]
I plugged in this as you wrote above:
```
ROM_START( mspactwin )
ROM_REGION( 20x20000, REGION_CPU1, 0 ) / 64k for encrypted code */
```
20*0x20000 correct?

**Comment by arcadez2003** [comment]
Nah for some reason i keep posting 2* uppercase on 8 you know the symbol i mean but on here it reads back 
as 20

**Comment by arcadez2003** [comment]
I've changed a few things around as per comparing the mspactwin mem map vs mspacman plus added in the
videoram call for mspactwin it's same as videoram_w with an extra scanline update, i then disabled the MACHINE_INIT
call as that has opcodes and decryption for mspacman which im thinking mspactwin does not use as it has it's own
decryption and finally i added a new interrupt for mspactwin as im thinking the one is used previously is full of speed up
cheats which again im not sure the game would use.

[pacman.zip](https://github.com/libretro/mame2003-plus-libretro/files/6430069/pacman.zip)

Here is the file it still wont boot for me, im thinking im gonna port this to my MAME84 core where i can
use the AM_SHARE call to rule out a problem with the decryption trampolines we're trying to use here

**Comment by mahoneyt944** [comment]
Yeah I thought the same thing on the init which I tried in earlier commits. Wasn't sure so I put it back in.

**Comment by mahoneyt944** [comment]
@arcadez2003 try my last commit. "test2" it boots and now has some more going on than the still image of before. Definitely a decode issue. it doesn't like how its mapped. It also has a tone melody which is funny lol.

**Comment by arcadez2003** [comment]
Nah it crashes on the loading screen in MAME84 if i disable the decryption if i dont then it loads to 
unable to start video emulation error mirroring likely i'll look at it someone tomorrow if i have the time

**Comment by mahoneyt944** [comment]
With the commit I have here (disabled the decryption mapping in the machine driver and commented out the driver init entirely. It loads, and flashes through a few screens and plays tones in a endless loop.

**Comment by arcadez2003** [comment]
Well it's progress eh LOL

**Comment by mahoneyt944** [comment]
here's a clip of it:
https://user-images.githubusercontent.com/49591133/117216484-d813a880-adcd-11eb-8182-018250145b0f.mp4

**Comment by arcadez2003** [comment]
Bit late here for testing but humour me try this as the mem map does seem closer to pacman than mspacman

MDRV_CPU_MEMORY(readmem, writemem)

**Comment by mahoneyt944** [comment]
> Bit late here for testing but humour me try this as the mem map does seem closer to pacman than mspacman
> 
> MDRV_CPU_MEMORY(readmem, writemem)

I'll try swapping the map

**Comment by mahoneyt944** [comment]
Update. Pacman map had no effect. Though maybe we need to hook up the decryption as a port instead? Like mschamp_readport is. I'll try.

**Comment by mahoneyt944** [comment]
This mirror should be mspactwin_videoram_w too correct?

```
{ 0xc000, 0xc3ff, mspactwin_videoram_w }, /* mirror address for video ram, */
```

**Comment by mahoneyt944** [comment]
Fixed the gfx decode

**Comment by mahoneyt944** [comment]
Ok game is working, need to fix inputs still

**Comment by arcadez2003** [comment]
You can always flip the screen via the ROT call to save you some time

**Comment by arcadez2003** [comment]
@mahoneyt944 looking at the tile flipping i dont see any difference here other than the hookup
to the memory map via the state call............

WRITE_LINE_MEMBER(pacman_state::flipscreen_w)
{
	m_flipscreen = state;
	m_bg_tilemap->set_flip(m_flipscreen * ( TILEMAP_FLIPX + TILEMAP_FLIPY ) );
}

WRITE_LINE_MEMBER(mspactwin_state::flipscreen_w)
{
	m_flipscreen = state;
	m_bg_tilemap->set_flip(m_flipscreen * ( TILEMAP_FLIPX + TILEMAP_FLIPY ) );
//	logerror("Flip: %02x\n", state);
}

After the driver conversion to tilemapping circa MAME90.u4 this would equate to 

WRITE8_HANDLER( pacman_flipscreen_w )
{
	if (flipscreen != (data & 1))
	{
		flipscreen = data & 1;
		tilemap_set_flip( tilemap, flipscreen * ( TILEMAP_FLIPX + TILEMAP_FLIPY ) );
	}
}

Will the game not be fine with our non tilemap based flipping method.??

WRITE_HANDLER( pengo_flipscreen_w )
{
	if (flipscreen != (data & 1))
	{
		flipscreen = data & 1;
		memset(dirtybuffer,1,videoram_size);
	}
}

**Comment by mahoneyt944** [comment]
Never looked into it yet. I moved it to vidhrdw commented out. If it's the same as what we have just use the pengo flip and remove the commented out one. Whatever's most proper.

**Comment by mahoneyt944** [comment]
now working.

**Comment by mahoneyt944** [comment]
Also good call on the inputs
