### ISSUE TITLE
[orunners] input mapping problem

### ISSUE THREAD

**Issue by mickagame** [libretro/mame2003-plus-libretro#985]
In the game i can accelerate with the button R of the retropad.
When i go in quick menu => controls => port 1 control the button R is assigned to anything : "---"
How is possible ???
This is like the acceleration button can't be acceded through the input menu.
Because of this i can't remap the button.

**Comment by mahoneyt944** [comment]
This cores inputs are not fully integrated with retroarch, you'll need to use the mame menu to remap the input.

You can use the quick menu -> options -> display mame menu -> toggle on, to open the mame menu then select "input this game". Now you can remap the input you need. I believe this is pedal for player 1.

**Comment by mickagame** [comment]
Thanks for the reply. I remap button in retroarch menu for street fighter 2 and it worked. So this integration does not work with all games? After doing the remap in mame menu it works :-)

**Comment by mahoneyt944** [comment]
Analog inputs are not fully integrated yet with Retroarch. Most of the common inputs -- up, down, left, right, start, select, a, b, x, y are supported and can be remapped in Retroarch. 

I would recommend remapping inputs through the mame menu for the best user experience.

**Comment by mickagame** [comment]
Thank you very much. mame2010/mame2015 core have better integration of this type of input?
Anyway remapping through mame works very well

**Comment by mahoneyt944** [comment]
Can't say for sure as I don't work on those cores but probably not. Mame inputs are very diverse compared to typical console emulation where there's a standard to the controls. For example if you were emulating sega, there's only so many inputs sega recognizes so it easy to cover them all. Mame covers thousands of arcade machines made by multiple different companies. There really wasn't a standard on how many or what kind of inputs each machine would use.
