### ISSUE TITLE
Several games are crashing

### ISSUE THREAD

**Issue by Wilstorm** [libretro/mame2003-plus-libretro#989]
@mahoneyt944 - I updated the core and deleted all my cfg, nvram and .hi files to test the new cfg options you implemented but it seems *all* games are crashing that I tried (but the same games run fine on mame2003). 

I am using RetroPie on an old stretch version on a Pi 3 and mame2003-plus current in the past hour or so. I can't get into a game to get you the specific version but I was able to get a verbose log. 

I'm sorry I don't have more info or time to troubleshoot as we are heading up to Minneapolis but I wanted to at least get something out there if it's a core issue or I think you guys have been troubleshooting some issues that might just be it but it might be my setup too. Verbose log from RetroPie:

```
Parameters: 
Executing: /opt/retropie/emulators/retroarch/bin/retroarch -L /opt/retropie/libretrocores/lr-mame2003-plus/mame2003_plus_libretro.so --config /opt/retropie/configs/arcade/retroarch.cfg "/home/pi/RetroPie/roms/arcade/dkong3.zip" --verbose --appendconfig /dev/shm/retroarch.cfg'|'"/home/pi/RetroPie/roms/arcade/dkong3.zip.cfg"
[INFO] RetroArch 1.8.8 (Git 9552f87)
[INFO] Redirecting save file to "/home/pi/RetroPie/roms/arcade/dkong3.srm".
[INFO] Redirecting save state to "/home/pi/RetroPie/roms/arcade/dkong3.state".
[INFO] === Build =======================================
[INFO] Capabilities:  NEON VFPv3 VFPv4
[INFO] Built: Dec 29 2020
[INFO] Version: 1.8.8
[INFO] Git: 9552f87
[INFO] =================================================
[INFO] Loading dynamic libretro core from: "/opt/retropie/libretrocores/lr-mame2003-plus/mame2003_plus_libretro.so"
[ERROR] Failed to open libretro core: "/opt/retropie/libretrocores/lr-mame2003-plus/mame2003_plus_libretro.so"
Error(s): /opt/retropie/libretrocores/lr-mame2003-plus/mame2003_plus_libretro.so: undefined symbol: driver_plegends
[INFO] Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[INFO] Unloading game..
[INFO] Unloading core..
[INFO] Unloading core symbols..
```

**Comment by mahoneyt944** [comment]
You probably downloaded a bad build, arcadez was making test drivers to help another user and one had a bad build.

**Comment by mahoneyt944** [comment]
Just reinstall from source and you'll be good.

**Comment by Wilstorm** [comment]
@mahoneyt944 - Ok, that sounds good. I know Arcadez was working his magic yesterday so I wasn't to worried. I'll give it go next week when we get home. I have a broken core and no cfgs I need to get working but first we need check out this riot situation up here! ;)
